In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
df = pd.read_csv("Data/Data2.csv")
df.head()

,Season,Year,Month,Day,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Pos,Pld,W,D,L,GF,GA,GD,Pts,Qualification or relegation
0,9394,1993,8,14,West Ham,Wimbledon,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,42.0,13.0,17.0,12.0,47.0,48.0,-1.0,56.0,Not Applicable
1,9394,1993,8,14,Southampton,Everton,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,42.0,12.0,12.0,18.0,49.0,57.0,-8.0,48.0,Not Applicable
2,9394,1993,8,14,Sheffield,Swindon,3,1,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,42.0,13.0,5.0,24.0,43.0,60.0,-17.0,44.0,Relegation to the Football League First Division
3,9394,1993,8,14,Oldham,Ipswich,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,42.0,9.0,16.0,17.0,42.0,56.0,-14.0,43.0,Relegation to the Football League First Division
4,9394,1993,8,14,Newcastle,Tottenham,0,1,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,42.0,23.0,8.0,11.0,82.0,41.0,41.0,77.0,Qualification for the UEFA Cup first round

In [97]:
df2 = pd.read_csv("ExtraData/matches.csv")
df2.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,opponent,xg,xga,poss,attendance,captain,formation,referee,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,0,2020-09-21,20:15 (21:15),Premier League,Matchweek 2,Mon,Away,W,3,1,Wolves,1.9,0.6,65,NaN,Fernandinho,4-2-3-1,Andre Marriner,Match Report,NaN,13,8,21.1,2,1,1,2024,Manchester City
1,2,2020-09-27,16:30 (17:30),Premier League,Matchweek 3,Sun,Home,L,2,5,Leicester City,0.9,2.9,72,NaN,Fernandinho,4-2-3-1,Michael Oliver,Match Report,NaN,16,5,19.8,1,0,0,2024,Manchester City
2,4,2020-10-03,17:30 (18:30),Premier League,Matchweek 4,Sat,Away,D,1,1,Leeds United,1.2,2.4,49,NaN,Kevin De Bruyne,4-3-3,Mike Dean,Match Report,NaN,23,1,18.2,1,0,0,2024,Manchester City
3,5,2020-10-17,17:30 (18:30),Premier League,Matchweek 5,Sat,Home,W,1,0,Arsenal,1.3,0.9,58,NaN,Raheem Sterling,3-1-4-2,Chris Kavanagh,Match Report,NaN,13,5,17.7,0,0,0,2024,Manchester City
4,7,2020-10-24,12:30 (13:30),Premier League,Matchweek 6,Sat,Away,D,1,1,West Ham,1.0,0.3,69,NaN,Raheem Sterling,4-3-3,Anthony Taylor,Match Report,NaN,14,7,20.9,1,0,0,2024,Manchester City

In [98]:
df2[ df2['comp'] == 'Premier League' ]['team'].nunique()

26

In [99]:
df2[ df2['comp'] == 'Premier League' ]['team'].unique()

array(['Manchester City', 'Manchester United', 'Liverpool', 'Chelsea',
       'Leicester City', 'West Ham United', 'Tottenham Hotspur',
       'Arsenal', 'Leeds United', 'Everton', 'Aston Villa',
       'Newcastle United', 'Wolverhampton Wanderers', 'Crystal Palace',
       'Southampton', 'Brighton and Hove Albion', 'Burnley', 'Fulham',
       'West Bromwich Albion', 'Sheffield United', 'Bournemouth',
       'Brentford', 'Nottingham Forest', 'Luton Town', 'Watford',
       'Norwich City'], dtype=object)

In [100]:
df2 = df2[ df2['comp'] == 'Premier League']

In [101]:
team_mapping = {
    'Brighton & Hove Albion': 'Brighton',
    'Luton Town': 'Luton',
    'Leeds United': 'Leeds',
    'Leicester City': 'Leicester',
    'Manchester City': 'Man City',
    'Manchester United': 'Man United',
    'Newcastle United': 'Newcastle',
    'Norwich City': 'Norwich',
    'Nottingham Forest': 'Nottingham',
    'Sheffield United': 'Sheffield',
    'Tottenham Hotspur': 'Tottenham',
    'West Bromwich Albion': 'West Brom',
    'West Ham United': 'West Ham',
    'Wolverhampton Wanderers': 'Wolves'
}

In [102]:
df2['team'] = df2['team'].replace(team_mapping)

In [103]:
df2['date'] = pd.to_datetime(df2['date'])

df2['Year'] = df2['date'].dt.year
df2['Month'] = df2['date'].dt.month
df2['Day'] = df2['date'].dt.day

In [104]:
df2['time'] = df2['time'].str.replace(r'\s*\(.*\)', '', regex=True).str.strip()

In [105]:
df2.drop('comp', axis=1, inplace=True)

In [106]:
df2.head()

,Unnamed: 0,date,time,round,day,venue,result,gf,ga,opponent,xg,xga,poss,attendance,captain,formation,referee,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team,Year,Month,Day
0,0,2020-09-21,20:15,Matchweek 2,Mon,Away,W,3,1,Wolves,1.9,0.6,65,NaN,Fernandinho,4-2-3-1,Andre Marriner,Match Report,NaN,13,8,21.1,2,1,1,2024,Man City,2020,9,21
1,2,2020-09-27,16:30,Matchweek 3,Sun,Home,L,2,5,Leicester City,0.9,2.9,72,NaN,Fernandinho,4-2-3-1,Michael Oliver,Match Report,NaN,16,5,19.8,1,0,0,2024,Man City,2020,9,27
2,4,2020-10-03,17:30,Matchweek 4,Sat,Away,D,1,1,Leeds United,1.2,2.4,49,NaN,Kevin De Bruyne,4-3-3,Mike Dean,Match Report,NaN,23,1,18.2,1,0,0,2024,Man City,2020,10,3
3,5,2020-10-17,17:30,Matchweek 5,Sat,Home,W,1,0,Arsenal,1.3,0.9,58,NaN,Raheem Sterling,3-1-4-2,Chris Kavanagh,Match Report,NaN,13,5,17.7,0,0,0,2024,Man City,2020,10,17
4,7,2020-10-24,12:30,Matchweek 6,Sat,Away,D,1,1,West Ham,1.0,0.3,69,NaN,Raheem Sterling,4-3-3,Anthony Taylor,Match Report,NaN,14,7,20.9,1,0,0,2024,Man City,2020,10,24

In [107]:
df2['round'] = df2['round'].str.extract(r'(\d+)').astype(int)

In [108]:
def swap_teams(row):
    if row['venue'] == 'Home':
        row['opponent'], row['team'] = row['team'], row['opponent']
    return row

df2 = df2.apply(swap_teams, axis=1)

In [109]:
def swap_teams_goals(row):
    if row['venue'] == 'Away':
        row['gf'], row['ga'] = row['ga'], row['gf']
    return row

df2 = df2.apply(swap_teams_goals, axis=1)

In [110]:
df2 = df2.rename(columns={'opponent': 'Team1', 'team': 'Team2'})

In [111]:
df2 = df2.rename(columns={'gf': 'GoalHome', 'ga': 'GoalAway'})

In [112]:
df2 = df2.rename(columns={'xg': 'XGHome', 'xga': 'XGAway'})

In [113]:
def check_possession(row):
    if row['venue'] == 'Away':
        row['poss'] = 100 - row['poss']
    return row
    
df2 = df2.apply(check_possession, axis=1)

In [114]:
df2 = df2.rename(columns={'poss': 'PossessionHome'})

In [115]:
df2[ ( (df2['Team1'] == 'Man City') & (df2['Team2'] == 'Wolves') ) | ( (df2['Team1'] == 'Wolves') & (df2['Team2'] == 'Man City') )]

,Unnamed: 0,date,time,round,day,venue,result,GoalHome,GoalAway,Team1,XGHome,XGAway,PossessionHome,attendance,captain,formation,referee,match report,notes,sh,sot,dist,fk,pk,pkatt,season,Team2,Year,Month,Day
0,0,2020-09-21,20:15,2,Mon,Away,W,1,3,Wolves,1.9,0.6,35,NaN,Fernandinho,4-2-3-1,Andre Marriner,Match Report,NaN,13,8,21.1,2,1,1,2024,Man City,2020,9,21
26,44,2021-03-02,20:00,29,Tue,Home,W,4,1,Man City,3.3,0.3,72,NaN,Kevin De Bruyne,4-3-3,Chris Kavanagh,Match Report,NaN,22,10,14.6,0,0,0,2024,Wolves,2021,3,2
805,11,2019-10-06,14:00,8,Sun,Home,L,0,2,Man City,1.4,1.0,75,54435.0,David Silva,4-2-3-1,Craig Pawson,Match Report,NaN,18,2,18.7,2,0,0,2023,Wolves,2019,10,6
816,32,2019-12-27,19:45,19,Fri,Away,L,3,2,Wolves,1.5,2.6,62,31737.0,Fernandinho,4-2-3-1,Martin Atkinson,Match Report,NaN,6,2,19.0,1,0,1,2023,Man City,2019,12,27
994,10,2023-09-30,15:00,7,Sat,Away,L,2,1,Wolves,0.9,0.4,32,31415.0,Kyle Walker,4-2-3-1,Craig Pawson,Match Report,NaN,23,8,19.3,1,0,0,2024,Man City,2023,9,30
1022,56,2024-05-04,17:30,36,Sat,Home,W,5,1,Man City,3.7,0.3,58,52439.0,Kyle Walker,4-2-3-1,Craig Pawson,Match Report,NaN,18,10,15.3,0,2,2,2024,Wolves,2024,5,4
1754,130,2022-09-17,12:30,8,Sat,Away,W,0,3,Wolves,1.1,0.4,41,31578.0,Kevin De Bruyne,4-3-3,Anthony Taylor,Match Report,NaN,16,7,19.4,0,0,0,2023,Man City,2022,9,17
1767,151,2023-01-22,14:00,21,Sun,Home,W,3,0,Man City,2.8,0.8,55,53282.0,İlkay Gündoğan,3-2-4-1,David Coote,Match Report,NaN,12,5,14.8,0,1,1,2023,Wolves,2023,1,22
2523,124,2021-12-11,12:30,16,Sat,Home,W,1,0,Man City,3.2,0.2,71,52613.0,İlkay Gündoğan,4-3-3,Jonathan Moss,Match Report,NaN,23,8,15.7,0,1,1,2022,Wolves,2021,12,11
2543,155,2022-05-11,20:15,33,Wed,Away,W,1,5,Wolves,2.3,0.5,34,32000.0,Fernandinho,4-2-3-1,Martin Atkinson,Match Report,NaN,15,5,14.7,0,0,0,2022,Man City,2022,5,11
3268,0,2020-09-21,20:15,2,Mon,Away,W,1,3,Wolves,1.9,0.6,35,NaN,Fernandinho,4-2-3-1,Andre Marriner,Match Report,NaN,13,8,21.1,2,1,1,2021,Man City,2020,9,21
3294,161,2021-03-02,20:00,29,Tue,Home,W,4,1,Man City,3.3,0.3,72,NaN,Kevin De Bruyne,4-3-3,Chris Kavanagh,Match Report,NaN,22,10,14.6,0,0,0,2021,Wolves,2021,3,2
4073,111,2019-10-06,14:00,8,Sun,Home,L,0,2,Man City,1.4,1.0,75,54435.0,David Silva,4-2-3-1,Craig Pawson,Match Report,NaN,18,2,18.7,2,0,0,2020,Wolves,2019,10,6
4084,128,2019-12-27,19:45,19,Fri,Away,L,3,2,Wolves,1.5,2.6,62,31737.0,Fernandinho,4-2-3-1,Martin Atkinson,Match Report,NaN,6,2,19.0,1,0,1,2020,Man City,2019,12,27

In [116]:
df2.drop(columns={'formation', 'captain', 'match report', 'notes'}, inplace=True)

In [117]:
df2.drop(columns={'Unnamed: 0'}, inplace=True)

In [118]:
df2.drop(columns={'date'}, inplace=True)

---

In [119]:
df.head()

,Season,Year,Month,Day,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Pos,Pld,W,D,L,GF,GA,GD,Pts,Qualification or relegation
0,9394,1993,8,14,West Ham,Wimbledon,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,42.0,13.0,17.0,12.0,47.0,48.0,-1.0,56.0,Not Applicable
1,9394,1993,8,14,Southampton,Everton,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,42.0,12.0,12.0,18.0,49.0,57.0,-8.0,48.0,Not Applicable
2,9394,1993,8,14,Sheffield,Swindon,3,1,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,42.0,13.0,5.0,24.0,43.0,60.0,-17.0,44.0,Relegation to the Football League First Division
3,9394,1993,8,14,Oldham,Ipswich,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,42.0,9.0,16.0,17.0,42.0,56.0,-14.0,43.0,Relegation to the Football League First Division
4,9394,1993,8,14,Newcastle,Tottenham,0,1,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,42.0,23.0,8.0,11.0,82.0,41.0,41.0,77.0,Qualification for the UEFA Cup first round

In [120]:
df.isna().sum()[df.isna().sum() > 0]

HTHG        924
HTAG        924
HTR         924
Referee    2824
HS         2824
AS         2824
HST        2824
AST        2824
HF         2824
AF         2824
HC         2824
AC         2824
HY         2824
AY         2824
HR         2824
AR         2824
dtype: int64

In [121]:
df2.head(10)

,time,round,day,venue,result,GoalHome,GoalAway,Team1,XGHome,XGAway,PossessionHome,attendance,referee,sh,sot,dist,fk,pk,pkatt,season,Team2,Year,Month,Day
0,20:15,2,Mon,Away,W,1,3,Wolves,1.9,0.6,35,NaN,Andre Marriner,13,8,21.1,2,1,1,2024,Man City,2020,9,21
1,16:30,3,Sun,Home,L,2,5,Man City,0.9,2.9,72,NaN,Michael Oliver,16,5,19.8,1,0,0,2024,Leicester City,2020,9,27
2,17:30,4,Sat,Away,D,1,1,Leeds United,1.2,2.4,51,NaN,Mike Dean,23,1,18.2,1,0,0,2024,Man City,2020,10,3
3,17:30,5,Sat,Home,W,1,0,Man City,1.3,0.9,58,NaN,Chris Kavanagh,13,5,17.7,0,0,0,2024,Arsenal,2020,10,17
4,12:30,6,Sat,Away,D,1,1,West Ham,1.0,0.3,31,NaN,Anthony Taylor,14,7,20.9,1,0,0,2024,Man City,2020,10,24
5,12:30,7,Sat,Away,W,0,1,Sheffield Utd,1.6,0.5,35,NaN,Michael Oliver,16,8,18.5,2,0,0,2024,Man City,2020,10,31
6,16:30,8,Sun,Home,D,1,1,Man City,1.4,1.2,54,NaN,Craig Pawson,6,2,20.6,0,0,1,2024,Liverpool,2020,11,8
7,17:30,9,Sat,Away,L,2,0,Tottenham,1.4,0.7,34,NaN,Mike Dean,22,5,16.0,0,0,0,2024,Man City,2020,11,21
8,15:00,10,Sat,Home,W,5,0,Man City,1.7,0.5,68,NaN,Lee Mason,19,6,16.4,0,0,0,2024,Burnley,2020,11,28
9,15:00,11,Sat,Home,W,2,0,Man City,2.9,0.3,69,NaN,Jonathan Moss,14,4,15.9,0,1,1,2024,Fulham,2020,12,5

In [122]:
df[ (df['Year'] == 2020) & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Man City') ]

,Season,Year,Month,Day,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Pos,Pld,W,D,L,GF,GA,GD,Pts,Qualification or relegation
10475,2021,2020,10,24,West Ham,Man City,1,1,D,1.0,0.0,H,A Taylor,6.0,14.0,2.0,7.0,14.0,6.0,2.0,10.0,2.0,0.0,0.0,0.0,6.0,38.0,19.0,8.0,11.0,62.0,47.0,15.0,65.0,Qualification for the Europa League group stag...

In [123]:
df.isna().sum()[df.isna().sum() > 0]

HTHG        924
HTAG        924
HTR         924
Referee    2824
HS         2824
AS         2824
HST        2824
AST        2824
HF         2824
AF         2824
HC         2824
AC         2824
HY         2824
AY         2824
HR         2824
AR         2824
dtype: int64

In [124]:
df.head()

,Season,Year,Month,Day,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Pos,Pld,W,D,L,GF,GA,GD,Pts,Qualification or relegation
0,9394,1993,8,14,West Ham,Wimbledon,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,42.0,13.0,17.0,12.0,47.0,48.0,-1.0,56.0,Not Applicable
1,9394,1993,8,14,Southampton,Everton,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,42.0,12.0,12.0,18.0,49.0,57.0,-8.0,48.0,Not Applicable
2,9394,1993,8,14,Sheffield,Swindon,3,1,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,42.0,13.0,5.0,24.0,43.0,60.0,-17.0,44.0,Relegation to the Football League First Division
3,9394,1993,8,14,Oldham,Ipswich,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,42.0,9.0,16.0,17.0,42.0,56.0,-14.0,43.0,Relegation to the Football League First Division
4,9394,1993,8,14,Newcastle,Tottenham,0,1,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,42.0,23.0,8.0,11.0,82.0,41.0,41.0,77.0,Qualification for the UEFA Cup first round

In [130]:
df['match_key'] = df['HomeTeam'] + '_' + df['AwayTeam'] + '_' + df['Year'].astype(str) + '_' + df['Month'].astype(str) + '_' + df['Day'].astype(str)
df2['match_key'] = df2['Team1'] + '_' + df2['Team2'] + '_' + df2['Year'].astype(str) + '_' + df2['Month'].astype(str) + '_' + df2['Day'].astype(str)

In [131]:
columns_to_add = ['referee', 'time', 'round', 'day', 'XGHome', 'XGAway', 'PossessionHome', 'attendance']
existing_columns = [col for col in columns_to_add if col in df2.columns]

df_merged = df.merge(df2[['match_key'] + existing_columns], 
                     on='match_key', 
                     how='left', 
                     suffixes=('', '_df2'))

In [136]:
df['Referee'] = df['Referee'].fillna(df_merged['referee'])

for col in existing_columns:
    if col != 'referee':
        df[col] = df_merged[col + '_df2'] if col + '_df2' in df_merged.columns else df_merged[col]

if 'day' in df.columns:
    df = df.rename(columns={'day': 'WeekDay'})

df = df.drop([col for col in df.columns if col.endswith('_df2')], axis=1)

In [137]:
df.head()

,Season,Year,Month,Day,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Pos,Pld,W,D,L,GF,GA,GD,Pts,Qualification or relegation,match_key,time,round,WeekDay,XGHome,XGAway,PossessionHome,attendance
0,9394,1993,8,14,West Ham,Wimbledon,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,42.0,13.0,17.0,12.0,47.0,48.0,-1.0,56.0,Not Applicable,West Ham_Wimbledon_1993_8_14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9394,1993,8,14,Southampton,Everton,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,42.0,12.0,12.0,18.0,49.0,57.0,-8.0,48.0,Not Applicable,Southampton_Everton_1993_8_14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9394,1993,8,14,Sheffield,Swindon,3,1,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,42.0,13.0,5.0,24.0,43.0,60.0,-17.0,44.0,Relegation to the Football League First Division,Sheffield_Swindon_1993_8_14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9394,1993,8,14,Oldham,Ipswich,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,42.0,9.0,16.0,17.0,42.0,56.0,-14.0,43.0,Relegation to the Football League First Division,Oldham_Ipswich_1993_8_14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9394,1993,8,14,Newcastle,Tottenham,0,1,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,42.0,23.0,8.0,11.0,82.0,41.0,41.0,77.0,Qualification for the UEFA Cup first round,Newcastle_Tottenham_1993_8_14,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [140]:
df.tail()

,Season,Year,Month,Day,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Pos,Pld,W,D,L,GF,GA,GD,Pts,Qualification or relegation,match_key,time,round,WeekDay,XGHome,XGAway,PossessionHome,attendance
12699,2526,2026,5,24,Crystal Palace,Arsenal,1,2,A,0.0,1.0,A,F Hallam,8.0,17.0,3.0,7.0,9.0,12.0,3.0,4.0,0.0,1.0,0.0,0.0,15.0,38.0,11.0,12.0,15.0,41.0,51.0,-10.0,45.0,Not Applicable,Crystal Palace_Arsenal_2026_5_24,17:30,28.0,Sat,1.2,2.3,68.0,40025.0
12700,2526,2026,5,24,Burnley,Wolves,1,1,D,0.0,1.0,A,A Kitchen,16.0,16.0,8.0,4.0,10.0,11.0,7.0,7.0,2.0,2.0,0.0,0.0,19.0,38.0,4.0,10.0,24.0,38.0,75.0,-37.0,22.0,Relegation to the EFL Championship,Burnley_Wolves_2026_5_24,15:00,28.0,Sat,3.5,1.3,56.0,41021.0
12701,2526,2026,5,24,Brighton,Man United,0,3,A,0.0,2.0,A,S Barrott,13.0,11.0,2.0,7.0,11.0,8.0,0.0,3.0,0.0,1.0,0.0,0.0,8.0,38.0,14.0,11.0,13.0,52.0,46.0,6.0,53.0,Qualification for the Europa Conference League...,Brighton_Man United_2026_5_24,15:00,28.0,Sat,1.3,3.5,56.0,41021.0
12702,2526,2026,5,24,Fulham,Newcastle,2,0,H,1.0,0.0,H,R Jones,21.0,7.0,6.0,2.0,13.0,6.0,6.0,6.0,2.0,2.0,0.0,0.0,11.0,38.0,15.0,7.0,16.0,47.0,51.0,-4.0,52.0,Not Applicable,Fulham_Newcastle_2026_5_24,15:00,28.0,Sat,1.3,0.6,53.0,17006.0
12703,2526,2026,5,24,Tottenham,Everton,1,0,H,1.0,0.0,H,M Oliver,21.0,8.0,6.0,3.0,15.0,12.0,6.0,2.0,5.0,3.0,0.0,1.0,17.0,38.0,10.0,11.0,17.0,48.0,57.0,-9.0,41.0,Not Applicable,Tottenham_Everton_2026_5_24,14:00,28.0,Sun,1.6,0.8,62.0,60247.0

In [142]:
new_columns_order = {
    'Season': 'Season',
    'Year': 'Year',
    'Month': 'Month',
    'Day': 'Day',
    'WeekDay': 'WeekDay',
    'time': 'Time',
    'round': 'Round',
    'HomeTeam': 'HomeTeam',
    'AwayTeam': 'AwayTeam',
    'FTHG': 'HomeGoal',
    'FTAG': 'AwayGoal',
    'FTR': 'Result',
    'HTHG': 'HomeGoal-HalfTime',
    'HTAG': 'AwayGoal-HalfTime',
    'HTR': 'Result-HalfTime',
    'attendance': 'Attendance',
    'Referee': 'Referee',
    'HS': 'HomeShot',
    'AS': 'AwayShot',
    'HST': 'HomeOnTargetShot',
    'AST': 'AwayOnTargetShot',
    'HF': 'HomeFoul',
    'AF': 'AwayFoul',
    'HC': 'HomeCorner',
    'AC': 'AwayCorner',
    'HY': 'HomeYellow',
    'AY': 'AwayYellow',
    'HR': 'HomeRed',
    'AR': 'AwayRed',
    'XGHome': 'XGHome',
    'XGAway': 'XGAway',
    'Pos': 'SeasonPosHome',
    'Pld': 'SeasonPlayedHome',
    'W': 'SeasonWinHome',
    'D': 'SeasonDrawHome',
    'L': 'SeasonLossHome',
    'GF': 'SeasonGFHome',
    'GA': 'SeasonGAHome',
    'GD': 'SeasonGDHome',
    'Pts': 'SeasonPointsHome',
    'Qualification or relegation': 'QualificationOrRelegationHome'
}

In [143]:
df = df.rename(columns=new_columns_order)

new_order = list(new_columns_order.values())
df = df[new_order]

In [144]:
df.head()

,Season,Year,Month,Day,WeekDay,Time,Round,HomeTeam,AwayTeam,HomeGoal,AwayGoal,Result,HomeGoal-HalfTime,AwayGoal-HalfTime,Result-HalfTime,Attendance,Referee,HomeShot,AwayShot,HomeOnTargetShot,AwayOnTargetShot,HomeFoul,AwayFoul,HomeCorner,AwayCorner,HomeYellow,AwayYellow,HomeRed,AwayRed,XGHome,XGAway,SeasonPosHome,SeasonPlayedHome,SeasonWinHome,SeasonDrawHome,SeasonLossHome,SeasonGFHome,SeasonGAHome,SeasonGDHome,SeasonPointsHome,QualificationOrRelegationHome
0,9394,1993,8,14,NaN,NaN,NaN,West Ham,Wimbledon,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,42.0,13.0,17.0,12.0,47.0,48.0,-1.0,56.0,Not Applicable
1,9394,1993,8,14,NaN,NaN,NaN,Southampton,Everton,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,42.0,12.0,12.0,18.0,49.0,57.0,-8.0,48.0,Not Applicable
2,9394,1993,8,14,NaN,NaN,NaN,Sheffield,Swindon,3,1,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,42.0,13.0,5.0,24.0,43.0,60.0,-17.0,44.0,Relegation to the Football League First Division
3,9394,1993,8,14,NaN,NaN,NaN,Oldham,Ipswich,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,42.0,9.0,16.0,17.0,42.0,56.0,-14.0,43.0,Relegation to the Football League First Division
4,9394,1993,8,14,NaN,NaN,NaN,Newcastle,Tottenham,0,1,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,42.0,23.0,8.0,11.0,82.0,41.0,41.0,77.0,Qualification for the UEFA Cup first round

In [ ]:
df.shape

(12704, 41)

In [146]:
df.to_csv("Data/Data3.csv", index=False)

---

In [147]:
df1 = pd.read_csv("ExtraData/EPL Standings 2000-2022.csv")
df1.head()

,Season,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification or relegation
0,2000-01,1,Manchester United,38,24,8,6,79,31,48,80,Qualification for the Champions League first g...
1,2000-01,2,Arsenal,38,20,10,8,63,38,25,70,Qualification for the Champions League first g...
2,2000-01,3,Liverpool,38,20,9,9,71,39,32,69,Qualification for the Champions League third q...
3,2000-01,4,Leeds United,38,20,8,10,64,43,21,68,Qualification for the UEFA Cup first round[a]
4,2000-01,5,Ipswich Town,38,20,6,12,57,42,15,66,Qualification for the UEFA Cup first round[a]

In [148]:
df1[['year1', 'year2']] = df1['Season'].str.split('-', expand=True)
df1['Season'] = df1['year1'].str[-2:] + df1['year2']
df1 = df1.drop(columns=['year1', 'year2'])
df1.head()

,Season,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification or relegation
0,0001,1,Manchester United,38,24,8,6,79,31,48,80,Qualification for the Champions League first g...
1,0001,2,Arsenal,38,20,10,8,63,38,25,70,Qualification for the Champions League first g...
2,0001,3,Liverpool,38,20,9,9,71,39,32,69,Qualification for the Champions League third q...
3,0001,4,Leeds United,38,20,8,10,64,43,21,68,Qualification for the UEFA Cup first round[a]
4,0001,5,Ipswich Town,38,20,6,12,57,42,15,66,Qualification for the UEFA Cup first round[a]

In [149]:
df1['Season'] = df1['Season'].astype(str)

In [ ]:
records_9900 = [
    {'Season': '9900', 'Pos': 1, 'Team': 'Man United', 'Pld': 38, 'W': 28, 'D': 7, 'L': 3, 'GF': 97, 'GA': 45, 'GD': 52, 'Pts': 91, 'Qualification or relegation': 'Qualification for the Champions League first group stage'},
    {'Season': '9900', 'Pos': 2, 'Team': 'Arsenal', 'Pld': 38, 'W': 22, 'D': 7, 'L': 9, 'GF': 73, 'GA': 43, 'GD': 30, 'Pts': 73, 'Qualification or relegation': 'Qualification for the Champions League first group stage'},
    {'Season': '9900', 'Pos': 3, 'Team': 'Liverpool', 'Pld': 38, 'W': 21, 'D': 6, 'L': 11, 'GF': 58, 'GA': 43, 'GD': 15, 'Pts': 69, 'Qualification or relegation': 'Qualification for the Champions League third qualifying round'},
    {'Season': '9900', 'Pos': 4, 'Team': 'Chelsea', 'Pld': 38, 'W': 19, 'D': 10, 'L': 9, 'GF': 51, 'GA': 30, 'GD': 21, 'Pts': 67, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9900', 'Pos': 5, 'Team': 'Leeds', 'Pld': 38, 'W': 18, 'D': 11, 'L': 9, 'GF': 53, 'GA': 34, 'GD': 19, 'Pts': 65, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9900', 'Pos': 6, 'Team': 'Aston Villa', 'Pld': 38, 'W': 15, 'D': 13, 'L': 10, 'GF': 46, 'GA': 35, 'GD': 11, 'Pts': 58, 'Qualification or relegation': 'Qualification for the Intertoto Cup third round'},
    {'Season': '9900', 'Pos': 7, 'Team': 'West Ham', 'Pld': 38, 'W': 16, 'D': 10, 'L': 12, 'GF': 57, 'GA': 56, 'GD': 1, 'Pts': 58, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9900', 'Pos': 8, 'Team': 'Sunderland', 'Pld': 38, 'W': 16, 'D': 7, 'L': 15, 'GF': 55, 'GA': 55, 'GD': 0, 'Pts': 55, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9900', 'Pos': 9, 'Team': 'Leicester', 'Pld': 38, 'W': 15, 'D': 10, 'L': 13, 'GF': 52, 'GA': 53, 'GD': -1, 'Pts': 55, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9900', 'Pos': 10, 'Team': 'Tottenham', 'Pld': 38, 'W': 15, 'D': 8, 'L': 15, 'GF': 57, 'GA': 49, 'GD': 8, 'Pts': 53, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9900', 'Pos': 11, 'Team': 'Newcastle', 'Pld': 38, 'W': 14, 'D': 10, 'L': 14, 'GF': 63, 'GA': 54, 'GD': 9, 'Pts': 52, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9900', 'Pos': 12, 'Team': 'Middlesbrough', 'Pld': 38, 'W': 14, 'D': 10, 'L': 14, 'GF': 46, 'GA': 52, 'GD': -6, 'Pts': 52, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9900', 'Pos': 13, 'Team': 'Everton', 'Pld': 38, 'W': 12, 'D': 14, 'L': 12, 'GF': 59, 'GA': 49, 'GD': 10, 'Pts': 50, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9900', 'Pos': 14, 'Team': 'Coventry', 'Pld': 38, 'W': 12, 'D': 8, 'L': 18, 'GF': 47, 'GA': 54, 'GD': -7, 'Pts': 44, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9900', 'Pos': 15, 'Team': 'Southampton', 'Pld': 38, 'W': 12, 'D': 8, 'L': 18, 'GF': 45, 'GA': 62, 'GD': -17, 'Pts': 44, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9900', 'Pos': 16, 'Team': 'Derby', 'Pld': 38, 'W': 9, 'D': 11, 'L': 18, 'GF': 44, 'GA': 57, 'GD': -13, 'Pts': 38, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9900', 'Pos': 17, 'Team': 'Bradford', 'Pld': 38, 'W': 9, 'D': 9, 'L': 20, 'GF': 38, 'GA': 68, 'GD': -30, 'Pts': 36, 'Qualification or relegation': 'Qualification for the Intertoto Cup third round'},
    {'Season': '9900', 'Pos': 18, 'Team': 'Wimbledon', 'Pld': 38, 'W': 7, 'D': 12, 'L': 19, 'GF': 46, 'GA': 74, 'GD': -28, 'Pts': 33, 'Qualification or relegation': 'Relegation to the Football League First Division'},
    {'Season': '9900', 'Pos': 19, 'Team': 'Sheffield Weds', 'Pld': 38, 'W': 8, 'D': 7, 'L': 23, 'GF': 38, 'GA': 70, 'GD': -32, 'Pts': 31, 'Qualification or relegation': 'Relegation to the Football League First Division'},
    {'Season': '9900', 'Pos': 20, 'Team': 'Watford', 'Pld': 38, 'W': 6, 'D': 6, 'L': 26, 'GF': 35, 'GA': 77, 'GD': -42, 'Pts': 24, 'Qualification or relegation': 'Relegation to the Football League First Division'},
]
df1 = pd.concat([df1, pd.DataFrame(records_9900)], ignore_index=True)
df1.head()

,Season,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification or relegation
0,0001,1,Manchester United,38,24,8,6,79,31,48,80,Qualification for the Champions League first g...
1,0001,2,Arsenal,38,20,10,8,63,38,25,70,Qualification for the Champions League first g...
2,0001,3,Liverpool,38,20,9,9,71,39,32,69,Qualification for the Champions League third q...
3,0001,4,Leeds United,38,20,8,10,64,43,21,68,Qualification for the UEFA Cup first round[a]
4,0001,5,Ipswich Town,38,20,6,12,57,42,15,66,Qualification for the UEFA Cup first round[a]

In [151]:
records_9899 = [
    {'Season': '9899', 'Pos': 1, 'Team': 'Man United', 'Pld': 38, 'W': 22, 'D': 13, 'L': 3, 'GF': 80, 'GA': 37, 'GD': 43, 'Pts': 79, 'Qualification or relegation': 'Qualification for the Champions League first group stage'},
    {'Season': '9899', 'Pos': 2, 'Team': 'Arsenal', 'Pld': 38, 'W': 22, 'D': 12, 'L': 4, 'GF': 59, 'GA': 17, 'GD': 42, 'Pts': 78, 'Qualification or relegation': 'Qualification for the Champions League first group stage'},
    {'Season': '9899', 'Pos': 3, 'Team': 'Chelsea', 'Pld': 38, 'W': 20, 'D': 15, 'L': 3, 'GF': 57, 'GA': 30, 'GD': 27, 'Pts': 75, 'Qualification or relegation': 'Qualification for the Champions League third qualifying round'}, 
    {'Season': '9899', 'Pos': 4, 'Team': 'Leeds', 'Pld': 38, 'W': 18, 'D': 13, 'L': 7, 'GF': 62, 'GA': 34, 'GD': 28, 'Pts': 67, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},  #
    {'Season': '9899', 'Pos': 5, 'Team': 'Aston Villa', 'Pld': 38, 'W': 16, 'D': 9, 'L': 13, 'GF': 46, 'GA': 53, 'GD': -7, 'Pts': 57, 'Qualification or relegation': 'Qualification for the Intertoto Cup third round'},
    {'Season': '9899', 'Pos': 6, 'Team': 'West Ham', 'Pld': 38, 'W': 15, 'D': 10, 'L': 13, 'GF': 51, 'GA': 46, 'GD': 5, 'Pts': 55, 'Qualification or relegation': 'Not Applicable'}, 
    {'Season': '9899', 'Pos': 7, 'Team': 'Liverpool', 'Pld': 38, 'W': 15, 'D': 9, 'L': 14, 'GF': 68, 'GA': 49, 'GD': 19, 'Pts': 54, 'Qualification or relegation': 'Not Applicable'}, 
    {'Season': '9899', 'Pos': 8, 'Team': 'Derby', 'Pld': 38, 'W': 13, 'D': 13, 'L': 12, 'GF': 40, 'GA': 45, 'GD': -5, 'Pts': 52, 'Qualification or relegation': 'Not Applicable'}, 
    {'Season': '9899', 'Pos': 9, 'Team': 'Middlesbrough', 'Pld': 38, 'W': 12, 'D': 15, 'L': 11, 'GF': 48, 'GA': 54, 'GD': -6, 'Pts': 51, 'Qualification or relegation': 'Not Applicable'}, 
    {'Season': '9899', 'Pos': 10, 'Team': 'Leicester', 'Pld': 38, 'W': 12, 'D': 13, 'L': 13, 'GF': 40, 'GA': 46, 'GD': -6, 'Pts': 49, 'Qualification or relegation': 'Not Applicable'}, 
    {'Season': '9899', 'Pos': 11, 'Team': 'Tottenham', 'Pld': 38, 'W': 11, 'D': 14, 'L': 13, 'GF': 47, 'GA': 50, 'GD': -3, 'Pts': 47, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9899', 'Pos': 12, 'Team': 'Newcastle', 'Pld': 38, 'W': 13, 'D': 7, 'L': 18, 'GF': 41, 'GA': 42, 'GD': -1, 'Pts': 46, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9899', 'Pos': 13, 'Team': 'Sheffield Weds', 'Pld': 38, 'W': 11, 'D': 13, 'L': 14, 'GF': 48, 'GA': 54, 'GD': -6, 'Pts': 46, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'}, 
    {'Season': '9899', 'Pos': 14, 'Team': 'Everton', 'Pld': 38, 'W': 11, 'D': 10, 'L': 17, 'GF': 42, 'GA': 47, 'GD': -5, 'Pts': 43, 'Qualification or relegation': 'Not Applicable'}, 
    {'Season': '9899', 'Pos': 15, 'Team': 'Coventry', 'Pld': 38, 'W': 11, 'D': 9, 'L': 18, 'GF': 39, 'GA': 51, 'GD': -12, 'Pts': 42, 'Qualification or relegation': 'Not Applicable'}, 
    {'Season': '9899', 'Pos': 16, 'Team': 'Wimbledon', 'Pld': 38, 'W': 10, 'D': 12, 'L': 16, 'GF': 40, 'GA': 63, 'GD': -23, 'Pts': 42, 'Qualification or relegation': 'Not Applicable'},  
    {'Season': '9899', 'Pos': 17, 'Team': 'Southampton', 'Pld': 38, 'W': 11, 'D': 8, 'L': 19, 'GF': 37, 'GA': 64, 'GD': -27, 'Pts': 41, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9899', 'Pos': 18, 'Team': 'Charlton', 'Pld': 38, 'W': 8, 'D': 12, 'L': 18, 'GF': 41, 'GA': 56, 'GD': -15, 'Pts': 36, 'Qualification or relegation': 'Relegation to the Football League First Division'},
    {'Season': '9899', 'Pos': 19, 'Team': 'Blackburn', 'Pld': 38, 'W': 7, 'D': 14, 'L': 17, 'GF': 38, 'GA': 52, 'GD': -14, 'Pts': 35, 'Qualification or relegation': 'Relegation to the Football League First Division'},
    {'Season': '9899', 'Pos': 20, 'Team': 'Nottm Forest', 'Pld': 38, 'W': 7, 'D': 9, 'L': 22, 'GF': 35, 'GA': 69, 'GD': -34, 'Pts': 30, 'Qualification or relegation': 'Relegation to the Football League First Division'},
]
df1 = pd.concat([df1, pd.DataFrame(records_9899)], ignore_index=True)

In [152]:
records_9798 = [
    {'Season': '9798', 'Pos': 1, 'Team': 'Arsenal', 'Pld': 38, 'W': 23, 'D': 9, 'L': 6, 'GF': 68, 'GA': 33, 'GD': 35, 'Pts': 78, 'Qualification or relegation': 'Qualification for the Champions League group stage'},
    {'Season': '9798', 'Pos': 2, 'Team': 'Man United', 'Pld': 38, 'W': 23, 'D': 8, 'L': 7, 'GF': 73, 'GA': 26, 'GD': 47, 'Pts': 77, 'Qualification or relegation': 'Qualification for the Champions League second qualifying round'},
    {'Season': '9798', 'Pos': 3, 'Team': 'Liverpool', 'Pld': 38, 'W': 18, 'D': 11, 'L': 9, 'GF': 68, 'GA': 42, 'GD': 26, 'Pts': 65, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9798', 'Pos': 4, 'Team': 'Chelsea', 'Pld': 38, 'W': 20, 'D': 3, 'L': 15, 'GF': 71, 'GA': 43, 'GD': 28, 'Pts': 63, 'Qualification or relegation': 'Qualification for the UEFA Cup Winners\' Cup'},
    {'Season': '9798', 'Pos': 5, 'Team': 'West Ham', 'Pld': 38, 'W': 17, 'D': 8, 'L': 13, 'GF': 57, 'GA': 46, 'GD': 11, 'Pts': 59, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9798', 'Pos': 6, 'Team': 'Leeds', 'Pld': 38, 'W': 16, 'D': 10, 'L': 12, 'GF': 57, 'GA': 52, 'GD': 5, 'Pts': 58, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9798', 'Pos': 7, 'Team': 'Blackburn', 'Pld': 38, 'W': 17, 'D': 6, 'L': 15, 'GF': 49, 'GA': 48, 'GD': 1, 'Pts': 57, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9798', 'Pos': 8, 'Team': 'Aston Villa', 'Pld': 38, 'W': 16, 'D': 8, 'L': 14, 'GF': 56, 'GA': 57, 'GD': -1, 'Pts': 56, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9798', 'Pos': 9, 'Team': 'Derby', 'Pld': 38, 'W': 16, 'D': 7, 'L': 15, 'GF': 52, 'GA': 49, 'GD': 3, 'Pts': 55, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9798', 'Pos': 10, 'Team': 'Leicester', 'Pld': 38, 'W': 13, 'D': 14, 'L': 11, 'GF': 51, 'GA': 41, 'GD': 10, 'Pts': 53, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9798', 'Pos': 11, 'Team': 'Coventry', 'Pld': 38, 'W': 12, 'D': 16, 'L': 10, 'GF': 46, 'GA': 44, 'GD': 2, 'Pts': 52, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9798', 'Pos': 12, 'Team': 'Southampton', 'Pld': 38, 'W': 14, 'D': 6, 'L': 18, 'GF': 50, 'GA': 55, 'GD': -5, 'Pts': 48, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9798', 'Pos': 13, 'Team': 'Tottenham', 'Pld': 38, 'W': 11, 'D': 11, 'L': 16, 'GF': 35, 'GA': 44, 'GD': -9, 'Pts': 44, 'Qualification or relegation': 'Qualification for the UEFA Cup Winners\' Cup'},
    {'Season': '9798', 'Pos': 14, 'Team': 'Newcastle', 'Pld': 38, 'W': 11, 'D': 11, 'L': 16, 'GF': 44, 'GA': 56, 'GD': -12, 'Pts': 44, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9798', 'Pos': 15, 'Team': 'Wimbledon', 'Pld': 38, 'W': 10, 'D': 14, 'L': 14, 'GF': 34, 'GA': 46, 'GD': -12, 'Pts': 44, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9798', 'Pos': 16, 'Team': 'Sheffield W', 'Pld': 38, 'W': 12, 'D': 8, 'L': 18, 'GF': 52, 'GA': 67, 'GD': -15, 'Pts': 44, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9798', 'Pos': 17, 'Team': 'Everton', 'Pld': 38, 'W': 9, 'D': 13, 'L': 16, 'GF': 41, 'GA': 56, 'GD': -15, 'Pts': 40, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9798', 'Pos': 18, 'Team': 'Bolton', 'Pld': 38, 'W': 9, 'D': 13, 'L': 16, 'GF': 41, 'GA': 61, 'GD': -20, 'Pts': 40, 'Qualification or relegation': 'Relegation to the Football League First Division'},
    {'Season': '9798', 'Pos': 19, 'Team': 'Barnsley', 'Pld': 38, 'W': 10, 'D': 5, 'L': 23, 'GF': 37, 'GA': 82, 'GD': -45, 'Pts': 35, 'Qualification or relegation': 'Relegation to the Football League First Division'},
    {'Season': '9798', 'Pos': 20, 'Team': 'Crystal Palace', 'Pld': 38, 'W': 8, 'D': 9, 'L': 21, 'GF': 37, 'GA': 71, 'GD': -34, 'Pts': 33, 'Qualification or relegation': 'Qualification for the Intertoto Cup third round'},
]
df1 = pd.concat([df1, pd.DataFrame(records_9798)], ignore_index=True)

In [153]:
records_9697 = [
    {'Season': '9697', 'Pos': 1, 'Team': 'Man United', 'Pld': 38, 'W': 21, 'D': 12, 'L': 5, 'GF': 76, 'GA': 44, 'GD': 32, 'Pts': 75, 'Qualification or relegation': 'Qualification for the Champions League group stage'},
    {'Season': '9697', 'Pos': 2, 'Team': 'Newcastle', 'Pld': 38, 'W': 19, 'D': 11, 'L': 8, 'GF': 73, 'GA': 40, 'GD': 33, 'Pts': 68, 'Qualification or relegation': 'Qualification for the Champions League second qualifying round'},
    {'Season': '9697', 'Pos': 3, 'Team': 'Arsenal', 'Pld': 38, 'W': 19, 'D': 11, 'L': 8, 'GF': 62, 'GA': 32, 'GD': 30, 'Pts': 68, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9697', 'Pos': 4, 'Team': 'Liverpool', 'Pld': 38, 'W': 18, 'D': 11, 'L': 9, 'GF': 62, 'GA': 37, 'GD': 25, 'Pts': 65, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9697', 'Pos': 5, 'Team': 'Aston Villa', 'Pld': 38, 'W': 17, 'D': 10, 'L': 11, 'GF': 47, 'GA': 34, 'GD': 13, 'Pts': 61, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9697', 'Pos': 6, 'Team': 'Chelsea', 'Pld': 38, 'W': 16, 'D': 11, 'L': 11, 'GF': 58, 'GA': 55, 'GD': 3, 'Pts': 59, 'Qualification or relegation': 'Qualification for the UEFA Cup Winners\' Cup'},
    {'Season': '9697', 'Pos': 7, 'Team': 'Sheffield W', 'Pld': 38, 'W': 14, 'D': 15, 'L': 9, 'GF': 50, 'GA': 51, 'GD': -1, 'Pts': 57, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9697', 'Pos': 8, 'Team': 'Wimbledon', 'Pld': 38, 'W': 15, 'D': 11, 'L': 12, 'GF': 49, 'GA': 46, 'GD': 3, 'Pts': 56, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9697', 'Pos': 9, 'Team': 'Leicester', 'Pld': 38, 'W': 12, 'D': 11, 'L': 15, 'GF': 46, 'GA': 54, 'GD': -8, 'Pts': 47, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9697', 'Pos': 10, 'Team': 'Tottenham', 'Pld': 38, 'W': 13, 'D': 7, 'L': 18, 'GF': 44, 'GA': 51, 'GD': -7, 'Pts': 46, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9697', 'Pos': 11, 'Team': 'Leeds', 'Pld': 38, 'W': 11, 'D': 13, 'L': 14, 'GF': 28, 'GA': 38, 'GD': -10, 'Pts': 46, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9697', 'Pos': 12, 'Team': 'Derby', 'Pld': 38, 'W': 11, 'D': 13, 'L': 14, 'GF': 45, 'GA': 58, 'GD': -13, 'Pts': 46, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9697', 'Pos': 13, 'Team': 'West Ham', 'Pld': 38, 'W': 9, 'D': 15, 'L': 14, 'GF': 42, 'GA': 43, 'GD': -1, 'Pts': 42, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9697', 'Pos': 14, 'Team': 'Blackburn', 'Pld': 38, 'W': 10, 'D': 12, 'L': 16, 'GF': 39, 'GA': 48, 'GD': -9, 'Pts': 42, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9697', 'Pos': 15, 'Team': 'Everton', 'Pld': 38, 'W': 10, 'D': 12, 'L': 16, 'GF': 44, 'GA': 57, 'GD': -13, 'Pts': 42, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9697', 'Pos': 16, 'Team': 'Southampton', 'Pld': 38, 'W': 10, 'D': 11, 'L': 17, 'GF': 50, 'GA': 56, 'GD': -6, 'Pts': 41, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9697', 'Pos': 17, 'Team': 'Coventry', 'Pld': 38, 'W': 9, 'D': 14, 'L': 15, 'GF': 38, 'GA': 54, 'GD': -16, 'Pts': 41, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9697', 'Pos': 18, 'Team': 'Sunderland', 'Pld': 38, 'W': 10, 'D': 10, 'L': 18, 'GF': 35, 'GA': 53, 'GD': -18, 'Pts': 40, 'Qualification or relegation': 'Relegation to the Football League First Division'},
    {'Season': '9697', 'Pos': 19, 'Team': 'Middlesbrough', 'Pld': 38, 'W': 10, 'D': 12, 'L': 16, 'GF': 51, 'GA': 60, 'GD': -9, 'Pts': 39, 'Qualification or relegation': 'Relegation to the Football League First Division'},
    {'Season': '9697', 'Pos': 20, 'Team': 'Nottm Forest', 'Pld': 38, 'W': 6, 'D': 16, 'L': 16, 'GF': 31, 'GA': 59, 'GD': -28, 'Pts': 34, 'Qualification or relegation': 'Relegation to the Football League First Division'},
]
df1 = pd.concat([df1, pd.DataFrame(records_9697)], ignore_index=True)

In [154]:
records_9596 = [
    {'Season': '9596', 'Pos': 1, 'Team': 'Man United', 'Pld': 38, 'W': 25, 'D': 7, 'L': 6, 'GF': 73, 'GA': 35, 'GD': 38, 'Pts': 82, 'Qualification or relegation': 'Qualification for the Champions League group stage'},
    {'Season': '9596', 'Pos': 2, 'Team': 'Newcastle', 'Pld': 38, 'W': 20, 'D': 11, 'L': 7, 'GF': 49, 'GA': 32, 'GD': 17, 'Pts': 71, 'Qualification or relegation': 'Qualification for the Champions League second qualifying round'},
    {'Season': '9596', 'Pos': 3, 'Team': 'Liverpool', 'Pld': 38, 'W': 19, 'D': 11, 'L': 8, 'GF': 66, 'GA': 41, 'GD': 25, 'Pts': 68, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9596', 'Pos': 4, 'Team': 'Arsenal', 'Pld': 38, 'W': 18, 'D': 11, 'L': 9, 'GF': 70, 'GA': 34, 'GD': 36, 'Pts': 65, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9596', 'Pos': 5, 'Team': 'Blackburn', 'Pld': 38, 'W': 18, 'D': 7, 'L': 13, 'GF': 52, 'GA': 39, 'GD': 13, 'Pts': 61, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9596', 'Pos': 6, 'Team': 'Aston Villa', 'Pld': 38, 'W': 16, 'D': 9, 'L': 13, 'GF': 58, 'GA': 55, 'GD': 3, 'Pts': 57, 'Qualification or relegation': 'Qualification for the UEFA Cup Winners\' Cup'},
    {'Season': '9596', 'Pos': 7, 'Team': 'Everton', 'Pld': 38, 'W': 15, 'D': 10, 'L': 13, 'GF': 61, 'GA': 47, 'GD': 14, 'Pts': 55, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9596', 'Pos': 8, 'Team': 'Tottenham', 'Pld': 38, 'W': 16, 'D': 6, 'L': 16, 'GF': 50, 'GA': 54, 'GD': -4, 'Pts': 54, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9596', 'Pos': 9, 'Team': 'Nottm Forest', 'Pld': 38, 'W': 15, 'D': 5, 'L': 18, 'GF': 50, 'GA': 61, 'GD': -11, 'Pts': 50, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9596', 'Pos': 10, 'Team': 'West Ham', 'Pld': 38, 'W': 13, 'D': 10, 'L': 15, 'GF': 48, 'GA': 51, 'GD': -3, 'Pts': 49, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9596', 'Pos': 11, 'Team': 'Chelsea', 'Pld': 38, 'W': 13, 'D': 9, 'L': 16, 'GF': 44, 'GA': 51, 'GD': -7, 'Pts': 48, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9596', 'Pos': 12, 'Team': 'Middlesbrough', 'Pld': 38, 'W': 11, 'D': 13, 'L': 14, 'GF': 42, 'GA': 53, 'GD': -11, 'Pts': 46, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9596', 'Pos': 13, 'Team': 'Leeds', 'Pld': 38, 'W': 11, 'D': 13, 'L': 14, 'GF': 46, 'GA': 51, 'GD': -5, 'Pts': 46, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9596', 'Pos': 14, 'Team': 'Wimbledon', 'Pld': 38, 'W': 11, 'D': 12, 'L': 15, 'GF': 37, 'GA': 48, 'GD': -11, 'Pts': 45, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9596', 'Pos': 15, 'Team': 'Sheffield Weds', 'Pld': 38, 'W': 10, 'D': 14, 'L': 14, 'GF': 34, 'GA': 44, 'GD': -10, 'Pts': 44, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9596', 'Pos': 16, 'Team': 'Coventry', 'Pld': 38, 'W': 11, 'D': 10, 'L': 17, 'GF': 44, 'GA': 55, 'GD': -11, 'Pts': 43, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9596', 'Pos': 17, 'Team': 'Southampton', 'Pld': 38, 'W': 9, 'D': 11, 'L': 18, 'GF': 33, 'GA': 58, 'GD': -25, 'Pts': 38, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9596', 'Pos': 18, 'Team': 'Man City', 'Pld': 38, 'W': 10, 'D': 8, 'L': 20, 'GF': 41, 'GA': 63, 'GD': -22, 'Pts': 38, 'Qualification or relegation': 'Relegation to the Football League First Division'},
    {'Season': '9596', 'Pos': 19, 'Team': 'QPR', 'Pld': 38, 'W': 8, 'D': 13, 'L': 17, 'GF': 39, 'GA': 66, 'GD': -27, 'Pts': 37, 'Qualification or relegation': 'Relegation to the Football League First Division'},
    {'Season': '9596', 'Pos': 20, 'Team': 'Bolton', 'Pld': 38, 'W': 7, 'D': 12, 'L': 19, 'GF': 36, 'GA': 60, 'GD': -24, 'Pts': 33, 'Qualification or relegation': 'Relegation to the Football League First Division'},
]
df1 = pd.concat([df1, pd.DataFrame(records_9596)], ignore_index=True)

In [155]:
records_9495 = [
    {'Season': '9495', 'Pos': 1, 'Team': 'Man United', 'Pld': 42, 'W': 27, 'D': 8, 'L': 7, 'GF': 80, 'GA': 39, 'GD': 41, 'Pts': 89, 'Qualification or relegation': 'Qualification for the Champions League group stage'},
    {'Season': '9495', 'Pos': 2, 'Team': 'Blackburn', 'Pld': 42, 'W': 26, 'D': 10, 'L': 6, 'GF': 77, 'GA': 28, 'GD': 49, 'Pts': 88, 'Qualification or relegation': 'Qualification for the Champions League group stage'},
    {'Season': '9495', 'Pos': 3, 'Team': 'Nottm Forest', 'Pld': 42, 'W': 22, 'D': 11, 'L': 9, 'GF': 72, 'GA': 43, 'GD': 29, 'Pts': 77, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9495', 'Pos': 4, 'Team': 'Liverpool', 'Pld': 42, 'W': 21, 'D': 11, 'L': 10, 'GF': 65, 'GA': 37, 'GD': 28, 'Pts': 74, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9495', 'Pos': 5, 'Team': 'Leeds', 'Pld': 42, 'W': 20, 'D': 13, 'L': 9, 'GF': 59, 'GA': 38, 'GD': 21, 'Pts': 73, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9495', 'Pos': 6, 'Team': 'Newcastle', 'Pld': 42, 'W': 20, 'D': 12, 'L': 10, 'GF': 67, 'GA': 47, 'GD': 20, 'Pts': 72, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 7, 'Team': 'Tottenham', 'Pld': 42, 'W': 20, 'D': 10, 'L': 12, 'GF': 65, 'GA': 50, 'GD': 15, 'Pts': 70, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 8, 'Team': 'QPR', 'Pld': 42, 'W': 19, 'D': 12, 'L': 11, 'GF': 56, 'GA': 46, 'GD': 10, 'Pts': 69, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 9, 'Team': 'Wimbledon', 'Pld': 42, 'W': 18, 'D': 13, 'L': 11, 'GF': 55, 'GA': 44, 'GD': 11, 'Pts': 67, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 10, 'Team': 'Southampton', 'Pld': 42, 'W': 18, 'D': 13, 'L': 11, 'GF': 54, 'GA': 46, 'GD': 8, 'Pts': 67, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 11, 'Team': 'Chelsea', 'Pld': 42, 'W': 17, 'D': 14, 'L': 11, 'GF': 60, 'GA': 41, 'GD': 19, 'Pts': 65, 'Qualification or relegation': 'Qualification for the UEFA Cup Winners\' Cup'},
    {'Season': '9495', 'Pos': 12, 'Team': 'Arsenal', 'Pld': 42, 'W': 16, 'D': 16, 'L': 10, 'GF': 63, 'GA': 52, 'GD': 11, 'Pts': 64, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 13, 'Team': 'Sheffield Weds', 'Pld': 42, 'W': 17, 'D': 8, 'L': 17, 'GF': 54, 'GA': 55, 'GD': -1, 'Pts': 59, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 14, 'Team': 'West Ham', 'Pld': 42, 'W': 15, 'D': 11, 'L': 16, 'GF': 56, 'GA': 55, 'GD': 1, 'Pts': 56, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 15, 'Team': 'Everton', 'Pld': 42, 'W': 14, 'D': 12, 'L': 16, 'GF': 53, 'GA': 56, 'GD': -3, 'Pts': 54, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 16, 'Team': 'Coventry', 'Pld': 42, 'W': 13, 'D': 15, 'L': 14, 'GF': 52, 'GA': 49, 'GD': 3, 'Pts': 54, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 17, 'Team': 'Man City', 'Pld': 42, 'W': 15, 'D': 8, 'L': 19, 'GF': 56, 'GA': 64, 'GD': -8, 'Pts': 53, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 18, 'Team': 'Aston Villa', 'Pld': 42, 'W': 12, 'D': 16, 'L': 14, 'GF': 46, 'GA': 54, 'GD': -8, 'Pts': 52, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 19, 'Team': 'Crystal Palace', 'Pld': 42, 'W': 11, 'D': 18, 'L': 13, 'GF': 49, 'GA': 57, 'GD': -8, 'Pts': 51, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9495', 'Pos': 20, 'Team': 'Norwich', 'Pld': 42, 'W': 11, 'D': 17, 'L': 14, 'GF': 42, 'GA': 50, 'GD': -8, 'Pts': 50, 'Qualification or relegation': 'Relegation to the Football League First Division'},
]
df1 = pd.concat([df1, pd.DataFrame(records_9495)], ignore_index=True)

In [156]:
records_9394 = [
    {'Season': '9394', 'Pos': 1, 'Team': 'Man United', 'Pld': 42, 'W': 27, 'D': 8, 'L': 7, 'GF': 80, 'GA': 38, 'GD': 42, 'Pts': 92, 'Qualification or relegation': 'Qualification for the Champions League group stage'},
    {'Season': '9394', 'Pos': 2, 'Team': 'Blackburn', 'Pld': 42, 'W': 25, 'D': 9, 'L': 8, 'GF': 63, 'GA': 36, 'GD': 27, 'Pts': 84, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9394', 'Pos': 3, 'Team': 'Newcastle', 'Pld': 42, 'W': 23, 'D': 8, 'L': 11, 'GF': 82, 'GA': 41, 'GD': 41, 'Pts': 77, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9394', 'Pos': 4, 'Team': 'Arsenal', 'Pld': 42, 'W': 18, 'D': 17, 'L': 7, 'GF': 53, 'GA': 28, 'GD': 25, 'Pts': 71, 'Qualification or relegation': 'Qualification for the UEFA Cup Winners\' Cup'},
    {'Season': '9394', 'Pos': 5, 'Team': 'Leeds', 'Pld': 42, 'W': 18, 'D': 16, 'L': 8, 'GF': 65, 'GA': 39, 'GD': 26, 'Pts': 70, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9394', 'Pos': 6, 'Team': 'Wimbledon', 'Pld': 42, 'W': 18, 'D': 16, 'L': 8, 'GF': 56, 'GA': 53, 'GD': 3, 'Pts': 70, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 7, 'Team': 'Sheffield Weds', 'Pld': 42, 'W': 16, 'D': 19, 'L': 7, 'GF': 53, 'GA': 47, 'GD': 6, 'Pts': 67, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 8, 'Team': 'Liverpool', 'Pld': 42, 'W': 17, 'D': 15, 'L': 10, 'GF': 59, 'GA': 47, 'GD': 12, 'Pts': 66, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 9, 'Team': 'QPR', 'Pld': 42, 'W': 16, 'D': 16, 'L': 10, 'GF': 62, 'GA': 52, 'GD': 10, 'Pts': 64, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 10, 'Team': 'Aston Villa', 'Pld': 42, 'W': 15, 'D': 18, 'L': 9, 'GF': 46, 'GA': 43, 'GD': 3, 'Pts': 63, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 11, 'Team': 'Coventry', 'Pld': 42, 'W': 16, 'D': 14, 'L': 12, 'GF': 55, 'GA': 51, 'GD': 4, 'Pts': 62, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 12, 'Team': 'Norwich', 'Pld': 42, 'W': 12, 'D': 22, 'L': 8, 'GF': 47, 'GA': 42, 'GD': 5, 'Pts': 58, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 13, 'Team': 'West Ham', 'Pld': 42, 'W': 13, 'D': 17, 'L': 12, 'GF': 47, 'GA': 48, 'GD': -1, 'Pts': 56, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 14, 'Team': 'Chelsea', 'Pld': 42, 'W': 13, 'D': 15, 'L': 14, 'GF': 49, 'GA': 52, 'GD': -3, 'Pts': 54, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 15, 'Team': 'Tottenham', 'Pld': 42, 'W': 11, 'D': 18, 'L': 13, 'GF': 54, 'GA': 53, 'GD': 1, 'Pts': 51, 'Qualification or relegation': 'Qualification for the UEFA Cup first round'},
    {'Season': '9394', 'Pos': 16, 'Team': 'Man City', 'Pld': 42, 'W': 9, 'D': 23, 'L': 10, 'GF': 38, 'GA': 43, 'GD': -5, 'Pts': 50, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 17, 'Team': 'Everton', 'Pld': 42, 'W': 12, 'D': 13, 'L': 17, 'GF': 41, 'GA': 43, 'GD': -2, 'Pts': 49, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 18, 'Team': 'Southampton', 'Pld': 42, 'W': 12, 'D': 12, 'L': 18, 'GF': 49, 'GA': 57, 'GD': -8, 'Pts': 48, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 19, 'Team': 'Ipswich', 'Pld': 42, 'W': 9, 'D': 18, 'L': 15, 'GF': 35, 'GA': 48, 'GD': -13, 'Pts': 45, 'Qualification or relegation': 'Not Applicable'},
    {'Season': '9394', 'Pos': 20, 'Team': 'Sheffield', 'Pld': 42, 'W': 13, 'D': 5, 'L': 24, 'GF': 43, 'GA': 60, 'GD': -17, 'Pts': 44, 'Qualification or relegation': 'Relegation to the Football League First Division'},
    {'Season': '9394', 'Pos': 21, 'Team': 'Oldham', 'Pld': 42, 'W': 9, 'D': 16, 'L': 17, 'GF': 42, 'GA': 56, 'GD': -14, 'Pts': 43, 'Qualification or relegation': 'Relegation to the Football League First Division'},
    {'Season': '9394', 'Pos': 22, 'Team': 'Swindon', 'Pld': 42, 'W': 7, 'D': 9, 'L': 26, 'GF': 38, 'GA': 83, 'GD': -45, 'Pts': 30, 'Qualification or relegation': 'Relegation to the Football League First Division'},
]
df1 = pd.concat([df1, pd.DataFrame(records_9394)], ignore_index=True)

In [157]:
team_mapping = {
    'Blackburn Rovers': 'Blackburn',
    'Bradford City': 'Bradford',
    'Brighton & Hove Albion': 'Brighton',
    'Cardiff City': 'Cardiff',
    'Charlton Athletic': 'Charlton',
    'Coventry City': 'Coventry',
    'Derby County': 'Derby',
    'Huddersfield Town': 'Huddersfield',
    'Hull City': 'Hull',
    'Ipswich Town': 'Ipswich',
    'Leeds United': 'Leeds',
    'Leicester City': 'Leicester',
    'Manchester City': 'Man City',
    'Manchester United': 'Man United',
    'Newcastle United': 'Newcastle',
    'Norwich City': 'Norwich',
    'Nottm Forest': 'Nottingham',
    "Nott'm Forest": 'Nottingham',
    'Queens Park Rangers': 'QPR',
    'Sheffield United': 'Sheffield',
    'Sheffield W': 'Sheffield Weds',
    'Stoke City': 'Stoke',
    'Swansea City': 'Swansea',
    'Tottenham Hotspur': 'Tottenham',
    'West Bromwich Albion': 'West Brom',
    'West Ham United': 'West Ham',
    'Wigan Athletic': 'Wigan',
    'Wolverhampton Wanderers': 'Wolves'
}

In [158]:
df1['Team'] = df1['Team'].replace(team_mapping)

In [160]:
df1['Season'] = df1['Season'].astype(str)
df['Season'] = df['Season'].astype(str)

In [161]:
df.loc[df['Season'] == '1', 'Season'] = '0001'
df.loc[df['Season'] == '102', 'Season'] = '0102'
df.loc[df['Season'] == '203', 'Season'] = '0203'
df.loc[df['Season'] == '304', 'Season'] = '0304'
df.loc[df['Season'] == '405', 'Season'] = '0405'
df.loc[df['Season'] == '506', 'Season'] = '0506'
df.loc[df['Season'] == '607', 'Season'] = '0607'
df.loc[df['Season'] == '708', 'Season'] = '0708'
df.loc[df['Season'] == '809', 'Season'] = '0809'
df.loc[df['Season'] == '910', 'Season'] = '0910'

df1.loc[df1['Season'] == '1', 'Season'] = '0001'
df1.loc[df1['Season'] == '102', 'Season'] = '0102'
df1.loc[df1['Season'] == '203', 'Season'] = '0203'
df1.loc[df1['Season'] == '304', 'Season'] = '0304'
df1.loc[df1['Season'] == '405', 'Season'] = '0405'
df1.loc[df1['Season'] == '506', 'Season'] = '0506'
df1.loc[df1['Season'] == '607', 'Season'] = '0607'
df1.loc[df1['Season'] == '708', 'Season'] = '0708'
df1.loc[df1['Season'] == '809', 'Season'] = '0809'
df1.loc[df1['Season'] == '910', 'Season'] = '0910'

In [ ]:
df1['Season'] = df1['Season'].astype(str)
df['Season'] = df['Season'].astype(str)
df1['Team'] = df1['Team'].astype(str)
df['AwayTeam'] = df['AwayTeam'].astype(str)

df_combined = df1.merge(
    df,
    left_on=['Team', 'Season'],
    right_on=['AwayTeam', 'Season'],
    how='right'
)

df_combined.head()

,Season,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification or relegation,Year,Month,Day,WeekDay,Time,Round,HomeTeam,AwayTeam,HomeGoal,AwayGoal,Result,HomeGoal-HalfTime,AwayGoal-HalfTime,Result-HalfTime,Attendance,Referee,HomeShot,AwayShot,HomeOnTargetShot,AwayOnTargetShot,HomeFoul,AwayFoul,HomeCorner,AwayCorner,HomeYellow,AwayYellow,HomeRed,AwayRed,XGHome,XGAway,SeasonPosHome,SeasonPlayedHome,SeasonWinHome,SeasonDrawHome,SeasonLossHome,SeasonGFHome,SeasonGAHome,SeasonGDHome,SeasonPointsHome,QualificationOrRelegationHome
0,9394,6.0,Wimbledon,42.0,18.0,16.0,8.0,56.0,53.0,3.0,70.0,Not Applicable,1993,8,14,NaN,NaN,NaN,West Ham,Wimbledon,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,42.0,13.0,17.0,12.0,47.0,48.0,-1.0,56.0,Not Applicable
1,9394,17.0,Everton,42.0,12.0,13.0,17.0,41.0,43.0,-2.0,49.0,Not Applicable,1993,8,14,NaN,NaN,NaN,Southampton,Everton,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,42.0,12.0,12.0,18.0,49.0,57.0,-8.0,48.0,Not Applicable
2,9394,22.0,Swindon,42.0,7.0,9.0,26.0,38.0,83.0,-45.0,30.0,Relegation to the Football League First Division,1993,8,14,NaN,NaN,NaN,Sheffield,Swindon,3,1,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,42.0,13.0,5.0,24.0,43.0,60.0,-17.0,44.0,Relegation to the Football League First Division
3,9394,19.0,Ipswich,42.0,9.0,18.0,15.0,35.0,48.0,-13.0,45.0,Not Applicable,1993,8,14,NaN,NaN,NaN,Oldham,Ipswich,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,42.0,9.0,16.0,17.0,42.0,56.0,-14.0,43.0,Relegation to the Football League First Division
4,9394,15.0,Tottenham,42.0,11.0,18.0,13.0,54.0,53.0,1.0,51.0,Qualification for the UEFA Cup first round,1993,8,14,NaN,NaN,NaN,Newcastle,Tottenham,0,1,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,42.0,23.0,8.0,11.0,82.0,41.0,41.0,77.0,Qualification for the UEFA Cup first round

In [163]:
df_combined = df_combined.drop(columns=['Team'])

In [170]:
df = df_combined

In [171]:
new_away_columns = {
    'Pos': 'SeasonPosAway',
    'Pld': 'SeasonPlayedAway',
    'W': 'SeasonWinAway',
    'D': 'SeasonDrawAway',
    'L': 'SeasonLossAway',
    'GF': 'SeasonGFAway',
    'GA': 'SeasonGAAway',
    'GD': 'SeasonGDAway',
    'Pts': 'SeasonPointsAway',
    'Qualification or relegation': 'QualificationOrRelegationAway'
}

In [172]:
df = df.rename(columns=new_away_columns)

In [173]:
final_column_order = [
    'Season',
    'Year',
    'Month',
    'Day',
    'WeekDay',
    'Time',
    'Round',
    'HomeTeam',
    'AwayTeam',
    'HomeGoal',
    'AwayGoal',
    'Result',
    'HomeGoal-HalfTime',
    'AwayGoal-HalfTime',
    'Result-HalfTime',
    'Attendance',
    'Referee',
    'HomeShot',
    'AwayShot',
    'HomeOnTargetShot',
    'AwayOnTargetShot',
    'HomeFoul',
    'AwayFoul',
    'HomeCorner',
    'AwayCorner',
    'HomeYellow',
    'AwayYellow',
    'HomeRed',
    'AwayRed',
    'XGHome',
    'XGAway',
    'PossessionHome',
    'SeasonPosHome',
    'SeasonPlayedHome',
    'SeasonWinHome',
    'SeasonDrawHome',
    'SeasonLossHome',
    'SeasonGFHome',
    'SeasonGAHome',
    'SeasonGDHome',
    'SeasonPointsHome',
    'QualificationOrRelegationHome',
    'SeasonPosAway',
    'SeasonPlayedAway',
    'SeasonWinAway',
    'SeasonDrawAway',
    'SeasonLossAway',
    'SeasonGFAway',
    'SeasonGAAway',
    'SeasonGDAway',
    'SeasonPointsAway',
    'QualificationOrRelegationAway'
]

In [174]:
existing_columns = [col for col in final_column_order if col in df.columns]
df = df[existing_columns]

In [175]:
df.shape

(12704, 51)

In [176]:
df.head()

,Season,Year,Month,Day,WeekDay,Time,Round,HomeTeam,AwayTeam,HomeGoal,AwayGoal,Result,HomeGoal-HalfTime,AwayGoal-HalfTime,Result-HalfTime,Attendance,Referee,HomeShot,AwayShot,HomeOnTargetShot,AwayOnTargetShot,HomeFoul,AwayFoul,HomeCorner,AwayCorner,HomeYellow,AwayYellow,HomeRed,AwayRed,XGHome,XGAway,SeasonPosHome,SeasonPlayedHome,SeasonWinHome,SeasonDrawHome,SeasonLossHome,SeasonGFHome,SeasonGAHome,SeasonGDHome,SeasonPointsHome,QualificationOrRelegationHome,SeasonPosAway,SeasonPlayedAway,SeasonWinAway,SeasonDrawAway,SeasonLossAway,SeasonGFAway,SeasonGAAway,SeasonGDAway,SeasonPointsAway,QualificationOrRelegationAway
0,9394,1993,8,14,NaN,NaN,NaN,West Ham,Wimbledon,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,42.0,13.0,17.0,12.0,47.0,48.0,-1.0,56.0,Not Applicable,6.0,42.0,18.0,16.0,8.0,56.0,53.0,3.0,70.0,Not Applicable
1,9394,1993,8,14,NaN,NaN,NaN,Southampton,Everton,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,42.0,12.0,12.0,18.0,49.0,57.0,-8.0,48.0,Not Applicable,17.0,42.0,12.0,13.0,17.0,41.0,43.0,-2.0,49.0,Not Applicable
2,9394,1993,8,14,NaN,NaN,NaN,Sheffield,Swindon,3,1,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,42.0,13.0,5.0,24.0,43.0,60.0,-17.0,44.0,Relegation to the Football League First Division,22.0,42.0,7.0,9.0,26.0,38.0,83.0,-45.0,30.0,Relegation to the Football League First Division
3,9394,1993,8,14,NaN,NaN,NaN,Oldham,Ipswich,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,42.0,9.0,16.0,17.0,42.0,56.0,-14.0,43.0,Relegation to the Football League First Division,19.0,42.0,9.0,18.0,15.0,35.0,48.0,-13.0,45.0,Not Applicable
4,9394,1993,8,14,NaN,NaN,NaN,Newcastle,Tottenham,0,1,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,42.0,23.0,8.0,11.0,82.0,41.0,41.0,77.0,Qualification for the UEFA Cup first round,15.0,42.0,11.0,18.0,13.0,54.0,53.0,1.0,51.0,Qualification for the UEFA Cup first round

In [177]:
df.to_csv("Data/Data3.csv", index=False)

---