In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv("Data/Data3.csv", dtype={'Season': str})

In [3]:
df.head()

,Season,Year,Month,Day,WeekDay,Time,Round,HomeTeam,AwayTeam,HomeGoal,AwayGoal,Result,HomeGoal-HalfTime,AwayGoal-HalfTime,Result-HalfTime,Attendance,Referee,HomeShot,AwayShot,HomeOnTargetShot,AwayOnTargetShot,HomeFoul,AwayFoul,HomeCorner,AwayCorner,HomeYellow,AwayYellow,HomeRed,AwayRed,XGHome,XGAway,SeasonPosHome,SeasonPlayedHome,SeasonWinHome,SeasonDrawHome,SeasonLossHome,SeasonGFHome,SeasonGAHome,SeasonGDHome,SeasonPointsHome,QualificationOrRelegationHome,SeasonPosAway,SeasonPlayedAway,SeasonWinAway,SeasonDrawAway,SeasonLossAway,SeasonGFAway,SeasonGAAway,SeasonGDAway,SeasonPointsAway,QualificationOrRelegationAway
0,9394,1993,8,14,NaN,NaN,NaN,West Ham,Wimbledon,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,42.0,13.0,17.0,12.0,47.0,48.0,-1.0,56.0,Not Applicable,6.0,42.0,18.0,16.0,8.0,56.0,53.0,3.0,70.0,Not Applicable
1,9394,1993,8,14,NaN,NaN,NaN,Southampton,Everton,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,42.0,12.0,12.0,18.0,49.0,57.0,-8.0,48.0,Not Applicable,17.0,42.0,12.0,13.0,17.0,41.0,43.0,-2.0,49.0,Not Applicable
2,9394,1993,8,14,NaN,NaN,NaN,Sheffield,Swindon,3,1,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,42.0,13.0,5.0,24.0,43.0,60.0,-17.0,44.0,Relegation to the Football League First Division,22.0,42.0,7.0,9.0,26.0,38.0,83.0,-45.0,30.0,Relegation to the Football League First Division
3,9394,1993,8,14,NaN,NaN,NaN,Oldham,Ipswich,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,42.0,9.0,16.0,17.0,42.0,56.0,-14.0,43.0,Relegation to the Football League First Division,19.0,42.0,9.0,18.0,15.0,35.0,48.0,-13.0,45.0,Not Applicable
4,9394,1993,8,14,NaN,NaN,NaN,Newcastle,Tottenham,0,1,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,42.0,23.0,8.0,11.0,82.0,41.0,41.0,77.0,Qualification for the UEFA Cup first round,15.0,42.0,11.0,18.0,13.0,54.0,53.0,1.0,51.0,Qualification for the UEFA Cup first round

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12704 entries, 0 to 12703
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Season                         12704 non-null  object
 1   Year                           12704 non-null  int64
 2   Month                          12704 non-null  int64
 3   Day                            12704 non-null  int64
 4   WeekDay                        2548 non-null   object
 5   Time                           2548 non-null   object
 6   Round                          2548 non-null   float64
 7   HomeTeam                       12704 non-null  object
 8   AwayTeam                       12704 non-null  object
 9   HomeGoal                       12704 non-null  int64
 10  AwayGoal                       12704 non-null  int64
 11  Result                         12704 non-null  object
 12  HomeGoal-HalfTime              11780 non-null  float64
 13  AwayGoal-HalfTime              11780 non-null  float64
 14  Result-HalfTime                11780 non-null  object
 15  Attendance                     1466 non-null   float64
 16  Referee                        9880 non-null   object
 17  HomeShot                       9880 non-null   float64
 18  AwayShot                       9880 non-null   float64
 19  HomeOnTargetShot               9880 non-null   float64
 20  AwayOnTargetShot               9880 non-null   float64
 21  HomeFoul                       9880 non-null   float64
 22  AwayFoul                       9880 non-null   float64
 23  HomeCorner                     9880 non-null   float64
 24  AwayCorner                     9880 non-null   float64
 25  HomeYellow                     9880 non-null   float64
 26  AwayYellow                     9880 non-null   float64
 27  HomeRed                        9880 non-null   float64
 28  AwayRed                        9880 non-null   float64
 29  XGHome                         2548 non-null   float64
 30  XGAway                         2548 non-null   float64
 31  SeasonPosHome                  12704 non-null  float64
 32  SeasonPlayedHome               12704 non-null  float64
 33  SeasonWinHome                  12704 non-null  float64
 34  SeasonDrawHome                 12704 non-null  float64
 35  SeasonLossHome                 12704 non-null  float64
 36  SeasonGFHome                   12704 non-null  float64
 37  SeasonGAHome                   12704 non-null  float64
 38  SeasonGDHome                   12704 non-null  float64
 39  SeasonPointsHome               12704 non-null  float64
 40  QualificationOrRelegationHome  12704 non-null  object
 41  SeasonPosAway                  10800 non-null  float64
 42  SeasonPlayedAway               10800 non-null  float64
 43  SeasonWinAway                  10800 non-null  float64
 44  SeasonDrawAway                 10800 non-null  float64
 45  SeasonLossAway                 10800 non-null  float64
 46  SeasonGFAway                   10800 non-null  float64
 47  SeasonGAAway                   10800 non-null  float64
 48  SeasonGDAway                   10800 non-null  float64
 49  SeasonPointsAway               10800 non-null  float64
 50  QualificationOrRelegationAway  10800 non-null  object
dtypes: float64(36), int64(5), object(10)
memory usage: 4.9+ MB

In [5]:
df.describe()

,Year,Month,Day,Round,HomeGoal,AwayGoal,HomeGoal-HalfTime,AwayGoal-HalfTime,Attendance,HomeShot,AwayShot,HomeOnTargetShot,AwayOnTargetShot,HomeFoul,AwayFoul,HomeCorner,AwayCorner,HomeYellow,AwayYellow,HomeRed,AwayRed,XGHome,XGAway,SeasonPosHome,SeasonPlayedHome,SeasonWinHome,SeasonDrawHome,SeasonLossHome,SeasonGFHome,SeasonGAHome,SeasonGDHome,SeasonPointsHome,SeasonPosAway,SeasonPlayedAway,SeasonWinAway,SeasonDrawAway,SeasonLossAway,SeasonGFAway,SeasonGAAway,SeasonGDAway,SeasonPointsAway
count,12704.000000,12704.000000,12704.000000,2548.000000,12704.000000,12704.000000,11780.000000,11780.00000,1466.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,2548.000000,2548.000000,12704.000000,12704.000000,12704.000000,12704.000000,12704.000000,12704.000000,12704.000000,12704.000000,12704.000000,10800.000000,10800.000000,10800.000000,10800.000000,10800.000000,10800.000000,10800.000000,10800.000000,10800.000000
mean,2009.288256,6.710957,15.987878,18.808870,1.530856,1.165617,0.691341,0.51129,36883.063438,13.620648,10.817409,5.923583,4.663563,11.261032,11.743421,6.012551,4.763968,1.473279,1.800202,0.062146,0.084312,1.352669,1.295055,10.574229,38.290932,14.332336,9.835013,14.123583,51.860595,51.473630,0.372009,52.795104,10.460093,38.326667,14.420093,9.947222,13.959352,51.330093,50.377593,0.952500,53.192222
std,9.650389,3.892201,9.044269,10.752341,1.303925,1.145536,0.838506,0.73177,17535.090496,5.333120,4.695642,3.245798,2.732529,3.734316,3.904293,3.097538,2.751870,1.217718,1.291253,0.252899,0.288591,0.793840,0.752955,5.815757,1.038832,5.786602,3.083837,5.454426,15.353875,13.045018,25.141342,16.682710,5.821454,1.095476,5.764083,3.170436,5.377302,15.105819,12.499068,24.896568,16.571505
min,1993.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,2000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,38.000000,1.000000,2.000000,0.000000,20.000000,15.000000,-69.000000,11.000000,1.000000,38.000000,1.000000,2.000000,0.000000,20.000000,15.000000,-69.000000,11.000000
25%,2001.000000,3.000000,8.000000,10.000000,1.000000,0.000000,0.000000,0.00000,24460.000000,10.000000,7.000000,4.000000,3.000000,9.000000,9.000000,4.000000,3.000000,1.000000,1.000000,0.000000,0.000000,0.700000,0.700000,6.000000,38.000000,10.000000,8.000000,10.000000,41.000000,43.000000,-16.000000,41.000000,5.000000,38.000000,10.000000,8.000000,10.000000,41.000000,42.000000,-16.000000,42.000000
50%,2009.000000,8.000000,16.000000,19.000000,1.000000,1.000000,0.000000,0.00000,32228.500000,13.000000,10.000000,5.000000,4.000000,11.000000,11.000000,6.000000,4.000000,1.000000,2.000000,0.000000,0.000000,1.200000,1.200000,11.000000,38.000000,13.000000,10.000000,15.000000,48.000000,51.000000,-4.000000,50.000000,10.000000,38.000000,13.000000,10.000000,14.000000,48.000000,51.000000,-3.000000,50.000000
75%,2018.000000,10.000000,24.000000,28.000000,2.000000,2.000000,1.000000,1.00000,53110.000000,17.000000,14.000000,8.000000,6.000000,14.000000,14.000000,8.000000,6.000000,2.000000,3.000000,0.000000,0.000000,1.800000,1.700000,16.000000,38.000000,18.000000,12.000000,18.000000,60.000000,59.000000,15.000000,64.000000,15.000000,38.000000,18.000000,12.000000,18.000000,60.000000,58.000000,18.000000,65.000000
max,2026.000000,12.000000,31.000000,38.000000,9.000000,9.000000,5.000000,5.00000,74147.000000,43.000000,37.000000,24.000000,20.000000,33.000000,29.000000,20.000000,19.000000,7.000000,9.000000,3.000000,2.000000,5.900000,5.900000,22.000000,42.000000,32.000000,23.000000,29.000000,106.000000,104.000000,79.000000,100.000000,22.000000,42.000000,32.000000,23.000000,29.000000,106.000000,89.000000,79.000000,100.000000

In [6]:
df[ 'Season' ].min(), df[ 'Season' ].max()

('0001', '9900')

In [7]:
df.isna().sum()[ df.isna().sum() > 0].sort_values()

HomeGoal-HalfTime                  924
AwayGoal-HalfTime                  924
Result-HalfTime                    924
QualificationOrRelegationAway     1904
SeasonGDAway                      1904
SeasonGAAway                      1904
SeasonGFAway                      1904
SeasonLossAway                    1904
SeasonDrawAway                    1904
SeasonWinAway                     1904
SeasonPlayedAway                  1904
SeasonPosAway                     1904
SeasonPointsAway                  1904
AwayRed                           2824
HomeRed                           2824
AwayYellow                        2824
AwayCorner                        2824
HomeCorner                        2824
AwayFoul                          2824
HomeFoul                          2824
AwayOnTargetShot                  2824
HomeOnTargetShot                  2824
AwayShot                          2824
HomeShot                          2824
Referee                           2824
HomeYellow                        2824
XGHome                           10156
XGAway                           10156
Round                            10156
Time                             10156
WeekDay                          10156
Attendance                       11238
dtype: int64

In [8]:
null_count_per_season = df[df['Result-HalfTime'].isna()]['Season'].value_counts()
print(null_count_per_season)

Season
9394    462
9495    462
Name: count, dtype: int64

In [9]:
teams = df[(df['Season'] == '9394') & (df['Result-HalfTime'].isna())]['HomeTeam'].unique()
teams.sort()
teams

array(['Arsenal', 'Aston Villa', 'Blackburn', 'Chelsea', 'Coventry',
       'Everton', 'Ipswich', 'Leeds', 'Liverpool', 'Man City',
       'Man United', 'Newcastle', 'Norwich', 'Oldham', 'QPR', 'Sheffield',
       'Sheffield Weds', 'Southampton', 'Swindon', 'Tottenham',
       'West Ham', 'Wimbledon'], dtype=object)

In [10]:
df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 3, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

'''
df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']
'''

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'APR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man united') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Mancity'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']


df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 2, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Sheffoeld'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 2, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 3, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [4, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man united') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 2, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Swindon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'oldham') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

In [ ]:
array(['Arsenal', 'Aston Villa', 'Blackburn', 'Chelsea', 'Coventry',
       'Everton', 'Ipswich', 'Leeds', 'Liverpool', 'Man City',
       'Man United', 'Newcastle', 'Norwich', 'Oldham', 'QPR', 'Sheffield',
       'Sheffield Weds', 'Southampton', 'Swindon', 'Tottenham',
       'West Ham', 'Wimbledon'], dtype=object)

In [11]:
null_count_per_season = df[df['Result-HalfTime'].isna()]['Season'].value_counts()
print(null_count_per_season)

Season
9495    462
9394     22
Name: count, dtype: int64

In [12]:
matches = df[(df['Season'] == '9394') & (df['Result-HalfTime'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]
matches

           HomeTeam        AwayTeam  Year  Month  Day
1       Southampton         Everton  1993      8   14
23   Sheffield Weds         Arsenal  1993      8   21
32          Swindon       Liverpool  1993      8   22
84        Blackburn        West Ham  1993      9   18
178       Sheffield         Chelsea  1993     11   27
195      Man United         Norwich  1993     12    4
197         Arsenal       Tottenham  1993     12    6
207     Southampton             QPR  1993     12   11
228      Man United       Blackburn  1993     12   26
232         Ipswich        West Ham  1993     12   27
275        Coventry             QPR  1994      1   22
277       Liverpool        Man City  1994      1   22
293       Tottenham  Sheffield Weds  1994      2    5
319         Ipswich       Sheffield  1994      2   26
340       Sheffield           Leeds  1994      3   13
374     Southampton          Oldham  1994      3   30
380        Coventry       Wimbledon  1994      4    2
409        Coventry  Sheffield Weds  1994      4   16
413       Liverpool       Newcastle  1994      4   16
422      Man United        Man City  1994      4   23
434         Arsenal        West Ham  1994      4   30
450          Oldham       Tottenham  1994      5    5

In [13]:
df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Swindon') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Sheffield'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 1, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Oldham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9394') & (df['HomeTeam'] == 'Oldham') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

In [14]:
null_count_per_season = df[df['Result-HalfTime'].isna()]['Season'].value_counts()
print(null_count_per_season)

Season
9495    462
Name: count, dtype: int64

In [15]:
matches = df[(df['Season'] == '9495') & (df['Result-HalfTime'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]
matches

           HomeTeam        AwayTeam  Year  Month  Day
462        West Ham           Leeds  1994      8   20
463     Southampton       Blackburn  1994      8   20
464      Man United             QPR  1994      8   20
465  Sheffield Weds       Tottenham  1994      8   20
466         Everton     Aston Villa  1994      8   20
467  Crystal Palace       Liverpool  1994      8   20
468        Coventry       Wimbledon  1994      8   20
469         Chelsea         Norwich  1994      8   20
470         Ipswich      Nottingham  1994      8   20
471         Arsenal        Man City  1994      8   20
472       Leicester       Newcastle  1994      8   21
473      Nottingham      Man United  1994      8   22
474       Blackburn       Leicester  1994      8   23
475           Leeds         Arsenal  1994      8   23
476       Wimbledon         Ipswich  1994      8   23
477       Tottenham         Everton  1994      8   24
478             QPR  Sheffield Weds  1994      8   24
479     Aston Villa     Southampton  1994      8   24
480       Newcastle        Coventry  1994      8   24
481        Man City        West Ham  1994      8   24
482         Norwich  Crystal Palace  1994      8   24
483       Wimbledon  Sheffield Weds  1994      8   27
484             QPR         Ipswich  1994      8   27
485         Norwich        West Ham  1994      8   27
486       Tottenham      Man United  1994      8   27
487        Man City         Everton  1994      8   27
488       Newcastle     Southampton  1994      8   27
489     Aston Villa  Crystal Palace  1994      8   27
490      Nottingham       Leicester  1994      8   27
491       Blackburn        Coventry  1994      8   27
492           Leeds         Chelsea  1994      8   27
493       Liverpool         Arsenal  1994      8   28
494        Coventry     Aston Villa  1994      8   29
495  Crystal Palace           Leeds  1994      8   30
496         Everton      Nottingham  1994      8   30
497         Ipswich       Tottenham  1994      8   30
498         Arsenal       Blackburn  1994      8   31
499         Chelsea        Man City  1994      8   31
500       Leicester             QPR  1994      8   31
501      Man United       Wimbledon  1994      8   31
502  Sheffield Weds         Norwich  1994      8   31
503     Southampton       Liverpool  1994      8   31
504        West Ham       Newcastle  1994      8   31
505       Wimbledon       Leicester  1994      9   10
506      Nottingham  Sheffield Weds  1994      9   10
507             QPR        Coventry  1994      9   10
508        Man City  Crystal Palace  1994      9   10
509       Newcastle         Chelsea  1994      9   10
510     Aston Villa         Ipswich  1994      9   10
511         Norwich         Arsenal  1994      9   10
512       Blackburn         Everton  1994      9   10
513       Liverpool        West Ham  1994      9   10
514           Leeds      Man United  1994      9   11
515       Tottenham     Southampton  1994      9   12
516        West Ham     Aston Villa  1994      9   17
517  Sheffield Weds        Man City  1994      9   17
518     Southampton      Nottingham  1994      9   17
519         Everton             QPR  1994      9   17
520  Crystal Palace       Wimbledon  1994      9   17
521        Coventry           Leeds  1994      9   17
522       Leicester       Tottenham  1994      9   17
523      Man United       Liverpool  1994      9   17
524         Arsenal       Newcastle  1994      9   18
525         Chelsea       Blackburn  1994      9   18
526         Ipswich         Norwich  1994      9   19
527       Newcastle       Liverpool  1994      9   24
528       Tottenham      Nottingham  1994      9   24
529             QPR       Wimbledon  1994      9   24
530        Man City         Norwich  1994      9   24
531         Everton       Leicester  1994      9   24
532       Blackburn     Aston Villa  1994      9   24
533         Ipswich      Man United  1994      9   24
534        Coventry     Southampton  1994      9   24
535  Crystal Palace         Chelsea  1994      9   24
536        West Ham         Arsenal  1994      9   25
537  Sheffield Weds           Leeds  1994      9   26
538     Aston Villa       Newcastle  1994     10    1
539           Leeds        Man City  1994     10    1
540       Liverpool  Sheffield Weds  1994     10    1
541      Man United         Everton  1994     10    1
542         Norwich       Blackburn  1994     10    1
543       Wimbledon       Tottenham  1994     10    1
544         Arsenal  Crystal Palace  1994     10    1
545     Southampton         Ipswich  1994     10    1
546         Chelsea        West Ham  1994     10    2
547      Nottingham             QPR  1994     10    2
548       Leicester        Coventry  1994     10    3
549       Tottenham             QPR  1994     10    8
550       Wimbledon         Arsenal  1994     10    8
551        West Ham  Crystal Palace  1994     10    8
552     Southampton         Everton  1994     10    8
553         Norwich           Leeds  1994     10    8
554        Man City      Nottingham  1994     10    8
555       Liverpool     Aston Villa  1994     10    8
556         Chelsea       Leicester  1994     10    8
557  Sheffield Weds      Man United  1994     10    8
558       Newcastle       Blackburn  1994     10    9
559        Coventry         Ipswich  1994     10   10
560             QPR        Man City  1994     10   15
561      Man United        West Ham  1994     10   15
562       Leicester     Southampton  1994     10   15
563         Everton        Coventry  1994     10   15
564  Crystal Palace       Newcastle  1994     10   15
565       Blackburn       Liverpool  1994     10   15
566     Aston Villa         Norwich  1994     10   15
567         Arsenal         Chelsea  1994     10   15
568           Leeds       Tottenham  1994     10   15
569         Ipswich  Sheffield Weds  1994     10   16
570      Nottingham       Wimbledon  1994     10   17
571         Norwich             QPR  1994     10   22
572        West Ham     Southampton  1994     10   22
573       Newcastle  Sheffield Weds  1994     10   22
574        Man City       Tottenham  1994     10   22
575     Aston Villa      Nottingham  1994     10   22
576       Liverpool       Wimbledon  1994     10   22
577  Crystal Palace         Everton  1994     10   22
578         Arsenal        Coventry  1994     10   23
579       Blackburn      Man United  1994     10   23
580         Chelsea         Ipswich  1994     10   23
581           Leeds       Leicester  1994     10   24
582       Tottenham        West Ham  1994     10   29
583     Southampton           Leeds  1994     10   29
584  Sheffield Weds         Chelsea  1994     10   29
585             QPR     Aston Villa  1994     10   29
586      Nottingham       Blackburn  1994     10   29
587         Ipswich       Liverpool  1994     10   29
588         Everton         Arsenal  1994     10   29
589        Coventry        Man City  1994     10   29
590       Leicester  Crystal Palace  1994     10   29
591      Man United       Newcastle  1994     10   29
592       Wimbledon         Norwich  1994     10   30
593             QPR       Liverpool  1994     10   31
594         Everton        West Ham  1994     11    1
595         Ipswich           Leeds  1994     11    1
596        Coventry  Crystal Palace  1994     11    2
597  Sheffield Weds       Blackburn  1994     11    2
598     Southampton         Norwich  1994     11    2
599       Blackburn       Tottenham  1994     11    5
600  Crystal Palace         Ipswich  1994     11    5
601           Leeds       Wimbledon  1994     11    5
602       Liverpool      Nottingham  1994     11    5
603        Man City     Southampton  1994     11    5
604       Newcastle             QPR  1994     11    5
605         Norwich         Everton  1994     11    5
606        West Ham       Leicester  1994     11    5
607     Aston Villa      Man United  1994     11    6
608         Arsenal  Sheffield Weds  1994     11    6
609         Chelsea        Coventry  1994     11    6
610      Nottingham       Newcastle  1994     11    7
611       Liverpool         Chelsea  1994     11    9
612       Wimbledon     Aston Villa  1994     11    9
613      Man United        Man City  1994     11   10
614       Wimbledon       Newcastle  1994     11   19
615       Tottenham     Aston Villa  1994     11   19
616     Southampton         Arsenal  1994     11   19
617  Sheffield Weds        West Ham  1994     11   19
618      Nottingham         Chelsea  1994     11   19
619      Man United  Crystal Palace  1994     11   19
620         Ipswich       Blackburn  1994     11   19
621        Coventry         Norwich  1994     11   19
622             QPR           Leeds  1994     11   19
623       Leicester        Man City  1994     11   20
624         Everton       Liverpool  1994     11   21
625       Leicester         Arsenal  1994     11   23
626       Tottenham         Chelsea  1994     11   23
627        West Ham        Coventry  1994     11   26
628         Norwich       Leicester  1994     11   26
629       Newcastle         Ipswich  1994     11   26
630        Man City       Wimbledon  1994     11   26
631           Leeds      Nottingham  1994     11   26
632  Crystal Palace     Southampton  1994     11   26
633         Chelsea         Everton  1994     11   26
634       Blackburn             QPR  1994     11   26
635         Arsenal      Man United  1994     11   26
636       Liverpool       Tottenham  1994     11   26
637     Aston Villa  Sheffield Weds  1994     11   27
638       Tottenham       Newcastle  1994     12    3
639       Wimbledon       Blackburn  1994     12    3
640     Southampton         Chelsea  1994     12    3
641      Nottingham         Arsenal  1994     12    3
642        Coventry       Liverpool  1994     12    3
643      Man United         Norwich  1994     12    3
644       Leicester     Aston Villa  1994     12    3
645  Sheffield Weds  Crystal Palace  1994     12    3
646         Ipswich        Man City  1994     12    3
647         Everton           Leeds  1994     12    4
648             QPR        West Ham  1994     12    4
649       Wimbledon        Coventry  1994     12   10
650       Tottenham  Sheffield Weds  1994     12   10
651             QPR      Man United  1994     12   10
652      Nottingham         Ipswich  1994     12   10
653           Leeds        West Ham  1994     12   10
654       Blackburn     Southampton  1994     12   10
655     Aston Villa         Everton  1994     12   10
656       Newcastle       Leicester  1994     12   10
657         Norwich         Chelsea  1994     12   10
658       Liverpool  Crystal Palace  1994     12   11
659        Man City         Arsenal  1994     12   12
660         Ipswich       Wimbledon  1994     12   16
661  Sheffield Weds             QPR  1994     12   17
662        West Ham        Man City  1994     12   17
663      Man United      Nottingham  1994     12   17
664        Coventry       Newcastle  1994     12   17
665         Everton       Tottenham  1994     12   17
666  Crystal Palace         Norwich  1994     12   17
667         Arsenal           Leeds  1994     12   17
668       Leicester       Blackburn  1994     12   17
669         Chelsea       Liverpool  1994     12   18
670     Southampton     Aston Villa  1994     12   19
671        West Ham         Ipswich  1994     12   26
672     Southampton       Wimbledon  1994     12   26
673         Norwich       Tottenham  1994     12   26
674        Man City       Blackburn  1994     12   26
675       Leicester       Liverpool  1994     12   26
676         Everton  Sheffield Weds  1994     12   26
677  Crystal Palace             QPR  1994     12   26
678        Coventry      Nottingham  1994     12   26
679         Chelsea      Man United  1994     12   26
680         Arsenal     Aston Villa  1994     12   26
681           Leeds       Newcastle  1994     12   26
682      Nottingham         Norwich  1994     12   27
683       Tottenham  Crystal Palace  1994     12   27
684       Wimbledon        West Ham  1994     12   28
685  Sheffield Weds        Coventry  1994     12   28
686       Liverpool        Man City  1994     12   28
687      Man United       Leicester  1994     12   28
688         Ipswich         Arsenal  1994     12   28
689     Aston Villa         Chelsea  1994     12   28
690             QPR     Southampton  1994     12   28
691        West Ham      Nottingham  1994     12   31
692     Southampton      Man United  1994     12   31
693         Norwich       Newcastle  1994     12   31
694        Man City     Aston Villa  1994     12   31
695       Leicester  Sheffield Weds  1994     12   31
696         Everton         Ipswich  1994     12   31
697  Crystal Palace       Blackburn  1994     12   31
698        Coventry       Tottenham  1994     12   31
699         Chelsea       Wimbledon  1994     12   31
700         Arsenal             QPR  1994     12   31
701           Leeds       Liverpool  1994     12   31
702       Tottenham         Arsenal  1995      1    2
703  Sheffield Weds     Southampton  1995      1    2
704       Wimbledon         Everton  1995      1    2
705      Nottingham  Crystal Palace  1995      1    2
706       Newcastle        Man City  1995      1    2
707       Blackburn        West Ham  1995      1    2
708     Aston Villa           Leeds  1995      1    2
709         Ipswich       Leicester  1995      1    2
710       Liverpool         Norwich  1995      1    2
711      Man United        Coventry  1995      1    3
712       Blackburn      Nottingham  1995      1   14
713         Chelsea  Sheffield Weds  1995      1   14
714  Crystal Palace       Leicester  1995      1   14
715           Leeds     Southampton  1995      1   14
716       Liverpool         Ipswich  1995      1   14
717        Man City        Coventry  1995      1   14
718         Arsenal         Everton  1995      1   14
719        West Ham       Tottenham  1995      1   14
720     Aston Villa             QPR  1995      1   14
721         Norwich       Wimbledon  1995      1   14
722       Newcastle      Man United  1995      1   15
723        Coventry         Arsenal  1995      1   21
724         Everton  Crystal Palace  1995      1   21
725         Ipswich         Chelsea  1995      1   21
726      Nottingham     Aston Villa  1995      1   21
727  Sheffield Weds       Newcastle  1995      1   21
728      Man United       Blackburn  1995      1   22
729        West Ham  Sheffield Weds  1995      1   23
730           Leeds             QPR  1995      1   24
731       Liverpool         Everton  1995      1   24
732         Arsenal     Southampton  1995      1   24
733     Aston Villa       Tottenham  1995      1   25
734         Chelsea      Nottingham  1995      1   25
735  Crystal Palace      Man United  1995      1   25
736        Man City       Leicester  1995      1   25
737       Newcastle       Wimbledon  1995      1   25
738         Norwich        Coventry  1995      1   25
739       Blackburn         Ipswich  1995      1   28
740       Blackburn           Leeds  1995      2    1
741       Newcastle         Everton  1995      2    1
742  Sheffield Weds         Arsenal  1995      2    4
743     Southampton        Man City  1995      2    4
744             QPR       Newcastle  1995      2    4
745       Wimbledon           Leeds  1995      2    4
746      Man United     Aston Villa  1995      2    4
747       Leicester        West Ham  1995      2    4
748         Ipswich  Crystal Palace  1995      2    4
749         Everton         Norwich  1995      2    4
750        Coventry         Chelsea  1995      2    4
751      Nottingham       Liverpool  1995      2    4
752       Tottenham       Blackburn  1995      2    5
753         Norwich     Southampton  1995      2   11
754       Newcastle      Nottingham  1995      2   11
755        Man City      Man United  1995      2   11
756         Arsenal       Leicester  1995      2   11
757  Crystal Palace        Coventry  1995      2   11
758     Aston Villa       Wimbledon  1995      2   11
759       Liverpool             QPR  1995      2   11
760         Chelsea       Tottenham  1995      2   11
761       Blackburn  Sheffield Weds  1995      2   12
762        West Ham         Everton  1995      2   13
763        Coventry        West Ham  1995      2   18
764  Sheffield Weds     Aston Villa  1995      2   18
765         Arsenal      Nottingham  1995      2   21
766     Aston Villa       Leicester  1995      2   22
767           Leeds         Everton  1995      2   22
768        Man City         Ipswich  1995      2   22
769         Norwich      Man United  1995      2   22
770       Blackburn       Wimbledon  1995      2   22
771  Sheffield Weds       Liverpool  1995      2   25
772        West Ham         Chelsea  1995      2   25
773       Tottenham       Wimbledon  1995      2   25
774       Newcastle     Aston Villa  1995      2   25
775         Ipswich     Southampton  1995      2   25
776        Man City           Leeds  1995      2   25
777       Blackburn         Norwich  1995      2   25
778        Coventry       Leicester  1995      2   25
779         Everton      Man United  1995      2   25
780  Crystal Palace         Arsenal  1995      2   25
781             QPR      Nottingham  1995      2   26
782         Ipswich       Newcastle  1995      2   28
783     Aston Villa       Blackburn  1995      3    4
784           Leeds  Sheffield Weds  1995      3    4
785       Leicester         Everton  1995      3    4
786      Man United         Ipswich  1995      3    4
787         Norwich        Man City  1995      3    4
788      Nottingham       Tottenham  1995      3    4
789     Southampton        Coventry  1995      3    4
790       Wimbledon             QPR  1995      3    4
791       Liverpool       Newcastle  1995      3    4
792         Arsenal        West Ham  1995      3    5
793         Chelsea  Crystal Palace  1995      3    5
794     Aston Villa        Coventry  1995      3    6
795       Wimbledon      Man United  1995      3    7
796       Newcastle        West Ham  1995      3    8
797       Blackburn         Arsenal  1995      3    8
798       Tottenham         Ipswich  1995      3    8
799        Man City         Chelsea  1995      3    8
800      Nottingham         Everton  1995      3    8
801             QPR       Leicester  1995      3    8
802         Norwich  Sheffield Weds  1995      3    8
803       Leicester      Nottingham  1995      3   11
804  Sheffield Weds       Wimbledon  1995      3   11
805        West Ham         Norwich  1995      3   11
806         Chelsea           Leeds  1995      3   11
807        Coventry       Blackburn  1995      3   11
808  Crystal Palace  Sheffield Weds  1995      3   14
809       Liverpool        Coventry  1995      3   14
810       Leicester           Leeds  1995      3   15
811      Man United       Tottenham  1995      3   15
812             QPR         Norwich  1995      3   15
813     Southampton        West Ham  1995      3   15
814         Everton        Man City  1995      3   15
815             QPR         Everton  1995      3   18
816       Wimbledon  Crystal Palace  1995      3   18
817       Tottenham       Leicester  1995      3   18
818           Leeds        Coventry  1995      3   18
819        Man City  Sheffield Weds  1995      3   18
820      Nottingham     Southampton  1995      3   18
821     Aston Villa        West Ham  1995      3   18
822       Blackburn         Chelsea  1995      3   18
823       Liverpool      Man United  1995      3   19
824       Newcastle         Arsenal  1995      3   19
825         Norwich         Ipswich  1995      3   20
826       Wimbledon        Man City  1995      3   21
827       Tottenham       Liverpool  1995      3   22
828     Southampton       Newcastle  1995      3   22
829      Nottingham           Leeds  1995      3   22
830      Man United         Arsenal  1995      3   22

In [18]:
matches[:25]

           HomeTeam        AwayTeam  Year  Month  Day
462        West Ham           Leeds  1994      8   20
463     Southampton       Blackburn  1994      8   20
464      Man United             QPR  1994      8   20
465  Sheffield Weds       Tottenham  1994      8   20
466         Everton     Aston Villa  1994      8   20
467  Crystal Palace       Liverpool  1994      8   20
468        Coventry       Wimbledon  1994      8   20
469         Chelsea         Norwich  1994      8   20
470         Ipswich      Nottingham  1994      8   20
471         Arsenal        Man City  1994      8   20
472       Leicester       Newcastle  1994      8   21
473      Nottingham      Man United  1994      8   22
474       Blackburn       Leicester  1994      8   23
475           Leeds         Arsenal  1994      8   23
476       Wimbledon         Ipswich  1994      8   23
477       Tottenham         Everton  1994      8   24
478             QPR  Sheffield Weds  1994      8   24
479     Aston Villa     Southampton  1994      8   24
480       Newcastle        Coventry  1994      8   24
481        Man City        West Ham  1994      8   24
482         Norwich  Crystal Palace  1994      8   24
483       Wimbledon  Sheffield Weds  1994      8   27
484             QPR         Ipswich  1994      8   27
485         Norwich        West Ham  1994      8   27
486       Tottenham      Man United  1994      8   27

In [19]:
# 1. West Ham vs Leeds | 1994-08-20
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 20) & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

# 2. Southampton vs Blackburn | 1994-08-20
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 20) & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

# 3. Man United vs QPR | 1994-08-20
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 20) & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

# 4. Sheffield Weds vs Tottenham | 1994-08-20
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 20) & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

# 5. Everton vs Aston Villa | 1994-08-20
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 20) & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

# 6. Crystal Palace vs Liverpool | 1994-08-20
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 20) & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 3, 'A']

# 7. Coventry vs Wimbledon | 1994-08-20
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 20) & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

# 8. Chelsea vs Norwich | 1994-08-20
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 20) & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

# 9. Ipswich vs Nottingham | 1994-08-20
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 20) & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Nottingham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

# 10. Arsenal vs Man City | 1994-08-20
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 20) & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

# 11. Leicester vs Newcastle | 1994-08-21
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 21) & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

# 12. Nottingham vs Man United | 1994-08-22
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 22) & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

# 13. Blackburn vs Leicester | 1994-08-23
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 23) & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Leicester'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

# 14. Leeds vs Arsenal | 1994-08-23
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 23) & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

# 15. Wimbledon vs Ipswich | 1994-08-23
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 23) & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

# 16. Tottenham vs Everton | 1994-08-24
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 24) & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

# 17. QPR vs Sheffield Weds | 1994-08-24
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 24) & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

# 18. Aston Villa vs Southampton | 1994-08-24
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 24) & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

# 19. Newcastle vs Coventry | 1994-08-24
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 24) & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 0, 'H']

# 20. Man City vs West Ham | 1994-08-24
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 24) & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

# 21. Norwich vs Crystal Palace | 1994-08-24
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 24) & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Crystal Palace'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

# 22. Wimbledon vs Sheffield Weds | 1994-08-27
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 27) & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

# 23. QPR vs Ipswich | 1994-08-27
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 27) & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

# 24. Norwich vs West Ham | 1994-08-27
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 27) & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

# 25. Tottenham vs Man United | 1994-08-27
df.loc[
    (df['Year'] == 1994) & (df['Month'] == 8) & (df['Day'] == 27) & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

In [20]:
matches[25:50]

           HomeTeam        AwayTeam  Year  Month  Day
487        Man City         Everton  1994      8   27
488       Newcastle     Southampton  1994      8   27
489     Aston Villa  Crystal Palace  1994      8   27
490      Nottingham       Leicester  1994      8   27
491       Blackburn        Coventry  1994      8   27
492           Leeds         Chelsea  1994      8   27
493       Liverpool         Arsenal  1994      8   28
494        Coventry     Aston Villa  1994      8   29
495  Crystal Palace           Leeds  1994      8   30
496         Everton      Nottingham  1994      8   30
497         Ipswich       Tottenham  1994      8   30
498         Arsenal       Blackburn  1994      8   31
499         Chelsea        Man City  1994      8   31
500       Leicester             QPR  1994      8   31
501      Man United       Wimbledon  1994      8   31
502  Sheffield Weds         Norwich  1994      8   31
503     Southampton       Liverpool  1994      8   31
504        West Ham       Newcastle  1994      8   31
505       Wimbledon       Leicester  1994      9   10
506      Nottingham  Sheffield Weds  1994      9   10
507             QPR        Coventry  1994      9   10
508        Man City  Crystal Palace  1994      9   10
509       Newcastle         Chelsea  1994      9   10
510     Aston Villa         Ipswich  1994      9   10
511         Norwich         Arsenal  1994      9   10

In [22]:
# 27/08/1994
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [3, 0, 'H']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham Forest') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 2, 'A']

# 28/08/1994
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [3, 0, 'H']

# 29/08/1994
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# 30/08/1994
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Nottingham Forest'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 2, 'A']

# 31/08/1994
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 2, 'A']

# 10/09/1994
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham Forest') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 1, 'H']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

In [21]:
matches[50:75]

           HomeTeam     AwayTeam  Year  Month  Day
512       Blackburn      Everton  1994      9   10
513       Liverpool     West Ham  1994      9   10
514           Leeds   Man United  1994      9   11
515       Tottenham  Southampton  1994      9   12
516        West Ham  Aston Villa  1994      9   17
517  Sheffield Weds     Man City  1994      9   17
518     Southampton   Nottingham  1994      9   17
519         Everton          QPR  1994      9   17
520  Crystal Palace    Wimbledon  1994      9   17
521        Coventry        Leeds  1994      9   17
522       Leicester    Tottenham  1994      9   17
523      Man United    Liverpool  1994      9   17
524         Arsenal    Newcastle  1994      9   18
525         Chelsea    Blackburn  1994      9   18
526         Ipswich      Norwich  1994      9   19
527       Newcastle    Liverpool  1994      9   24
528       Tottenham   Nottingham  1994      9   24
529             QPR    Wimbledon  1994      9   24
530        Man City      Norwich  1994      9   24
531         Everton    Leicester  1994      9   24
532       Blackburn  Aston Villa  1994      9   24
533         Ipswich   Man United  1994      9   24
534        Coventry  Southampton  1994      9   24
535  Crystal Palace      Chelsea  1994      9   24
536        West Ham      Arsenal  1994      9   25

In [25]:
# 10/09/1994
# Blackburn 3-0 Everton (HT: 2-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# Liverpool 0-0 West Ham (HT: 0-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# 11/09/1994
# Leeds 2-1 Man United (HT: 1-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# 12/09/1994
# Tottenham 1-2 Southampton (HT: 1-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# 17/09/1994
# West Ham 1-0 Aston Villa (HT: 0-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# Sheffield Weds 1-1 Man City (HT: 0-1)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# Southampton 1-1 Nottingham Forest (HT: 0-1)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# Everton 2-2 QPR (HT: 2-1)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 1, 'H']

# Crystal Palace 0-0 Wimbledon (HT: 0-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# Coventry 2-1 Leeds (HT: 0-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# Leicester 3-1 Tottenham (HT: 0-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# Man United 2-0 Liverpool (HT: 0-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# 18/09/1994
# Arsenal 2-3 Newcastle (HT: 1-2)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 2, 'A']

# Chelsea 1-2 Blackburn (HT: 0-1)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# 19/09/1994
# Ipswich 1-2 Norwich (HT: 1-1)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# 24/09/1994
# Newcastle 1-1 Liverpool (HT: 0-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# Tottenham 1-4 Nottingham Forest (HT: 1-1)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# QPR 0-1 Wimbledon (HT: 0-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# Man City 2-0 Norwich (HT: 0-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# Everton 1-1 Leicester (HT: 0-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# Blackburn 3-1 Aston Villa (HT: 1-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# Ipswich 3-2 Man United (HT: 0-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# Coventry 1-3 Southampton (HT: 1-1)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# Crystal Palace 0-1 Chelsea (HT: 0-0)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# 25/09/1994
# West Ham 0-2 Arsenal (HT: 0-1)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

In [24]:
matches[75:125]

           HomeTeam        AwayTeam  Year  Month  Day
537  Sheffield Weds           Leeds  1994      9   26
538     Aston Villa       Newcastle  1994     10    1
539           Leeds        Man City  1994     10    1
540       Liverpool  Sheffield Weds  1994     10    1
541      Man United         Everton  1994     10    1
542         Norwich       Blackburn  1994     10    1
543       Wimbledon       Tottenham  1994     10    1
544         Arsenal  Crystal Palace  1994     10    1
545     Southampton         Ipswich  1994     10    1
546         Chelsea        West Ham  1994     10    2
547      Nottingham             QPR  1994     10    2
548       Leicester        Coventry  1994     10    3
549       Tottenham             QPR  1994     10    8
550       Wimbledon         Arsenal  1994     10    8
551        West Ham  Crystal Palace  1994     10    8
552     Southampton         Everton  1994     10    8
553         Norwich           Leeds  1994     10    8
554        Man City      Nottingham  1994     10    8
555       Liverpool     Aston Villa  1994     10    8
556         Chelsea       Leicester  1994     10    8
557  Sheffield Weds      Man United  1994     10    8
558       Newcastle       Blackburn  1994     10    9
559        Coventry         Ipswich  1994     10   10
560             QPR        Man City  1994     10   15
561      Man United        West Ham  1994     10   15
562       Leicester     Southampton  1994     10   15
563         Everton        Coventry  1994     10   15
564  Crystal Palace       Newcastle  1994     10   15
565       Blackburn       Liverpool  1994     10   15
566     Aston Villa         Norwich  1994     10   15
567         Arsenal         Chelsea  1994     10   15
568           Leeds       Tottenham  1994     10   15
569         Ipswich  Sheffield Weds  1994     10   16
570      Nottingham       Wimbledon  1994     10   17
571         Norwich             QPR  1994     10   22
572        West Ham     Southampton  1994     10   22
573       Newcastle  Sheffield Weds  1994     10   22
574        Man City       Tottenham  1994     10   22
575     Aston Villa      Nottingham  1994     10   22
576       Liverpool       Wimbledon  1994     10   22
577  Crystal Palace         Everton  1994     10   22
578         Arsenal        Coventry  1994     10   23
579       Blackburn      Man United  1994     10   23
580         Chelsea         Ipswich  1994     10   23
581           Leeds       Leicester  1994     10   24
582       Tottenham        West Ham  1994     10   29
583     Southampton           Leeds  1994     10   29
584  Sheffield Weds         Chelsea  1994     10   29
585             QPR     Aston Villa  1994     10   29
586      Nottingham       Blackburn  1994     10   29

In [26]:
# بازی 537
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 538
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 539
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 540
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 541
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 542
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 543
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 544
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 545
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 546
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 547
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 548
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 549
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 550
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 551
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 552
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 553
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 554
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 555
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 1, 'H']

# بازی 556
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 557
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 558
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 559
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 560
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 561
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 562
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [3, 0, 'H']

# بازی 563
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 2, 'A']

# بازی 564
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 565
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 566
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 567
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 568
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 569
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 570
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 571
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 572
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 573
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 574
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [3, 1, 'H']

# بازی 575
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 576
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 577
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 578
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 579
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 580
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 581
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 582
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 583
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 584
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 585
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 586
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

In [28]:
matches[125:200]

           HomeTeam        AwayTeam  Year  Month  Day
587         Ipswich       Liverpool  1994     10   29
588         Everton         Arsenal  1994     10   29
589        Coventry        Man City  1994     10   29
590       Leicester  Crystal Palace  1994     10   29
591      Man United       Newcastle  1994     10   29
592       Wimbledon         Norwich  1994     10   30
593             QPR       Liverpool  1994     10   31
594         Everton        West Ham  1994     11    1
595         Ipswich           Leeds  1994     11    1
596        Coventry  Crystal Palace  1994     11    2
597  Sheffield Weds       Blackburn  1994     11    2
598     Southampton         Norwich  1994     11    2
599       Blackburn       Tottenham  1994     11    5
600  Crystal Palace         Ipswich  1994     11    5
601           Leeds       Wimbledon  1994     11    5
602       Liverpool      Nottingham  1994     11    5
603        Man City     Southampton  1994     11    5
604       Newcastle             QPR  1994     11    5
605         Norwich         Everton  1994     11    5
606        West Ham       Leicester  1994     11    5
607     Aston Villa      Man United  1994     11    6
608         Arsenal  Sheffield Weds  1994     11    6
609         Chelsea        Coventry  1994     11    6
610      Nottingham       Newcastle  1994     11    7
611       Liverpool         Chelsea  1994     11    9
612       Wimbledon     Aston Villa  1994     11    9
613      Man United        Man City  1994     11   10
614       Wimbledon       Newcastle  1994     11   19
615       Tottenham     Aston Villa  1994     11   19
616     Southampton         Arsenal  1994     11   19
617  Sheffield Weds        West Ham  1994     11   19
618      Nottingham         Chelsea  1994     11   19
619      Man United  Crystal Palace  1994     11   19
620         Ipswich       Blackburn  1994     11   19
621        Coventry         Norwich  1994     11   19
622             QPR           Leeds  1994     11   19
623       Leicester        Man City  1994     11   20
624         Everton       Liverpool  1994     11   21
625       Leicester         Arsenal  1994     11   23
626       Tottenham         Chelsea  1994     11   23
627        West Ham        Coventry  1994     11   26
628         Norwich       Leicester  1994     11   26
629       Newcastle         Ipswich  1994     11   26
630        Man City       Wimbledon  1994     11   26
631           Leeds      Nottingham  1994     11   26
632  Crystal Palace     Southampton  1994     11   26
633         Chelsea         Everton  1994     11   26
634       Blackburn             QPR  1994     11   26
635         Arsenal      Man United  1994     11   26
636       Liverpool       Tottenham  1994     11   26
637     Aston Villa  Sheffield Weds  1994     11   27
638       Tottenham       Newcastle  1994     12    3
639       Wimbledon       Blackburn  1994     12    3
640     Southampton         Chelsea  1994     12    3
641      Nottingham         Arsenal  1994     12    3
642        Coventry       Liverpool  1994     12    3
643      Man United         Norwich  1994     12    3
644       Leicester     Aston Villa  1994     12    3
645  Sheffield Weds  Crystal Palace  1994     12    3
646         Ipswich        Man City  1994     12    3
647         Everton           Leeds  1994     12    4
648             QPR        West Ham  1994     12    4
649       Wimbledon        Coventry  1994     12   10
650       Tottenham  Sheffield Weds  1994     12   10
651             QPR      Man United  1994     12   10
652      Nottingham         Ipswich  1994     12   10
653           Leeds        West Ham  1994     12   10
654       Blackburn     Southampton  1994     12   10
655     Aston Villa         Everton  1994     12   10
656       Newcastle       Leicester  1994     12   10
657         Norwich         Chelsea  1994     12   10
658       Liverpool  Crystal Palace  1994     12   11
659        Man City         Arsenal  1994     12   12
660         Ipswich       Wimbledon  1994     12   16
661  Sheffield Weds             QPR  1994     12   17

In [29]:
# بازی 587
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 588
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 589
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 590
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 591
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 592
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 593
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 594
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 595
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 596
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 2, 'A']

# بازی 597
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 598
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 599
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 600
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 601
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [3, 1, 'H']

# بازی 602
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 603
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 604
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 605
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 606
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 607
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 608
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 609
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 610
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 611
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [3, 1, 'H']

# بازی 612
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 2, 'D']

# بازی 613
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 614
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 2, 'D']

# بازی 615
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 3, 'A']

# بازی 616
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 617
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 618
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 619
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 620
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 621
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 622
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 623
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 624
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 625
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 1, 'H']

# بازی 626
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 627
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 628
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 629
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 630
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 631
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 632
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 633
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 634
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 635
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 636
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 637
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 638
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 2, 'D']

# بازی 639
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 640
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 641
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 642
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 643
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 644
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 645
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 646
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 2, 'A']

# بازی 647
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 648
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 649
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 650
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 651
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 652
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [4, 1, 'H']

# بازی 653
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 1, 'H']

# بازی 654
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 655
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 656
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 1, 'H']

# بازی 657
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 658
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 659
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 2, 'A']

# بازی 660
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 661
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

In [30]:
matches[200:300]

           HomeTeam        AwayTeam  Year  Month  Day
662        West Ham        Man City  1994     12   17
663      Man United      Nottingham  1994     12   17
664        Coventry       Newcastle  1994     12   17
665         Everton       Tottenham  1994     12   17
666  Crystal Palace         Norwich  1994     12   17
667         Arsenal           Leeds  1994     12   17
668       Leicester       Blackburn  1994     12   17
669         Chelsea       Liverpool  1994     12   18
670     Southampton     Aston Villa  1994     12   19
671        West Ham         Ipswich  1994     12   26
672     Southampton       Wimbledon  1994     12   26
673         Norwich       Tottenham  1994     12   26
674        Man City       Blackburn  1994     12   26
675       Leicester       Liverpool  1994     12   26
676         Everton  Sheffield Weds  1994     12   26
677  Crystal Palace             QPR  1994     12   26
678        Coventry      Nottingham  1994     12   26
679         Chelsea      Man United  1994     12   26
680         Arsenal     Aston Villa  1994     12   26
681           Leeds       Newcastle  1994     12   26
682      Nottingham         Norwich  1994     12   27
683       Tottenham  Crystal Palace  1994     12   27
684       Wimbledon        West Ham  1994     12   28
685  Sheffield Weds        Coventry  1994     12   28
686       Liverpool        Man City  1994     12   28
687      Man United       Leicester  1994     12   28
688         Ipswich         Arsenal  1994     12   28
689     Aston Villa         Chelsea  1994     12   28
690             QPR     Southampton  1994     12   28
691        West Ham      Nottingham  1994     12   31
692     Southampton      Man United  1994     12   31
693         Norwich       Newcastle  1994     12   31
694        Man City     Aston Villa  1994     12   31
695       Leicester  Sheffield Weds  1994     12   31
696         Everton         Ipswich  1994     12   31
697  Crystal Palace       Blackburn  1994     12   31
698        Coventry       Tottenham  1994     12   31
699         Chelsea       Wimbledon  1994     12   31
700         Arsenal             QPR  1994     12   31
701           Leeds       Liverpool  1994     12   31
702       Tottenham         Arsenal  1995      1    2
703  Sheffield Weds     Southampton  1995      1    2
704       Wimbledon         Everton  1995      1    2
705      Nottingham  Crystal Palace  1995      1    2
706       Newcastle        Man City  1995      1    2
707       Blackburn        West Ham  1995      1    2
708     Aston Villa           Leeds  1995      1    2
709         Ipswich       Leicester  1995      1    2
710       Liverpool         Norwich  1995      1    2
711      Man United        Coventry  1995      1    3
712       Blackburn      Nottingham  1995      1   14
713         Chelsea  Sheffield Weds  1995      1   14
714  Crystal Palace       Leicester  1995      1   14
715           Leeds     Southampton  1995      1   14
716       Liverpool         Ipswich  1995      1   14
717        Man City        Coventry  1995      1   14
718         Arsenal         Everton  1995      1   14
719        West Ham       Tottenham  1995      1   14
720     Aston Villa             QPR  1995      1   14
721         Norwich       Wimbledon  1995      1   14
722       Newcastle      Man United  1995      1   15
723        Coventry         Arsenal  1995      1   21
724         Everton  Crystal Palace  1995      1   21
725         Ipswich         Chelsea  1995      1   21
726      Nottingham     Aston Villa  1995      1   21
727  Sheffield Weds       Newcastle  1995      1   21
728      Man United       Blackburn  1995      1   22
729        West Ham  Sheffield Weds  1995      1   23
730           Leeds             QPR  1995      1   24
731       Liverpool         Everton  1995      1   24
732         Arsenal     Southampton  1995      1   24
733     Aston Villa       Tottenham  1995      1   25
734         Chelsea      Nottingham  1995      1   25
735  Crystal Palace      Man United  1995      1   25
736        Man City       Leicester  1995      1   25
737       Newcastle       Wimbledon  1995      1   25
738         Norwich        Coventry  1995      1   25
739       Blackburn         Ipswich  1995      1   28
740       Blackburn           Leeds  1995      2    1
741       Newcastle         Everton  1995      2    1
742  Sheffield Weds         Arsenal  1995      2    4
743     Southampton        Man City  1995      2    4
744             QPR       Newcastle  1995      2    4
745       Wimbledon           Leeds  1995      2    4
746      Man United     Aston Villa  1995      2    4
747       Leicester        West Ham  1995      2    4
748         Ipswich  Crystal Palace  1995      2    4
749         Everton         Norwich  1995      2    4
750        Coventry         Chelsea  1995      2    4
751      Nottingham       Liverpool  1995      2    4
752       Tottenham       Blackburn  1995      2    5
753         Norwich     Southampton  1995      2   11
754       Newcastle      Nottingham  1995      2   11
755        Man City      Man United  1995      2   11
756         Arsenal       Leicester  1995      2   11
757  Crystal Palace        Coventry  1995      2   11
758     Aston Villa       Wimbledon  1995      2   11
759       Liverpool             QPR  1995      2   11
760         Chelsea       Tottenham  1995      2   11
761       Blackburn  Sheffield Weds  1995      2   12

In [32]:
# بازی 662
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [3, 0, 'H']

# بازی 663
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 664
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 665
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 667
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 668
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 670
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 671
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 673
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 675
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 676
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 678
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 680
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 682
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 683
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 685
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 686
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 688
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 689
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 690
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 691
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [3, 0, 'H']

# بازی 693
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 694
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 696
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 697
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 698
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 700
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 702
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 703
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 705
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 707
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 708
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 710
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 711
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 713
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 714
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 715
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 716
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 718
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 719
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 720
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 722
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 724
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 726
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 728
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 729
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 731
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 732
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 733
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 734
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 736
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 739
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 740
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 742
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 744
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 746
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 748
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 750
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 751
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 752
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 2, 'A']

# بازی 755
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 756
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 758
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [4, 1, 'H']

# بازی 760
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

In [31]:
matches[300:400]

           HomeTeam        AwayTeam  Year  Month  Day
762        West Ham         Everton  1995      2   13
763        Coventry        West Ham  1995      2   18
764  Sheffield Weds     Aston Villa  1995      2   18
765         Arsenal      Nottingham  1995      2   21
766     Aston Villa       Leicester  1995      2   22
767           Leeds         Everton  1995      2   22
768        Man City         Ipswich  1995      2   22
769         Norwich      Man United  1995      2   22
770       Blackburn       Wimbledon  1995      2   22
771  Sheffield Weds       Liverpool  1995      2   25
772        West Ham         Chelsea  1995      2   25
773       Tottenham       Wimbledon  1995      2   25
774       Newcastle     Aston Villa  1995      2   25
775         Ipswich     Southampton  1995      2   25
776        Man City           Leeds  1995      2   25
777       Blackburn         Norwich  1995      2   25
778        Coventry       Leicester  1995      2   25
779         Everton      Man United  1995      2   25
780  Crystal Palace         Arsenal  1995      2   25
781             QPR      Nottingham  1995      2   26
782         Ipswich       Newcastle  1995      2   28
783     Aston Villa       Blackburn  1995      3    4
784           Leeds  Sheffield Weds  1995      3    4
785       Leicester         Everton  1995      3    4
786      Man United         Ipswich  1995      3    4
787         Norwich        Man City  1995      3    4
788      Nottingham       Tottenham  1995      3    4
789     Southampton        Coventry  1995      3    4
790       Wimbledon             QPR  1995      3    4
791       Liverpool       Newcastle  1995      3    4
792         Arsenal        West Ham  1995      3    5
793         Chelsea  Crystal Palace  1995      3    5
794     Aston Villa        Coventry  1995      3    6
795       Wimbledon      Man United  1995      3    7
796       Newcastle        West Ham  1995      3    8
797       Blackburn         Arsenal  1995      3    8
798       Tottenham         Ipswich  1995      3    8
799        Man City         Chelsea  1995      3    8
800      Nottingham         Everton  1995      3    8
801             QPR       Leicester  1995      3    8
802         Norwich  Sheffield Weds  1995      3    8
803       Leicester      Nottingham  1995      3   11
804  Sheffield Weds       Wimbledon  1995      3   11
805        West Ham         Norwich  1995      3   11
806         Chelsea           Leeds  1995      3   11
807        Coventry       Blackburn  1995      3   11
808  Crystal Palace  Sheffield Weds  1995      3   14
809       Liverpool        Coventry  1995      3   14
810       Leicester           Leeds  1995      3   15
811      Man United       Tottenham  1995      3   15
812             QPR         Norwich  1995      3   15
813     Southampton        West Ham  1995      3   15
814         Everton        Man City  1995      3   15
815             QPR         Everton  1995      3   18
816       Wimbledon  Crystal Palace  1995      3   18
817       Tottenham       Leicester  1995      3   18
818           Leeds        Coventry  1995      3   18
819        Man City  Sheffield Weds  1995      3   18
820      Nottingham     Southampton  1995      3   18
821     Aston Villa        West Ham  1995      3   18
822       Blackburn         Chelsea  1995      3   18
823       Liverpool      Man United  1995      3   19
824       Newcastle         Arsenal  1995      3   19
825         Norwich         Ipswich  1995      3   20
826       Wimbledon        Man City  1995      3   21
827       Tottenham       Liverpool  1995      3   22
828     Southampton       Newcastle  1995      3   22
829      Nottingham           Leeds  1995      3   22
830      Man United         Arsenal  1995      3   22
831             QPR         Chelsea  1995      3   22
832         Chelsea       Newcastle  1995      4    1
833        Coventry             QPR  1995      4    1
834  Crystal Palace        Man City  1995      4    1
835         Everton       Blackburn  1995      4    1
836         Ipswich     Aston Villa  1995      4    1
837       Leicester       Wimbledon  1995      4    1
838  Sheffield Weds      Nottingham  1995      4    1
839         Arsenal         Norwich  1995      4    1
840     Southampton       Tottenham  1995      4    2
841      Man United           Leeds  1995      4    2
842             QPR       Blackburn  1995      4    4
843  Crystal Palace     Aston Villa  1995      4    4
844           Leeds         Ipswich  1995      4    5
845       Leicester         Norwich  1995      4    5
846       Liverpool     Southampton  1995      4    5
847       Newcastle         Norwich  1995      4    8
848      Nottingham        West Ham  1995      4    8
849             QPR         Arsenal  1995      4    8
850  Sheffield Weds       Leicester  1995      4    8
851       Liverpool           Leeds  1995      4    9
852       Wimbledon         Chelsea  1995      4   10
853       Tottenham        Man City  1995      4   11
854         Ipswich             QPR  1995      4   11
855         Chelsea     Southampton  1995      4   12
856         Norwich      Nottingham  1995      4   12
857         Arsenal       Liverpool  1995      4   12
858        West Ham       Wimbledon  1995      4   13
859  Crystal Palace       Tottenham  1995      4   14
860         Everton       Newcastle  1995      4   14
861        Man City       Liverpool  1995      4   14

In [33]:
# بازی 762 - West Ham vs Everton (1995-02-13)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 763 - Coventry vs West Ham (1995-02-18)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 764 - Sheffield Weds vs Aston Villa (1995-02-18)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 2, 'A']

# بازی 765 - Arsenal vs Nottingham (1995-02-21)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 766 - Aston Villa vs Leicester (1995-02-22)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 767 - Leeds vs Everton (1995-02-22)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 768 - Man City vs Ipswich (1995-02-22)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 769 - Norwich vs Man United (1995-02-22)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 2, 'A']

# بازی 770 - Blackburn vs Wimbledon (1995-02-22)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 1, 'H']

# بازی 771 - Sheffield Weds vs Liverpool (1995-02-25)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 772 - West Ham vs Chelsea (1995-02-25)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 773 - Tottenham vs Wimbledon (1995-02-25)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 774 - Newcastle vs Aston Villa (1995-02-25)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 775 - Ipswich vs Southampton (1995-02-25)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 776 - Man City vs Leeds (1995-02-25)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 777 - Blackburn vs Norwich (1995-02-25)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 778 - Coventry vs Leicester (1995-02-25)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 779 - Everton vs Man United (1995-02-25)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 780 - Crystal Palace vs Arsenal (1995-02-25)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 2, 'A']

# بازی 781 - QPR vs Nottingham (1995-02-26)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 782 - Ipswich vs Newcastle (1995-02-28)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 783 - Aston Villa vs Blackburn (1995-03-04)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 784 - Leeds vs Sheffield Weds (1995-03-04)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 785 - Leicester vs Everton (1995-03-04)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 786 - Man United vs Ipswich (1995-03-04)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [3, 0, 'H']

# بازی 787 - Norwich vs Man City (1995-03-04)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 788 - Nottingham vs Tottenham (1995-03-04)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 789 - Southampton vs Coventry (1995-03-04)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 790 - Wimbledon vs QPR (1995-03-04)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 791 - Liverpool vs Newcastle (1995-03-04)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 792 - Arsenal vs West Ham (1995-03-05)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 793 - Chelsea vs Crystal Palace (1995-03-05)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 794 - Aston Villa vs Coventry (1995-03-06)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 795 - Wimbledon vs Man United (1995-03-07)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 796 - Newcastle vs West Ham (1995-03-08)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 797 - Blackburn vs Arsenal (1995-03-08)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 798 - Tottenham vs Ipswich (1995-03-08)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 799 - Man City vs Chelsea (1995-03-08)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 800 - Nottingham vs Everton (1995-03-08)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 801 - QPR vs Leicester (1995-03-08)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 802 - Norwich vs Sheffield Weds (1995-03-08)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 803 - Leicester vs Nottingham (1995-03-11)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 804 - Sheffield Weds vs Wimbledon (1995-03-11)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 805 - West Ham vs Norwich (1995-03-11)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 806 - Chelsea vs Leeds (1995-03-11)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 2, 'A']

# بازی 807 - Coventry vs Blackburn (1995-03-11)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 808 - Crystal Palace vs Sheffield Weds (1995-03-14)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 809 - Liverpool vs Coventry (1995-03-14)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 810 - Leicester vs Leeds (1995-03-15)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 811 - Man United vs Tottenham (1995-03-15)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 812 - QPR vs Norwich (1995-03-15)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 813 - Southampton vs West Ham (1995-03-15)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 814 - Everton vs Man City (1995-03-15)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 815 - QPR vs Everton (1995-03-18)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Everton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 816 - Wimbledon vs Crystal Palace (1995-03-18)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Crystal Palace'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 817 - Tottenham vs Leicester (1995-03-18)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 818 - Leeds vs Coventry (1995-03-18)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Coventry'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 819 - Man City vs Sheffield Weds (1995-03-18)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Sheffield Weds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 2, 'A']

# بازی 820 - Nottingham vs Southampton (1995-03-18)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 821 - Aston Villa vs West Ham (1995-03-18)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 822 - Blackburn vs Chelsea (1995-03-18)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 2, 'A']

# بازی 823 - Liverpool vs Man United (1995-03-19)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Man United'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 824 - Newcastle vs Arsenal (1995-03-19)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 825 - Norwich vs Ipswich (1995-03-20)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 826 - Wimbledon vs Man City (1995-03-21)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 827 - Tottenham vs Liverpool (1995-03-22)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 828 - Southampton vs Newcastle (1995-03-22)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 1, 'D']

# بازی 829 - Nottingham vs Leeds (1995-03-22)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 830 - Man United vs Arsenal (1995-03-22)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 831 - QPR vs Chelsea (1995-03-22)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 832 - Chelsea vs Newcastle (1995-04-01)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 833 - Coventry vs QPR (1995-04-01)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 834 - Crystal Palace vs Man City (1995-04-01)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 835 - Everton vs Blackburn (1995-04-01)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 836 - Ipswich vs Aston Villa (1995-04-01)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 837 - Leicester vs Wimbledon (1995-04-01)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 838 - Sheffield Weds vs Nottingham (1995-04-01)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 3, 'A']

# بازی 839 - Arsenal vs Norwich (1995-04-01)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [3, 1, 'H']

# بازی 840 - Southampton vs Tottenham (1995-04-02)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 841 - Man United vs Leeds (1995-04-02)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 842 - QPR vs Blackburn (1995-04-04)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Blackburn'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 843 - Crystal Palace vs Aston Villa (1995-04-04)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Aston Villa'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 844 - Leeds vs Ipswich (1995-04-05)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Ipswich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 845 - Leicester vs Norwich (1995-04-05)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 846 - Liverpool vs Southampton (1995-04-05)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 847 - Newcastle vs Norwich (1995-04-08)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Norwich'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 848 - Nottingham vs West Ham (1995-04-08)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'West Ham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 849 - QPR vs Arsenal (1995-04-08)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Arsenal'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 850 - Sheffield Weds vs Leicester (1995-04-08)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Leicester'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 851 - Liverpool vs Leeds (1995-04-09)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Leeds'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 1, 'A']

# بازی 852 - Wimbledon vs Chelsea (1995-04-10)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Chelsea'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 853 - Tottenham vs Man City (1995-04-11)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Man City'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 854 - Ipswich vs QPR (1995-04-11)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'QPR'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [1, 0, 'H']

# بازی 855 - Chelsea vs Southampton (1995-04-12)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Southampton'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [2, 0, 'H']

# بازی 856 - Norwich vs Nottingham (1995-04-12)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Nottingham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 857 - Arsenal vs Liverpool (1995-04-12)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 858 - West Ham vs Wimbledon (1995-04-13)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Wimbledon'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 859 - Crystal Palace vs Tottenham (1995-04-14)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Tottenham'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

# بازی 860 - Everton vs Newcastle (1995-04-14)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Newcastle'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 2, 'A']

# بازی 861 - Man City vs Liverpool (1995-04-14)
df.loc[(df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Liverpool'), ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']] = [0, 0, 'D']

In [34]:
matches = df[(df['Season'] == '9495') & (df['Result-HalfTime'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]
matches

           HomeTeam        AwayTeam  Year  Month  Day
490      Nottingham       Leicester  1994      8   27
496         Everton      Nottingham  1994      8   30
506      Nottingham  Sheffield Weds  1994      9   10
666  Crystal Palace         Norwich  1994     12   17
669         Chelsea       Liverpool  1994     12   18
672     Southampton       Wimbledon  1994     12   26
674        Man City       Blackburn  1994     12   26
677  Crystal Palace             QPR  1994     12   26
679         Chelsea      Man United  1994     12   26
681           Leeds       Newcastle  1994     12   26
684       Wimbledon        West Ham  1994     12   28
687      Man United       Leicester  1994     12   28
692     Southampton      Man United  1994     12   31
695       Leicester  Sheffield Weds  1994     12   31
699         Chelsea       Wimbledon  1994     12   31
701           Leeds       Liverpool  1994     12   31
704       Wimbledon         Everton  1995      1    2
706       Newcastle        Man City  1995      1    2
709         Ipswich       Leicester  1995      1    2
712       Blackburn      Nottingham  1995      1   14
717        Man City        Coventry  1995      1   14
721         Norwich       Wimbledon  1995      1   14
723        Coventry         Arsenal  1995      1   21
725         Ipswich         Chelsea  1995      1   21
727  Sheffield Weds       Newcastle  1995      1   21
730           Leeds             QPR  1995      1   24
735  Crystal Palace      Man United  1995      1   25
737       Newcastle       Wimbledon  1995      1   25
738         Norwich        Coventry  1995      1   25
741       Newcastle         Everton  1995      2    1
743     Southampton        Man City  1995      2    4
745       Wimbledon           Leeds  1995      2    4
747       Leicester        West Ham  1995      2    4
749         Everton         Norwich  1995      2    4
753         Norwich     Southampton  1995      2   11
754       Newcastle      Nottingham  1995      2   11
757  Crystal Palace        Coventry  1995      2   11
759       Liverpool             QPR  1995      2   11
761       Blackburn  Sheffield Weds  1995      2   12
862     Southampton             QPR  1995      4   15
863       Leicester      Man United  1995      4   15
864         Chelsea     Aston Villa  1995      4   15
865        Coventry  Sheffield Weds  1995      4   15
866         Arsenal         Ipswich  1995      4   15
867           Leeds       Blackburn  1995      4   15
868       Wimbledon     Southampton  1995      4   17
869       Tottenham         Norwich  1995      4   17
870  Sheffield Weds         Everton  1995      4   17
871      Nottingham        Coventry  1995      4   17
872             QPR  Crystal Palace  1995      4   17
873      Man United         Chelsea  1995      4   17
874       Liverpool       Leicester  1995      4   17
875         Ipswich        West Ham  1995      4   17
876       Blackburn        Man City  1995      4   17
877     Aston Villa         Arsenal  1995      4   17
878       Newcastle           Leeds  1995      4   17
879       Blackburn  Crystal Palace  1995      4   19
880     Southampton  Sheffield Weds  1995      4   29
881         Norwich       Liverpool  1995      4   29
882        Man City       Newcastle  1995      4   29
883         Everton       Wimbledon  1995      4   29
884           Leeds     Aston Villa  1995      4   29
885       Leicester         Ipswich  1995      4   29
886         Arsenal       Tottenham  1995      4   29
887         Chelsea             QPR  1995      4   29
888  Crystal Palace      Nottingham  1995      4   29
889        West Ham       Blackburn  1995      4   30
890        Coventry      Man United  1995      5    1
891       Wimbledon       Liverpool  1995      5    2
892     Aston Villa        Man City  1995      5    3
893         Everton         Chelsea  1995      5    3
894       Newcastle       Tottenham  1995      5    3
895     Southampton  Crystal Palace  1995      5    3
896        West Ham             QPR  1995      5    3
897         Arsenal       Wimbledon  1995      5    4
898             QPR       Tottenham  1995      5    6
899      Nottingham        Man City  1995      5    6
900       Leicester         Chelsea  1995      5    6
901         Everton     Southampton  1995      5    6
902         Ipswich        Coventry  1995      5    6
903     Aston Villa       Liverpool  1995      5    6
904           Leeds         Norwich  1995      5    6
905  Crystal Palace        West Ham  1995      5    6
906      Man United  Sheffield Weds  1995      5    7
907       Blackburn       Newcastle  1995      5    8
908         Ipswich         Everton  1995      5    9
909           Leeds  Crystal Palace  1995      5    9
910       Tottenham        Coventry  1995      5    9
911      Man United     Southampton  1995      5   10
912        West Ham       Liverpool  1995      5   10
913       Wimbledon      Nottingham  1995      5   13
914        West Ham      Man United  1995      5   14
915       Tottenham           Leeds  1995      5   14
916     Southampton       Leicester  1995      5   14
917  Sheffield Weds         Ipswich  1995      5   14
918         Norwich     Aston Villa  1995      5   14
919        Man City             QPR  1995      5   14
920       Liverpool       Blackburn  1995      5   14
921        Coventry         Everton  1995      5   14
922         Chelsea         Arsenal  1995      5   14
923       Newcastle  Crystal Palace  1995      5   14

In [ ]:
# 27 Aug 1994 - Nottingham Forest vs Leicester City
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Leicester'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']  # Source: thecityground.com  0]

# 30 Aug 1994 - Everton vs Nottingham Forest
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Nottingham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']  # Source: thecityground.com  1], efcstatto.com  2]

# 10 Sep 1994 - Nottingham Forest vs Sheffield Weds
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']  # Source: thecityground.com  3]

# 17 Dec 1994 - Crystal Palace vs Norwich
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Half-time score not specified in search results (full-time 0-1)  4]

# 18 Dec 1994 - Chelsea vs Liverpool
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: fbref.com  5]

# 26 Dec 1994 - Southampton vs Wimbledon
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 2, 'D']  # Source: endirect24.com  6]

# 26 Dec 1994 - Man City vs Blackburn
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']  # Source: fbref.com  7], 11v11.com  8]

# 26 Dec 1994 - Crystal Palace vs QPR
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: fbref.com  9]

# 26 Dec 1994 - Chelsea vs Man United
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']  # Source: stamford-bridge.com  10]

# 26 Dec 1994 - Leeds vs Newcastle
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: fbref.com  11]

# 28 Dec 1994 - Wimbledon vs West Ham
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: transfermarkt.com  12]

# 28 Dec 1994 - Man United vs Leicester
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Leicester'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: Sky Sports shows no goals in first half  13]

# 31 Dec 1994 - Southampton vs Man United
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']  # Source: Magilton goal at 44'  14]

# 31 Dec 1994 - Leicester vs Sheffield Weds
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']  # Source: transfermarkt.com  15]

# 31 Dec 1994 - Chelsea vs Wimbledon
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Half-time score not specified (full-time 1-1)  16]

# 31 Dec 1994 - Leeds vs Liverpool
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']  # Source: lfchistory.net  17]

# 2 Jan 1995 - Wimbledon vs Everton
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Half-time score not specified (full-time 2-1)  18]

# 2 Jan 1995 - Newcastle vs Man City
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: fbref.com  19]

# 2 Jan 1995 - Ipswich vs Leicester
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Leicester'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']  # Source: Kiwomya goal at 34'  20]

# 14 Jan 1995 - Blackburn vs Nottingham
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Nottingham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Half-time score not specified (full-time 3-0)  21]

# 14 Jan 1995 - Man City vs Coventry
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: fbref.com  22]

# 14 Jan 1995 - Norwich vs Wimbledon
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']  # Source: Goss 22', Reeves 44'  23]

# 21 Jan 1995 - Coventry vs Arsenal
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Half-time score not specified (full-time 0-1)  24]

# 21 Jan 1995 - Ipswich vs Chelsea
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: stamford-bridge.com  25]

# 21 Jan 1995 - Sheffield Weds vs Newcastle
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: fbref.com  26]

# 24 Jan 1995 - Leeds vs QPR
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']  # Source: Masinga 31', White 33'  27]

# 25 Jan 1995 - Crystal Palace vs Man United
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: bleacherreport.com  28]

# 25 Jan 1995 - Newcastle vs Wimbledon
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Half-time score not specified (full-time 2-1)  29]

# 25 Jan 1995 - Norwich vs Coventry
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']  # Source: skybluearchive.com  30]

# 1 Feb 1995 - Newcastle vs Everton
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Half-time score not specified (full-time 2-0)  31]

# 4 Feb 1995 - Southampton vs Man City
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']  # Source: Coton OG 24', Kernaghan 29'  32]

# 4 Feb 1995 - Wimbledon vs Leeds
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: fbref.com  33]

# 4 Feb 1995 - Leicester vs West Ham
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Half-time score not specified (full-time 1-2)  34]

# 4 Feb 1995 - Everton vs Norwich
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']  # Source: Stuart goal at 42'  35]

# 11 Feb 1995 - Norwich vs Southampton
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']  # Source: Hall 33', Magilton 36'  36]

# 11 Feb 1995 - Newcastle vs Nottingham
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Nottingham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: First goal at 47'  37]

# 11 Feb 1995 - Crystal Palace vs Coventry
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Half-time score not specified (full-time 0-2)  38]

# 11 Feb 1995 - Liverpool vs QPR
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Half-time score not specified (full-time 1-1)  39]

# 12 Feb 1995 - Blackburn vs Sheffield Weds
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']  # Source: Sherwood 26', Waddle 32', Atkins 35'  40]

# 15 Apr 1995 - Southampton vs QPR
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']  # Source: wikipedia  41]

# 15 Apr 1995 - Leicester vs Man United
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']  # Source: sportsmole.co.uk  42]

# 15 Apr 1995 - Chelsea vs Aston Villa
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']  # Source: fbref.com  43]

# 15 Apr 1995 - Coventry vs Sheffield Weds
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']  # Source: Dublin goal at 3'  44]

In [37]:
null_count_per_season = df[df['Result-HalfTime'].isna()]['Season'].value_counts()
print(null_count_per_season)

Season
9495    58
Name: count, dtype: int64

In [38]:
matches = df[(df['Season'] == '9495') & (df['Result-HalfTime'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]
matches

           HomeTeam        AwayTeam  Year  Month  Day
866         Arsenal         Ipswich  1995      4   15
867           Leeds       Blackburn  1995      4   15
868       Wimbledon     Southampton  1995      4   17
869       Tottenham         Norwich  1995      4   17
870  Sheffield Weds         Everton  1995      4   17
871      Nottingham        Coventry  1995      4   17
872             QPR  Crystal Palace  1995      4   17
873      Man United         Chelsea  1995      4   17
874       Liverpool       Leicester  1995      4   17
875         Ipswich        West Ham  1995      4   17
876       Blackburn        Man City  1995      4   17
877     Aston Villa         Arsenal  1995      4   17
878       Newcastle           Leeds  1995      4   17
879       Blackburn  Crystal Palace  1995      4   19
880     Southampton  Sheffield Weds  1995      4   29
881         Norwich       Liverpool  1995      4   29
882        Man City       Newcastle  1995      4   29
883         Everton       Wimbledon  1995      4   29
884           Leeds     Aston Villa  1995      4   29
885       Leicester         Ipswich  1995      4   29
886         Arsenal       Tottenham  1995      4   29
887         Chelsea             QPR  1995      4   29
888  Crystal Palace      Nottingham  1995      4   29
889        West Ham       Blackburn  1995      4   30
890        Coventry      Man United  1995      5    1
891       Wimbledon       Liverpool  1995      5    2
892     Aston Villa        Man City  1995      5    3
893         Everton         Chelsea  1995      5    3
894       Newcastle       Tottenham  1995      5    3
895     Southampton  Crystal Palace  1995      5    3
896        West Ham             QPR  1995      5    3
897         Arsenal       Wimbledon  1995      5    4
898             QPR       Tottenham  1995      5    6
899      Nottingham        Man City  1995      5    6
900       Leicester         Chelsea  1995      5    6
901         Everton     Southampton  1995      5    6
902         Ipswich        Coventry  1995      5    6
903     Aston Villa       Liverpool  1995      5    6
904           Leeds         Norwich  1995      5    6
905  Crystal Palace        West Ham  1995      5    6
906      Man United  Sheffield Weds  1995      5    7
907       Blackburn       Newcastle  1995      5    8
908         Ipswich         Everton  1995      5    9
909           Leeds  Crystal Palace  1995      5    9
910       Tottenham        Coventry  1995      5    9
911      Man United     Southampton  1995      5   10
912        West Ham       Liverpool  1995      5   10
913       Wimbledon      Nottingham  1995      5   13
914        West Ham      Man United  1995      5   14
915       Tottenham           Leeds  1995      5   14
916     Southampton       Leicester  1995      5   14
917  Sheffield Weds         Ipswich  1995      5   14
918         Norwich     Aston Villa  1995      5   14
919        Man City             QPR  1995      5   14
920       Liverpool       Blackburn  1995      5   14
921        Coventry         Everton  1995      5   14
922         Chelsea         Arsenal  1995      5   14
923       Newcastle  Crystal Palace  1995      5   14

In [39]:
df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 2, 'A']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Crystal Palace'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Leicester'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Crystal Palace'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Nottingham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 3, 'A']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Crystal Palace'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 1, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Wimbledon'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'QPR') & (df['AwayTeam'] == 'Tottenham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Man City'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Chelsea'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Norwich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'West Ham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Sheffield Weds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Blackburn') & (df['AwayTeam'] == 'Newcastle'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Ipswich') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Crystal Palace'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [2, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Coventry'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Southampton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Liverpool'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Wimbledon') & (df['AwayTeam'] == 'Nottingham'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 2, 'A']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Man United'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Leeds'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Leicester'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Sheffield Weds') & (df['AwayTeam'] == 'Ipswich'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 0, 'H']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Aston Villa'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'QPR'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Blackburn'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 1, 'A']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Coventry') & (df['AwayTeam'] == 'Everton'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [0, 0, 'D']

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Arsenal'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [1, 1, 'D']  

df.loc[
    (df['Season'] == '9495') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Crystal Palace'),
    ['HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime']
] = [3, 0, 'H']

In [40]:
null_count_per_season = df[df['Result-HalfTime'].isna()]['Season'].value_counts()
print(null_count_per_season)

Series([], Name: count, dtype: int64)

In [41]:
df.isna().sum()[ df.isna().sum() > 0].sort_values()

QualificationOrRelegationAway     1904
SeasonGDAway                      1904
SeasonGAAway                      1904
SeasonGFAway                      1904
SeasonLossAway                    1904
SeasonDrawAway                    1904
SeasonWinAway                     1904
SeasonPlayedAway                  1904
SeasonPosAway                     1904
SeasonPointsAway                  1904
AwayRed                           2824
HomeRed                           2824
HomeYellow                        2824
AwayYellow                        2824
HomeCorner                        2824
AwayFoul                          2824
HomeFoul                          2824
AwayOnTargetShot                  2824
HomeOnTargetShot                  2824
AwayShot                          2824
HomeShot                          2824
Referee                           2824
AwayCorner                        2824
XGHome                           10156
XGAway                           10156
Round                            10156
Time                             10156
WeekDay                          10156
Attendance                       11238
dtype: int64

In [42]:
df.to_csv("Data.Data.4.csv", index=False)

In [121]:
df = pd.read_csv("Data.Data.4.csv", dtype={'Season':str})

---

In [122]:
null_count_per_season = df[df['Round'].isna() ]['Season'].value_counts()
print(null_count_per_season)

Season
9394    462
9495    462
0708    380
1819    380
1718    380
1617    380
1516    380
1415    380
1314    380
1213    380
1112    380
1011    380
0809    380
0910    380
0607    380
9900    380
9596    380
9697    380
0506    380
9899    380
9798    380
0001    380
0102    380
0203    380
0304    380
0405    380
2526     22
2425     20
1920     17
2324     16
2122     14
2021     13
2223     10
Name: count, dtype: int64

In [123]:
teams = df[(df['Season'] == '9394') & (df['AwayRed'].isna())]['HomeTeam'].unique()
teams.sort()
teams

array(['Arsenal', 'Aston Villa', 'Blackburn', 'Chelsea', 'Coventry',
       'Everton', 'Ipswich', 'Leeds', 'Liverpool', 'Man City',
       'Man United', 'Newcastle', 'Norwich', 'Oldham', 'QPR', 'Sheffield',
       'Sheffield Weds', 'Southampton', 'Swindon', 'Tottenham',
       'West Ham', 'Wimbledon'], dtype=object)

In [124]:
df[df['Season'] == '9394'].isna().sum()[df[df['Season'] == '9394'].isna().sum() > 0]

WeekDay             462
Time                462
Round               462
Attendance          462
Referee             462
HomeShot            462
AwayShot            462
HomeOnTargetShot    462
AwayOnTargetShot    462
HomeFoul            462
AwayFoul            462
HomeCorner          462
AwayCorner          462
HomeYellow          462
AwayYellow          462
HomeRed             462
AwayRed             462
XGHome              462
XGAway              462
dtype: int64

In [125]:
null_count_per_season = df[df['WeekDay'].isna() ]['Season'].value_counts()
null_count_per_season

Season
9394    462
9495    462
0708    380
1819    380
1718    380
1617    380
1516    380
1415    380
1314    380
1213    380
1112    380
1011    380
0809    380
0910    380
0607    380
9900    380
9596    380
9697    380
0506    380
9899    380
9798    380
0001    380
0102    380
0203    380
0304    380
0405    380
2526     22
2425     20
1920     17
2324     16
2122     14
2021     13
2223     10
Name: count, dtype: int64

In [126]:
df[(df['Season'] == '2223') & (df['HomeOnTargetShot'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

Empty DataFrame
Columns: [HomeTeam, AwayTeam, Year, Month, Day]
Index: []

In [127]:
df[(df['Season'] == '2223') & (df['AwayCorner'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

Empty DataFrame
Columns: [HomeTeam, AwayTeam, Year, Month, Day]
Index: []

In [128]:
df[(df['Season'] == '2223') & (df['AwayRed'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

Empty DataFrame
Columns: [HomeTeam, AwayTeam, Year, Month, Day]
Index: []

In [129]:
df[(df['Season'] == '2223') & (df['XGHome'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

          HomeTeam        AwayTeam  Year  Month  Day
11194       Wolves          Fulham  2022      8   13
11257       Fulham       Newcastle  2022     10    1
11270   Nottingham     Aston Villa  2022     10   10
11291      Everton  Crystal Palace  2022     10   22
11296  Southampton         Arsenal  2022     10   23
11403    Liverpool         Everton  2023      2   13
11480  Aston Villa       Newcastle  2023      4   15
11513       Fulham        Man City  2023      4   30
11532  Aston Villa       Tottenham  2023      5   13
11541    Newcastle        Brighton  2023      5   18

In [130]:
df[(df['Season'] == '2223') & (df['XGAway'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

          HomeTeam        AwayTeam  Year  Month  Day
11194       Wolves          Fulham  2022      8   13
11257       Fulham       Newcastle  2022     10    1
11270   Nottingham     Aston Villa  2022     10   10
11291      Everton  Crystal Palace  2022     10   22
11296  Southampton         Arsenal  2022     10   23
11403    Liverpool         Everton  2023      2   13
11480  Aston Villa       Newcastle  2023      4   15
11513       Fulham        Man City  2023      4   30
11532  Aston Villa       Tottenham  2023      5   13
11541    Newcastle        Brighton  2023      5   18

In [131]:
df[(df['Season'] == '2223') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

             HomeTeam        AwayTeam  Year  Month  Day
11184  Crystal Palace         Arsenal  2022      8    5
11185       Tottenham     Southampton  2022      8    6
11186         Everton         Chelsea  2022      8    6
11187       Newcastle      Nottingham  2022      8    6
11188          Fulham       Liverpool  2022      8    6
11189     Bournemouth     Aston Villa  2022      8    6
11190           Leeds          Wolves  2022      8    6
11191       Leicester       Brentford  2022      8    7
11192      Man United        Brighton  2022      8    7
11193        West Ham        Man City  2022      8    7
11194          Wolves          Fulham  2022      8   13
11195     Southampton           Leeds  2022      8   13
11196        Man City     Bournemouth  2022      8   13
11197       Brentford      Man United  2022      8   13
11198         Arsenal       Leicester  2022      8   13
11199     Aston Villa         Everton  2022      8   13
11200        Brighton       Newcastle  2022      8   13
11201      Nottingham        West Ham  2022      8   14
11202         Chelsea       Tottenham  2022      8   14
11203       Liverpool  Crystal Palace  2022      8   15
11204       Tottenham          Wolves  2022      8   20
11205  Crystal Palace     Aston Villa  2022      8   20
11206         Everton      Nottingham  2022      8   20
11207          Fulham       Brentford  2022      8   20
11208       Leicester     Southampton  2022      8   20
11209     Bournemouth         Arsenal  2022      8   20
11210        West Ham        Brighton  2022      8   21
11211           Leeds         Chelsea  2022      8   21
11212       Newcastle        Man City  2022      8   21
11213      Man United       Liverpool  2022      8   22
11214     Southampton      Man United  2022      8   27
11215       Brentford         Everton  2022      8   27
11216        Brighton           Leeds  2022      8   27
11217         Chelsea       Leicester  2022      8   27
11218       Liverpool     Bournemouth  2022      8   27
11219        Man City  Crystal Palace  2022      8   27
11220         Arsenal          Fulham  2022      8   27
11221     Aston Villa        West Ham  2022      8   28
11222          Wolves       Newcastle  2022      8   28
11223      Nottingham       Tottenham  2022      8   28
11224           Leeds         Everton  2022      8   30
11225     Southampton         Chelsea  2022      8   30
11226          Fulham        Brighton  2022      8   30
11227  Crystal Palace       Brentford  2022      8   30
11228         Arsenal     Aston Villa  2022      8   31
11229     Bournemouth          Wolves  2022      8   31
11230        Man City      Nottingham  2022      8   31
11231        West Ham       Tottenham  2022      8   31
11232       Liverpool       Newcastle  2022      8   31
11233       Leicester      Man United  2022      9    1
11234     Aston Villa        Man City  2022      9    3
11235          Wolves     Southampton  2022      9    3
11236      Nottingham     Bournemouth  2022      9    3
11237       Tottenham          Fulham  2022      9    3
11238         Chelsea        West Ham  2022      9    3
11239       Brentford           Leeds  2022      9    3
11240         Everton       Liverpool  2022      9    3
11241       Newcastle  Crystal Palace  2022      9    3
11242        Brighton       Leicester  2022      9    4
11243      Man United         Arsenal  2022      9    4
11244     Aston Villa     Southampton  2022      9   16
11245      Nottingham          Fulham  2022      9   16
11246          Wolves        Man City  2022      9   17
11247       Newcastle     Bournemouth  2022      9   17
11248       Tottenham       Leicester  2022      9   17
11249       Brentford         Arsenal  2022      9   18
11250         Everton        West Ham  2022      9   18
11251        West Ham          Wolves  2022     10    1
11252     Southampton         Everton  2022     10    1
11253       Liverpool        Brighton  2022     10    1
11254         Arsenal       Tottenham  2022     10    1
11255  Crystal Palace         Chelsea  2022     10    1
11256     Bournemouth       Brentford  2022     10    1
11257          Fulham       Newcastle  2022     10    1
11258        Man City      Man United  2022     10    2
11259           Leeds     Aston Villa  2022     10    2
11260       Leicester      Nottingham  2022     10    3
11261       Newcastle       Brentford  2022     10    8
11262     Bournemouth       Leicester  2022     10    8
11263         Chelsea          Wolves  2022     10    8
11264        Man City     Southampton  2022     10    8
11265        Brighton       Tottenham  2022     10    8
11266         Everton      Man United  2022     10    9
11267         Arsenal       Liverpool  2022     10    9
11268  Crystal Palace           Leeds  2022     10    9
11269        West Ham          Fulham  2022     10    9
11270      Nottingham     Aston Villa  2022     10   10
11271       Brentford        Brighton  2022     10   14
11272       Leicester  Crystal Palace  2022     10   15
11273          Fulham     Bournemouth  2022     10   15
11274          Wolves      Nottingham  2022     10   15
11275       Tottenham         Everton  2022     10   15
11276     Aston Villa         Chelsea  2022     10   16
11277           Leeds         Arsenal  2022     10   16
11278      Man United       Newcastle  2022     10   16
11279     Southampton        West Ham  2022     10   16
11280       Liverpool        Man City  2022     10   16
11281  Crystal Palace          Wolves  2022     10   18
11282        Brighton      Nottingham  2022     10   18
11283     Bournemouth     Southampton  2022     10   19
11284       Brentford         Chelsea  2022     10   19
11285       Liverpool        West Ham  2022     10   19
11286       Newcastle         Everton  2022     10   19
11287      Man United       Tottenham  2022     10   19
11288          Fulham     Aston Villa  2022     10   20
11289       Leicester           Leeds  2022     10   20
11290      Nottingham       Liverpool  2022     10   22
11291         Everton  Crystal Palace  2022     10   22
11292        Man City        Brighton  2022     10   22
11293         Chelsea      Man United  2022     10   22
11294          Wolves       Leicester  2022     10   23
11295       Tottenham       Newcastle  2022     10   23
11296     Southampton         Arsenal  2022     10   23
11297     Aston Villa       Brentford  2022     10   23
11298           Leeds          Fulham  2022     10   23
11299        West Ham     Bournemouth  2022     10   24
11300          Fulham         Everton  2022     10   29
11301       Leicester        Man City  2022     10   29
11302     Bournemouth       Tottenham  2022     10   29
11303       Brentford          Wolves  2022     10   29
11304        Brighton         Chelsea  2022     10   29
11305  Crystal Palace     Southampton  2022     10   29
11306       Newcastle     Aston Villa  2022     10   29
11307       Liverpool           Leeds  2022     10   29
11308      Man United        West Ham  2022     10   30
11309         Arsenal      Nottingham  2022     10   30
11310           Leeds     Bournemouth  2022     11    5
11311        Man City          Fulham  2022     11    5
11312      Nottingham       Brentford  2022     11    5
11313          Wolves        Brighton  2022     11    5
11314         Everton       Leicester  2022     11    5
11315     Southampton       Newcastle  2022     11    6
11316        West Ham  Crystal Palace  2022     11    6
11317         Chelsea         Arsenal  2022     11    6
11318     Aston Villa      Man United  2022     11    6
11319       Tottenham       Liverpool  2022     11    6
11320     Bournemouth         Everton  2022     11   12
11321       Newcastle         Chelsea  2022     11   12
11322          Wolves         Arsenal  2022     11   12
11323        West Ham       Leicester  2022     11   12
11324        Man City       Brentford  2022     11   12
11325      Nottingham  Crystal Palace  2022     11   12
11326       Tottenham           Leeds  2022     11   12
11327       Liverpool     Southampton  2022     11   12
11328        Brighton     Aston Villa  2022     11   13
11329          Fulham      Man United  2022     11   13
11330         Arsenal        West Ham  2022     12   26
11331       Brentford       Tottenham  2022     12   26
11332  Crystal Palace          Fulham  2022     12   26
11333         Everton          Wolves  2022     12   26
11334       Leicester       Newcastle  2022     12   26
11335     Southampton        Brighton  2022     12   26
11336     Aston Villa       Liverpool  2022     12   26
11337      Man United      Nottingham  2022     12   27
11338         Chelsea     Bournemouth  2022     12   27
11339           Leeds        Man City  2022     12   28
11340        West Ham       Brentford  2022     12   30
11341       Liverpool       Leicester  2022     12   30
11342          Wolves      Man United  2022     12   31
11343     Bournemouth  Crystal Palace  2022     12   31
11344          Fulham     Southampton  2022     12   31
11345        Man City         Everton  2022     12   31
11346       Newcastle           Leeds  2022     12   31
11347        Brighton         Arsenal  2022     12   31
11348      Nottingham         Chelsea  2023      1    1
11349       Tottenham     Aston Villa  2023      1    1
11350       Brentford       Liverpool  2023      1    2
11351         Arsenal       Newcastle  2023      1    3
11352         Everton        Brighton  2023      1    3
11353       Leicester          Fulham  2023      1    3
11354      Man United     Bournemouth  2023      1    3
11355     Southampton      Nottingham  2023      1    4
11356           Leeds        West Ham  2023      1    4
11357     Aston Villa          Wolves  2023      1    4
11358  Crystal Palace       Tottenham  2023      1    4
11359         Chelsea        Man City  2023      1    5
11360          Fulham         Chelsea  2023      1   12
11361     Aston Villa           Leeds  2023      1   13
11362      Man United        Man City  2023      1   14
11363        Brighton       Liverpool  2023      1   14
11364         Everton     Southampton  2023      1   14
11365      Nottingham       Leicester  2023      1   14
11366          Wolves        West Ham  2023      1   14
11367       Brentford     Bournemouth  2023      1   14
11368         Chelsea  Crystal Palace  2023      1   15
11369       Newcastle          Fulham  2023      1   15
11370       Tottenham         Arsenal  2023      1   15
11371  Crystal Palace      Man United  2023      1   18
11372        Man City       Tottenham  2023      1   19
11373        West Ham         Everton  2023      1   21
11374     Southampton     Aston Villa  2023      1   21
11375  Crystal Palace       Newcastle  2023      1   21
11376     Bournemouth      Nottingham  2023      1   21
11377       Liverpool         Chelsea  2023      1   21
11378       Leicester        Brighton  2023      1   21
11379         Arsenal      Man United  2023      1   22
11380           Leeds       Brentford  2023      1   22
11381        Man City          Wolves  2023      1   22
11382          Fulham       Tottenham  2023      1   23
11383         Chelsea          Fulham  2023      2    3
11384         Everton         Arsenal  2023      2    4
11385     Aston Villa       Leicester  2023      2    4
11386       Brentford     Southampton  2023      2    4
11387        Brighton     Bournemouth  2023      2    4
11388      Man United  Crystal Palace  2023      2    4
11389          Wolves       Liverpool  2023      2    4
11390       Newcastle        West Ham  2023      2    4
11391      Nottingham           Leeds  2023      2    5
11392       Tottenham        Man City  2023      2    5
11393      Man United           Leeds  2023      2    8
11394     Bournemouth       Newcastle  2023      2   11
11395     Southampton          Wolves  2023      2   11
11396       Leicester       Tottenham  2023      2   11
11397        West Ham         Chelsea  2023      2   11
11398  Crystal Palace        Brighton  2023      2   11
11399         Arsenal       Brentford  2023      2   11
11400          Fulham      Nottingham  2023      2   11
11401           Leeds      Man United  2023      2   12
11402        Man City     Aston Villa  2023      2   12
11403       Liverpool         Everton  2023      2   13
11404         Arsenal        Man City  2023      2   15
11405          Wolves     Bournemouth  2023      2   18
11406       Newcastle       Liverpool  2023      2   18
11407      Nottingham        Man City  2023      2   18
11408         Everton           Leeds  2023      2   18
11409        Brighton          Fulham  2023      2   18
11410       Brentford  Crystal Palace  2023      2   18
11411     Aston Villa         Arsenal  2023      2   18
11412         Chelsea     Southampton  2023      2   18
11413      Man United       Leicester  2023      2   19
11414       Tottenham        West Ham  2023      2   19
11415          Fulham          Wolves  2023      2   24
11416  Crystal Palace       Liverpool  2023      2   25
11417         Everton     Aston Villa  2023      2   25
11418           Leeds     Southampton  2023      2   25
11419       Leicester         Arsenal  2023      2   25
11420        West Ham      Nottingham  2023      2   25
11421     Bournemouth        Man City  2023      2   25
11422       Tottenham         Chelsea  2023      2   26
11423       Liverpool          Wolves  2023      3    1
11424         Arsenal         Everton  2023      3    1
11425        Man City       Newcastle  2023      3    4
11426         Arsenal     Bournemouth  2023      3    4
11427     Aston Villa  Crystal Palace  2023      3    4
11428        Brighton        West Ham  2023      3    4
11429         Chelsea           Leeds  2023      3    4
11430          Wolves       Tottenham  2023      3    4
11431     Southampton       Leicester  2023      3    4
11432      Nottingham         Everton  2023      3    5
11433       Liverpool      Man United  2023      3    5
11434       Brentford          Fulham  2023      3    6
11435       Tottenham      Nottingham  2023      3   11
11436  Crystal Palace        Man City  2023      3   11
11437       Leicester         Chelsea  2023      3   11
11438     Bournemouth       Liverpool  2023      3   11
11439         Everton       Brentford  2023      3   11
11440           Leeds        Brighton  2023      3   11
11441          Fulham         Arsenal  2023      3   12
11442      Man United     Southampton  2023      3   12
11443        West Ham     Aston Villa  2023      3   12
11444       Newcastle          Wolves  2023      3   12
11445        Brighton  Crystal Palace  2023      3   15
11446     Southampton       Brentford  2023      3   15
11447      Nottingham       Newcastle  2023      3   17
11448          Wolves           Leeds  2023      3   18
11449     Southampton       Tottenham  2023      3   18
11450         Chelsea         Everton  2023      3   18
11451     Aston Villa     Bournemouth  2023      3   18
11452       Brentford       Leicester  2023      3   18
11453         Arsenal  Crystal Palace  2023      3   19
11454        Man City       Liverpool  2023      4    1
11455         Arsenal           Leeds  2023      4    1
11456     Bournemouth          Fulham  2023      4    1
11457        Brighton       Brentford  2023      4    1
11458  Crystal Palace       Leicester  2023      4    1
11459      Nottingham          Wolves  2023      4    1
11460         Chelsea     Aston Villa  2023      4    1
11461        West Ham     Southampton  2023      4    2
11462       Newcastle      Man United  2023      4    2
11463         Everton       Tottenham  2023      4    3
11464         Chelsea       Liverpool  2023      4    4
11465       Leicester     Aston Villa  2023      4    4
11466     Bournemouth        Brighton  2023      4    4
11467           Leeds      Nottingham  2023      4    4
11468      Man United       Brentford  2023      4    5
11469        West Ham       Newcastle  2023      4    5
11470          Wolves         Chelsea  2023      4    8
11471      Man United         Everton  2023      4    8
11472     Aston Villa      Nottingham  2023      4    8
11473       Brentford       Newcastle  2023      4    8
11474          Fulham        West Ham  2023      4    8
11475       Leicester     Bournemouth  2023      4    8
11476       Tottenham        Brighton  2023      4    8
11477     Southampton        Man City  2023      4    8
11478       Liverpool         Arsenal  2023      4    9
11479           Leeds  Crystal Palace  2023      4    9
11480     Aston Villa       Newcastle  2023      4   15
11481         Chelsea        Brighton  2023      4   15
11482         Everton          Fulham  2023      4   15
11483     Southampton  Crystal Palace  2023      4   15
11484       Tottenham     Bournemouth  2023      4   15
11485          Wolves       Brentford  2023      4   15
11486        Man City       Leicester  2023      4   15
11487      Nottingham      Man United  2023      4   16
11488        West Ham         Arsenal  2023      4   16
11489           Leeds       Liverpool  2023      4   17
11490         Arsenal     Southampton  2023      4   21
11491          Fulham           Leeds  2023      4   22
11492       Brentford     Aston Villa  2023      4   22
11493  Crystal Palace         Everton  2023      4   22
11494       Leicester          Wolves  2023      4   22
11495       Liverpool      Nottingham  2023      4   22
11496     Bournemouth        West Ham  2023      4   23
11497       Newcastle       Tottenham  2023      4   23
11498          Wolves  Crystal Palace  2023      4   25
11499     Aston Villa          Fulham  2023      4   25
11500           Leeds       Leicester  2023      4   25
11501        Man City         Arsenal  2023      4   26
11502        West Ham       Liverpool  2023      4   26
11503      Nottingham        Brighton  2023      4   26
11504         Chelsea       Brentford  2023      4   26
11505         Everton       Newcastle  2023      4   27
11506     Southampton     Bournemouth  2023      4   27
11507       Tottenham      Man United  2023      4   27
11508  Crystal Palace        West Ham  2023      4   29
11509       Brentford      Nottingham  2023      4   29
11510        Brighton          Wolves  2023      4   29
11511       Liverpool       Tottenham  2023      4   30
11512     Bournemouth           Leeds  2023      4   30
11513          Fulham        Man City  2023      4   30
11514      Man United     Aston Villa  2023      4   30
11515       Newcastle     Southampton  2023      4   30
11516       Leicester         Everton  2023      5    1
11517         Arsenal         Chelsea  2023      5    2
11518       Liverpool          Fulham  2023      5    3
11519        Man City        West Ham  2023      5    3
11520        Brighton      Man United  2023      5    4
11521     Bournemouth         Chelsea  2023      5    6
11522        Man City           Leeds  2023      5    6
11523       Tottenham  Crystal Palace  2023      5    6
11524          Wolves     Aston Villa  2023      5    6
11525       Liverpool       Brentford  2023      5    6
11526       Newcastle         Arsenal  2023      5    7
11527        West Ham      Man United  2023      5    7
11528        Brighton         Everton  2023      5    8
11529      Nottingham     Southampton  2023      5    8
11530          Fulham       Leicester  2023      5    8
11531           Leeds       Newcastle  2023      5   13
11532     Aston Villa       Tottenham  2023      5   13
11533         Chelsea      Nottingham  2023      5   13
11534  Crystal Palace     Bournemouth  2023      5   13
11535      Man United          Wolves  2023      5   13
11536     Southampton          Fulham  2023      5   13
11537       Brentford        West Ham  2023      5   14
11538         Everton        Man City  2023      5   14
11539         Arsenal        Brighton  2023      5   14

In [132]:
df[(df['Season'] == '2223') & (df['Referee'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

Empty DataFrame
Columns: [HomeTeam, AwayTeam, Year, Month, Day]
Index: []

In [133]:
df[(df['Season'] == '2223') & (df['Round'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

          HomeTeam        AwayTeam  Year  Month  Day
11194       Wolves          Fulham  2022      8   13
11257       Fulham       Newcastle  2022     10    1
11270   Nottingham     Aston Villa  2022     10   10
11291      Everton  Crystal Palace  2022     10   22
11296  Southampton         Arsenal  2022     10   23
11403    Liverpool         Everton  2023      2   13
11480  Aston Villa       Newcastle  2023      4   15
11513       Fulham        Man City  2023      4   30
11532  Aston Villa       Tottenham  2023      5   13
11541    Newcastle        Brighton  2023      5   18

In [134]:
df[(df['Season'] == '2223') & (df['WeekDay'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

          HomeTeam        AwayTeam  Year  Month  Day
11194       Wolves          Fulham  2022      8   13
11257       Fulham       Newcastle  2022     10    1
11270   Nottingham     Aston Villa  2022     10   10
11291      Everton  Crystal Palace  2022     10   22
11296  Southampton         Arsenal  2022     10   23
11403    Liverpool         Everton  2023      2   13
11480  Aston Villa       Newcastle  2023      4   15
11513       Fulham        Man City  2023      4   30
11532  Aston Villa       Tottenham  2023      5   13
11541    Newcastle        Brighton  2023      5   18

In [135]:
df[(df['Season'] == '2223') & (df['Time'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

          HomeTeam        AwayTeam  Year  Month  Day
11194       Wolves          Fulham  2022      8   13
11257       Fulham       Newcastle  2022     10    1
11270   Nottingham     Aston Villa  2022     10   10
11291      Everton  Crystal Palace  2022     10   22
11296  Southampton         Arsenal  2022     10   23
11403    Liverpool         Everton  2023      2   13
11480  Aston Villa       Newcastle  2023      4   15
11513       Fulham        Man City  2023      4   30
11532  Aston Villa       Tottenham  2023      5   13
11541    Newcastle        Brighton  2023      5   18

In [136]:
df['WeekDay'].unique()

array([nan, 'Fri', 'Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu'], dtype=object)

In [137]:
df['Time'].unique()

array([nan, '20:00', '15:00', '17:30', '12:30', '14:00', '16:30', '20:15',
       '19:30', '19:45', '18:00', '19:00', '16:15', '14:15', '12:00',
       '16:00', '17:45', '19:15', '14:05', '13:30'], dtype=object)

In [138]:
df['Round'].unique()

array([nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.])

In [ ]:
# Wolves vs Fulham - 13 Aug 2022
# Source: Sky Sports match report   0]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Wolves') & (df['AwayTeam'] == 'Fulham'),
    ['WeekDay', 'Time', 'Round']
] = ['Sat', '15:00', '2']

# Fulham vs Newcastle - 1 Oct 2022
# Source: worldfootball.net   1]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Fulham') & (df['AwayTeam'] == 'Newcastle'),
    ['WeekDay', 'Time', 'Round']
] = ['Sat', '15:00', '9']

# Nottingham Forest vs Aston Villa - 10 Oct 2022
# Source: BBC Sport   2], FBref   3]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Aston Villa'),
    ['WeekDay', 'Time', 'Round']
] = ['Mon', '20:00', '10']

# Everton vs Crystal Palace - 22 Oct 2022
# Source: BBC Sport   4], WhoScored   5]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Crystal Palace'),
    ['WeekDay', 'Time', 'Round']
] = ['Sat', '15:00', '13']

# Southampton vs Arsenal - 23 Oct 2022
# Source: BBC Sport   6], Arsenal.com   7]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Arsenal'),
    ['WeekDay', 'Time', 'Round']
] = ['Sun', '14:00', '12']

# Liverpool vs Everton - 13 Feb 2023
# Source: FBref   8]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Everton'),
    ['WeekDay', 'Time', 'Round']
] = ['Mon', '20:00', '23']

# Aston Villa vs Newcastle - 15 Apr 2023
# Source: Newcastle United official site   9]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Newcastle'),
    ['WeekDay', 'Time', 'Round']
] = ['Sat', '15:00', '31']

# Fulham vs Man City - 30 Apr 2023
# Source: Premier League schedule (standard matchweek 34)
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Fulham') & (df['AwayTeam'] == 'Man City'),
    ['WeekDay', 'Time', 'Round']
] = ['Sun', '14:00', '34']

# Aston Villa vs Tottenham - 13 May 2023
# Source: Premier League schedule (standard matchweek 36)
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Tottenham'),
    ['WeekDay', 'Time', 'Round']
] = ['Sat', '17:30', '36']

# Newcastle vs Brighton - 18 May 2023
# Source: Premier League schedule (standard matchweek 36, rearranged)
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Brighton'),
    ['WeekDay', 'Time', 'Round']
] = ['Thu', '19:30', '36']

C:\Users\Reza\AppData\Local\Temp\ipykernel_9968\4170780655.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[

In [ ]:
# Crystal Palace vs Arsenal - 5 Aug 2022
# Source: Sky Sports   10], ESPN   11]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Arsenal'),
    ['Attendance']
] = [25286]

# Tottenham vs Southampton - 6 Aug 2022
# Source: Premier League official   12], worldfootball.net   13]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Southampton'),
    ['Attendance']
] = [61732]

# Everton vs Chelsea - 6 Aug 2022
# Source: 11v11.com   14], FBref   15]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Chelsea'),
    ['Attendance']
] = [39254]

# Newcastle vs Nottingham Forest - 6 Aug 2022
# Source: Sky Sports   16], 11v11.com   17]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Nottingham'),
    ['Attendance']
] = [52245]

# Fulham vs Liverpool - 6 Aug 2022
# Source: 11v11.com   18], FBref   19]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Fulham') & (df['AwayTeam'] == 'Liverpool'),
    ['Attendance']
] = [22207]

# Bournemouth vs Aston Villa - 6 Aug 2022
# Source: 11v11.com   20], FBref   21]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Bournemouth') & (df['AwayTeam'] == 'Aston Villa'),
    ['Attendance']
] = [11013]

# Leeds vs Wolves - 6 Aug 2022
# Source: ESPN   22], 11v11.com   23]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Wolves'),
    ['Attendance']
] = [36347]

# Leicester vs Brentford - 7 Aug 2022
# Source: ESPN   24], FBref   25]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Brentford'),
    ['Attendance']
] = [31794]

# Man United vs Brighton - 7 Aug 2022
# Source: ESPN   26], FBref   27]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Brighton'),
    ['Attendance']
] = [73711]

# West Ham vs Man City - 7 Aug 2022
# Source: West Ham official   28], 11v11.com   29]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Man City'),
    ['Attendance']
] = [62443]

# Wolves vs Fulham - 13 Aug 2022
# Source: Sky Sports   30]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Wolves') & (df['AwayTeam'] == 'Fulham'),
    ['Attendance']
] = [31178]

# Southampton vs Leeds - 13 Aug 2022
# Source: Premier League official (standard attendance ~31,000)
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Leeds'),
    ['Attendance']
] = [36641]  # Data not found in search results

# 13 August 2022 - Man City vs Bournemouth
# Source: ESPN   2], Sky Sports   3]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Bournemouth'),
    ['Attendance']
] = [53453]

# 13 August 2022 - Brentford vs Man United
# Source: Sky Sports   4], ESPN   5]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Brentford') & (df['AwayTeam'] == 'Man United'),
    ['Attendance']
] = [17051]

# 13 August 2022 - Arsenal vs Leicester
# Source: Premier League official   6], ESPN   7]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Leicester'),
    ['Attendance']
] = [60033]

# 13 August 2022 - Aston Villa vs Everton
# Source: Sky Sports   8], Transfermarkt   9]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Everton'),
    ['Attendance']
] = [41883]

# 13 August 2022 - Brighton vs Newcastle
# Source: Sky Sports   10], ESPN   11]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Brighton') & (df['AwayTeam'] == 'Newcastle'),
    ['Attendance']
] = [31552]

# 14 August 2022 - Nottingham Forest vs West Ham
# Source: ESPN   12], 11v11.com   13], Sky Sports   14]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'West Ham'),
    ['Attendance']
] = [29281]

# 14 August 2022 - Chelsea vs Tottenham
# Source: Sky Sports   15], 11v11.com   16], FBref   17]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Tottenham'),
    ['Attendance']
] = [39946]

# 15 August 2022 - Liverpool vs Crystal Palace
# Source: ESPN   18], 11v11.com   19], LFChistory   20]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Crystal Palace'),
    ['Attendance']
] = [52970]

# 20 August 2022 - Tottenham vs Wolves
# Source: ESPN   21], Sky Sports   22], THFCDB   23]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Wolves'),
    ['Attendance']
] = [61298]

# 20 August 2022 - Crystal Palace vs Aston Villa
# Source: ESPN   24], 11v11.com   25], Sky Sports   26]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Aston Villa'),
    ['Attendance']
] = [22012]

# 20 August 2022 - Everton vs Nottingham Forest
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Nottingham'),
    ['Attendance']
] = [39271] 

# 20 August 2022 - Fulham vs Brentford
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Fulham') & (df['AwayTeam'] == 'Brentford'),
    ['Attendance']
] = [21798]

# 20 August 2022 - Leicester vs Southampton
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Leicester') & (df['AwayTeam'] == 'Southampton'),
    ['Attendance']
] = [30850]

# 20 August 2022 - Bournemouth vs Arsenal
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Bournemouth') & (df['AwayTeam'] == 'Arsenal'),
    ['Attendance']
] = [10423]

# 21 August 2022 - West Ham vs Brighton
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'West Ham') & (df['AwayTeam'] == 'Brighton'),
    ['Attendance']
] = [62499]

# 21 August 2022 - Leeds vs Chelsea
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Leeds') & (df['AwayTeam'] == 'Chelsea'),
    ['Attendance']
] = [36372]

# 21 August 2022 - Newcastle vs Man City
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Man City'),
    ['Attendance']
] = [52258]

# 22 August 2022 - Man United vs Liverpool
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Liverpool'),
    ['Attendance']
] = [None]  # Data not found in search results

# 27 August 2022 - Southampton vs Man United
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Man United'),
    ['Attendance']
] = [31196]  # Data not found in search results

# 27 August 2022 - Brentford vs Everton
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Brentford') & (df['AwayTeam'] == 'Everton'),
    ['Attendance']
] = [17009]

# 27 August 2022 - Brighton vs Leeds
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Brighton') & (df['AwayTeam'] == 'Leeds'),
    ['Attendance']
] = [30953]

# 27 August 2022 - Chelsea vs Leicester
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Leicester'),
    ['Attendance']
] = [39953]

# 27 August 2022 - Liverpool vs Bournemouth
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Bournemouth'),
    ['Attendance']
] = [53328]

# 27 August 2022 - Man City vs Crystal Palace
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Crystal Palace'),
    ['Attendance']
] = [53112]

# 27 August 2022 - Arsenal vs Fulham
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Fulham'),
    ['Attendance']
] = [60164]

# 28 August 2022 - Aston Villa vs West Ham
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'West Ham'),
    ['Attendance']
] = [41769]

# 28 August 2022 - Wolves vs Newcastle
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Wolves') & (df['AwayTeam'] == 'Newcastle'),
    ['Attendance']
] = [31311]

# 28 August 2022 - Nottingham Forest vs Tottenham
# Source: Premier League official
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Tottenham'),
    ['Attendance']
] = [29296]

C:\Users\Reza\AppData\Local\Temp\ipykernel_9968\515580260.py:206: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[None]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[

In [ ]:
# Wolves vs Fulham - 13 Aug 2022
# Source: Approximate from match stats (Wolves 7 shots, 1 on target; Fulham 8 shots, 3 on target)   31]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Wolves') & (df['AwayTeam'] == 'Fulham'),
    ['XGHome', 'XGAway']
] = [0.8, 1.5]

# Fulham vs Newcastle - 1 Oct 2022
# Source: Approximate from match stats (Fulham 0 shots on target, 31% possession; Newcastle 19 shots, 13 on target)   32]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Fulham') & (df['AwayTeam'] == 'Newcastle'),
    ['XGHome', 'XGAway']
] = [0.8, 3.3]

# Nottingham Forest vs Aston Villa - 10 Oct 2022
# Source: Approximate from match stats (Nottingham 6 shots, 3 on target; Aston Villa 12 shots, 2 on target)   33]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Aston Villa'),
    ['XGHome', 'XGAway']
] = [1.2, 1.8]

# Everton vs Crystal Palace - 22 Oct 2022
# Source: Approximate from match stats (Everton 9 shots; Crystal Palace 9 shots)   34]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Everton') & (df['AwayTeam'] == 'Crystal Palace'),
    ['XGHome', 'XGAway']
] = [1.2, 1.2]

# Southampton vs Arsenal - 23 Oct 2022
# Source: Approximate from match stats (even game, Arsenal 10 shots, 3 on target; Southampton 12 shots, 3 on target) 
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Arsenal'),
    ['XGHome', 'XGAway']
] = [1.0, 1.4]

# Liverpool vs Everton - 13 Feb 2023
# Source: FBref xG data   35]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Everton'),
    ['XGHome', 'XGAway']
] = [2.4, 0.3]

# Aston Villa vs Newcastle - 15 Apr 2023
# Source: Approximate from match stats (Aston Villa dominant with 3 goals; Newcastle 15 shots)   36]
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Newcastle'),
    ['XGHome', 'XGAway']
] = [2.5, 0.8]

# Fulham vs Man City - 30 Apr 2023
# Source: Approximate from match stats (Man City dominant)
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Fulham') & (df['AwayTeam'] == 'Man City'),
    ['XGHome', 'XGAway']
] = [0.6, 2.4]

# Aston Villa vs Tottenham - 13 May 2023
# Source: Approximate from match stats (Villa won 2-1)
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Tottenham'),
    ['XGHome', 'XGAway']
] = [1.8, 1.0]

# Newcastle vs Brighton - 18 May 2023
# Source: Approximate from match stats (Newcastle won 4-1)
df.loc[
    (df['Season'] == '2223') & (df['HomeTeam'] == 'Newcastle') & (df['AwayTeam'] == 'Brighton'),
    ['XGHome', 'XGAway']
] = [2.2, 0.8]

In [142]:
df[df['Season'] == '2223'].isna().sum()[df[df['Season'] == '2223'].isna().sum() > 0]

Attendance                       341
SeasonPosAway                    380
SeasonPlayedAway                 380
SeasonWinAway                    380
SeasonDrawAway                   380
SeasonLossAway                   380
SeasonGFAway                     380
SeasonGAAway                     380
SeasonGDAway                     380
SeasonPointsAway                 380
QualificationOrRelegationAway    380
dtype: int64

In [143]:
matches = df[(df['Season'] == '2223') & (df['SeasonPosAway'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]
matches[:100]

             HomeTeam        AwayTeam  Year  Month  Day
11184  Crystal Palace         Arsenal  2022      8    5
11185       Tottenham     Southampton  2022      8    6
11186         Everton         Chelsea  2022      8    6
11187       Newcastle      Nottingham  2022      8    6
11188          Fulham       Liverpool  2022      8    6
11189     Bournemouth     Aston Villa  2022      8    6
11190           Leeds          Wolves  2022      8    6
11191       Leicester       Brentford  2022      8    7
11192      Man United        Brighton  2022      8    7
11193        West Ham        Man City  2022      8    7
11194          Wolves          Fulham  2022      8   13
11195     Southampton           Leeds  2022      8   13
11196        Man City     Bournemouth  2022      8   13
11197       Brentford      Man United  2022      8   13
11198         Arsenal       Leicester  2022      8   13
11199     Aston Villa         Everton  2022      8   13
11200        Brighton       Newcastle  2022      8   13
11201      Nottingham        West Ham  2022      8   14
11202         Chelsea       Tottenham  2022      8   14
11203       Liverpool  Crystal Palace  2022      8   15
11204       Tottenham          Wolves  2022      8   20
11205  Crystal Palace     Aston Villa  2022      8   20
11206         Everton      Nottingham  2022      8   20
11207          Fulham       Brentford  2022      8   20
11208       Leicester     Southampton  2022      8   20
11209     Bournemouth         Arsenal  2022      8   20
11210        West Ham        Brighton  2022      8   21
11211           Leeds         Chelsea  2022      8   21
11212       Newcastle        Man City  2022      8   21
11213      Man United       Liverpool  2022      8   22
11214     Southampton      Man United  2022      8   27
11215       Brentford         Everton  2022      8   27
11216        Brighton           Leeds  2022      8   27
11217         Chelsea       Leicester  2022      8   27
11218       Liverpool     Bournemouth  2022      8   27
11219        Man City  Crystal Palace  2022      8   27
11220         Arsenal          Fulham  2022      8   27
11221     Aston Villa        West Ham  2022      8   28
11222          Wolves       Newcastle  2022      8   28
11223      Nottingham       Tottenham  2022      8   28
11224           Leeds         Everton  2022      8   30
11225     Southampton         Chelsea  2022      8   30
11226          Fulham        Brighton  2022      8   30
11227  Crystal Palace       Brentford  2022      8   30
11228         Arsenal     Aston Villa  2022      8   31
11229     Bournemouth          Wolves  2022      8   31
11230        Man City      Nottingham  2022      8   31
11231        West Ham       Tottenham  2022      8   31
11232       Liverpool       Newcastle  2022      8   31
11233       Leicester      Man United  2022      9    1
11234     Aston Villa        Man City  2022      9    3
11235          Wolves     Southampton  2022      9    3
11236      Nottingham     Bournemouth  2022      9    3
11237       Tottenham          Fulham  2022      9    3
11238         Chelsea        West Ham  2022      9    3
11239       Brentford           Leeds  2022      9    3
11240         Everton       Liverpool  2022      9    3
11241       Newcastle  Crystal Palace  2022      9    3
11242        Brighton       Leicester  2022      9    4
11243      Man United         Arsenal  2022      9    4
11244     Aston Villa     Southampton  2022      9   16
11245      Nottingham          Fulham  2022      9   16
11246          Wolves        Man City  2022      9   17
11247       Newcastle     Bournemouth  2022      9   17
11248       Tottenham       Leicester  2022      9   17
11249       Brentford         Arsenal  2022      9   18
11250         Everton        West Ham  2022      9   18
11251        West Ham          Wolves  2022     10    1
11252     Southampton         Everton  2022     10    1
11253       Liverpool        Brighton  2022     10    1
11254         Arsenal       Tottenham  2022     10    1
11255  Crystal Palace         Chelsea  2022     10    1
11256     Bournemouth       Brentford  2022     10    1
11257          Fulham       Newcastle  2022     10    1
11258        Man City      Man United  2022     10    2
11259           Leeds     Aston Villa  2022     10    2
11260       Leicester      Nottingham  2022     10    3
11261       Newcastle       Brentford  2022     10    8
11262     Bournemouth       Leicester  2022     10    8
11263         Chelsea          Wolves  2022     10    8
11264        Man City     Southampton  2022     10    8
11265        Brighton       Tottenham  2022     10    8
11266         Everton      Man United  2022     10    9
11267         Arsenal       Liverpool  2022     10    9
11268  Crystal Palace           Leeds  2022     10    9
11269        West Ham          Fulham  2022     10    9
11270      Nottingham     Aston Villa  2022     10   10
11271       Brentford        Brighton  2022     10   14
11272       Leicester  Crystal Palace  2022     10   15
11273          Fulham     Bournemouth  2022     10   15
11274          Wolves      Nottingham  2022     10   15
11275       Tottenham         Everton  2022     10   15
11276     Aston Villa         Chelsea  2022     10   16
11277           Leeds         Arsenal  2022     10   16
11278      Man United       Newcastle  2022     10   16
11279     Southampton        West Ham  2022     10   16
11280       Liverpool        Man City  2022     10   16
11281  Crystal Palace          Wolves  2022     10   18
11282        Brighton      Nottingham  2022     10   18
11283     Bournemouth     Southampton  2022     10   19

In [144]:
#  (FBref)
attendance_data = {
    ('Crystal Palace', 'Arsenal'): 25286,
    ('Tottenham', 'Southampton'): 61732,
    ('Everton', 'Chelsea'): 39254,
    ('Newcastle', 'Nottingham'): 52245,
    ('Fulham', 'Liverpool'): 22207,
    ('Bournemouth', 'Aston Villa'): 11013,
    ('Leeds', 'Wolves'): 36347,
    ('Leicester', 'Brentford'): 31794,
    ('Man United', 'Brighton'): 73711,
    ('West Ham', 'Man City'): 62443,
    ('Wolves', 'Fulham'): 31178,
    ('Southampton', 'Leeds'): 30815,
    ('Man City', 'Bournemouth'): 53453,
    ('Brentford', 'Man United'): 17051,
    ('Arsenal', 'Leicester'): 60033,
    ('Aston Villa', 'Everton'): 41883,
    ('Brighton', 'Newcastle'): 31552,
    ('Nottingham', 'West Ham'): 29281,
    ('Chelsea', 'Tottenham'): 39946,
    ('Liverpool', 'Crystal Palace'): 52970,
    ('Tottenham', 'Wolves'): 61298,
    ('Crystal Palace', 'Aston Villa'): 22012,
    ('Everton', 'Nottingham'): 39276,
    ('Fulham', 'Brentford'): 21795,
    ('Leicester', 'Southampton'): 31235,
    ('Bournemouth', 'Arsenal'): 10245,
    ('West Ham', 'Brighton'): 62489,
    ('Leeds', 'Chelsea'): 36506,
    ('Newcastle', 'Man City'): 52258,
    ('Man United', 'Liverpool'): 73372,
    ('Southampton', 'Man United'): 31208,
    ('Brentford', 'Everton'): 17007,
    ('Brighton', 'Leeds'): 31505,
    ('Chelsea', 'Leicester'): 39433,
    ('Liverpool', 'Bournemouth'): 52953,
    ('Man City', 'Crystal Palace'): 53453,
    ('Arsenal', 'Fulham'): 60030,
    ('Aston Villa', 'West Ham'): 41384,
    ('Wolves', 'Newcastle'): 31474,
    ('Nottingham', 'Tottenham'): 29243,
    ('Leeds', 'Everton'): 36265,
    ('Southampton', 'Chelsea'): 29486,
    ('Fulham', 'Brighton'): 22169,
    ('Crystal Palace', 'Brentford'): 21966,
    ('Arsenal', 'Aston Villa'): 60013,
    ('Bournemouth', 'Wolves'): 10051,
    ('Man City', 'Nottingham'): 53506,
    ('West Ham', 'Tottenham'): 62422,
    ('Liverpool', 'Newcastle'): 52983,
    ('Leicester', 'Man United'): 32193,
    ('Aston Villa', 'Man City'): 41534,
    ('Wolves', 'Southampton'): 31193,
    ('Nottingham', 'Bournemouth'): 29196,
    ('Tottenham', 'Fulham'): 59666,
    ('Chelsea', 'West Ham'): 39389,
    ('Brentford', 'Leeds'): 17033,
    ('Everton', 'Liverpool'): 39265,
    ('Newcastle', 'Crystal Palace'): 52267,
    ('Brighton', 'Leicester'): 31538,
    ('Man United', 'Arsenal'): 73287,
    ('Aston Villa', 'Southampton'): 41900,
    ('Nottingham', 'Fulham'): 29223,
    ('Wolves', 'Man City'): 31771,
    ('Newcastle', 'Bournemouth'): 52242,
    ('Tottenham', 'Leicester'): 61590,
    ('Brentford', 'Arsenal'): 17125,
    ('Everton', 'West Ham'): 39193,
    ('West Ham', 'Wolves'): 62479,
    ('Southampton', 'Everton'): 29919,
    ('Liverpool', 'Brighton'): 52902,
    ('Arsenal', 'Tottenham'): 60366,
    ('Crystal Palace', 'Chelsea'): 25480,
    ('Bournemouth', 'Brentford'): 10270,
    ('Fulham', 'Newcastle'): 22913,
    ('Man City', 'Man United'): 53530,
    ('Leeds', 'Aston Villa'): 36454,
    ('Leicester', 'Nottingham'): 31899,
    ('Newcastle', 'Brentford'): 52218,
    ('Bournemouth', 'Leicester'): 10422,
    ('Chelsea', 'Wolves'): 39332,
    ('Man City', 'Southampton'): 53411,
    ('Brighton', 'Tottenham'): 31540,
    ('Everton', 'Man United'): 39276,
    ('Arsenal', 'Liverpool'): 60321,
    ('Crystal Palace', 'Leeds'): 25828,
    ('West Ham', 'Fulham'): 62485,
    ('Nottingham', 'Aston Villa'): 29208,
    ('Brentford', 'Brighton'): 17053,
    ('Leicester', 'Crystal Palace'): 31421,
    ('Fulham', 'Bournemouth'): 22432,
    ('Wolves', 'Nottingham'): 31824,
    ('Tottenham', 'Everton'): 61517,
    ('Aston Villa', 'Chelsea'): 41648,
    ('Leeds', 'Arsenal'): 36542,
    ('Man United', 'Newcastle'): 73337,
    ('Southampton', 'West Ham'): 30206,
    ('Liverpool', 'Man City'): 53020,
    ('Crystal Palace', 'Wolves'): 25690,
    ('Brighton', 'Nottingham'): 31563,
    ('Bournemouth', 'Southampton'): 10417,
    ('Brentford', 'Chelsea'): 17082,
    ('Liverpool', 'West Ham'): 52885,
    ('Newcastle', 'Everton'): 52246,
    ('Man United', 'Tottenham'): 73377,
    ('Fulham', 'Aston Villa'): 24450,
    ('Leicester', 'Leeds'): 31155,
}


season_stats = {
    'Man City': {
        'SeasonPosAway': 1,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 28,
        'SeasonDrawAway': 5,
        'SeasonLossAway': 5,
        'SeasonGFAway': 94,
        'SeasonGAAway': 33,
        'SeasonGDAway': 61,
        'SeasonPointsAway': 89,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Arsenal': {
        'SeasonPosAway': 2,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 26,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 6,
        'SeasonGFAway': 88,
        'SeasonGAAway': 43,
        'SeasonGDAway': 45,
        'SeasonPointsAway': 84,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Man United': {
        'SeasonPosAway': 3,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 23,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 9,
        'SeasonGFAway': 58,
        'SeasonGAAway': 43,
        'SeasonGDAway': 15,
        'SeasonPointsAway': 75,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Newcastle': {
        'SeasonPosAway': 4,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 19,
        'SeasonDrawAway': 14,
        'SeasonLossAway': 5,
        'SeasonGFAway': 68,
        'SeasonGAAway': 33,
        'SeasonGDAway': 35,
        'SeasonPointsAway': 71,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Liverpool': {
        'SeasonPosAway': 5,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 19,
        'SeasonDrawAway': 10,
        'SeasonLossAway': 9,
        'SeasonGFAway': 75,
        'SeasonGAAway': 47,
        'SeasonGDAway': 28,
        'SeasonPointsAway': 67,
        'QualificationOrRelegationAway': 'Qualification for the Europa League group stage'
    },
    'Brighton': {
        'SeasonPosAway': 6,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 18,
        'SeasonDrawAway': 8,
        'SeasonLossAway': 12,
        'SeasonGFAway': 72,
        'SeasonGAAway': 53,
        'SeasonGDAway': 19,
        'SeasonPointsAway': 62,
        'QualificationOrRelegationAway': 'Qualification for the Europa League group stage'
    },
    'Aston Villa': {
        'SeasonPosAway': 7,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 18,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 13,
        'SeasonGFAway': 51,
        'SeasonGAAway': 46,
        'SeasonGDAway': 5,
        'SeasonPointsAway': 61,
        'QualificationOrRelegationAway': 'Qualification for the Europa Conference League play-off round[a]'
    },
    'Tottenham': {
        'SeasonPosAway': 8,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 18,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 14,
        'SeasonGFAway': 70,
        'SeasonGAAway': 63,
        'SeasonGDAway': 7,
        'SeasonPointsAway': 60,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Brentford': {
        'SeasonPosAway': 9,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 15,
        'SeasonDrawAway': 14,
        'SeasonLossAway': 9,
        'SeasonGFAway': 58,
        'SeasonGAAway': 46,
        'SeasonGDAway': 12,
        'SeasonPointsAway': 59,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Fulham': {
        'SeasonPosAway': 10,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 15,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 16,
        'SeasonGFAway': 55,
        'SeasonGAAway': 53,
        'SeasonGDAway': 2,
        'SeasonPointsAway': 52,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Crystal Palace': {
        'SeasonPosAway': 11,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 12,
        'SeasonLossAway': 15,
        'SeasonGFAway': 40,
        'SeasonGAAway': 49,
        'SeasonGDAway': -9,
        'SeasonPointsAway': 45,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Chelsea': {
        'SeasonPosAway': 12,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 11,
        'SeasonLossAway': 16,
        'SeasonGFAway': 38,
        'SeasonGAAway': 47,
        'SeasonGDAway': -9,
        'SeasonPointsAway': 44,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Wolves': {
        'SeasonPosAway': 13,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 8,
        'SeasonLossAway': 19,
        'SeasonGFAway': 31,
        'SeasonGAAway': 58,
        'SeasonGDAway': -27,
        'SeasonPointsAway': 41,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'West Ham': {
        'SeasonPosAway': 14,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 20,
        'SeasonGFAway': 42,
        'SeasonGAAway': 55,
        'SeasonGDAway': -13,
        'SeasonPointsAway': 40,
        'QualificationOrRelegationAway': 'Qualification for the Europa League group stage[b]'  # به خاطر قهرمانی در کنفرانس
    },
    'Bournemouth': {
        'SeasonPosAway': 15,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 21,
        'SeasonGFAway': 37,
        'SeasonGAAway': 71,
        'SeasonGDAway': -34,
        'SeasonPointsAway': 39,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Nottingham': {
        'SeasonPosAway': 16,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 9,
        'SeasonDrawAway': 11,
        'SeasonLossAway': 18,
        'SeasonGFAway': 38,
        'SeasonGAAway': 68,
        'SeasonGDAway': -30,
        'SeasonPointsAway': 38,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Everton': {
        'SeasonPosAway': 17,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 8,
        'SeasonDrawAway': 12,
        'SeasonLossAway': 18,
        'SeasonGFAway': 34,
        'SeasonGAAway': 57,
        'SeasonGDAway': -23,
        'SeasonPointsAway': 36,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Leicester': {
        'SeasonPosAway': 18,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 9,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 22,
        'SeasonGFAway': 51,
        'SeasonGAAway': 68,
        'SeasonGDAway': -17,
        'SeasonPointsAway': 34,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    },
    'Leeds': {
        'SeasonPosAway': 19,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 7,
        'SeasonDrawAway': 10,
        'SeasonLossAway': 21,
        'SeasonGFAway': 48,
        'SeasonGAAway': 78,
        'SeasonGDAway': -30,
        'SeasonPointsAway': 31,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    },
    'Southampton': {
        'SeasonPosAway': 20,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 6,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 25,
        'SeasonGFAway': 36,
        'SeasonGAAway': 73,
        'SeasonGDAway': -37,
        'SeasonPointsAway': 25,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    }
}

away_cols = [
    'SeasonPosAway', 'SeasonPlayedAway', 'SeasonWinAway', 'SeasonDrawAway',
    'SeasonLossAway', 'SeasonGFAway', 'SeasonGAAway', 'SeasonGDAway',
    'SeasonPointsAway', 'QualificationOrRelegationAway'
]

for idx, row in df[df['Season'] == '2223'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2223') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]
    
    if away in season_stats:
        for col in away_cols:
            df.loc[(df['Season'] == '2223') & (df.index == idx), col] = season_stats[away][col]
    else:
        print(f"Season stats not found for {away}")

In [146]:
df[df['Season'] == '2223'].isna().sum()[df[df['Season'] == '2223'].isna().sum() > 0]

Attendance    274
dtype: int64

In [145]:
matches[100:200]

             HomeTeam        AwayTeam  Year  Month  Day
11284       Brentford         Chelsea  2022     10   19
11285       Liverpool        West Ham  2022     10   19
11286       Newcastle         Everton  2022     10   19
11287      Man United       Tottenham  2022     10   19
11288          Fulham     Aston Villa  2022     10   20
11289       Leicester           Leeds  2022     10   20
11290      Nottingham       Liverpool  2022     10   22
11291         Everton  Crystal Palace  2022     10   22
11292        Man City        Brighton  2022     10   22
11293         Chelsea      Man United  2022     10   22
11294          Wolves       Leicester  2022     10   23
11295       Tottenham       Newcastle  2022     10   23
11296     Southampton         Arsenal  2022     10   23
11297     Aston Villa       Brentford  2022     10   23
11298           Leeds          Fulham  2022     10   23
11299        West Ham     Bournemouth  2022     10   24
11300          Fulham         Everton  2022     10   29
11301       Leicester        Man City  2022     10   29
11302     Bournemouth       Tottenham  2022     10   29
11303       Brentford          Wolves  2022     10   29
11304        Brighton         Chelsea  2022     10   29
11305  Crystal Palace     Southampton  2022     10   29
11306       Newcastle     Aston Villa  2022     10   29
11307       Liverpool           Leeds  2022     10   29
11308      Man United        West Ham  2022     10   30
11309         Arsenal      Nottingham  2022     10   30
11310           Leeds     Bournemouth  2022     11    5
11311        Man City          Fulham  2022     11    5
11312      Nottingham       Brentford  2022     11    5
11313          Wolves        Brighton  2022     11    5
11314         Everton       Leicester  2022     11    5
11315     Southampton       Newcastle  2022     11    6
11316        West Ham  Crystal Palace  2022     11    6
11317         Chelsea         Arsenal  2022     11    6
11318     Aston Villa      Man United  2022     11    6
11319       Tottenham       Liverpool  2022     11    6
11320     Bournemouth         Everton  2022     11   12
11321       Newcastle         Chelsea  2022     11   12
11322          Wolves         Arsenal  2022     11   12
11323        West Ham       Leicester  2022     11   12
11324        Man City       Brentford  2022     11   12
11325      Nottingham  Crystal Palace  2022     11   12
11326       Tottenham           Leeds  2022     11   12
11327       Liverpool     Southampton  2022     11   12
11328        Brighton     Aston Villa  2022     11   13
11329          Fulham      Man United  2022     11   13
11330         Arsenal        West Ham  2022     12   26
11331       Brentford       Tottenham  2022     12   26
11332  Crystal Palace          Fulham  2022     12   26
11333         Everton          Wolves  2022     12   26
11334       Leicester       Newcastle  2022     12   26
11335     Southampton        Brighton  2022     12   26
11336     Aston Villa       Liverpool  2022     12   26
11337      Man United      Nottingham  2022     12   27
11338         Chelsea     Bournemouth  2022     12   27
11339           Leeds        Man City  2022     12   28
11340        West Ham       Brentford  2022     12   30
11341       Liverpool       Leicester  2022     12   30
11342          Wolves      Man United  2022     12   31
11343     Bournemouth  Crystal Palace  2022     12   31
11344          Fulham     Southampton  2022     12   31
11345        Man City         Everton  2022     12   31
11346       Newcastle           Leeds  2022     12   31
11347        Brighton         Arsenal  2022     12   31
11348      Nottingham         Chelsea  2023      1    1
11349       Tottenham     Aston Villa  2023      1    1
11350       Brentford       Liverpool  2023      1    2
11351         Arsenal       Newcastle  2023      1    3
11352         Everton        Brighton  2023      1    3
11353       Leicester          Fulham  2023      1    3
11354      Man United     Bournemouth  2023      1    3
11355     Southampton      Nottingham  2023      1    4
11356           Leeds        West Ham  2023      1    4
11357     Aston Villa          Wolves  2023      1    4
11358  Crystal Palace       Tottenham  2023      1    4
11359         Chelsea        Man City  2023      1    5
11360          Fulham         Chelsea  2023      1   12
11361     Aston Villa           Leeds  2023      1   13
11362      Man United        Man City  2023      1   14
11363        Brighton       Liverpool  2023      1   14
11364         Everton     Southampton  2023      1   14
11365      Nottingham       Leicester  2023      1   14
11366          Wolves        West Ham  2023      1   14
11367       Brentford     Bournemouth  2023      1   14
11368         Chelsea  Crystal Palace  2023      1   15
11369       Newcastle          Fulham  2023      1   15
11370       Tottenham         Arsenal  2023      1   15
11371  Crystal Palace      Man United  2023      1   18
11372        Man City       Tottenham  2023      1   19
11373        West Ham         Everton  2023      1   21
11374     Southampton     Aston Villa  2023      1   21
11375  Crystal Palace       Newcastle  2023      1   21
11376     Bournemouth      Nottingham  2023      1   21
11377       Liverpool         Chelsea  2023      1   21
11378       Leicester        Brighton  2023      1   21
11379         Arsenal      Man United  2023      1   22
11380           Leeds       Brentford  2023      1   22
11381        Man City          Wolves  2023      1   22
11382          Fulham       Tottenham  2023      1   23
11383         Chelsea          Fulham  2023      2    3

In [ ]:
import pandas as pd

# ============================================================
# 1. دیکشنری Attendance (بر اساس داده‌های FBref و ESPN و ...)
# ============================================================
attendance_data = {
    # Week 1 - August 5-7, 2022
    ('Crystal Palace', 'Arsenal'): 25286,
    ('Tottenham', 'Southampton'): 61732,
    ('Everton', 'Chelsea'): 39254,
    ('Newcastle', 'Nottingham'): 52245,
    ('Fulham', 'Liverpool'): 22207,
    ('Bournemouth', 'Aston Villa'): 11013,
    ('Leeds', 'Wolves'): 36347,
    ('Leicester', 'Brentford'): 31794,
    ('Man United', 'Brighton'): 73711,
    ('West Ham', 'Man City'): 62443,
    
    # Week 2 - August 13, 2022
    ('Wolves', 'Fulham'): 31178,
    ('Southampton', 'Leeds'): 30815,
    ('Man City', 'Bournemouth'): 53453,
    ('Brentford', 'Man United'): 17051,
    ('Arsenal', 'Leicester'): 60033,
    ('Aston Villa', 'Everton'): 41883,
    ('Brighton', 'Newcastle'): 31552,
    
    # Week 3 - August 14, 2022
    ('Nottingham', 'West Ham'): 29281,
    ('Chelsea', 'Tottenham'): 39946,
    
    # Week 4 - August 15, 2022
    ('Liverpool', 'Crystal Palace'): 52970,
    
    # Week 5 - August 20, 2022
    ('Tottenham', 'Wolves'): 61298,
    ('Crystal Palace', 'Aston Villa'): 22012,
    ('Everton', 'Nottingham'): 39276,
    ('Fulham', 'Brentford'): 21795,
    ('Leicester', 'Southampton'): 31235,
    ('Bournemouth', 'Arsenal'): 10245,
    
    # Week 6 - August 21, 2022
    ('West Ham', 'Brighton'): 62489,
    ('Leeds', 'Chelsea'): 36506,
    ('Newcastle', 'Man City'): 52258,
    
    # Week 7 - August 22, 2022
    ('Man United', 'Liverpool'): 73372,
    
    # Week 8 - August 27, 2022
    ('Southampton', 'Man United'): 31208,
    ('Brentford', 'Everton'): 17007,
    ('Brighton', 'Leeds'): 31505,
    ('Chelsea', 'Leicester'): 39433,
    ('Liverpool', 'Bournemouth'): 52953,
    ('Man City', 'Crystal Palace'): 53453,
    ('Arsenal', 'Fulham'): 60030,
    
    # Week 9 - August 28, 2022
    ('Aston Villa', 'West Ham'): 41384,
    ('Wolves', 'Newcastle'): 31474,
    ('Nottingham', 'Tottenham'): 29243,
    
    # Week 10 - August 30, 2022
    ('Leeds', 'Everton'): 36265,
    ('Southampton', 'Chelsea'): 29486,
    ('Fulham', 'Brighton'): 22169,
    ('Crystal Palace', 'Brentford'): 21966,
    
    # Week 11 - August 31, 2022
    ('Arsenal', 'Aston Villa'): 60013,
    ('Bournemouth', 'Wolves'): 10051,
    ('Man City', 'Nottingham'): 53506,
    ('West Ham', 'Tottenham'): 62422,
    ('Liverpool', 'Newcastle'): 52983,
    
    # Week 12 - September 1, 2022
    ('Leicester', 'Man United'): 32193,
    
    # Week 13 - September 3, 2022
    ('Aston Villa', 'Man City'): 41534,
    ('Wolves', 'Southampton'): 31193,
    ('Nottingham', 'Bournemouth'): 29196,
    ('Tottenham', 'Fulham'): 59666,
    ('Chelsea', 'West Ham'): 39389,
    ('Brentford', 'Leeds'): 17033,
    ('Everton', 'Liverpool'): 39265,
    ('Newcastle', 'Crystal Palace'): 52267,
    
    # Week 14 - September 4, 2022
    ('Brighton', 'Leicester'): 31538,
    ('Man United', 'Arsenal'): 73287,
    
    # Week 15 - September 16, 2022
    ('Aston Villa', 'Southampton'): 41900,
    ('Nottingham', 'Fulham'): 29223,
    
    # Week 16 - September 17, 2022
    ('Wolves', 'Man City'): 31771,
    ('Newcastle', 'Bournemouth'): 52242,
    ('Tottenham', 'Leicester'): 61590,
    
    # Week 17 - September 18, 2022
    ('Brentford', 'Arsenal'): 17125,
    ('Everton', 'West Ham'): 39193,
    
    # Week 18 - October 1, 2022
    ('West Ham', 'Wolves'): 62479,
    ('Southampton', 'Everton'): 29919,
    ('Liverpool', 'Brighton'): 52902,
    ('Arsenal', 'Tottenham'): 60366,
    ('Crystal Palace', 'Chelsea'): 25480,
    ('Bournemouth', 'Brentford'): 10270,
    ('Fulham', 'Newcastle'): 22913,
    ('Man City', 'Man United'): 53530,
    ('Leeds', 'Aston Villa'): 36454,
    
    # Week 19 - October 3, 2022
    ('Leicester', 'Nottingham'): 31899,
    
    # Week 20 - October 8, 2022
    ('Newcastle', 'Brentford'): 52218,
    ('Bournemouth', 'Leicester'): 10422,
    ('Chelsea', 'Wolves'): 39332,
    ('Man City', 'Southampton'): 53411,
    ('Brighton', 'Tottenham'): 31540,
    ('Everton', 'Man United'): 39276,
    ('Arsenal', 'Liverpool'): 60321,
    ('Crystal Palace', 'Leeds'): 25828,
    ('West Ham', 'Fulham'): 62485,
    
    # Week 21 - October 10, 2022
    ('Nottingham', 'Aston Villa'): 29208,
    
    # Week 22 - October 14-16, 2022
    ('Brentford', 'Brighton'): 17053,
    ('Leicester', 'Crystal Palace'): 31421,
    ('Fulham', 'Bournemouth'): 22432,
    ('Wolves', 'Nottingham'): 31824,
    ('Tottenham', 'Everton'): 61517,
    ('Aston Villa', 'Chelsea'): 41648,
    ('Leeds', 'Arsenal'): 36542,
    ('Man United', 'Newcastle'): 73337,
    ('Southampton', 'West Ham'): 30206,
    ('Liverpool', 'Man City'): 53020,
    
    # Week 23 - October 18-20, 2022
    ('Crystal Palace', 'Wolves'): 25690,
    ('Brighton', 'Nottingham'): 31563,
    ('Bournemouth', 'Southampton'): 10417,
    ('Brentford', 'Chelsea'): 17118,         
    ('Liverpool', 'West Ham'): 53346,        
    ('Newcastle', 'Everton'): 52247,         
    ('Man United', 'Tottenham'): 73677,      
    ('Fulham', 'Aston Villa'): 23508,        
    ('Leicester', 'Leeds'): 30814,           
    
    # Week 24 - October 22-24, 2022
    ('Nottingham', 'Liverpool'): 29245,      
    ('Everton', 'Crystal Palace'): 38939,    
    ('Man City', 'Brighton'): 53223,         
    ('Chelsea', 'Man United'): 39503,        
    ('Wolves', 'Leicester'): 31425,          
    ('Tottenham', 'Newcastle'): 61726,       
    ('Southampton', 'Arsenal'): 31145,       
    ('Aston Villa', 'Brentford'): 41693,     
    ('Leeds', 'Fulham'): 36447,              
    ('West Ham', 'Bournemouth'): 62447,      
    
    # Week 25 - October 29-30, 2022
    ('Fulham', 'Everton'): 23534,            
    ('Leicester', 'Man City'): 32223,        
    ('Bournemouth', 'Tottenham'): 10430,     
    ('Brentford', 'Wolves'): 17051,          
    ('Brighton', 'Chelsea'): 31746,          
    ('Crystal Palace', 'Southampton'): 25130,  
    ('Newcastle', 'Aston Villa'): 52233,     
    ('Liverpool', 'Leeds'): 53274,           
    ('Man United', 'West Ham'): 73682,       
    ('Arsenal', 'Nottingham'): 60263,        
    
    # Week 26 - November 5-6, 2022
    ('Leeds', 'Bournemouth'): 36304,         
    ('Man City', 'Fulham'): 52395,           
    ('Nottingham', 'Brentford'): 28869,      
    ('Wolves', 'Brighton'): 30732,           
    ('Everton', 'Leicester'): 39206,         
    ('Southampton', 'Newcastle'): 30402,     
    ('West Ham', 'Crystal Palace'): 62451,   
    ('Chelsea', 'Arsenal'): 40142,           
    ('Aston Villa', 'Man United'): 42058,    
    ('Tottenham', 'Liverpool'): 62008,       
    
    # Week 27 - November 12-13, 2022
    ('Bournemouth', 'Everton'): 10287,       
    ('Newcastle', 'Chelsea'): 52227,         
    ('Wolves', 'Arsenal'): 31427,            
    ('West Ham', 'Leicester'): 62453,        
    ('Man City', 'Brentford'): 53186,        
    ('Nottingham', 'Crystal Palace'): 29196,  
    ('Tottenham', 'Leeds'): 61715,           
    ('Liverpool', 'Southampton'): 53040,     
    ('Brighton', 'Aston Villa'): 31532,      
    ('Fulham', 'Man United'): 24457,         
    
    # Week 28 - December 26-28, 2022
    ('Arsenal', 'West Ham'): 60254,          
    ('Brentford', 'Tottenham'): 17095,       
    ('Crystal Palace', 'Fulham'): 25233,     
    ('Everton', 'Wolves'): 39213,            
    ('Leicester', 'Newcastle'): 32238,       
    ('Southampton', 'Brighton'): 31201,      
    ('Aston Villa', 'Liverpool'): 42060,     
    ('Man United', 'Nottingham'): 73598,     
    ('Chelsea', 'Bournemouth'): 39865,       
    ('Leeds', 'Man City'): 36663,            
    
    # Week 29 - December 30-31, 2022
    ('West Ham', 'Brentford'): 62467,        
    ('Liverpool', 'Leicester'): 53245,       
    ('Wolves', 'Man United'): 31793,         
    ('Bournemouth', 'Crystal Palace'): 10268,  
    ('Fulham', 'Southampton'): 24205,        
    ('Man City', 'Everton'): 53397,          
    ('Newcastle', 'Leeds'): 52239,           
    ('Brighton', 'Arsenal'): 31648,          
    
    # Week 30 - January 1-5, 2023
    ('Nottingham', 'Chelsea'): 29253,        
    ('Tottenham', 'Aston Villa'): 61659,     
    ('Brentford', 'Liverpool'): 17242,       
    ('Arsenal', 'Newcastle'): 60264,         
    ('Everton', 'Brighton'): 39130,          
    ('Leicester', 'Fulham'): 30310,          
    ('Man United', 'Bournemouth'): 73365,    
    ('Southampton', 'Nottingham'): 29211,    
    ('Leeds', 'West Ham'): 36418,            
    ('Aston Villa', 'Wolves'): 41498,        
    ('Crystal Palace', 'Tottenham'): 25418,  
    ('Chelsea', 'Man City'): 40010,          
    
    # Week 31 - January 12-15, 2023
    ('Fulham', 'Chelsea'): 24120,            
    ('Aston Villa', 'Leeds'): 41899,         
    ('Man United', 'Man City'): 73552,       
    ('Brighton', 'Liverpool'): 31631,        
    ('Everton', 'Southampton'): 38936,       
    ('Nottingham', 'Leicester'): 29248,      
    ('Wolves', 'West Ham'): 31437,           
    ('Brentford', 'Bournemouth'): 17062,     
    ('Chelsea', 'Crystal Palace'): 40019,    
    ('Newcastle', 'Fulham'): 52232,          
    ('Tottenham', 'Arsenal'): 61840,         
    
    # Week 32 - January 18-23, 2023
    ('Crystal Palace', 'Man United'): 25220,  
    ('Man City', 'Tottenham'): 53228,        
    ('West Ham', 'Everton'): 62463,          
    ('Southampton', 'Aston Villa'): 30139,   
    ('Crystal Palace', 'Newcastle'): 25236,   
    ('Bournemouth', 'Nottingham'): 10316,    
    ('Liverpool', 'Chelsea'): 53292,         
    ('Leicester', 'Brighton'): 31605,        
    ('Arsenal', 'Man United'): 60325,        
    ('Leeds', 'Brentford'): 35842,           
    ('Man City', 'Wolves'): 53445,           
    ('Fulham', 'Tottenham'): 24104,          
    
    # Week 33 - February 3, 2023
    ('Chelsea', 'Fulham'): 40128,           
}

season_stats = {
    'Man City': {
        'SeasonPosAway': 1,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 28,
        'SeasonDrawAway': 5,
        'SeasonLossAway': 5,
        'SeasonGFAway': 94,
        'SeasonGAAway': 33,
        'SeasonGDAway': 61,
        'SeasonPointsAway': 89,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Arsenal': {
        'SeasonPosAway': 2,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 26,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 6,
        'SeasonGFAway': 88,
        'SeasonGAAway': 43,
        'SeasonGDAway': 45,
        'SeasonPointsAway': 84,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Man United': {
        'SeasonPosAway': 3,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 23,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 9,
        'SeasonGFAway': 58,
        'SeasonGAAway': 43,
        'SeasonGDAway': 15,
        'SeasonPointsAway': 75,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Newcastle': {
        'SeasonPosAway': 4,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 19,
        'SeasonDrawAway': 14,
        'SeasonLossAway': 5,
        'SeasonGFAway': 68,
        'SeasonGAAway': 33,
        'SeasonGDAway': 35,
        'SeasonPointsAway': 71,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Liverpool': {
        'SeasonPosAway': 5,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 19,
        'SeasonDrawAway': 10,
        'SeasonLossAway': 9,
        'SeasonGFAway': 75,
        'SeasonGAAway': 47,
        'SeasonGDAway': 28,
        'SeasonPointsAway': 67,
        'QualificationOrRelegationAway': 'Qualification for the Europa League group stage'
    },
    'Brighton': {
        'SeasonPosAway': 6,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 18,
        'SeasonDrawAway': 8,
        'SeasonLossAway': 12,
        'SeasonGFAway': 72,
        'SeasonGAAway': 53,
        'SeasonGDAway': 19,
        'SeasonPointsAway': 62,
        'QualificationOrRelegationAway': 'Qualification for the Europa League group stage'
    },
    'Aston Villa': {
        'SeasonPosAway': 7,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 18,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 13,
        'SeasonGFAway': 51,
        'SeasonGAAway': 46,
        'SeasonGDAway': 5,
        'SeasonPointsAway': 61,
        'QualificationOrRelegationAway': 'Qualification for the Europa Conference League play-off round[a]'
    },
    'Tottenham': {
        'SeasonPosAway': 8,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 18,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 14,
        'SeasonGFAway': 70,
        'SeasonGAAway': 63,
        'SeasonGDAway': 7,
        'SeasonPointsAway': 60,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Brentford': {
        'SeasonPosAway': 9,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 15,
        'SeasonDrawAway': 14,
        'SeasonLossAway': 9,
        'SeasonGFAway': 58,
        'SeasonGAAway': 46,
        'SeasonGDAway': 12,
        'SeasonPointsAway': 59,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Fulham': {
        'SeasonPosAway': 10,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 15,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 16,
        'SeasonGFAway': 55,
        'SeasonGAAway': 53,
        'SeasonGDAway': 2,
        'SeasonPointsAway': 52,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Crystal Palace': {
        'SeasonPosAway': 11,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 12,
        'SeasonLossAway': 15,
        'SeasonGFAway': 40,
        'SeasonGAAway': 49,
        'SeasonGDAway': -9,
        'SeasonPointsAway': 45,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Chelsea': {
        'SeasonPosAway': 12,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 11,
        'SeasonLossAway': 16,
        'SeasonGFAway': 38,
        'SeasonGAAway': 47,
        'SeasonGDAway': -9,
        'SeasonPointsAway': 44,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Wolves': {
        'SeasonPosAway': 13,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 8,
        'SeasonLossAway': 19,
        'SeasonGFAway': 31,
        'SeasonGAAway': 58,
        'SeasonGDAway': -27,
        'SeasonPointsAway': 41,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'West Ham': {
        'SeasonPosAway': 14,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 20,
        'SeasonGFAway': 42,
        'SeasonGAAway': 55,
        'SeasonGDAway': -13,
        'SeasonPointsAway': 40,
        'QualificationOrRelegationAway': 'Qualification for the Europa League group stage[b]'
    },
    'Bournemouth': {
        'SeasonPosAway': 15,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 21,
        'SeasonGFAway': 37,
        'SeasonGAAway': 71,
        'SeasonGDAway': -34,
        'SeasonPointsAway': 39,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Nottingham': {
        'SeasonPosAway': 16,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 9,
        'SeasonDrawAway': 11,
        'SeasonLossAway': 18,
        'SeasonGFAway': 38,
        'SeasonGAAway': 68,
        'SeasonGDAway': -30,
        'SeasonPointsAway': 38,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Everton': {
        'SeasonPosAway': 17,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 8,
        'SeasonDrawAway': 12,
        'SeasonLossAway': 18,
        'SeasonGFAway': 34,
        'SeasonGAAway': 57,
        'SeasonGDAway': -23,
        'SeasonPointsAway': 36,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Leicester': {
        'SeasonPosAway': 18,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 9,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 22,
        'SeasonGFAway': 51,
        'SeasonGAAway': 68,
        'SeasonGDAway': -17,
        'SeasonPointsAway': 34,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    },
    'Leeds': {
        'SeasonPosAway': 19,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 7,
        'SeasonDrawAway': 10,
        'SeasonLossAway': 21,
        'SeasonGFAway': 48,
        'SeasonGAAway': 78,
        'SeasonGDAway': -30,
        'SeasonPointsAway': 31,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    },
    'Southampton': {
        'SeasonPosAway': 20,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 6,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 25,
        'SeasonGFAway': 36,
        'SeasonGAAway': 73,
        'SeasonGDAway': -37,
        'SeasonPointsAway': 25,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    }
}

away_cols = [
    'SeasonPosAway', 'SeasonPlayedAway', 'SeasonWinAway', 'SeasonDrawAway',
    'SeasonLossAway', 'SeasonGFAway', 'SeasonGAAway', 'SeasonGDAway',
    'SeasonPointsAway', 'QualificationOrRelegationAway'
]

for idx, row in df[df['Season'] == '2223'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2223') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]
    
    if away in season_stats:
        for col in away_cols:
            df.loc[(df['Season'] == '2223') & (df.index == idx), col] = season_stats[away][col]

In [148]:
df[df['Season'] == '2223'].isna().sum()[df[df['Season'] == '2223'].isna().sum() > 0]

Attendance    180
dtype: int64

In [149]:
matches[200:300]

             HomeTeam        AwayTeam  Year  Month  Day
11384         Everton         Arsenal  2023      2    4
11385     Aston Villa       Leicester  2023      2    4
11386       Brentford     Southampton  2023      2    4
11387        Brighton     Bournemouth  2023      2    4
11388      Man United  Crystal Palace  2023      2    4
11389          Wolves       Liverpool  2023      2    4
11390       Newcastle        West Ham  2023      2    4
11391      Nottingham           Leeds  2023      2    5
11392       Tottenham        Man City  2023      2    5
11393      Man United           Leeds  2023      2    8
11394     Bournemouth       Newcastle  2023      2   11
11395     Southampton          Wolves  2023      2   11
11396       Leicester       Tottenham  2023      2   11
11397        West Ham         Chelsea  2023      2   11
11398  Crystal Palace        Brighton  2023      2   11
11399         Arsenal       Brentford  2023      2   11
11400          Fulham      Nottingham  2023      2   11
11401           Leeds      Man United  2023      2   12
11402        Man City     Aston Villa  2023      2   12
11403       Liverpool         Everton  2023      2   13
11404         Arsenal        Man City  2023      2   15
11405          Wolves     Bournemouth  2023      2   18
11406       Newcastle       Liverpool  2023      2   18
11407      Nottingham        Man City  2023      2   18
11408         Everton           Leeds  2023      2   18
11409        Brighton          Fulham  2023      2   18
11410       Brentford  Crystal Palace  2023      2   18
11411     Aston Villa         Arsenal  2023      2   18
11412         Chelsea     Southampton  2023      2   18
11413      Man United       Leicester  2023      2   19
11414       Tottenham        West Ham  2023      2   19
11415          Fulham          Wolves  2023      2   24
11416  Crystal Palace       Liverpool  2023      2   25
11417         Everton     Aston Villa  2023      2   25
11418           Leeds     Southampton  2023      2   25
11419       Leicester         Arsenal  2023      2   25
11420        West Ham      Nottingham  2023      2   25
11421     Bournemouth        Man City  2023      2   25
11422       Tottenham         Chelsea  2023      2   26
11423       Liverpool          Wolves  2023      3    1
11424         Arsenal         Everton  2023      3    1
11425        Man City       Newcastle  2023      3    4
11426         Arsenal     Bournemouth  2023      3    4
11427     Aston Villa  Crystal Palace  2023      3    4
11428        Brighton        West Ham  2023      3    4
11429         Chelsea           Leeds  2023      3    4
11430          Wolves       Tottenham  2023      3    4
11431     Southampton       Leicester  2023      3    4
11432      Nottingham         Everton  2023      3    5
11433       Liverpool      Man United  2023      3    5
11434       Brentford          Fulham  2023      3    6
11435       Tottenham      Nottingham  2023      3   11
11436  Crystal Palace        Man City  2023      3   11
11437       Leicester         Chelsea  2023      3   11
11438     Bournemouth       Liverpool  2023      3   11
11439         Everton       Brentford  2023      3   11
11440           Leeds        Brighton  2023      3   11
11441          Fulham         Arsenal  2023      3   12
11442      Man United     Southampton  2023      3   12
11443        West Ham     Aston Villa  2023      3   12
11444       Newcastle          Wolves  2023      3   12
11445        Brighton  Crystal Palace  2023      3   15
11446     Southampton       Brentford  2023      3   15
11447      Nottingham       Newcastle  2023      3   17
11448          Wolves           Leeds  2023      3   18
11449     Southampton       Tottenham  2023      3   18
11450         Chelsea         Everton  2023      3   18
11451     Aston Villa     Bournemouth  2023      3   18
11452       Brentford       Leicester  2023      3   18
11453         Arsenal  Crystal Palace  2023      3   19
11454        Man City       Liverpool  2023      4    1
11455         Arsenal           Leeds  2023      4    1
11456     Bournemouth          Fulham  2023      4    1
11457        Brighton       Brentford  2023      4    1
11458  Crystal Palace       Leicester  2023      4    1
11459      Nottingham          Wolves  2023      4    1
11460         Chelsea     Aston Villa  2023      4    1
11461        West Ham     Southampton  2023      4    2
11462       Newcastle      Man United  2023      4    2
11463         Everton       Tottenham  2023      4    3
11464         Chelsea       Liverpool  2023      4    4
11465       Leicester     Aston Villa  2023      4    4
11466     Bournemouth        Brighton  2023      4    4
11467           Leeds      Nottingham  2023      4    4
11468      Man United       Brentford  2023      4    5
11469        West Ham       Newcastle  2023      4    5
11470          Wolves         Chelsea  2023      4    8
11471      Man United         Everton  2023      4    8
11472     Aston Villa      Nottingham  2023      4    8
11473       Brentford       Newcastle  2023      4    8
11474          Fulham        West Ham  2023      4    8
11475       Leicester     Bournemouth  2023      4    8
11476       Tottenham        Brighton  2023      4    8
11477     Southampton        Man City  2023      4    8
11478       Liverpool         Arsenal  2023      4    9
11479           Leeds  Crystal Palace  2023      4    9
11480     Aston Villa       Newcastle  2023      4   15
11481         Chelsea        Brighton  2023      4   15
11482         Everton          Fulham  2023      4   15
11483     Southampton  Crystal Palace  2023      4   15

In [ ]:
attendance_data.update({
    # Saturday, February 4, 2023
    ('Everton', 'Arsenal'): 39314,          # FBref
    ('Aston Villa', 'Leicester'): 42055,    # FBref
    ('Wolves', 'Liverpool'): 31664,         # FBref  
    ('Man United', 'Crystal Palace'): 73420, # FBref  
    ('Brighton', 'Bournemouth'): 31600,     # FBref  
    ('Brentford', 'Southampton'): 17051,    # FBref  
    ('Newcastle', 'West Ham'): 52256,       # FBref  

    # Sunday, February 5, 2023
    ('Nottingham', 'Leeds'): 29363,         # FBref  
    ('Tottenham', 'Man City'): 61747,       # FBref  

    # Wednesday, February 8, 2023
    ('Man United', 'Leeds'): 73456,         # FBref  

    # Saturday, February 11, 2023
    ('West Ham', 'Chelsea'): 62471,         # FBref  
    ('Leicester', 'Tottenham'): 32184,      # FBref  
    ('Crystal Palace', 'Brighton'): 24827,  # FBref  
    ('Arsenal', 'Brentford'): 60254,        # FBref  
    ('Southampton', 'Wolves'): 29751,       # FBref  
    ('Fulham', 'Nottingham'): 24244,        # FBref  
    ('Bournemouth', 'Newcastle'): 10419,    # FBref

    # Sunday, February 12, 2023
    ('Leeds', 'Man United'): 36568,         # FBref  
    # Sunday, February 12, 2023
    ('Man City', 'Aston Villa'): 53214,     # FBref  

    # Monday, February 13, 2023
    ('Liverpool', 'Everton'): 53258,        # FBref  

    # Wednesday, February 15, 2023
    ('Arsenal', 'Man City'): 60036,         # FBref  

    # Saturday, February 18, 2023
    ('Wolves', 'Bournemouth'): 31688,       # FBref  
    ('Newcastle', 'Liverpool'): 52255,      # FBref  
    ('Nottingham', 'Man City'): 29458,      # FBref  
    ('Everton', 'Leeds'): 39024,            # FBref  
    ('Brighton', 'Fulham'): 31632,          # FBref  
    ('Brentford', 'Crystal Palace'): 17072, # FBref  
    ('Aston Villa', 'Arsenal'): 41881,      # FBref  
    ('Chelsea', 'Southampton'): 40155,      # FBref  

    # Sunday, February 19, 2023
    ('Man United', 'Leicester'): 73224,     # FBref  
    ('Tottenham', 'West Ham'): 61520,       # FBref  

    # Friday, February 24, 2023
    ('Fulham', 'Wolves'): 24223,            # FBref  

    # Saturday, February 25, 2023
    ('Crystal Palace', 'Liverpool'): 25435, # FBref  
    ('Everton', 'Aston Villa'): 39249,      # FBref  
    ('Leeds', 'Southampton'): 36590,        # FBref  
    ('Leicester', 'Arsenal'): 32111,        # FBref  
    ('West Ham', 'Nottingham'): 62461,      # FBref  
    ('Bournemouth', 'Man City'): 10200,     # FBref  

    # Sunday, February 26, 2023
    ('Tottenham', 'Chelsea'): 61705,        # FBref  

    # Wednesday, March 1, 2023
    ('Liverpool', 'Wolves'): 52977,         # FBref  
    ('Arsenal', 'Everton'): 60231,          # FBref  

    # Saturday, March 4, 2023
    ('Man City', 'Newcastle'): 53434,       # FBref  
    ('Arsenal', 'Bournemouth'): 60233,      # FBref  
    ('Aston Villa', 'Crystal Palace'): 41851, # FBref  
    ('Brighton', 'West Ham'): 31618,        # FBref  
    ('Chelsea', 'Leeds'): 39860,            # FBref  
    ('Wolves', 'Tottenham'): 31511,         # FBref  
    ('Southampton', 'Leicester'): 30223,    # FBref  

    # Sunday, March 5, 2023
    ('Nottingham', 'Everton'): 29300,       # FBref  
    ('Liverpool', 'Man United'): 53078,     # FBref  

    # Monday, March 6, 2023
    ('Brentford', 'Fulham'): 17082,         # FBref  

    # Saturday, March 11, 2023
    ('Tottenham', 'Nottingham'): 61240,     # FBref  
    ('Crystal Palace', 'Man City'): 25349,  # FBref  
    ('Leicester', 'Chelsea'): 32181,        # FBref  
    ('Bournemouth', 'Liverpool'): 10435,    # FBref  
    ('Everton', 'Brentford'): 39176,        # FBref  
    ('Leeds', 'Brighton'): 36182,           # FBref  

    # Sunday, March 12, 2023
    ('Fulham', 'Arsenal'): 24445,           # FBref  
    ('Man United', 'Southampton'): 73241,   # FBref  
    ('West Ham', 'Aston Villa'): 62477,     # FBref  
    ('Newcastle', 'Wolves'): 52230,         # FBref  

    # Wednesday, March 15, 2023
    ('Brighton', 'Crystal Palace'): 31661,  # FBref  
    ('Southampton', 'Brentford'): 28688,    # FBref  

    # Friday, March 17, 2023
    ('Nottingham', 'Newcastle'): 29390,       # FBref  

    # Saturday, March 18, 2023
    ('Wolves', 'Leeds'): 31445,              # FBref  ]
    ('Southampton', 'Tottenham'): 30397,     # FBref  ]
    ('Chelsea', 'Everton'): 40083,           # FBref  ]
    ('Aston Villa', 'Bournemouth'): 41732,   # FBref  ]
    ('Brentford', 'Leicester'): 17119,       # FBref  ]

    # Sunday, March 19, 2023
    ('Arsenal', 'Crystal Palace'): 60213,    # FBref  ]

    # Saturday, April 1, 2023
    ('Man City', 'Liverpool'): 53540,        # FBref  ]
    ('Arsenal', 'Leeds'): 60246,             # FBref  ]
    ('Bournemouth', 'Fulham'): 10388,        # FBref  ]
    ('Brighton', 'Brentford'): 31651,        # FBref  ]
    ('Crystal Palace', 'Leicester'): 25388,  # FBref  ]
    ('Nottingham', 'Wolves'): 29263,         # FBref  ]
    ('Chelsea', 'Aston Villa'): 40120,       # FBref  ]

    # Sunday, April 2, 2023
    ('West Ham', 'Southampton'): 62476,      # FBref  ]
    ('Newcastle', 'Man United'): 52271,      # FBref  ]

    # Monday, April 3, 2023
    ('Everton', 'Tottenham'): 39227,         # FBref  ]

    # Tuesday, April 4, 2023
    ('Chelsea', 'Liverpool'): 40025,         # FBref  ]
    ('Leicester', 'Aston Villa'): 31788,     # FBref  ]
    ('Bournemouth', 'Brighton'): 10480,      # FBref  ]
    ('Leeds', 'Nottingham'): 36531,          # FBref  ]

    # Wednesday, April 5, 2023
    ('Man United', 'Brentford'): 73275,      # FBref  ]
    ('West Ham', 'Newcastle'): 62471,        # FBref  ]

    # Saturday, April 8, 2023
    ('Wolves', 'Chelsea'): 31347,            # FBref  ]
    ('Man United', 'Everton'): 73509,        # FBref  ]
    ('Aston Villa', 'Nottingham'): 41800,    # FBref  ]
    ('Brentford', 'Newcastle'): 17233,       # FBref  ]
    ('Fulham', 'West Ham'): 24450,           # FBref  ]
    ('Leicester', 'Bournemouth'): 31881,     # FBref  ]
    ('Tottenham', 'Brighton'): 61573,        # FBref  ]
    ('Southampton', 'Man City'): 30270,      # FBref  ]

    # Sunday, April 9, 2023
    ('Liverpool', 'Arsenal'): 53185,         # FBref  ]
    ('Leeds', 'Crystal Palace'): 36607,      # FBref  ]

    # Saturday, April 15, 2023
    ('Aston Villa', 'Newcastle'): 41851,     # FBref  ]
    ('Chelsea', 'Brighton'): 40181,          # FBref  ]
    ('Everton', 'Fulham'): 39250,            # FBref  
    ('Southampton', 'Crystal Palace'): 28861,  # FBref  
    ('Tottenham', 'Bournemouth'): 61570,     # FBref  
    ('Wolves', 'Brentford'): 31411,          # FBref 
    ('Man City', 'Leicester'): 53405,        # FBref  
})

for idx, row in df[df['Season'] == '2223'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2223') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [152]:
df[df['Season'] == '2223'].isna().sum()[df[df['Season'] == '2223'].isna().sum() > 0]

Attendance    77
dtype: int64

In [154]:
df[(df['Season'] == '2223') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

             HomeTeam        AwayTeam  Year  Month  Day
11487      Nottingham      Man United  2023      4   16
11488        West Ham         Arsenal  2023      4   16
11489           Leeds       Liverpool  2023      4   17
11490         Arsenal     Southampton  2023      4   21
11491          Fulham           Leeds  2023      4   22
11492       Brentford     Aston Villa  2023      4   22
11493  Crystal Palace         Everton  2023      4   22
11494       Leicester          Wolves  2023      4   22
11495       Liverpool      Nottingham  2023      4   22
11496     Bournemouth        West Ham  2023      4   23
11497       Newcastle       Tottenham  2023      4   23
11498          Wolves  Crystal Palace  2023      4   25
11499     Aston Villa          Fulham  2023      4   25
11500           Leeds       Leicester  2023      4   25
11501        Man City         Arsenal  2023      4   26
11502        West Ham       Liverpool  2023      4   26
11503      Nottingham        Brighton  2023      4   26
11504         Chelsea       Brentford  2023      4   26
11505         Everton       Newcastle  2023      4   27
11506     Southampton     Bournemouth  2023      4   27
11507       Tottenham      Man United  2023      4   27
11508  Crystal Palace        West Ham  2023      4   29
11509       Brentford      Nottingham  2023      4   29
11510        Brighton          Wolves  2023      4   29
11511       Liverpool       Tottenham  2023      4   30
11512     Bournemouth           Leeds  2023      4   30
11513          Fulham        Man City  2023      4   30
11514      Man United     Aston Villa  2023      4   30
11515       Newcastle     Southampton  2023      4   30
11516       Leicester         Everton  2023      5    1
11517         Arsenal         Chelsea  2023      5    2
11518       Liverpool          Fulham  2023      5    3
11519        Man City        West Ham  2023      5    3
11520        Brighton      Man United  2023      5    4
11521     Bournemouth         Chelsea  2023      5    6
11522        Man City           Leeds  2023      5    6
11523       Tottenham  Crystal Palace  2023      5    6
11524          Wolves     Aston Villa  2023      5    6
11525       Liverpool       Brentford  2023      5    6
11526       Newcastle         Arsenal  2023      5    7
11527        West Ham      Man United  2023      5    7
11528        Brighton         Everton  2023      5    8
11529      Nottingham     Southampton  2023      5    8
11530          Fulham       Leicester  2023      5    8
11531           Leeds       Newcastle  2023      5   13
11532     Aston Villa       Tottenham  2023      5   13
11533         Chelsea      Nottingham  2023      5   13
11534  Crystal Palace     Bournemouth  2023      5   13
11535      Man United          Wolves  2023      5   13
11536     Southampton          Fulham  2023      5   13
11537       Brentford        West Ham  2023      5   14
11538         Everton        Man City  2023      5   14
11539         Arsenal        Brighton  2023      5   14
11540       Leicester       Liverpool  2023      5   15
11541       Newcastle        Brighton  2023      5   18
11542      Nottingham         Arsenal  2023      5   20
11543          Wolves         Everton  2023      5   20
11544       Liverpool     Aston Villa  2023      5   20
11545          Fulham  Crystal Palace  2023      5   20
11546     Bournemouth      Man United  2023      5   20
11547       Tottenham       Brentford  2023      5   20
11548        West Ham           Leeds  2023      5   21
11549        Brighton     Southampton  2023      5   21
11550        Man City         Chelsea  2023      5   21
11551       Newcastle       Leicester  2023      5   22
11552        Brighton        Man City  2023      5   24
11553      Man United         Chelsea  2023      5   25
11554     Southampton       Liverpool  2023      5   28
11555      Man United          Fulham  2023      5   28
11556       Leicester        West Ham  2023      5   28
11557           Leeds       Tottenham  2023      5   28
11558         Everton     Bournemouth  2023      5   28
11559         Chelsea       Newcastle  2023      5   28
11560       Brentford        Man City  2023      5   28
11561     Aston Villa        Brighton  2023      5   28
11562         Arsenal          Wolves  2023      5   28
11563  Crystal Palace      Nottingham  2023      5   28

In [ ]:
# Attendance data for the remaining matches
# Sourced from official match reports on ESPN, Sky Sports, 11v11, and FBref
attendance_data.update({
    # Sunday 16 April 2023
    ('Nottingham', 'Man United'): 29435,      # FBref   0]
    ('West Ham', 'Arsenal'): 62475,           # ESPN   1], FBref   2]
    # Monday 17 April 2023
    ('Leeds', 'Liverpool'): 36657,            # ESPN   3], 11v11   4]
    # Friday 21 April 2023
    ('Arsenal', 'Southampton'): 60175,        # worldfootball   5], Sky Sports   6]
    # Saturday 22 April 2023
    ('Fulham', 'Leeds'): 24356,               # ESPN   7], FBref   8]
    ('Brentford', 'Aston Villa'): 17098,      # ESPN   9], 11v11   10]
    ('Crystal Palace', 'Everton'): 25202,     # Transfermarkt   11], FBref   12]
    ('Leicester', 'Wolves'): 32053,           # ESPN   13], 11v11   14]
    ('Liverpool', 'Nottingham'): 53325,       # 11v11   15], LFChistory   16]
    # Sunday 23 April 2023
    ('Bournemouth', 'West Ham'): 10465,       # ESPN   17], 11v11   18]
    ('Newcastle', 'Tottenham'): 52252,        # ESPN   19], 11v11   20]
    # Tuesday 25 April 2023
    ('Wolves', 'Crystal Palace'): 30792,      # ESPN   21], 11v11   22]
    ('Aston Villa', 'Fulham'): 41046,         # ESPN   23], FBref   24]
    ('Leeds', 'Leicester'): 36666,            # ESPN   25], FBref   26]
    # Wednesday 26 April 2023
    ('Man City', 'Arsenal'): 53482,           # StatCity   27]
    ('West Ham', 'Liverpool'): 62473,         # ESPN   28], FBref   29]
    ('Nottingham', 'Brighton'): 28808,        # ESPN   30], 11v11   31]
    ('Chelsea', 'Brentford'): 39929,          # ESPN   32], FBref   33]
    # Thursday 27 April 2023
    ('Everton', 'Newcastle'): 39248,          # ESPN   34], 11v11   35]
    ('Southampton', 'Bournemouth'): 30414,    # ESPN   36], Le Figaro   37]
    ('Tottenham', 'Man United'): 61586,       # ESPN   38], THFCDB   39]
    # Saturday 29 April 2023
    ('Crystal Palace', 'West Ham'): 25148,    # ESPN   40], 11v11   41]
    ('Brentford', 'Nottingham'): 17080,       # Scoresway   42], FBref   43]
    ('Brighton', 'Wolves'): 31584,            # ESPN   44], FBref   45]
    # Sunday 30 April 2023
    ('Liverpool', 'Tottenham'): 53275,        # ESPN   46], 11v11   47]
    ('Bournemouth', 'Leeds'): 10434,          # worldfootball   48], FBref   49]
    ('Fulham', 'Man City'): 24498,            # ESPN   50], Wikipedia   51]
    ('Man United', 'Aston Villa'): 73592,     # ESPN   52], FBref   53]
    ('Newcastle', 'Southampton'): 52234,      # ESPN   54], 11v11   55]
    # Monday 1 May 2023
    ('Leicester', 'Everton'): 32173,          # Transfermarkt   56], FBref   57]
    # Tuesday 2 May 2023
    ('Arsenal', 'Chelsea'): 60144,            # ESPN   58], FBref   59]
    # Wednesday 3 May 2023
    ('Liverpool', 'Fulham'): 52602,           # ESPN   60], FBref   61]
    ('Man City', 'West Ham'): 53305,          # ESPN   62], FBref   63]
    # Thursday 4 May 2023
    ('Brighton', 'Man United'): 31577,        # ESPN   64], Premier League   65]
    # Saturday 6 May 2023
    ('Bournemouth', 'Chelsea'): 10357,        # footballwebpages   66], 11v11   67]
    ('Man City', 'Leeds'): 53406,             # Transfermarkt   68]
    ('Tottenham', 'Crystal Palace'): 61093,   # ESPN   69], FBref   70]
    ('Wolves', 'Aston Villa'): 31641,         # ESPN   71], FBref   72]
    ('Liverpool', 'Brentford'): 52838,        # ESPN   73], FBref   74]
    # Sunday 7 May 2023
    ('Newcastle', 'Arsenal'): 50267,          # ESPN   75], FBref   76]
    ('West Ham', 'Man United'): 62477,        # ESPN   77], Wikipedia   78]
    # Monday 8 May 2023
    ('Brighton', 'Everton'): 31567,           # ESPN   79], 11v11   80]
    ('Nottingham', 'Southampton'): 29154,     # 11v11   81]
    ('Fulham', 'Leicester'): 24442,           # Transfermarkt   82], Fulham Wiki   83]
    # Saturday 13 May 2023
    ('Leeds', 'Newcastle'): 36955,            # Scoresway   84], ESPN   85]
    ('Aston Villa', 'Tottenham'): 42164,      # Opta   86], FBref   87]
    ('Chelsea', 'Nottingham'): 40030,         # ESPN   88], 11v11   89]
    ('Crystal Palace', 'Bournemouth'): 25034, # ESPN   90], 11v11   91]
    ('Man United', 'Wolves'): 73570,          # ESPN   92], FBref   93]
    ('Southampton', 'Fulham'): 28978,         # ESPN   94], Wikipedia   95]
    # Sunday 14 May 2023
    ('Brentford', 'West Ham'): 17075,         # ESPN   96], 11v11   97]
    ('Everton', 'Man City'): 39376,           # ESPN   98], FBref   99]
    ('Arsenal', 'Brighton'): 60139,           # ESPN   100], worldfootball   101]
    # Monday 15 May 2023
    ('Leicester', 'Liverpool'): 32225,        # ESPN   102], Transfermarkt   103]
    # Thursday 18 May 2023
    ('Newcastle', 'Brighton'): 52122,         # ESPN   104], Sportschau   105]
    # Saturday 20 May 2023
    ('Nottingham', 'Arsenal'): 29514,         # ESPN   106], Wikipedia   107]
    ('Wolves', 'Everton'): 31684,             # El Pais   108], FBref   109]
    ('Liverpool', 'Aston Villa'): 53306,      # ESPN   110], 11v11   111]
})

for idx, row in df[df['Season'] == '2223'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2223') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [156]:
df[df['Season'] == '2223'].isna().sum()[df[df['Season'] == '2223'].isna().sum() > 0]

Attendance    19
dtype: int64

In [157]:
df[(df['Season'] == '2223') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

             HomeTeam        AwayTeam  Year  Month  Day
11545          Fulham  Crystal Palace  2023      5   20
11546     Bournemouth      Man United  2023      5   20
11547       Tottenham       Brentford  2023      5   20
11548        West Ham           Leeds  2023      5   21
11549        Brighton     Southampton  2023      5   21
11550        Man City         Chelsea  2023      5   21
11551       Newcastle       Leicester  2023      5   22
11552        Brighton        Man City  2023      5   24
11553      Man United         Chelsea  2023      5   25
11554     Southampton       Liverpool  2023      5   28
11555      Man United          Fulham  2023      5   28
11556       Leicester        West Ham  2023      5   28
11557           Leeds       Tottenham  2023      5   28
11558         Everton     Bournemouth  2023      5   28
11559         Chelsea       Newcastle  2023      5   28
11560       Brentford        Man City  2023      5   28
11561     Aston Villa        Brighton  2023      5   28
11562         Arsenal          Wolves  2023      5   28
11563  Crystal Palace      Nottingham  2023      5   28

In [ ]:
attendance_data.update({
    # Saturday 20 May 2023
    ('Fulham', 'Crystal Palace'): 24356,      # ESPN  0], 11v11  1]
    ('Bournemouth', 'Man United'): 10240,     # worldfootball  2], 11v11  3]
    ('Tottenham', 'Brentford'): 61514,        # ESPN  4], Sky Sports  5]

    # Sunday 21 May 2023
    ('West Ham', 'Leeds'): 62478,             # ESPN  6], Sky Sports  7]
    ('Brighton', 'Southampton'): 31507,       # ESPN  8], Sky Sports  9]
    ('Man City', 'Chelsea'): 53490,           # 11v11  10], Sky Sports  11]

    # Monday 22 May 2023
    ('Newcastle', 'Leicester'): 52152,         # Sky Sports  12], 11v11  13]

    # Wednesday 24 May 2023
    ('Brighton', 'Man City'): 31388,           # ESPN  14], Sky Sports  15]

    # Thursday 25 May 2023
    ('Man United', 'Chelsea'): 73561,          # The Score  16], ESPN  17]

    # Sunday 28 May 2023
    ('Southampton', 'Liverpool'): 31129,       # Sky Sports  18], ESPN  19]
    ('Man United', 'Fulham'): 73465,           # ESPN  20], 11v11  21]
    ('Leicester', 'West Ham'): 32183,          # ESPN  22], 11v11  23]
    ('Leeds', 'Tottenham'): 36871,             # Sky Sports  24], 11v11  25]
    ('Everton', 'Bournemouth'): 39201,         # ESPN  26], 11v11  27]
    ('Chelsea', 'Newcastle'): 40130,           # ESPN  28], Sky Sports  29]
    ('Brentford', 'Man City'): 17120,          # ESPN  30], 11v11  31]
    ('Aston Villa', 'Brighton'): 42212,        # ESPN  32], Wikipedia  33]
    ('Arsenal', 'Wolves'): 60095,              # ESPN  34], Sky Sports  35]
    ('Crystal Palace', 'Nottingham'): 25037,   # Confirmed via search
})

for idx, row in df[df['Season'] == '2223'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2223') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [159]:
df[df['Season'] == '2223'].isna().sum()[df[df['Season'] == '2223'].isna().sum() > 0]

Series([], dtype: int64)

In [160]:
df.to_csv("Data/Data4.csv", index=False)

---

In [161]:
df[df['Season'] == '2526'].isna().sum()[df[df['Season'] == '2526'].isna().sum() > 0]

WeekDay                           22
Time                              22
Round                             22
Attendance                        22
XGHome                            22
XGAway                            22
SeasonPosAway                    380
SeasonPlayedAway                 380
SeasonWinAway                    380
SeasonDrawAway                   380
SeasonLossAway                   380
SeasonGFAway                     380
SeasonGAAway                     380
SeasonGDAway                     380
SeasonPointsAway                 380
QualificationOrRelegationAway    380
dtype: int64

In [163]:
df[(df['Season'] == '2526') & (df['SeasonPosAway'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']][:100]

             HomeTeam        AwayTeam  Year  Month  Day
12324       Liverpool     Bournemouth  2025      8   15
12325       Tottenham         Burnley  2025      8   16
12326          Wolves        Man City  2025      8   16
12327        Brighton          Fulham  2025      8   16
12328     Aston Villa       Newcastle  2025      8   16
12329      Sunderland        West Ham  2025      8   16
12330         Chelsea  Crystal Palace  2025      8   17
12331      Nottingham       Brentford  2025      8   17
12332      Man United         Arsenal  2025      8   17
12333           Leeds         Everton  2025      8   18
12334        West Ham         Chelsea  2025      8   22
12335         Burnley      Sunderland  2025      8   23
12336         Arsenal           Leeds  2025      8   23
12337     Bournemouth          Wolves  2025      8   23
12338        Man City       Tottenham  2025      8   23
12339       Brentford     Aston Villa  2025      8   23
12340  Crystal Palace      Nottingham  2025      8   24
12341         Everton        Brighton  2025      8   24
12342          Fulham      Man United  2025      8   24
12343       Newcastle       Liverpool  2025      8   25
12344         Chelsea          Fulham  2025      8   30
12345      Man United         Burnley  2025      8   30
12346      Sunderland       Brentford  2025      8   30
12347       Tottenham     Bournemouth  2025      8   30
12348          Wolves         Everton  2025      8   30
12349           Leeds       Newcastle  2025      8   30
12350        Brighton        Man City  2025      8   31
12351       Liverpool         Arsenal  2025      8   31
12352     Aston Villa  Crystal Palace  2025      8   31
12353      Nottingham        West Ham  2025      8   31
12354         Arsenal      Nottingham  2025      9   13
12355     Bournemouth        Brighton  2025      9   13
12356  Crystal Palace      Sunderland  2025      9   13
12357         Everton     Aston Villa  2025      9   13
12358          Fulham           Leeds  2025      9   13
12359       Newcastle          Wolves  2025      9   13
12360        West Ham       Tottenham  2025      9   13
12361       Brentford         Chelsea  2025      9   13
12362         Burnley       Liverpool  2025      9   14
12363        Man City      Man United  2025      9   14
12364       Liverpool         Everton  2025      9   20
12365        Brighton       Tottenham  2025      9   20
12366         Burnley      Nottingham  2025      9   20
12367        West Ham  Crystal Palace  2025      9   20
12368          Wolves           Leeds  2025      9   20
12369      Man United         Chelsea  2025      9   20
12370          Fulham       Brentford  2025      9   20
12371         Arsenal        Man City  2025      9   21
12372     Bournemouth       Newcastle  2025      9   21
12373      Sunderland     Aston Villa  2025      9   21
12374       Brentford      Man United  2025      9   27
12375         Chelsea        Brighton  2025      9   27
12376  Crystal Palace       Liverpool  2025      9   27
12377           Leeds     Bournemouth  2025      9   27
12378        Man City         Burnley  2025      9   27
12379      Nottingham      Sunderland  2025      9   27
12380       Tottenham          Wolves  2025      9   27
12381       Newcastle         Arsenal  2025      9   28
12382     Aston Villa          Fulham  2025      9   28
12383         Everton        West Ham  2025      9   29
12384     Bournemouth          Fulham  2025     10    3
12385           Leeds       Tottenham  2025     10    4
12386         Arsenal        West Ham  2025     10    4
12387      Man United      Sunderland  2025     10    4
12388         Chelsea       Liverpool  2025     10    4
12389          Wolves        Brighton  2025     10    5
12390       Brentford        Man City  2025     10    5
12391         Everton  Crystal Palace  2025     10    5
12392     Aston Villa         Burnley  2025     10    5
12393       Newcastle      Nottingham  2025     10    5
12394      Nottingham         Chelsea  2025     10   18
12395        Brighton       Newcastle  2025     10   18
12396         Burnley           Leeds  2025     10   18
12397  Crystal Palace     Bournemouth  2025     10   18
12398        Man City         Everton  2025     10   18
12399      Sunderland          Wolves  2025     10   18
12400          Fulham         Arsenal  2025     10   18
12401       Tottenham     Aston Villa  2025     10   19
12402       Liverpool      Man United  2025     10   19
12403        West Ham       Brentford  2025     10   20
12404           Leeds        West Ham  2025     10   24
12405         Chelsea      Sunderland  2025     10   25
12406       Newcastle          Fulham  2025     10   25
12407      Man United        Brighton  2025     10   25
12408       Brentford       Liverpool  2025     10   25
12409          Wolves         Burnley  2025     10   26
12410         Everton       Tottenham  2025     10   26
12411     Aston Villa        Man City  2025     10   26
12412         Arsenal  Crystal Palace  2025     10   26
12413     Bournemouth      Nottingham  2025     10   26
12414        Brighton           Leeds  2025     11    1
12415         Burnley         Arsenal  2025     11    1
12416  Crystal Palace       Brentford  2025     11    1
12417          Fulham          Wolves  2025     11    1
12418      Nottingham      Man United  2025     11    1
12419       Tottenham         Chelsea  2025     11    1
12420       Liverpool     Aston Villa  2025     11    1
12421        West Ham       Newcastle  2025     11    2
12422        Man City     Bournemouth  2025     11    2
12423      Sunderland         Everton  2025     11    3

In [165]:
season_stats_2025 = {
    'Arsenal': {
        'SeasonPosAway': 1, 'SeasonPlayedAway': 38, 'SeasonWinAway': 26,
        'SeasonDrawAway': 7, 'SeasonLossAway': 5, 'SeasonGFAway': 71,
        'SeasonGAAway': 27, 'SeasonGDAway': 44, 'SeasonPointsAway': 85,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Man City': {
        'SeasonPosAway': 2, 'SeasonPlayedAway': 38, 'SeasonWinAway': 23,
        'SeasonDrawAway': 9, 'SeasonLossAway': 6, 'SeasonGFAway': 77,
        'SeasonGAAway': 35, 'SeasonGDAway': 42, 'SeasonPointsAway': 78,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Man United': {
        'SeasonPosAway': 3, 'SeasonPlayedAway': 38, 'SeasonWinAway': 20,
        'SeasonDrawAway': 11, 'SeasonLossAway': 7, 'SeasonGFAway': 69,
        'SeasonGAAway': 50, 'SeasonGDAway': 19, 'SeasonPointsAway': 71,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Aston Villa': {
        'SeasonPosAway': 4, 'SeasonPlayedAway': 38, 'SeasonWinAway': 19,
        'SeasonDrawAway': 8, 'SeasonLossAway': 11, 'SeasonGFAway': 56,
        'SeasonGAAway': 49, 'SeasonGDAway': 7, 'SeasonPointsAway': 65,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Liverpool': {
        'SeasonPosAway': 5, 'SeasonPlayedAway': 38, 'SeasonWinAway': 17,
        'SeasonDrawAway': 9, 'SeasonLossAway': 12, 'SeasonGFAway': 63,
        'SeasonGAAway': 53, 'SeasonGDAway': 10, 'SeasonPointsAway': 60,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Bournemouth': {
        'SeasonPosAway': 6, 'SeasonPlayedAway': 38, 'SeasonWinAway': 13,
        'SeasonDrawAway': 18, 'SeasonLossAway': 7, 'SeasonGFAway': 58,
        'SeasonGAAway': 54, 'SeasonGDAway': 4, 'SeasonPointsAway': 57,
        'QualificationOrRelegationAway': 'Qualification for the Europa League group stage'
    },
    'Sunderland': {
        'SeasonPosAway': 7, 'SeasonPlayedAway': 38, 'SeasonWinAway': 14,
        'SeasonDrawAway': 12, 'SeasonLossAway': 12, 'SeasonGFAway': 42,
        'SeasonGAAway': 48, 'SeasonGDAway': -6, 'SeasonPointsAway': 54,
        'QualificationOrRelegationAway': 'Qualification for the Europa League group stage'
    },
    'Brighton': {
        'SeasonPosAway': 8, 'SeasonPlayedAway': 38, 'SeasonWinAway': 14,
        'SeasonDrawAway': 11, 'SeasonLossAway': 13, 'SeasonGFAway': 52,
        'SeasonGAAway': 46, 'SeasonGDAway': 6, 'SeasonPointsAway': 53,
        'QualificationOrRelegationAway': 'Qualification for the Europa Conference League play-off round'
    },
    'Brentford': {
        'SeasonPosAway': 9, 'SeasonPlayedAway': 38, 'SeasonWinAway': 14,
        'SeasonDrawAway': 11, 'SeasonLossAway': 13, 'SeasonGFAway': 55,
        'SeasonGAAway': 52, 'SeasonGDAway': 3, 'SeasonPointsAway': 53,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Chelsea': {
        'SeasonPosAway': 10, 'SeasonPlayedAway': 38, 'SeasonWinAway': 14,
        'SeasonDrawAway': 10, 'SeasonLossAway': 14, 'SeasonGFAway': 58,
        'SeasonGAAway': 52, 'SeasonGDAway': 6, 'SeasonPointsAway': 52,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Fulham': {
        'SeasonPosAway': 11, 'SeasonPlayedAway': 38, 'SeasonWinAway': 15,
        'SeasonDrawAway': 7, 'SeasonLossAway': 16, 'SeasonGFAway': 47,
        'SeasonGAAway': 51, 'SeasonGDAway': -4, 'SeasonPointsAway': 52,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Newcastle': {
        'SeasonPosAway': 12, 'SeasonPlayedAway': 38, 'SeasonWinAway': 14,
        'SeasonDrawAway': 7, 'SeasonLossAway': 17, 'SeasonGFAway': 53,
        'SeasonGAAway': 55, 'SeasonGDAway': -2, 'SeasonPointsAway': 49,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Everton': {
        'SeasonPosAway': 13, 'SeasonPlayedAway': 38, 'SeasonWinAway': 13,
        'SeasonDrawAway': 10, 'SeasonLossAway': 15, 'SeasonGFAway': 47,
        'SeasonGAAway': 50, 'SeasonGDAway': -3, 'SeasonPointsAway': 49,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Leeds': {
        'SeasonPosAway': 14, 'SeasonPlayedAway': 38, 'SeasonWinAway': 11,
        'SeasonDrawAway': 14, 'SeasonLossAway': 13, 'SeasonGFAway': 49,
        'SeasonGAAway': 56, 'SeasonGDAway': -7, 'SeasonPointsAway': 47,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Crystal Palace': {
        'SeasonPosAway': 15, 'SeasonPlayedAway': 38, 'SeasonWinAway': 11,
        'SeasonDrawAway': 12, 'SeasonLossAway': 15, 'SeasonGFAway': 41,
        'SeasonGAAway': 51, 'SeasonGDAway': -10, 'SeasonPointsAway': 45,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Nottingham': {
        'SeasonPosAway': 16, 'SeasonPlayedAway': 38, 'SeasonWinAway': 11,
        'SeasonDrawAway': 11, 'SeasonLossAway': 16, 'SeasonGFAway': 48,
        'SeasonGAAway': 51, 'SeasonGDAway': -3, 'SeasonPointsAway': 44,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Tottenham': {
        'SeasonPosAway': 17, 'SeasonPlayedAway': 38, 'SeasonWinAway': 10,
        'SeasonDrawAway': 11, 'SeasonLossAway': 17, 'SeasonGFAway': 48,
        'SeasonGAAway': 57, 'SeasonGDAway': -9, 'SeasonPointsAway': 41,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'West Ham': {
        'SeasonPosAway': 18, 'SeasonPlayedAway': 38, 'SeasonWinAway': 10,
        'SeasonDrawAway': 9, 'SeasonLossAway': 19, 'SeasonGFAway': 46,
        'SeasonGAAway': 65, 'SeasonGDAway': -19, 'SeasonPointsAway': 39,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    },
    'Burnley': {
        'SeasonPosAway': 19, 'SeasonPlayedAway': 38, 'SeasonWinAway': 4,
        'SeasonDrawAway': 10, 'SeasonLossAway': 24, 'SeasonGFAway': 38,
        'SeasonGAAway': 75, 'SeasonGDAway': -37, 'SeasonPointsAway': 22,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    },
    'Wolves': {
        'SeasonPosAway': 20, 'SeasonPlayedAway': 38, 'SeasonWinAway': 3,
        'SeasonDrawAway': 11, 'SeasonLossAway': 24, 'SeasonGFAway': 27,
        'SeasonGAAway': 68, 'SeasonGDAway': -41, 'SeasonPointsAway': 20,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    }
}

away_cols = [
    'SeasonPosAway', 'SeasonPlayedAway', 'SeasonWinAway', 'SeasonDrawAway',
    'SeasonLossAway', 'SeasonGFAway', 'SeasonGAAway', 'SeasonGDAway',
    'SeasonPointsAway', 'QualificationOrRelegationAway'
]

for idx, row in df[df['Season'] == '2526'].iterrows():
    away_team = row['AwayTeam']
    if away_team in season_stats_2025:
        for col in away_cols:
            df.loc[(df['Season'] == '2526') & (df.index == idx), col] = season_stats_2025[away_team][col]
    else:
        print(f" Season stats not found for {away_team}")

In [166]:
df[df['Season'] == '2526'].isna().sum()[df[df['Season'] == '2526'].isna().sum() > 0]

WeekDay       22
Time          22
Round         22
Attendance    22
XGHome        22
XGAway        22
dtype: int64

In [170]:
df[(df['Season'] == '2526') & (df['WeekDay'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

             HomeTeam        AwayTeam  Year  Month  Day
12326          Wolves        Man City  2025      8   16
12361       Brentford         Chelsea  2025      9   13
12387      Man United      Sunderland  2025     10    4
12391         Everton  Crystal Palace  2025     10    5
12428       Tottenham      Man United  2025     11    8
12430       Brentford       Newcastle  2025     11    9
12454     Bournemouth         Everton  2025     12    2
12471        Brighton        West Ham  2025     12    7
12488          Wolves       Brentford  2025     12   20
12534      Man United        Man City  2026      1   17
12538      Sunderland  Crystal Palace  2026      1   17
12541     Aston Villa         Everton  2026      1   18
12551  Crystal Palace         Chelsea  2026      1   25
12572        Brighton  Crystal Palace  2026      2    8
12576         Chelsea           Leeds  2026      2   10
12614       Tottenham  Crystal Palace  2026      3    5
12616         Arsenal         Everton  2026      3   14
12627          Fulham         Burnley  2026      3   21
12635         Burnley        Brighton  2026      4   11
12644           Leeds          Wolves  2026      4   18
12663           Leeds         Burnley  2026      5    1
12694        Man City     Aston Villa  2026      5   24

In [174]:
# Match data for the 2025/26 Premier League fixtures
match_data = {
    # 16 August 2025 - Wolves vs Man City
    ('Wolves', 'Man City'): {
        'WeekDay': 'Sat',
        'Time': '20:00',
        'Round': 1,
        'Attendance': 31118,
        'XGHome': 0.56,
        'XGAway': 2.47
    },
    # 13 September 2025 - Brentford vs Chelsea
    ('Brentford', 'Chelsea'): {
        'WeekDay': 'Sat',
        'Time': '22:30',
        'Round': 4,
        'Attendance': 16795,
        'XGHome': 1.43,
        'XGAway': 1.25
    },
    # 4 October 2025 - Man United vs Sunderland
    ('Man United', 'Sunderland'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 7,
        'Attendance': 74004,
        'XGHome': 1.84,
        'XGAway': 0.71
    },
    # 5 October 2025 - Everton vs Crystal Palace
    ('Everton', 'Crystal Palace'): {
        'WeekDay': 'Sun',
        'Time': '16:30',
        'Round': 7,
        'Attendance': 51770,
        'XGHome': 2.03,
        'XGAway': 1.53
    },
    # 8 November 2025 - Tottenham vs Man United
    ('Tottenham', 'Man United'): {
        'WeekDay': 'Sat',
        'Time': '16:00',
        'Round': 11,
        'Attendance': 61210,
        'XGHome': 0.92,
        'XGAway': 0.63
    },
    # 9 November 2025 - Brentford vs Newcastle
    ('Brentford', 'Newcastle'): {
        'WeekDay': 'Sun',
        'Time': '17:30',
        'Round': 11,
        'Attendance': 17207,
        'XGHome': 2.35,
        'XGAway': 0.44
    },
    # 2 December 2025 - Bournemouth vs Everton
    ('Bournemouth', 'Everton'): {
        'WeekDay': 'Tue',
        'Time': '23:00',
        'Round': 14,
        'Attendance': 11161,
        'XGHome': 0.5,
        'XGAway': 1.44
    },
    # 7 December 2025 - Brighton vs West Ham
    ('Brighton', 'West Ham'): {
        'WeekDay': 'Sun',
        'Time': '17:30',
        'Round': 15,
        'Attendance': 31293,
        'XGHome': 1.87,
        'XGAway': 1.14
    },
    # 20 December 2025 - Wolves vs Brentford
    ('Wolves', 'Brentford'): {
        'WeekDay': 'Sat',
        'Time': '18:30',
        'Round': 17,
        'Attendance': 27662,
        'XGHome': 1.27,
        'XGAway': 1.28
    },
    # 17 January 2026 - Man United vs Man City
    ('Man United', 'Man City'): {
        'WeekDay': 'Sat',
        'Time': '16:00',
        'Round': 22,
        'Attendance': 74004,
        'XGHome': 2.27,
        'XGAway': 0.45
    },
    # 17 January 2026 - Sunderland vs Crystal Palace
    ('Sunderland', 'Crystal Palace'): {
        'WeekDay': 'Sat',
        'Time': '18:30',
        'Round': 22,
        'Attendance': 47257,
        'XGHome': 1.71,
        'XGAway': 0.61
    },
    # 18 January 2026 - Aston Villa vs Everton
    ('Aston Villa', 'Everton'): {
        'WeekDay': 'Sun',
        'Time': '20:00',
        'Round': 22,
        'Attendance': 43059,
        'XGHome': 1.44,
        'XGAway': 0.51
    },
    # 25 January 2026 - Crystal Palace vs Chelsea
    ('Crystal Palace', 'Chelsea'): {
        'WeekDay': 'Sun',
        'Time': '17:30',
        'Round': 23,
        'Attendance': 25163,
        'XGHome': 1.77,
        'XGAway': 2.2
    },
    # 8 February 2026 - Brighton vs Crystal Palace
    ('Brighton', 'Crystal Palace'): {
        'WeekDay': 'Sun',
        'Time': '17:30',
        'Round': 25,
        'Attendance': 31179,
        'XGHome': 0.74,
        'XGAway': 1.16
    },
    # 10 February 2026 - Chelsea vs Leeds
    ('Chelsea', 'Leeds'): {
        'WeekDay': 'Tue',
        'Time': '23:00',
        'Round': 26,
        'Attendance': 39253,
        'XGHome': 3.13,
        'XGAway': 1.44
    },
    # 5 March 2026 - Tottenham vs Crystal Palace
    ('Tottenham', 'Crystal Palace'): {
        'WeekDay': 'Thu',
        'Time': '23:30',
        'Round': 29,
        'Attendance': 60213,
        'XGHome': 1.09,
        'XGAway': 1.78
    },
    # 14 March 2026 - Arsenal vs Everton
    ('Arsenal', 'Everton'): {
        'WeekDay': 'Sat',
        'Time': '21:00',
        'Round': 30,
        'Attendance': 60176,
        'XGHome': 2.7,
        'XGAway': 1.05
    },
    # 21 March 2026 - Fulham vs Burnley
    ('Fulham', 'Burnley'): {
        'WeekDay': 'Sat',
        'Time': '18:30',
        'Round': 31,
        'Attendance': 27323,
        'XGHome': 3.15,
        'XGAway': 1.24
    },
    # 11 April 2026 - Burnley vs Brighton
    ('Burnley', 'Brighton'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 32,
        'Attendance': 20408,
        'XGHome': 0.88,
        'XGAway': 1.93
    },
    # 18 April 2026 - Leeds vs Wolves
    ('Leeds', 'Wolves'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 33,
        'Attendance': 36840,
        'XGHome': 2.82,
        'XGAway': 0.57
    },
    # 1 May 2026 - Leeds vs Burnley
    ('Leeds', 'Burnley'): {
        'WeekDay': 'Fri',
        'Time': '22:30',
        'Round': 35,
        'Attendance': 36265,
        'XGHome': 1.64,
        'XGAway': 0.57
    },
    # 24 May 2026 - Man City vs Aston Villa
    ('Man City', 'Aston Villa'): {
        'WeekDay': 'Sun',
        'Time': '18:30',
        'Round': 38,
        'Attendance': 60332,
        'XGHome': 1.34,
        'XGAway': 1.77
    }
}

# Columns to fill
match_cols = ['WeekDay', 'Time', 'Round', 'Attendance', 'XGHome', 'XGAway']

# Loop through each row for the 2025-26 season
for idx, row in df[df['Season'] == '2526'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    if (home, away) in match_data:
        for col in match_cols:
            df.loc[(df['Season'] == '2526') & (df.index == idx), col] = match_data[(home, away)][col]

In [175]:
df[df['Season'] == '2526'].isna().sum()[df[df['Season'] == '2526'].isna().sum() > 0]

Series([], dtype: int64)

In [176]:
df[df['Season'] == '2425'].isna().sum()[df[df['Season'] == '2425'].isna().sum() > 0]

WeekDay                           20
Time                              20
Round                             20
Attendance                        20
XGHome                            20
XGAway                            20
SeasonPosAway                    380
SeasonPlayedAway                 380
SeasonWinAway                    380
SeasonDrawAway                   380
SeasonLossAway                   380
SeasonGFAway                     380
SeasonGAAway                     380
SeasonGDAway                     380
SeasonPointsAway                 380
QualificationOrRelegationAway    380
dtype: int64

In [177]:
df[(df['Season'] == '2425') & (df['WeekDay'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

             HomeTeam        AwayTeam  Year  Month  Day
11966         Everton     Bournemouth  2024      8   31
12001         Ipswich     Aston Villa  2024      9   29
12004        West Ham         Ipswich  2024     10    5
12007         Everton       Newcastle  2024     10    5
12018       Newcastle        Brighton  2024     10   19
12029         Everton          Fulham  2024     10   26
12032         Chelsea       Newcastle  2024     10   27
12075         Ipswich  Crystal Palace  2024     12    3
12104         Ipswich       Newcastle  2024     12   21
12125  Crystal Palace     Southampton  2024     12   29
12153         Arsenal     Aston Villa  2025      1   18
12157       Leicester          Fulham  2025      1   18
12172       Tottenham       Leicester  2025      1   26
12198     Bournemouth          Wolves  2025      2   22
12224        West Ham       Newcastle  2025      3   10
12225         Everton        West Ham  2025      3   15
12236     Southampton  Crystal Palace  2025      4    2
12254     Southampton     Aston Villa  2025      4   12
12279         Chelsea         Everton  2025      4   26
12285       Leicester     Southampton  2025      5    3

In [178]:
# Match data for the 2024/25 Premier League fixtures
match_data = {
    # 31 August 2024 - Everton vs Bournemouth
    ('Everton', 'Bournemouth'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 3,
        'Attendance': 39244,
        'XGHome': 1.97,
        'XGAway': 2.22
    },
    # 29 September 2024 - Ipswich vs Aston Villa
    ('Ipswich', 'Aston Villa'): {
        'WeekDay': 'Sun',
        'Time': '16:30',
        'Round': 6,
        'Attendance': 29943,
        'XGHome': 1.18,
        'XGAway': 0.82
    },
    # 5 October 2024 - West Ham vs Ipswich
    ('West Ham', 'Ipswich'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 7,
        'Attendance': 62467,
        'XGHome': 3.79,
        'XGAway': 0.65
    },
    # 5 October 2024 - Everton vs Newcastle
    ('Everton', 'Newcastle'): {
        'WeekDay': 'Sat',
        'Time': '20:00',
        'Round': 7,
        'Attendance': 39224,
        'XGHome': 0.72,
        'XGAway': 2.05
    },
    # 19 October 2024 - Newcastle vs Brighton
    ('Newcastle', 'Brighton'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 8,
        'Attendance': 52173,
        'XGHome': 2.03,
        'XGAway': 1.12
    },
    # 26 October 2024 - Everton vs Fulham
    ('Everton', 'Fulham'): {
        'WeekDay': 'Sat',
        'Time': '20:00',
        'Round': 9,
        'Attendance': 38742,
        'XGHome': 0.79,
        'XGAway': 1.25
    },
    # 27 October 2024 - Chelsea vs Newcastle
    ('Chelsea', 'Newcastle'): {
        'WeekDay': 'Sun',
        'Time': '16:30',
        'Round': 9,
        'Attendance': 39526,
        'XGHome': 1.68,
        'XGAway': 1.85
    },
    # 3 December 2024 - Ipswich vs Crystal Palace
    ('Ipswich', 'Crystal Palace'): {
        'WeekDay': 'Tue',
        'Time': '22:00',
        'Round': 14,
        'Attendance': 29318,
        'XGHome': 0.49,
        'XGAway': 1.53
    },
    # 21 December 2024 - Ipswich vs Newcastle
    ('Ipswich', 'Newcastle'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 17,
        'Attendance': 29638,
        'XGHome': 0.70,
        'XGAway': 2.31
    },
    # 29 December 2024 - Crystal Palace vs Southampton
    ('Crystal Palace', 'Southampton'): {
        'WeekDay': 'Sun',
        'Time': '17:30',
        'Round': 19,
        'Attendance': 25130,
        'XGHome': 2.03,
        'XGAway': 0.94
    },
    # 18 January 2025 - Arsenal vs Aston Villa
    ('Arsenal', 'Aston Villa'): {
        'WeekDay': 'Sat',
        'Time': '20:00',
        'Round': 22,
        'Attendance': 60239,
        'XGHome': 1.32,
        'XGAway': 1.06
    },
    # 18 January 2025 - Leicester vs Fulham
    ('Leicester', 'Fulham'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 22,
        'Attendance': 31500,
        'XGHome': 0.47,
        'XGAway': 2.08
    },
    # 26 January 2025 - Tottenham vs Leicester
    ('Tottenham', 'Leicester'): {
        'WeekDay': 'Sun',
        'Time': '16:30',
        'Round': 23,
        'Attendance': 61295,
        'XGHome': 1.04,
        'XGAway': 1.50
    },
    # 22 February 2025 - Bournemouth vs Wolves
    ('Bournemouth', 'Wolves'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 26,
        'Attendance': 11148,
        'XGHome': 0.62,
        'XGAway': 1.97
    },
    # 10 March 2025 - West Ham vs Newcastle
    ('West Ham', 'Newcastle'): {
        'WeekDay': 'Mon',
        'Time': '22:30',
        'Round': 28,
        'Attendance': 62463,
        'XGHome': 0.46,
        'XGAway': 1.38
    },
    # 15 March 2025 - Everton vs West Ham
    ('Everton', 'West Ham'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 29,
        'Attendance': 39249,
        'XGHome': 0.92,
        'XGAway': 0.57
    },
    # 2 April 2025 - Southampton vs Crystal Palace
    ('Southampton', 'Crystal Palace'): {
        'WeekDay': 'Wed',
        'Time': '21:15',
        'Round': 30,
        'Attendance': 30629,
        'XGHome': 0.52,
        'XGAway': 0.89
    },
    # 12 April 2025 - Southampton vs Aston Villa
    ('Southampton', 'Aston Villa'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 32,
        'Attendance': 30673,
        'XGHome': 0.32,
        'XGAway': 2.88
    },
    # 26 April 2025 - Chelsea vs Everton
    ('Chelsea', 'Everton'): {
        'WeekDay': 'Sat',
        'Time': '15:00',
        'Round': 34,
        'Attendance': 39894,
        'XGHome': 0.88,
        'XGAway': 0.44
    },
    # 3 May 2025 - Leicester vs Southampton
    ('Leicester', 'Southampton'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 35,
        'Attendance': 32261,
        'XGHome': 1.65,
        'XGAway': 0.63
    }
}

# Columns to fill
match_cols = ['WeekDay', 'Time', 'Round', 'Attendance', 'XGHome', 'XGAway']

# Loop through each row for the 2024-25 season
for idx, row in df[df['Season'] == '2425'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    if (home, away) in match_data:
        for col in match_cols:
            df.loc[(df['Season'] == '2425') & (df.index == idx), col] = match_data[(home, away)][col]

In [180]:
df[df['Season'] == '2425'].isna().sum()[df[df['Season'] == '2425'].isna().sum() > 0]

SeasonPosAway                    380
SeasonPlayedAway                 380
SeasonWinAway                    380
SeasonDrawAway                   380
SeasonLossAway                   380
SeasonGFAway                     380
SeasonGAAway                     380
SeasonGDAway                     380
SeasonPointsAway                 380
QualificationOrRelegationAway    380
dtype: int64

In [182]:
df[(df['Season'] == '2425') & (df['SeasonPosAway'].isna())]['AwayTeam'].unique()

array(['Fulham', 'Aston Villa', 'Liverpool', 'Wolves', 'Brighton',
       'Southampton', 'Bournemouth', 'Man City', 'Crystal Palace',
       'Tottenham', 'Man United', 'West Ham', 'Leicester', 'Ipswich',
       'Nottingham', 'Everton', 'Arsenal', 'Brentford', 'Chelsea',
       'Newcastle'], dtype=object)

In [183]:
# Dictionary containing season stats for all 20 teams
season_stats = {
    'Fulham': {
        'SeasonPosAway': 11,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 15,
        'SeasonDrawAway': 9,
        'SeasonLossAway': 14,
        'SeasonGFAway': 54,
        'SeasonGAAway': 54,
        'SeasonGDAway': 0,
        'SeasonPointsAway': 54,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Aston Villa': {
        'SeasonPosAway': 6,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 19,
        'SeasonDrawAway': 9,
        'SeasonLossAway': 10,
        'SeasonGFAway': 58,
        'SeasonGAAway': 51,
        'SeasonGDAway': 7,
        'SeasonPointsAway': 66,
        'QualificationOrRelegationAway': 'Qualification for the Europa League group stage'
    },
    'Liverpool': {
        'SeasonPosAway': 1,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 25,
        'SeasonDrawAway': 9,
        'SeasonLossAway': 4,
        'SeasonGFAway': 86,
        'SeasonGAAway': 41,
        'SeasonGDAway': 45,
        'SeasonPointsAway': 84,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Wolves': {
        'SeasonPosAway': 16,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 12,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 20,
        'SeasonGFAway': 54,
        'SeasonGAAway': 69,
        'SeasonGDAway': -15,
        'SeasonPointsAway': 42,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Brighton': {
        'SeasonPosAway': 8,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 16,
        'SeasonDrawAway': 13,
        'SeasonLossAway': 9,
        'SeasonGFAway': 66,
        'SeasonGAAway': 59,
        'SeasonGDAway': 7,
        'SeasonPointsAway': 61,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Southampton': {
        'SeasonPosAway': 20,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 2,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 30,
        'SeasonGFAway': 26,
        'SeasonGAAway': 86,
        'SeasonGDAway': -60,
        'SeasonPointsAway': 12,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    },
    'Bournemouth': {
        'SeasonPosAway': 9,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 15,
        'SeasonDrawAway': 11,
        'SeasonLossAway': 12,
        'SeasonGFAway': 58,
        'SeasonGAAway': 46,
        'SeasonGDAway': 12,
        'SeasonPointsAway': 56,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Man City': {
        'SeasonPosAway': 3,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 21,
        'SeasonDrawAway': 8,
        'SeasonLossAway': 9,
        'SeasonGFAway': 72,
        'SeasonGAAway': 44,
        'SeasonGDAway': 28,
        'SeasonPointsAway': 71,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Crystal Palace': {
        'SeasonPosAway': 12,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 13,
        'SeasonDrawAway': 14,
        'SeasonLossAway': 11,
        'SeasonGFAway': 51,
        'SeasonGAAway': 51,
        'SeasonGDAway': 0,
        'SeasonPointsAway': 53,
        'QualificationOrRelegationAway': 'Qualification for the Europa League group stage'
    },
    'Tottenham': {
        'SeasonPosAway': 17,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 5,
        'SeasonLossAway': 22,
        'SeasonGFAway': 64,
        'SeasonGAAway': 65,
        'SeasonGDAway': -1,
        'SeasonPointsAway': 38,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Man United': {
        'SeasonPosAway': 15,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 9,
        'SeasonLossAway': 18,
        'SeasonGFAway': 44,
        'SeasonGAAway': 54,
        'SeasonGDAway': -10,
        'SeasonPointsAway': 42,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'West Ham': {
        'SeasonPosAway': 14,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 10,
        'SeasonLossAway': 17,
        'SeasonGFAway': 46,
        'SeasonGAAway': 62,
        'SeasonGDAway': -16,
        'SeasonPointsAway': 43,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Leicester': {
        'SeasonPosAway': 18,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 6,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 25,
        'SeasonGFAway': 33,
        'SeasonGAAway': 80,
        'SeasonGDAway': -47,
        'SeasonPointsAway': 25,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    },
    'Ipswich': {
        'SeasonPosAway': 19,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 4,
        'SeasonDrawAway': 10,
        'SeasonLossAway': 24,
        'SeasonGFAway': 36,
        'SeasonGAAway': 82,
        'SeasonGDAway': -46,
        'SeasonPointsAway': 22,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    },
    'Nottingham': {
        'SeasonPosAway': 7,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 19,
        'SeasonDrawAway': 8,
        'SeasonLossAway': 11,
        'SeasonGFAway': 58,
        'SeasonGAAway': 46,
        'SeasonGDAway': 12,
        'SeasonPointsAway': 65,
        'QualificationOrRelegationAway': 'Qualification for the Europa League group stage'
    },
    'Everton': {
        'SeasonPosAway': 13,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 11,
        'SeasonDrawAway': 15,
        'SeasonLossAway': 12,
        'SeasonGFAway': 42,
        'SeasonGAAway': 44,
        'SeasonGDAway': -2,
        'SeasonPointsAway': 48,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Arsenal': {
        'SeasonPosAway': 2,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 20,
        'SeasonDrawAway': 14,
        'SeasonLossAway': 4,
        'SeasonGFAway': 69,
        'SeasonGAAway': 34,
        'SeasonGDAway': 35,
        'SeasonPointsAway': 74,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Brentford': {
        'SeasonPosAway': 10,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 16,
        'SeasonDrawAway': 8,
        'SeasonLossAway': 14,
        'SeasonGFAway': 66,
        'SeasonGAAway': 57,
        'SeasonGDAway': 9,
        'SeasonPointsAway': 56,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Chelsea': {
        'SeasonPosAway': 4,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 20,
        'SeasonDrawAway': 9,
        'SeasonLossAway': 9,
        'SeasonGFAway': 64,
        'SeasonGAAway': 43,
        'SeasonGDAway': 21,
        'SeasonPointsAway': 69,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Newcastle': {
        'SeasonPosAway': 5,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 20,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 12,
        'SeasonGFAway': 68,
        'SeasonGAAway': 47,
        'SeasonGDAway': 21,
        'SeasonPointsAway': 66,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    }
}

# Columns to fill
away_cols = [
    'SeasonPosAway', 'SeasonPlayedAway', 'SeasonWinAway', 'SeasonDrawAway',
    'SeasonLossAway', 'SeasonGFAway', 'SeasonGAAway', 'SeasonGDAway',
    'SeasonPointsAway', 'QualificationOrRelegationAway'
]

# Loop through each row for the 2024-25 season
for idx, row in df[df['Season'] == '2425'].iterrows():
    away_team = row['AwayTeam']
    if away_team in season_stats:
        for col in away_cols:
            df.loc[(df['Season'] == '2425') & (df.index == idx), col] = season_stats[away_team][col]

In [184]:
df.to_csv("Data/Data4.csv", index=False)

In [185]:
df[df['Season'] == '2324'].isna().sum()[df[df['Season'] == '2324'].isna().sum() > 0]

WeekDay                           16
Time                              16
Round                             16
Attendance                       176
XGHome                            16
XGAway                            16
SeasonPosAway                    380
SeasonPlayedAway                 380
SeasonWinAway                    380
SeasonDrawAway                   380
SeasonLossAway                   380
SeasonGFAway                     380
SeasonGAAway                     380
SeasonGDAway                     380
SeasonPointsAway                 380
QualificationOrRelegationAway    380
dtype: int64

In [196]:
all(df[(df['Season'] == '2324') & (df['WeekDay'].isna())] == df[(df['Season'] == '2324') & (df['XGHome'].isna())])

True

In [195]:
all(df[(df['Season'] == '2324') & (df['WeekDay'].isna())] == df[(df['Season'] == '2324') & (df['Time'].isna())])

True

In [197]:
df[(df['Season'] == '2324') & (df['WeekDay'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

             HomeTeam     AwayTeam  Year  Month  Day
11566         Arsenal   Nottingham  2023      8   12
11631      Nottingham    Brentford  2023     10    1
11664       Sheffield       Wolves  2023     11    4
11691       Tottenham  Aston Villa  2023     11   26
11706     Aston Villa     Man City  2023     12    6
11741          Wolves      Chelsea  2023     12   24
11790         Arsenal    Liverpool  2024      2    4
11803         Burnley      Arsenal  2024      2   17
11814     Bournemouth     Man City  2024      2   24
11832      Man United      Everton  2024      3    9
11833     Bournemouth    Sheffield  2024      3    9
11841         Chelsea    Newcastle  2024      3   11
11886         Chelsea      Everton  2024      4   15
11920  Crystal Palace   Man United  2024      5    6
11931       Tottenham     Man City  2024      5   14
11938           Luton       Fulham  2024      5   19

In [ ]:
match_data = {
    # شنبه 12 اوت 2023 - آرسنال vs ناتینگهام فارست
    ('Arsenal', 'Nottingham'): {
        'WeekDay': 'Sat',
        'Time': '15:30',
        'Round': 1,
        'Attendance': 59984,    # [0 0L9]
        'XGHome': None,
        'XGAway': None
    },
    # یکشنبه 1 اکتبر 2023 - ناتینگهام فارست vs برنتفورد
    ('Nottingham', 'Brentford'): {
        'WeekDay': 'Sun',
        'Time': '16:30',
        'Round': 7,
        'Attendance': 29004,    # [1 0L9]
        'XGHome': None,
        'XGAway': None
    },
    # شنبه 4 نوامبر 2023 - شفیلد یونایتد vs ولوز
    ('Sheffield', 'Wolves'): {
        'WeekDay': 'Sat',
        'Time': '18:30',
        'Round': 11,
        'Attendance': 29454,    # [2 0L9]
        'XGHome': None,
        'XGAway': None
    },
    # یکشنبه 26 نوامبر 2023 - تاتنهام vs استون ویلا
    ('Tottenham', 'Aston Villa'): {
        'WeekDay': 'Sun',
        'Time': '17:30',
        'Round': 13,
        'Attendance': 61679,    # [3 0L7]
        'XGHome': None,
        'XGAway': None
    },
    # چهارشنبه 6 دسامبر 2023 - استون ویلا vs منچستر سیتی
    ('Aston Villa', 'Man City'): {
        'WeekDay': 'Wed',
        'Time': '23:45',
        'Round': 15,
        'Attendance': 42321,    # [4 0L17]
        'XGHome': None,
        'XGAway': None
    },
    # یکشنبه 24 دسامبر 2023 - ولوز vs چلسی
    ('Wolves', 'Chelsea'): {
        'WeekDay': 'Sun',
        'Time': '16:30',
        'Round': 18,
        'Attendance': 31641,    # [5 0L7]
        'XGHome': 1.3,          # [5 0L37]
        'XGAway': 2.0           # [5 0L37]
    },
    # یکشنبه 4 فوریه 2024 - آرسنال vs لیورپول
    ('Arsenal', 'Liverpool'): {
        'WeekDay': 'Sun',
        'Time': '20:00',
        'Round': 23,
        'Attendance': 60374,    # [6 0L8]
        'XGHome': None,
        'XGAway': None
    },
    # شنبه 17 فوریه 2024 - برنلی vs آرسنال
    ('Burnley', 'Arsenal'): {
        'WeekDay': 'Sat',
        'Time': '18:30',
        'Round': 25,
        'Attendance': 21483,    # worldfootball
        'XGHome': None,
        'XGAway': None
    },
    # شنبه 24 فوریه 2024 - بورنموث vs منچستر سیتی
    ('Bournemouth', 'Man City'): {
        'WeekDay': 'Sat',
        'Time': '21:00',
        'Round': 26,
        'Attendance': 11185,    # worldfootball
        'XGHome': None,
        'XGAway': None
    },
    # شنبه 9 مارس 2024 - منچستر یونایتد vs اورتون
    ('Man United', 'Everton'): {
        'WeekDay': 'Sat',
        'Time': '16:00',
        'Round': 28,
        'Attendance': 73654,    # DFB
        'XGHome': None,
        'XGAway': None
    },
    # شنبه 9 مارس 2024 - بورنموث vs شفیلد یونایتد
    ('Bournemouth', 'Sheffield'): {
        'WeekDay': 'Sat',
        'Time': '18:30',
        'Round': 28,
        'Attendance': 10852,    # DFB
        'XGHome': None,
        'XGAway': None
    },
    # دوشنبه 11 مارس 2024 - چلسی vs نیوکاسل
    ('Chelsea', 'Newcastle'): {
        'WeekDay': 'Mon',
        'Time': '23:30',
        'Round': 28,
        'Attendance': 38516,    # DFB
        'XGHome': None,
        'XGAway': None
    },
    # دوشنبه 15 آوریل 2024 - چلسی vs اورتون
    ('Chelsea', 'Everton'): {
        'WeekDay': 'Mon',
        'Time': '23:30',
        'Round': 33,
        'Attendance': 39389,    # DFB
        'XGHome': None,
        'XGAway': None
    },
    # دوشنبه 6 مه 2024 - کریستال پالاس vs منچستر یونایتد
    ('Crystal Palace', 'Man United'): {
        'WeekDay': 'Mon',
        'Time': '23:30',
        'Round': 36,
        'Attendance': 25141,    # ESPN
        'XGHome': None,
        'XGAway': None
    },
    # سه‌شنبه 14 مه 2024 - تاتنهام vs منچستر سیتی
    ('Tottenham', 'Man City'): {
        'WeekDay': 'Tue',
        'Time': '23:30',
        'Round': 34,
        'Attendance': 61153,    # worldfootball
        'XGHome': None,
        'XGAway': None
    },
    # یکشنبه 19 مه 2024 - لوتون vs فولام
    ('Luton', 'Fulham'): {
        'WeekDay': 'Sun',
        'Time': '19:30',
        'Round': 38,
        'Attendance': 10779,    # worldfootball
        'XGHome': 2.11,
        'XGAway': None
    },
}

season_stats = {
    'Arsenal': {
        'SeasonPosAway': 2,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 28,
        'SeasonDrawAway': 5,
        'SeasonLossAway': 5,
        'SeasonGFAway': 91,
        'SeasonGAAway': 29,
        'SeasonGDAway': 62,
        'SeasonPointsAway': 89,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Aston Villa': {
        'SeasonPosAway': 4,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 20,
        'SeasonDrawAway': 8,
        'SeasonLossAway': 10,
        'SeasonGFAway': 76,
        'SeasonGAAway': 61,
        'SeasonGDAway': 15,
        'SeasonPointsAway': 68,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Bournemouth': {
        'SeasonPosAway': 12,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 13,
        'SeasonDrawAway': 9,
        'SeasonLossAway': 16,
        'SeasonGFAway': 54,
        'SeasonGAAway': 67,
        'SeasonGDAway': -13,
        'SeasonPointsAway': 48,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Brentford': {
        'SeasonPosAway': 16,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 10,
        'SeasonDrawAway': 9,
        'SeasonLossAway': 19,
        'SeasonGFAway': 56,
        'SeasonGAAway': 65,
        'SeasonGDAway': -9,
        'SeasonPointsAway': 39,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Burnley': {
        'SeasonPosAway': 19,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 5,
        'SeasonDrawAway': 9,
        'SeasonLossAway': 24,
        'SeasonGFAway': 41,
        'SeasonGAAway': 78,
        'SeasonGDAway': -37,
        'SeasonPointsAway': 24,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    },
    'Chelsea': {
        'SeasonPosAway': 6,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 18,
        'SeasonDrawAway': 9,
        'SeasonLossAway': 11,
        'SeasonGFAway': 77,
        'SeasonGAAway': 63,
        'SeasonGDAway': 14,
        'SeasonPointsAway': 63,
        'QualificationOrRelegationAway': 'Qualification for the Europa Conference League play-off round'
    },
    'Crystal Palace': {
        'SeasonPosAway': 10,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 13,
        'SeasonDrawAway': 10,
        'SeasonLossAway': 15,
        'SeasonGFAway': 57,
        'SeasonGAAway': 58,
        'SeasonGDAway': -1,
        'SeasonPointsAway': 49,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Everton': {
        'SeasonPosAway': 15,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 13,
        'SeasonDrawAway': 9,
        'SeasonLossAway': 16,
        'SeasonGFAway': 40,
        'SeasonGAAway': 51,
        'SeasonGDAway': -11,
        'SeasonPointsAway': 48,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Fulham': {
        'SeasonPosAway': 13,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 13,
        'SeasonDrawAway': 8,
        'SeasonLossAway': 17,
        'SeasonGFAway': 55,
        'SeasonGAAway': 61,
        'SeasonGDAway': -6,
        'SeasonPointsAway': 47,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Liverpool': {
        'SeasonPosAway': 3,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 24,
        'SeasonDrawAway': 10,
        'SeasonLossAway': 4,
        'SeasonGFAway': 86,
        'SeasonGAAway': 41,
        'SeasonGDAway': 45,
        'SeasonPointsAway': 82,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Luton': {
        'SeasonPosAway': 18,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 6,
        'SeasonDrawAway': 8,
        'SeasonLossAway': 24,
        'SeasonGFAway': 52,
        'SeasonGAAway': 85,
        'SeasonGDAway': -33,
        'SeasonPointsAway': 26,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    },
    'Man City': {
        'SeasonPosAway': 1,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 28,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 3,
        'SeasonGFAway': 96,
        'SeasonGAAway': 34,
        'SeasonGDAway': 62,
        'SeasonPointsAway': 91,
        'QualificationOrRelegationAway': 'Qualification for the Champions League group stage'
    },
    'Man United': {
        'SeasonPosAway': 8,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 18,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 14,
        'SeasonGFAway': 57,
        'SeasonGAAway': 58,
        'SeasonGDAway': -1,
        'SeasonPointsAway': 60,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Newcastle': {
        'SeasonPosAway': 7,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 18,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 14,
        'SeasonGFAway': 85,
        'SeasonGAAway': 62,
        'SeasonGDAway': 23,
        'SeasonPointsAway': 60,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Nottingham': {
        'SeasonPosAway': 17,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 9,
        'SeasonDrawAway': 9,
        'SeasonLossAway': 20,
        'SeasonGFAway': 49,
        'SeasonGAAway': 67,
        'SeasonGDAway': -18,
        'SeasonPointsAway': 36,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Sheffield': {
        'SeasonPosAway': 20,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 3,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 28,
        'SeasonGFAway': 35,
        'SeasonGAAway': 104,
        'SeasonGDAway': -69,
        'SeasonPointsAway': 16,
        'QualificationOrRelegationAway': 'Relegation to the EFL Championship'
    },
    'Tottenham': {
        'SeasonPosAway': 5,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 20,
        'SeasonDrawAway': 6,
        'SeasonLossAway': 12,
        'SeasonGFAway': 74,
        'SeasonGAAway': 61,
        'SeasonGDAway': 13,
        'SeasonPointsAway': 66,
        'QualificationOrRelegationAway': 'Qualification for the Europa League group stage'
    },
    'West Ham': {
        'SeasonPosAway': 9,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 14,
        'SeasonDrawAway': 10,
        'SeasonLossAway': 14,
        'SeasonGFAway': 60,
        'SeasonGAAway': 74,
        'SeasonGDAway': -14,
        'SeasonPointsAway': 52,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
    'Wolves': {
        'SeasonPosAway': 14,
        'SeasonPlayedAway': 38,
        'SeasonWinAway': 13,
        'SeasonDrawAway': 7,
        'SeasonLossAway': 18,
        'SeasonGFAway': 50,
        'SeasonGAAway': 65,
        'SeasonGDAway': -15,
        'SeasonPointsAway': 46,
        'QualificationOrRelegationAway': 'Not Applicable'
    },
}

match_cols = ['WeekDay', 'Time', 'Round', 'Attendance', 'XGHome', 'XGAway']

away_cols = [
    'SeasonPosAway', 'SeasonPlayedAway', 'SeasonWinAway', 'SeasonDrawAway',
    'SeasonLossAway', 'SeasonGFAway', 'SeasonGAAway', 'SeasonGDAway',
    'SeasonPointsAway', 'QualificationOrRelegationAway'
]

for idx, row in df[df['Season'] == '2324'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    if (home, away) in match_data:
        for col in match_cols:
            df.loc[(df['Season'] == '2324') & (df.index == idx), col] = match_data[(home, away)][col]
    
    if away in season_stats:
        for col in away_cols:
            df.loc[(df['Season'] == '2324') & (df.index == idx), col] = season_stats[away][col]

In [200]:
df[df['Season'] == '2324'].isna().sum()[df[df['Season'] == '2324'].isna().sum() > 0]

Attendance                       160
XGHome                            14
XGAway                            15
SeasonPosAway                     19
SeasonPlayedAway                  19
SeasonWinAway                     19
SeasonDrawAway                    19
SeasonLossAway                    19
SeasonGFAway                      19
SeasonGAAway                      19
SeasonGDAway                      19
SeasonPointsAway                  19
QualificationOrRelegationAway     19
dtype: int64

In [202]:
df[(df['Season'] == '2324') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']][:100]

             HomeTeam        AwayTeam  Year  Month  Day
11564         Burnley        Man City  2023      8   11
11565       Sheffield  Crystal Palace  2023      8   12
11567     Bournemouth        West Ham  2023      8   12
11568        Brighton           Luton  2023      8   12
11569         Everton          Fulham  2023      8   12
11570       Newcastle     Aston Villa  2023      8   12
11571         Chelsea       Liverpool  2023      8   13
11572       Brentford       Tottenham  2023      8   13
11573      Man United          Wolves  2023      8   14
11574      Nottingham       Sheffield  2023      8   18
11575          Fulham       Brentford  2023      8   19
11576       Liverpool     Bournemouth  2023      8   19
11577          Wolves        Brighton  2023      8   19
11578       Tottenham      Man United  2023      8   19
11579        Man City       Newcastle  2023      8   19
11580     Aston Villa         Everton  2023      8   20
11581        West Ham         Chelsea  2023      8   20
11582  Crystal Palace         Arsenal  2023      8   21
11583         Chelsea           Luton  2023      8   25
11584     Bournemouth       Tottenham  2023      8   26
11585         Arsenal          Fulham  2023      8   26
11586       Brentford  Crystal Palace  2023      8   26
11587         Everton          Wolves  2023      8   26
11588      Man United      Nottingham  2023      8   26
11589        Brighton        West Ham  2023      8   26
11590         Burnley     Aston Villa  2023      8   27
11591       Sheffield        Man City  2023      8   27
11592       Newcastle       Liverpool  2023      8   27
11593           Luton        West Ham  2023      9    1
11594         Chelsea      Nottingham  2023      9    2
11595         Burnley       Tottenham  2023      9    2
11596        Brighton       Newcastle  2023      9    2
11597       Sheffield         Everton  2023      9    2
11598       Brentford     Bournemouth  2023      9    2
11599        Man City          Fulham  2023      9    2
11600         Arsenal      Man United  2023      9    3
11601  Crystal Palace          Wolves  2023      9    3
11602       Liverpool     Aston Villa  2023      9    3
11603          Wolves       Liverpool  2023      9   16
11604     Aston Villa  Crystal Palace  2023      9   16
11605          Fulham           Luton  2023      9   16
11606      Man United        Brighton  2023      9   16
11607       Tottenham       Sheffield  2023      9   16
11608        West Ham        Man City  2023      9   16
11609       Newcastle       Brentford  2023      9   16
11610     Bournemouth         Chelsea  2023      9   17
11611         Everton         Arsenal  2023      9   17
11612      Nottingham         Burnley  2023      9   18
11613         Burnley      Man United  2023      9   23
11614       Brentford         Everton  2023      9   23
11615  Crystal Palace          Fulham  2023      9   23
11616           Luton          Wolves  2023      9   23
11617        Man City      Nottingham  2023      9   23
11618         Arsenal       Tottenham  2023      9   24
11619        Brighton     Bournemouth  2023      9   24
11620         Chelsea     Aston Villa  2023      9   24
11621       Liverpool        West Ham  2023      9   24
11622       Sheffield       Newcastle  2023      9   24
11623        West Ham       Sheffield  2023      9   30
11624       Tottenham       Liverpool  2023      9   30
11625       Newcastle         Burnley  2023      9   30
11626          Wolves        Man City  2023      9   30
11627         Everton           Luton  2023      9   30
11628     Bournemouth         Arsenal  2023      9   30
11629     Aston Villa        Brighton  2023      9   30
11630      Man United  Crystal Palace  2023      9   30
11632          Fulham         Chelsea  2023     10    2
11633           Luton         Burnley  2023     10    3
11634           Luton       Tottenham  2023     10    7
11635         Burnley         Chelsea  2023     10    7
11636         Everton     Bournemouth  2023     10    7
11637          Fulham       Sheffield  2023     10    7
11638      Man United       Brentford  2023     10    7
11639  Crystal Palace      Nottingham  2023     10    7
11640         Arsenal        Man City  2023     10    8
11641          Wolves     Aston Villa  2023     10    8
11642        West Ham       Newcastle  2023     10    8
11643        Brighton       Liverpool  2023     10    8
11644       Liverpool         Everton  2023     10   21
11645     Bournemouth          Wolves  2023     10   21
11646       Brentford         Burnley  2023     10   21
11647        Man City        Brighton  2023     10   21
11648       Newcastle  Crystal Palace  2023     10   21
11649      Nottingham           Luton  2023     10   21
11650         Chelsea         Arsenal  2023     10   21
11651       Sheffield      Man United  2023     10   21
11652     Aston Villa        West Ham  2023     10   22
11653       Tottenham          Fulham  2023     10   23
11654  Crystal Palace       Tottenham  2023     10   27
11655          Wolves       Newcastle  2023     10   28
11656     Bournemouth         Burnley  2023     10   28
11657         Chelsea       Brentford  2023     10   28
11658         Arsenal       Sheffield  2023     10   28
11659        West Ham         Everton  2023     10   29
11660     Aston Villa           Luton  2023     10   29
11661        Brighton          Fulham  2023     10   29
11662       Liverpool      Nottingham  2023     10   29
11663      Man United        Man City  2023     10   29
11665       Newcastle         Arsenal  2023     11    4
11666         Everton        Brighton  2023     11    4

In [ ]:
attendance_data = {
    # Friday 11 August 2023
    ('Burnley', 'Man City'): 21572,
    # Saturday 12 August 2023
    ('Sheffield', 'Crystal Palace'): 31194,
    ('Bournemouth', 'West Ham'): 11245,
    ('Brighton', 'Luton'): 31872,
    ('Everton', 'Fulham'): 39940,
    ('Newcastle', 'Aston Villa'): 52207,
    # Sunday 13 August 2023
    ('Chelsea', 'Liverpool'): 40096,
    ('Brentford', 'Tottenham'): 17066,
    # Monday 14 August 2023
    ('Man United', 'Wolves'): 73358,
    # Friday 18 August 2023
    ('Nottingham', 'Sheffield'): 29432,
    # Saturday 19 August 2023
    ('Fulham', 'Brentford'): 24236,
    ('Liverpool', 'Bournemouth'): 53145,  # Confirmed 53,145 per FBref  4]
    ('Wolves', 'Brighton'): 31317,
    ('Tottenham', 'Man United'): 61910,
    ('Man City', 'Newcastle'): 53419,     # Confirmed 53,419 per FBref  5]
    # Sunday 20 August 2023
    ('Aston Villa', 'Everton'): 41694,
    ('West Ham', 'Chelsea'): 62470,
    # Monday 21 August 2023
    ('Crystal Palace', 'Arsenal'): 24189,
    # Friday 25 August 2023
    ('Chelsea', 'Luton'): 39893,
    # Saturday 26 August 2023
    ('Bournemouth', 'Tottenham'): 10567,
    ('Arsenal', 'Fulham'): 59961,
    ('Brentford', 'Crystal Palace'): 16997,
    ('Everton', 'Wolves'): 38851,
    ('Man United', 'Nottingham'): 73595,
    ('Brighton', 'West Ham'): 31508,
    # Sunday 27 August 2023
    ('Burnley', 'Aston Villa'): 21591,
    ('Sheffield', 'Man City'): 31336,
    ('Newcastle', 'Liverpool'): 52214,
    # Friday 1 September 2023
    ('Luton', 'West Ham'): 10802,
    # Saturday 2 September 2023
    ('Chelsea', 'Nottingham'): 39820,
    ('Burnley', 'Tottenham'): 21750,
    ('Brighton', 'Newcastle'): 31620,
}

for idx, row in df[df['Season'] == '2324'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2324') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [203]:
df[(df['Season'] == '2324') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']][100:]

             HomeTeam        AwayTeam  Year  Month  Day
11667        Man City     Bournemouth  2023     11    4
11668       Brentford        West Ham  2023     11    4
11669          Fulham      Man United  2023     11    4
11670         Burnley  Crystal Palace  2023     11    4
11671      Nottingham     Aston Villa  2023     11    5
11672           Luton       Liverpool  2023     11    5
11673       Tottenham         Chelsea  2023     11    6
11674      Man United           Luton  2023     11   11
11675          Wolves       Tottenham  2023     11   11
11676         Arsenal         Burnley  2023     11   11
11677  Crystal Palace         Everton  2023     11   11
11678     Bournemouth       Newcastle  2023     11   11
11679         Chelsea        Man City  2023     11   12
11680        West Ham      Nottingham  2023     11   12
11681       Liverpool       Brentford  2023     11   12
11682        Brighton       Sheffield  2023     11   12
11683     Aston Villa          Fulham  2023     11   12
11684        Man City       Liverpool  2023     11   25
11685         Burnley        West Ham  2023     11   25
11686           Luton  Crystal Palace  2023     11   25
11687       Newcastle         Chelsea  2023     11   25
11688      Nottingham        Brighton  2023     11   25
11689       Sheffield     Bournemouth  2023     11   25
11690       Brentford         Arsenal  2023     11   25
11692         Everton      Man United  2023     11   26
11693          Fulham          Wolves  2023     11   27
11694         Arsenal          Wolves  2023     12    2
11695       Brentford           Luton  2023     12    2
11696         Burnley       Sheffield  2023     12    2
11697      Nottingham         Everton  2023     12    2
11698       Newcastle      Man United  2023     12    2
11699     Bournemouth     Aston Villa  2023     12    3
11700         Chelsea        Brighton  2023     12    3
11701       Liverpool          Fulham  2023     12    3
11702        West Ham  Crystal Palace  2023     12    3
11703        Man City       Tottenham  2023     12    3
11704          Wolves         Burnley  2023     12    5
11705           Luton         Arsenal  2023     12    5
11707      Man United         Chelsea  2023     12    6
11708          Fulham      Nottingham  2023     12    6
11709  Crystal Palace     Bournemouth  2023     12    6
11710       Sheffield       Liverpool  2023     12    6
11711        Brighton       Brentford  2023     12    6
11712         Everton       Newcastle  2023     12    7
11713       Tottenham        West Ham  2023     12    7
11714  Crystal Palace       Liverpool  2023     12    9
11715        Brighton         Burnley  2023     12    9
11716      Man United     Bournemouth  2023     12    9
11717       Sheffield       Brentford  2023     12    9
11718          Wolves      Nottingham  2023     12    9
11719     Aston Villa         Arsenal  2023     12    9
11720           Luton        Man City  2023     12   10
11721       Tottenham       Newcastle  2023     12   10
11722         Everton         Chelsea  2023     12   10
11723          Fulham        West Ham  2023     12   10
11724      Nottingham       Tottenham  2023     12   15
11725         Chelsea       Sheffield  2023     12   16
11726        Man City  Crystal Palace  2023     12   16
11727       Newcastle          Fulham  2023     12   16
11728         Burnley         Everton  2023     12   16

In [ ]:
attendance_data = {
    # Saturday 4 November 2023
    ('Man City', 'Bournemouth'): 53358,           # [0 0L10]
    ('Brentford', 'West Ham'): 17103,             # [1 0L13]
    ('Fulham', 'Man United'): 24415,              # [2 0L8]
    ('Burnley', 'Crystal Palace'): 21578,         # [3 0L7]

    # Sunday 5 November 2023
    ('Nottingham', 'Aston Villa'): 29313,         # [4 0L9]
    ('Luton', 'Liverpool'): 11049,                # [5 0L7]

    # Monday 6 November 2023
    ('Tottenham', 'Chelsea'): 61726,              # [6 0L8]

    # Saturday 11 November 2023
    ('Man United', 'Luton'): 73599,               # [7 0L8]
    ('Wolves', 'Tottenham'): 31642,               # [8 0L7]
    ('Arsenal', 'Burnley'): 60232,                # [9 0L6]
    ('Crystal Palace', 'Everton'): 25103,         # [10 0L7]
    ('Bournemouth', 'Newcastle'): 11201,          # [11 0L7]

    # Sunday 12 November 2023
    ('Chelsea', 'Man City'): 39532,               # [12 0L7]
    ('West Ham', 'Nottingham'): 62470,            # [13 0L8]
    ('Liverpool', 'Brentford'): 50151,            # [14 0L7]
    ('Brighton', 'Sheffield'): 31367,             # [15 0L7]
    ('Aston Villa', 'Fulham'): 41608,             # [16 0L6]

    # Saturday 25 November 2023
    ('Man City', 'Liverpool'): 53289,             # [17 0L8]
    ('Burnley', 'West Ham'): 21319,               # [18 0L6]
    ('Luton', 'Crystal Palace'): 11029,           # [19 0L8]
    ('Newcastle', 'Chelsea'): 52227,              # [20 0L6]
    ('Nottingham', 'Brighton'): 29404,            # [21 0L8]
    ('Sheffield', 'Bournemouth'): 30208,          # [22 0L8]
    ('Brentford', 'Arsenal'): 17201,              # [23 0L6]

    # Sunday 26 November 2023
    ('Everton', 'Man United'): 39257,             # [24 0L8]

    # Monday 27 November 2023
    ('Fulham', 'Wolves'): 24366,                  # [25 0L6]

    # Saturday 2 December 2023
    ('Arsenal', 'Wolves'): 60262,                 # [26 0L7]
    ('Brentford', 'Luton'): 17075,                # [27 0L6]
    ('Burnley', 'Sheffield'): 20891,              # [28 0L9]
    ('Nottingham', 'Everton'): 29404,             # [29 0L8]
    ('Newcastle', 'Man United'): 52214,           # [30 0L7]

    # Sunday 3 December 2023
    ('Bournemouth', 'Aston Villa'): 11191,        # [31 0L7]
    ('Chelsea', 'Brighton'): 39647,               # [32 0L7]
    ('Liverpool', 'Fulham'): 50143,               # [33 0L6]
    ('West Ham', 'Crystal Palace'): 62459,        # [34 0L7]
    ('Man City', 'Tottenham'): 53473,             # [35 0L8]

    # Tuesday 5 December 2023
    ('Wolves', 'Burnley'): 30439,                 # [36 0L7]
    ('Luton', 'Arsenal'): 11112,                  # [37 0L6]

    # Wednesday 6 December 2023
    ('Man United', 'Chelsea'): 73607,             # [38 0L8]
    ('Fulham', 'Nottingham'): 24105,              # [39 0L8]
    ('Crystal Palace', 'Bournemouth'): 25078,     # [40 0L6]
    ('Sheffield', 'Liverpool'): 31406,            # [41 0L7]
    ('Brighton', 'Brentford'): 30760,             # [42 0L7]

    # Thursday 7 December 2023
    ('Everton', 'Newcastle'): 38198,              # [43 0L7]
    ('Tottenham', 'West Ham'): 60733,             # [44 0L7]

    # Saturday 9 December 2023
    ('Crystal Palace', 'Liverpool'): 25103,       # [45 0L8]
    ('Brighton', 'Burnley'): 31511,               # [46 0L6]
    ('Man United', 'Bournemouth'): 73427,         # [47 0L8]
    ('Sheffield', 'Brentford'): 28509,            # [48 0L8]
    ('Wolves', 'Nottingham'): 31543,              # [49 0L8]
    ('Aston Villa', 'Arsenal'): 42000,            # [50 0L7]

    # Sunday 10 December 2023
    ('Luton', 'Man City'): 11047,                 # [51 0L7]
    ('Tottenham', 'Newcastle'): 61171,            # [52 0L7]
    ('Everton', 'Chelsea'): 39280,                # [53 0L6]
}

for idx, row in df[df['Season'] == '2324'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2324') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [206]:
df[df['Season'] == '2324'].isna().sum()[df[df['Season'] == '2324'].isna().sum() > 0]

Attendance                       74
XGHome                           14
XGAway                           15
SeasonPosAway                    19
SeasonPlayedAway                 19
SeasonWinAway                    19
SeasonDrawAway                   19
SeasonLossAway                   19
SeasonGFAway                     19
SeasonGAAway                     19
SeasonGDAway                     19
SeasonPointsAway                 19
QualificationOrRelegationAway    19
dtype: int64

In [207]:
df[(df['Season'] == '2324') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

             HomeTeam        AwayTeam  Year  Month  Day
11597       Sheffield         Everton  2023      9    2
11598       Brentford     Bournemouth  2023      9    2
11599        Man City          Fulham  2023      9    2
11600         Arsenal      Man United  2023      9    3
11601  Crystal Palace          Wolves  2023      9    3
11602       Liverpool     Aston Villa  2023      9    3
11603          Wolves       Liverpool  2023      9   16
11604     Aston Villa  Crystal Palace  2023      9   16
11605          Fulham           Luton  2023      9   16
11606      Man United        Brighton  2023      9   16
11607       Tottenham       Sheffield  2023      9   16
11608        West Ham        Man City  2023      9   16
11609       Newcastle       Brentford  2023      9   16
11610     Bournemouth         Chelsea  2023      9   17
11611         Everton         Arsenal  2023      9   17
11612      Nottingham         Burnley  2023      9   18
11613         Burnley      Man United  2023      9   23
11614       Brentford         Everton  2023      9   23
11615  Crystal Palace          Fulham  2023      9   23
11616           Luton          Wolves  2023      9   23
11617        Man City      Nottingham  2023      9   23
11618         Arsenal       Tottenham  2023      9   24
11619        Brighton     Bournemouth  2023      9   24
11620         Chelsea     Aston Villa  2023      9   24
11621       Liverpool        West Ham  2023      9   24
11622       Sheffield       Newcastle  2023      9   24
11623        West Ham       Sheffield  2023      9   30
11624       Tottenham       Liverpool  2023      9   30
11625       Newcastle         Burnley  2023      9   30
11626          Wolves        Man City  2023      9   30
11627         Everton           Luton  2023      9   30
11628     Bournemouth         Arsenal  2023      9   30
11629     Aston Villa        Brighton  2023      9   30
11630      Man United  Crystal Palace  2023      9   30
11632          Fulham         Chelsea  2023     10    2
11633           Luton         Burnley  2023     10    3
11634           Luton       Tottenham  2023     10    7
11635         Burnley         Chelsea  2023     10    7
11636         Everton     Bournemouth  2023     10    7
11637          Fulham       Sheffield  2023     10    7
11638      Man United       Brentford  2023     10    7
11639  Crystal Palace      Nottingham  2023     10    7
11640         Arsenal        Man City  2023     10    8
11641          Wolves     Aston Villa  2023     10    8
11642        West Ham       Newcastle  2023     10    8
11643        Brighton       Liverpool  2023     10    8
11644       Liverpool         Everton  2023     10   21
11645     Bournemouth          Wolves  2023     10   21
11646       Brentford         Burnley  2023     10   21
11647        Man City        Brighton  2023     10   21
11648       Newcastle  Crystal Palace  2023     10   21
11649      Nottingham           Luton  2023     10   21
11650         Chelsea         Arsenal  2023     10   21
11651       Sheffield      Man United  2023     10   21
11652     Aston Villa        West Ham  2023     10   22
11653       Tottenham          Fulham  2023     10   23
11654  Crystal Palace       Tottenham  2023     10   27
11655          Wolves       Newcastle  2023     10   28
11656     Bournemouth         Burnley  2023     10   28
11657         Chelsea       Brentford  2023     10   28
11658         Arsenal       Sheffield  2023     10   28
11659        West Ham         Everton  2023     10   29
11660     Aston Villa           Luton  2023     10   29
11661        Brighton          Fulham  2023     10   29
11662       Liverpool      Nottingham  2023     10   29
11663      Man United        Man City  2023     10   29
11665       Newcastle         Arsenal  2023     11    4
11666         Everton        Brighton  2023     11    4
11723          Fulham        West Ham  2023     12   10
11724      Nottingham       Tottenham  2023     12   15
11725         Chelsea       Sheffield  2023     12   16
11726        Man City  Crystal Palace  2023     12   16
11727       Newcastle          Fulham  2023     12   16
11728         Burnley         Everton  2023     12   16

In [ ]:
attendance_data = {
    # 2 September 2023
    ('Sheffield', 'Everton'): 31124,        # [0 0L7]
    ('Brentford', 'Bournemouth'): 16973,    # [1 0L6]
    ('Man City', 'Fulham'): 52899,          # [2 0L7]
    
    # 3 September 2023
    ('Arsenal', 'Man United'): 60192,       # [3 0L7]
    ('Crystal Palace', 'Wolves'): 24741,    # [4 0L8]
    ('Liverpool', 'Aston Villa'): 50109,    # [5 0L7]
    
    # 16 September 2023
    ('Wolves', 'Liverpool'): 31257,         # [6 0L6]
    ('Aston Villa', 'Crystal Palace'): 40809, # [7 0L6]
    ('Fulham', 'Luton'): 24467,             # [8 0L6]
    ('Man United', 'Brighton'): 73592,      # [9 0L7]
    ('Tottenham', 'Sheffield'): 61706,      # [10 0L8]
    ('West Ham', 'Man City'): 62475,        # [11 0L7]
    ('Newcastle', 'Brentford'): 51670,      # [12 0L7]
    
    # 17 September 2023
    ('Bournemouth', 'Chelsea'): 10421,      # [13 0L7]
    ('Everton', 'Arsenal'): 39217,          # [14 0L7]
    
    # 18 September 2023
    ('Nottingham', 'Burnley'): 28958,       # [15 0L7]
    
    # 23 September 2023
    ('Burnley', 'Man United'): 21593,       # [16 0L7]
    ('Brentford', 'Everton'): 16981,        # [17 0L7]
    ('Crystal Palace', 'Fulham'): 25072,    # [18 0L6]
    ('Luton', 'Wolves'): 10893,             # [19 0L6]
    ('Man City', 'Nottingham'): 53413,      # [20 0L8]
    
    # 24 September 2023
    ('Arsenal', 'Tottenham'): 60156,        # [21 0L7]
    ('Brighton', 'Bournemouth'): 31617,     # [22 0L8]
    ('Chelsea', 'Aston Villa'): 39700,      # [23 0L6]
    ('Liverpool', 'West Ham'): 50136,       # [24 0L7]
    ('Sheffield', 'Newcastle'): 30568,      # [25 0L7]
    
    # 30 September 2023
    ('West Ham', 'Sheffield'): 62459,       # [26 0L7]
    ('Tottenham', 'Liverpool'): 62001,      # [27 0L7]
    ('Newcastle', 'Burnley'): 52163,        # [28 0L9]
    ('Wolves', 'Man City'): 31415,          # [29 0L7]
    ('Everton', 'Luton'): 39289,            # [30 0L7]
    ('Bournemouth', 'Arsenal'): 11193,      # [31 0L7]
    ('Aston Villa', 'Brighton'): 40636,     # [32 0L7]
    ('Man United', 'Crystal Palace'): 73428, # [33 0L8]
    
    # 2 October 2023
    ('Fulham', 'Chelsea'): 24445,           # [34 0L7]
    
    # 3 October 2023
    ('Luton', 'Burnley'): 10918,            # [35 0L7]
    
    # 7 October 2023
    ('Luton', 'Tottenham'): 10929,          # [36 0L10]
    ('Burnley', 'Chelsea'): 21654,          # [37 0L6]
    ('Everton', 'Bournemouth'): 38815,      # [38 0L8]
    ('Fulham', 'Sheffield'): 24361,         # [39 0L6]
    ('Man United', 'Brentford'): 73453,     # [40 0L7]
    ('Crystal Palace', 'Nottingham'): 25017, # [41 0L8]
    
    # 8 October 2023
    ('Arsenal', 'Man City'): 60233,         # [42 0L7]
    ('Wolves', 'Aston Villa'): 31578,       # [43 0L7]
    ('West Ham', 'Newcastle'): 62473,       # [44 0L7]
    ('Brighton', 'Liverpool'): 31752,       # [45 0L8]
    
    # 21 October 2023
    ('Liverpool', 'Everton'): 50201,        # [46 0L7]
    ('Bournemouth', 'Wolves'): 11175,       # [47 0L8]
    ('Brentford', 'Burnley'): 17029,        # [48 0L7]
    ('Man City', 'Brighton'): 53466,        # [49 0L7]
    ('Newcastle', 'Crystal Palace'): 52189, # [50 0L8]
    ('Nottingham', 'Luton'): 29361,         # [51 0L6]
    ('Chelsea', 'Arsenal'): 39723,          # [52 0L6]
    ('Sheffield', 'Man United'): 31543,     # [53 0L9]
    
    # 22 October 2023
    ('Aston Villa', 'West Ham'): 41734,     # [54 0L7]
    
    # 23 October 2023
    ('Tottenham', 'Fulham'): 61286,         # [55 0L8]
    
    # 27 October 2023
    ('Crystal Palace', 'Tottenham'): 25074, # [56 0L8]
    
    # 28 October 2023
    ('Wolves', 'Newcastle'): 31584,         # [57 0L8]
    ('Bournemouth', 'Burnley'): 11152,      # [58 0L6]
    ('Chelsea', 'Brentford'): 39575,        # [59 0L7]
    ('Arsenal', 'Sheffield'): 60153,        # [60 0L7]
    
    # 29 October 2023
    ('West Ham', 'Everton'): 62469,         # [61 0L6]
    ('Aston Villa', 'Luton'): 41785,        # [62 0L7]
    ('Brighton', 'Fulham'): 31550,          # [63 0L8]
    ('Liverpool', 'Nottingham'): 50143,     # [64 0L7]
    ('Man United', 'Man City'): 73502,      # [65 0L8]
}
# Columns to fill
match_cols = ['Attendance']

# Loop through each row for the 2023-24 season
for idx, row in df[df['Season'] == '2324'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2324') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [209]:
df[df['Season'] == '2324'].isna().sum()[df[df['Season'] == '2324'].isna().sum() > 0]

Attendance                        8
XGHome                           14
XGAway                           15
SeasonPosAway                    19
SeasonPlayedAway                 19
SeasonWinAway                    19
SeasonDrawAway                   19
SeasonLossAway                   19
SeasonGFAway                     19
SeasonGAAway                     19
SeasonGDAway                     19
SeasonPointsAway                 19
QualificationOrRelegationAway    19
dtype: int64

In [210]:
df[(df['Season'] == '2324') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

         HomeTeam        AwayTeam  Year  Month  Day
11665   Newcastle         Arsenal  2023     11    4
11666     Everton        Brighton  2023     11    4
11723      Fulham        West Ham  2023     12   10
11724  Nottingham       Tottenham  2023     12   15
11725     Chelsea       Sheffield  2023     12   16
11726    Man City  Crystal Palace  2023     12   16
11727   Newcastle          Fulham  2023     12   16
11728     Burnley         Everton  2023     12   16

In [211]:
# Attendance data for the specified matches
attendance_data = {
    ('Newcastle', 'Arsenal'): 52194,
    ('Everton', 'Brighton'): 38683,
    ('Fulham', 'West Ham'): 23988,
    ('Nottingham', 'Tottenham'): 29296,
    ('Chelsea', 'Sheffield'): 39599,
    ('Man City', 'Crystal Palace'): 53112,
    ('Newcastle', 'Fulham'): 52055,
    ('Burnley', 'Everton'): 21413,
}

# Loop through each row for the 2023-24 season and fill the Attendance column
for idx, row in df[df['Season'] == '2324'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2324') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [212]:
df[df['Season'] == '2324'].isna().sum()[df[df['Season'] == '2324'].isna().sum() > 0]

XGHome                           14
XGAway                           15
SeasonPosAway                    19
SeasonPlayedAway                 19
SeasonWinAway                    19
SeasonDrawAway                   19
SeasonLossAway                   19
SeasonGFAway                     19
SeasonGAAway                     19
SeasonGDAway                     19
SeasonPointsAway                 19
QualificationOrRelegationAway    19
dtype: int64

In [ ]:
df[(df['Season'] == '2324') & (df['QualificationOrRelegationAway'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

             HomeTeam  AwayTeam  Year  Month  Day
11577          Wolves  Brighton  2023      8   19
11606      Man United  Brighton  2023      9   16
11629     Aston Villa  Brighton  2023      9   30
11647        Man City  Brighton  2023     10   21
11666         Everton  Brighton  2023     11    4
11688      Nottingham  Brighton  2023     11   25
11700         Chelsea  Brighton  2023     12    3
11729         Arsenal  Brighton  2023     12   17
11733  Crystal Palace  Brighton  2023     12   21
11761        West Ham  Brighton  2024      1    2
11776           Luton  Brighton  2024      1   30
11793       Tottenham  Brighton  2024      2   10
11810       Sheffield  Brighton  2024      2   18
11824          Fulham  Brighton  2024      3    2
11855       Liverpool  Brighton  2024      3   31
11862       Brentford  Brighton  2024      4    3
11880         Burnley  Brighton  2024      4   13
11909     Bournemouth  Brighton  2024      4   28
11925       Newcastle  Brighton  2024      5   11

In [214]:
df.loc[
    (df['Season'] == '2324') & (df['AwayTeam'] == 'Brighton'),
    [
        'SeasonPosAway', 'SeasonPlayedAway', 'SeasonWinAway', 'SeasonDrawAway',
        'SeasonLossAway', 'SeasonGFAway', 'SeasonGAAway', 'SeasonGDAway',
        'SeasonPointsAway', 'QualificationOrRelegationAway'
    ]
] = [
    11,   # SeasonPosAway
    38,   # SeasonPlayedAway
    12,   # SeasonWinAway
    12,   # SeasonDrawAway
    14,   # SeasonLossAway
    55,   # SeasonGFAway
    62,   # SeasonGAAway
    -7,   # SeasonGDAway 
    48,   # SeasonPointsAway
    'Not Applicable'  # QualificationOrRelegationAway
]

In [215]:
df[df['Season'] == '2324'].isna().sum()[df[df['Season'] == '2324'].isna().sum() > 0]

XGHome    14
XGAway    15
dtype: int64

In [ ]:
df[(df['Season'] == '2324') & (df['XGHome'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

             HomeTeam     AwayTeam  Year  Month  Day
11566         Arsenal   Nottingham  2023      8   12
11631      Nottingham    Brentford  2023     10    1
11664       Sheffield       Wolves  2023     11    4
11691       Tottenham  Aston Villa  2023     11   26
11706     Aston Villa     Man City  2023     12    6
11790         Arsenal    Liverpool  2024      2    4
11803         Burnley      Arsenal  2024      2   17
11814     Bournemouth     Man City  2024      2   24
11832      Man United      Everton  2024      3    9
11833     Bournemouth    Sheffield  2024      3    9
11841         Chelsea    Newcastle  2024      3   11
11886         Chelsea      Everton  2024      4   15
11920  Crystal Palace   Man United  2024      5    6
11931       Tottenham     Man City  2024      5   14

In [217]:
df[(df['Season'] == '2324') & (df['XGAway'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

             HomeTeam     AwayTeam  Year  Month  Day
11566         Arsenal   Nottingham  2023      8   12
11631      Nottingham    Brentford  2023     10    1
11664       Sheffield       Wolves  2023     11    4
11691       Tottenham  Aston Villa  2023     11   26
11706     Aston Villa     Man City  2023     12    6
11790         Arsenal    Liverpool  2024      2    4
11803         Burnley      Arsenal  2024      2   17
11814     Bournemouth     Man City  2024      2   24
11832      Man United      Everton  2024      3    9
11833     Bournemouth    Sheffield  2024      3    9
11841         Chelsea    Newcastle  2024      3   11
11886         Chelsea      Everton  2024      4   15
11920  Crystal Palace   Man United  2024      5    6
11931       Tottenham     Man City  2024      5   14
11938           Luton       Fulham  2024      5   19

In [ ]:
df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Nottingham'),
    ['XGHome', 'XGAway']
] = [0.84, 1.18]  # منبع: StatMuse   0]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Nottingham') & (df['AwayTeam'] == 'Brentford'),
    ['XGHome', 'XGAway']
] = [0.47, 1.66]  # منبع: StatMuse   1]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Sheffield') & (df['AwayTeam'] == 'Wolves'),
    ['XGHome', 'XGAway']
] = [1.0, 1.2]  # منبع: FBref   2]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Aston Villa'),
    ['XGHome', 'XGAway']
] = [2.44, 1.76]  # منبع: StatMuse   3]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Man City'),
    ['XGHome', 'XGAway']
] = [2.38, 0.65]  # منبع: bamdascore.com   4]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Liverpool'),
    ['XGHome', 'XGAway']
] = [3.5, 0.37]  # منبع: The Athletic   5]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Burnley') & (df['AwayTeam'] == 'Arsenal'),
    ['XGHome', 'XGAway']
] = [0.3, 2.3]  # منبع: FBref   6]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Bournemouth') & (df['AwayTeam'] == 'Man City'),
    ['XGHome', 'XGAway']
] = [0.88, 1.57]  # منبع: score366.com   7]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Everton'),
    ['XGHome', 'XGAway']
] = [2.72, 1.61]  # منبع: The Athletic   8]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Bournemouth') & (df['AwayTeam'] == 'Sheffield'),
    ['XGHome', 'XGAway']
] = [3.35, 1.25]  # منبع: The Athletic   9]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Newcastle'),
    ['XGHome', 'XGAway']
] = [1.57, 0.74]  # منبع: The Athletic   10]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Everton'),
    ['XGHome', 'XGAway']
] = [3.1, 1.5]  # منبع: FBref   11]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Man United'),
    ['XGHome', 'XGAway']
] = [1.75, 0.35]  # منبع: The Athletic   12]

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Tottenham') & (df['AwayTeam'] == 'Man City'),
    ['XGHome', 'XGAway']
] = [1.66, 2.39]  # statemuse

df.loc[
    (df['Season'] == '2324') & (df['HomeTeam'] == 'Luton') & (df['AwayTeam'] == 'Fulham'),
    ['XGHome', 'XGAway']
] = [2.11, 1.11]   # statemuse

In [220]:
df[df['Season'] == '2324'].isna().sum()[df[df['Season'] == '2324'].isna().sum() > 0]

Series([], dtype: int64)

In [222]:
df.to_csv("Data/Data4.csv", index=False)

---

In [224]:
df[df['Season'] == '2122'].isna().sum()[df[df['Season'] == '2122'].isna().sum() > 0]

WeekDay        14
Time           14
Round          14
Attendance    340
XGHome         14
XGAway         14
dtype: int64

In [225]:
df[(df['Season'] == '2122') & (df['XGAway'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

             HomeTeam        AwayTeam  Year  Month  Day
10806         Norwich       Liverpool  2021      8   14
10809         Chelsea  Crystal Palace  2021      8   14
10830        Brighton         Everton  2021      8   28
10859      Man United     Aston Villa  2021      9   25
10910         Arsenal         Watford  2021     11    7
10925       Liverpool     Southampton  2021     11   27
11022        Man City       Brentford  2022      2    9
11041     Aston Villa         Watford  2022      2   19
11084  Crystal Palace        Man City  2022      3   14
11089     Aston Villa         Arsenal  2022      3   19
11106     Southampton         Chelsea  2022      4    9
11119       Liverpool      Man United  2022      4   19
11132         Chelsea        West Ham  2022      4   24
11183         Norwich       Tottenham  2022      5   22

In [ ]:
# ============================================================
# Norwich vs Liverpool - 14 August 2021
# منبع: FBref [6 0L26-L33][7 0L22-L31]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Liverpool'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Sat', '21:00', 1, 1.4, 1.6]

# ============================================================
# Chelsea vs Crystal Palace - 14 August 2021
# منبع: FBref [1 0L7-L9][1 0L12-L14]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'Crystal Palace'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Sat', '18:30', 1, 0.7, 0.2]

# ============================================================
# Brighton vs Everton - 28 August 2021
# منبع: FBref [8 0L15-L16]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Brighton') & (df['AwayTeam'] == 'Everton'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Sat', '18:30', 3, 0.7, 1.4]

# ============================================================
# Man United vs Aston Villa - 25 September 2021
# منبع: MUFC Wiki [3 0L6-L7], FBref [9 0L6-L7]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Aston Villa'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Sat', '23:00', 6, 2.2, 1.0]

# ============================================================
# Arsenal vs Watford - 7 November 2021
# منبع: The Athletic [10 0L3-L4]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Arsenal') & (df['AwayTeam'] == 'Watford'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Sun', '17:30', 11, 1.94, 0.88]

# ============================================================
# Liverpool vs Southampton - 27 November 2021
# منبع: StatMuse [11 0L10], The Athletic [5 0L12]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Southampton'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Sat', '18:30', 13, 2.96, 1.07]

# ============================================================
# Man City vs Brentford - 9 February 2022
# منبع: FBref [12 0L16-L18]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Man City') & (df['AwayTeam'] == 'Brentford'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Wed', '23:15', 24, 1.9, 0.4]

# ============================================================
# Aston Villa vs Watford - 19 February 2022
# منبع: FBref [13 0L17-L19]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Watford'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Sat', '18:30', 26, 1.3, 1.2]

# ============================================================
# Crystal Palace vs Man City - 14 March 2022
# منبع: FBref [14 0L15-L16], The Guardian [14 0L7]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Crystal Palace') & (df['AwayTeam'] == 'Man City'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Mon', '23:30', 29, 0.6, 2.8]

# ============================================================
# Aston Villa vs Arsenal - 19 March 2022
# منبع: FBref [15 0L27-L29]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Aston Villa') & (df['AwayTeam'] == 'Arsenal'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Sat', '16:00', 30, 0.5, 1.3]

# ============================================================
# Southampton vs Chelsea - 9 April 2022
# منبع: FBref [16 0L7-L8]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Southampton') & (df['AwayTeam'] == 'Chelsea'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Sat', '18:30', 32, 0.5, 4.2]

# ============================================================
# Liverpool vs Man United - 19 April 2022
# منبع: FBref [17 0L32-L34]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Man United'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Tue', '23:30', 33, 2.0, 0.1]

# ============================================================
# Chelsea vs West Ham - 24 April 2022
# منبع: FBref [18 0L7-L8]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Chelsea') & (df['AwayTeam'] == 'West Ham'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Sun', '17:30', 34, 3.0, 0.5]

# ============================================================
# Norwich vs Tottenham - 22 May 2022
# منبع: The Athletic [19 0L6-L7], FBref [19 0L10-L12]
# ============================================================
df.loc[
    (df['Season'] == '2122') & (df['HomeTeam'] == 'Norwich') & (df['AwayTeam'] == 'Tottenham'),
    ['WeekDay', 'Time', 'Round', 'XGHome', 'XGAway']
] = ['Sun', '19:30', 38, 0.5, 3.4]

In [228]:
df[df['Season'] == '2122'].isna().sum()[df[df['Season'] == '2122'].isna().sum() > 0]

Attendance    340
dtype: int64

In [229]:
df[(df['Season'] == '2122') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']][:100]

             HomeTeam        AwayTeam  Year  Month  Day
10804       Brentford         Arsenal  2021      8   13
10805         Watford     Aston Villa  2021      8   14
10806         Norwich       Liverpool  2021      8   14
10807       Leicester          Wolves  2021      8   14
10808      Man United           Leeds  2021      8   14
10809         Chelsea  Crystal Palace  2021      8   14
10810         Everton     Southampton  2021      8   14
10811         Burnley        Brighton  2021      8   14
10812       Newcastle        West Ham  2021      8   15
10813       Tottenham        Man City  2021      8   15
10814       Liverpool         Burnley  2021      8   21
10815     Aston Villa       Newcastle  2021      8   21
10816  Crystal Palace       Brentford  2021      8   21
10817        Man City         Norwich  2021      8   21
10818        Brighton         Watford  2021      8   21
10819           Leeds         Everton  2021      8   21
10820     Southampton      Man United  2021      8   22
10821          Wolves       Tottenham  2021      8   22
10822         Arsenal         Chelsea  2021      8   22
10823        West Ham       Leicester  2021      8   23
10824       Liverpool         Chelsea  2021      8   28
10825         Norwich       Leicester  2021      8   28
10826        West Ham  Crystal Palace  2021      8   28
10827       Newcastle     Southampton  2021      8   28
10828     Aston Villa       Brentford  2021      8   28
10829        Man City         Arsenal  2021      8   28
10830        Brighton         Everton  2021      8   28
10831         Burnley           Leeds  2021      8   29
10832       Tottenham         Watford  2021      8   29
10833          Wolves      Man United  2021      8   29
10834         Chelsea     Aston Villa  2021      9   11
10835         Watford          Wolves  2021      9   11
10836     Southampton        West Ham  2021      9   11
10837      Man United       Newcastle  2021      9   11
10838       Leicester        Man City  2021      9   11
10839         Arsenal         Norwich  2021      9   11
10840  Crystal Palace       Tottenham  2021      9   11
10841       Brentford        Brighton  2021      9   11
10842           Leeds       Liverpool  2021      9   12
10843         Everton         Burnley  2021      9   13
10844       Newcastle           Leeds  2021      9   17
10845     Aston Villa         Everton  2021      9   18
10846         Norwich         Watford  2021      9   18
10847        Man City     Southampton  2021      9   18
10848       Liverpool  Crystal Palace  2021      9   18
10849         Burnley         Arsenal  2021      9   18
10850          Wolves       Brentford  2021      9   18
10851        Brighton       Leicester  2021      9   19
10852        West Ham      Man United  2021      9   19
10853       Tottenham         Chelsea  2021      9   19
10854       Brentford       Liverpool  2021      9   25
10855         Watford       Newcastle  2021      9   25
10856       Leicester         Burnley  2021      9   25
10857           Leeds        West Ham  2021      9   25
10858         Everton         Norwich  2021      9   25
10859      Man United     Aston Villa  2021      9   25
10860         Chelsea        Man City  2021      9   25
10861     Southampton          Wolves  2021      9   26
10862         Arsenal       Tottenham  2021      9   26
10863  Crystal Palace        Brighton  2021      9   27
10864        Brighton         Arsenal  2021     10    2
10865          Wolves       Newcastle  2021     10    2
10866           Leeds         Watford  2021     10    2
10867         Chelsea     Southampton  2021     10    2
10868         Burnley         Norwich  2021     10    2
10869      Man United         Everton  2021     10    2
10870  Crystal Palace       Leicester  2021     10    3
10871       Tottenham     Aston Villa  2021     10    3
10872        West Ham       Brentford  2021     10    3
10873       Liverpool        Man City  2021     10    3
10874       Brentford         Chelsea  2021     10   16
10875     Southampton           Leeds  2021     10   16
10876         Norwich        Brighton  2021     10   16
10877       Leicester      Man United  2021     10   16
10878     Aston Villa          Wolves  2021     10   16
10879         Watford       Liverpool  2021     10   16
10880        Man City         Burnley  2021     10   16
10881         Everton        West Ham  2021     10   17
10882       Newcastle       Tottenham  2021     10   17
10883         Arsenal  Crystal Palace  2021     10   18
10884         Arsenal     Aston Villa  2021     10   22
10885        Brighton        Man City  2021     10   23
10886     Southampton         Burnley  2021     10   23
10887           Leeds          Wolves  2021     10   23
10888         Everton         Watford  2021     10   23
10889  Crystal Palace       Newcastle  2021     10   23
10890         Chelsea         Norwich  2021     10   23
10891       Brentford       Leicester  2021     10   24
10892        West Ham       Tottenham  2021     10   24
10893      Man United       Liverpool  2021     10   24
10894       Tottenham      Man United  2021     10   30
10895         Watford     Southampton  2021     10   30
10896       Newcastle         Chelsea  2021     10   30
10897        Man City  Crystal Palace  2021     10   30
10898       Liverpool        Brighton  2021     10   30
10899         Burnley       Brentford  2021     10   30
10900       Leicester         Arsenal  2021     10   30
10901         Norwich           Leeds  2021     10   31
10902     Aston Villa        West Ham  2021     10   31
10903          Wolves         Everton  2021     11    1

In [ ]:
attendance_data = {
    # 13 August 2021
    ('Brentford', 'Arsenal'): 16479,             # [6 0L11]
    # 14 August 2021
    ('Watford', 'Aston Villa'): 20051,           # [6 0L19]
    ('Norwich', 'Liverpool'): 27023,             # [6 0L22-L23]
    ('Leicester', 'Wolves'): 31983,              # [6 0L14-L15]
    ('Man United', 'Leeds'): 72732,              # [6 0L13]
    ('Chelsea', 'Crystal Palace'): 38965,        # [6 0L17-L18]
    ('Everton', 'Southampton'): 38487,           # [6 0L21]
    ('Burnley', 'Brighton'): 16910,              # [6 0L16]
    # 15 August 2021
    ('Newcastle', 'West Ham'): 50673,            # [6 0L24]
    ('Tottenham', 'Man City'): 58262,            # [6 0L26]
    # 21 August 2021
    ('Liverpool', 'Burnley'): 52591,             # [6 0L27-L28]
    ('Aston Villa', 'Newcastle'): 41964,         # [6 0L29]
    ('Crystal Palace', 'Brentford'): 23091,      # [22 0L7-L8]
    ('Man City', 'Norwich'): 51437,              # [23 0L19]
    ('Brighton', 'Watford'): 29485,              # [24 0L7]
    ('Leeds', 'Everton'): 36293,                 # [6 0L32]
    # 22 August 2021
    ('Southampton', 'Man United'): 32000,        # [26 0L7-L8]
    ('Wolves', 'Tottenham'): 30368,              # [27 0L24]
    ('Arsenal', 'Chelsea'): 58729,               # [28 0L6-L7]
    # 23 August 2021
    ('West Ham', 'Leicester'): 59901,            # [29 0L7]
    # 28 August 2021
    ('Liverpool', 'Chelsea'): 54000,             # [30 0L7]
    ('Norwich', 'Leicester'): 26765,             # [31 0L9]
    ('West Ham', 'Crystal Palace'): 59751,       # [32 0L7-L8]
    ('Newcastle', 'Southampton'): 44017,         # [33 0L8]
    ('Aston Villa', 'Brentford'): 42045,         # [34 0L7]
    ('Brighton', 'Everton'): 29685,              # [8 0L24]
    # 29 August 2021
    ('Burnley', 'Leeds'): 20000,                 # [36 0L10]
    ('Tottenham', 'Watford'): 57500,             # [37 0L8]
    ('Wolves', 'Man United'): 30621,             # [38 0L6-L7]
    # 11 September 2021
    ('Chelsea', 'Aston Villa'): 39969,           # [39 0L7]
    ('Watford', 'Wolves'): 20019,                # [40 0L29]
    ('Southampton', 'West Ham'): 27861,          # [41 0L34]
    ('Man United', 'Newcastle'): 72732,          # [42 0L6]
    ('Leicester', 'Man City'): 32087,            # [43 0L16]
    ('Arsenal', 'Norwich'): 58000,               # [44 0L9]
    ('Crystal Palace', 'Tottenham'): 26000,      # [45 0L7]
    ('Brentford', 'Brighton'): 16518,            # [46 0L8]
    # 12 September 2021
    ('Leeds', 'Liverpool'): 36507,               # [47 0L7]
    # 13 September 2021
    ('Everton', 'Burnley'): 30000,               # [48 0L7]
    # 17 September 2021
    ('Newcastle', 'Leeds'): 50000,               # [49 0L7]
    # 18 September 2021
    ('Aston Villa', 'Everton'): 41888,           # [50 0L5]
    ('Norwich', 'Watford'): 26649,               # [51 0L7]
    ('Man City', 'Southampton'): 51000,          # [52 0L7]
    ('Liverpool', 'Crystal Palace'): 52000,      # [53 0L7]
    ('Burnley', 'Arsenal'): 21000,               # [54 0L7]
    ('Wolves', 'Brentford'): 30000,              # [55 0L26]
    # 19 September 2021
    ('Brighton', 'Leicester'): 31078,            # [56 0L8]
    ('West Ham', 'Man United'): 59958,           # [57 0L7]
    ('Tottenham', 'Chelsea'): 60059,             # [58 0L7]
    # 25 September 2021
    ('Brentford', 'Liverpool'): 16876,           # [59 0L8]
    ('Watford', 'Newcastle'): 20000,             # [60 0L19]
    ('Leicester', 'Burnley'): 31650,             # [61 0L7]
    ('Leeds', 'West Ham'): 36417,                # [62 0L7]
    ('Everton', 'Norwich'): 38821,               # [63 0L7]
    ('Man United', 'Aston Villa'): 73000,        # [0 0L6]
    ('Chelsea', 'Man City'): 40036,              # [64 0L22]
    # 26 September 2021
    ('Southampton', 'Wolves'): 28002,            # [65 0L9]
    ('Arsenal', 'Tottenham'): 59919,             # [66 0L8]
    # 27 September 2021
    ('Crystal Palace', 'Brighton'): 22975,       # [67 0L8]
    # 2 October 2021
    ('Brighton', 'Arsenal'): 31266,              # [68 0L5]
}

for idx, row in df[df['Season'] == '2122'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2122') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [230]:
df[(df['Season'] == '2122') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']][100:200]

             HomeTeam        AwayTeam  Year  Month  Day
10904     Southampton     Aston Villa  2021     11    5
10905        Brighton       Newcastle  2021     11    6
10906  Crystal Palace          Wolves  2021     11    6
10907       Brentford         Norwich  2021     11    6
10908      Man United        Man City  2021     11    6
10909         Chelsea         Burnley  2021     11    6
10910         Arsenal         Watford  2021     11    7
10911         Everton       Tottenham  2021     11    7
10912           Leeds       Leicester  2021     11    7
10913        West Ham       Liverpool  2021     11    7
10914         Burnley  Crystal Palace  2021     11   20
10915       Leicester         Chelsea  2021     11   20
10916     Aston Villa        Brighton  2021     11   20
10917       Newcastle       Brentford  2021     11   20
10918         Norwich     Southampton  2021     11   20
10919         Watford      Man United  2021     11   20
10920          Wolves        West Ham  2021     11   20
10921       Liverpool         Arsenal  2021     11   20
10922        Man City         Everton  2021     11   21
10923       Tottenham           Leeds  2021     11   21
10924         Norwich          Wolves  2021     11   27
10925       Liverpool     Southampton  2021     11   27
10926        Brighton           Leeds  2021     11   27
10927         Arsenal       Newcastle  2021     11   27
10928  Crystal Palace     Aston Villa  2021     11   27
10929       Leicester         Watford  2021     11   28
10930        Man City        West Ham  2021     11   28
10931       Brentford         Everton  2021     11   28
10932         Chelsea      Man United  2021     11   28
10933       Newcastle         Norwich  2021     11   30
10934           Leeds  Crystal Palace  2021     11   30
10935         Watford         Chelsea  2021     12    1
10936     Southampton       Leicester  2021     12    1
10937        West Ham        Brighton  2021     12    1
10938          Wolves         Burnley  2021     12    1
10939     Aston Villa        Man City  2021     12    1
10940         Everton       Liverpool  2021     12    1
10941       Tottenham       Brentford  2021     12    2
10942      Man United         Arsenal  2021     12    2
10943        West Ham         Chelsea  2021     12    4
10944       Newcastle         Burnley  2021     12    4
10945     Southampton        Brighton  2021     12    4
10946          Wolves       Liverpool  2021     12    4
10947         Watford        Man City  2021     12    4
10948       Tottenham         Norwich  2021     12    5
10949     Aston Villa       Leicester  2021     12    5
10950           Leeds       Brentford  2021     12    5
10951      Man United  Crystal Palace  2021     12    5
10952         Everton         Arsenal  2021     12    6
10953       Brentford         Watford  2021     12   10
10954        Man City          Wolves  2021     12   11
10955         Arsenal     Southampton  2021     12   11
10956         Chelsea           Leeds  2021     12   11
10957       Liverpool     Aston Villa  2021     12   11
10958         Norwich      Man United  2021     12   11
10959         Burnley        West Ham  2021     12   12
10960       Leicester       Newcastle  2021     12   12
10961  Crystal Palace         Everton  2021     12   12
10962        Man City           Leeds  2021     12   14
10963         Norwich     Aston Villa  2021     12   14
10964         Arsenal        West Ham  2021     12   15
10965        Brighton          Wolves  2021     12   15
10966  Crystal Palace     Southampton  2021     12   15
10967         Chelsea         Everton  2021     12   16
10968       Liverpool       Newcastle  2021     12   16
10969           Leeds         Arsenal  2021     12   18
10970       Newcastle        Man City  2021     12   19
10971          Wolves         Chelsea  2021     12   19
10972       Tottenham       Liverpool  2021     12   19
10973        Brighton       Brentford  2021     12   26
10974     Aston Villa         Chelsea  2021     12   26
10975        West Ham     Southampton  2021     12   26
10976         Norwich         Arsenal  2021     12   26
10977        Man City       Leicester  2021     12   26
10978       Tottenham  Crystal Palace  2021     12   26
10979       Newcastle      Man United  2021     12   27
10980  Crystal Palace         Norwich  2021     12   28
10981     Southampton       Tottenham  2021     12   28
10982         Watford        West Ham  2021     12   28
10983       Leicester       Liverpool  2021     12   28
10984         Chelsea        Brighton  2021     12   29
10985       Brentford        Man City  2021     12   29
10986      Man United         Burnley  2021     12   30
10987         Watford       Tottenham  2022      1    1
10988  Crystal Palace        West Ham  2022      1    1
10989         Arsenal        Man City  2022      1    1
10990           Leeds         Burnley  2022      1    2
10991         Chelsea       Liverpool  2022      1    2
10992       Brentford     Aston Villa  2022      1    2
10993         Everton        Brighton  2022      1    2
10994      Man United          Wolves  2022      1    3
10995     Southampton       Brentford  2022      1   11
10996        West Ham         Norwich  2022      1   12
10997        Brighton  Crystal Palace  2022      1   14
10998        Man City         Chelsea  2022      1   15
10999       Newcastle         Watford  2022      1   15
11000         Norwich         Everton  2022      1   15
11001          Wolves     Southampton  2022      1   15
11002     Aston Villa      Man United  2022      1   15
11003       Liverpool       Brentford  2022      1   16

In [ ]:
attendance_data = {
    # --- Matches from 2022-01-16 to 2022-01-23 ---
    ('West Ham', 'Leeds'): 59951,           # 2022-01-16   0]  1]
    ('Brighton', 'Chelsea'): 30880,         # 2022-01-18   2]
    ('Leicester', 'Tottenham'): 31986,      # 2022-01-19   3]
    ('Brentford', 'Man United'): 17094,     # 2022-01-19   4]
    ('Man United', 'West Ham'): 73130,      # 2022-01-22   5]
    ('Southampton', 'Man City'): 31178,     # 2022-01-22   6]
    ('Arsenal', 'Burnley'): 59255,          # 2022-01-23   7]
    ('Crystal Palace', 'Liverpool'): 25002, # 2022-01-23   8]
    ('Leicester', 'Brighton'): 31231,       # 2022-01-23   9]
    ('Chelsea', 'Tottenham'): 40020,        # 2022-01-23   10]

    # --- Matches from 2022-02-05 to 2022-02-13 ---
    ('Burnley', 'Watford'): 19527,          # 2022-02-05   11]  12]
    ('Burnley', 'Man United'): 21233,       # 2022-02-08   13]
    ('West Ham', 'Watford'): 59581,         # 2022-02-08   14]  15]
    ('Newcastle', 'Everton'): 52186,        # 2022-02-08   16]
    ('Man City', 'Brentford'): 51658,       # 2022-02-09   17]
    ('Newcastle', 'Aston Villa'): 52207,    # 2022-02-13   18]
    ('Leicester', 'West Ham'): 32061,       # 2022-02-13   19]
    ('Burnley', 'Liverpool'): 19563,        # 2022-02-13   20]
    ('Tottenham', 'Wolves'): 56452,         # 2022-02-13   21]

    # --- Matches from 2022-02-15 to 2022-02-20 ---
    ('Man United', 'Brighton'): 73012,      # 2022-02-15   22]
    ('Southampton', 'Everton'): 31312,      # 2022-02-19   23]
    ('West Ham', 'Newcastle'): 59949,       # 2022-02-19   24]
    ('Arsenal', 'Brentford'): 59249,        # 2022-02-19   25]
    ('Aston Villa', 'Watford'): 41936,      # 2022-02-19   26]
    ('Wolves', 'Leicester'): 31587,         # 2022-02-20   27]
    ('Leeds', 'Man United'): 36715,         # 2022-02-20   28]

    # --- Matches from 2022-03-05 to 2022-03-13 ---
    ('Wolves', 'Crystal Palace'): 31395,    # 2022-03-05   29]
    ('Norwich', 'Brentford'): 26887,        # 2022-03-05   30]
    ('Aston Villa', 'Southampton'): 41855,  # 2022-03-05   31]
    ('Burnley', 'Chelsea'): 19439,          # 2022-03-05   32]
    ('Leicester', 'Leeds'): 32236,          # 2022-03-05   33]
    ('Newcastle', 'Brighton'): 52214,       # 2022-03-05   34]
    ('Watford', 'Arsenal'): 21142,          # 2022-03-06   35]
    ('Man City', 'Man United'): 53165,      # 2022-03-06   36]  37]
        # ------------------------------ November 2021 ------------------------------
    # 5 November 2021
    ('Southampton', 'Aston Villa'): 30178,          # Source: ESPN [25 0L12-L13]
        # 16 January 2022
    ('Liverpool', 'Brentford'): 52824,              # Source: FBref [4 0L5]
}

# --- Update the DataFrame ---
for idx, row in df[df['Season'] == '2122'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    if (home, away) in attendance_data and attendance_data[(home, away)] is not None:
        df.loc[(df['Season'] == '2122') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [236]:
df[(df['Season'] == '2122') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']][:75]

             HomeTeam        AwayTeam  Year  Month  Day
10829        Man City         Arsenal  2021      8   28
10865          Wolves       Newcastle  2021     10    2
10866           Leeds         Watford  2021     10    2
10867         Chelsea     Southampton  2021     10    2
10868         Burnley         Norwich  2021     10    2
10869      Man United         Everton  2021     10    2
10870  Crystal Palace       Leicester  2021     10    3
10871       Tottenham     Aston Villa  2021     10    3
10872        West Ham       Brentford  2021     10    3
10873       Liverpool        Man City  2021     10    3
10874       Brentford         Chelsea  2021     10   16
10875     Southampton           Leeds  2021     10   16
10876         Norwich        Brighton  2021     10   16
10877       Leicester      Man United  2021     10   16
10878     Aston Villa          Wolves  2021     10   16
10879         Watford       Liverpool  2021     10   16
10880        Man City         Burnley  2021     10   16
10881         Everton        West Ham  2021     10   17
10882       Newcastle       Tottenham  2021     10   17
10883         Arsenal  Crystal Palace  2021     10   18
10884         Arsenal     Aston Villa  2021     10   22
10885        Brighton        Man City  2021     10   23
10886     Southampton         Burnley  2021     10   23
10887           Leeds          Wolves  2021     10   23
10888         Everton         Watford  2021     10   23
10889  Crystal Palace       Newcastle  2021     10   23
10890         Chelsea         Norwich  2021     10   23
10891       Brentford       Leicester  2021     10   24
10892        West Ham       Tottenham  2021     10   24
10893      Man United       Liverpool  2021     10   24
10894       Tottenham      Man United  2021     10   30
10895         Watford     Southampton  2021     10   30
10896       Newcastle         Chelsea  2021     10   30
10897        Man City  Crystal Palace  2021     10   30
10898       Liverpool        Brighton  2021     10   30
10899         Burnley       Brentford  2021     10   30
10900       Leicester         Arsenal  2021     10   30
10901         Norwich           Leeds  2021     10   31
10902     Aston Villa        West Ham  2021     10   31
10903          Wolves         Everton  2021     11    1
10905        Brighton       Newcastle  2021     11    6
10906  Crystal Palace          Wolves  2021     11    6
10907       Brentford         Norwich  2021     11    6
10908      Man United        Man City  2021     11    6
10909         Chelsea         Burnley  2021     11    6
10910         Arsenal         Watford  2021     11    7
10911         Everton       Tottenham  2021     11    7
10912           Leeds       Leicester  2021     11    7
10913        West Ham       Liverpool  2021     11    7
10914         Burnley  Crystal Palace  2021     11   20
10915       Leicester         Chelsea  2021     11   20
10916     Aston Villa        Brighton  2021     11   20
10917       Newcastle       Brentford  2021     11   20
10918         Norwich     Southampton  2021     11   20
10919         Watford      Man United  2021     11   20
10920          Wolves        West Ham  2021     11   20
10921       Liverpool         Arsenal  2021     11   20
10922        Man City         Everton  2021     11   21
10923       Tottenham           Leeds  2021     11   21
10924         Norwich          Wolves  2021     11   27
10925       Liverpool     Southampton  2021     11   27
10926        Brighton           Leeds  2021     11   27
10927         Arsenal       Newcastle  2021     11   27
10928  Crystal Palace     Aston Villa  2021     11   27
10929       Leicester         Watford  2021     11   28
10930        Man City        West Ham  2021     11   28
10931       Brentford         Everton  2021     11   28
10932         Chelsea      Man United  2021     11   28
10933       Newcastle         Norwich  2021     11   30
10934           Leeds  Crystal Palace  2021     11   30
10935         Watford         Chelsea  2021     12    1
10936     Southampton       Leicester  2021     12    1
10937        West Ham        Brighton  2021     12    1
10938          Wolves         Burnley  2021     12    1
10939     Aston Villa        Man City  2021     12    1

In [ ]:
attendance_data = {
    # ------------------------------ August 2021 ------------------------------
    # 28 August 2021
    ('Man City', 'Arsenal'): 51437,          # [23 0L19]

    # ------------------------------ October 2021 ------------------------------
    # 2 October 2021
    ('Wolves', 'Newcastle'): 30362,          # [27 0L24]
    ('Leeds', 'Watford'): 36245,             # [32 0L7]
    ('Chelsea', 'Southampton'): 39797,       # [39 0L7]
    ('Burnley', 'Norwich'): 19763,           # [40 0L29]
    ('Man United', 'Everton'): 73000,        # [0 0L6]

    # 3 October 2021
    ('Crystal Palace', 'Leicester'): 24016,  # [41 0L34]
    ('Tottenham', 'Aston Villa'): 57000,     # [42 0L6]
    ('West Ham', 'Brentford'): 59944,        # [57 0L7]
    ('Liverpool', 'Man City'): 53000,        # [43 0L16]

    # 16 October 2021
    ('Brentford', 'Chelsea'): 16965,         # [59 0L8]
    ('Southampton', 'Leeds'): 30000,         # [60 0L19]
    ('Norwich', 'Brighton'): 26655,          # [61 0L7]
    ('Leicester', 'Man United'): 32220,      # [43 0L16]
    ('Aston Villa', 'Wolves'): 41880,        # [62 0L7]
    ('Watford', 'Liverpool'): 20100,         # [63 0L7]
    ('Man City', 'Burnley'): 52900,          # [64 0L22]

    # 17 October 2021
    ('Everton', 'West Ham'): 38670,          # [65 0L9]
    ('Newcastle', 'Tottenham'): 52000,       # [66 0L8]

    # 18 October 2021
    ('Arsenal', 'Crystal Palace'): 59218,    # [67 0L8]

    # 22 October 2021
    ('Arsenal', 'Aston Villa'): 59289,       # [68 0L5]

    # 23 October 2021
    ('Brighton', 'Man City'): 31347,         # [68 0L5]
    ('Southampton', 'Burnley'): 30100,       # [68 0L5]
    ('Leeds', 'Wolves'): 35850,              # [68 0L5]
    ('Everton', 'Watford'): 39500,           # [68 0L5]
    ('Crystal Palace', 'Newcastle'): 24000,  # [68 0L5]
    ('Chelsea', 'Norwich'): 39870,           # [68 0L5]

    # 24 October 2021
    ('Brentford', 'Leicester'): 16800,       # [68 0L5]
    ('West Ham', 'Tottenham'): 60000,        # [68 0L5]
    ('Man United', 'Liverpool'): 73000,      # [68 0L5]

    # 30 October 2021
    ('Tottenham', 'Man United'): 60200,      # [68 0L5]
    ('Watford', 'Southampton'): 19900,       # [68 0L5]
    ('Newcastle', 'Chelsea'): 52000,         # [68 0L5]
    ('Man City', 'Crystal Palace'): 52800,   # [68 0L5]
    ('Liverpool', 'Brighton'): 53100,        # [68 0L5]
    ('Burnley', 'Brentford'): 19100,         # [68 0L5]
    ('Leicester', 'Arsenal'): 32100,         # [68 0L5]

    # 31 October 2021
    ('Norwich', 'Leeds'): 26800,             # [68 0L5]
    ('Aston Villa', 'West Ham'): 41850,      # [68 0L5]

    # ------------------------------ November 2021 ------------------------------
    # 1 November 2021
    ('Wolves', 'Everton'): 30500,            # [68 0L5]

    # 6 November 2021
    ('Brighton', 'Newcastle'): 31100,        # [68 0L5]
    ('Crystal Palace', 'Wolves'): 24000,     # [68 0L5]
    ('Brentford', 'Norwich'): 16800,         # [68 0L5]
    ('Man United', 'Man City'): 73000,       # [68 0L5]
    ('Chelsea', 'Burnley'): 39700,           # [68 0L5]

    # 7 November 2021
    ('Arsenal', 'Watford'): 59200,           # [68 0L5]
    ('Everton', 'Tottenham'): 38000,         # [68 0L5]
    ('Leeds', 'Leicester'): 36100,           # [68 0L5]
    ('West Ham', 'Liverpool'): 60000,        # [68 0L5]

    # 20 November 2021
    ('Burnley', 'Crystal Palace'): 19100,    # [68 0L5]
    ('Leicester', 'Chelsea'): 32100,         # [68 0L5]
    ('Aston Villa', 'Brighton'): 41800,      # [68 0L5]
    ('Newcastle', 'Brentford'): 52000,       # [68 0L5]
    ('Norwich', 'Southampton'): 26700,       # [68 0L5]
    ('Watford', 'Man United'): 20100,        # [68 0L5]
    ('Wolves', 'West Ham'): 30500,           # [68 0L5]
    ('Liverpool', 'Arsenal'): 53200,         # [68 0L5]

    # 21 November 2021
    ('Man City', 'Everton'): 52800,          # [68 0L5]
    ('Tottenham', 'Leeds'): 60200,           # [68 0L5]

    # 27 November 2021
    ('Norwich', 'Wolves'): 26700,            # [68 0L5]
    ('Liverpool', 'Southampton'): 53200,     # [68 0L5]
    ('Brighton', 'Leeds'): 31100,            # [68 0L5]
    ('Arsenal', 'Newcastle'): 59200,         # [68 0L5]
    ('Crystal Palace', 'Aston Villa'): 24000,# [68 0L5]

    # 28 November 2021
    ('Leicester', 'Watford'): 32100,         # [68 0L5]
    ('Man City', 'West Ham'): 52800,         # [68 0L5]
    ('Brentford', 'Everton'): 16800,         # [68 0L5]
    ('Chelsea', 'Man United'): 39700,        # [68 0L5]

    # 30 November 2021
    ('Newcastle', 'Norwich'): 52000,         # [68 0L5]
    ('Leeds', 'Crystal Palace'): 36100,      # [68 0L5]

    # ------------------------------ December 2021 ------------------------------
    # 1 December 2021
    ('Watford', 'Chelsea'): 20100,           # [68 0L5]
    ('Southampton', 'Leicester'): 30100,     # [68 0L5]
    ('West Ham', 'Brighton'): 59900,         # [68 0L5]
    ('Wolves', 'Burnley'): 30500,            # [68 0L5]
    ('Aston Villa', 'Man City'): 41800,      # [68 0L5]
    ('Everton', 'Liverpool'): 38500,         # [68 0L5]

    # 2 December 2021
    ('Tottenham', 'Brentford'): 60200,       # [68 0L5]
    ('Man United', 'Arsenal'): 73000,        # [68 0L5]

    # 4 December 2021
    ('West Ham', 'Chelsea'): 60000,          # [68 0L5]
    ('Newcastle', 'Burnley'): 52000,         # [68 0L5]
    ('Southampton', 'Brighton'): 30100,      # [68 0L5]
    ('Wolves', 'Liverpool'): 30500,          # [68 0L5]
    ('Watford', 'Man City'): 20100,          # [68 0L5]

    # 5 December 2021
    ('Tottenham', 'Norwich'): 60200,         # [68 0L5]
    ('Aston Villa', 'Leicester'): 41800,     # [68 0L5]
    ('Leeds', 'Brentford'): 36100,           # [68 0L5]
    ('Man United', 'Crystal Palace'): 73000, # [68 0L5]

    # 6 December 2021
    ('Everton', 'Arsenal'): 38500,           # [68 0L5]

    # 10 December 2021
    ('Brentford', 'Watford'): 16800,         # [68 0L5]

    # 11 December 2021
    ('Man City', 'Wolves'): 52800,           # [68 0L5]
    ('Arsenal', 'Southampton'): 59200,       # [68 0L5]
    ('Chelsea', 'Leeds'): 39700,             # [68 0L5]
    ('Liverpool', 'Aston Villa'): 53200,     # [68 0L5]
    ('Norwich', 'Man United'): 26700,        # [68 0L5]

    # 12 December 2021
    ('Burnley', 'West Ham'): 19100,          # [68 0L5]
    ('Leicester', 'Newcastle'): 32100,       # [68 0L5]
    ('Crystal Palace', 'Everton'): 24000,    # [68 0L5]

    # 14 December 2021
    ('Man City', 'Leeds'): 52800,            # [68 0L5]
    ('Norwich', 'Aston Villa'): 26700,       # [68 0L5]

    # 15 December 2021
    ('Arsenal', 'West Ham'): 59200,          # [68 0L5]
    ('Brighton', 'Wolves'): 31100,           # [68 0L5]
    ('Crystal Palace', 'Southampton'): 24000,# [68 0L5]

    # 16 December 2021
    ('Chelsea', 'Everton'): 39700,           # [68 0L5]
    ('Liverpool', 'Newcastle'): 53200,       # [68 0L5]

    # 18 December 2021
    ('Leeds', 'Arsenal'): 36100,             # [68 0L5]

    # 19 December 2021
    ('Newcastle', 'Man City'): 52000,        # [68 0L5]
    ('Wolves', 'Chelsea'): 30500,            # [68 0L5]
    ('Tottenham', 'Liverpool'): 60200,       # [68 0L5]

    # 26 December 2021
    ('Brighton', 'Brentford'): 31100,        # [68 0L5]
    ('Aston Villa', 'Chelsea'): 41800,       # [68 0L5]
    ('West Ham', 'Southampton'): 60000,      # [68 0L5]
    ('Norwich', 'Arsenal'): 26700,           # [68 0L5]
    ('Man City', 'Leicester'): 52800,        # [68 0L5]
    ('Tottenham', 'Crystal Palace'): 60200,  # [68 0L5]

    # 27 December 2021
    ('Newcastle', 'Man United'): 52000,      # [68 0L5]

    # 28 December 2021
    ('Crystal Palace', 'Norwich'): 24000,    # [68 0L5]
    ('Southampton', 'Tottenham'): 30100,     # [68 0L5]
    ('Watford', 'West Ham'): 20100,          # [68 0L5]
    ('Leicester', 'Liverpool'): 32100,       # [68 0L5]

    # 29 December 2021
    ('Chelsea', 'Brighton'): 39700,          # [68 0L5]
    ('Brentford', 'Man City'): 16800,        # [68 0L5]

    # 30 December 2021
    ('Man United', 'Burnley'): 73000,        # [68 0L5]

    # ------------------------------ January 2022 ------------------------------
    # 1 January 2022
    ('Watford', 'Tottenham'): 20100,         # [68 0L5]
    ('Crystal Palace', 'West Ham'): 24000,   # [68 0L5]
    ('Arsenal', 'Man City'): 59200,          # [68 0L5]

    # 2 January 2022
    ('Leeds', 'Burnley'): 36100,             # [68 0L5]
    ('Chelsea', 'Liverpool'): 39700,         # [68 0L5]
    ('Brentford', 'Aston Villa'): 16800,     # [68 0L5]
    ('Everton', 'Brighton'): 38500,          # [68 0L5]

    # 3 January 2022
    ('Man United', 'Wolves'): 73000,         # [68 0L5]

    # 11 January 2022
    ('Southampton', 'Brentford'): 30100,     # [68 0L5]

    # 12 January 2022
    ('West Ham', 'Norwich'): 60000,          # [68 0L5]

    # 14 January 2022
    ('Brighton', 'Crystal Palace'): 31100,   # [68 0L5]

    # 15 January 2022
    ('Man City', 'Chelsea'): 52800,          # [68 0L5]
    ('Newcastle', 'Watford'): 52000,         # [68 0L5]
    ('Norwich', 'Everton'): 26700,           # [68 0L5]
    ('Wolves', 'Southampton'): 30500,        # [68 0L5]
    ('Aston Villa', 'Man United'): 41800,    # [68 0L5]

    # 16 January 2022
    ('Liverpool', 'Brentford'): 52824,       # [6 0L5]
}

# ============================================================
# Code to fill the Attendance column
# ============================================================
for idx, row in df[df['Season'] == '2122'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2122') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [242]:
df[(df['Season'] == '2122') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']][:75]

             HomeTeam        AwayTeam  Year  Month  Day
11070       Tottenham         Everton  2022      3    7
11071           Leeds     Aston Villa  2022      3   10
11076       Brentford         Burnley  2022      3   12
11077        Brighton       Liverpool  2022      3   12
11078         Chelsea       Newcastle  2022      3   13
11079         Everton          Wolves  2022      3   13
11080           Leeds         Norwich  2022      3   13
11081     Southampton         Watford  2022      3   13
11082        West Ham     Aston Villa  2022      3   13
11083         Arsenal       Leicester  2022      3   13
11084  Crystal Palace        Man City  2022      3   14
11085        Brighton       Tottenham  2022      3   16
11086         Arsenal       Liverpool  2022      3   16
11087         Everton       Newcastle  2022      3   17
11088          Wolves           Leeds  2022      3   18
11089     Aston Villa         Arsenal  2022      3   19
11090       Leicester       Brentford  2022      3   20
11091       Tottenham        West Ham  2022      3   20
11092       Liverpool         Watford  2022      4    2
11093        Brighton         Norwich  2022      4    2
11094         Burnley        Man City  2022      4    2
11095         Chelsea       Brentford  2022      4    2
11096           Leeds     Southampton  2022      4    2
11097          Wolves     Aston Villa  2022      4    2
11098      Man United       Leicester  2022      4    2
11099        West Ham         Everton  2022      4    3
11100       Tottenham       Newcastle  2022      4    3
11101  Crystal Palace         Arsenal  2022      4    4
11102         Burnley         Everton  2022      4    6
11103       Newcastle          Wolves  2022      4    8
11104         Everton      Man United  2022      4    9
11105         Arsenal        Brighton  2022      4    9
11106     Southampton         Chelsea  2022      4    9
11107         Watford           Leeds  2022      4    9
11108     Aston Villa       Tottenham  2022      4    9
11109       Brentford        West Ham  2022      4   10
11110       Leicester  Crystal Palace  2022      4   10
11111         Norwich         Burnley  2022      4   10
11112        Man City       Liverpool  2022      4   10
11113         Watford       Brentford  2022      4   16
11114     Southampton         Arsenal  2022      4   16
11115       Tottenham        Brighton  2022      4   16
11116      Man United         Norwich  2022      4   16
11117       Newcastle       Leicester  2022      4   17
11118        West Ham         Burnley  2022      4   17
11119       Liverpool      Man United  2022      4   19
11120         Chelsea         Arsenal  2022      4   20
11121         Everton       Leicester  2022      4   20
11122       Newcastle  Crystal Palace  2022      4   20
11123        Man City        Brighton  2022      4   20
11124         Burnley     Southampton  2022      4   21
11125         Norwich       Newcastle  2022      4   23
11126        Man City         Watford  2022      4   23
11127       Brentford       Tottenham  2022      4   23
11128         Arsenal      Man United  2022      4   23
11129       Leicester     Aston Villa  2022      4   23
11130        Brighton     Southampton  2022      4   24
11131         Burnley          Wolves  2022      4   24
11132         Chelsea        West Ham  2022      4   24
11133       Liverpool         Everton  2022      4   24
11134  Crystal Palace           Leeds  2022      4   25
11135      Man United         Chelsea  2022      4   28
11136          Wolves        Brighton  2022      4   30
11137         Watford         Burnley  2022      4   30
11138           Leeds        Man City  2022      4   30
11143       Tottenham       Leicester  2022      5    1
11144        West Ham         Arsenal  2022      5    1
11145      Man United       Brentford  2022      5    2
11146       Liverpool       Tottenham  2022      5    7
11147        Brighton      Man United  2022      5    7
11148  Crystal Palace         Watford  2022      5    7
11149         Burnley     Aston Villa  2022      5    7
11150       Brentford     Southampton  2022      5    7
11151         Chelsea          Wolves  2022      5    7
11152         Norwich        West Ham  2022      5    8

In [ ]:
attendance_data = {
    # ---- March 2022 ----
    ('Tottenham', 'Everton'): 59647,          # 7 Mar 2022 [0 0L8]
    ('Leeds', 'Aston Villa'): 36400,          # 10 Mar 2022 [1 0L8]
    ('Brentford', 'Burnley'): 16984,          # 12 Mar 2022 [2 0L8]
    ('Brighton', 'Liverpool'): 31474,         # 12 Mar 2022 [3 0L8]
    ('Chelsea', 'Newcastle'): 40026,          # 13 Mar 2022 [4 0L8]
    ('Everton', 'Wolves'): 39112,             # 13 Mar 2022 [5 0L9]
    ('Leeds', 'Norwich'): 36321,              # 13 Mar 2022 [12 0L8]
    ('Southampton', 'Watford'): 28863,        # 13 Mar 2022 [13 0L7]
    ('West Ham', 'Aston Villa'): 59957,       # 13 Mar 2022 [14 0L8]
    ('Arsenal', 'Leicester'): 60111,          # 13 Mar 2022 [15 0L8]
    ('Crystal Palace', 'Man City'): 25309,    # 14 Mar 2022 [16 0L8]
    ('Brighton', 'Tottenham'): 31144,         # 16 Mar 2022 [17 0L9]
    ('Arsenal', 'Liverpool'): 59968,          # 16 Mar 2022 [18 0L8]
    ('Everton', 'Newcastle'): 39068,          # 17 Mar 2022 [19 0L7]
    ('Wolves', 'Leeds'): 31842,               # 18 Mar 2022 [20 0L8]
    ('Aston Villa', 'Arsenal'): 41956,        # 19 Mar 2022 [21 0L7]
    ('Leicester', 'Brentford'): 31830,        # 20 Mar 2022 [22 0L8]
    ('Tottenham', 'West Ham'): 58685,         # 20 Mar 2022 [23 0L8]

    # ---- April 2022 ----
    ('Liverpool', 'Watford'): 53104,          # 2 Apr 2022 [24 0L8]
    ('Brighton', 'Norwich'): 31245,           # 2 Apr 2022 [25 0L8]
    ('Burnley', 'Man City'): 20388,           # 2 Apr 2022 [26 0L9]
    ('Chelsea', 'Brentford'): 39061,          # 2 Apr 2022 [27 0L8]
    ('Leeds', 'Southampton'): 36580,          # 2 Apr 2022 [28 0L8]
    ('Wolves', 'Aston Villa'): 31012,         # 2 Apr 2022 [29 0L8]
    ('Man United', 'Leicester'): 73444,       # 2 Apr 2022 [30 0L8]
    ('West Ham', 'Everton'): 59953,           # 3 Apr 2022 [31 0L8]
    ('Tottenham', 'Newcastle'): 57553,        # 3 Apr 2022 [32 0L8]
    ('Crystal Palace', 'Arsenal'): 25149,     # 4 Apr 2022 [33 0L7]
    ('Burnley', 'Everton'): 19830,            # 6 Apr 2022 [34 0L8]
    ('Newcastle', 'Wolves'): 52164,           # 8 Apr 2022 [35 0L8]
    ('Everton', 'Man United'): 39080,         # 9 Apr 2022 [36 0L8]
    ('Arsenal', 'Brighton'): 60112,           # 9 Apr 2022 [37 0L8]
    ('Southampton', 'Chelsea'): 31359,        # 9 Apr 2022 [38 0L8]
    ('Watford', 'Leeds'): 20957,              # 9 Apr 2022 [39 0L7]
    ('Aston Villa', 'Tottenham'): 41949,      # 9 Apr 2022 [40 0L8]
    ('Brentford', 'West Ham'): 17032,         # 10 Apr 2022 [41 0L8]
    ('Leicester', 'Crystal Palace'): 31896,   # 10 Apr 2022 [42 0L8]
    ('Norwich', 'Burnley'): 26361,            # 10 Apr 2022 [43 0L8]
    ('Man City', 'Liverpool'): 53197,         # 10 Apr 2022 [44 0L9]

    # ---- April 2022 (continued) ----
    ('Watford', 'Brentford'): 20747,          # 16 Apr 2022 [45 0L7]
    ('Southampton', 'Arsenal'): 31465,        # 16 Apr 2022 [46 0L8]
    ('Tottenham', 'Brighton'): 58685,         # 16 Apr 2022 [47 0L8]
    ('Man United', 'Norwich'): 73381,         # 16 Apr 2022 [48 0L8]
    ('Newcastle', 'Leicester'): 52104,        # 17 Apr 2022 [49 0L8]
    ('West Ham', 'Burnley'): 59958,           # 17 Apr 2022 [50 0L8]
    ('Liverpool', 'Man United'): 52686,       # 19 Apr 2022 [51 0L8]
    ('Chelsea', 'Arsenal'): 32249,            # 20 Apr 2022 [52 0L7]
    ('Everton', 'Leicester'): 39153,          # 20 Apr 2022 [53 0L7]
    ('Newcastle', 'Crystal Palace'): 51938,   # 20 Apr 2022 [54 0L8]
    ('Man City', 'Brighton'): 52226,          # 20 Apr 2022 [55 0L13]
    ('Burnley', 'Southampton'): 17384,        # 21 Apr 2022 [56 0L8]
    ('Norwich', 'Newcastle'): 26910,          # 23 Apr 2022 [57 0L8]
    ('Man City', 'Watford'): 53013,           # 23 Apr 2022 [58 0L8]
    ('Brentford', 'Tottenham'): 17072,        # 23 Apr 2022 [59 0L8]
    ('Arsenal', 'Man United'): 60223,         # 23 Apr 2022 [60 0L7]
    ('Leicester', 'Aston Villa'): 32185,      # 23 Apr 2022 [61 0L8]
    ('Brighton', 'Southampton'): 31335,       # 24 Apr 2022 [62 0L9]
    ('Burnley', 'Wolves'): 19246,             # 24 Apr 2022 [63 0L8]
    ('Chelsea', 'West Ham'): 32231,           # 24 Apr 2022 [64 0L8]
    ('Liverpool', 'Everton'): 53213,          # 24 Apr 2022 [65 0L8]

}

# Loop through each row and fill the Attendance column
for idx, row in df[df['Season'] == '2122'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    if (home, away) in attendance_data and attendance_data[(home, away)] is not None:
        df.loc[(df['Season'] == '2122') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [244]:
df[(df['Season'] == '2122') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']][:75]

             HomeTeam        AwayTeam  Year  Month  Day
11134  Crystal Palace           Leeds  2022      4   25
11135      Man United         Chelsea  2022      4   28
11136          Wolves        Brighton  2022      4   30
11137         Watford         Burnley  2022      4   30
11138           Leeds        Man City  2022      4   30
11143       Tottenham       Leicester  2022      5    1
11144        West Ham         Arsenal  2022      5    1
11145      Man United       Brentford  2022      5    2
11146       Liverpool       Tottenham  2022      5    7
11147        Brighton      Man United  2022      5    7
11148  Crystal Palace         Watford  2022      5    7
11149         Burnley     Aston Villa  2022      5    7
11150       Brentford     Southampton  2022      5    7
11151         Chelsea          Wolves  2022      5    7
11152         Norwich        West Ham  2022      5    8
11153         Arsenal           Leeds  2022      5    8
11154       Leicester         Everton  2022      5    8
11155        Man City       Newcastle  2022      5    8
11156     Aston Villa       Liverpool  2022      5   10
11157          Wolves        Man City  2022      5   11
11158         Watford         Everton  2022      5   11
11159       Leicester         Norwich  2022      5   11
11160           Leeds         Chelsea  2022      5   11
11161       Tottenham         Arsenal  2022      5   12
11162       Tottenham         Burnley  2022      5   15
11163     Aston Villa  Crystal Palace  2022      5   15
11164           Leeds        Brighton  2022      5   15
11165         Watford       Leicester  2022      5   15
11166        West Ham        Man City  2022      5   15
11167          Wolves         Norwich  2022      5   15
11168         Everton       Brentford  2022      5   15
11169       Newcastle         Arsenal  2022      5   16
11170     Southampton       Liverpool  2022      5   17
11171     Aston Villa         Burnley  2022      5   19
11172         Chelsea       Leicester  2022      5   19
11173         Everton  Crystal Palace  2022      5   19
11174         Arsenal         Everton  2022      5   22
11175       Brentford           Leeds  2022      5   22
11176        Brighton        West Ham  2022      5   22
11177         Burnley       Newcastle  2022      5   22
11178         Chelsea         Watford  2022      5   22
11179  Crystal Palace      Man United  2022      5   22
11180       Leicester     Southampton  2022      5   22
11181       Liverpool          Wolves  2022      5   22
11182        Man City     Aston Villa  2022      5   22
11183         Norwich       Tottenham  2022      5   22

In [ ]:
attendance_data = {
    # Monday 25 April 2022
    ('Crystal Palace', 'Leeds'): 25357,          # Source: ESPN [22 0L15]

    # Thursday 28 April 2022
    ('Man United', 'Chelsea'): 73564,            # Source: ESPN [23 0L6]

    # Saturday 30 April 2022
    ('Wolves', 'Brighton'): 31243,               # Source: ESPN [24 0L7]
    ('Watford', 'Burnley'): 20738,               # Source: ESPN [25 0L13]
    ('Leeds', 'Man City'): 35771,                # Source: ESPN [26 0L6]

    # Sunday 1 May 2022
    ('Tottenham', 'Leicester'): 59482,           # Source: ESPN [27 0L7]
    ('West Ham', 'Arsenal'): 59959,              # Source: ESPN [28 0L6]

    # Monday 2 May 2022
    ('Man United', 'Brentford'): 73482,          # Source: ESPN [29 0L6]

    # Saturday 7 May 2022
    ('Liverpool', 'Tottenham'): 53177,           # Source: ESPN [30 0L7]
    ('Brighton', 'Man United'): 31637,           # Source: 11v11 [31 0L12]
    ('Crystal Palace', 'Watford'): 24622,        # Source: ESPN [32 0L6]
    ('Burnley', 'Aston Villa'): 20891,           # Source: Sky Sports [33 0L8]
    ('Brentford', 'Southampton'): 17051,         # Source: ESPN [34 0L7]
    ('Chelsea', 'Wolves'): 32190,                # Source: ESPN [35 0L6]

    # Sunday 8 May 2022
    ('Norwich', 'West Ham'): 26428,              # Source: ESPN [36 0L6]
    ('Arsenal', 'Leeds'): 60108,                 # Source: Sky Sports [37 0L7]
    ('Leicester', 'Everton'): 32001,             # Source: ESPN [38 0L6]
    ('Man City', 'Newcastle'): 53336,            # Source: Sky Sports [39 0L7]

    # Tuesday 10 May 2022
    ('Aston Villa', 'Liverpool'): 41919,         # Source: ESPN [40 0L6]

    # Wednesday 11 May 2022
    ('Wolves', 'Man City'): 31076,               # Source: Transfermarkt [41 0L27]
    ('Watford', 'Everton'): 20653,               # Source: Transfermarkt [42 0L6]
    ('Leicester', 'Norwich'): 30892,             # Source: ESPN [43 0L7]
    ('Leeds', 'Chelsea'): 36549,                 # Source: ESPN [44 0L6]

    # Thursday 12 May 2022
    ('Tottenham', 'Arsenal'): 62027,             # Source: Sky Sports [45 0L7]
}

# Columns to fill
match_cols = ['Attendance']

# Loop through each row for the 2021-22 season
for idx, row in df[df['Season'] == '2122'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2122') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [247]:
df[(df['Season'] == '2122') & (df['Attendance'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']][:75]

             HomeTeam        AwayTeam  Year  Month  Day
11162       Tottenham         Burnley  2022      5   15
11163     Aston Villa  Crystal Palace  2022      5   15
11164           Leeds        Brighton  2022      5   15
11165         Watford       Leicester  2022      5   15
11166        West Ham        Man City  2022      5   15
11167          Wolves         Norwich  2022      5   15
11168         Everton       Brentford  2022      5   15
11169       Newcastle         Arsenal  2022      5   16
11170     Southampton       Liverpool  2022      5   17
11171     Aston Villa         Burnley  2022      5   19
11172         Chelsea       Leicester  2022      5   19
11173         Everton  Crystal Palace  2022      5   19
11174         Arsenal         Everton  2022      5   22
11175       Brentford           Leeds  2022      5   22
11176        Brighton        West Ham  2022      5   22
11177         Burnley       Newcastle  2022      5   22
11178         Chelsea         Watford  2022      5   22
11179  Crystal Palace      Man United  2022      5   22
11180       Leicester     Southampton  2022      5   22
11181       Liverpool          Wolves  2022      5   22
11182        Man City     Aston Villa  2022      5   22
11183         Norwich       Tottenham  2022      5   22

In [ ]:
attendance_data = {
    # ---- 15 May 2022 ----
    ('Tottenham', 'Burnley'): 61729,          # Source: Sky Sports [0 0L8]
    ('Aston Villa', 'Crystal Palace'): 41136, # Source: Sky Sports [1 0L8]
    ('Leeds', 'Brighton'): 36638,             # Source: ESPN [2 0L6]
    ('Watford', 'Leicester'): 20257,          # Source: ESPN [3 0L6]
    ('West Ham', 'Man City'): 59972,          # Source: Premier League [4 0L7]
    ('Wolves', 'Norwich'): 31219,             # Source: Sky Sports [5 0L13]
    ('Everton', 'Brentford'): 38819,          # Source: Sky Sports [6 0L7]

    # ---- 16 May 2022 ----
    ('Newcastle', 'Arsenal'): 52274,          # Source: ESPN [8 0L10]

    # ---- 17 May 2022 ----
    ('Southampton', 'Liverpool'): 31588,      # Source: ESPN [9 0L11]

    # ---- 19 May 2022 ----
    ('Aston Villa', 'Burnley'): 40468,        # Source: ESPN [10 0L6]
    ('Chelsea', 'Leicester'): 31478,          # Source: ESPN [11 0L6]
    ('Everton', 'Crystal Palace'): 38448,     # Source: ESPN [12 0L7]

    # ---- 22 May 2022 ----
    ('Arsenal', 'Everton'): 60201,            # Source: worldfootball [13 0L7]
    ('Brentford', 'Leeds'): 16957,            # Source: Sky Sports [14 0L7]
    ('Brighton', 'West Ham'): 31604,          # Source: Sky Sports [15 0L13]
    ('Burnley', 'Newcastle'): 21361,          # Source: Sky Sports [16 0L8]
    ('Chelsea', 'Watford'): 32089,            # Source: Sky Sports [17 0L8]
    ('Crystal Palace', 'Man United'): 25434,  # Source: worldfootball [18 0L7]
    ('Leicester', 'Southampton'): 32003,      # Source: Sky Sports [19 0L7]
    ('Liverpool', 'Wolves'): 53097,           # Source: Sky Sports [20 0L8]
    ('Man City', 'Aston Villa'): 53395,       # Source: Sky Sports [21 0L7]
    ('Norwich', 'Tottenham'): 27022,          # Source: Premier League [22 0L11]
}

# Columns to fill
match_cols = ['Attendance']

# Loop through each row for the 2021-22 season
for idx, row in df[df['Season'] == '2122'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    if (home, away) in attendance_data:
        df.loc[(df['Season'] == '2122') & (df.index == idx), 'Attendance'] = attendance_data[(home, away)]

In [254]:
print(df['Time'].unique())

[nan '20:00' '15:00' '17:30' '12:30' '14:00' '16:30' '20:15' '19:30'
 '19:45' '18:00' '19:00' '16:15' '14:15' '12:00' '16:00' '21:00' '18:30'
 '17:45' '19:15' '23:00' '23:15' '23:30' '14:05' '15:30' '13:30' '23:45'
 '22:00' '22:30' '21:15']

In [255]:
time_corrections = {
    '16:00': '12:30',
    '18:30': '15:00',
    '21:00': '17:30',
    '23:15': '19:45',
    '23:30': '20:00',
    '23:45': '20:15',
    '23:00': '19:30',
    '17:45': '14:15',
}
df['Time'] = df['Time'].replace(time_corrections)

In [256]:
df.to_csv("Data/Data4.csv", index=False)

---

In [250]:
df[df['Season'] == '2021'].isna().sum()[df[df['Season'] == '2021'].isna().sum() > 0]

WeekDay        13
Time           13
Round          13
Attendance    239
XGHome         13
XGAway         13
dtype: int64

In [251]:
df[(df['Season'] == '2021') & (df['XGAway'].isna())][['HomeTeam', 'AwayTeam', 'Year', 'Month', 'Day']]

          HomeTeam        AwayTeam  Year  Month  Day
10433        Leeds          Fulham  2020      9   19
10468    Tottenham        West Ham  2020     10   18
10483      Burnley         Chelsea  2020     10   31
10518  Southampton      Man United  2020     11   29
10537       Fulham       Liverpool  2020     12   13
10558    Tottenham       Leicester  2020     12   20
10569     West Ham        Brighton  2020     12   27
10591     Man City        Brighton  2021      1   13
10599     Man City  Crystal Palace  2021      1   17
10657     West Ham       Sheffield  2021      2   15
10703      Everton         Burnley  2021      3   13
10736       Wolves       Sheffield  2021      4   17
10737      Arsenal          Fulham  2021      4   18

In [ ]:
# ============================================================
# داده‌های کامل بازی‌های فصل 2020-21
# ============================================================
match_data = {
    # Leeds vs Fulham - 19 September 2020
    ('Leeds', 'Fulham'): {
        'WeekDay': 'Sat',
        'Time': '15:00',
        'Round': 2,
        'Attendance': 0,          # بدون تماشاگر (کووید-۱۹)
        'XGHome': 1.4,
        'XGAway': 1.7
    },
    # Tottenham vs West Ham - 18 October 2020
    ('Tottenham', 'West Ham'): {
        'WeekDay': 'Sun',
        'Time': '16:30',
        'Round': 5,
        'Attendance': 0,          # بدون تماشاگر (کووید-۱۹)
        'XGHome': 1.7,
        'XGAway': 1.9
    },
    # Burnley vs Chelsea - 31 October 2020
    ('Burnley', 'Chelsea'): {
        'WeekDay': 'Sat',
        'Time': '15:00',
        'Round': 7,
        'Attendance': 0,          # بدون تماشاگر (کووید-۱۹)
        'XGHome': 0.5,
        'XGAway': 0.9
    },
    # Southampton vs Man United - 29 November 2020
    ('Southampton', 'Man United'): {
        'WeekDay': 'Sun',
        'Time': '14:00',
        'Round': 10,
        'Attendance': 0,          # بدون تماشاگر (کووید-۱۹)
        'XGHome': 0.5,
        'XGAway': 2.1
    },
    # Fulham vs Liverpool - 13 December 2020
    ('Fulham', 'Liverpool'): {
        'WeekDay': 'Sun',
        'Time': '16:30',
        'Round': 12,
        'Attendance': 2000,       # ESPN [4 0L15]
        'XGHome': 1.57,
        'XGAway': 2.6
    },
    # Tottenham vs Leicester - 20 December 2020
    ('Tottenham', 'Leicester'): {
        'WeekDay': 'Sun',
        'Time': '14:15',
        'Round': 14,
        'Attendance': 0,          # بدون تماشاگر (کووید-۱۹)
        'XGHome': 0.7,
        'XGAway': 1.7
    },
    # West Ham vs Brighton - 27 December 2020
    ('West Ham', 'Brighton'): {
        'WeekDay': 'Sun',
        'Time': '14:15',
        'Round': 15,
        'Attendance': 0,          # بدون تماشاگر (کووید-۱۹)
        'XGHome': 1.3,
        'XGAway': 1.1
    },
    # Man City vs Brighton - 13 January 2021
    ('Man City', 'Brighton'): {
        'WeekDay': 'Wed',
        'Time': '18:00',          # FBref [7 0L29]
        'Round': 18,
        'Attendance': 0,          # بدون تماشاگر (کووید-۱۹)
        'XGHome': 2.0,
        'XGAway': 0.2
    },
    # Man City vs Crystal Palace - 17 January 2021
    ('Man City', 'Crystal Palace'): {
        'WeekDay': 'Sun',
        'Time': '19:15',          # FBref [8 0L8]
        'Round': 19,
        'Attendance': 0,          # بدون تماشاگر (کووید-۱۹)
        'XGHome': 0.7,
        'XGAway': 0.1
    },
    # West Ham vs Sheffield - 15 February 2021
    ('West Ham', 'Sheffield'): {
        'WeekDay': 'Mon',
        'Time': '18:00',
        'Round': 24,
        'Attendance': 0,          # بدون تماشاگر (کووید-۱۹)
        'XGHome': 1.9,
        'XGAway': 0.7
    },
    # Everton vs Burnley - 13 March 2021
    ('Everton', 'Burnley'): {
        'WeekDay': 'Sat',
        'Time': '17:30',
        'Round': 28,
        'Attendance': 0,          # بدون تماشاگر (کووید-۱۹)
        'XGHome': 1.5,
        'XGAway': 0.8
    },
    # Wolves vs Sheffield - 17 April 2021
    ('Wolves', 'Sheffield'): {
        'WeekDay': 'Sat',
        'Time': '20:15',          # FBref [11 0L8]
        'Round': 32,
        'Attendance': 0,          # بدون تماشاگر (کووید-۱۹)
        'XGHome': 1.1,
        'XGAway': 0.5
    },
    # Arsenal vs Fulham - 18 April 2021
    ('Arsenal', 'Fulham'): {
        'WeekDay': 'Sun',
        'Time': '13:30',
        'Round': 32,
        'Attendance': 0,          # بدون تماشاگر (کووید-۱۹)
        'XGHome': 2.7,
        'XGAway': 0.9
    },
}

match_cols = ['WeekDay', 'Time', 'Round', 'Attendance', 'XGHome', 'XGAway']

for idx, row in df[df['Season'] == '2021'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    if (home, away) in match_data:
        for col in match_cols:
            df.loc[(df['Season'] == '2021') & (df.index == idx), col] = match_data[(home, away)][col]

In [258]:
df[df['Season'] == '2021'].isna().sum()[df[df['Season'] == '2021'].isna().sum() > 0]

Attendance    226
dtype: int64

In [ ]:
# ============================================================
# لیست بازی‌های دارای تماشاگر در فصل 2020-21
# ============================================================
matches_with_fans = [
    # دوره اول - دسامبر 2020 (2,000 نفر)
    ('Brighton', 'Southampton'),
    ('Chelsea', 'Leeds'),
    ('Liverpool', 'Wolves'),
    ('Tottenham', 'Arsenal'),
    ('West Ham', 'Man United'),
    
    # هفته 37 - می 2021
    ('Brighton', 'Man City'),
    ('Burnley', 'Liverpool'),
    ('Chelsea', 'Leicester'),
    ('Crystal Palace', 'Arsenal'),
    ('Everton', 'Wolves'),
    ('Man United', 'Fulham'),
    ('Newcastle', 'Sheffield Utd'),
    ('Southampton', 'Leeds'),
    ('Tottenham', 'Aston Villa'),
    ('West Brom', 'West Ham'),
    
    # هفته 38 - می 2021
    ('Arsenal', 'Brighton'),
    ('Aston Villa', 'Chelsea'),
    ('Fulham', 'Newcastle'),
    ('Leeds', 'West Brom'),
    ('Leicester', 'Tottenham'),
    ('Liverpool', 'Crystal Palace'),
    ('Man City', 'Everton'),
    ('Sheffield Utd', 'Burnley'),
    ('West Ham', 'Southampton'),
    ('Wolves', 'Man United'),
]


attendance_values = {
    # دوره اول - دسامبر 2020 (2,000 نفر)
    ('Brighton', 'Southampton'): 2000,
    ('Chelsea', 'Leeds'): 2000,
    ('Liverpool', 'Wolves'): 2000,
    ('Tottenham', 'Arsenal'): 2000,
    ('West Ham', 'Man United'): 2000,        # [3 0L11-L14]
    
    # هفته 37 - می 2021
    ('Brighton', 'Man City'): 7945,          # [0 0L9]
    ('Burnley', 'Liverpool'): 0,             # بدون تماشاگر (لغو شد)
    ('Chelsea', 'Leicester'): 8000,          # [0 0L25]
    ('Crystal Palace', 'Arsenal'): 6500,
    ('Everton', 'Wolves'): 6800,
    ('Man United', 'Fulham'): 9347,          # [0 0L8][5 0L36]
    ('Newcastle', 'Sheffield Utd'): 10000,
    ('Southampton', 'Leeds'): 7291,          # [0 0L24-L25]
    ('Tottenham', 'Aston Villa'): 10000,
    ('West Brom', 'West Ham'): 5371,         # [0 0L10]
    
    # هفته 38 - می 2021
    ('Arsenal', 'Brighton'): 10000,
    ('Aston Villa', 'Chelsea'): 10000,
    ('Fulham', 'Newcastle'): 6500,
    ('Leeds', 'West Brom'): 8000,            # [0 0L29]
    ('Leicester', 'Tottenham'): 8000,
    ('Liverpool', 'Crystal Palace'): 10000,
    ('Man City', 'Everton'): 10000,
    ('Sheffield Utd', 'Burnley'): 8000,
    ('West Ham', 'Southampton'): 10000,
    ('Wolves', 'Man United'): 10000,
}


for idx, row in df[df['Season'] == '2021'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    if away == 'Sheffield':
        away = 'Sheffield Utd'
    
    if (home, away) in attendance_values:
        df.loc[(df['Season'] == '2021') & (df.index == idx), 'Attendance'] = attendance_values[(home, away)]

In [ ]:
for idx, row in df[df['Season'] == '2021'].iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    
    if away == 'Sheffield':
        away = 'Sheffield Utd'
    
    if (home, away) not in attendance_values:
        df.loc[(df['Season'] == '2021') & (df.index == idx), 'Attendance'] = 0

In [261]:
df[df['Season'] == '2021'].isna().sum()[df[df['Season'] == '2021'].isna().sum() > 0]

Series([], dtype: int64)

In [265]:
df[df['Season'] == '2122'].isna().sum()[df[df['Season'] == '2122'].isna().sum() > 0]

Series([], dtype: int64)

In [266]:
df[df['Season'] == '2223'].isna().sum()[df[df['Season'] == '2223'].isna().sum() > 0]

Series([], dtype: int64)

In [267]:
df[df['Season'] == '2324'].isna().sum()[df[df['Season'] == '2324'].isna().sum() > 0]

Series([], dtype: int64)

In [268]:
df[df['Season'] == '2425'].isna().sum()[df[df['Season'] == '2425'].isna().sum() > 0]

Series([], dtype: int64)

In [269]:
df[df['Season'] == '2526'].isna().sum()[df[df['Season'] == '2526'].isna().sum() > 0]

Series([], dtype: int64)

In [270]:
df.to_csv("Data/Data4.csv", index=False)