In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [10]:
df = pd.read_csv("Data/Data8.csv", dtype={"Season":str})

In [3]:
df.head()

,Season,Year,Month,Day,WeekDay,Time,Round,HomeTeam,AwayTeam,HomeGoal,AwayGoal,Result,HomeGoal-HalfTime,AwayGoal-HalfTime,Result-HalfTime,Attendance,Referee,HomeShot,AwayShot,HomeOnTargetShot,AwayOnTargetShot,HomeFoul,AwayFoul,HomeCorner,AwayCorner,HomeYellow,AwayYellow,HomeRed,AwayRed,XGHome,XGAway,SeasonPosHome,SeasonPlayedHome,SeasonWinHome,SeasonDrawHome,SeasonLossHome,SeasonGFHome,SeasonGAHome,SeasonGDHome,SeasonPointsHome,QualificationOrRelegationHome,SeasonPosAway,SeasonPlayedAway,SeasonWinAway,SeasonDrawAway,SeasonLossAway,SeasonGFAway,SeasonGAAway,SeasonGDAway,SeasonPointsAway,QualificationOrRelegationAway
0,9394,1993,8,14,NaN,NaN,NaN,West Ham,Wimbledon,0,2,A,0.0,0.0,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,42.0,13.0,17.0,12.0,47.0,48.0,-1.0,56.0,Not Applicable,6.0,42.0,18.0,16.0,8.0,56.0,53.0,3.0,70.0,Not Applicable
1,9394,1993,8,14,NaN,NaN,NaN,Southampton,Everton,0,2,A,0.0,2.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,42.0,12.0,12.0,18.0,49.0,57.0,-8.0,48.0,Not Applicable,17.0,42.0,12.0,13.0,17.0,41.0,43.0,-2.0,49.0,Not Applicable
2,9394,1993,8,14,NaN,NaN,NaN,Sheffield,Swindon,3,1,H,1.0,1.0,D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,42.0,13.0,5.0,24.0,43.0,60.0,-17.0,44.0,Relegation to the Football League First Division,22.0,42.0,7.0,9.0,26.0,38.0,83.0,-45.0,30.0,Relegation to the Football League First Division
3,9394,1993,8,14,NaN,NaN,NaN,Oldham,Ipswich,0,3,A,0.0,2.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,42.0,9.0,16.0,17.0,42.0,56.0,-14.0,43.0,Relegation to the Football League First Division,19.0,42.0,9.0,18.0,15.0,35.0,48.0,-13.0,45.0,Not Applicable
4,9394,1993,8,14,NaN,NaN,NaN,Newcastle,Tottenham,0,1,A,0.0,1.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,42.0,23.0,8.0,11.0,82.0,41.0,41.0,77.0,Qualification for the UEFA Cup first round,15.0,42.0,11.0,18.0,13.0,54.0,53.0,1.0,51.0,Qualification for the UEFA Cup first round

In [11]:
df.shape

(12704, 51)

In [8]:
df['Season'].unique()

array(['9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001',
       '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809',
       '0910', '1011', '1112', '1213', '1314', '1415', '1516', '1617',
       '1718', '1819', '1920', '2021', '2122', '2223', '2324', '2425',
       '2526'], dtype=object)

In [12]:
df = df[~df['Season'].isin(['9900', '9899', '9798', '9697', '9596', '9495', '9394'])]

In [13]:
df.shape

(9880, 51)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9880 entries, 2824 to 12703
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Season                         9880 non-null   object
 1   Year                           9880 non-null   int64
 2   Month                          9880 non-null   int64
 3   Day                            9880 non-null   int64
 4   WeekDay                        9880 non-null   object
 5   Time                           9880 non-null   object
 6   Round                          9880 non-null   float64
 7   HomeTeam                       9880 non-null   object
 8   AwayTeam                       9880 non-null   object
 9   HomeGoal                       9880 non-null   int64
 10  AwayGoal                       9880 non-null   int64
 11  Result                         9880 non-null   object
 12  HomeGoal-HalfTime              9880 non-null   float64
 13  AwayGoal-HalfTime              9880 non-null   float64
 14  Result-HalfTime                9880 non-null   object
 15  Attendance                     9880 non-null   float64
 16  Referee                        9880 non-null   object
 17  HomeShot                       9880 non-null   float64
 18  AwayShot                       9880 non-null   float64
 19  HomeOnTargetShot               9880 non-null   float64
 20  AwayOnTargetShot               9880 non-null   float64
 21  HomeFoul                       9880 non-null   float64
 22  AwayFoul                       9880 non-null   float64
 23  HomeCorner                     9880 non-null   float64
 24  AwayCorner                     9880 non-null   float64
 25  HomeYellow                     9880 non-null   float64
 26  AwayYellow                     9880 non-null   float64
 27  HomeRed                        9880 non-null   float64
 28  AwayRed                        9880 non-null   float64
 29  XGHome                         2858 non-null   float64
 30  XGAway                         2857 non-null   float64
 31  SeasonPosHome                  9880 non-null   float64
 32  SeasonPlayedHome               9880 non-null   float64
 33  SeasonWinHome                  9880 non-null   float64
 34  SeasonDrawHome                 9880 non-null   float64
 35  SeasonLossHome                 9880 non-null   float64
 36  SeasonGFHome                   9880 non-null   float64
 37  SeasonGAHome                   9880 non-null   float64
 38  SeasonGDHome                   9880 non-null   float64
 39  SeasonPointsHome               9880 non-null   float64
 40  QualificationOrRelegationHome  9880 non-null   object
 41  SeasonPosAway                  9880 non-null   float64
 42  SeasonPlayedAway               9880 non-null   float64
 43  SeasonWinAway                  9880 non-null   float64
 44  SeasonDrawAway                 9880 non-null   float64
 45  SeasonLossAway                 9880 non-null   float64
 46  SeasonGFAway                   9880 non-null   float64
 47  SeasonGAAway                   9880 non-null   float64
 48  SeasonGDAway                   9880 non-null   float64
 49  SeasonPointsAway               9880 non-null   float64
 50  QualificationOrRelegationAway  9880 non-null   object
dtypes: float64(36), int64(5), object(10)
memory usage: 3.9+ MB

In [15]:
df.columns

Index(['Season', 'Year', 'Month', 'Day', 'WeekDay', 'Time', 'Round',
       'HomeTeam', 'AwayTeam', 'HomeGoal', 'AwayGoal', 'Result',
       'HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime',
       'Attendance', 'Referee', 'HomeShot', 'AwayShot', 'HomeOnTargetShot',
       'AwayOnTargetShot', 'HomeFoul', 'AwayFoul', 'HomeCorner', 'AwayCorner',
       'HomeYellow', 'AwayYellow', 'HomeRed', 'AwayRed', 'XGHome', 'XGAway',
       'SeasonPosHome', 'SeasonPlayedHome', 'SeasonWinHome', 'SeasonDrawHome',
       'SeasonLossHome', 'SeasonGFHome', 'SeasonGAHome', 'SeasonGDHome',
       'SeasonPointsHome', 'QualificationOrRelegationHome', 'SeasonPosAway',
       'SeasonPlayedAway', 'SeasonWinAway', 'SeasonDrawAway', 'SeasonLossAway',
       'SeasonGFAway', 'SeasonGAAway', 'SeasonGDAway', 'SeasonPointsAway',
       'QualificationOrRelegationAway'],
      dtype='object')

---

$$ Season $$

In [16]:
df['Season'].unique()

array(['0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708',
       '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516',
       '1617', '1718', '1819', '1920', '2021', '2122', '2223', '2324',
       '2425', '2526'], dtype=object)

---

$$ Year $$

In [17]:
df['Year'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
       2022, 2023, 2024, 2025, 2026])

---

$$ Month $$

In [26]:
df['Month'].drop_duplicates().sort_values()

3029      1
3069      2
3098      3
3128      4
3178      5
10332     6
10358     7
2824      8
2853      9
2900     10
2933     11
2973     12
Name: Month, dtype: int64

---

$$ Day $$

In [27]:
df['Day'].drop_duplicates().sort_values()

2900     1
2973     2
2981     3
2933     4
2853     5
2857     6
3078     7
3135     8
2863     9
2871    10
2872    11
2951    12
3039    13
2903    14
2911    15
2873    16
2880    17
2953    18
2824    19
2833    20
2834    21
2835    22
2838    23
2892    24
2963    25
2843    26
2852    27
2923    28
2931    29
2893    30
3062    31
Name: Day, dtype: int64

---

$$ WeekDay $$

In [25]:
df['WeekDay'].unique()

array(['Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Fri', 'Thu', '52354', '26438',
       '34876', '51847', '36121', '47106', '26837', '17278', '75500',
       '38130', '27191', '22326', '41780', '25117', '41794', '26372',
       '75498', '47054', '25640', '25756', '20365', '60071', '44792',
       '27531', '36063', '44614', '27544', '25700', '36192', '41500',
       '16658', '60112', '23001', '18550', '27488', '52355', '37011',
       '20242', '44991', '41581', '25671', '18178', '52351', '25002',
       '46158', '75591', '60068', '37428', '34563', '17391', '75572',
       '45009', '26842', '49403', '35005', '34962', '44901', '41784',
       '60089', '24097', '46402', '44752', '44832', '60079', '26250',
       '39312', '75586', '35244', '41548', '31728', '36170', '33217',
       '26783', '18169', '24102', '24832', '50703', '75605', '20583',
       '26317', '36519', '38594', '32070', '38625', '36004', '22297',
       '41639', '17784', '20604', '43760', '34966', '45007', '24139',
       '34692', '34544', '20561', '26460', '47189', '31946', '23388',
       '36190', '24087', '41988', '39475', '22859', '34973', '31539'],
      dtype=object)

In [35]:
pd.to_datetime(weekday_df[['Year', 'Month', 'Day']]).dt.weekday.unique()

array([5, 6, 0, 2, 1], dtype=int32)

In [38]:
codes_list = [
        '52354', '26438',
       '34876', '51847', '36121', '47106', '26837', '17278', '75500',
       '38130', '27191', '22326', '41780', '25117', '41794', '26372',
       '75498', '47054', '25640', '25756', '20365', '60071', '44792',
       '27531', '36063', '44614', '27544', '25700', '36192', '41500',
       '16658', '60112', '23001', '18550', '27488', '52355', '37011',
       '20242', '44991', '41581', '25671', '18178', '52351', '25002',
       '46158', '75591', '60068', '37428', '34563', '17391', '75572',
       '45009', '26842', '49403', '35005', '34962', '44901', '41784',
       '60089', '24097', '46402', '44752', '44832', '60079', '26250',
       '39312', '75586', '35244', '41548', '31728', '36170', '33217',
       '26783', '18169', '24102', '24832', '50703', '75605', '20583',
       '26317', '36519', '38594', '32070', '38625', '36004', '22297',
       '41639', '17784', '20604', '43760', '34966', '45007', '24139',
       '34692', '34544', '20561', '26460', '47189', '31946', '23388',
       '36190', '24087', '41988', '39475', '22859', '34973', '31539'
]

In [39]:
filtered_df = df[df['WeekDay'].isin(codes_list)].copy()

In [30]:
weekday_df.shape

(162, 51)

In [40]:
filtered_df['WeekDayNumber'] = pd.to_datetime(
    filtered_df[['Year', 'Month', 'Day']]
).dt.weekday

In [41]:
day_mapping = {
    5: 'Sat',
    6: 'Sun',
    0: 'Mon',
    1: 'Tue',
    2: 'Wed'
}
filtered_df['WeekDayName'] = filtered_df['WeekDayNumber'].map(day_mapping)

In [42]:
filtered_df = filtered_df.dropna(subset=['WeekDayName'])

In [43]:
filtered_df.head()

,Season,Year,Month,Day,WeekDay,Time,Round,HomeTeam,AwayTeam,HomeGoal,AwayGoal,Result,HomeGoal-HalfTime,AwayGoal-HalfTime,Result-HalfTime,Attendance,Referee,HomeShot,AwayShot,HomeOnTargetShot,AwayOnTargetShot,HomeFoul,AwayFoul,HomeCorner,AwayCorner,HomeYellow,AwayYellow,HomeRed,AwayRed,XGHome,XGAway,SeasonPosHome,SeasonPlayedHome,SeasonWinHome,SeasonDrawHome,SeasonLossHome,SeasonGFHome,SeasonGAHome,SeasonGDHome,SeasonPointsHome,QualificationOrRelegationHome,SeasonPosAway,SeasonPlayedAway,SeasonWinAway,SeasonDrawAway,SeasonLossAway,SeasonGFAway,SeasonGAAway,SeasonGDAway,SeasonPointsAway,QualificationOrRelegationAway,WeekDayNumber,WeekDayName
7007,1112,2011,8,13,52354,52354,52354.0,Newcastle,Arsenal,0,0,D,0.0,0.0,D,52354.0,P Walton,6.0,9.0,1.0,4.0,9.0,11.0,2.0,5.0,3.0,5.0,0.0,1.0,NaN,NaN,5.0,38.0,19.0,8.0,11.0,56.0,51.0,5.0,65.0,Qualification for the Europa League play-off r...,3.0,38.0,21.0,7.0,10.0,74.0,49.0,25.0,70.0,Qualification for the Champions League group s...,5,Sat
7011,1112,2011,8,14,26438,26438,26438.0,West Brom,Man United,1,2,A,1.0,1.0,D,26438.0,M Jones,14.0,11.0,8.0,5.0,16.0,9.0,6.0,5.0,3.0,2.0,0.0,0.0,NaN,NaN,10.0,38.0,13.0,8.0,17.0,45.0,52.0,-7.0,47.0,Not Applicable,2.0,38.0,28.0,5.0,5.0,89.0,33.0,56.0,89.0,Qualification for the Champions League group s...,6,Sun
7017,1112,2011,8,20,34876,34876,34876.0,Everton,QPR,0,1,A,0.0,1.0,A,34876.0,K Friend,14.0,4.0,7.0,3.0,12.0,9.0,2.0,1.0,1.0,1.0,0.0,0.0,NaN,NaN,7.0,38.0,15.0,11.0,12.0,50.0,40.0,10.0,56.0,Not Applicable,17.0,38.0,10.0,7.0,21.0,43.0,66.0,-23.0,37.0,Not Applicable,5,Sat
7030,1112,2011,8,28,51847,51847,51847.0,Newcastle,Fulham,2,1,H,0.0,0.0,D,51847.0,K Friend,13.0,16.0,9.0,9.0,19.0,8.0,6.0,6.0,2.0,1.0,0.0,0.0,NaN,NaN,5.0,38.0,19.0,8.0,11.0,56.0,51.0,5.0,65.0,Qualification for the Europa League play-off r...,9.0,38.0,14.0,10.0,14.0,48.0,51.0,-3.0,52.0,Not Applicable,6,Sun
7031,1112,2011,8,28,36121,36121,36121.0,Tottenham,Man City,1,5,A,0.0,2.0,A,36121.0,P Dowd,15.0,22.0,10.0,12.0,11.0,9.0,10.0,5.0,2.0,4.0,0.0,0.0,NaN,NaN,4.0,38.0,20.0,9.0,9.0,66.0,41.0,25.0,69.0,Qualification for the Europa League group stag...,1.0,38.0,28.0,5.0,5.0,93.0,29.0,64.0,89.0,Qualification for the Champions League group s...,6,Sun

In [44]:
filtered_df.shape

(162, 53)

In [45]:
filtered_df['WeekDay'] = filtered_df['WeekDayName']

In [48]:
filtered_df.drop(columns=['WeekDayNumber', 'WeekDayName'], inplace=True)

In [49]:
filtered_df.shape

(162, 51)

In [50]:
mask = df.set_index(['Year', 'Month', 'Day', 'HomeTeam', 'AwayTeam']).index.isin(
    filtered_df.set_index(['Year', 'Month', 'Day', 'HomeTeam', 'AwayTeam']).index
)
df_remaining = df[~mask]

df = pd.concat([df_remaining, filtered_df])

df = df.sort_index().reset_index(drop=True)

In [51]:
df.shape

(9880, 51)

In [54]:
df.head()

,Season,Year,Month,Day,WeekDay,Time,Round,HomeTeam,AwayTeam,HomeGoal,AwayGoal,Result,HomeGoal-HalfTime,AwayGoal-HalfTime,Result-HalfTime,Attendance,Referee,HomeShot,AwayShot,HomeOnTargetShot,AwayOnTargetShot,HomeFoul,AwayFoul,HomeCorner,AwayCorner,HomeYellow,AwayYellow,HomeRed,AwayRed,XGHome,XGAway,SeasonPosHome,SeasonPlayedHome,SeasonWinHome,SeasonDrawHome,SeasonLossHome,SeasonGFHome,SeasonGAHome,SeasonGDHome,SeasonPointsHome,QualificationOrRelegationHome,SeasonPosAway,SeasonPlayedAway,SeasonWinAway,SeasonDrawAway,SeasonLossAway,SeasonGFAway,SeasonGAAway,SeasonGDAway,SeasonPointsAway,QualificationOrRelegationAway
0,0001,2000,8,19,Sat,15:00,1.0,Charlton,Man City,4,0,H,2.0,0.0,H,20043.0,Rob Harris,17.0,8.0,14.0,4.0,13.0,12.0,6.0,6.0,1.0,2.0,0.0,0.0,NaN,NaN,9.0,38.0,14.0,10.0,14.0,50.0,57.0,-7.0,52.0,Not Applicable,18.0,38.0,8.0,10.0,20.0,41.0,65.0,-24.0,34.0,Relegation to the Football League First Division
1,0001,2000,8,19,Sat,15:00,1.0,Leeds,Everton,2,0,H,2.0,0.0,H,40010.0,Dermot Gallagher,17.0,12.0,8.0,6.0,21.0,20.0,6.0,4.0,1.0,3.0,0.0,0.0,NaN,NaN,4.0,38.0,20.0,8.0,10.0,64.0,43.0,21.0,68.0,Qualification for the UEFA Cup first round[a],16.0,38.0,11.0,9.0,18.0,45.0,59.0,-14.0,42.0,Not Applicable
2,0001,2000,8,19,Sat,15:00,1.0,Derby,Southampton,2,2,D,1.0,2.0,A,27223.0,Andy D'Urso,6.0,13.0,4.0,6.0,11.0,13.0,5.0,8.0,1.0,1.0,0.0,0.0,NaN,NaN,17.0,38.0,10.0,12.0,16.0,37.0,59.0,-22.0,42.0,Not Applicable,10.0,38.0,14.0,10.0,14.0,40.0,48.0,-8.0,52.0,Not Applicable
3,0001,2000,8,19,Sat,15:00,1.0,Chelsea,West Ham,4,2,H,1.0,0.0,H,34914.0,Graham Barber,17.0,12.0,10.0,5.0,19.0,14.0,7.0,7.0,1.0,2.0,0.0,0.0,NaN,NaN,6.0,38.0,17.0,10.0,11.0,68.0,45.0,23.0,61.0,Qualification for the UEFA Cup first round[a],15.0,38.0,10.0,12.0,16.0,45.0,50.0,-5.0,42.0,Not Applicable
4,0001,2000,8,19,Sat,15:00,1.0,Tottenham,Ipswich,3,1,H,2.0,1.0,H,36148.0,Alan Wiley,20.0,15.0,6.0,5.0,14.0,13.0,3.0,4.0,0.0,0.0,0.0,0.0,NaN,NaN,12.0,38.0,13.0,10.0,15.0,47.0,54.0,-7.0,49.0,Not Applicable,5.0,38.0,20.0,6.0,12.0,57.0,42.0,15.0,66.0,Qualification for the UEFA Cup first round[a]

In [55]:
df['WeekDay'].unique()

array(['Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Fri', 'Thu'], dtype=object)

---

$$ Time $$

In [57]:
df['Time'].unique()

array(['15:00', '16:00', '20:00', '19:45', '14:00', '21:00', '12:30',
       '17:00', '11:30', '12:00', '20:45', '13:00', '17:30', '18:35',
       '18:15', '16:05', '12:15', '13:15', '17:05', '19:30', '17:35',
       '12:45', '17:15', '13:30', '18:00', '18:30', '16:30', '13:45',
       '15:30', '14:30', '14:35', '18:20', '16:15', '14:05', '16:10',
       '52354', '26438', '34876', '51847', '36121', '47106', '26837',
       '17278', '75500', '38130', '27191', '22326', '41780', '25117',
       '41794', '26372', '75498', '47054', '25640', '25756', '20365',
       '60071', '44792', '27531', '36063', '44614', '27544', '25700',
       '36192', '41500', '16658', '60112', '23001', '18550', '27488',
       '52355', '37011', '20242', '44991', '41581', '25671', '18178',
       '52351', '25002', '46158', '75591', '60068', '37428', '34563',
       '17391', '75572', '45009', '26842', '49403', '35005', '34962',
       '44901', '41784', '60089', '24097', '46402', '44752', '44832',
       '60079', '26250', '39312', '75586', '35244', '41548', '31728',
       '36170', '33217', '26783', '18169', '24102', '24832', '50703',
       '75605', '20583', '26317', '36519', '38594', '32070', '38625',
       '36004', '22297', '41639', '17784', '20604', '43760', '34966',
       '11:00', '45007', '24139', '34692', '34544', '20561', '26460',
       '47189', '31946', '23388', '36190', '24087', '41988', '39475',
       '22859', '34973', '31539', '16:07', '15:07', '13:37', '19:00',
       '20:30', '14:15', '20:15', '19:15', '22:00', '22:30', '21:15'],
      dtype=object)

In [58]:
codes_list = [
       '52354', '26438', '34876', '51847', '36121', '47106', '26837',
       '17278', '75500', '38130', '27191', '22326', '41780', '25117',
       '41794', '26372', '75498', '47054', '25640', '25756', '20365',
       '60071', '44792', '27531', '36063', '44614', '27544', '25700',
       '36192', '41500', '16658', '60112', '23001', '18550', '27488',
       '52355', '37011', '20242', '44991', '41581', '25671', '18178',
       '52351', '25002', '46158', '75591', '60068', '37428', '34563',
       '17391', '75572', '45009', '26842', '49403', '35005', '34962',
       '44901', '41784', '60089', '24097', '46402', '44752', '44832',
       '60079', '26250', '39312', '75586', '35244', '41548', '31728',
       '36170', '33217', '26783', '18169', '24102', '24832', '50703',
       '75605', '20583', '26317', '36519', '38594', '32070', '38625',
       '36004', '22297', '41639', '17784', '20604', '43760', '34966',
       '11:00', '45007', '24139', '34692', '34544', '20561', '26460',
       '47189', '31946', '23388', '36190', '24087', '41988', '39475',
       '22859', '34973', '31539', '16:07', '15:07', '13:37',
]

In [60]:
df[ df['Time'].isin(codes_list)].shape

(172, 51)

In [ ]:
df[ df['Time'].isin(codes_list)][['HomeTeam', 'AwayTeam', 'Day', 'Month', 'Year']]

            HomeTeam     AwayTeam  Day  Month  Year
4183       Newcastle      Arsenal   13      8  2011
4187       West Brom   Man United   14      8  2011
4193         Everton          QPR   20      8  2011
4206       Newcastle       Fulham   28      8  2011
4207       Tottenham     Man City   28      8  2011
4211        Man City        Wigan   10      9  2011
4217         Norwich    West Brom   11      9  2011
4218             QPR    Newcastle   12      9  2011
4226      Man United      Chelsea   18      9  2011
4227      Sunderland        Stoke   18      9  2011
4230           Stoke   Man United   24      9  2011
4231           Wigan    Tottenham   24      9  2011
4235         Chelsea      Swansea   24      9  2011
4247          Fulham          QPR    2     10  2011
4249         Chelsea      Everton   15     10  2011
4252         Norwich      Swansea   15     10  2011
4267      Man United     Man City   23     10  2011
4312        Man City      Norwich    3     12  2011
4318          Fulham    Liverpool    5     12  2011
4319       West Brom        Wigan   10     12  2011
4320         Swansea       Fulham   10     12  2011
4324         Arsenal      Everton   10     12  2011
4325       Liverpool          QPR   10     12  2011
4326           Stoke    Tottenham   11     12  2011
4338       Tottenham   Sunderland   18     12  2011
4349      Sunderland      Everton   26     12  2011
4354           Stoke  Aston Villa   26     12  2011
4373          Fulham      Arsenal    2      1  2012
4379       Tottenham      Everton   11      1  2012
4383         Chelsea   Sunderland   14      1  2012
4392             QPR        Wigan   21      1  2012
4398         Arsenal   Man United   22      1  2012
4430           Wigan  Aston Villa   25      2  2012
4439           Wigan      Swansea    3      3  2012
4441           Stoke      Norwich    3      3  2012
4447       Newcastle   Sunderland    4      3  2012
4453     Aston Villa       Fulham   10      3  2012
4457         Swansea     Man City   11      3  2012
4459       Liverpool      Everton   13      3  2012
4474         Chelsea    Tottenham   24      3  2012
4477       West Brom    Newcastle   25      3  2012
4483             QPR      Arsenal   31      3  2012
4487       Newcastle    Liverpool    1      4  2012
4501          Fulham      Chelsea    9      4  2012
4505        Man City    West Brom   11      4  2012
4513      Man United  Aston Villa   15      4  2012
4514         Arsenal        Wigan   16      4  2012
4517     Aston Villa   Sunderland   21      4  2012
4531         Everton       Fulham   28      4  2012
4542             QPR        Stoke    6      5  2012
4547      Man United      Swansea    6      5  2012
4549       Liverpool      Chelsea    8      5  2012
4555         Norwich  Aston Villa   13      5  2012
4675       Newcastle      Swansea   17     11  2012
4758        West Ham      Norwich    1      1  2013
4781        West Ham          QPR   19      1  2013
4784       Liverpool      Norwich   19      1  2013
4786         Chelsea      Arsenal   20      1  2013
4794         Arsenal    Liverpool   30      1  2013
4799         Reading      Chelsea   30      1  2013
4812      Sunderland      Arsenal    9      2  2013
4819       Liverpool    West Brom   11      2  2013
4820       Liverpool      Swansea   17      2  2013
4825         Arsenal  Aston Villa   23      2  2013
4832           Stoke     West Ham    2      3  2013
4833      Sunderland       Fulham    2      3  2013
4834      Man United      Norwich    2      3  2013
4835         Everton      Reading    2      3  2013
4836         Chelsea    West Brom    2      3  2013
4837     Southampton          QPR    2      3  2013
4838       Tottenham      Arsenal    3      3  2013
4839     Aston Villa     Man City    4      3  2013
4840         Norwich  Southampton    9      3  2013
4841             QPR   Sunderland    9      3  2013
4842         Reading  Aston Villa    9      3  2013
4843       West Brom      Swansea    9      3  2013
4844       Liverpool    Tottenham   10      3  2013
4845       Newcastle        Stoke   10      3  2013
4846      Man United      Reading   16      3  2013
4847         Swansea      Arsenal   16      3  2013
4848           Stoke    West Brom   16      3  2013
4849         Everton     Man City   16      3  2013
4850     Aston Villa          QPR   16      3  2013
4851     Southampton    Liverpool   16      3  2013
4852      Sunderland      Norwich   17      3  2013
4853       Tottenham       Fulham   17      3  2013
4854           Wigan    Newcastle   17      3  2013
4855         Chelsea     West Ham   17      3  2013
4856           Wigan      Norwich   30      3  2013
4857         Swansea    Tottenham   30      3  2013
4858      Sunderland   Man United   30      3  2013
4859        West Ham    West Brom   30      3  2013
4862         Arsenal      Reading   30      3  2013
4865          Fulham          QPR    1      4  2013
4866         Norwich      Swansea    6      4  2013
4868           Stoke  Aston Villa    6      4  2013
4870       Tottenham      Everton    7      4  2013
4871             QPR        Wigan    7      4  2013
4872       Liverpool     West Ham    7      4  2013
4873       Newcastle       Fulham    7      4  2013
4874         Chelsea   Sunderland    7      4  2013
4875      Man United     Man City    8      4  2013
4877     Aston Villa       Fulham   13      4  2013
4878         Everton          QPR   13      4  2013
4879         Reading    Liverpool   13      4  2013
4881       Newcastle   Sunderland   14      4  2013
4882           Stoke   Man United   14      4  2013
4883         Arsenal      Everton   16      4  2013
4884          Fulham      Chelsea   17      4  2013
4885        Man City        Wigan   17      4  2013
4886        West Ham   Man United   17      4  2013
4887       West Brom    Newcastle   20      4  2013
4888        West Ham        Wigan   20      4  2013
4889         Swansea  Southampton   20      4  2013
4890             QPR        Stoke   20      4  2013
4891          Fulham      Arsenal   20      4  2013
4892      Sunderland      Everton   20      4  2013
4893         Norwich      Reading   20      4  2013
4894       Liverpool      Chelsea   21      4  2013
4895       Tottenham     Man City   21      4  2013
4896      Man United  Aston Villa   22      4  2013
4897         Everton       Fulham   27      4  2013
4898        Man City     West Ham   27      4  2013
4899       Newcastle    Liverpool   27      4  2013
4900           Stoke      Norwich   27      4  2013
4901           Wigan    Tottenham   27      4  2013
4902     Southampton    West Brom   27      4  2013
4903         Arsenal   Man United   28      4  2013
4904         Chelsea      Swansea   28      4  2013
4905         Reading          QPR   28      4  2013
4906     Aston Villa   Sunderland   29      4  2013
4907       West Brom        Wigan    4      5  2013
4908        West Ham    Newcastle    4      5  2013
4909       Tottenham  Southampton    4      5  2013
4910             QPR      Arsenal    4      5  2013
4911         Norwich  Aston Villa    4      5  2013
4912          Fulham      Reading    4      5  2013
4913         Swansea     Man City    4      5  2013
4914       Liverpool      Everton    5      5  2013
4915      Man United      Chelsea    5      5  2013
4916      Sunderland        Stoke    6      5  2013
4917        Man City    West Brom    7      5  2013
4918           Wigan      Swansea    7      5  2013
4919         Chelsea    Tottenham    8      5  2013
4921      Sunderland  Southampton   12      5  2013
4922           Stoke    Tottenham   12      5  2013
4923             QPR    Newcastle   12      5  2013
4924         Everton     West Ham   12      5  2013
4925      Man United      Swansea   12      5  2013
4926          Fulham    Liverpool   12      5  2013
4927         Norwich    West Brom   12      5  2013
4928         Arsenal        Wigan   14      5  2013
4929         Reading     Man City   14      5  2013
4930        West Ham      Reading   19      5  2013
4931       West Brom   Man United   19      5  2013
4932           Wigan  Aston Villa   19      5  2013
4933         Swansea       Fulham   19      5  2013
4934       Tottenham   Sunderland   19      5  2013
4935       Newcastle      Arsenal   19      5  2013
4936     Southampton        Stoke   19      5  2013
4937         Chelsea      Everton   19      5  2013
4938       Liverpool          QPR   19      5  2013
4939        Man City      Norwich   19      5  2013
5118         Chelsea      Swansea   26     12  2013
5266       West Brom    Tottenham   12      4  2014
5267      Sunderland      Everton   12      4  2014
5268     Southampton      Cardiff   12      4  2014
5269          Fulham      Norwich   12      4  2014
5270  Crystal Palace  Aston Villa   12      4  2014
5271           Stoke    Newcastle   12      4  2014
5272       Liverpool     Man City   13      4  2014
5273         Swansea      Chelsea   13      4  2014

In [65]:
time_mapping = {
    (2011, 8, 13, 'Newcastle', 'Arsenal'):"12:30",
    (2011, 8, 14, 'West Brom', 'Man United'):"16:00",
    (2011, 8, 20, 'Everton', 'QPR'):"15:00",
    (2011, 8, 28, 'Newcastle', 'Fulham'):"17:00",
    (2011, 8, 28, 'Tottenham', 'Man City'):"17:30",
    (2011, 9, 10, 'Man City', 'Wigan'):"16:00",
    (2011, 9, 11, 'Norwich', 'West Brom'):"14:30",
    (2011, 9, 12, 'QPR', 'Newcastle'):"15:00",
    (2011, 9, 18, 'Man United', 'Chelsea'):"20:00",
    (2011, 9, 18, 'Sunderland', 'Stoke'):"16:00",
    (2011, 9, 24, 'Stoke', 'Man United'):"17:30",
    (2011, 9, 24, 'Wigan', 'Tottenham'):"16:00",
    (2011, 9, 24, 'Chelsea', 'Swansea'):"14:00",
    (2011, 10, 2, 'Fulham', 'QPR'):"19:00",
    (2011, 10, 15, 'Chelsea', 'Everton'):"21:30",
    (2011, 10, 15, 'Norwich', 'Swansea'):"19:00",
    (2011, 10, 23, 'Man United', 'Man City'):"17:30",
    (2011, 12, 3, 'Man City', 'Norwich'):"15:00",
    (2011, 12, 5, 'Fulham', 'Liverpool'):"20:00",
    (2011, 12, 10, 'West Brom', 'Wigan'):"16:00",
    (2011, 12, 10, 'Swansea', 'Fulham'):"16:00",
    (2011, 12, 10, 'Arsenal', 'Everton'):"16:00",
    (2011, 12, 10, 'Liverpool', 'QPR'):"19:00",
    (2011, 12, 11, 'Stoke', 'Tottenham'):"16:00",
    (2011, 12, 18, 'Tottenham', 'Sunderland'):"16:00",
    (2011, 12, 26, 'Sunderland', 'Everton'):"16:00",
    (2011, 12, 26, 'Stoke', 'Aston Villa'):"19:45",
    (2012, 1, 2, 'Fulham', 'Arsenal'):"18:30",
    (2012, 1, 11, 'Tottenham', 'Everton'):"20:45",
    (2012, 1, 14, 'Chelsea', 'Sunderland'):"16:00",
    (2012, 1, 21, 'QPR', 'Wigan'):"16:00",
    (2012, 1, 22, 'Arsenal', 'Man United'):"20:00",
    (2012, 2, 25, 'Wigan', 'Aston Villa'):"15:00",
    (2012, 3, 3, 'Wigan', 'Swansea'):"15:00",
    (2012, 3, 3, 'Stoke', 'Norwich'):"16:00",
    (2012, 3, 4, 'Newcastle', 'Sunderland'):"13:00",
    (2012, 3, 10, 'Aston Villa', 'Fulham'):"15:00",
    (2012, 3, 11, 'Swansea', 'Man City'):"15:00",
    (2012, 3, 13, 'Liverpool', 'Everton'):"21:00",
    (2012, 3, 24, 'Chelsea', 'Tottenham'):"13:45",
    (2012, 3, 25, 'West Brom', 'Newcastle'):"18:30",
    (2012, 3, 31, 'QPR', 'Arsenal'):"16:00",
    (2012, 4, 1, 'Newcastle', 'Liverpool'):"17:00",
    (2012, 4, 9, 'Fulham', 'Chelsea'):"21:00",
    (2012, 4, 11, 'Man City', 'West Brom'):"20:45",
    (2012, 4, 15, 'Man United', 'Aston Villa'):"17:00",
    (2012, 4, 16, 'Arsenal', 'Wigan'):"21:00",
    (2012, 4, 21, 'Aston Villa', 'Sunderland'):"16:00",
    (2012, 4, 28, 'Everton', 'Fulham'):"15:00",
    (2012, 5, 6, 'QPR', 'Stoke'):"15:00",
    (2012, 5, 6, 'Man United', 'Swansea'):"17:00",
    (2012, 5, 8, 'Liverpool', 'Chelsea'):"15:00",
    (2012, 5, 13, 'Norwich', 'Aston Villa'):"10:00",
    (2012, 11, 17, 'Newcastle', 'Swansea'):"16:00",
    (2013, 1, 1, 'West Ham', 'Norwich'):"16:00",
    (2013, 1, 19, 'West Ham', 'QPR'):"16:00",
    (2013, 1, 19, 'Liverpool', 'Norwich'):"16:00",
    (2013, 1, 20, 'Chelsea', 'Arsenal'):"14:30",
    (2013, 1, 30, 'Arsenal', 'Liverpool'):"20:45",
    (2013, 1, 30, 'Reading', 'Chelsea'):"21:00",
    (2013, 2, 9, 'Sunderland', 'Arsenal'):"16:00",
    (2013, 2, 11, 'Liverpool', 'West Brom'):"21:00",
    (2013, 2, 17, 'Liverpool', 'Swansea'):"16:00",
    (2013, 2, 23, 'Arsenal', 'Aston Villa'):"16:00",
    (2013, 3, 2, 'Stoke', 'West Ham'):"15:00",
    (2013, 3, 2, 'Sunderland', 'Fulham'):"16:00",
    (2013, 3, 2, 'Man United', 'Norwich'):"16:00",
    (2013, 3, 2, 'Everton', 'Reading'):"15:00",
    (2013, 3, 2, 'Chelsea', 'West Brom'):"16:00",
    (2013, 3, 2, 'Southampton', 'QPR'):"18:30:",
    (2013, 3, 3, 'Tottenham', 'Arsenal'):"17:00",
    (2013, 3, 4, 'Aston Villa', 'Man City'):"21:00",
    (2013, 3, 9, 'Norwich', 'Southampton'):"16:00",
    (2013, 3, 9, 'QPR', 'Sunderland'):"16:00",
    (2013, 3, 9, 'Reading', 'Aston Villa'):"16:00",
    (2013, 3, 9, 'West Brom', 'Swansea'):"14:30",
    (2013, 3, 10, 'Liverpool', 'Tottenham'): "16:00",  # Source: Sky Sports
    (2013, 3, 10, 'Newcastle', 'Stoke'): "16:00",      # Source: Sky Sports

    (2013, 3, 16, 'Man United', 'Reading'): "15:00",   # Standard Saturday 3pm
    (2013, 3, 16, 'Swansea', 'Arsenal'): "17:30",      # Source: ESPN
    (2013, 3, 16, 'Stoke', 'West Brom'): "15:00",      # Standard Saturday 3pm
    (2013, 3, 16, 'Everton', 'Man City'): "12:45",     # Source: Sky Sports
    (2013, 3, 16, 'Aston Villa', 'QPR'): "15:00",      # Standard Saturday 3pm
    (2013, 3, 16, 'Southampton', 'Liverpool'): "17:30", # Source: ESPN

    (2013, 3, 17, 'Sunderland', 'Norwich'): "13:30",   # Sunday early kickoff
    (2013, 3, 17, 'Tottenham', 'Fulham'): "16:00",     # Source: Sky Sports
    (2013, 3, 17, 'Wigan', 'Newcastle'): "15:00",      # Sunday 3pm (moved due to TV)
    (2013, 3, 17, 'Chelsea', 'West Ham'): "16:00",     # Source: Sky Sports

    (2013, 3, 30, 'Wigan', 'Norwich'): "15:00",        # Standard Saturday 3pm
    (2013, 3, 30, 'Swansea', 'Tottenham'): "17:30",    # Source: Sky Sports
    (2013, 3, 30, 'Sunderland', 'Man United'): "12:45", # Source: Sky Sports
    (2013, 3, 30, 'West Ham', 'West Brom'): "15:00",   # Standard Saturday 3pm
    (2013, 3, 30, 'Arsenal', 'Reading'): "15:00",      # Standard Saturday 3pm

    (2013, 4, 1, 'Fulham', 'QPR'): "20:00",            # Monday Night Football

    (2013, 4, 6, 'Norwich', 'Swansea'): "15:00",       # Standard Saturday 3pm
    (2013, 4, 6, 'Stoke', 'Aston Villa'): "15:00",     # Standard Saturday 3pm

    (2013, 4, 7, 'Tottenham', 'Everton'): "13:30",     # Sunday early kickoff
    (2013, 4, 7, 'QPR', 'Wigan'): "15:00",             # Sunday 3pm
    (2013, 4, 7, 'Liverpool', 'West Ham'): "16:00",    # Source: Sky Sports
    (2013, 4, 7, 'Newcastle', 'Fulham'): "15:00",      # Sunday 3pm
    (2013, 4, 7, 'Chelsea', 'Sunderland'): "15:00",    # Sunday 3pm

    (2013, 4, 8, 'Man United', 'Man City'): "20:00",   # Monday Night Football

    (2013, 4, 13, 'Aston Villa', 'Fulham'): "15:00",   # Standard Saturday 3pm
    (2013, 4, 13, 'Everton', 'QPR'): "15:00",          # Standard Saturday 3pm
    (2013, 4, 13, 'Reading', 'Liverpool'): "12:45",    # Source: Sky Sports

    (2013, 4, 14, 'Newcastle', 'Sunderland'): "12:00", # Tyne-Wear derby (Sky Sports)
    (2013, 4, 14, 'Stoke', 'Man United'): "14:05",     # Source: Sky Sports

    (2013, 4, 16, 'Arsenal', 'Everton'): "19:45",      # Tuesday night (Sky Sports)

    (2013, 4, 17, 'Fulham', 'Chelsea'): "20:00",       # Wednesday night (Sky Sports)
    (2013, 4, 17, 'Man City', 'Wigan'): "19:45",       # Wednesday night
    (2013, 4, 17, 'West Ham', 'Man United'): "19:45",  # Wednesday night (Sky Sports)

    (2013, 4, 20, 'West Brom', 'Newcastle'): "15:00",  # Standard Saturday 3pm
    (2013, 4, 20, 'West Ham', 'Wigan'): "15:00",       # Standard Saturday 3pm
    (2013, 4, 20, 'Swansea', 'Southampton'): "15:00",  # Standard Saturday 3pm
    (2013, 4, 20, 'QPR', 'Stoke'): "15:00",            # Standard Saturday 3pm
    (2013, 4, 20, 'Fulham', 'Arsenal'): "15:00",       # Standard Saturday 3pm
    (2013, 4, 20, 'Sunderland', 'Everton'): "15:00",   # Standard Saturday 3pm
    (2013, 4, 20, 'Norwich', 'Reading'): "15:00",      # Standard Saturday 3pm

    (2013, 4, 21, 'Liverpool', 'Chelsea'): "16:00",    # Source: Sky Sports
    (2013, 4, 21, 'Tottenham', 'Man City'): "13:30",   # Source: Sky Sports

    (2013, 4, 22, 'Man United', 'Aston Villa'): "20:00", # Monday Night Football

    (2013, 4, 27, 'Everton', 'Fulham'): "15:00",       # Standard Saturday 3pm
    (2013, 4, 27, 'Man City', 'West Ham'): "15:00",    # Standard Saturday 3pm
    (2013, 4, 27, 'Newcastle', 'Liverpool'): "15:00",  # Standard Saturday 3pm
    (2013, 4, 27, 'Stoke', 'Norwich'): "15:00",        # Standard Saturday 3pm
    (2013, 4, 27, 'Wigan', 'Tottenham'): "15:00",      # Standard Saturday 3pm
    (2013, 4, 27, 'Southampton', 'West Brom'): "15:00", # Standard Saturday 3pm

    (2013, 4, 28, 'Arsenal', 'Man United'): "16:00",   # Source: Sky Sports
    (2013, 4, 28, 'Chelsea', 'Swansea'): "13:30",      # Source: Sky Sports
    (2013, 4, 28, 'Reading', 'QPR'): "15:00",          # Sunday 3pm

    (2013, 4, 29, 'Aston Villa', 'Sunderland'): "20:00", # Monday Night Football

    (2013, 5, 4, 'West Brom', 'Wigan'): "15:00",       # Standard Saturday 3pm
    (2013, 5, 4, 'West Ham', 'Newcastle'): "15:00",    # Standard Saturday 3pm
    (2013, 5, 4, 'Tottenham', 'Southampton'): "15:00", # Standard Saturday 3pm
    (2013, 5, 4, 'QPR', 'Arsenal'): "12:45",           # Source: Sky Sports
    (2013, 5, 4, 'Norwich', 'Aston Villa'): "15:00",   # Standard Saturday 3pm
    (2013, 5, 4, 'Fulham', 'Reading'): "15:00",        # Standard Saturday 3pm
    (2013, 5, 4, 'Swansea', 'Man City'): "17:30",      # Source: Sky Sports

    (2013, 5, 5, 'Liverpool', 'Everton'): "13:30",     # Source: Sky Sports
    (2013, 5, 5, 'Man United', 'Chelsea'): "16:00",    # Source: Sky Sports

    (2013, 5, 6, 'Sunderland', 'Stoke'): "20:00",      # Monday Night Football

    (2013, 5, 7, 'Man City', 'West Brom'): "19:45",    # Tuesday night
    (2013, 5, 7, 'Wigan', 'Swansea'): "19:45",         # Tuesday night

    (2013, 5, 8, 'Chelsea', 'Tottenham'): "19:45",     # Wednesday night (Sky Sports)

    (2013, 5, 12, 'Sunderland', 'Southampton'): "15:00", # Standard Sunday 3pm
    (2013, 5, 12, 'Stoke', 'Tottenham'): "15:00",      # Standard Sunday 3pm
    (2013, 5, 12, 'QPR', 'Newcastle'): "15:00",        # Standard Sunday 3pm
    (2013, 5, 12, 'Everton', 'West Ham'): "15:00",     # Standard Sunday 3pm
    (2013, 5, 12, 'Man United', 'Swansea'): "15:00",   # Standard Sunday 3pm
    (2013, 5, 12, 'Fulham', 'Liverpool'): "15:00",     # Standard Sunday 3pm
    (2013, 5, 12, 'Norwich', 'West Brom'): "15:00",    # Standard Sunday 3pm

    (2013, 5, 14, 'Arsenal', 'Wigan'): "19:45",        # Tuesday night (Sky Sports)
    (2013, 5, 14, 'Reading', 'Man City'): "20:00",     # Tuesday night (Sky Sports)

    (2013, 5, 19, 'West Ham', 'Reading'): "16:00",     # Final day, simultaneous kickoff
    (2013, 5, 19, 'West Brom', 'Man United'): "16:00", # Final day, simultaneous kickoff
    (2013, 5, 19, 'Wigan', 'Aston Villa'): "16:00",    # Final day, simultaneous kickoff
    (2013, 5, 19, 'Swansea', 'Fulham'): "16:00",       # Final day, simultaneous kickoff
    (2013, 5, 19, 'Tottenham', 'Sunderland'): "16:00", # Final day, simultaneous kickoff
    (2013, 5, 19, 'Newcastle', 'Arsenal'): "16:00",    # Final day, simultaneous kickoff
    (2013, 5, 19, 'Southampton', 'Stoke'): "16:00",    # Final day, simultaneous kickoff
    (2013, 5, 19, 'Chelsea', 'Everton'): "16:00",      # Final day, simultaneous kickoff
    (2013, 5, 19, 'Liverpool', 'QPR'): "16:00",        # Final day, simultaneous kickoff
    (2013, 5, 19, 'Man City', 'Norwich'): "16:00",     # Final day, simultaneous kickoff

    # ---- December 2013 ----
    (2013, 12, 26, 'Chelsea', 'Swansea'): "15:00",     # Boxing Day standard 3pm

    # ---- April 2014 ----
    (2014, 4, 12, 'West Brom', 'Tottenham'): "15:00",  # Standard Saturday 3pm
    (2014, 4, 12, 'Sunderland', 'Everton'): "15:00",   # Standard Saturday 3pm
    (2014, 4, 12, 'Southampton', 'Cardiff'): "15:00",  # Standard Saturday 3pm
    (2014, 4, 12, 'Fulham', 'Norwich'): "15:00",       # Standard Saturday 3pm
    (2014, 4, 12, 'Crystal Palace', 'Aston Villa'): "15:00", # Standard Saturday 3pm
    (2014, 4, 12, 'Stoke', 'Newcastle'): "15:00",      # Standard Saturday 3pm

    (2014, 4, 13, 'Liverpool', 'Man City'): "16:00",   # Source: Sky Sports
    (2014, 4, 13, 'Swansea', 'Chelsea'): "13:30",      # Source: Sky Sport
}


def apply_time(row):
    key = (row['Year'], row['Month'], row['Day'], row['HomeTeam'], row['AwayTeam'])
    return time_mapping.get(key, row['Time'])

df['Time'] = df.apply(apply_time, axis=1)

In [66]:
df['Time'].unique()

array(['15:00', '16:00', '20:00', '19:45', '14:00', '21:00', '12:30',
       '17:00', '11:30', '12:00', '20:45', '13:00', '17:30', '18:35',
       '18:15', '16:05', '12:15', '13:15', '17:05', '19:30', '17:35',
       '12:45', '17:15', '13:30', '18:00', '18:30', '16:30', '13:45',
       '15:30', '14:30', '14:35', '18:20', '16:15', '14:05', '16:10',
       '19:00', '21:30', '10:00', '18:30:', '20:30', '14:15', '20:15',
       '19:15', '22:00', '22:30', '21:15'], dtype=object)

---

$$ Round $$

In [72]:
df.to_csv("Data/matches.csv", index=False)

In [88]:
Round_df = df[ df['Round'] > 38 ]

In [89]:
Round_df.shape

(162, 51)

In [90]:
Round_df['Year'].max()

np.int64(2013)

In [98]:
df[ df['Round'] > 38 ][['Season']].min(), df[ df['Round'] > 38 ][['Season']].max()

(Season    1112
 dtype: object,
 Season    1213
 dtype: object)

In [92]:
df[ df['Year'] == 2014].head(30)[['Round', 'Season']]

      Round Season
5130   20.0   1314
5131   20.0   1314
5132   20.0   1314
5133   20.0   1314
5134   20.0   1314
5135   20.0   1314
5136   20.0   1314
5137   20.0   1314
5138   20.0   1314
5139   20.0   1314
5140   21.0   1314
5141   21.0   1314
5142   21.0   1314
5143   21.0   1314
5144   21.0   1314
5145   21.0   1314
5146   21.0   1314
5147   21.0   1314
5148   21.0   1314
5149   21.0   1314
5150   22.0   1314
5151   22.0   1314
5152   22.0   1314
5153   22.0   1314
5154   22.0   1314
5155   22.0   1314
5156   22.0   1314
5157   22.0   1314
5158   22.0   1314
5159   22.0   1314

In [99]:
for year in ['1112', '1213']:
    mask = df['Season'] == year
    indices = df[mask].sort_values(['Month', 'Day']).index
    
    for i, idx in enumerate(indices):
        round_num = (i // 10) + 1
        df.loc[idx, 'Round'] = round_num

In [100]:
df[ df['Round'] > 38 ].shape

(0, 51)

In [101]:
df[ df['Round'] > 38 ][['Year', 'Month']]

Empty DataFrame
Columns: [Year, Month]
Index: []

In [102]:
df[ df['Year'] == 2012 ]['Round'].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.])

In [103]:
df[df['Year'] == 2012]['Round'].value_counts().sort_index()

Round
1.0     10
2.0     10
3.0     10
4.0     10
5.0     10
6.0     10
7.0     10
8.0     10
9.0     10
10.0    10
11.0    10
12.0    10
13.0    10
14.0    10
15.0    10
16.0    10
17.0    10
18.0    10
19.0    18
20.0    13
21.0    10
22.0    10
23.0    10
24.0    10
25.0    10
26.0    10
27.0    10
28.0    10
29.0    10
30.0    10
31.0    10
32.0    10
33.0    10
34.0    10
35.0    10
36.0    10
37.0    10
38.0    10
Name: count, dtype: int64

In [104]:
df.to_csv("Data/matches.csv", index=False)

---

$$ HomeTeam $$

In [107]:
df['HomeTeam'].drop_duplicates().sort_values()

10             Arsenal
28         Aston Villa
778         Birmingham
394          Blackburn
3824         Blackpool
392             Bolton
5702       Bournemouth
12            Bradford
7980         Brentford
6467          Brighton
3433           Burnley
4958           Cardiff
0             Charlton
3              Chelsea
7             Coventry
1535    Crystal Palace
2                Derby
16             Everton
395             Fulham
6477      Huddersfield
3043              Hull
13             Ipswich
1                Leeds
5            Leicester
8            Liverpool
8769             Luton
15            Man City
9           Man United
11       Middlesbrough
17           Newcastle
1522           Norwich
8377        Nottingham
1140        Portsmouth
4184               QPR
2282           Reading
2281         Sheffield
14         Southampton
3050             Stoke
6           Sunderland
4190           Swansea
4            Tottenham
2291           Watford
772          West Brom
18            West Ham
1909             Wigan
1150            Wolves
Name: HomeTeam, dtype: object

---

$$ HomeGoal $$

In [108]:
df['HomeGoal'].unique()

array([4, 2, 3, 0, 1, 5, 6, 7, 8, 9])

---
$$ AwayGoal $$

In [109]:
df['AwayGoal'].unique()

array([0, 2, 1, 3, 4, 5, 6, 7, 9, 8])

---
$$ Result $$

In [110]:
df['Result'].unique()

array(['H', 'D', 'A'], dtype=object)

---
$$ HomeGoal-HalfTime $$  $$ AwayGoal-HalfTime $$

In [112]:
df['HomeGoal-HalfTime'].unique(), df['AwayGoal-HalfTime'].unique()

(array([2., 1., 0., 3., 5., 4.]), array([0., 2., 1., 3., 4., 5.]))

---
$$ Result-HalfTime $$

In [113]:
df['Result-HalfTime'].unique()

array(['H', 'A', 'D'], dtype=object)

---
$$ Attendance $$

In [116]:
df['Attendance'].describe()

count     9880.000000
mean     34640.137955
std      16167.927040
min          0.000000
25%      24391.750000
50%      32053.500000
75%      42471.500000
max      83014.000000
Name: Attendance, dtype: float64

---
$$ Referee $$

In [118]:
df['Referee'].unique().shape

(190,)

In [120]:
df['Referee'].drop_duplicates().sort_values()

768                A D'Urso
9442              A Kitchen
7001               A Madley
1641             A Marriner
7959                 A Moss
3651               A Taylor
763                 A Wiley
415             A. G. Wiley
394            A. G. Wiley
409            A. P. D'Urso
388           A. P. D'Urso
419              A.G. Wiley
4                Alan Wiley
2               Andy D'Urso
312            Andy D'Urso
16                Andy Hall
760                B Knight
413               B. Knight
395              B. Knight
565           Barber, G. P.
7              Barry Knight
567            Barry, N. S.
562          Bennett, S. G.
782                   C Foy
6383             C Kavanagh
4831               C Pawson
773                C Wilkes
539               C. J. Foy
410            C. R. Wilkes
385           C. R. Wilkes
169            Clive Wilkes
8529                 D Bond
6808                D Coote
762               D Elleray
7444              D England
2589              D Gallagh
2643             D Gallaghe
778             D Gallagher
784                  D Pugh
9461                 D Webb
566           D'Urso, A. P.
380         D. J. Gallagher
416                 D. Pugh
444           D. R. Elleray
390          D. R. Elleray
15            David Ellaray
595              Dean, M. L
1          Dermot Gallagher
618                Dowd, P.
551             Dunn, S. W.
612              Durkin, P.
557           Durkin, P. A.
783          E Wolstenholme
431      E. K. Wolstenholme
393     E. K. Wolstenholme
553          Elleray, D. R.
9723               F Hallam
14                 F Taylor
613              Foy, C. J.
764                G Barber
766                  G Poll
5447                G Scott
381            G. P. Barber
403           G. P. Barber
382                 G. Poll
405                G. Poll
577        Gallagher, D. J.
3             Graham Barber
10              Graham Poll
1221                 H Webb
560           Halsey, M. R.
2124           I Williamson
30               Ian Harris
8114               J Brooks
8031              J Gillett
9096             J Gillett
4000                 J Moss
8721                J Smith
776                J Winter
387            J. T. Winter
391           J. T. Winter
520             J.T. Winter
13              Jeff Winter
559               Jones, P.
3473               K Friend
9360             K Kavanagh
2156               K Stroud
550              Knight, B.
2137                L Mason
2500              L Probert
8980                L Smith
1571             M Atkinson
1535          M Clattenburg
774                  M Dean
9099              M Donohue
785                M Halsey
3061                M Jones
777               M Messias
3815               M Oliver
767                 M Riley
8104            M Salisbury
420             M. A. Riley
404            M. A. Riley
528           M. D. Messias
399               M. L Dean
443              M. L. Dean
423            M. R. Halsey
12              Mark Halsey
313            Mark Halsey
175            Matt Messias
592          Messias, M. D.
43                Mike Dean
5                Mike Riley
3533            Mn Atkinson
765                 N Barry
3961            N Swarbrick
383             N. S. Barry
33              Neale Barry
7238             O Langford
9438               O Oliver
7253               P Bankes
1604             P Crossley
823                  P Dowd
769                P Durkin
5345              P Tierney
1236               P Walton
386            P. A. Durkin
396           P. A. Durkin
527                 P. Dowd
437                P. Jones
389               P. Jones
418             P.A. Durkin
8               Paul Durkin
34              Paul Taylor
11              Peter Jones
558                Poll, G.
573                Pugh, D.
1885                R Beeby
4581                 R East
7394                R Jones
4902               R Madley
1148               R Martin
779                R Styles
8915                R Welch
384               R. Styles
556           Rennie, U. D.
549            Riley, M. A.
0                Rob Harris
18               Rob Styles
156              Roy Burton
8920              S Allison
3055              S Attwell
8813              S Barrott
761               S Bennett
772                  S Dunn
5700               S Hooper
7442                S Scott
9010                S Singh
2460               S Tanner
402           S. G. Bennett
424              S. W. Dunn
392             S. W. Dunn
3531             St Bennett
26            Steve Bennett
315          Steve Bennett
6                Steve Dunn
9               Steve Lodge
607               Styles, R
568              Styles, R.
8402              T Bramall
8141           T Harrington
9635                 T Kirk
7383             T Robinson
775                U Rennie
398            U. D. Rennie
554            Wiley, A. G.
564           Wilkes, C. R.
552           Winter, J. T.
555     Wolstenholme, E. K.
741                Yates, N
6454                l Mason
1859               A D'Urso
1861                A Wiley
1860                  C Foy
1858            D Gallagher
1856                 H Webb
1855             M Atkinson
1863                N Barry
1862                 S Dunn
1857               U Rennie
Name: Referee, dtype: object

In [121]:
Referee = {
    # A
    "A D'Urso": "Andy D'Urso",
    "A. P. D'Urso": "Andy D'Urso",
    "A. P. D'Urso ": "Andy D'Urso",
    "Andy D'Urso": "Andy D'Urso",
    "Andy D'Urso ": "Andy D'Urso",
    "D'Urso, A. P.": "Andy D'Urso",
    "A D'Urso": "Andy D'Urso",
    "A Kitchen": "Andrew Kitchen",
    "A Madley": "Andrew Madley",
    "A Marriner": "Andre Marriner",
    "A Moss": "Andy Moss",
    "A Taylor": "Anthony Taylor",
    "A Wiley": "Alan Wiley",
    "A. G. Wiley": "Alan Wiley",
    "A. G. Wiley ": "Alan Wiley",
    "A.G. Wiley": "Alan Wiley",
    "Alan Wiley": "Alan Wiley",
    "Wiley, A. G.": "Alan Wiley",
    "A Wiley": "Alan Wiley",
    "Andy Hall": "Andy Hall",
    # B
    "B Knight": "Barry Knight",
    "B. Knight": "Barry Knight",
    "B. Knight ": "Barry Knight",
    "Barry Knight": "Barry Knight",
    "Knight, B.": "Barry Knight",
    "Barber, G. P.": "Graham Barber",
    "G Barber": "Graham Barber",
    "G. P. Barber": "Graham Barber",
    "G. P. Barber ": "Graham Barber",
    "Graham Barber": "Graham Barber",
    "Barry, N. S.": "Neale Barry",
    "N Barry": "Neale Barry",
    "N. S. Barry": "Neale Barry",
    "Neale Barry": "Neale Barry",
    "N Barry": "Neale Barry",
    "Bennett, S. G.": "Steve Bennett",
    "S Bennett": "Steve Bennett",
    "S. G. Bennett": "Steve Bennett",
    "St Bennett": "Steve Bennett",
    "Steve Bennett": "Steve Bennett",
    "Steve Bennett ": "Steve Bennett",
    # C
    "C Foy": "Chris Foy",
    "C. J. Foy": "Chris Foy",
    "Foy, C. J.": "Chris Foy",
    "C Foy": "Chris Foy",
    "C Kavanagh": "Chris Kavanagh",
    "K Kavanagh": "Chris Kavanagh",
    "C Pawson": "Craig Pawson",
    "C Wilkes": "Clive Wilkes",
    "C. R. Wilkes": "Clive Wilkes",
    "C. R. Wilkes ": "Clive Wilkes",
    "Clive Wilkes": "Clive Wilkes",
    "Wilkes, C. R.": "Clive Wilkes",
    # D
    "D Bond": "Darren Bond",
    "D Coote": "David Coote",
    "D Elleray": "David Elleray",
    "D. R. Elleray": "David Elleray",
    "D. R. Elleray ": "David Elleray",
    "David Ellaray": "David Elleray",
    "Elleray, D. R.": "David Elleray",
    "D England": "Darren England",
    "D Gallagh": "Dermot Gallagher",
    "D Gallaghe": "Dermot Gallagher",
    "D Gallagher": "Dermot Gallagher",
    "D. J. Gallagher": "Dermot Gallagher",
    "Gallagher, D. J.": "Dermot Gallagher",
    "Dermot Gallagher": "Dermot Gallagher",
    "D Gallagher": "Dermot Gallagher",
    "D Pugh": "David Pugh",
    "D. Pugh": "David Pugh",
    "Pugh, D.": "David Pugh",
    "D Webb": "David Webb",
    "Dean, M. L": "Mike Dean",
    "M Dean": "Mike Dean",
    "M. L Dean": "Mike Dean",
    "M. L. Dean": "Mike Dean",
    "Mike Dean": "Mike Dean",
    "Dowd, P.": "Phil Dowd",
    "P Dowd": "Phil Dowd",
    "P. Dowd": "Phil Dowd",
    "Dunn, S. W.": "Steve Dunn",
    "S Dunn": "Steve Dunn",
    "S. W. Dunn": "Steve Dunn",
    "S. W. Dunn ": "Steve Dunn",
    "Steve Dunn": "Steve Dunn",
    "S Dunn": "Steve Dunn",
    "Durkin, P.": "Paul Durkin",
    "Durkin, P. A.": "Paul Durkin",
    "P Durkin": "Paul Durkin",
    "P. A. Durkin": "Paul Durkin",
    "P. A. Durkin ": "Paul Durkin",
    "P.A. Durkin": "Paul Durkin",
    "Paul Durkin": "Paul Durkin",
    # E - F - G
    "E Wolstenholme": "Eddie Wolstenholme",
    "E. K. Wolstenholme": "Eddie Wolstenholme",
    "E. K. Wolstenholme ": "Eddie Wolstenholme",
    "Wolstenholme, E. K.": "Eddie Wolstenholme",
    "F Hallam": "Farai Hallam",
    "F Taylor": "Fred Taylor",
    "G Poll": "Graham Poll",
    "G. Poll": "Graham Poll",
    "G. Poll ": "Graham Poll",
    "Graham Poll": "Graham Poll",
    "Poll, G.": "Graham Poll",
    "G Scott": "Graham Scott",
    # H - I - J
    "H Webb": "Howard Webb",
    "H Webb": "Howard Webb",
    "Halsey, M. R.": "Mark Halsey",
    "M Halsey": "Mark Halsey",
    "M. R. Halsey": "Mark Halsey",
    "Mark Halsey": "Mark Halsey",
    "Mark Halsey ": "Mark Halsey",
    "I Williamson": "Ian Williamson",
    "Ian Harris": "Ian Harris",
    "J Brooks": "John Brooks",
    "J Gillett": "Jarred Gillett",
    "J Gillett ": "Jarred Gillett",
    "J Moss": "Jon Moss",
    "J Smith": "John Smith",
    "J Winter": "Jeff Winter",
    "J. T. Winter": "Jeff Winter",
    "J. T. Winter ": "Jeff Winter",
    "J.T. Winter": "Jeff Winter",
    "Jeff Winter": "Jeff Winter",
    "Winter, J. T.": "Jeff Winter",
    "Jones, P.": "Peter Jones",
    "P. Jones": "Peter Jones",
    "P. Jones ": "Peter Jones",
    "Peter Jones": "Peter Jones",
    # K - L
    "K Friend": "Kevin Friend",
    "K Stroud": "Keith Stroud",
    "L Mason": "Lee Mason",
    "l Mason": "Lee Mason",
    "L Probert": "Lee Probert",
    "L Smith": "Lee Smith",
    # M
    "M Atkinson": "Martin Atkinson",
    "Mn Atkinson": "Martin Atkinson",
    "M Atkinson": "Martin Atkinson",
    "M Clattenburg": "Mark Clattenburg",
    "M Donohue": "Martin Donohue",
    "M Jones": "Mike Jones",
    "M Messias": "Matt Messias",
    "M. D. Messias": "Matt Messias",
    "Matt Messias": "Matt Messias",
    "Messias, M. D.": "Matt Messias",
    "M Oliver": "Michael Oliver",
    "M Riley": "Mike Riley",
    "M. A. Riley": "Mike Riley",
    "M. A. Riley ": "Mike Riley",
    "Mike Riley": "Mike Riley",
    "Riley, M. A.": "Mike Riley",
    "M Salisbury": "Michael Salisbury",
    # O - P
    "O Langford": "Oliver Langford",
    "O Oliver": "Michael Oliver",
    "P Bankes": "Peter Bankes",
    "P Crossley": "Paul Crossley",
    "P Tierney": "Paul Tierney",
    "P Walton": "Peter Walton",
    "Paul Taylor": "Paul Taylor",
    # R
    "R Beeby": "Roger Beeby",
    "R East": "Roger East",
    "R Jones": "Robert Jones",
    "R Madley": "Bobby Madley",
    "R Martin": "Rob Martin",
    "R Styles": "Rob Styles",
    "R. Styles": "Rob Styles",
    "Rob Styles": "Rob Styles",
    "Styles, R": "Rob Styles",
    "Styles, R.": "Rob Styles",
    "R Welch": "Rebecca Welch",
    "Rennie, U. D.": "Uriah Rennie",
    "U Rennie": "Uriah Rennie",
    "U. D. Rennie": "Uriah Rennie",
    "U Rennie": "Uriah Rennie",
    "Rob Harris": "Rob Harris",
    "Roy Burton": "Roy Burton",
    # S
    "S Allison": "Sam Allison",
    "S Attwell": "Stuart Attwell",
    "S Barrott": "Sam Barrott",
    "S Hooper": "Simon Hooper",
    "S Scott": "Stuart Scott",
    "S Singh": "Sunny Singh Gill",
    "S Tanner": "Steve Tanner",
    "Steve Lodge": "Stephen Lodge",
    # T - Y
    "T Bramall": "Thomas Bramall",
    "T Harrington": "Tony Harrington",
    "T Kirk": "Trevor Kirk",
    "T Robinson": "Tim Robinson",
    "Yates, N": "Nigel Yates",
}

In [123]:
len(Referee)

180

In [125]:
df['Referee'] = df['Referee'].replace(Referee)
df['Referee'] = df['Referee'].str.strip()

In [126]:
df['Referee'].drop_duplicates().sort_values()

1859              A D'Urso
1861               A Wiley
4               Alan Wiley
1641        Andre Marriner
9442        Andrew Kitchen
7001         Andrew Madley
2              Andy D'Urso
16               Andy Hall
7959             Andy Moss
3651        Anthony Taylor
7             Barry Knight
4902          Bobby Madley
1860                 C Foy
539              Chris Foy
6383        Chris Kavanagh
169           Clive Wilkes
4831          Craig Pawson
1858           D Gallagher
8529           Darren Bond
7444        Darren England
6808           David Coote
15           David Elleray
416             David Pugh
9461            David Webb
1         Dermot Gallagher
393     Eddie Wolstenholme
9723          Farai Hallam
14             Fred Taylor
3            Graham Barber
10             Graham Poll
5447          Graham Scott
1856                H Webb
1221           Howard Webb
30              Ian Harris
2124        Ian Williamson
8031        Jarred Gillett
13             Jeff Winter
8114           John Brooks
8721            John Smith
4000              Jon Moss
2156          Keith Stroud
3473          Kevin Friend
2137             Lee Mason
2500           Lee Probert
8980             Lee Smith
1855            M Atkinson
1535      Mark Clattenburg
12             Mark Halsey
1571       Martin Atkinson
9099        Martin Donohue
175           Matt Messias
3815        Michael Oliver
8104     Michael Salisbury
43               Mike Dean
3061            Mike Jones
5               Mike Riley
1863               N Barry
3961           N Swarbrick
33             Neale Barry
741            Nigel Yates
7238       Oliver Langford
1604         Paul Crossley
8              Paul Durkin
34             Paul Taylor
5345          Paul Tierney
7253          Peter Bankes
11             Peter Jones
1236          Peter Walton
527              Phil Dowd
8915         Rebecca Welch
0               Rob Harris
1148            Rob Martin
18              Rob Styles
7394          Robert Jones
1885           Roger Beeby
4581            Roger East
156             Roy Burton
1862                S Dunn
8920           Sam Allison
8813           Sam Barrott
5700          Simon Hooper
9            Stephen Lodge
26           Steve Bennett
6               Steve Dunn
2460          Steve Tanner
3055        Stuart Attwell
7442          Stuart Scott
9010      Sunny Singh Gill
8402        Thomas Bramall
7383          Tim Robinson
8141       Tony Harrington
9635           Trevor Kirk
1857              U Rennie
398           Uriah Rennie
Name: Referee, dtype: object

In [127]:
Referee = {
    "U Rennie": "Uriah Rennie",
    "S Dunn": "Steve Dunn",
    "N Barry": "Neale Barry",
    "N Swarbrick": "Neil Swarbrick",
    "M Atkinson": "Martin Atkinson",
    "H Webb": "Howard Webb",
    "D Gallagher": "Dermot Gallagher",
    "C Foy": "Chris Foy",
    "A D'Urso": "Andy D'Urso",
    "A Wiley": "Alan Wiley"
}
df['Referee'] = df['Referee'].replace(Referee)
df['Referee'] = df['Referee'].str.strip()

In [128]:
df['Referee'].drop_duplicates().sort_values()

4               Alan Wiley
1641        Andre Marriner
9442        Andrew Kitchen
7001         Andrew Madley
2              Andy D'Urso
16               Andy Hall
7959             Andy Moss
3651        Anthony Taylor
7             Barry Knight
4902          Bobby Madley
539              Chris Foy
6383        Chris Kavanagh
169           Clive Wilkes
4831          Craig Pawson
8529           Darren Bond
7444        Darren England
6808           David Coote
15           David Elleray
416             David Pugh
9461            David Webb
1         Dermot Gallagher
393     Eddie Wolstenholme
9723          Farai Hallam
14             Fred Taylor
3            Graham Barber
10             Graham Poll
5447          Graham Scott
1221           Howard Webb
30              Ian Harris
2124        Ian Williamson
8031        Jarred Gillett
13             Jeff Winter
8114           John Brooks
8721            John Smith
4000              Jon Moss
2156          Keith Stroud
3473          Kevin Friend
2137             Lee Mason
2500           Lee Probert
8980             Lee Smith
1535      Mark Clattenburg
12             Mark Halsey
1571       Martin Atkinson
9099        Martin Donohue
175           Matt Messias
3815        Michael Oliver
8104     Michael Salisbury
43               Mike Dean
3061            Mike Jones
5               Mike Riley
33             Neale Barry
3961        Neil Swarbrick
741            Nigel Yates
7238       Oliver Langford
1604         Paul Crossley
8              Paul Durkin
34             Paul Taylor
5345          Paul Tierney
7253          Peter Bankes
11             Peter Jones
1236          Peter Walton
527              Phil Dowd
8915         Rebecca Welch
0               Rob Harris
1148            Rob Martin
18              Rob Styles
7394          Robert Jones
1885           Roger Beeby
4581            Roger East
156             Roy Burton
8920           Sam Allison
8813           Sam Barrott
5700          Simon Hooper
9            Stephen Lodge
26           Steve Bennett
6               Steve Dunn
2460          Steve Tanner
3055        Stuart Attwell
7442          Stuart Scott
9010      Sunny Singh Gill
8402        Thomas Bramall
7383          Tim Robinson
8141       Tony Harrington
9635           Trevor Kirk
398           Uriah Rennie
Name: Referee, dtype: object

In [129]:
df.to_csv("Data/matches.csv", index=False)

---
$$ HomeShot $$
$$ AwayShot $$
$$ HomeOnTargetShot $$
$$ AwayOnTargetShot $$

In [131]:
df['HomeShot'].unique()

array([17.,  6., 20.,  5.,  8., 16., 19., 12., 13., 15.,  9., 14., 18.,
       21., 11., 10.,  7., 22.,  0., 33., 24., 26.,  4., 30.,  1., 27.,
       25.,  3., 23., 28., 31., 34.,  2., 32., 29., 37., 35., 39., 43.,
       36.])

In [132]:
df['AwayShot'].unique()

array([ 8., 12., 13., 15.,  5., 14., 16.,  3.,  9.,  7., 11., 10.,  4.,
        6., 18., 17.,  2., 20., 19., 24., 21., 22.,  0.,  1., 23., 25.,
       26., 27., 30., 29., 28., 31., 37.])

In [133]:
df['HomeOnTargetShot'].unique()

array([14.,  8.,  4., 10.,  6.,  2.,  3.,  9., 12.,  5.,  7.,  1., 13.,
       11.,  0., 19., 15., 18., 16., 17., 21., 20., 24., 22.])

In [134]:
df['HomeOnTargetShot'].unique()

array([14.,  8.,  4., 10.,  6.,  2.,  3.,  9., 12.,  5.,  7.,  1., 13.,
       11.,  0., 19., 15., 18., 16., 17., 21., 20., 24., 22.])

---
$$ HomeFoul $$
$$ AwayFoul $$

In [135]:
df['HomeFoul'].unique()

array([13., 21., 11., 19., 14., 12., 10., 15.,  8.,  7., 25.,  9., 18.,
       24., 17., 23., 16.,  6.,  5.,  0., 20., 22., 28., 26.,  4.,  3.,
        2., 27.,  1., 33.])

In [136]:
df['AwayFoul'].unique()

array([12., 20., 13., 14., 21.,  8., 18., 16.,  7., 15., 11.,  9., 10.,
        6., 24., 22.,  5., 17., 19., 28.,  1., 23., 26., 25.,  3., 29.,
       27.,  4.,  2.])

---
$$ HomeCorner $$
$$ AwayCorner $$

In [137]:
df['HomeCorner'].unique()

array([ 6.,  5.,  7.,  3.,  2.,  8., 10.,  4.,  9., 11., 15., 12.,  1.,
       13.,  0., 16., 14., 17., 19., 18., 20.])

In [138]:
df['AwayCorner'].unique()

array([ 6.,  4.,  8.,  7.,  9.,  1., 11.,  5.,  3.,  2., 10., 14.,  0.,
       13., 12., 18., 16., 17., 15., 19.])

---
$$ HomeYellow $$
$$ AwayYellow $$
$$ HomeRed $$
$$ AwayRed $$

In [139]:
df['HomeYellow'].unique()

array([1., 0., 2., 3., 5., 4., 7., 6.])

In [140]:
df['AwayYellow'].unique()

array([2., 3., 1., 0., 4., 5., 7., 6., 8., 9.])

In [141]:
df['HomeRed'].unique()

array([0., 1., 2., 3.])

In [142]:
df['AwayRed'].unique()

array([0., 1., 2.])

---
$$ XGHome $$
$$ XGAway $$

In [143]:
df['XGHome'].unique()

array([ nan, 1.5 , 1.  , 1.2 , 0.3 , 2.2 , 0.7 , 0.5 , 4.  , 1.1 , 2.9 ,
       0.2 , 1.23, 0.9 , 1.7 , 0.6 , 3.8 , 0.4 , 1.8 , 1.6 , 1.3 , 2.8 ,
       2.31, 0.94, 3.43, 0.13, 0.09, 0.49, 1.37, 0.84, 2.4 , 2.3 , 2.6 ,
       2.  , 2.1 , 1.9 , 3.1 , 2.5 , 0.8 , 1.4 , 2.7 , 2.37, 1.98, 0.69,
       0.91, 0.58, 0.42, 1.09, 3.3 , 1.36, 1.97, 0.1 , 1.79, 0.82, 3.  ,
       2.85, 1.31, 3.5 , 3.4 , 3.2 , 5.9 , 3.7 , 4.6 , 3.6 , 2.74, 1.57,
       4.4 , 3.9 , 1.94, 2.96, 0.  , 4.7 , 0.47, 2.44, 2.38, 0.88, 2.72,
       3.35, 1.75, 1.66, 2.11, 4.3 , 1.18, 3.79, 0.72, 2.03, 0.79, 1.68,
       1.32, 1.04, 0.62, 4.2 , 0.46, 0.92, 0.52, 0.32, 1.65, 0.56, 1.43,
       1.84, 2.35, 1.87, 1.27, 2.27, 1.71, 1.44, 1.77, 0.74, 3.13, 3.15,
       2.82, 1.64, 1.34])

In [144]:
df['XGAway'].unique()

array([ nan, 1.8 , 1.  , 0.3 , 2.  , 1.9 , 1.4 , 1.7 , 0.7 , 1.6 , 1.3 ,
       1.1 , 2.02, 1.5 , 0.2 , 2.6 , 0.6 , 0.9 , 3.14, 1.09, 1.14, 2.94,
       1.77, 2.97, 2.3 , 1.2 , 0.5 , 3.2 , 0.4 , 0.8 , 2.9 , 1.03, 0.75,
       2.03, 0.73, 2.17, 2.7 , 2.1 , 2.4 , 1.87, 2.8 , 2.2 , 1.16, 0.57,
       0.96, 1.15, 0.71, 0.1 , 3.5 , 2.5 , 3.  , 3.6 , 3.4 , 0.  , 3.7 ,
       3.9 , 0.88, 1.07, 3.1 , 4.1 , 4.2 , 3.3 , 1.18, 1.66, 1.76, 0.65,
       0.37, 1.57, 1.61, 1.25, 4.3 , 0.74, 0.35, 2.39, 1.11, 2.22, 0.82,
       2.05, 1.12, 1.85, 1.53, 2.31, 0.94, 5.9 , 1.06, 2.08, 1.97, 1.38,
       0.89, 2.88, 0.44, 0.63, 2.47, 1.44, 1.28, 0.45, 0.61, 0.51, 1.78,
       1.05, 1.24, 1.93])

---
$$ Season Stats $$

In [147]:
df[ (df['SeasonPosHome'] < 0) | (df['SeasonPosHome'] > 20) ]

Empty DataFrame
Columns: [Season, Year, Month, Day, WeekDay, Time, Round, HomeTeam, AwayTeam, HomeGoal, AwayGoal, Result, HomeGoal-HalfTime, AwayGoal-HalfTime, Result-HalfTime, Attendance, Referee, HomeShot, AwayShot, HomeOnTargetShot, AwayOnTargetShot, HomeFoul, AwayFoul, HomeCorner, AwayCorner, HomeYellow, AwayYellow, HomeRed, AwayRed, XGHome, XGAway, SeasonPosHome, SeasonPlayedHome, SeasonWinHome, SeasonDrawHome, SeasonLossHome, SeasonGFHome, SeasonGAHome, SeasonGDHome, SeasonPointsHome, QualificationOrRelegationHome, SeasonPosAway, SeasonPlayedAway, SeasonWinAway, SeasonDrawAway, SeasonLossAway, SeasonGFAway, SeasonGAAway, SeasonGDAway, SeasonPointsAway, QualificationOrRelegationAway]
Index: []

In [148]:
df[ (df['SeasonPosAway'] < 0) | (df['SeasonPosAway'] > 20) ]

Empty DataFrame
Columns: [Season, Year, Month, Day, WeekDay, Time, Round, HomeTeam, AwayTeam, HomeGoal, AwayGoal, Result, HomeGoal-HalfTime, AwayGoal-HalfTime, Result-HalfTime, Attendance, Referee, HomeShot, AwayShot, HomeOnTargetShot, AwayOnTargetShot, HomeFoul, AwayFoul, HomeCorner, AwayCorner, HomeYellow, AwayYellow, HomeRed, AwayRed, XGHome, XGAway, SeasonPosHome, SeasonPlayedHome, SeasonWinHome, SeasonDrawHome, SeasonLossHome, SeasonGFHome, SeasonGAHome, SeasonGDHome, SeasonPointsHome, QualificationOrRelegationHome, SeasonPosAway, SeasonPlayedAway, SeasonWinAway, SeasonDrawAway, SeasonLossAway, SeasonGFAway, SeasonGAAway, SeasonGDAway, SeasonPointsAway, QualificationOrRelegationAway]
Index: []

In [149]:
df[ (df['SeasonPlayedHome'] < 0) | (df['SeasonPlayedHome'] > 38) ]

Empty DataFrame
Columns: [Season, Year, Month, Day, WeekDay, Time, Round, HomeTeam, AwayTeam, HomeGoal, AwayGoal, Result, HomeGoal-HalfTime, AwayGoal-HalfTime, Result-HalfTime, Attendance, Referee, HomeShot, AwayShot, HomeOnTargetShot, AwayOnTargetShot, HomeFoul, AwayFoul, HomeCorner, AwayCorner, HomeYellow, AwayYellow, HomeRed, AwayRed, XGHome, XGAway, SeasonPosHome, SeasonPlayedHome, SeasonWinHome, SeasonDrawHome, SeasonLossHome, SeasonGFHome, SeasonGAHome, SeasonGDHome, SeasonPointsHome, QualificationOrRelegationHome, SeasonPosAway, SeasonPlayedAway, SeasonWinAway, SeasonDrawAway, SeasonLossAway, SeasonGFAway, SeasonGAAway, SeasonGDAway, SeasonPointsAway, QualificationOrRelegationAway]
Index: []

In [150]:
df[ (df['SeasonPlayedAway'] < 0) | (df['SeasonPlayedAway'] > 38) ]

Empty DataFrame
Columns: [Season, Year, Month, Day, WeekDay, Time, Round, HomeTeam, AwayTeam, HomeGoal, AwayGoal, Result, HomeGoal-HalfTime, AwayGoal-HalfTime, Result-HalfTime, Attendance, Referee, HomeShot, AwayShot, HomeOnTargetShot, AwayOnTargetShot, HomeFoul, AwayFoul, HomeCorner, AwayCorner, HomeYellow, AwayYellow, HomeRed, AwayRed, XGHome, XGAway, SeasonPosHome, SeasonPlayedHome, SeasonWinHome, SeasonDrawHome, SeasonLossHome, SeasonGFHome, SeasonGAHome, SeasonGDHome, SeasonPointsHome, QualificationOrRelegationHome, SeasonPosAway, SeasonPlayedAway, SeasonWinAway, SeasonDrawAway, SeasonLossAway, SeasonGFAway, SeasonGAAway, SeasonGDAway, SeasonPointsAway, QualificationOrRelegationAway]
Index: []

In [151]:
df['SeasonWinHome'].unique()

array([14., 20., 10., 17., 13., 15.,  8., 24.,  9.,  5., 11., 12., 18.,
       26., 21., 25., 16., 23., 19.,  6.,  4.,  7., 29., 22.,  3., 28.,
        1., 27., 30., 32.])

In [152]:
df['SeasonWinAway'].unique()

array([ 8., 11., 14., 10., 20., 13.,  9.,  5., 17., 24., 15., 12., 26.,
       21., 18.,  6.,  4., 19., 25., 23., 16.,  7., 22., 29.,  3., 28.,
        1., 27., 30., 32.,  2.])

In [153]:
df['SeasonDrawHome'].unique()

array([10.,  8., 12.,  6.,  9., 15., 11., 14., 13.,  5.,  7., 17., 16.,
        4.,  3.,  2., 18.])

In [154]:
df['SeasonDrawAway'].unique()

array([10.,  9., 12.,  6., 15., 11.,  8., 14., 13.,  5.,  7., 17., 16.,
        4.,  3.,  2., 18.])

In [155]:
df['SeasonLossHome'].unique()

array([14., 10., 16., 11., 15., 18., 20.,  9.,  6.,  8., 22., 12., 17.,
       24.,  3.,  5., 13., 19., 27.,  0., 21.,  7.,  1., 29.,  4.,  2.,
       23., 26., 28., 25.])

In [156]:
df['SeasonLossAway'].unique()

array([20., 18., 14., 16., 12., 10.,  8., 22., 15.,  9., 11.,  6.,  3.,
       17., 24., 27.,  5., 19., 13.,  7., 21.,  0.,  1., 29.,  4.,  2.,
       23., 26., 28., 25., 30.])

In [157]:
df['SeasonGFHome'].unique()

array([ 50.,  64.,  37.,  68.,  47.,  39.,  46.,  36.,  71.,  79.,  63.,
        44.,  30.,  57.,  40.,  41.,  45.,  49.,  35.,  29.,  38.,  53.,
        33.,  67.,  66.,  87.,  55.,  48.,  74.,  43.,  52.,  58.,  85.,
        42.,  51.,  61.,  21.,  73.,  32.,  72.,  26.,  34.,  31.,  28.,
        83.,  20.,  65.,  80.,  54.,  77.,  60., 103.,  86.,  69.,  59.,
        78.,  56.,  93.,  89.,  75., 101., 102.,  62.,  27.,  84., 106.,
        22.,  95.,  23.,  76.,  94.,  99.,  70.,  88.,  91.,  96.])

In [158]:
df['SeasonGAHome'].unique()

array([ 57.,  43.,  59.,  45.,  54.,  51.,  41.,  63.,  39.,  31.,  38.,
        44.,  70.,  42.,  48.,  65.,  50.,  53.,  47.,  49.,  64.,  37.,
        30.,  36.,  62.,  52.,  46.,  34.,  56.,  35.,  26.,  79.,  77.,
        40.,  15.,  66.,  58.,  60.,  61.,  55.,  69.,  25.,  22.,  24.,
        27.,  89.,  33.,  28.,  67.,  32.,  82.,  75.,  71.,  78.,  29.,
        68.,  73.,  85.,  74.,  76.,  80.,  81.,  23.,  84., 104.])

In [159]:
df['SeasonGDHome'].unique()

array([ -7.,  21., -22.,  23., -12.,   5., -27.,  32.,  48.,  25.,   0.,
       -40.,  15.,  -8., -24., -14.,  -6.,  -5.,   3.,  -4., -11., -34.,
        16., -30.,  37.,  28.,  42.,  43., -18., -23.,   4.,  -9.,  -1.,
        22.,  -3.,  40.,   9.,   1.,  30., -17., -36.,  20., -44.,  29.,
         6.,  47., -39.,  18., -10.,  12., -16., -35.,   8.,   7.,  57.,
       -21.,  11.,  51., -25., -43., -15., -13.,  38.,  50.,  56., -26.,
         2.,  -2., -28., -69.,  39.,  58., -20., -29.,  31.,  44., -19.,
       -31.,  71.,  13., -32.,  26., -42., -41.,  36.,  41.,  27.,  64.,
        19.,  10.,  35.,  65., -45.,  45.,  14., -49.,  34.,  33.,  52.,
        60.,  24., -33.,  46.,  79., -54., -47.,  67.,  72., -61.,  68.,
        73., -37.,  61.,  62.])

In [160]:
df['SeasonGFAway'].unique()

array([ 41.,  45.,  40.,  57.,  46.,  63.,  44.,  30.,  71.,  47.,  68.,
        79.,  36.,  50.,  37.,  39.,  64.,  55.,  48.,  74.,  49.,  53.,
        35.,  33.,  87.,  29.,  66.,  38.,  67.,  21.,  51.,  61.,  42.,
        85.,  58.,  43.,  52.,  73.,  32.,  72.,  31.,  28.,  26.,  34.,
        83.,  20.,  80.,  65.,  77.,  54., 103.,  86.,  60.,  56.,  69.,
        78.,  59.,  89.,  93.,  75., 101., 102.,  62.,  27.,  84., 106.,
        95.,  22.,  94.,  99.,  23.,  76.,  88.,  70.,  96.,  91.])

In [161]:
df['SeasonGAAway'].unique()

array([ 65.,  59.,  48.,  50.,  42.,  43.,  38.,  44.,  70.,  39.,  54.,
        45.,  31.,  63.,  41.,  57.,  51.,  47.,  36.,  64.,  62.,  52.,
        53.,  37.,  49.,  30.,  34.,  46.,  56.,  77.,  40.,  79.,  35.,
        26.,  58.,  60.,  61.,  66.,  15.,  55.,  25.,  22.,  69.,  27.,
        24.,  28.,  33.,  89.,  67.,  75.,  82.,  32.,  78.,  71.,  29.,
        73.,  68.,  74.,  85.,  76.,  80.,  23.,  81.,  84., 104.,  86.])

In [162]:
df['SeasonGDAway'].unique()

array([-24., -14.,  -8.,  -5.,  15.,   3.,  25.,   0., -40.,  -6.,  32.,
        -7.,  23.,  48., -27.,   5., -22., -12.,  21.,  -1.,  43., -23.,
       -18.,   4.,  -9.,  22.,  -4.,  16., -30.,  42.,  28., -34., -11.,
        37., -36., -44., -10.,  30.,  20., -17.,  40.,   1.,  -3.,   9.,
       -39.,  12.,   6.,  29.,  47.,  18.,  11., -21., -16., -25.,  51.,
       -35.,  57.,   8.,   7.,  38.,  50., -43., -13., -15., -26.,   2.,
        -2.,  56.,  39., -20., -69.,  58., -31., -19.,  31., -29.,  44.,
       -41., -42.,  26.,  71., -32.,  13.,  27.,  36.,  41.,  19.,  64.,
        10.,  35., -45.,  65.,  45.,  34., -49.,  14., -28.,  60.,  33.,
        52.,  46., -33.,  79.,  24.,  72., -47., -54.,  67.,  68., -37.,
        73., -61.,  61.,  62., -60., -46.])

In [163]:
df['SeasonPointsHome'].unique()

array([ 52.,  68.,  42.,  61.,  49.,  48.,  57.,  34.,  69.,  80.,  70.,
        26.,  66.,  51.,  54.,  50.,  45.,  40.,  44.,  28.,  30.,  64.,
        77.,  43.,  87.,  36.,  46.,  53.,  71.,  83.,  60.,  59.,  47.,
        78.,  67.,  19.,  75.,  90.,  33.,  39.,  41.,  56.,  79.,  58.,
        55.,  95.,  32.,  15.,  38.,  65.,  82.,  63.,  91.,  89.,  37.,
        11.,  85.,  35.,  76.,  72.,  62.,  86.,  31.,  25.,  73.,  84.,
        81.,  17.,  93.,  24., 100.,  16.,  97.,  98.,  99.,  21.,  23.,
        74.,  22.,  92.,  20.])

In [164]:
df['SeasonPointsAway'].unique()

array([ 34.,  42.,  52.,  66.,  54.,  70.,  26.,  51.,  69.,  49.,  61.,
        80.,  57.,  48.,  68.,  50.,  87.,  36.,  43.,  40.,  45.,  46.,
        53.,  71.,  44.,  30.,  77.,  64.,  28.,  19.,  67.,  83.,  78.,
        47.,  60.,  59.,  56.,  33.,  39.,  41.,  79.,  75.,  90.,  58.,
        32.,  95.,  55.,  63.,  65.,  82.,  91.,  38.,  15.,  89.,  76.,
        35.,  11.,  85.,  37.,  86.,  62.,  72.,  25.,  31.,  73.,  84.,
        17.,  81.,  24.,  93., 100.,  98.,  16.,  97.,  21.,  99.,  23.,
        74.,  92.,  22.,  12.,  20.])

In [165]:
df['QualificationOrRelegationHome'].unique()

array(['Not Applicable', 'Qualification for the UEFA Cup first round[a]',
       'Relegation to the Football League First Division',
       'Qualification for the Champions League third qualifying round[a]',
       'Qualification for the Champions League first group stage',
       'Qualification for the Intertoto Cup third round',
       'Qualification for the UEFA Cup first round[b]',
       'Qualification for the Champions League third qualifying round',
       'Qualification for the UEFA Cup qualifying round[a]Relegation to the Football League First Division',
       'Qualification for the UEFA Cup first round[c]',
       'Qualification for the Intertoto Cup second round',
       'Qualification for the Champions League group stage',
       'Relegation to Football League First Division',
       'Qualification for the UEFA Cup qualifying round[c]',
       'Relegation to the Football League Championship',
       'Qualification for the UEFA Cup first round',
       'Qualification for the Champions League first qualifying round[a]',
       'Qualification for the Champions League group stage[a]',
       'Qualification for the Intertoto Cup third round[b]',
       'Qualification for the UEFA Cup first qualifying round[b]',
       'Qualification for the Champions League play-off round',
       'Qualification for the Europa League play-off round[a]',
       'Qualification for the Europa League third qualifying round[a]',
       'Qualification for the Europa League third qualifying round[b]',
       'Qualification for the Europa League play-off round',
       'Qualification for the Europa League third qualifying round[c]',
       'Qualification for the Europa League first qualifying round[b]',
       'Qualification for the Europa League group stage[a]',
       'Qualification for the Europa League group stage[b]Relegation to the Football League Championship',
       'Qualification for the Europa League group stage',
       'Relegation to the EFL Championship',
       'Qualification for the Champions League group stage[b]',
       'Qualification for the Europa League second qualifying round[a]',
       'Qualification for the Europa League group stage[b]',
       'Qualification for the Europa Conference League play-off round[b]',
       'Qualification for the Europa Conference League play-off round[a]',
       'Qualification for the Europa Conference League play-off round'],
      dtype=object)

In [166]:
col = 'QualificationOrRelegationHome'

df[col] = df[col].astype(str).str.replace(r'\[[a-zA-Z0-9]+\]', '', regex=True).str.strip()

qualification_mapping = {
    'Relegation to Football League First Division': 
        'Relegation to the Football League First Division',
        
    'Qualification for the UEFA Cup qualifying roundRelegation to the Football League First Division': 
        'Qualification for the UEFA Cup qualifying round / Relegation to the Football League First Division',

    'Qualification for the Europa League group stageRelegation to the Football League Championship': 
        'Qualification for the Europa League group stage / Relegation to the Football League Championship',
}

df[col] = df[col].replace(qualification_mapping).str.strip()

In [167]:
df['QualificationOrRelegationAway'].unique()

array(['Relegation to the Football League First Division',
       'Not Applicable', 'Qualification for the UEFA Cup first round[a]',
       'Qualification for the Intertoto Cup third round',
       'Qualification for the Champions League first group stage',
       'Qualification for the Champions League third qualifying round[a]',
       'Qualification for the UEFA Cup qualifying round[a]Relegation to the Football League First Division',
       'Qualification for the UEFA Cup first round[c]',
       'Qualification for the Champions League third qualifying round',
       'Qualification for the Intertoto Cup second round',
       'Qualification for the UEFA Cup first round[b]',
       'Relegation to Football League First Division',
       'Qualification for the UEFA Cup qualifying round[c]',
       'Qualification for the Champions League group stage',
       'Relegation to the Football League Championship',
       'Qualification for the UEFA Cup first round',
       'Qualification for the Champions League first qualifying round[a]',
       'Qualification for the Champions League group stage[a]',
       'Qualification for the Intertoto Cup third round[b]',
       'Qualification for the UEFA Cup first qualifying round[b]',
       'Qualification for the Europa League third qualifying round[a]',
       'Qualification for the Europa League play-off round[a]',
       'Qualification for the Champions League play-off round',
       'Qualification for the Europa League third qualifying round[b]',
       'Qualification for the Europa League third qualifying round[c]',
       'Qualification for the Europa League first qualifying round[b]',
       'Qualification for the Europa League play-off round',
       'Qualification for the Europa League group stage[a]',
       'Qualification for the Europa League group stage[b]Relegation to the Football League Championship',
       'Qualification for the Europa League group stage',
       'Relegation to the EFL Championship',
       'Qualification for the Champions League group stage[b]',
       'Qualification for the Europa League second qualifying round[a]',
       'Qualification for the Europa League group stage[b]',
       'Qualification for the Europa Conference League play-off round[b]',
       'Qualification for the Europa Conference League play-off round[a]',
       'Qualification for the Europa Conference League play-off round'],
      dtype=object)

In [168]:
col = 'QualificationOrRelegationAway'

df[col] = df[col].astype(str).str.replace(r'\[[a-zA-Z0-9]+\]', '', regex=True).str.strip()

qualification_mapping = {
    'Relegation to Football League First Division': 
        'Relegation to the Football League First Division',
        
    'Qualification for the UEFA Cup qualifying roundRelegation to the Football League First Division': 
        'Qualification for the UEFA Cup qualifying round / Relegation to the Football League First Division',

    'Qualification for the Europa League group stageRelegation to the Football League Championship': 
        'Qualification for the Europa League group stage / Relegation to the Football League Championship',
}

df[col] = df[col].replace(qualification_mapping).str.strip()

In [169]:
df.to_csv("Data/matches.csv", index=False)

---

In [170]:
df['HomeTeam'].unique()

array(['Charlton', 'Leeds', 'Derby', 'Chelsea', 'Tottenham', 'Leicester',
       'Sunderland', 'Coventry', 'Liverpool', 'Man United', 'Arsenal',
       'Middlesbrough', 'Bradford', 'Ipswich', 'Southampton', 'Man City',
       'Everton', 'Newcastle', 'West Ham', 'Aston Villa', 'Bolton',
       'Blackburn', 'Fulham', 'West Brom', 'Birmingham', 'Portsmouth',
       'Wolves', 'Norwich', 'Crystal Palace', 'Wigan', 'Sheffield',
       'Reading', 'Watford', 'Hull', 'Stoke', 'Burnley', 'Blackpool',
       'QPR', 'Swansea', 'Cardiff', 'Bournemouth', 'Brighton',
       'Huddersfield', 'Brentford', 'Nottingham', 'Luton'], dtype=object)

In [174]:
# دیکشنری اطلاعات تیم‌ها
plus_info = {
    # London
    'Charlton': {'City': 'London', 'Region': 'South'},
    'Chelsea': {'City': 'London', 'Region': 'South'},
    'Tottenham': {'City': 'London', 'Region': 'South'},
    'Arsenal': {'City': 'London', 'Region': 'South'},
    'West Ham': {'City': 'London', 'Region': 'South'},
    'Fulham': {'City': 'London', 'Region': 'South'},
    'Crystal Palace': {'City': 'London', 'Region': 'South'},
    'QPR': {'City': 'London', 'Region': 'South'},

    # Manchester and North West
    'Man United': {'City': 'Manchester', 'Region': 'North'},
    'Man City': {'City': 'Manchester', 'Region': 'North'},
    'Bolton': {'City': 'Bolton', 'Region': 'North'},
    'Wigan': {'City': 'Wigan', 'Region': 'North'},
    'Blackburn': {'City': 'Blackburn', 'Region': 'North'},
    'Blackpool': {'City': 'Blackpool', 'Region': 'North'},
    'Burnley': {'City': 'Burnley', 'Region': 'North'},

    # Liverpool and North East
    'Liverpool': {'City': 'Liverpool', 'Region': 'North'},
    'Everton': {'City': 'Liverpool', 'Region': 'North'},
    'Newcastle': {'City': 'Newcastle upon Tyne', 'Region': 'North'},
    'Sunderland': {'City': 'Sunderland', 'Region': 'North'},
    'Middlesbrough': {'City': 'Middlesbrough', 'Region': 'North'},

    # Yorkshire
    'Leeds': {'City': 'Leeds', 'Region': 'North'},
    'Sheffield': {'City': 'Sheffield', 'Region': 'North'},
    'Huddersfield': {'City': 'Huddersfield', 'Region': 'North'},
    'Hull': {'City': 'Kingston upon Hull', 'Region': 'East'},

    # Midlands
    'Derby': {'City': 'Derby', 'Region': 'Midlands'},
    'Leicester': {'City': 'Leicester', 'Region': 'Midlands'},
    'Coventry': {'City': 'Coventry', 'Region': 'Midlands'},
    'Birmingham': {'City': 'Birmingham', 'Region': 'Midlands'},
    'Aston Villa': {'City': 'Birmingham', 'Region': 'Midlands'},
    'Nottingham': {'City': 'Nottingham', 'Region': 'Midlands'},
    'West Brom': {'City': 'West Bromwich', 'Region': 'West'},
    'Wolves': {'City': 'Wolverhampton', 'Region': 'West'},
    'Stoke': {'City': 'Stoke-on-Trent', 'Region': 'West'},

    # East
    'Norwich': {'City': 'Norwich', 'Region': 'East'},
    'Ipswich': {'City': 'Ipswich', 'Region': 'East'},

    # South
    'Southampton': {'City': 'Southampton', 'Region': 'South'},
    'Portsmouth': {'City': 'Portsmouth', 'Region': 'South'},
    'Brighton': {'City': 'Brighton and Hove', 'Region': 'South'},
    'Reading': {'City': 'Reading', 'Region': 'South'},
    'Watford': {'City': 'Watford', 'Region': 'South'},
    'Luton': {'City': 'Luton', 'Region': 'South'},
    'Bournemouth': {'City': 'Bournemouth', 'Region': 'South'},

    # Wales
    'Cardiff': {'City': 'Cardiff', 'Region': 'West'},
    'Swansea': {'City': 'Swansea', 'Region': 'West'},

    # Other
    'Bradford': {'City': 'Bradford', 'Region': 'North'},
    'Ipswich': {'City': 'Ipswich', 'Region': 'East'},
    'Reading': {'City': 'Reading', 'Region': 'South'},
    'Watford': {'City': 'Watford', 'Region': 'South'},
    'Hull': {'City': 'Kingston upon Hull', 'Region': 'East'},
}

In [176]:
df['HomeCity'] = df['HomeTeam'].map(
    lambda team: plus_info.get(team, {}).get('City')
)

df['HomeRegion'] = df['HomeTeam'].map(
    lambda team: plus_info.get(team, {}).get('Region')
)

df['AwayCity'] = df['AwayTeam'].map(
    lambda team: plus_info.get(team, {}).get('City')
)

df['AwayRegion'] = df['AwayTeam'].map(
    lambda team: plus_info.get(team, {}).get('Region')
)

In [177]:
df['IsDerby'] = (
    df['HomeCity'].notna()
    & df['AwayCity'].notna()
    & df['HomeCity'].eq(df['AwayCity'])
).map({
    True: 'Yes',
    False: 'No'
})

In [179]:
df[
    [
        'HomeTeam',
        'AwayTeam',
        'HomeCity',
        'HomeRegion',
        'AwayCity',
        'AwayRegion',
        'IsDerby'
    ]
].head()

    HomeTeam     AwayTeam HomeCity HomeRegion     AwayCity AwayRegion IsDerby
0   Charlton     Man City   London      South   Manchester      North      No
1      Leeds      Everton    Leeds      North    Liverpool      North      No
2      Derby  Southampton    Derby   Midlands  Southampton      South      No
3    Chelsea     West Ham   London      South       London      South     Yes
4  Tottenham      Ipswich   London      South      Ipswich       East      No

In [182]:
all_teams = set(df['HomeTeam'].dropna()) | set(df['AwayTeam'].dropna())

unknown_teams = sorted(
    team for team in all_teams
    if team not in plus_info
)

print('Unknown teams:')
print(unknown_teams)

Unknown teams:
['Brentford']

In [184]:
plus_info['Brentford'] = {
    'City': 'London',
    'Region': 'South'
}

df['HomeCity'] = df['HomeTeam'].map(
    lambda team: plus_info.get(team, {}).get('City')
)

df['HomeRegion'] = df['HomeTeam'].map(
    lambda team: plus_info.get(team, {}).get('Region')
)

df['AwayCity'] = df['AwayTeam'].map(
    lambda team: plus_info.get(team, {}).get('City')
)

df['AwayRegion'] = df['AwayTeam'].map(
    lambda team: plus_info.get(team, {}).get('Region')
)

df['IsDerby'] = (
    df['HomeCity'].notna()
    & df['AwayCity'].notna()
    & df['HomeCity'].eq(df['AwayCity'])
).map({
    True: 'Yes',
    False: 'No'
})

In [185]:
all_teams = set(df['HomeTeam'].dropna()) | set(df['AwayTeam'].dropna())

unknown_teams = sorted(
    team for team in all_teams
    if team not in plus_info
)

print('Unknown teams:')
print(unknown_teams)

Unknown teams:
[]

In [186]:
df.to_csv("Data/matches.csv", index=False)

---

In [187]:
stadium_history = [
    # Arsenal
    {
        'plus': 'Arsenal',
        'StartYear': 1992,
        'EndYear': 2005,
        'Stadium': 'Highbury'
    },
    {
        'plus': 'Arsenal',
        'StartYear': 2006,
        'EndYear': 9999,
        'Stadium': 'Emirates Stadium'
    },

    # Chelsea
    {
        'plus': 'Chelsea',
        'StartYear': 1992,
        'EndYear': 9999,
        'Stadium': 'Stamford Bridge'
    },

    # Tottenham
    {
        'plus': 'Tottenham',
        'StartYear': 1992,
        'EndYear': 2017,
        'Stadium': 'White Hart Lane'
    },
    {
        'plus': 'Tottenham',
        'StartYear': 2018,
        'EndYear': 2018,
        'Stadium': 'Wembley Stadium'
    },
    {
        'plus': 'Tottenham',
        'StartYear': 2019,
        'EndYear': 9999,
        'Stadium': 'Tottenham Hotspur Stadium'
    },

    # West Ham
    {
        'plus': 'West Ham',
        'StartYear': 1992,
        'EndYear': 2016,
        'Stadium': 'Boleyn Ground'
    },
    {
        'plus': 'West Ham',
        'StartYear': 2017,
        'EndYear': 9999,
        'Stadium': 'London Stadium'
    },

    # Manchester United
    {
        'plus': 'Man United',
        'StartYear': 1992,
        'EndYear': 9999,
        'Stadium': 'Old Trafford'
    },

    # Manchester City
    {
        'plus': 'Man City',
        'StartYear': 1992,
        'EndYear': 2003,
        'Stadium': 'Maine Road'
    },
    {
        'plus': 'Man City',
        'StartYear': 2004,
        'EndYear': 9999,
        'Stadium': 'Etihad Stadium'
    },

    # Liverpool
    {
        'plus': 'Liverpool',
        'StartYear': 1992,
        'EndYear': 9999,
        'Stadium': 'Anfield'
    },

    # Everton
    {
        'plus': 'Everton',
        'StartYear': 1992,
        'EndYear': 9999,
        'Stadium': 'Goodison Park'
    },

    # Newcastle
    {
        'plus': 'Newcastle',
        'StartYear': 1992,
        'EndYear': 9999,
        'Stadium': 'St James’ Park'
    },

    # Sunderland
    {
        'plus': 'Sunderland',
        'StartYear': 1992,
        'EndYear': 1997,
        'Stadium': 'Roker Park'
    },
    {
        'plus': 'Sunderland',
        'StartYear': 1997,
        'EndYear': 9999,
        'Stadium': 'Stadium of Light'
    },

    # Aston Villa
    {
        'plus': 'Aston Villa',
        'StartYear': 1992,
        'EndYear': 9999,
        'Stadium': 'Villa Park'
    },

    # Birmingham
    {
        'plus': 'Birmingham',
        'StartYear': 1992,
        'EndYear': 9999,
        'Stadium': 'St Andrew’s'
    },

    # Leeds
    {
        'plus': 'Leeds',
        'StartYear': 1992,
        'EndYear': 9999,
        'Stadium': 'Elland Road'
    },

    # Sheffield
    {
        'plus': 'Sheffield',
        'StartYear': 1992,
        'EndYear': 9999,
        'Stadium': 'Bramall Lane'
    },

    # Nottingham
    {
        'plus': 'Nottingham',
        'StartYear': 1992,
        'EndYear': 9999,
        'Stadium': 'City Ground'
    },

    # Leicester
    {
        'plus': 'Leicester',
        'StartYear': 1992,
        'EndYear': 2002,
        'Stadium': 'Filbert Street'
    },
    {
        'plus': 'Leicester',
        'StartYear': 2003,
        'EndYear': 9999,
        'Stadium': 'King Power Stadium'
    },

    # Southampton
    {
        'plus': 'Southampton',
        'StartYear': 1992,
        'EndYear': 2001,
        'Stadium': 'The Dell'
    },
    {
        'plus': 'Southampton',
        'StartYear': 2001,
        'EndYear': 9999,
        'Stadium': 'St Mary’s Stadium'
    },

    # Fulham
    {
        'plus': 'Fulham',
        'StartYear': 1992,
        'EndYear': 9999,
        'Stadium': 'Craven Cottage'
    },

    # Crystal Palace
    {
        'plus': 'Crystal Palace',
        'StartYear': 1992,
        'EndYear': 9999,
        'Stadium': 'Selhurst Park'
    },

    # Brentford
    {
        'plus': 'Brentford',
        'StartYear': 1992,
        'EndYear': 2019,
        'Stadium': 'Griffin Park'
    },
    {
        'plus': 'Brentford',
        'StartYear': 2020,
        'EndYear': 9999,
        'Stadium': 'Gtech Community Stadium'
    },
]

In [188]:
stadium_history_df = pd.DataFrame(stadium_history)

In [189]:
def get_stadium(team, year):
    if pd.isna(team) or pd.isna(year):
        return pd.NA

    try:
        year = int(year)
    except (ValueError, TypeError):
        return pd.NA

    matched_rows = stadium_history_df[
        (stadium_history_df['plus'] == team)
        & (stadium_history_df['StartYear'] <= year)
        & (stadium_history_df['EndYear'] >= year)
    ]

    if matched_rows.empty:
        return pd.NA

    return matched_rows.iloc[0]['Stadium']

In [190]:
df['HomeStadium'] = df.apply(
    lambda row: get_stadium(
        row['HomeTeam'],
        row['Year']
    ),
    axis=1
)

In [191]:
df['HomeStadium'].isna().sum()

np.int64(3097)

In [192]:
df['HomeStadium'].unique()

array([<NA>, 'Elland Road', 'Stamford Bridge', 'White Hart Lane',
       'Filbert Street', 'Stadium of Light', 'Anfield', 'Old Trafford',
       'Highbury', 'The Dell', 'Maine Road', 'Goodison Park',
       'St James’ Park', 'Boleyn Ground', 'Villa Park', 'Craven Cottage',
       'St Mary’s Stadium', 'St Andrew’s', 'King Power Stadium',
       'Etihad Stadium', 'Selhurst Park', 'Emirates Stadium',
       'Bramall Lane', 'London Stadium', 'Wembley Stadium',
       'Tottenham Hotspur Stadium', 'Gtech Community Stadium',
       'City Ground'], dtype=object)

In [193]:
missing_home_stadium = df[
    df['HomeStadium'].isna()
][
    ['Year', 'HomeTeam', 'AwayTeam']
].drop_duplicates()

print(missing_home_stadium)

      Year       HomeTeam        AwayTeam
0     2000       Charlton        Man City
2     2000          Derby     Southampton
7     2000       Coventry   Middlesbrough
11    2000  Middlesbrough       Tottenham
12    2000       Bradford         Chelsea
13    2000        Ipswich      Man United
20    2000        Ipswich      Sunderland
22    2000  Middlesbrough           Leeds
26    2000       Bradford       Leicester
35    2000       Coventry       Newcastle
37    2000       Charlton     Southampton
38    2000          Derby   Middlesbrough
40    2000  Middlesbrough         Everton
41    2000       Bradford         Arsenal
44    2000        Ipswich     Aston Villa
45    2000       Coventry           Leeds
47    2000          Derby        Charlton
51    2000       Charlton       Tottenham
59    2000       Bradford     Southampton
62    2000       Coventry        West Ham
65    2000          Derby           Leeds
66    2000        Ipswich         Arsenal
67    2000  Middlesbrough     Aston Villa
73    2000       Charlton        Coventry
81    2000        Ipswich        West Ham
84    2000       Coventry       Tottenham
87    2000          Derby       Liverpool
88    2000  Middlesbrough       Newcastle
89    2000       Bradford         Ipswich
90    2000       Charlton   Middlesbrough
105   2000        Ipswich   Middlesbrough
107   2000       Bradford           Leeds
109   2000       Coventry      Man United
112   2000  Middlesbrough         Arsenal
116   2000       Charlton        Bradford
118   2000          Derby        West Ham
122   2000        Ipswich        Charlton
123   2000       Bradford         Everton
134   2000          Derby        Bradford
135   2000       Charlton         Chelsea
136   2000  Middlesbrough       Leicester
138   2000       Coventry         Ipswich
140   2000  Middlesbrough        Bradford
142   2000          Derby      Man United
143   2000       Charlton      Sunderland
146   2000       Coventry     Aston Villa
151   2000       Bradford        Coventry
152   2000        Ipswich           Derby
163   2000       Charlton      Man United
164   2000       Bradford       Tottenham
167   2000       Coventry       Leicester
170   2000        Ipswich     Southampton
175   2000          Derby        Coventry
176   2000  Middlesbrough         Chelsea
179   2000       Coventry     Southampton
185   2000          Derby       Newcastle
187   2000       Charlton         Everton
191   2000       Bradford      Sunderland
193   2000        Ipswich         Chelsea
195   2000  Middlesbrough       Liverpool
199   2000  Middlesbrough        Coventry
202   2000        Ipswich       Tottenham
208   2001          Derby         Everton
210   2001       Charlton         Arsenal
212   2001       Coventry        Man City
218   2001  Middlesbrough           Derby
220   2001       Bradford      Man United
224   2001        Ipswich       Leicester
230   2001       Coventry         Everton
231   2001          Derby        Man City
234   2001       Charlton        West Ham
237   2001       Charlton           Derby
245   2001       Coventry         Arsenal
246   2001          Derby      Sunderland
247   2001        Ipswich           Leeds
251   2001  Middlesbrough        Man City
253   2001       Bradford     Aston Villa
263   2001       Charlton       Newcastle
267   2001        Ipswich         Everton
269   2001          Derby     Aston Villa
270   2001       Coventry        Charlton
271   2001       Bradford        West Ham
272   2001  Middlesbrough     Southampton
274   2001  Middlesbrough        Charlton
279   2001       Coventry         Chelsea
281   2001          Derby       Tottenham
282   2001        Ipswich        Bradford
291   2001       Charlton           Leeds
292   2001       Bradford        Man City
300   2001       Coventry           Derby
302   2001       Bradford       Newcastle
304   2001       Charlton       Leicester
308   2001          Derby         Chelsea
312   2001  Middlesbrough      Sunderland
314   2001        Ipswich       Liverpool
317   2001       Bradford        Charlton
326   2001        Ipswich       Newcastle
328   2001  Middlesbrough         Ipswich
330   2001       Coventry      Sunderland
331   2001          Derby       Leicester
332   2001       Charlton     Aston Villa
338   2001        Ipswich        Coventry
339   2001       Bradford           Derby
346   2001  Middlesbrough      Man United
350   2001          Derby         Arsenal
351   2001       Coventry       Liverpool
353   2001       Charlton         Ipswich
354   2001       Bradford       Liverpool
361   2001       Bradford   Middlesbrough
365   2001        Ipswich        Man City
376   2001          Derby         Ipswich
377   2001       Coventry        Bradford
378   2001       Charlton       Liverpool
379   2001  Middlesbrough        West Ham
381   2001  Middlesbrough         Arsenal
383   2001       Charlton         Everton
386   2001          Derby       Blackburn
392   2001         Bolton   Middlesbrough
393   2001        Ipswich           Derby
394   2001      Blackburn      Man United
401   2001        Ipswich        Charlton
402   2001      Blackburn       Tottenham
405   2001         Bolton       Liverpool
407   2001  Middlesbrough       Newcastle
410   2001          Derby        West Ham
414   2001       Charlton          Fulham
416   2001         Bolton     Southampton
422   2001        Ipswich       Blackburn
427   2001      Blackburn          Bolton
433   2001      Blackburn         Everton
444   2001         Bolton      Sunderland
455   2001         Bolton       Newcastle
456   2001       Charlton   Middlesbrough
458   2001      Blackburn        West Ham
461   2001          Derby        Charlton
481   2001        Ipswich        West Ham
482   2001      Blackburn       Leicester
487   2001         Bolton         Everton
495   2001          Derby     Southampton
496   2001      Blackburn       Liverpool
500   2001        Ipswich          Bolton
507   2001         Bolton          Fulham
515   2001          Derby       Liverpool
518   2001      Blackburn   Middlesbrough
519   2001        Ipswich         Arsenal
528   2001          Derby          Bolton
529   2001       Charlton       Tottenham
532   2001      Blackburn           Leeds
539   2001         Bolton        Charlton
554   2001       Charlton       Blackburn
563   2001         Bolton           Leeds
564   2001      Blackburn      Sunderland
571   2001        Ipswich      Sunderland
572   2001         Bolton       Leicester
573   2001      Blackburn           Derby
580   2002       Charlton         Ipswich
582   2002  Middlesbrough         Everton
585   2002          Derby          Fulham
589   2002      Blackburn        Charlton
590   2002         Bolton         Chelsea
592   2002        Ipswich       Tottenham
601   2002          Derby         Ipswich
603   2002  Middlesbrough          Bolton
607   2002       Charlton     Aston Villa
610   2002         Bolton      Man United
611   2002       Charlton           Derby
614   2002      Blackburn         Arsenal
616   2002        Ipswich          Fulham
626   2002          Derby       Tottenham
628   2002  Middlesbrough        Charlton
633   2002        Ipswich       Liverpool
635   2002          Derby      Sunderland
636   2002         Bolton        West Ham
637   2002  Middlesbrough           Leeds
638   2002       Charlton      Man United
640   2002  Middlesbrough          Fulham
649   2002       Charlton         Chelsea
652   2002         Bolton       Blackburn
653   2002  Middlesbrough       Leicester
654   2002        Ipswich     Southampton
657   2002          Derby      Man United
660   2002      Blackburn     Aston Villa
669   2002      Blackburn         Ipswich
672   2002  Middlesbrough       Liverpool
677   2002         Bolton           Derby
683   2002        Ipswich     Aston Villa
684   2002          Derby         Everton
685   2002       Charlton          Bolton
692   2002  Middlesbrough       Tottenham
696   2002         Bolton     Aston Villa
699   2002      Blackburn     Southampton
700   2002       Charlton         Arsenal
701   2002          Derby   Middlesbrough
704   2002        Ipswich         Chelsea
712   2002         Bolton         Ipswich
713   2002  Middlesbrough     Aston Villa
717   2002      Blackburn         Chelsea
721   2002       Charlton     Southampton
722   2002          Derby       Newcastle
726   2002  Middlesbrough       Blackburn
732   2002         Bolton       Tottenham
734   2002      Blackburn       Newcastle
737   2002        Ipswich   Middlesbrough
739   2002  Middlesbrough         Chelsea
742   2002          Derby           Leeds
744   2002       Charlton      Sunderland
745   2002        Ipswich      Man United
747   2002         Bolton         Arsenal
757   2002      Blackburn          Fulham
762   2002      Blackburn      Sunderland
772   2002      West Brom           Leeds
777   2002         Bolton        Charlton
781   2002       Charlton       Tottenham
786   2002      Blackburn       Liverpool
792   2002      West Brom          Fulham
799   2002  Middlesbrough      Sunderland
808   2002      West Brom     Southampton
812   2002         Bolton       Liverpool
821   2002  Middlesbrough      Birmingham
826   2002      Blackburn           Leeds
833   2002         Bolton     Southampton
837   2002      West Brom       Blackburn
843   2002      Blackburn       Tottenham
849   2002      West Brom      Birmingham
855   2002       Charlton   Middlesbrough
868   2002         Bolton      Sunderland
869   2002      West Brom        Man City
881   2002         Bolton       West Brom
889   2002      West Brom     Aston Villa
897   2002      Blackburn         Everton
904   2002  Middlesbrough        Man City
907   2002       Charlton       Blackburn
909   2002      West Brom   Middlesbrough
920   2002  Middlesbrough        West Ham
925   2002       Charlton       Liverpool
932   2002       Charlton        Man City
938   2002         Bolton           Leeds
940   2002      West Brom      Sunderland
947   2002      Blackburn      Man United
950   2002         Bolton       Newcastle
956   2002      West Brom         Arsenal
958   2002  Middlesbrough      Man United
963   2002       Charlton       West Brom
965   2002      Blackburn        West Ham
973   2003      Blackburn   Middlesbrough
978   2003      West Brom      Man United
980   2003  Middlesbrough     Southampton
981   2003         Bolton          Fulham
992   2003      Blackburn      Birmingham
993   2003       Charlton          Bolton
997   2003       Charlton        West Ham
999   2003         Bolton         Everton
1001  2003  Middlesbrough     Aston Villa
1006  2003      West Brom        Charlton
1009  2003         Bolton      Birmingham
1019  2003      West Brom          Bolton
1024  2003       Charlton         Everton
1025  2003      Blackburn     Southampton
1029  2003         Bolton      Man United
1030  2003       Charlton     Aston Villa
1037  2003      West Brom        West Ham
1041  2003  Middlesbrough         Everton
1043  2003      Blackburn        Man City
1048  2003  Middlesbrough       Newcastle
1051  2003      Blackburn         Arsenal
1052  2003       Charlton       Newcastle
1059  2003      West Brom         Chelsea
1065  2003  Middlesbrough        Charlton
1069  2003         Bolton       Tottenham
1071  2003       Charlton           Leeds
1074  2003         Bolton        Man City
1075  2003  Middlesbrough       West Brom
1082  2003      West Brom         Everton
1086  2003      Blackburn        Charlton
1093  2003  Middlesbrough         Arsenal
1096  2003       Charlton      Birmingham
1097  2003         Bolton        West Ham
1101  2003      Blackburn          Bolton
1106  2003      West Brom       Tottenham
1111  2003      West Brom       Liverpool
1114  2003         Bolton         Arsenal
1116  2003       Charlton     Southampton
1125  2003      Blackburn       West Brom
1126  2003  Middlesbrough       Tottenham
1131  2003      West Brom       Newcastle
1136  2003       Charlton          Fulham
1138  2003         Bolton   Middlesbrough
1140  2003     Portsmouth     Aston Villa
1143  2003      Blackburn          Wolves
1147  2003       Charlton        Man City
1150  2003         Wolves        Charlton
1154  2003         Bolton       Blackburn
1161  2003     Portsmouth          Bolton
1169  2003         Bolton        Charlton
1172  2003  Middlesbrough           Leeds
1174  2003         Wolves      Portsmouth
1181  2003      Blackburn       Liverpool
1183  2003       Charlton      Man United
1192  2003     Portsmouth       Blackburn
1194  2003         Wolves         Chelsea
1202  2003         Bolton          Wolves
1205  2003      Blackburn          Fulham
1206  2003       Charlton       Liverpool
1211  2003     Portsmouth        Charlton
1213  2003         Wolves        Man City
1217  2003  Middlesbrough         Chelsea
1219  2003     Portsmouth       Liverpool
1236  2003         Wolves       Leicester
1239  2003       Charlton         Arsenal
1246  2003  Middlesbrough          Wolves
1251  2003         Wolves      Birmingham
1253  2003     Portsmouth           Leeds
1254  2003         Bolton     Southampton
1259  2003      Blackburn         Everton
1264  2003  Middlesbrough       Liverpool
1270  2003         Wolves       Newcastle
1273  2003      Blackburn       Tottenham
1274  2003     Portsmouth       Leicester
1285  2003  Middlesbrough      Portsmouth
1292  2003     Portsmouth         Everton
1304  2003      Blackburn     Aston Villa
1309  2003     Portsmouth       Tottenham
1313  2003       Charlton         Chelsea
1319  2003         Bolton       Leicester
1323  2003  Middlesbrough      Man United
1326  2003         Wolves           Leeds
1330  2004         Bolton      Man United
1331  2004         Wolves       Blackburn
1335  2004  Middlesbrough          Fulham
1338  2004       Charlton          Wolves
1342  2004     Portsmouth        Man City
1345  2004      Blackburn          Bolton
1349  2004  Middlesbrough       Leicester
1352  2004         Wolves      Man United
1353  2004         Bolton      Portsmouth
1358  2004         Wolves       Liverpool
1360  2004       Charlton          Bolton
1366  2004     Portsmouth          Wolves
1368  2004      Blackburn         Chelsea
1369  2004         Wolves         Arsenal
1375  2004  Middlesbrough       Blackburn
1376  2004         Bolton       Liverpool
1383  2004      Blackburn       Newcastle
1384  2004       Charlton       Tottenham
1388  2004     Portsmouth         Chelsea
1389  2004         Wolves          Fulham
1393  2004       Charlton       Blackburn
1394  2004         Bolton        Man City
1402  2004      Blackburn     Southampton
1405  2004     Portsmouth       Newcastle
1408  2004  Middlesbrough       Tottenham
1410  2004      Blackburn         Arsenal
1411  2004         Bolton         Chelsea
1413  2004       Charlton   Middlesbrough
1418  2004         Wolves     Aston Villa
1421  2004  Middlesbrough      Birmingham
1428  2004     Portsmouth     Southampton
1430  2004       Charlton     Aston Villa
1433  2004      Blackburn      Portsmouth
1438  2004         Bolton       Newcastle
1440  2004  Middlesbrough          Bolton
1443  2004         Wolves     Southampton
1450  2004      Blackburn           Leeds
1454  2004       Charlton      Portsmouth
1455  2004         Bolton     Aston Villa
1460  2004  Middlesbrough     Southampton
1461  2004     Portsmouth      Birmingham
1463  2004         Wolves          Bolton
1468  2004       Charlton      Birmingham
1469  2004         Bolton       Tottenham
1470  2004         Wolves   Middlesbrough
1471  2004     Portsmouth      Man United
1472  2004      Blackburn       Leicester
1482  2004  Middlesbrough     Aston Villa
1488  2004     Portsmouth          Fulham
1489  2004         Wolves         Everton
1491  2004       Charlton       Leicester
1494  2004      Blackburn      Man United
1496  2004         Bolton           Leeds
1498  2004     Portsmouth         Arsenal
1504  2004  Middlesbrough        Man City
1512  2004      Blackburn      Birmingham
1513  2004         Bolton          Fulham
1514  2004       Charlton     Southampton
1518  2004     Portsmouth   Middlesbrough
1519  2004         Wolves       Tottenham
1522  2004        Norwich  Crystal Palace
1523  2004         Bolton        Charlton
1525  2004      Blackburn       West Brom
1527  2004  Middlesbrough       Newcastle
1539  2004      West Brom     Aston Villa
1542  2004      West Brom       Tottenham
1548  2004        Norwich         Arsenal
1550  2004  Middlesbrough  Crystal Palace
1565  2004     Portsmouth  Crystal Palace
1569  2004        Norwich     Aston Villa
1570  2004      West Brom          Fulham
1581  2004  Middlesbrough         Chelsea
1584  2004         Bolton      Birmingham
1587  2004     Portsmouth         Everton
1589  2004      West Brom          Bolton
1593  2004        Norwich      Portsmouth
1594  2004      Blackburn     Aston Villa
1599  2004      Blackburn   Middlesbrough
1600  2004         Bolton  Crystal Palace
1604  2004      West Brom         Norwich
1607  2004       Charlton       Newcastle
1608  2004     Portsmouth       Tottenham
1612  2004        Norwich         Everton
1618  2004  Middlesbrough      Portsmouth
1619  2004      West Brom         Chelsea
1624  2004      Blackburn       Liverpool
1633  2004        Norwich       Blackburn
1641  2004       Charlton         Norwich
1648  2004      West Brom   Middlesbrough
1650  2004        Norwich     Southampton
1651  2004  Middlesbrough       Liverpool
1659  2004      West Brom      Man United
1663  2004       Charlton         Chelsea
1669  2004     Portsmouth       West Brom
1670  2004        Norwich          Fulham
1673  2004      Blackburn       Tottenham
1679  2004      West Brom        Charlton
1684  2004        Norwich          Bolton
1691  2004      Blackburn         Everton
1699  2004       Charlton          Fulham
1700  2004        Norwich       Tottenham
1701  2004      West Brom       Liverpool
1712  2004  Middlesbrough         Norwich
1715  2004       Charlton         Everton
1716  2004         Bolton       Blackburn
1721  2005     Portsmouth         Norwich
1723  2005  Middlesbrough      Man United
1726  2005       Charlton         Arsenal
1727  2005         Bolton       West Brom
1730  2005      Blackburn        Charlton
1732  2005        Norwich       Liverpool
1733  2005      West Brom       Newcastle
1740  2005     Portsmouth       Blackburn
1744  2005       Charlton      Birmingham
1745  2005         Bolton         Arsenal
1749  2005  Middlesbrough         Everton
1750  2005      West Brom        Man City
1751  2005        Norwich   Middlesbrough
1759  2005      Blackburn          Bolton
1761  2005         Bolton       Tottenham
1762  2005       Charlton       Liverpool
1763  2005     Portsmouth   Middlesbrough
1764  2005      West Brom  Crystal Palace
1767  2005      Blackburn         Chelsea
1772  2005  Middlesbrough       Blackburn
1774  2005        Norwich       West Brom
1780  2005     Portsmouth     Aston Villa
1781  2005      Blackburn         Norwich
1782  2005         Bolton   Middlesbrough
1787  2005      West Brom     Southampton
1793  2005  Middlesbrough        Charlton
1795  2005        Norwich        Man City
1802  2005        Norwich         Chelsea
1804  2005      West Brom      Birmingham
1807  2005       Charlton       Tottenham
1809  2005     Portsmouth       Newcastle
1812  2005       Charlton       West Brom
1814  2005         Bolton         Norwich
1815  2005      Blackburn         Arsenal
1817  2005  Middlesbrough     Southampton
1823  2005       Charlton        Man City
1827  2005      West Brom         Everton
1829  2005      Blackburn     Southampton
1830  2005         Bolton          Fulham
1833  2005  Middlesbrough         Arsenal
1834  2005        Norwich      Man United
1835  2005     Portsmouth        Charlton
1840  2005       Charlton          Bolton
1845  2005         Bolton     Southampton

In [194]:
unknown_home_teams = sorted(
    df.loc[df['HomeStadium'].isna(), 'HomeTeam']
    .dropna()
    .unique()
)

print('Unknown home teams:')
print(unknown_home_teams)

Unknown home teams:
['Blackburn', 'Blackpool', 'Bolton', 'Bournemouth', 'Bradford', 'Brighton', 'Burnley', 'Cardiff', 'Charlton', 'Coventry', 'Derby', 'Huddersfield', 'Hull', 'Ipswich', 'Luton', 'Middlesbrough', 'Norwich', 'Portsmouth', 'QPR', 'Reading', 'Stoke', 'Swansea', 'Watford', 'West Brom', 'Wigan', 'Wolves']

In [195]:
stadium_history = [
    {'plus': 'Arsenal', 'StartYear': 1992, 'EndYear': 2005, 'Stadium': 'Highbury'},
    {'plus': 'Arsenal', 'StartYear': 2006, 'EndYear': 9999, 'Stadium': 'Emirates Stadium'},
    {'plus': 'Chelsea', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Stamford Bridge'},
    {'plus': 'Tottenham', 'StartYear': 1992, 'EndYear': 2016, 'Stadium': 'White Hart Lane'},
    {'plus': 'Tottenham', 'StartYear': 2017, 'EndYear': 2018, 'Stadium': 'Wembley Stadium'},
    {'plus': 'Tottenham', 'StartYear': 2019, 'EndYear': 9999, 'Stadium': 'Tottenham Hotspur Stadium'},
    {'plus': 'West Ham', 'StartYear': 1992, 'EndYear': 2015, 'Stadium': 'Boleyn Ground'},
    {'plus': 'West Ham', 'StartYear': 2016, 'EndYear': 9999, 'Stadium': 'London Stadium'},
    {'plus': 'Man United', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Old Trafford'},
    {'plus': 'Man City', 'StartYear': 1992, 'EndYear': 2002, 'Stadium': 'Maine Road'},
    {'plus': 'Man City', 'StartYear': 2003, 'EndYear': 9999, 'Stadium': 'Etihad Stadium'},
    {'plus': 'Liverpool', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Anfield'},
    {'plus': 'Everton', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Goodison Park'},
    {'plus': 'Newcastle', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'St James’ Park'},
    {'plus': 'Sunderland', 'StartYear': 1992, 'EndYear': 1996, 'Stadium': 'Roker Park'},
    {'plus': 'Sunderland', 'StartYear': 1997, 'EndYear': 9999, 'Stadium': 'Stadium of Light'},
    {'plus': 'Aston Villa', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Villa Park'},
    {'plus': 'Birmingham', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'St Andrew’s'},
    {'plus': 'Leeds', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Elland Road'},
    {'plus': 'Sheffield', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Bramall Lane'},
    {'plus': 'Nottingham', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'City Ground'},
    {'plus': 'Leicester', 'StartYear': 1992, 'EndYear': 2001, 'Stadium': 'Filbert Street'},
    {'plus': 'Leicester', 'StartYear': 2002, 'EndYear': 9999, 'Stadium': 'King Power Stadium'},
    {'plus': 'Southampton', 'StartYear': 1992, 'EndYear': 2000, 'Stadium': 'The Dell'},
    {'plus': 'Southampton', 'StartYear': 2001, 'EndYear': 9999, 'Stadium': 'St Mary’s Stadium'},
    {'plus': 'Fulham', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Craven Cottage'},
    {'plus': 'Crystal Palace', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Selhurst Park'},
    {'plus': 'Brentford', 'StartYear': 1992, 'EndYear': 2019, 'Stadium': 'Griffin Park'},
    {'plus': 'Brentford', 'StartYear': 2020, 'EndYear': 9999, 'Stadium': 'Gtech Community Stadium'},


    {'plus': 'Blackburn', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Ewood Park'},
    {'plus': 'Blackpool', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Bloomfield Road'},
    
    {'plus': 'Bolton', 'StartYear': 1992, 'EndYear': 1996, 'Stadium': 'Burnden Park'},
    {'plus': 'Bolton', 'StartYear': 1997, 'EndYear': 9999, 'Stadium': 'Reebok Stadium'},
    
    {'plus': 'Bournemouth', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Dean Court / Vitality Stadium'},
    {'plus': 'Bradford', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Valley Parade'},
    
    {'plus': 'Brighton', 'StartYear': 1992, 'EndYear': 1996, 'Stadium': 'Goldstone Ground'},
    {'plus': 'Brighton', 'StartYear': 1997, 'EndYear': 1998, 'Stadium': 'Priestfield Stadium'},
    {'plus': 'Brighton', 'StartYear': 1999, 'EndYear': 2010, 'Stadium': 'Withdean Stadium'},
    {'plus': 'Brighton', 'StartYear': 2011, 'EndYear': 9999, 'Stadium': 'Amex Stadium'},
    
    {'plus': 'Burnley', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Turf Moor'},
    
    {'plus': 'Cardiff', 'StartYear': 1992, 'EndYear': 2008, 'Stadium': 'Ninian Park'},
    {'plus': 'Cardiff', 'StartYear': 2009, 'EndYear': 9999, 'Stadium': 'Cardiff City Stadium'},
    
    {'plus': 'Charlton', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'The Valley'},
    
    {'plus': 'Coventry', 'StartYear': 1992, 'EndYear': 2004, 'Stadium': 'Highfield Road'},
    {'plus': 'Coventry', 'StartYear': 2005, 'EndYear': 9999, 'Stadium': 'Ricoh Arena'},
    
    {'plus': 'Derby', 'StartYear': 1992, 'EndYear': 1996, 'Stadium': 'Baseball Ground'},
    {'plus': 'Derby', 'StartYear': 1997, 'EndYear': 9999, 'Stadium': 'Pride Park'},
    
    {'plus': 'Huddersfield', 'StartYear': 1992, 'EndYear': 1993, 'Stadium': 'Leeds Road'},
    {'plus': 'Huddersfield', 'StartYear': 1994, 'EndYear': 9999, 'Stadium': 'Kirklees / John Smith’s Stadium'},
    
    {'plus': 'Hull', 'StartYear': 1992, 'EndYear': 2001, 'Stadium': 'Boothferry Park'},
    {'plus': 'Hull', 'StartYear': 2002, 'EndYear': 9999, 'Stadium': 'MKM / KC Stadium'},
    
    {'plus': 'Ipswich', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Portman Road'},
    {'plus': 'Luton', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Kenilworth Road'},
    
    {'plus': 'Middlesbrough', 'StartYear': 1992, 'EndYear': 1994, 'Stadium': 'Ayresome Park'},
    {'plus': 'Middlesbrough', 'StartYear': 1995, 'EndYear': 9999, 'Stadium': 'Riverside Stadium'},
    
    {'plus': 'Norwich', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Carrow Road'},
    {'plus': 'Portsmouth', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Fratton Park'},
    {'plus': 'QPR', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Loftus Road'},
    
    {'plus': 'Reading', 'StartYear': 1992, 'EndYear': 1997, 'Stadium': 'Elm Park'},
    {'plus': 'Reading', 'StartYear': 1998, 'EndYear': 9999, 'Stadium': 'Madejski Stadium'},
    
    {'plus': 'Stoke', 'StartYear': 1992, 'EndYear': 1996, 'Stadium': 'Victoria Ground'},
    {'plus': 'Stoke', 'StartYear': 1997, 'EndYear': 9999, 'Stadium': 'Britannia Stadium'},
    
    {'plus': 'Swansea', 'StartYear': 1992, 'EndYear': 2004, 'Stadium': 'Vetch Field'},
    {'plus': 'Swansea', 'StartYear': 2005, 'EndYear': 9999, 'Stadium': 'Liberty Stadium'},
    
    {'plus': 'Watford', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Vicarage Road'},
    {'plus': 'West Brom', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'The Hawthorns'},
    
    {'plus': 'Wigan', 'StartYear': 1992, 'EndYear': 1998, 'Stadium': 'Springfield Park'},
    {'plus': 'Wigan', 'StartYear': 1999, 'EndYear': 9999, 'Stadium': 'DW Stadium'},
    
    {'plus': 'Wolves', 'StartYear': 1992, 'EndYear': 9999, 'Stadium': 'Molineux'}
]

stadium_history_df = pd.DataFrame(stadium_history)

def get_stadium(team, year):
    if pd.isna(team) or pd.isna(year):
        return pd.NA

    try:
        year = int(year)
    except (ValueError, TypeError):
        return pd.NA

    result = stadium_history_df[
        (stadium_history_df['plus'] == team)
        & (stadium_history_df['StartYear'] <= year)
        & (stadium_history_df['EndYear'] >= year)
    ]

    if result.empty:
        return pd.NA

    return result.iloc[0]['Stadium']


df['HomeStadium'] = df.apply(
    lambda row: get_stadium(row['HomeTeam'], row['Year']),
    axis=1
)

unknown_home_teams = sorted(
    df.loc[df['HomeStadium'].isna(), 'HomeTeam'].dropna().unique()
)
print('Unknown home teams:', unknown_home_teams)

Unknown home teams: []

In [196]:
df.to_csv("Data/matches.csv", index=False)

---

In [197]:
manager_history = [
    # Arsenal
    {'plus': 'Arsenal', 'StartYear': 1992, 'EndYear': 1994, 'Manager': 'George Graham'},
    {'plus': 'Arsenal', 'StartYear': 1995, 'EndYear': 1995, 'Manager': 'Bruce Rioch'},
    {'plus': 'Arsenal', 'StartYear': 1996, 'EndYear': 2017, 'Manager': 'Arsene Wenger'},
    {'plus': 'Arsenal', 'StartYear': 2018, 'EndYear': 2018, 'Manager': 'Unai Emery'},
    {'plus': 'Arsenal', 'StartYear': 2019, 'EndYear': 9999, 'Manager': 'Mikel Arteta'},

    # Manchester United
    {'plus': 'Man United', 'StartYear': 1992, 'EndYear': 2012, 'Manager': 'Sir Alex Ferguson'},
    {'plus': 'Man United', 'StartYear': 2013, 'EndYear': 2013, 'Manager': 'David Moyes'},
    {'plus': 'Man United', 'StartYear': 2014, 'EndYear': 2015, 'Manager': 'Louis van Gaal'},
    {'plus': 'Man United', 'StartYear': 2016, 'EndYear': 2017, 'Manager': 'Jose Mourinho'},
    {'plus': 'Man United', 'StartYear': 2018, 'EndYear': 2020, 'Manager': 'Ole Gunnar Solskjaer'},
    {'plus': 'Man United', 'StartYear': 2021, 'EndYear': 9999, 'Manager': 'Erik ten Hag'},

    # Liverpool
    {'plus': 'Liverpool', 'StartYear': 1992, 'EndYear': 1997, 'Manager': 'Roy Evans'},
    {'plus': 'Liverpool', 'StartYear': 1998, 'EndYear': 2003, 'Manager': 'Gerard Houllier'},
    {'plus': 'Liverpool', 'StartYear': 2004, 'EndYear': 2009, 'Manager': 'Rafa Benitez'},
    {'plus': 'Liverpool', 'StartYear': 2010, 'EndYear': 2011, 'Manager': 'Kenny Dalglish'},
    {'plus': 'Liverpool', 'StartYear': 2012, 'EndYear': 2014, 'Manager': 'Brendan Rodgers'},
    {'plus': 'Liverpool', 'StartYear': 2015, 'EndYear': 2023, 'Manager': 'Jurgen Klopp'},
    {'plus': 'Liverpool', 'StartYear': 2024, 'EndYear': 9999, 'Manager': 'Arne Slot'},

    # Manchester City
    {'plus': 'Man City', 'StartYear': 1992, 'EndYear': 2000, 'Manager': 'Joe Royle'}, # (خلاصه‌شده سال‌های اولیه)
    {'plus': 'Man City', 'StartYear': 2001, 'EndYear': 2004, 'Manager': 'Kevin Keegan'},
    {'plus': 'Man City', 'StartYear': 2005, 'EndYear': 2006, 'Manager': 'Stuart Pearce'},
    {'plus': 'Man City', 'StartYear': 2007, 'EndYear': 2007, 'Manager': 'Sven-Goran Eriksson'},
    {'plus': 'Man City', 'StartYear': 2008, 'EndYear': 2008, 'Manager': 'Mark Hughes'},
    {'plus': 'Man City', 'StartYear': 2009, 'EndYear': 2012, 'Manager': 'Roberto Mancini'},
    {'plus': 'Man City', 'StartYear': 2013, 'EndYear': 2015, 'Manager': 'Manuel Pellegrini'},
    {'plus': 'Man City', 'StartYear': 2016, 'EndYear': 9999, 'Manager': 'Pep Guardiola'},

    # Chelsea
    {'plus': 'Chelsea', 'StartYear': 1992, 'EndYear': 1999, 'Manager': 'Ruud Gullit / Vialli'}, # (خلاصه‌شده)
    {'plus': 'Chelsea', 'StartYear': 2000, 'EndYear': 2003, 'Manager': 'Claudio Ranieri'},
    {'plus': 'Chelsea', 'StartYear': 2004, 'EndYear': 2006, 'Manager': 'Jose Mourinho'},
    {'plus': 'Chelsea', 'StartYear': 2007, 'EndYear': 2008, 'Manager': 'Avram Grant / Scolari'},
    {'plus': 'Chelsea', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Carlo Ancelotti'},
    {'plus': 'Chelsea', 'StartYear': 2011, 'EndYear': 2012, 'Manager': 'Roberto Di Matteo'},
    {'plus': 'Chelsea', 'StartYear': 2013, 'EndYear': 2014, 'Manager': 'Jose Mourinho'},
    {'plus': 'Chelsea', 'StartYear': 2015, 'EndYear': 2015, 'Manager': 'Guus Hiddink'},
    {'plus': 'Chelsea', 'StartYear': 2016, 'EndYear': 2017, 'Manager': 'Antonio Conte'},
    {'plus': 'Chelsea', 'StartYear': 2018, 'EndYear': 2018, 'Manager': 'Maurizio Sarri'},
    {'plus': 'Chelsea', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Frank Lampard'},
    {'plus': 'Chelsea', 'StartYear': 2021, 'EndYear': 2021, 'Manager': 'Thomas Tuchel'},
    {'plus': 'Chelsea', 'StartYear': 2022, 'EndYear': 2022, 'Manager': 'Graham Potter'},
    {'plus': 'Chelsea', 'StartYear': 2023, 'EndYear': 2023, 'Manager': 'Mauricio Pochettino'},
    {'plus': 'Chelsea', 'StartYear': 2024, 'EndYear': 9999, 'Manager': 'Enzo Maresca'},

    # Tottenham
    {'plus': 'Tottenham', 'StartYear': 1992, 'EndYear': 2003, 'Manager': 'Gerry Francis / Hoddle'}, # (خلاصه‌شده)
    {'plus': 'Tottenham', 'StartYear': 2004, 'EndYear': 2007, 'Manager': 'Martin Jol'},
    {'plus': 'Tottenham', 'StartYear': 2008, 'EndYear': 2011, 'Manager': 'Harry Redknapp'},
    {'plus': 'Tottenham', 'StartYear': 2012, 'EndYear': 2013, 'Manager': 'Andre Villas-Boas'},
    {'plus': 'Tottenham', 'StartYear': 2014, 'EndYear': 2018, 'Manager': 'Mauricio Pochettino'},
    {'plus': 'Tottenham', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Jose Mourinho'},
    {'plus': 'Tottenham', 'StartYear': 2021, 'EndYear': 2022, 'Manager': 'Antonio Conte'},
    {'plus': 'Tottenham', 'StartYear': 2023, 'EndYear': 9999, 'Manager': 'Ange Postecoglou'},
]

manager_df = pd.DataFrame(manager_history)

def get_manager(team, year):
    if pd.isna(team) or pd.isna(year):
        return pd.NA

    try:
        year = int(year)
    except (ValueError, TypeError):
        return pd.NA

    result = manager_df[
        (manager_df['plus'] == team)
        & (manager_df['StartYear'] <= year)
        & (manager_df['EndYear'] >= year)
    ]

    if result.empty:
        return pd.NA

    return result.iloc[0]['Manager']


df['HomeManager'] = df.apply(
    lambda row: get_manager(row['HomeTeam'], row['Year']),
    axis=1
)

df['AwayManager'] = df.apply(
    lambda row: get_manager(row['AwayTeam'], row['Year']),
    axis=1
)

print(
    df[
        ['Year', 'HomeTeam', 'AwayTeam', 'HomeManager', 'AwayManager']
    ].head(10)
)

   Year    HomeTeam       AwayTeam             HomeManager    AwayManager
0  2000    Charlton       Man City                    <NA>      Joe Royle
1  2000       Leeds        Everton                    <NA>           <NA>
2  2000       Derby    Southampton                    <NA>           <NA>
3  2000     Chelsea       West Ham         Claudio Ranieri           <NA>
4  2000   Tottenham        Ipswich  Gerry Francis / Hoddle           <NA>
5  2000   Leicester    Aston Villa                    <NA>           <NA>
6  2000  Sunderland        Arsenal                    <NA>  Arsene Wenger
7  2000    Coventry  Middlesbrough                    <NA>           <NA>
8  2000   Liverpool       Bradford         Gerard Houllier           <NA>
9  2000  Man United      Newcastle       Sir Alex Ferguson           <NA>

In [199]:
df['HomeTeam'].unique()

array(['Charlton', 'Leeds', 'Derby', 'Chelsea', 'Tottenham', 'Leicester',
       'Sunderland', 'Coventry', 'Liverpool', 'Man United', 'Arsenal',
       'Middlesbrough', 'Bradford', 'Ipswich', 'Southampton', 'Man City',
       'Everton', 'Newcastle', 'West Ham', 'Aston Villa', 'Bolton',
       'Blackburn', 'Fulham', 'West Brom', 'Birmingham', 'Portsmouth',
       'Wolves', 'Norwich', 'Crystal Palace', 'Wigan', 'Sheffield',
       'Reading', 'Watford', 'Hull', 'Stoke', 'Burnley', 'Blackpool',
       'QPR', 'Swansea', 'Cardiff', 'Bournemouth', 'Brighton',
       'Huddersfield', 'Brentford', 'Nottingham', 'Luton'], dtype=object)

In [200]:
manager_history = [
    # Arsenal
    {'plus': 'Arsenal', 'StartYear': 1992, 'EndYear': 1994, 'Manager': 'George Graham'},
    {'plus': 'Arsenal', 'StartYear': 1995, 'EndYear': 1995, 'Manager': 'Bruce Rioch'},
    {'plus': 'Arsenal', 'StartYear': 1996, 'EndYear': 2017, 'Manager': 'Arsene Wenger'},
    {'plus': 'Arsenal', 'StartYear': 2018, 'EndYear': 2018, 'Manager': 'Unai Emery'},
    {'plus': 'Arsenal', 'StartYear': 2019, 'EndYear': 9999, 'Manager': 'Mikel Arteta'},

    # Manchester United
    {'plus': 'Man United', 'StartYear': 1992, 'EndYear': 2012, 'Manager': 'Sir Alex Ferguson'},
    {'plus': 'Man United', 'StartYear': 2013, 'EndYear': 2013, 'Manager': 'David Moyes'},
    {'plus': 'Man United', 'StartYear': 2014, 'EndYear': 2015, 'Manager': 'Louis van Gaal'},
    {'plus': 'Man United', 'StartYear': 2016, 'EndYear': 2017, 'Manager': 'Jose Mourinho'},
    {'plus': 'Man United', 'StartYear': 2018, 'EndYear': 2020, 'Manager': 'Ole Gunnar Solskjaer'},
    {'plus': 'Man United', 'StartYear': 2021, 'EndYear': 9999, 'Manager': 'Erik ten Hag'},

    # Liverpool
    {'plus': 'Liverpool', 'StartYear': 1992, 'EndYear': 1997, 'Manager': 'Roy Evans'},
    {'plus': 'Liverpool', 'StartYear': 1998, 'EndYear': 2003, 'Manager': 'Gerard Houllier'},
    {'plus': 'Liverpool', 'StartYear': 2004, 'EndYear': 2009, 'Manager': 'Rafa Benitez'},
    {'plus': 'Liverpool', 'StartYear': 2010, 'EndYear': 2011, 'Manager': 'Kenny Dalglish'},
    {'plus': 'Liverpool', 'StartYear': 2012, 'EndYear': 2014, 'Manager': 'Brendan Rodgers'},
    {'plus': 'Liverpool', 'StartYear': 2015, 'EndYear': 2023, 'Manager': 'Jurgen Klopp'},
    {'plus': 'Liverpool', 'StartYear': 2024, 'EndYear': 9999, 'Manager': 'Arne Slot'},

    # Manchester City
    {'plus': 'Man City', 'StartYear': 1992, 'EndYear': 1995, 'Manager': 'Brian Horton'},
    {'plus': 'Man City', 'StartYear': 1996, 'EndYear': 1998, 'Manager': 'Frank Clark / Steve Coppell'},
    {'plus': 'Man City', 'StartYear': 1999, 'EndYear': 2000, 'Manager': 'Joe Royle'},
    {'plus': 'Man City', 'StartYear': 2001, 'EndYear': 2004, 'Manager': 'Kevin Keegan'},
    {'plus': 'Man City', 'StartYear': 2005, 'EndYear': 2006, 'Manager': 'Stuart Pearce'},
    {'plus': 'Man City', 'StartYear': 2007, 'EndYear': 2007, 'Manager': 'Sven-Goran Eriksson'},
    {'plus': 'Man City', 'StartYear': 2008, 'EndYear': 2008, 'Manager': 'Mark Hughes'},
    {'plus': 'Man City', 'StartYear': 2009, 'EndYear': 2012, 'Manager': 'Roberto Mancini'},
    {'plus': 'Man City', 'StartYear': 2013, 'EndYear': 2015, 'Manager': 'Manuel Pellegrini'},
    {'plus': 'Man City', 'StartYear': 2016, 'EndYear': 9999, 'Manager': 'Pep Guardiola'},

    # Chelsea
    {'plus': 'Chelsea', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Ian Porterfield'},
    {'plus': 'Chelsea', 'StartYear': 1994, 'EndYear': 1995, 'Manager': 'Glenn Hoddle'},
    {'plus': 'Chelsea', 'StartYear': 1996, 'EndYear': 1998, 'Manager': 'Ruud Gullit'},
    {'plus': 'Chelsea', 'StartYear': 1998, 'EndYear': 1999, 'Manager': 'Gianluca Vialli'},
    {'plus': 'Chelsea', 'StartYear': 2000, 'EndYear': 2003, 'Manager': 'Claudio Ranieri'},
    {'plus': 'Chelsea', 'StartYear': 2004, 'EndYear': 2007, 'Manager': 'Jose Mourinho'},
    {'plus': 'Chelsea', 'StartYear': 2008, 'EndYear': 2008, 'Manager': 'Luiz Felipe Scolari'},
    {'plus': 'Chelsea', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Carlo Ancelotti'},
    {'plus': 'Chelsea', 'StartYear': 2011, 'EndYear': 2012, 'Manager': 'Roberto Di Matteo'},
    {'plus': 'Chelsea', 'StartYear': 2013, 'EndYear': 2014, 'Manager': 'Jose Mourinho'},
    {'plus': 'Chelsea', 'StartYear': 2015, 'EndYear': 2015, 'Manager': 'Guus Hiddink'},
    {'plus': 'Chelsea', 'StartYear': 2016, 'EndYear': 2017, 'Manager': 'Antonio Conte'},
    {'plus': 'Chelsea', 'StartYear': 2018, 'EndYear': 2018, 'Manager': 'Maurizio Sarri'},
    {'plus': 'Chelsea', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Frank Lampard'},
    {'plus': 'Chelsea', 'StartYear': 2021, 'EndYear': 2021, 'Manager': 'Thomas Tuchel'},
    {'plus': 'Chelsea', 'StartYear': 2022, 'EndYear': 2022, 'Manager': 'Graham Potter'},
    {'plus': 'Chelsea', 'StartYear': 2023, 'EndYear': 2023, 'Manager': 'Mauricio Pochettino'},
    {'plus': 'Chelsea', 'StartYear': 2024, 'EndYear': 9999, 'Manager': 'Enzo Maresca'},

    # Tottenham
    {'plus': 'Tottenham', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Doug Livermore / Ray Clemence'},
    {'plus': 'Tottenham', 'StartYear': 1994, 'EndYear': 1997, 'Manager': 'Gerry Francis'},
    {'plus': 'Tottenham', 'StartYear': 1998, 'EndYear': 2000, 'Manager': 'George Graham'},
    {'plus': 'Tottenham', 'StartYear': 2001, 'EndYear': 2003, 'Manager': 'Glenn Hoddle'},
    {'plus': 'Tottenham', 'StartYear': 2004, 'EndYear': 2007, 'Manager': 'Martin Jol'},
    {'plus': 'Tottenham', 'StartYear': 2008, 'EndYear': 2011, 'Manager': 'Harry Redknapp'},
    {'plus': 'Tottenham', 'StartYear': 2012, 'EndYear': 2013, 'Manager': 'Andre Villas-Boas'},
    {'plus': 'Tottenham', 'StartYear': 2014, 'EndYear': 2018, 'Manager': 'Mauricio Pochettino'},
    {'plus': 'Tottenham', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Jose Mourinho'},
    {'plus': 'Tottenham', 'StartYear': 2021, 'EndYear': 2022, 'Manager': 'Antonio Conte'},
    {'plus': 'Tottenham', 'StartYear': 2023, 'EndYear': 9999, 'Manager': 'Ange Postecoglou'},

    # Newcastle United
    {'plus': 'Newcastle', 'StartYear': 1992, 'EndYear': 1996, 'Manager': 'Kevin Keegan'},
    {'plus': 'Newcastle', 'StartYear': 1997, 'EndYear': 1998, 'Manager': 'Kenny Dalglish'},
    {'plus': 'Newcastle', 'StartYear': 1998, 'EndYear': 1999, 'Manager': 'Ruud Gullit'},
    {'plus': 'Newcastle', 'StartYear': 1999, 'EndYear': 2004, 'Manager': 'Sir Bobby Robson'},
    {'plus': 'Newcastle', 'StartYear': 2005, 'EndYear': 2006, 'Manager': 'Graeme Souness'},
    {'plus': 'Newcastle', 'StartYear': 2007, 'EndYear': 2007, 'Manager': 'Glenn Roeder'},
    {'plus': 'Newcastle', 'StartYear': 2008, 'EndYear': 2008, 'Manager': 'Kevin Keegan'},
    {'plus': 'Newcastle', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Alan Shearer / Chris Hughton'},
    {'plus': 'Newcastle', 'StartYear': 2011, 'EndYear': 2014, 'Manager': 'Alan Pardew'},
    {'plus': 'Newcastle', 'StartYear': 2015, 'EndYear': 2015, 'Manager': 'John Carver'},
    {'plus': 'Newcastle', 'StartYear': 2016, 'EndYear': 2016, 'Manager': 'Rafa Benitez'},
    {'plus': 'Newcastle', 'StartYear': 2017, 'EndYear': 2018, 'Manager': 'Rafa Benitez'},
    {'plus': 'Newcastle', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Steve Bruce'},
    {'plus': 'Newcastle', 'StartYear': 2021, 'EndYear': 2021, 'Manager': 'Graeme Jones (interim)'},
    {'plus': 'Newcastle', 'StartYear': 2022, 'EndYear': 9999, 'Manager': 'Eddie Howe'},

    # Everton
    {'plus': 'Everton', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Howard Kendall'},
    {'plus': 'Everton', 'StartYear': 1994, 'EndYear': 1997, 'Manager': 'Joe Royle'},
    {'plus': 'Everton', 'StartYear': 1998, 'EndYear': 2000, 'Manager': 'Walter Smith'},
    {'plus': 'Everton', 'StartYear': 2001, 'EndYear': 2001, 'Manager': 'David Moyes'},
    {'plus': 'Everton', 'StartYear': 2002, 'EndYear': 2012, 'Manager': 'David Moyes'},
    {'plus': 'Everton', 'StartYear': 2013, 'EndYear': 2015, 'Manager': 'Roberto Martinez'},
    {'plus': 'Everton', 'StartYear': 2016, 'EndYear': 2016, 'Manager': 'Ronald Koeman'},
    {'plus': 'Everton', 'StartYear': 2017, 'EndYear': 2018, 'Manager': 'Sam Allardyce'},
    {'plus': 'Everton', 'StartYear': 2019, 'EndYear': 2019, 'Manager': 'Marco Silva'},
    {'plus': 'Everton', 'StartYear': 2020, 'EndYear': 2021, 'Manager': 'Carlo Ancelotti'},
    {'plus': 'Everton', 'StartYear': 2022, 'EndYear': 2022, 'Manager': 'Frank Lampard'},
    {'plus': 'Everton', 'StartYear': 2023, 'EndYear': 9999, 'Manager': 'Sean Dyche'},

    # Aston Villa
    {'plus': 'Aston Villa', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Ron Atkinson'},
    {'plus': 'Aston Villa', 'StartYear': 1994, 'EndYear': 1996, 'Manager': 'Brian Little'},
    {'plus': 'Aston Villa', 'StartYear': 1997, 'EndYear': 2000, 'Manager': 'John Gregory'},
    {'plus': 'Aston Villa', 'StartYear': 2001, 'EndYear': 2002, 'Manager': 'Graham Taylor'},
    {'plus': 'Aston Villa', 'StartYear': 2003, 'EndYear': 2006, 'Manager': 'David O\'Leary'},
    {'plus': 'Aston Villa', 'StartYear': 2007, 'EndYear': 2009, 'Manager': 'Martin O\'Neill'},
    {'plus': 'Aston Villa', 'StartYear': 2010, 'EndYear': 2011, 'Manager': 'Gerard Houllier / Alex McLeish'},
    {'plus': 'Aston Villa', 'StartYear': 2012, 'EndYear': 2014, 'Manager': 'Paul Lambert'},
    {'plus': 'Aston Villa', 'StartYear': 2015, 'EndYear': 2015, 'Manager': 'Tim Sherwood'},
    {'plus': 'Aston Villa', 'StartYear': 2016, 'EndYear': 2016, 'Manager': 'Roberto Di Matteo'},
    {'plus': 'Aston Villa', 'StartYear': 2017, 'EndYear': 2018, 'Manager': 'Steve Bruce'},
    {'plus': 'Aston Villa', 'StartYear': 2019, 'EndYear': 2021, 'Manager': 'Dean Smith'},
    {'plus': 'Aston Villa', 'StartYear': 2022, 'EndYear': 9999, 'Manager': 'Unai Emery'},

    # Leeds United
    {'plus': 'Leeds', 'StartYear': 1992, 'EndYear': 1995, 'Manager': 'Howard Wilkinson'},
    {'plus': 'Leeds', 'StartYear': 1996, 'EndYear': 1998, 'Manager': 'George Graham'},
    {'plus': 'Leeds', 'StartYear': 1999, 'EndYear': 2001, 'Manager': 'David O\'Leary'},
    {'plus': 'Leeds', 'StartYear': 2002, 'EndYear': 2003, 'Manager': 'Terry Venables'},
    {'plus': 'Leeds', 'StartYear': 2004, 'EndYear': 2004, 'Manager': 'Eddie Gray'},
    {'plus': 'Leeds', 'StartYear': 2010, 'EndYear': 2011, 'Manager': 'Simon Grayson'},
    {'plus': 'Leeds', 'StartYear': 2012, 'EndYear': 2013, 'Manager': 'Neil Warnock'},
    {'plus': 'Leeds', 'StartYear': 2014, 'EndYear': 2015, 'Manager': 'Uwe Rosler'},
    {'plus': 'Leeds', 'StartYear': 2016, 'EndYear': 2017, 'Manager': 'Garry Monk'},
    {'plus': 'Leeds', 'StartYear': 2018, 'EndYear': 2022, 'Manager': 'Marcelo Bielsa'},
    {'plus': 'Leeds', 'StartYear': 2023, 'EndYear': 2023, 'Manager': 'Javi Gracia / Sam Allardyce'},
    {'plus': 'Leeds', 'StartYear': 2024, 'EndYear': 9999, 'Manager': 'Daniel Farke'},

    # West Ham United
    {'plus': 'West Ham', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Billy Bonds'},
    {'plus': 'West Ham', 'StartYear': 1994, 'EndYear': 2000, 'Manager': 'Harry Redknapp'},
    {'plus': 'West Ham', 'StartYear': 2001, 'EndYear': 2002, 'Manager': 'Glenn Roeder'},
    {'plus': 'West Ham', 'StartYear': 2003, 'EndYear': 2003, 'Manager': 'Trevor Brooking (caretaker)'},
    {'plus': 'West Ham', 'StartYear': 2004, 'EndYear': 2005, 'Manager': 'Alan Pardew'},
    {'plus': 'West Ham', 'StartYear': 2006, 'EndYear': 2008, 'Manager': 'Alan Curbishley'},
    {'plus': 'West Ham', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Gianfranco Zola'},
    {'plus': 'West Ham', 'StartYear': 2011, 'EndYear': 2013, 'Manager': 'Sam Allardyce'},
    {'plus': 'West Ham', 'StartYear': 2014, 'EndYear': 2016, 'Manager': 'Slaven Bilic'},
    {'plus': 'West Ham', 'StartYear': 2017, 'EndYear': 2022, 'Manager': 'David Moyes'},
    {'plus': 'West Ham', 'StartYear': 2023, 'EndYear': 2023, 'Manager': 'David Moyes'},
    {'plus': 'West Ham', 'StartYear': 2024, 'EndYear': 9999, 'Manager': 'Julen Lopetegui'},

    # Leicester City
    {'plus': 'Leicester', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Brian Little'},
    {'plus': 'Leicester', 'StartYear': 1994, 'EndYear': 1995, 'Manager': 'Mark McGhee'},
    {'plus': 'Leicester', 'StartYear': 1996, 'EndYear': 2000, 'Manager': 'Martin O\'Neill'},
    {'plus': 'Leicester', 'StartYear': 2001, 'EndYear': 2002, 'Manager': 'Peter Taylor'},
    {'plus': 'Leicester', 'StartYear': 2003, 'EndYear': 2003, 'Manager': 'Micky Adams'},
    {'plus': 'Leicester', 'StartYear': 2004, 'EndYear': 2007, 'Manager': 'Craig Levein / Rob Kelly / Martin Allen'},
    {'plus': 'Leicester', 'StartYear': 2008, 'EndYear': 2009, 'Manager': 'Nigel Pearson'},
    {'plus': 'Leicester', 'StartYear': 2010, 'EndYear': 2011, 'Manager': 'Paulo Sousa / Sven-Goran Eriksson'},
    {'plus': 'Leicester', 'StartYear': 2012, 'EndYear': 2015, 'Manager': 'Nigel Pearson'},
    {'plus': 'Leicester', 'StartYear': 2016, 'EndYear': 2018, 'Manager': 'Claudio Ranieri'},
    {'plus': 'Leicester', 'StartYear': 2019, 'EndYear': 2023, 'Manager': 'Brendan Rodgers'},
    {'plus': 'Leicester', 'StartYear': 2024, 'EndYear': 9999, 'Manager': 'Steve Cooper'},

    # Blackburn Rovers
    {'plus': 'Blackburn', 'StartYear': 1992, 'EndYear': 1995, 'Manager': 'Kenny Dalglish'},
    {'plus': 'Blackburn', 'StartYear': 1996, 'EndYear': 1996, 'Manager': 'Ray Harford'},
    {'plus': 'Blackburn', 'StartYear': 1997, 'EndYear': 1998, 'Manager': 'Roy Hodgson'},
    {'plus': 'Blackburn', 'StartYear': 1999, 'EndYear': 1999, 'Manager': 'Brian Kidd'},
    {'plus': 'Blackburn', 'StartYear': 2000, 'EndYear': 2003, 'Manager': 'Graeme Souness'},
    {'plus': 'Blackburn', 'StartYear': 2004, 'EndYear': 2008, 'Manager': 'Mark Hughes'},
    {'plus': 'Blackburn', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Sam Allardyce'},
    {'plus': 'Blackburn', 'StartYear': 2011, 'EndYear': 2012, 'Manager': 'Steve Kean'},
    {'plus': 'Blackburn', 'StartYear': 2013, 'EndYear': 2014, 'Manager': 'Gary Bowyer'},
    {'plus': 'Blackburn', 'StartYear': 2015, 'EndYear': 2016, 'Manager': 'Paul Lambert'},
    {'plus': 'Blackburn', 'StartYear': 2017, 'EndYear': 2021, 'Manager': 'Tony Mowbray'},
    {'plus': 'Blackburn', 'StartYear': 2022, 'EndYear': 9999, 'Manager': 'Jon Dahl Tomasson'},

    # Sunderland
    {'plus': 'Sunderland', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Malcolm Crosby'},
    {'plus': 'Sunderland', 'StartYear': 1994, 'EndYear': 1995, 'Manager': 'Mick Buxton'},
    {'plus': 'Sunderland', 'StartYear': 1996, 'EndYear': 2001, 'Manager': 'Peter Reid'},
    {'plus': 'Sunderland', 'StartYear': 2002, 'EndYear': 2002, 'Manager': 'Howard Wilkinson'},
    {'plus': 'Sunderland', 'StartYear': 2003, 'EndYear': 2004, 'Manager': 'Mick McCarthy'},
    {'plus': 'Sunderland', 'StartYear': 2005, 'EndYear': 2008, 'Manager': 'Roy Keane'},
    {'plus': 'Sunderland', 'StartYear': 2009, 'EndYear': 2011, 'Manager': 'Steve Bruce'},
    {'plus': 'Sunderland', 'StartYear': 2012, 'EndYear': 2012, 'Manager': 'Martin O\'Neill'},
    {'plus': 'Sunderland', 'StartYear': 2013, 'EndYear': 2014, 'Manager': 'Gus Poyet'},
    {'plus': 'Sunderland', 'StartYear': 2015, 'EndYear': 2015, 'Manager': 'Dick Advocaat'},
    {'plus': 'Sunderland', 'StartYear': 2016, 'EndYear': 2016, 'Manager': 'Sam Allardyce'},
    {'plus': 'Sunderland', 'StartYear': 2017, 'EndYear': 2017, 'Manager': 'David Moyes'},
    {'plus': 'Sunderland', 'StartYear': 2018, 'EndYear': 2019, 'Manager': 'Jack Ross'},
    {'plus': 'Sunderland', 'StartYear': 2020, 'EndYear': 2021, 'Manager': 'Lee Johnson'},
    {'plus': 'Sunderland', 'StartYear': 2022, 'EndYear': 9999, 'Manager': 'Tony Mowbray'},

    # Coventry City
    {'plus': 'Coventry', 'StartYear': 1992, 'EndYear': 1994, 'Manager': 'Bobby Gould'},
    {'plus': 'Coventry', 'StartYear': 1995, 'EndYear': 1996, 'Manager': 'Ron Atkinson'},
    {'plus': 'Coventry', 'StartYear': 1997, 'EndYear': 2000, 'Manager': 'Gordon Strachan'},
    {'plus': 'Coventry', 'StartYear': 2001, 'EndYear': 2001, 'Manager': 'Roland Nilsson'},
    {'plus': 'Coventry', 'StartYear': 2002, 'EndYear': 2003, 'Manager': 'Gary McAllister'},
    {'plus': 'Coventry', 'StartYear': 2004, 'EndYear': 2005, 'Manager': 'Peter Reid'},
    {'plus': 'Coventry', 'StartYear': 2006, 'EndYear': 2007, 'Manager': 'Mick Adams'},
    {'plus': 'Coventry', 'StartYear': 2008, 'EndYear': 2010, 'Manager': 'Chris Coleman'},
    {'plus': 'Coventry', 'StartYear': 2011, 'EndYear': 2012, 'Manager': 'Andy Thorn'},
    {'plus': 'Coventry', 'StartYear': 2013, 'EndYear': 2015, 'Manager': 'Steven Pressley'},
    {'plus': 'Coventry', 'StartYear': 2016, 'EndYear': 2017, 'Manager': 'Tony Mowbray'},
    {'plus': 'Coventry', 'StartYear': 2018, 'EndYear': 9999, 'Manager': 'Mark Robins'},

    # Middlesbrough
    {'plus': 'Middlesbrough', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Lennie Lawrence'},
    {'plus': 'Middlesbrough', 'StartYear': 1994, 'EndYear': 2000, 'Manager': 'Bryan Robson'},
    {'plus': 'Middlesbrough', 'StartYear': 2001, 'EndYear': 2005, 'Manager': 'Steve McClaren'},
    {'plus': 'Middlesbrough', 'StartYear': 2006, 'EndYear': 2008, 'Manager': 'Gareth Southgate'},
    {'plus': 'Middlesbrough', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Gordon Strachan'},
    {'plus': 'Middlesbrough', 'StartYear': 2011, 'EndYear': 2013, 'Manager': 'Tony Mowbray'},
    {'plus': 'Middlesbrough', 'StartYear': 2014, 'EndYear': 2016, 'Manager': 'Aitor Karanka'},
    {'plus': 'Middlesbrough', 'StartYear': 2017, 'EndYear': 2018, 'Manager': 'Garry Monk'},
    {'plus': 'Middlesbrough', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Jonathan Woodgate'},
    {'plus': 'Middlesbrough', 'StartYear': 2021, 'EndYear': 2021, 'Manager': 'Neil Warnock'},
    {'plus': 'Middlesbrough', 'StartYear': 2022, 'EndYear': 9999, 'Manager': 'Chris Wilder'},

    # Southampton
    {'plus': 'Southampton', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Ian Branfoot'},
    {'plus': 'Southampton', 'StartYear': 1994, 'EndYear': 1995, 'Manager': 'Alan Ball'},
    {'plus': 'Southampton', 'StartYear': 1996, 'EndYear': 1997, 'Manager': 'Dave Merrington'},
    {'plus': 'Southampton', 'StartYear': 1998, 'EndYear': 2001, 'Manager': 'Graeme Souness'},
    {'plus': 'Southampton', 'StartYear': 2002, 'EndYear': 2003, 'Manager': 'Gordon Strachan'},
    {'plus': 'Southampton', 'StartYear': 2004, 'EndYear': 2004, 'Manager': 'Paul Sturrock'},
    {'plus': 'Southampton', 'StartYear': 2005, 'EndYear': 2006, 'Manager': 'Harry Redknapp'},
    {'plus': 'Southampton', 'StartYear': 2007, 'EndYear': 2008, 'Manager': 'George Burley'},
    {'plus': 'Southampton', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Alan Pardew'},
    {'plus': 'Southampton', 'StartYear': 2011, 'EndYear': 2013, 'Manager': 'Nigel Adkins'},
    {'plus': 'Southampton', 'StartYear': 2014, 'EndYear': 2016, 'Manager': 'Ronald Koeman'},
    {'plus': 'Southampton', 'StartYear': 2017, 'EndYear': 2018, 'Manager': 'Mauricio Pellegrino'},
    {'plus': 'Southampton', 'StartYear': 2019, 'EndYear': 2021, 'Manager': 'Ralph Hasenhuttl'},
    {'plus': 'Southampton', 'StartYear': 2022, 'EndYear': 2022, 'Manager': 'Nathan Jones'},
    {'plus': 'Southampton', 'StartYear': 2023, 'EndYear': 9999, 'Manager': 'Russell Martin'},

    # Bolton Wanderers
    {'plus': 'Bolton', 'StartYear': 1992, 'EndYear': 1995, 'Manager': 'Bruce Rioch'},
    {'plus': 'Bolton', 'StartYear': 1996, 'EndYear': 2006, 'Manager': 'Sam Allardyce'},
    {'plus': 'Bolton', 'StartYear': 2007, 'EndYear': 2009, 'Manager': 'Gary Megson'},
    {'plus': 'Bolton', 'StartYear': 2010, 'EndYear': 2012, 'Manager': 'Owen Coyle'},
    {'plus': 'Bolton', 'StartYear': 2013, 'EndYear': 2013, 'Manager': 'Dougie Freedman'},
    {'plus': 'Bolton', 'StartYear': 2014, 'EndYear': 2015, 'Manager': 'Neil Lennon'},
    {'plus': 'Bolton', 'StartYear': 2016, 'EndYear': 2018, 'Manager': 'Phil Parkinson'},
    {'plus': 'Bolton', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Keith Hill'},
    {'plus': 'Bolton', 'StartYear': 2021, 'EndYear': 9999, 'Manager': 'Ian Evatt'},

    # Fulham
    {'plus': 'Fulham', 'StartYear': 1992, 'EndYear': 1996, 'Manager': 'Ray Wilkins / Micky Adams'},
    {'plus': 'Fulham', 'StartYear': 1997, 'EndYear': 1998, 'Manager': 'Kevin Keegan'},
    {'plus': 'Fulham', 'StartYear': 1999, 'EndYear': 2000, 'Manager': 'Paul Bracewell'},
    {'plus': 'Fulham', 'StartYear': 2001, 'EndYear': 2003, 'Manager': 'Jean Tigana'},
    {'plus': 'Fulham', 'StartYear': 2004, 'EndYear': 2006, 'Manager': 'Chris Coleman'},
    {'plus': 'Fulham', 'StartYear': 2007, 'EndYear': 2008, 'Manager': 'Lawrie Sanchez'},
    {'plus': 'Fulham', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Roy Hodgson'},
    {'plus': 'Fulham', 'StartYear': 2011, 'EndYear': 2013, 'Manager': 'Martin Jol'},
    {'plus': 'Fulham', 'StartYear': 2014, 'EndYear': 2014, 'Manager': 'Felix Magath'},
    {'plus': 'Fulham', 'StartYear': 2015, 'EndYear': 2018, 'Manager': 'Slavisa Jokanovic'},
    {'plus': 'Fulham', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Scott Parker'},
    {'plus': 'Fulham', 'StartYear': 2021, 'EndYear': 9999, 'Manager': 'Marco Silva'},

    # West Bromwich Albion
    {'plus': 'West Brom', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'John Williams'},
    {'plus': 'West Brom', 'StartYear': 1994, 'EndYear': 1995, 'Manager': 'Kevin Cullis'},
    {'plus': 'West Brom', 'StartYear': 1996, 'EndYear': 1999, 'Manager': 'Ray Harford'},
    {'plus': 'West Brom', 'StartYear': 2000, 'EndYear': 2004, 'Manager': 'Gary Megson'},
    {'plus': 'West Brom', 'StartYear': 2005, 'EndYear': 2006, 'Manager': 'Bryan Robson'},
    {'plus': 'West Brom', 'StartYear': 2007, 'EndYear': 2008, 'Manager': 'Tony Mowbray'},
    {'plus': 'West Brom', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Roberto Di Matteo'},
    {'plus': 'West Brom', 'StartYear': 2011, 'EndYear': 2013, 'Manager': 'Roy Hodgson'},
    {'plus': 'West Brom', 'StartYear': 2014, 'EndYear': 2014, 'Manager': 'Alan Irvine'},
    {'plus': 'West Brom', 'StartYear': 2015, 'EndYear': 2017, 'Manager': 'Tony Pulis'},
    {'plus': 'West Brom', 'StartYear': 2018, 'EndYear': 2019, 'Manager': 'Darren Moore'},
    {'plus': 'West Brom', 'StartYear': 2020, 'EndYear': 2021, 'Manager': 'Slaven Bilic'},
    {'plus': 'West Brom', 'StartYear': 2022, 'EndYear': 9999, 'Manager': 'Carlos Corberan'},

    # Charlton Athletic
    {'plus': 'Charlton', 'StartYear': 1992, 'EndYear': 1994, 'Manager': 'Lennie Lawrence'},
    {'plus': 'Charlton', 'StartYear': 1995, 'EndYear': 2006, 'Manager': 'Alan Curbishley'},
    {'plus': 'Charlton', 'StartYear': 2007, 'EndYear': 2008, 'Manager': 'Iain Dowie'},
    {'plus': 'Charlton', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Phil Parkinson'},
    {'plus': 'Charlton', 'StartYear': 2011, 'EndYear': 2012, 'Manager': 'Chris Powell'},
    {'plus': 'Charlton', 'StartYear': 2013, 'EndYear': 2014, 'Manager': 'Jose Riga'},
    {'plus': 'Charlton', 'StartYear': 2015, 'EndYear': 2016, 'Manager': 'Guy Luzon'},
    {'plus': 'Charlton', 'StartYear': 2017, 'EndYear': 2018, 'Manager': 'Karl Robinson'},
    {'plus': 'Charlton', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Lee Bowyer'},
    {'plus': 'Charlton', 'StartYear': 2021, 'EndYear': 9999, 'Manager': 'Nigel Adkins'},

    # Derby County
    {'plus': 'Derby', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Arthur Cox'},
    {'plus': 'Derby', 'StartYear': 1994, 'EndYear': 1995, 'Manager': 'Roy McFarland'},
    {'plus': 'Derby', 'StartYear': 1996, 'EndYear': 2000, 'Manager': 'Jim Smith'},
    {'plus': 'Derby', 'StartYear': 2001, 'EndYear': 2001, 'Manager': 'Colin Todd'},
    {'plus': 'Derby', 'StartYear': 2002, 'EndYear': 2003, 'Manager': 'John Gregory'},
    {'plus': 'Derby', 'StartYear': 2004, 'EndYear': 2005, 'Manager': 'George Burley'},
    {'plus': 'Derby', 'StartYear': 2006, 'EndYear': 2007, 'Manager': 'Phil Brown'},
    {'plus': 'Derby', 'StartYear': 2008, 'EndYear': 2013, 'Manager': 'Nigel Clough'},
    {'plus': 'Derby', 'StartYear': 2014, 'EndYear': 2016, 'Manager': 'Steve McClaren'},
    {'plus': 'Derby', 'StartYear': 2017, 'EndYear': 2018, 'Manager': 'Gary Rowett'},
    {'plus': 'Derby', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Frank Lampard'},
    {'plus': 'Derby', 'StartYear': 2021, 'EndYear': 2022, 'Manager': 'Wayne Rooney'},
    {'plus': 'Derby', 'StartYear': 2023, 'EndYear': 9999, 'Manager': 'Paul Warne'},

    # Ipswich Town
    {'plus': 'Ipswich', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'John Lyall'},
    {'plus': 'Ipswich', 'StartYear': 1994, 'EndYear': 2002, 'Manager': 'George Burley'},
    {'plus': 'Ipswich', 'StartYear': 2003, 'EndYear': 2005, 'Manager': 'Joe Royle'},
    {'plus': 'Ipswich', 'StartYear': 2006, 'EndYear': 2008, 'Manager': 'Jim Magilton'},
    {'plus': 'Ipswich', 'StartYear': 2009, 'EndYear': 2011, 'Manager': 'Roy Keane'},
    {'plus': 'Ipswich', 'StartYear': 2012, 'EndYear': 2013, 'Manager': 'Paul Jewell'},
    {'plus': 'Ipswich', 'StartYear': 2014, 'EndYear': 2017, 'Manager': 'Mick McCarthy'},
    {'plus': 'Ipswich', 'StartYear': 2018, 'EndYear': 2019, 'Manager': 'Paul Hurst'},
    {'plus': 'Ipswich', 'StartYear': 2020, 'EndYear': 2021, 'Manager': 'Paul Lambert'},
    {'plus': 'Ipswich', 'StartYear': 2022, 'EndYear': 9999, 'Manager': 'Kieran McKenna'},

    # Bradford City
    {'plus': 'Bradford', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Frank Stapleton'},
    {'plus': 'Bradford', 'StartYear': 1994, 'EndYear': 1996, 'Manager': 'Lennie Lawrence'},
    {'plus': 'Bradford', 'StartYear': 1997, 'EndYear': 1998, 'Manager': 'Chris Kamara'},
    {'plus': 'Bradford', 'StartYear': 1999, 'EndYear': 2000, 'Manager': 'Paul Jewell'},
    {'plus': 'Bradford', 'StartYear': 2001, 'EndYear': 2001, 'Manager': 'Jim Jefferies'},
    {'plus': 'Bradford', 'StartYear': 2002, 'EndYear': 2003, 'Manager': 'Nicky Law'},
    {'plus': 'Bradford', 'StartYear': 2004, 'EndYear': 2005, 'Manager': 'Colin Todd'},
    {'plus': 'Bradford', 'StartYear': 2006, 'EndYear': 2007, 'Manager': 'Peter Taylor'},
    {'plus': 'Bradford', 'StartYear': 2008, 'EndYear': 2009, 'Manager': 'Stuart McCall'},
    {'plus': 'Bradford', 'StartYear': 2010, 'EndYear': 2011, 'Manager': 'Peter Taylor'},
    {'plus': 'Bradford', 'StartYear': 2012, 'EndYear': 2013, 'Manager': 'Phil Parkinson'},
    {'plus': 'Bradford', 'StartYear': 2014, 'EndYear': 2015, 'Manager': 'Phil Parkinson'},
    {'plus': 'Bradford', 'StartYear': 2016, 'EndYear': 2017, 'Manager': 'Stuart McCall'},
    {'plus': 'Bradford', 'StartYear': 2018, 'EndYear': 2019, 'Manager': 'David Hopkin'},
    {'plus': 'Bradford', 'StartYear': 2020, 'EndYear': 2021, 'Manager': 'Mark Trueman'},
    {'plus': 'Bradford', 'StartYear': 2022, 'EndYear': 9999, 'Manager': 'Mark Hughes'},

    # Sheffield Wednesday
    {'plus': 'Sheffield', 'StartYear': 1992, 'EndYear': 1995, 'Manager': 'Trevor Francis'},
    {'plus': 'Sheffield', 'StartYear': 1996, 'EndYear': 1998, 'Manager': 'David Pleat'},
    {'plus': 'Sheffield', 'StartYear': 1999, 'EndYear': 2000, 'Manager': 'Danny Wilson'},
    {'plus': 'Sheffield', 'StartYear': 2001, 'EndYear': 2002, 'Manager': 'Peter Shreeves'},
    {'plus': 'Sheffield', 'StartYear': 2003, 'EndYear': 2004, 'Manager': 'Chris Turner'},
    {'plus': 'Sheffield', 'StartYear': 2005, 'EndYear': 2006, 'Manager': 'Paul Sturrock'},
    {'plus': 'Sheffield', 'StartYear': 2007, 'EndYear': 2008, 'Manager': 'Brian Laws'},
    {'plus': 'Sheffield', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Alan Irvine'},
    {'plus': 'Sheffield', 'StartYear': 2011, 'EndYear': 2012, 'Manager': 'Gary Megson'},
    {'plus': 'Sheffield', 'StartYear': 2013, 'EndYear': 2015, 'Manager': 'Dave Jones'},
    {'plus': 'Sheffield', 'StartYear': 2016, 'EndYear': 2018, 'Manager': 'Carlos Carvalhal'},
    {'plus': 'Sheffield', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Garry Monk'},
    {'plus': 'Sheffield', 'StartYear': 2021, 'EndYear': 2021, 'Manager': 'Darren Moore'},
    {'plus': 'Sheffield', 'StartYear': 2022, 'EndYear': 9999, 'Manager': 'Darren Moore'},

    # Birmingham City
    {'plus': 'Birmingham', 'StartYear': 2002, 'EndYear': 2004, 'Manager': 'Steve Bruce'},
    {'plus': 'Birmingham', 'StartYear': 2005, 'EndYear': 2006, 'Manager': 'Steve Bruce'},
    {'plus': 'Birmingham', 'StartYear': 2007, 'EndYear': 2007, 'Manager': 'Alex McLeish'},
    {'plus': 'Birmingham', 'StartYear': 2008, 'EndYear': 2010, 'Manager': 'Alex McLeish'},
    {'plus': 'Birmingham', 'StartYear': 2011, 'EndYear': 2011, 'Manager': 'Chris Hughton'},
    {'plus': 'Birmingham', 'StartYear': 2012, 'EndYear': 2013, 'Manager': 'Lee Clark'},
    {'plus': 'Birmingham', 'StartYear': 2014, 'EndYear': 2015, 'Manager': 'Gary Rowett'},
    {'plus': 'Birmingham', 'StartYear': 2016, 'EndYear': 2017, 'Manager': 'Gianfranco Zola'},
    {'plus': 'Birmingham', 'StartYear': 2018, 'EndYear': 2019, 'Manager': 'Garry Monk'},
    {'plus': 'Birmingham', 'StartYear': 2020, 'EndYear': 2021, 'Manager': 'Aitor Karanka'},
    {'plus': 'Birmingham', 'StartYear': 2022, 'EndYear': 9999, 'Manager': 'John Eustace'},

    # Portsmouth
    {'plus': 'Portsmouth', 'StartYear': 1992, 'EndYear': 1995, 'Manager': 'Jim Smith'},
    {'plus': 'Portsmouth', 'StartYear': 1996, 'EndYear': 1998, 'Manager': 'Terry Fenwick'},
    {'plus': 'Portsmouth', 'StartYear': 1999, 'EndYear': 2000, 'Manager': 'Tony Pulis'},
    {'plus': 'Portsmouth', 'StartYear': 2001, 'EndYear': 2001, 'Manager': 'Graham Rix'},
    {'plus': 'Portsmouth', 'StartYear': 2002, 'EndYear': 2004, 'Manager': 'Harry Redknapp'},
    {'plus': 'Portsmouth', 'StartYear': 2005, 'EndYear': 2005, 'Manager': 'Velimir Zajec'},
    {'plus': 'Portsmouth', 'StartYear': 2006, 'EndYear': 2006, 'Manager': 'Harry Redknapp'},
    {'plus': 'Portsmouth', 'StartYear': 2007, 'EndYear': 2008, 'Manager': 'Harry Redknapp'},
    {'plus': 'Portsmouth', 'StartYear': 2009, 'EndYear': 2009, 'Manager': 'Paul Hart'},
    {'plus': 'Portsmouth', 'StartYear': 2010, 'EndYear': 2010, 'Manager': 'Avram Grant'},
    {'plus': 'Portsmouth', 'StartYear': 2011, 'EndYear': 2012, 'Manager': 'Steve Cotterill'},
    {'plus': 'Portsmouth', 'StartYear': 2013, 'EndYear': 2014, 'Manager': 'Richie Barker'},
    # Portsmouth out of PL after 2010

    # Wolverhampton Wanderers
    {'plus': 'Wolves', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Graham Turner'},
    {'plus': 'Wolves', 'StartYear': 1994, 'EndYear': 1995, 'Manager': 'Graham Taylor'},
    {'plus': 'Wolves', 'StartYear': 1996, 'EndYear': 1997, 'Manager': 'Mark McGhee'},
    {'plus': 'Wolves', 'StartYear': 1998, 'EndYear': 2000, 'Manager': 'Colin Lee'},
    {'plus': 'Wolves', 'StartYear': 2001, 'EndYear': 2001, 'Manager': 'Dave Jones'},
    {'plus': 'Wolves', 'StartYear': 2002, 'EndYear': 2003, 'Manager': 'Dave Jones'},
    {'plus': 'Wolves', 'StartYear': 2004, 'EndYear': 2005, 'Manager': 'Glenn Hoddle'},
    {'plus': 'Wolves', 'StartYear': 2006, 'EndYear': 2007, 'Manager': 'Mick McCarthy'},
    {'plus': 'Wolves', 'StartYear': 2008, 'EndYear': 2011, 'Manager': 'Mick McCarthy'},
    {'plus': 'Wolves', 'StartYear': 2012, 'EndYear': 2012, 'Manager': 'Terry Connor'},
    {'plus': 'Wolves', 'StartYear': 2013, 'EndYear': 2015, 'Manager': 'Kenny Jackett'},
    {'plus': 'Wolves', 'StartYear': 2016, 'EndYear': 2017, 'Manager': 'Paul Lambert'},
    {'plus': 'Wolves', 'StartYear': 2018, 'EndYear': 2020, 'Manager': 'Nuno Espirito Santo'},
    {'plus': 'Wolves', 'StartYear': 2021, 'EndYear': 2021, 'Manager': 'Bruno Lage'},
    {'plus': 'Wolves', 'StartYear': 2022, 'EndYear': 2022, 'Manager': 'Julen Lopetegui'},
    {'plus': 'Wolves', 'StartYear': 2023, 'EndYear': 9999, 'Manager': 'Gary O\'Neil'},

    # Norwich City
    {'plus': 'Norwich', 'StartYear': 1992, 'EndYear': 1994, 'Manager': 'Mike Walker'},
    {'plus': 'Norwich', 'StartYear': 1995, 'EndYear': 1996, 'Manager': 'John Deehan'},
    {'plus': 'Norwich', 'StartYear': 1997, 'EndYear': 1998, 'Manager': 'Mike Walker'},
    {'plus': 'Norwich', 'StartYear': 1999, 'EndYear': 2000, 'Manager': 'Bruce Rioch'},
    {'plus': 'Norwich', 'StartYear': 2001, 'EndYear': 2002, 'Manager': 'Nigel Worthington'},
    {'plus': 'Norwich', 'StartYear': 2003, 'EndYear': 2006, 'Manager': 'Nigel Worthington'},
    {'plus': 'Norwich', 'StartYear': 2007, 'EndYear': 2007, 'Manager': 'Peter Grant'},
    {'plus': 'Norwich', 'StartYear': 2008, 'EndYear': 2009, 'Manager': 'Glenn Roeder'},
    {'plus': 'Norwich', 'StartYear': 2010, 'EndYear': 2011, 'Manager': 'Paul Lambert'},
    {'plus': 'Norwich', 'StartYear': 2012, 'EndYear': 2013, 'Manager': 'Chris Hughton'},
    {'plus': 'Norwich', 'StartYear': 2014, 'EndYear': 2014, 'Manager': 'Neil Adams'},
    {'plus': 'Norwich', 'StartYear': 2015, 'EndYear': 2017, 'Manager': 'Alex Neil'},
    {'plus': 'Norwich', 'StartYear': 2018, 'EndYear': 2021, 'Manager': 'Daniel Farke'},
    {'plus': 'Norwich', 'StartYear': 2022, 'EndYear': 2022, 'Manager': 'Dean Smith'},
    {'plus': 'Norwich', 'StartYear': 2023, 'EndYear': 9999, 'Manager': 'David Wagner'},

    # Crystal Palace
    {'plus': 'Crystal Palace', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Steve Coppell'},
    {'plus': 'Crystal Palace', 'StartYear': 1994, 'EndYear': 1995, 'Manager': 'Alan Smith'},
    {'plus': 'Crystal Palace', 'StartYear': 1996, 'EndYear': 1997, 'Manager': 'Dave Bassett'},
    {'plus': 'Crystal Palace', 'StartYear': 1998, 'EndYear': 1998, 'Manager': 'Terry Venables'},
    {'plus': 'Crystal Palace', 'StartYear': 1999, 'EndYear': 2000, 'Manager': 'Steve Coppell'},
    {'plus': 'Crystal Palace', 'StartYear': 2001, 'EndYear': 2003, 'Manager': 'Trevor Francis'},
    {'plus': 'Crystal Palace', 'StartYear': 2004, 'EndYear': 2006, 'Manager': 'Iain Dowie'},
    {'plus': 'Crystal Palace', 'StartYear': 2007, 'EndYear': 2008, 'Manager': 'Peter Taylor'},
    {'plus': 'Crystal Palace', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Neil Warnock'},
    {'plus': 'Crystal Palace', 'StartYear': 2011, 'EndYear': 2012, 'Manager': 'Dougie Freedman'},
    {'plus': 'Crystal Palace', 'StartYear': 2013, 'EndYear': 2014, 'Manager': 'Ian Holloway'},
    {'plus': 'Crystal Palace', 'StartYear': 2015, 'EndYear': 2019, 'Manager': 'Alan Pardew'},
    {'plus': 'Crystal Palace', 'StartYear': 2020, 'EndYear': 2023, 'Manager': 'Roy Hodgson'},
    {'plus': 'Crystal Palace', 'StartYear': 2024, 'EndYear': 9999, 'Manager': 'Oliver Glasner'},

    # Wigan Athletic
    {'plus': 'Wigan', 'StartYear': 2005, 'EndYear': 2006, 'Manager': 'Paul Jewell'},
    {'plus': 'Wigan', 'StartYear': 2007, 'EndYear': 2008, 'Manager': 'Chris Hutchings'},
    {'plus': 'Wigan', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Roberto Martinez'},
    {'plus': 'Wigan', 'StartYear': 2011, 'EndYear': 2012, 'Manager': 'Roberto Martinez'},
    {'plus': 'Wigan', 'StartYear': 2013, 'EndYear': 2013, 'Manager': 'Owen Coyle'},
    # Wigan relegated after 2013

    # Reading
    {'plus': 'Reading', 'StartYear': 2006, 'EndYear': 2008, 'Manager': 'Steve Coppell'},
    {'plus': 'Reading', 'StartYear': 2009, 'EndYear': 2009, 'Manager': 'Brendan Rodgers'},
    {'plus': 'Reading', 'StartYear': 2010, 'EndYear': 2012, 'Manager': 'Brian McDermott'},
    {'plus': 'Reading', 'StartYear': 2013, 'EndYear': 2013, 'Manager': 'Nigel Adkins'},
    {'plus': 'Reading', 'StartYear': 2014, 'EndYear': 2015, 'Manager': 'Steve Clarke'},
    {'plus': 'Reading', 'StartYear': 2016, 'EndYear': 2017, 'Manager': 'Jaap Stam'},
    {'plus': 'Reading', 'StartYear': 2018, 'EndYear': 2019, 'Manager': 'Paul Clement'},
    {'plus': 'Reading', 'StartYear': 2020, 'EndYear': 2021, 'Manager': 'Veljko Paunovic'},
    {'plus': 'Reading', 'StartYear': 2022, 'EndYear': 9999, 'Manager': 'Paul Ince'},

    # Watford
    {'plus': 'Watford', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Glenn Roeder'},
    {'plus': 'Watford', 'StartYear': 1994, 'EndYear': 1995, 'Manager': 'Graham Taylor'},
    {'plus': 'Watford', 'StartYear': 1996, 'EndYear': 1997, 'Manager': 'Kenny Jackett'},
    {'plus': 'Watford', 'StartYear': 1998, 'EndYear': 2000, 'Manager': 'Graham Taylor'},
    {'plus': 'Watford', 'StartYear': 2001, 'EndYear': 2002, 'Manager': 'Gianluca Vialli'},
    {'plus': 'Watford', 'StartYear': 2003, 'EndYear': 2004, 'Manager': 'Ray Lewington'},
    {'plus': 'Watford', 'StartYear': 2005, 'EndYear': 2007, 'Manager': 'Aidy Boothroyd'},
    {'plus': 'Watford', 'StartYear': 2008, 'EndYear': 2009, 'Manager': 'Malky Mackay'},
    {'plus': 'Watford', 'StartYear': 2010, 'EndYear': 2011, 'Manager': 'Malky Mackay'},
    {'plus': 'Watford', 'StartYear': 2012, 'EndYear': 2013, 'Manager': 'Gianfranco Zola'},
    {'plus': 'Watford', 'StartYear': 2014, 'EndYear': 2015, 'Manager': 'Slavisa Jokanovic'},
    {'plus': 'Watford', 'StartYear': 2016, 'EndYear': 2017, 'Manager': 'Quique Flores'},
    {'plus': 'Watford', 'StartYear': 2018, 'EndYear': 2019, 'Manager': 'Javi Gracia'},
    {'plus': 'Watford', 'StartYear': 2020, 'EndYear': 2021, 'Manager': 'Nigel Pearson'},
    {'plus': 'Watford', 'StartYear': 2022, 'EndYear': 2022, 'Manager': 'Roy Hodgson'},
    {'plus': 'Watford', 'StartYear': 2023, 'EndYear': 9999, 'Manager': 'Valerien Ismael'},

    # Hull City
    {'plus': 'Hull', 'StartYear': 2008, 'EndYear': 2009, 'Manager': 'Phil Brown'},
    {'plus': 'Hull', 'StartYear': 2010, 'EndYear': 2011, 'Manager': 'Nigel Pearson'},
    {'plus': 'Hull', 'StartYear': 2012, 'EndYear': 2013, 'Manager': 'Steve Bruce'},
    {'plus': 'Hull', 'StartYear': 2014, 'EndYear': 2014, 'Manager': 'Steve Bruce'},
    {'plus': 'Hull', 'StartYear': 2015, 'EndYear': 2015, 'Manager': 'Mike Phelan'},
    {'plus': 'Hull', 'StartYear': 2016, 'EndYear': 2016, 'Manager': 'Mike Phelan'},
    {'plus': 'Hull', 'StartYear': 2017, 'EndYear': 2017, 'Manager': 'Marco Silva'},
    # Hull relegated after 2017

    # Stoke City
    {'plus': 'Stoke', 'StartYear': 2008, 'EndYear': 2012, 'Manager': 'Tony Pulis'},
    {'plus': 'Stoke', 'StartYear': 2013, 'EndYear': 2017, 'Manager': 'Mark Hughes'},
    {'plus': 'Stoke', 'StartYear': 2018, 'EndYear': 2018, 'Manager': 'Paul Lambert'},
    {'plus': 'Stoke', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Nathan Jones'},
    {'plus': 'Stoke', 'StartYear': 2021, 'EndYear': 2022, 'Manager': 'Michael O\'Neill'},
    {'plus': 'Stoke', 'StartYear': 2023, 'EndYear': 9999, 'Manager': 'Alex Neil'},

    # Burnley
    {'plus': 'Burnley', 'StartYear': 2009, 'EndYear': 2009, 'Manager': 'Owen Coyle'},
    {'plus': 'Burnley', 'StartYear': 2010, 'EndYear': 2011, 'Manager': 'Brian Laws'},
    {'plus': 'Burnley', 'StartYear': 2012, 'EndYear': 2013, 'Manager': 'Eddie Howe'},
    {'plus': 'Burnley', 'StartYear': 2014, 'EndYear': 2015, 'Manager': 'Sean Dyche'},
    {'plus': 'Burnley', 'StartYear': 2016, 'EndYear': 2022, 'Manager': 'Sean Dyche'},
    {'plus': 'Burnley', 'StartYear': 2023, 'EndYear': 9999, 'Manager': 'Vincent Kompany'},

    # Blackpool
    {'plus': 'Blackpool', 'StartYear': 2010, 'EndYear': 2011, 'Manager': 'Ian Holloway'},
    {'plus': 'Blackpool', 'StartYear': 2012, 'EndYear': 2012, 'Manager': 'Michael Appleton'},
    # Blackpool relegated after 2012

    # QPR
    {'plus': 'QPR', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Gerry Francis'},
    {'plus': 'QPR', 'StartYear': 1994, 'EndYear': 1995, 'Manager': 'Ray Wilkins'},
    {'plus': 'QPR', 'StartYear': 1996, 'EndYear': 1996, 'Manager': 'Bruce Rioch'},
    {'plus': 'QPR', 'StartYear': 1997, 'EndYear': 1997, 'Manager': 'Ray Harford'},
    {'plus': 'QPR', 'StartYear': 1998, 'EndYear': 1999, 'Manager': 'Iain Dowie'},
    {'plus': 'QPR', 'StartYear': 2000, 'EndYear': 2001, 'Manager': 'Ian Holloway'},
    {'plus': 'QPR', 'StartYear': 2002, 'EndYear': 2003, 'Manager': 'Kevin Gallen'},
    {'plus': 'QPR', 'StartYear': 2004, 'EndYear': 2006, 'Manager': 'Ian Holloway'},
    {'plus': 'QPR', 'StartYear': 2007, 'EndYear': 2008, 'Manager': 'John Gregory'},
    {'plus': 'QPR', 'StartYear': 2009, 'EndYear': 2010, 'Manager': 'Jim Magilton'},
    {'plus': 'QPR', 'StartYear': 2011, 'EndYear': 2012, 'Manager': 'Mark Hughes'},
    {'plus': 'QPR', 'StartYear': 2013, 'EndYear': 2013, 'Manager': 'Harry Redknapp'},
    {'plus': 'QPR', 'StartYear': 2014, 'EndYear': 2014, 'Manager': 'Harry Redknapp'},
    {'plus': 'QPR', 'StartYear': 2015, 'EndYear': 2016, 'Manager': 'Chris Ramsey'},
    {'plus': 'QPR', 'StartYear': 2017, 'EndYear': 2018, 'Manager': 'Ian Holloway'},
    {'plus': 'QPR', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Mark Warburton'},
    {'plus': 'QPR', 'StartYear': 2021, 'EndYear': 9999, 'Manager': 'Mark Warburton'},

    # Swansea City
    {'plus': 'Swansea', 'StartYear': 2011, 'EndYear': 2014, 'Manager': 'Brendan Rodgers'},
    {'plus': 'Swansea', 'StartYear': 2015, 'EndYear': 2016, 'Manager': 'Garry Monk'},
    {'plus': 'Swansea', 'StartYear': 2017, 'EndYear': 2017, 'Manager': 'Paul Clement'},
    {'plus': 'Swansea', 'StartYear': 2018, 'EndYear': 2018, 'Manager': 'Carlos Carvalhal'},
    {'plus': 'Swansea', 'StartYear': 2019, 'EndYear': 2020, 'Manager': 'Graham Potter'},
    {'plus': 'Swansea', 'StartYear': 2021, 'EndYear': 2022, 'Manager': 'Steve Cooper'},
    {'plus': 'Swansea', 'StartYear': 2023, 'EndYear': 9999, 'Manager': 'Michael Duff'},

    # Cardiff City
    {'plus': 'Cardiff', 'StartYear': 2013, 'EndYear': 2013, 'Manager': 'Malky Mackay'},
    {'plus': 'Cardiff', 'StartYear': 2014, 'EndYear': 2014, 'Manager': 'Ole Gunnar Solskjaer'},
    {'plus': 'Cardiff', 'StartYear': 2015, 'EndYear': 2016, 'Manager': 'Russell Slade'},
    {'plus': 'Cardiff', 'StartYear': 2017, 'EndYear': 2018, 'Manager': 'Neil Warnock'},
    {'plus': 'Cardiff', 'StartYear': 2019, 'EndYear': 2019, 'Manager': 'Neil Warnock'},
    # Cardiff back to Championship after 2019

    # Bournemouth
    {'plus': 'Bournemouth', 'StartYear': 2015, 'EndYear': 2020, 'Manager': 'Eddie Howe'},
    {'plus': 'Bournemouth', 'StartYear': 2021, 'EndYear': 2022, 'Manager': 'Jason Tindall'},
    {'plus': 'Bournemouth', 'StartYear': 2023, 'EndYear': 9999, 'Manager': 'Andoni Iraola'},

    # Brighton
    {'plus': 'Brighton', 'StartYear': 2017, 'EndYear': 2018, 'Manager': 'Chris Hughton'},
    {'plus': 'Brighton', 'StartYear': 2019, 'EndYear': 2021, 'Manager': 'Graham Potter'},
    {'plus': 'Brighton', 'StartYear': 2022, 'EndYear': 9999, 'Manager': 'Roberto De Zerbi'},

    # Huddersfield
    {'plus': 'Huddersfield', 'StartYear': 2017, 'EndYear': 2018, 'Manager': 'David Wagner'},
    {'plus': 'Huddersfield', 'StartYear': 2019, 'EndYear': 2019, 'Manager': 'Jan Siewert'},
    {'plus': 'Huddersfield', 'StartYear': 2020, 'EndYear': 2021, 'Manager': 'Danny Cowley'},
    # Huddersfield relegated after 2019

    # Brentford
    {'plus': 'Brentford', 'StartYear': 2021, 'EndYear': 9999, 'Manager': 'Thomas Frank'},

    # Nottingham Forest
    {'plus': 'Nottingham', 'StartYear': 1992, 'EndYear': 1993, 'Manager': 'Brian Clough'},
    {'plus': 'Nottingham', 'StartYear': 1994, 'EndYear': 1995, 'Manager': 'Dave Bassett'},
    {'plus': 'Nottingham', 'StartYear': 1996, 'EndYear': 1997, 'Manager': 'Stuart Pearce'},
    {'plus': 'Nottingham', 'StartYear': 1998, 'EndYear': 1998, 'Manager': 'Ron Atkinson'},
    {'plus': 'Nottingham', 'StartYear': 1999, 'EndYear': 1999, 'Manager': 'David Platt'},
    # Forest relegated after 1999
    {'plus': 'Nottingham', 'StartYear': 2022, 'EndYear': 2023, 'Manager': 'Steve Cooper'},
    {'plus': 'Nottingham', 'StartYear': 2024, 'EndYear': 9999, 'Manager': 'Nuno Espirito Santo'},

    # Luton Town
    {'plus': 'Luton', 'StartYear': 2023, 'EndYear': 2024, 'Manager': 'Rob Edwards'},
    # Luton promoted for 2023-24

    # Wimbledon (no longer in PL, but include for completeness)
    {'plus': 'Wimbledon', 'StartYear': 1992, 'EndYear': 1999, 'Manager': 'Joe Kinnear / various'},
    # They were relegated in 2000 and later moved.
]

# Convert to DataFrame
manager_df = pd.DataFrame(manager_history)

# Function to get manager
def get_manager(team, year):
    if pd.isna(team) or pd.isna(year):
        return pd.NA
    try:
        year = int(year)
    except:
        return pd.NA
    result = manager_df[
        (manager_df['plus'] == team) &
        (manager_df['StartYear'] <= year) &
        (manager_df['EndYear'] >= year)
    ]
    if result.empty:
        return pd.NA
    return result.iloc[0]['Manager']

# Apply to dataframe
df['HomeManager'] = df.apply(lambda row: get_manager(row['HomeTeam'], row['Year']), axis=1)
df['AwayManager'] = df.apply(lambda row: get_manager(row['AwayTeam'], row['Year']), axis=1)

In [201]:
unknown_home_manager_teams = sorted(
    df.loc[df['HomeManager'].isna(), 'HomeTeam'].dropna().unique()
)
unknown_away_manager_teams = sorted(
    df.loc[df['AwayManager'].isna(), 'AwayTeam'].dropna().unique()
)

print('Unknown home manager teams:', unknown_home_manager_teams)
print('Unknown away manager teams:', unknown_away_manager_teams)

Unknown home manager teams: []
Unknown away manager teams: []

In [202]:
df.to_csv("Data/matches.csv", index=False)

---

In [203]:
df['HomeTeam'].unique()

array(['Charlton', 'Leeds', 'Derby', 'Chelsea', 'Tottenham', 'Leicester',
       'Sunderland', 'Coventry', 'Liverpool', 'Man United', 'Arsenal',
       'Middlesbrough', 'Bradford', 'Ipswich', 'Southampton', 'Man City',
       'Everton', 'Newcastle', 'West Ham', 'Aston Villa', 'Bolton',
       'Blackburn', 'Fulham', 'West Brom', 'Birmingham', 'Portsmouth',
       'Wolves', 'Norwich', 'Crystal Palace', 'Wigan', 'Sheffield',
       'Reading', 'Watford', 'Hull', 'Stoke', 'Burnley', 'Blackpool',
       'QPR', 'Swansea', 'Cardiff', 'Bournemouth', 'Brighton',
       'Huddersfield', 'Brentford', 'Nottingham', 'Luton'], dtype=object)

In [204]:
pl_champions = {
    '9293': 'Man United', '9394': 'Man United', '9495': 'Blackburn', '9596': 'Man United',
    '9697': 'Man United', '9798': 'Arsenal', '9899': 'Man United', '9900': 'Man United',
    '0001': 'Man United', '0102': 'Arsenal', '0203': 'Man United', '0304': 'Arsenal',
    '0405': 'Chelsea', '0506': 'Chelsea', '0607': 'Man United', '0708': 'Man United',
    '0809': 'Man United', '0910': 'Chelsea', '1011': 'Man United', '1112': 'Man City',
    '1213': 'Man United', '1314': 'Man City', '1415': 'Chelsea', '1516': 'Leicester',
    '1617': 'Chelsea', '1718': 'Man City', '1819': 'Man City', '1920': 'Liverpool',
    '2021': 'Man City', '2122': 'Man City', '2223': 'Man City', '2324': 'Man City',
    '2425': 'Liverpool', '2526': 'Arsenal'
}

# دیکشنری قهرمانان جام حذفی (بر اساس سال شروع فصل)
fa_cup_winners = {
    '9293': 'Arsenal', '9394': 'Man United', '9495': 'Everton', '9596': 'Man United',
    '9697': 'Chelsea', '9798': 'Arsenal', '9899': 'Man United', '9900': 'Chelsea',
    '0001': 'Liverpool', '0102': 'Arsenal', '0203': 'Arsenal', '0304': 'Man United',
    '0405': 'Arsenal', '0506': 'Liverpool', '0607': 'Chelsea', '0708': 'Portsmouth',
    '0809': 'Chelsea', '0910': 'Chelsea', '1011': 'Man City', '1112': 'Chelsea',
    '1213': 'Wigan', '1314': 'Arsenal', '1415': 'Arsenal', '1516': 'Man United',
    '1617': 'Arsenal', '1718': 'Chelsea', '1819': 'Man City', '1920': 'Arsenal',
    '2021': 'Leicester', '2222': 'Liverpool', '2323': 'Man City', '2324': 'Man United',
    '2425': 'Crystal Palace', '2526': 'Man City'
}

# دیکشنری قهرمانان لیگ کاپ (بر اساس سال شروع فصل)
league_cup_winners = {
    '9293': 'Arsenal', '9394': 'Aston Villa', '9495': 'Liverpool', '9596': 'Aston Villa',
    '9697': 'Leicester', '9798': 'Chelsea', '9899': 'Tottenham', '9900': 'Leicester',
    '0001': 'Liverpool', '0102': 'Blackburn', '0203': 'Liverpool', '0304': 'Middlesbrough',
    '0405': 'Chelsea', '0506': 'Man United', '0607': 'Chelsea', '0708': 'Tottenham',
    '0809': 'Man United', '0910': 'Man United', '1011': 'Birmingham', '1112': 'Liverpool',
    '1213': 'Swansea', '1314': 'Man City', '1415': 'Chelsea', '1516': 'Man City',
    '1617': 'Man United', '1718': 'Man City', '1819': 'Man City', '1920': 'Man City',
    '2021': 'Man City', '2122': 'Liverpool', '2223': 'Man United', '2324': 'Liverpool',
    '2425': 'Newcastle', '2526': 'Man City'
}

# دیکشنری قهرمانان لیگ قهرمانان اروپا (فقط تیم‌های انگلیسی، بر اساس سال شروع فصل)
ucl_winners = {
    '9899': 'Man United', '0405': 'Liverpool', '0708': 'Man United', '1112': 'Chelsea',
    '1819': 'Liverpool', '2021': 'Chelsea', '2223': 'Man City'
}

# دیکشنری قهرمانان لیگ اروپا (فقط تیم‌های انگلیسی، بر اساس سال شروع فصل)
uel_winners = {
    '0001': 'Liverpool', '1213': 'Chelsea', '1617': 'Man United', '1819': 'Chelsea',
    '2425': 'Tottenham', '2526': 'Aston Villa'
}

# دیکشنری قهرمانان لیگ اروپا (فقط تیم‌های انگلیسی، بر اساس سال شروع فصل)
conf_winners = {
    '2223': 'West Ham', '2425': 'Chelsea', '2526': 'Crystal Palace'
}

# تابع محاسبه تعداد جام‌های یک تیم در یک سال خاص
def get_trophies(team, year):
    if pd.isna(team) or pd.isna(year):
        return 0
    year = int(year)
    count = 0
    if pl_champions.get(year) == team:
        count += 1
    if fa_cup_winners.get(year) == team:
        count += 1
    if league_cup_winners.get(year) == team:
        count += 1
    if ucl_winners.get(year) == team:
        count += 1
    if uel_winners.get(year) == team:
        count += 1
    if conf_winners.get(year) == team:
        count += 1
    return count

# اضافه کردن ستون‌های افتخارات به دیتافریم
df['HomeTrophies'] = df.apply(lambda row: get_trophies(row['HomeTeam'], row['Season']), axis=1)
df['AwayTrophies'] = df.apply(lambda row: get_trophies(row['AwayTeam'], row['Season']), axis=1)

In [205]:
df['HomeTrophies'].isna().sum()

np.int64(0)

In [206]:
df.to_csv("Data/matches.csv", index=False)

---

In [208]:
df = df.sort_values(['Year', 'Month', 'Day']).reset_index(drop=True)

team_history = {}
h2h_history = {}

home_forms = []
away_forms = []
h2h_forms = []

for idx, row in df.iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    home_goals = row['HomeGoal']
    away_goals = row['AwayGoal']
    
    if home_goals > away_goals:
        home_res = 'W'
        away_res = 'L'
        winner = home
    elif home_goals < away_goals:
        home_res = 'L'
        away_res = 'W'
        winner = away
    else:
        home_res = 'D'
        away_res = 'D'
        winner = 'D'
    
    home_last5 = team_history.get(home, [])[-5:]
    home_form = ''.join(reversed(home_last5))
    home_forms.append(home_form)
    
    away_last5 = team_history.get(away, [])[-5:]
    away_form = ''.join(reversed(away_last5))
    away_forms.append(away_form)
    
    pair = tuple(sorted([home, away]))
    h2h_last5 = h2h_history.get(pair, [])[-5:]
    
    h2h_codes = []
    for w in h2h_last5:
        if w == 'D':
            h2h_codes.append('D')
        elif w == home:
            h2h_codes.append('H')
        elif w == away:
            h2h_codes.append('A')
        else:
            h2h_codes.append('?')

    h2h_form = ''.join(reversed(h2h_codes))
    h2h_forms.append(h2h_form)
    
    team_history.setdefault(home, []).append(home_res)
    team_history.setdefault(away, []).append(away_res)
    h2h_history.setdefault(pair, []).append(winner)

df['HomeForm'] = home_forms
df['AwayForm'] = away_forms
df['H2HForm'] = h2h_forms

In [215]:
df[ df['Season'] == '2526' ].sample(20)[['HomeTeam', 'Round', 'AwayTeam', 'HomeForm', 'AwayForm', 'H2HForm']]

            HomeTeam  Round        AwayTeam HomeForm AwayForm H2HForm
9727  Crystal Palace   23.0         Chelsea    LDLDL    WLDDL   DDDAA
9615          Wolves   10.0  Crystal Palace    LLLLD    DWLDL   ADAAH
9609        Man City   10.0       Liverpool    WLWWW    WLLLL   AADDH
9555      Nottingham    5.0      Sunderland    DLLDW    DDWLW
9802        Brighton   23.0       Liverpool    WLWWL    DLWWW   AHAAD
9721         Burnley   18.0       Tottenham    DDLLD    LLDDW   AAAAH
9869         Chelsea    7.0       Tottenham    DLLLL    DWWDL   HHHHH
9637           Leeds   12.0         Chelsea    LLLLW    DWWWL   AHAAD
9592  Crystal Palace    9.0       Brentford    LDLWW    WWLWL   AAHDD
9775       Newcastle   21.0         Everton    LWLLL    LLWDD   HADDA
9692        Brighton   16.0         Burnley    DLDLD    LDDLL   DDAHD
9616       Newcastle   10.0        Man City    LLWLW    WWLWW   ADAAA
9789       Newcastle   22.0      Man United    LLWLL    WWDWW   AHHAH
9806     Aston Villa   23.0        West Ham    LLLDW    DWLDD   HDHDH
9535       Newcastle    3.0          Wolves    DLDLL    LLLDL   HHHDH
9650         Chelsea   13.0         Everton    DLDWW    WWLWW   HDHAD
9824         Everton   25.0       Liverpool    DWLWW    WLDLW   AADHA
9579        West Ham    6.0       Brentford    LDLLW    LWLDL   ADHAA
9745     Bournemouth    7.0     Aston Villa    WWDWL    LWLDW   AADAD
9815      Nottingham   24.0     Aston Villa    WDDLL    WLLLD   AAHAH

In [216]:
df.to_csv("Data/matches.csv", index=False)

---

In [218]:
var_seasons = ['1920', '2021', '2122', '2223', '2324', '2425', '2526']

df['VAR'] = df['Season'].apply(lambda x: 'Yes' if x in var_seasons else 'No')

In [219]:
df.to_csv("Data/matches.csv", index=False)

In [220]:
df.shape

(9880, 65)

In [221]:
df['Season'].unique()

array(['0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708',
       '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516',
       '1617', '1718', '1819', '1920', '2021', '2122', '2223', '2324',
       '2425', '2526'], dtype=object)

In [222]:
df.columns

Index(['Season', 'Year', 'Month', 'Day', 'WeekDay', 'Time', 'Round',
       'HomeTeam', 'AwayTeam', 'HomeGoal', 'AwayGoal', 'Result',
       'HomeGoal-HalfTime', 'AwayGoal-HalfTime', 'Result-HalfTime',
       'Attendance', 'Referee', 'HomeShot', 'AwayShot', 'HomeOnTargetShot',
       'AwayOnTargetShot', 'HomeFoul', 'AwayFoul', 'HomeCorner', 'AwayCorner',
       'HomeYellow', 'AwayYellow', 'HomeRed', 'AwayRed', 'XGHome', 'XGAway',
       'SeasonPosHome', 'SeasonPlayedHome', 'SeasonWinHome', 'SeasonDrawHome',
       'SeasonLossHome', 'SeasonGFHome', 'SeasonGAHome', 'SeasonGDHome',
       'SeasonPointsHome', 'QualificationOrRelegationHome', 'SeasonPosAway',
       'SeasonPlayedAway', 'SeasonWinAway', 'SeasonDrawAway', 'SeasonLossAway',
       'SeasonGFAway', 'SeasonGAAway', 'SeasonGDAway', 'SeasonPointsAway',
       'QualificationOrRelegationAway', 'HomeCity', 'HomeRegion', 'AwayCity',
       'AwayRegion', 'IsDerby', 'HomeStadium', 'HomeManager', 'AwayManager',
       'HomeTrophies', 'AwayTrophies', 'HomeForm', 'AwayForm', 'H2HForm',
       'VAR'],
      dtype='object')

In [223]:
df.to_csv("Data/EPL_Match_Data_2000_2026.csv", index=False)