In [2]:
import pandas as pd
from tools.utils import *

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [18]:
df = pd.read_csv("Data/Data7.csv", dtype={'Season': str})

---
$$ 2003-04 $$

In [13]:
missing_report(df,"0304")

WeekDay                          380
Time                             380
Round                            380
Attendance                       380
XGHome                           380
XGAway                           380
SeasonPosAway                     38
SeasonPlayedAway                  38
SeasonWinAway                     38
SeasonDrawAway                    38
SeasonLossAway                    38
SeasonGFAway                      38
SeasonGAAway                      38
SeasonGDAway                      38
SeasonPointsAway                  38
QualificationOrRelegationAway     38
dtype: int64

In [14]:
null_rows(df, '0304', 'SeasonPosAway')['AwayTeam'].unique()

array(['Bolton', 'Birmingham'], dtype=object)

In [5]:
df['QualificationOrRelegationAway'].unique()

array(['Not Applicable',
       'Relegation to the Football League First Division',
       'Qualification for the UEFA Cup first round',
       'Qualification for the Champions League group stage',
       "Qualification for the UEFA Cup Winners' Cup", nan,
       'Qualification for the Champions League second qualifying round',
       'Qualification for the Intertoto Cup third round',
       'Qualification for the Champions League third qualifying round',
       'Qualification for the Champions League first group stage',
       'Qualification for the UEFA Cup first round[a]',
       'Qualification for the Champions League third qualifying round[a]',
       'Qualification for the UEFA Cup qualifying round[a]Relegation to the Football League First Division',
       'Qualification for the UEFA Cup first round[c]',
       'Qualification for the Intertoto Cup second round',
       'Qualification for the UEFA Cup first round[b]',
       'Relegation to Football League First Division',
       'Qualification for the UEFA Cup qualifying round[c]',
       'Relegation to the Football League Championship',
       'Qualification for the Champions League first qualifying round[a]',
       'Qualification for the Champions League group stage[a]',
       'Qualification for the Intertoto Cup third round[b]',
       'Qualification for the UEFA Cup first qualifying round[b]',
       'Qualification for the Europa League third qualifying round[a]',
       'Qualification for the Europa League play-off round[a]',
       'Qualification for the Champions League play-off round',
       'Qualification for the Europa League third qualifying round[b]',
       'Qualification for the Europa League third qualifying round[c]',
       'Qualification for the Europa League first qualifying round[b]',
       'Qualification for the Europa League play-off round',
       'Qualification for the Europa League group stage[a]',
       'Qualification for the Europa League group stage[b]Relegation to the Football League Championship',
       'Qualification for the Europa League group stage',
       'Relegation to the EFL Championship',
       'Qualification for the Champions League group stage[b]',
       'Qualification for the Europa League second qualifying round[a]',
       'Qualification for the Europa League group stage[b]',
       'Qualification for the Europa Conference League play-off round[b]',
       'Qualification for the Europa Conference League play-off round[a]',
       'Qualification for the Europa Conference League play-off round'],
      dtype=object)

In [19]:
# Season statistics for Bolton Wanderers in 2003-04
bolton_stats = {
    'SeasonPosAway': 8,
    'SeasonPlayedAway': 38,
    'SeasonWinAway': 14,
    'SeasonDrawAway': 11,
    'SeasonLossAway': 13,
    'SeasonGFAway': 48,
    'SeasonGAAway': 56,
    'SeasonGDAway': -8,
    'SeasonPointsAway': 53,
    'QualificationOrRelegationAway': 'Not Applicable'
}

# Season statistics for Birmingham in 2003-04
Birmingham_stats = {
    'SeasonPosAway': 10,
    'SeasonPlayedAway': 38,
    'SeasonWinAway': 12,
    'SeasonDrawAway': 14,
    'SeasonLossAway': 12,
    'SeasonGFAway': 43,
    'SeasonGAAway': 48,
    'SeasonGDAway': -5,
    'SeasonPointsAway': 50,
    'QualificationOrRelegationAway': 'Not Applicable'
}

# List of columns to fill
away_cols = [
    'SeasonPosAway', 'SeasonPlayedAway', 'SeasonWinAway', 'SeasonDrawAway',
    'SeasonLossAway', 'SeasonGFAway', 'SeasonGAAway', 'SeasonGDAway',
    'SeasonPointsAway', 'QualificationOrRelegationAway'
]

# Fill the columns for all rows where AwayTeam is 'Bolton' in the 2003-04 season
for idx, row in df[df['Season'] == '0304'].iterrows():
    if row['AwayTeam'] == 'Bolton':
        for col in away_cols:
            df.loc[(df['Season'] == '0304') & (df.index == idx), col] = bolton_stats[col]

# Fill the columns for all rows where AwayTeam is 'Birmingham' in the 2003-04 season
for idx, row in df[df['Season'] == '0304'].iterrows():
    if row['AwayTeam'] == 'Birmingham':
        for col in away_cols:
            df.loc[(df['Season'] == '0304') & (df.index == idx), col] = Birmingham_stats[col]

In [8]:
null_rows(df, "0304", 'WeekDay')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
3964     Portsmouth    Aston Villa  2003      8   16
3965     Man United         Bolton  2003      8   16
3966         Fulham  Middlesbrough  2003      8   16
3967      Blackburn         Wolves  2003      8   16
3968     Birmingham      Tottenham  2003      8   16
3969        Arsenal        Everton  2003      8   16
3970      Leicester    Southampton  2003      8   16
3971       Charlton       Man City  2003      8   17
3972          Leeds      Newcastle  2003      8   17
3973      Liverpool        Chelsea  2003      8   17
3974         Wolves       Charlton  2003      8   23
3975    Southampton     Birmingham  2003      8   23
3976      Tottenham          Leeds  2003      8   23
3977        Everton         Fulham  2003      8   23
3978         Bolton      Blackburn  2003      8   23
3979       Man City     Portsmouth  2003      8   23
3980      Newcastle     Man United  2003      8   23
3981        Chelsea      Leicester  2003      8   23
3982  Middlesbrough        Arsenal  2003      8   24
3983    Aston Villa      Liverpool  2003      8   24
3984      Blackburn       Man City  2003      8   25
3985     Portsmouth         Bolton  2003      8   26
3986          Leeds    Southampton  2003      8   26
3987       Charlton        Everton  2003      8   26
3988      Leicester  Middlesbrough  2003      8   26
3989      Liverpool      Tottenham  2003      8   27
3990        Arsenal    Aston Villa  2003      8   27
3991     Man United         Wolves  2003      8   27
3992    Aston Villa      Leicester  2003      8   30
3993         Bolton       Charlton  2003      8   30
3994        Chelsea      Blackburn  2003      8   30
3995        Everton      Liverpool  2003      8   30
3996  Middlesbrough          Leeds  2003      8   30
3997      Tottenham         Fulham  2003      8   30
3998         Wolves     Portsmouth  2003      8   30
3999      Newcastle     Birmingham  2003      8   30
4000       Man City        Arsenal  2003      8   31
4001    Southampton     Man United  2003      8   31
4002        Everton      Newcastle  2003      9   13
4003    Southampton         Wolves  2003      9   13
4004        Chelsea      Tottenham  2003      9   13
4005      Blackburn      Liverpool  2003      9   13
4006        Arsenal     Portsmouth  2003      9   13
4007       Charlton     Man United  2003      9   13
4008         Bolton  Middlesbrough  2003      9   13
4009       Man City    Aston Villa  2003      9   14
4010     Birmingham         Fulham  2003      9   14
4011      Leicester          Leeds  2003      9   15
4012    Aston Villa       Charlton  2003      9   20
4013         Fulham       Man City  2003      9   20
4014          Leeds     Birmingham  2003      9   20
4015      Liverpool      Leicester  2003      9   20
4016     Portsmouth      Blackburn  2003      9   20
4017      Tottenham    Southampton  2003      9   20
4018         Wolves        Chelsea  2003      9   20
4019      Newcastle         Bolton  2003      9   20
4020     Man United        Arsenal  2003      9   21
4021  Middlesbrough        Everton  2003      9   21
4022        Arsenal      Newcastle  2003      9   26
4023      Leicester     Man United  2003      9   27
4024     Birmingham     Portsmouth  2003      9   27
4025        Chelsea    Aston Villa  2003      9   27
4026         Bolton         Wolves  2003      9   27
4027    Southampton  Middlesbrough  2003      9   27
4028        Everton          Leeds  2003      9   28
4029      Blackburn         Fulham  2003      9   28
4030       Charlton      Liverpool  2003      9   28
4031       Man City      Tottenham  2003      9   28
4032      Liverpool        Arsenal  2003     10    4
4033     Man United     Birmingham  2003     10    4
4034      Newcastle    Southampton  2003     10    4
4035     Portsmouth       Charlton  2003     10    4
4036         Fulham      Leicester  2003     10    4
4037         Wolves       Man City  2003     10    4
4038          Leeds      Blackburn  2003     10    4
4039      Tottenham        Everton  2003     10    4
4040    Aston Villa         Bolton  2003     10    5
4041  Middlesbrough        Chelsea  2003     10    5
4042     Birmingham        Chelsea  2003     10   14
4043     Portsmouth      Liverpool  2003     10   18
4044  Middlesbrough      Newcastle  2003     10   18
4045         Fulham         Wolves  2003     10   18
4046        Arsenal        Chelsea  2003     10   18
4047       Man City         Bolton  2003     10   18
4048          Leeds     Man United  2003     10   18
4049        Everton    Southampton  2003     10   19
4050     Birmingham    Aston Villa  2003     10   19
4051      Leicester      Tottenham  2003     10   19
4052      Blackburn       Charlton  2003     10   20
4053         Fulham      Newcastle  2003     10   21
4054    Aston Villa        Everton  2003     10   25
4055         Bolton     Birmingham  2003     10   25
4056      Liverpool          Leeds  2003     10   25
4057     Man United         Fulham  2003     10   25
4058      Newcastle     Portsmouth  2003     10   25
4059    Southampton      Blackburn  2003     10   25
4060         Wolves      Leicester  2003     10   25
4061        Chelsea       Man City  2003     10   25
4062      Tottenham  Middlesbrough  2003     10   26
4063       Charlton        Arsenal  2003     10   26

In [20]:
match_data = {
    # ==================== 16-17 August 2003 - Matchweek 1 ====================
    ('Portsmouth', 'Aston Villa'):    {'Round': 1, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 20101},
    ('Man United', 'Bolton'):         {'Round': 1, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 67647},
    ('Fulham', 'Middlesbrough'):      {'Round': 1, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 14546},
    ('Blackburn', 'Wolves'):          {'Round': 1, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 26270},
    ('Birmingham', 'Tottenham'):      {'Round': 1, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 29358},
    ('Arsenal', 'Everton'):           {'Round': 1, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 38014},
    ('Leicester', 'Southampton'):     {'Round': 1, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 31621},
    ('Charlton', 'Man City'):         {'Round': 1, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': 25846},
    ('Leeds', 'Newcastle'):           {'Round': 1, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': 36766},
    ('Liverpool', 'Chelsea'):         {'Round': 1, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': 44080},

    # ==================== 23-24 August 2003 - Matchweek 2 ====================
    ('Wolves', 'Charlton'):           {'Round': 2, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 27327},
    ('Southampton', 'Birmingham'):    {'Round': 2, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 31656},
    ('Tottenham', 'Leeds'):           {'Round': 2, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 34350},
    ('Everton', 'Fulham'):            {'Round': 2, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 37604},
    ('Bolton', 'Blackburn'):          {'Round': 2, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 27423},
    ('Man City', 'Portsmouth'):       {'Round': 2, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 46287},
    ('Newcastle', 'Man United'):      {'Round': 2, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 52165},
    ('Chelsea', 'Leicester'):         {'Round': 2, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 41074},
    ('Middlesbrough', 'Arsenal'):     {'Round': 2, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': 29450},
    ('Aston Villa', 'Liverpool'):     {'Round': 2, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': 42573},

    # ==================== 25-27 August 2003 - Matchweek 3 ====================
    ('Blackburn', 'Man City'):        {'Round': 3, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': 23353},
    ('Portsmouth', 'Bolton'):         {'Round': 3, 'WeekDay': 'Tue', 'Time': '19:45', 'Attendance': 20118},
    ('Leeds', 'Southampton'):         {'Round': 3, 'WeekDay': 'Tue', 'Time': '19:45', 'Attendance': 34721},
    ('Charlton', 'Everton'):          {'Round': 3, 'WeekDay': 'Tue', 'Time': '19:45', 'Attendance': 26314},
    ('Leicester', 'Middlesbrough'):   {'Round': 3, 'WeekDay': 'Tue', 'Time': '19:45', 'Attendance': 30823},
    ('Liverpool', 'Tottenham'):       {'Round': 3, 'WeekDay': 'Wed', 'Time': '20:00', 'Attendance': 43778},
    ('Arsenal', 'Aston Villa'):       {'Round': 3, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': 38010},
    ('Man United', 'Wolves'):         {'Round': 3, 'WeekDay': 'Wed', 'Time': '20:00', 'Attendance': 67648},

    # ==================== 30-31 August 2003 - Matchweek 4 ====================
    ('Aston Villa', 'Leicester'):     {'Round': 4, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 32274},
    ('Bolton', 'Charlton'):           {'Round': 4, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 23098},
    ('Chelsea', 'Blackburn'):         {'Round': 4, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 41066},
    ('Everton', 'Liverpool'):         {'Round': 4, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 40200},
    ('Middlesbrough', 'Leeds'):       {'Round': 4, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 30414},
    ('Tottenham', 'Fulham'):          {'Round': 4, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 33421},
    ('Wolves', 'Portsmouth'):         {'Round': 4, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 28680},
    ('Newcastle', 'Birmingham'):      {'Round': 4, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 52003},
    ('Man City', 'Arsenal'):          {'Round': 4, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': 46436},
    ('Southampton', 'Man United'):    {'Round': 4, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': 32066},

    # ==================== 13-15 September 2003 - Matchweek 5 ====================
    ('Everton', 'Newcastle'):         {'Round': 5, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 40228},
    ('Southampton', 'Wolves'):        {'Round': 5, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 31711},
    ('Chelsea', 'Tottenham'):         {'Round': 5, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 41165},
    ('Blackburn', 'Liverpool'):       {'Round': 5, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 30074},
    ('Arsenal', 'Portsmouth'):        {'Round': 5, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 38052},
    ('Charlton', 'Man United'):       {'Round': 5, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 26046},
    ('Bolton', 'Middlesbrough'):      {'Round': 5, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 26419},
    ('Man City', 'Aston Villa'):      {'Round': 5, 'WeekDay': 'Sun', 'Time': '14:00', 'Attendance': 46687},
    ('Birmingham', 'Fulham'):         {'Round': 5, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': 27250},
    ('Leicester', 'Leeds'):           {'Round': 5, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': 30460},

    # ==================== 20-21 September 2003 - Matchweek 6 ====================
    ('Aston Villa', 'Charlton'):      {'Round': 6, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 31410},
    ('Fulham', 'Man City'):           {'Round': 6, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 16124},
    ('Leeds', 'Birmingham'):          {'Round': 6, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 34305},
    ('Liverpool', 'Leicester'):       {'Round': 6, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 44094},
    ('Portsmouth', 'Blackburn'):      {'Round': 6, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 20029},
    ('Tottenham', 'Southampton'):     {'Round': 6, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 35758},
    ('Wolves', 'Chelsea'):            {'Round': 6, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 29208},
    ('Newcastle', 'Bolton'):          {'Round': 6, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 52014},
    ('Man United', 'Arsenal'):        {'Round': 6, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': 67639},
    ('Middlesbrough', 'Everton'):     {'Round': 6, 'WeekDay': 'Sun', 'Time': '14:00', 'Attendance': 28113},

    # ==================== 26-28 September 2003 - Matchweek 7 ====================
    ('Arsenal', 'Newcastle'):         {'Round': 7, 'WeekDay': 'Fri', 'Time': '20:00', 'Attendance': 38112},
    ('Leicester', 'Man United'):      {'Round': 7, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 32044},
    ('Birmingham', 'Portsmouth'):     {'Round': 7, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 29057},
    ('Chelsea', 'Aston Villa'):       {'Round': 7, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 41182},
    ('Bolton', 'Wolves'):             {'Round': 7, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 27043},
    ('Southampton', 'Middlesbrough'): {'Round': 7, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 30772},
    ('Everton', 'Leeds'):             {'Round': 7, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': 39151},
    ('Blackburn', 'Fulham'):          {'Round': 7, 'WeekDay': 'Sun', 'Time': '14:00', 'Attendance': 21985},
    ('Charlton', 'Liverpool'):        {'Round': 7, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': 26530},
    ('Man City', 'Tottenham'):        {'Round': 7, 'WeekDay': 'Sun', 'Time': '14:00', 'Attendance': 46842},

    # ==================== 4-5 October 2003 - Matchweek 8 ====================
    ('Liverpool', 'Arsenal'):         {'Round': 8, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 44374},
    ('Man United', 'Birmingham'):     {'Round': 8, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 67633},
    ('Newcastle', 'Southampton'):     {'Round': 8, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 52127},
    ('Portsmouth', 'Charlton'):       {'Round': 8, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 20122},
    ('Fulham', 'Leicester'):          {'Round': 8, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 14612},
    ('Wolves', 'Man City'):           {'Round': 8, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 29386},
    ('Leeds', 'Blackburn'):           {'Round': 8, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 35039},
    ('Tottenham', 'Everton'):         {'Round': 8, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 36103},
    ('Aston Villa', 'Bolton'):        {'Round': 8, 'WeekDay': 'Sun', 'Time': '14:00', 'Attendance': 30229},
    ('Middlesbrough', 'Chelsea'):     {'Round': 8, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': 29170},

    # ==================== 14 October 2003 - Matchweek 9 ====================
    ('Birmingham', 'Chelsea'):        {'Round': 9, 'WeekDay': 'Tue', 'Time': '19:45', 'Attendance': 29460},

    # ==================== 18-19 October 2003 - Matchweek 9 (continued) ====================
    ('Portsmouth', 'Liverpool'):      {'Round': 9, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 19126},
    ('Middlesbrough', 'Newcastle'):   {'Round': 9, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 34081},
    ('Fulham', 'Wolves'):             {'Round': 9, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 17031},
    ('Arsenal', 'Chelsea'):           {'Round': 9, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 38172},
    ('Man City', 'Bolton'):           {'Round': 9, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 47101},
    ('Leeds', 'Man United'):          {'Round': 9, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 40153},
    ('Everton', 'Southampton'):       {'Round': 9, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},
    ('Birmingham', 'Aston Villa'):    {'Round': 9, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},
    ('Leicester', 'Tottenham'):       {'Round': 9, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},
    ('Blackburn', 'Charlton'):        {'Round': 9, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},
    ('Fulham', 'Newcastle'):          {'Round': 9, 'WeekDay': 'Tue', 'Time': '19:45', 'Attendance': None},

    # ==================== 25-26 October 2003 - Matchweek 10 ====================
    ('Aston Villa', 'Everton'):       {'Round': 10, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Bolton', 'Birmingham'):         {'Round': 10, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Liverpool', 'Leeds'):           {'Round': 10, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Man United', 'Fulham'):         {'Round': 10, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Newcastle', 'Portsmouth'):      {'Round': 10, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Southampton', 'Blackburn'):     {'Round': 10, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Wolves', 'Leicester'):          {'Round': 10, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Chelsea', 'Man City'):          {'Round': 10, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Tottenham', 'Middlesbrough'):   {'Round': 10, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},
    ('Charlton', 'Arsenal'):          {'Round': 10, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},
}

fill_from_dict(
    df,
    season="0304",
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [22]:
null_rows(df, "0304", 'WeekDay')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
4064     Man United     Portsmouth  2003     11    1
4065        Everton        Chelsea  2003     11    1
4066      Tottenham         Bolton  2003     11    1
4067          Leeds        Arsenal  2003     11    1
4068    Southampton       Man City  2003     11    1
4069      Newcastle    Aston Villa  2003     11    1
4070  Middlesbrough         Wolves  2003     11    1
4071         Fulham      Liverpool  2003     11    2
4072      Leicester      Blackburn  2003     11    2
4073     Birmingham       Charlton  2003     11    3
4074    Aston Villa  Middlesbrough  2003     11    8
4075         Wolves     Birmingham  2003     11    8
4076        Arsenal      Tottenham  2003     11    8
4077     Portsmouth          Leeds  2003     11    8
4078         Bolton    Southampton  2003     11    8
4079       Charlton         Fulham  2003     11    8
4080        Chelsea      Newcastle  2003     11    9
4081       Man City      Leicester  2003     11    9
4082      Liverpool     Man United  2003     11    9
4083      Blackburn        Everton  2003     11   10
4084     Birmingham        Arsenal  2003     11   22
4085        Everton         Wolves  2003     11   22
4086          Leeds         Bolton  2003     11   22
4087      Leicester       Charlton  2003     11   22
4088  Middlesbrough      Liverpool  2003     11   22
4089      Newcastle       Man City  2003     11   22
4090    Southampton        Chelsea  2003     11   22
4091     Man United      Blackburn  2003     11   22
4092      Tottenham    Aston Villa  2003     11   23
4093         Fulham     Portsmouth  2003     11   24
4094         Wolves      Newcastle  2003     11   29
4095       Charlton          Leeds  2003     11   29
4096         Bolton        Everton  2003     11   29
4097      Blackburn      Tottenham  2003     11   29
4098     Portsmouth      Leicester  2003     11   29
4099    Aston Villa    Southampton  2003     11   29
4100        Arsenal         Fulham  2003     11   30
4101        Chelsea     Man United  2003     11   30
4102      Liverpool     Birmingham  2003     11   30
4103       Man City  Middlesbrough  2003     11   30
4104     Birmingham      Blackburn  2003     12    6
4105         Fulham         Bolton  2003     12    6
4106          Leeds        Chelsea  2003     12    6
4107      Leicester        Arsenal  2003     12    6
4108     Man United    Aston Villa  2003     12    6
4109  Middlesbrough     Portsmouth  2003     12    6
4110      Newcastle      Liverpool  2003     12    6
4111      Tottenham         Wolves  2003     12    6
4112        Everton       Man City  2003     12    7
4113    Southampton       Charlton  2003     12    7
4114      Liverpool    Southampton  2003     12   13
4115      Leicester     Birmingham  2003     12   13
4116     Portsmouth        Everton  2003     12   13
4117        Chelsea         Bolton  2003     12   13
4118      Newcastle      Tottenham  2003     12   13
4119  Middlesbrough       Charlton  2003     12   13
4120     Man United       Man City  2003     12   13
4121        Arsenal      Blackburn  2003     12   14
4122          Leeds         Fulham  2003     12   14
4123    Aston Villa         Wolves  2003     12   14
4124         Bolton        Arsenal  2003     12   20
4125       Charlton      Newcastle  2003     12   20
4126        Everton      Leicester  2003     12   20
4127         Fulham        Chelsea  2003     12   20
4128      Blackburn    Aston Villa  2003     12   20
4129      Tottenham     Man United  2003     12   21
4130    Southampton     Portsmouth  2003     12   21
4131       Man City          Leeds  2003     12   22
4132      Liverpool         Bolton  2003     12   26
4133     Portsmouth      Tottenham  2003     12   26
4134     Man United        Everton  2003     12   26
4135          Leeds    Aston Villa  2003     12   26
4136         Fulham    Southampton  2003     12   26
4137       Charlton        Chelsea  2003     12   26
4138     Birmingham       Man City  2003     12   26
4139        Arsenal         Wolves  2003     12   26
4140      Leicester      Newcastle  2003     12   26
4141      Blackburn  Middlesbrough  2003     12   26
4142    Aston Villa         Fulham  2003     12   28
4143         Bolton      Leicester  2003     12   28
4144        Chelsea     Portsmouth  2003     12   28
4145        Everton     Birmingham  2003     12   28
4146       Man City      Liverpool  2003     12   28
4147  Middlesbrough     Man United  2003     12   28
4148      Newcastle      Blackburn  2003     12   28
4149      Tottenham       Charlton  2003     12   28
4150         Wolves          Leeds  2003     12   28
4151    Southampton        Arsenal  2003     12   29
4152    Aston Villa     Portsmouth  2004      1    6
4153        Everton        Arsenal  2004      1    7
4154         Bolton     Man United  2004      1    7
4155         Wolves      Blackburn  2004      1    7
4156      Tottenham     Birmingham  2004      1    7
4157        Chelsea      Liverpool  2004      1    7
4158      Newcastle          Leeds  2004      1    7
4159  Middlesbrough         Fulham  2004      1    7
4160    Southampton      Leicester  2004      1    7
4161       Man City       Charlton  2004      1    7
4162       Charlton         Wolves  2004      1   10
4163         Fulham        Everton  2004      1   10

In [23]:
match_data = {
    # ==================== 1 November 2003 - Matchweek 11 ====================
    ('Man United', 'Portsmouth'):    {'Round': 11, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 67639},   # Source: FBref[reference:4][reference:5]
    ('Everton', 'Chelsea'):          {'Round': 11, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Tottenham', 'Bolton'):         {'Round': 11, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Leeds', 'Arsenal'):            {'Round': 11, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Southampton', 'Man City'):     {'Round': 11, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Newcastle', 'Aston Villa'):    {'Round': 11, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Middlesbrough', 'Wolves'):     {'Round': 11, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Fulham', 'Liverpool'):         {'Round': 11, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found
    ('Leicester', 'Blackburn'):      {'Round': 11, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found
    ('Birmingham', 'Charlton'):      {'Round': 11, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 8-10 November 2003 - Matchweek 12 ====================
    ('Aston Villa', 'Middlesbrough'): {'Round': 12, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Wolves', 'Birmingham'):         {'Round': 12, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Arsenal', 'Tottenham'):         {'Round': 12, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Portsmouth', 'Leeds'):          {'Round': 12, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Bolton', 'Southampton'):        {'Round': 12, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Charlton', 'Fulham'):           {'Round': 12, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Chelsea', 'Newcastle'):         {'Round': 12, 'WeekDay': 'Sun', 'Time': '14:00', 'Attendance': None},   # Source: FBref - data not found
    ('Man City', 'Leicester'):        {'Round': 12, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found
    ('Liverpool', 'Man United'):      {'Round': 12, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found
    ('Blackburn', 'Everton'):         {'Round': 12, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},   # Source: FBref - data not found

    # ==================== 22-24 November 2003 - Matchweek 13 ====================
    ('Birmingham', 'Arsenal'):        {'Round': 13, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Everton', 'Wolves'):            {'Round': 13, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Leeds', 'Bolton'):              {'Round': 13, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Leicester', 'Charlton'):        {'Round': 13, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Middlesbrough', 'Liverpool'):   {'Round': 13, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Newcastle', 'Man City'):        {'Round': 13, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Southampton', 'Chelsea'):       {'Round': 13, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Man United', 'Blackburn'):      {'Round': 13, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Tottenham', 'Aston Villa'):     {'Round': 13, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found
    ('Fulham', 'Portsmouth'):         {'Round': 13, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': 15624},  # Source: ESPN[reference:6]

    # ==================== 29-30 November 2003 - Matchweek 14 ====================
    ('Wolves', 'Newcastle'):          {'Round': 14, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Charlton', 'Leeds'):            {'Round': 14, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Bolton', 'Everton'):            {'Round': 14, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Blackburn', 'Tottenham'):       {'Round': 14, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Portsmouth', 'Leicester'):      {'Round': 14, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Aston Villa', 'Southampton'):   {'Round': 14, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Arsenal', 'Fulham'):            {'Round': 14, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found
    ('Chelsea', 'Man United'):        {'Round': 14, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found
    ('Liverpool', 'Birmingham'):      {'Round': 14, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found
    ('Man City', 'Middlesbrough'):    {'Round': 14, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found

    # ==================== 6-7 December 2003 - Matchweek 15 ====================
    ('Birmingham', 'Blackburn'):      {'Round': 15, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Fulham', 'Bolton'):             {'Round': 15, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Leeds', 'Chelsea'):             {'Round': 15, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Leicester', 'Arsenal'):         {'Round': 15, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Man United', 'Aston Villa'):    {'Round': 15, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Middlesbrough', 'Portsmouth'):  {'Round': 15, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Newcastle', 'Liverpool'):       {'Round': 15, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Tottenham', 'Wolves'):          {'Round': 15, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Everton', 'Man City'):          {'Round': 15, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found
    ('Southampton', 'Charlton'):      {'Round': 15, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found

    # ==================== 13-14 December 2003 - Matchweek 16 ====================
    ('Liverpool', 'Southampton'):     {'Round': 16, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Leicester', 'Birmingham'):      {'Round': 16, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Portsmouth', 'Everton'):        {'Round': 16, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Chelsea', 'Bolton'):            {'Round': 16, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Newcastle', 'Tottenham'):       {'Round': 16, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Middlesbrough', 'Charlton'):    {'Round': 16, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Man United', 'Man City'):       {'Round': 16, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Arsenal', 'Blackburn'):         {'Round': 16, 'WeekDay': 'Sun', 'Time': '14:00', 'Attendance': None},   # Source: FBref - data not found
    ('Leeds', 'Fulham'):              {'Round': 16, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found
    ('Aston Villa', 'Wolves'):        {'Round': 16, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found

    # ==================== 20-22 December 2003 - Matchweek 17 ====================
    ('Bolton', 'Arsenal'):            {'Round': 17, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Charlton', 'Newcastle'):        {'Round': 17, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Everton', 'Leicester'):         {'Round': 17, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Fulham', 'Chelsea'):            {'Round': 17, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Blackburn', 'Aston Villa'):     {'Round': 17, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Tottenham', 'Man United'):      {'Round': 17, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found
    ('Southampton', 'Portsmouth'):    {'Round': 17, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},   # Source: FBref - data not found
    ('Man City', 'Leeds'):            {'Round': 17, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},   # Source: FBref - data not found

    # ==================== 26 December 2003 - Matchweek 18 ====================
    ('Liverpool', 'Bolton'):          {'Round': 18, 'WeekDay': 'Fri', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Portsmouth', 'Tottenham'):      {'Round': 18, 'WeekDay': 'Fri', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Man United', 'Everton'):        {'Round': 18, 'WeekDay': 'Fri', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Leeds', 'Aston Villa'):         {'Round': 18, 'WeekDay': 'Fri', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Fulham', 'Southampton'):        {'Round': 18, 'WeekDay': 'Fri', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Charlton', 'Chelsea'):          {'Round': 18, 'WeekDay': 'Fri', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Birmingham', 'Man City'):       {'Round': 18, 'WeekDay': 'Fri', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Arsenal', 'Wolves'):            {'Round': 18, 'WeekDay': 'Fri', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Leicester', 'Newcastle'):       {'Round': 18, 'WeekDay': 'Fri', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Blackburn', 'Middlesbrough'):   {'Round': 18, 'WeekDay': 'Fri', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found

    # ==================== 28-29 December 2003 - Matchweek 19 ====================
    ('Aston Villa', 'Fulham'):        {'Round': 19, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Bolton', 'Leicester'):          {'Round': 19, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Chelsea', 'Portsmouth'):        {'Round': 19, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Everton', 'Birmingham'):        {'Round': 19, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Man City', 'Liverpool'):        {'Round': 19, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Middlesbrough', 'Man United'):  {'Round': 19, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Newcastle', 'Blackburn'):       {'Round': 19, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Tottenham', 'Charlton'):        {'Round': 19, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Wolves', 'Leeds'):              {'Round': 19, 'WeekDay': 'Sun', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Southampton', 'Arsenal'):       {'Round': 19, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},   # Source: FBref - data not found

    # ==================== 6-7 January 2004 - Matchweek 20 ====================
    ('Aston Villa', 'Portsmouth'):    {'Round': 20, 'WeekDay': 'Tue', 'Time': '19:45', 'Attendance': None},   # Source: FBref - data not found
    ('Everton', 'Arsenal'):           {'Round': 20, 'WeekDay': 'Wed', 'Time': '20:00', 'Attendance': None},   # Source: FBref - data not found
    ('Bolton', 'Man United'):         {'Round': 20, 'WeekDay': 'Wed', 'Time': '20:00', 'Attendance': None},   # Source: FBref - data not found
    ('Wolves', 'Blackburn'):          {'Round': 20, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},   # Source: FBref - data not found
    ('Tottenham', 'Birmingham'):      {'Round': 20, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},   # Source: FBref - data not found
    ('Chelsea', 'Liverpool'):         {'Round': 20, 'WeekDay': 'Wed', 'Time': '20:00', 'Attendance': None},   # Source: FBref - data not found
    ('Newcastle', 'Leeds'):           {'Round': 20, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},   # Source: FBref - data not found
    ('Middlesbrough', 'Fulham'):      {'Round': 20, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},   # Source: FBref - data not found
    ('Southampton', 'Leicester'):     {'Round': 20, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},   # Source: FBref - data not found
    ('Man City', 'Charlton'):         {'Round': 20, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},   # Source: FBref - data not found

    # ==================== 10 January 2004 - Matchweek 21 ====================
    ('Charlton', 'Wolves'):           {'Round': 21, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
    ('Fulham', 'Everton'):            {'Round': 21, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},   # Source: FBref - data not found
}


fill_from_dict(
    df,
    season="0304",
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [24]:
null_rows(df, "0304", 'WeekDay')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
4164          Leeds      Tottenham  2004      1   10
4165      Liverpool    Aston Villa  2004      1   10
4166     Portsmouth       Man City  2004      1   10
4167        Arsenal  Middlesbrough  2004      1   10
4168     Birmingham    Southampton  2004      1   10
4169      Blackburn         Bolton  2004      1   10
4170     Man United      Newcastle  2004      1   11
4171      Leicester        Chelsea  2004      1   11
4172       Man City      Blackburn  2004      1   17
4173  Middlesbrough      Leicester  2004      1   17
4174    Southampton          Leeds  2004      1   17
4175      Tottenham      Liverpool  2004      1   17
4176         Wolves     Man United  2004      1   17
4177         Bolton     Portsmouth  2004      1   17
4178        Everton       Charlton  2004      1   17
4179    Aston Villa        Arsenal  2004      1   18
4180        Chelsea     Birmingham  2004      1   18
4181      Newcastle         Fulham  2004      1   19
4182         Wolves      Liverpool  2004      1   21
4183     Birmingham      Newcastle  2004      1   31
4184       Charlton         Bolton  2004      1   31
4185         Fulham      Tottenham  2004      1   31
4186          Leeds  Middlesbrough  2004      1   31
4187      Leicester    Aston Villa  2004      1   31
4188      Liverpool        Everton  2004      1   31
4189     Man United    Southampton  2004      1   31
4190     Portsmouth         Wolves  2004      1   31
4191        Arsenal       Man City  2004      2    1
4192      Blackburn        Chelsea  2004      2    1
4193         Wolves        Arsenal  2004      2    7
4194    Southampton         Fulham  2004      2    7
4195      Tottenham     Portsmouth  2004      2    7
4196        Everton     Man United  2004      2    7
4197    Aston Villa          Leeds  2004      2    7
4198      Newcastle      Leicester  2004      2    7
4199  Middlesbrough      Blackburn  2004      2    7
4200         Bolton      Liverpool  2004      2    7
4201       Man City     Birmingham  2004      2    8
4202        Chelsea       Charlton  2004      2    8
4203        Arsenal    Southampton  2004      2   10
4204          Leeds         Wolves  2004      2   10
4205      Leicester         Bolton  2004      2   10
4206     Birmingham        Everton  2004      2   11
4207      Blackburn      Newcastle  2004      2   11
4208       Charlton      Tottenham  2004      2   11
4209         Fulham    Aston Villa  2004      2   11
4210      Liverpool       Man City  2004      2   11
4211     Man United  Middlesbrough  2004      2   11
4212     Portsmouth        Chelsea  2004      2   11
4213         Wolves         Fulham  2004      2   21
4214    Southampton        Everton  2004      2   21
4215     Man United          Leeds  2004      2   21
4216        Chelsea        Arsenal  2004      2   21
4217       Charlton      Blackburn  2004      2   21
4218         Bolton       Man City  2004      2   21
4219      Newcastle  Middlesbrough  2004      2   21
4220    Aston Villa     Birmingham  2004      2   22
4221      Tottenham      Leicester  2004      2   22
4222        Everton    Aston Villa  2004      2   28
4223         Fulham     Man United  2004      2   28
4224      Leicester         Wolves  2004      2   28
4225        Arsenal       Charlton  2004      2   28
4226      Blackburn    Southampton  2004      2   28
4227       Man City        Chelsea  2004      2   28
4228          Leeds      Liverpool  2004      2   29
4229     Portsmouth      Newcastle  2004      2   29
4230     Birmingham  Middlesbrough  2004      3    3
4231     Birmingham         Bolton  2004      3    6
4232  Middlesbrough      Tottenham  2004      3    9
4233     Birmingham      Leicester  2004      3   13
4234      Blackburn        Arsenal  2004      3   13
4235         Bolton        Chelsea  2004      3   13
4236         Fulham          Leeds  2004      3   13
4237       Charlton  Middlesbrough  2004      3   13
4238        Everton     Portsmouth  2004      3   13
4239      Tottenham      Newcastle  2004      3   14
4240    Southampton      Liverpool  2004      3   14
4241       Man City     Man United  2004      3   14
4242         Wolves    Aston Villa  2004      3   14
4243      Liverpool     Portsmouth  2004      3   17
4244      Newcastle       Charlton  2004      3   20
4245  Middlesbrough     Birmingham  2004      3   20
4246     Man United      Tottenham  2004      3   20
4247        Arsenal         Bolton  2004      3   20
4248      Leicester        Everton  2004      3   20
4249    Aston Villa      Blackburn  2004      3   20
4250      Liverpool         Wolves  2004      3   20
4251        Chelsea         Fulham  2004      3   20
4252     Portsmouth    Southampton  2004      3   21
4253          Leeds       Man City  2004      3   22
4254       Charlton    Aston Villa  2004      3   27
4255     Birmingham          Leeds  2004      3   27
4256    Southampton      Tottenham  2004      3   27
4257      Blackburn     Portsmouth  2004      3   27
4258        Everton  Middlesbrough  2004      3   27
4259        Chelsea         Wolves  2004      3   27
4260       Man City         Fulham  2004      3   27
4261        Arsenal     Man United  2004      3   28
4262         Bolton      Newcastle  2004      3   28
4263      Leicester      Liverpool  2004      3   28

In [25]:
match_data = {
    # ==================== 10 January 2004 - Matchweek 21 ====================
    ('Leeds', 'Tottenham'):         {'Round': 21, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 35365},   # Source: BBC Sport[reference:0]
    ('Liverpool', 'Aston Villa'):   {'Round': 21, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Portsmouth', 'Man City'):     {'Round': 21, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Arsenal', 'Middlesbrough'):   {'Round': 21, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 38117},   # Source: FBref[reference:1], 11v11.com[reference:2]
    ('Birmingham', 'Southampton'):  {'Round': 21, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Blackburn', 'Bolton'):        {'Round': 21, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 11 January 2004 - Matchweek 21 ====================
    ('Man United', 'Newcastle'):    {'Round': 21, 'WeekDay': 'Sun', 'Time': '16:05', 'Attendance': 67622},   # Source: FBref[reference:3], ESPN[reference:4]

    # ==================== 17 January 2004 - Matchweek 22 ====================
    ('Man City', 'Blackburn'):      {'Round': 22, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 47090},   # Source: weltfussball.de[reference:5], Wikipedia[reference:6]
    ('Middlesbrough', 'Leicester'): {'Round': 22, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 27124},   # Source: FBref[reference:7], ESPN[reference:8]
    ('Southampton', 'Leeds'):       {'Round': 22, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Tottenham', 'Liverpool'):     {'Round': 22, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Wolves', 'Man United'):       {'Round': 22, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Bolton', 'Portsmouth'):       {'Round': 22, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Everton', 'Charlton'):        {'Round': 22, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 18 January 2004 - Matchweek 22 ====================
    ('Aston Villa', 'Arsenal'):     {'Round': 22, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found
    ('Chelsea', 'Birmingham'):      {'Round': 22, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 19 January 2004 - Matchweek 22 ====================
    ('Newcastle', 'Fulham'):        {'Round': 22, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 21 January 2004 - Matchweek 21 (Rescheduled) ====================
    ('Wolves', 'Liverpool'):        {'Round': 21, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 31 January 2004 - Matchweek 23 ====================
    ('Birmingham', 'Newcastle'):    {'Round': 23, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 29513},   # Source: FBref[reference:9], Sky Sports[reference:10]
    ('Charlton', 'Bolton'):         {'Round': 23, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Fulham', 'Tottenham'):        {'Round': 23, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Leeds', 'Middlesbrough'):     {'Round': 23, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Leicester', 'Aston Villa'):   {'Round': 23, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Liverpool', 'Everton'):       {'Round': 23, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Man United', 'Southampton'):  {'Round': 23, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Portsmouth', 'Wolves'):       {'Round': 23, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 1 February 2004 - Matchweek 23 ====================
    ('Arsenal', 'Man City'):        {'Round': 23, 'WeekDay': 'Sun', 'Time': '16:05', 'Attendance': 38103},   # Source: Wikipedia[reference:11], ResultDB[reference:12]
    ('Blackburn', 'Chelsea'):       {'Round': 23, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 7 February 2004 - Matchweek 24 ====================
    ('Wolves', 'Arsenal'):          {'Round': 24, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 29392},   # Source: FBref[reference:13], ESPN[reference:14]
    ('Southampton', 'Fulham'):      {'Round': 24, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Tottenham', 'Portsmouth'):    {'Round': 24, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Everton', 'Man United'):      {'Round': 24, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Aston Villa', 'Leeds'):       {'Round': 24, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Newcastle', 'Leicester'):     {'Round': 24, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Middlesbrough', 'Blackburn'): {'Round': 24, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Bolton', 'Liverpool'):        {'Round': 24, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 8 February 2004 - Matchweek 24 ====================
    ('Man City', 'Birmingham'):     {'Round': 24, 'WeekDay': 'Sun', 'Time': '14:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 10 February 2004 - Matchweek 25 ====================
    ('Arsenal', 'Southampton'):     {'Round': 25, 'WeekDay': 'Tue', 'Time': '19:45', 'Attendance': None},    # Source: FBref - data not found
    ('Leeds', 'Wolves'):            {'Round': 25, 'WeekDay': 'Tue', 'Time': '19:45', 'Attendance': None},    # Source: FBref - data not found
    ('Leicester', 'Bolton'):        {'Round': 25, 'WeekDay': 'Tue', 'Time': '19:45', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 11 February 2004 - Matchweek 25 ====================
    ('Birmingham', 'Everton'):      {'Round': 25, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},    # Source: FBref - data not found
    ('Blackburn', 'Newcastle'):     {'Round': 25, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},    # Source: FBref - data not found
    ('Charlton', 'Tottenham'):      {'Round': 25, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},    # Source: FBref - data not found
    ('Fulham', 'Aston Villa'):      {'Round': 25, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},    # Source: FBref - data not found
    ('Liverpool', 'Man City'):      {'Round': 25, 'WeekDay': 'Wed', 'Time': '20:00', 'Attendance': None},    # Source: FBref - data not found
    ('Man United', 'Middlesbrough'):{'Round': 25, 'WeekDay': 'Wed', 'Time': '20:00', 'Attendance': None},    # Source: FBref - data not found
    ('Portsmouth', 'Chelsea'):      {'Round': 25, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 21 February 2004 - Matchweek 26 ====================
    ('Wolves', 'Fulham'):           {'Round': 26, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Southampton', 'Everton'):     {'Round': 26, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Man United', 'Leeds'):        {'Round': 26, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Chelsea', 'Arsenal'):         {'Round': 26, 'WeekDay': 'Sat', 'Time': '12:30', 'Attendance': 41926},   # Source: FBref[reference:15], Stamford-Bridge.com[reference:16]
    ('Charlton', 'Blackburn'):      {'Round': 26, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Bolton', 'Man City'):         {'Round': 26, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Newcastle', 'Middlesbrough'): {'Round': 26, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 22 February 2004 - Matchweek 26 ====================
    ('Aston Villa', 'Birmingham'):  {'Round': 26, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found
    ('Tottenham', 'Leicester'):     {'Round': 26, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 28 February 2004 - Matchweek 27 ====================
    ('Everton', 'Aston Villa'):     {'Round': 27, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Fulham', 'Man United'):       {'Round': 27, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Leicester', 'Wolves'):        {'Round': 27, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Arsenal', 'Charlton'):        {'Round': 27, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 38137},   # Source: FBref[reference:17], Sky Sports[reference:18]
    ('Blackburn', 'Southampton'):   {'Round': 27, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Man City', 'Chelsea'):        {'Round': 27, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 29 February 2004 - Matchweek 27 ====================
    ('Leeds', 'Liverpool'):         {'Round': 27, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found
    ('Portsmouth', 'Newcastle'):    {'Round': 27, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 3 March 2004 - Matchweek 25 (Rescheduled) ====================
    ('Birmingham', 'Middlesbrough'):{'Round': 25, 'WeekDay': 'Wed', 'Time': '19:45', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 6 March 2004 - Matchweek 28 ====================
    ('Birmingham', 'Bolton'):       {'Round': 28, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 9 March 2004 - Matchweek 27 (Rescheduled) ====================
    ('Middlesbrough', 'Tottenham'): {'Round': 27, 'WeekDay': 'Tue', 'Time': '19:45', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 13 March 2004 - Matchweek 28 ====================
    ('Birmingham', 'Leicester'):    {'Round': 28, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Blackburn', 'Arsenal'):       {'Round': 28, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Bolton', 'Chelsea'):          {'Round': 28, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Fulham', 'Leeds'):            {'Round': 28, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Charlton', 'Middlesbrough'):  {'Round': 28, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Everton', 'Portsmouth'):      {'Round': 28, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 14 March 2004 - Matchweek 28 ====================
    ('Tottenham', 'Newcastle'):     {'Round': 28, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found
    ('Southampton', 'Liverpool'):   {'Round': 28, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found
    ('Man City', 'Man United'):     {'Round': 28, 'WeekDay': 'Sun', 'Time': '14:00', 'Attendance': None},    # Source: FBref - data not found
    ('Wolves', 'Aston Villa'):      {'Round': 28, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 17 March 2004 - Matchweek 29 ====================
    ('Liverpool', 'Portsmouth'):    {'Round': 29, 'WeekDay': 'Wed', 'Time': '20:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 20 March 2004 - Matchweek 29 ====================
    ('Newcastle', 'Charlton'):      {'Round': 29, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Middlesbrough', 'Birmingham'):{'Round': 29, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Man United', 'Tottenham'):    {'Round': 29, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Arsenal', 'Bolton'):          {'Round': 29, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Leicester', 'Everton'):       {'Round': 29, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Aston Villa', 'Blackburn'):   {'Round': 29, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Liverpool', 'Wolves'):        {'Round': 29, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Chelsea', 'Fulham'):          {'Round': 29, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 21 March 2004 - Matchweek 29 ====================
    ('Portsmouth', 'Southampton'):  {'Round': 29, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 22 March 2004 - Matchweek 29 ====================
    ('Leeds', 'Man City'):          {'Round': 29, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 27 March 2004 - Matchweek 30 ====================
    ('Charlton', 'Aston Villa'):    {'Round': 30, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Birmingham', 'Leeds'):        {'Round': 30, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Southampton', 'Tottenham'):   {'Round': 30, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Blackburn', 'Portsmouth'):    {'Round': 30, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Everton', 'Middlesbrough'):   {'Round': 30, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Chelsea', 'Wolves'):          {'Round': 30, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found
    ('Man City', 'Fulham'):         {'Round': 30, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},    # Source: FBref - data not found

    # ==================== 28 March 2004 - Matchweek 30 ====================
    ('Arsenal', 'Man United'):      {'Round': 30, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found
    ('Bolton', 'Newcastle'):        {'Round': 30, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found
    ('Leicester', 'Liverpool'):     {'Round': 30, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},    # Source: FBref - data not found
}
fill_from_dict(
    df,
    season="0304",
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [26]:
null_rows(df, "0304", 'WeekDay')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
4171      Leicester        Chelsea  2004      1   11
4202        Chelsea       Charlton  2004      2    8
4264  Middlesbrough         Bolton  2004      4    3
4265      Newcastle        Everton  2004      4    3
4266      Tottenham        Chelsea  2004      4    3
4267         Wolves    Southampton  2004      4    3
4268         Fulham     Birmingham  2004      4    3
4269    Aston Villa       Man City  2004      4    4
4270      Liverpool      Blackburn  2004      4    4
4271          Leeds      Leicester  2004      4    5
4272        Arsenal      Liverpool  2004      4    9
4273        Everton      Tottenham  2004      4    9
4274      Blackburn          Leeds  2004      4   10
4275       Man City         Wolves  2004      4   10
4276      Leicester         Fulham  2004      4   10
4277     Birmingham     Man United  2004      4   10
4278       Charlton     Portsmouth  2004      4   10
4279         Bolton    Aston Villa  2004      4   10
4280        Chelsea  Middlesbrough  2004      4   10
4281      Newcastle        Arsenal  2004      4   11
4282    Aston Villa        Chelsea  2004      4   12
4283      Liverpool       Charlton  2004      4   12
4284  Middlesbrough    Southampton  2004      4   12
4285     Portsmouth     Birmingham  2004      4   12
4286      Tottenham       Man City  2004      4   12
4287         Wolves         Bolton  2004      4   12
4288         Fulham      Blackburn  2004      4   12
4289          Leeds        Everton  2004      4   13
4290     Man United      Leicester  2004      4   13
4291        Arsenal          Leeds  2004      4   16
4292       Charlton     Birmingham  2004      4   17
4293         Bolton      Tottenham  2004      4   17
4294         Wolves  Middlesbrough  2004      4   17
4295     Portsmouth     Man United  2004      4   17
4296      Blackburn      Leicester  2004      4   17
4297      Liverpool         Fulham  2004      4   17
4298        Chelsea        Everton  2004      4   17
4299       Man City    Southampton  2004      4   17
4300    Aston Villa      Newcastle  2004      4   18
4301     Man United       Charlton  2004      4   20
4302        Everton      Blackburn  2004      4   24
4303         Fulham       Charlton  2004      4   24
4304      Leicester       Man City  2004      4   24
4305     Man United      Liverpool  2004      4   24
4306  Middlesbrough    Aston Villa  2004      4   24
4307    Southampton         Bolton  2004      4   24
4308     Birmingham         Wolves  2004      4   25
4309          Leeds     Portsmouth  2004      4   25
4310      Newcastle        Chelsea  2004      4   25
4311      Tottenham        Arsenal  2004      4   25
4312     Portsmouth         Fulham  2004      5    1
4313         Wolves        Everton  2004      5    1
4314        Chelsea    Southampton  2004      5    1
4315       Charlton      Leicester  2004      5    1
4316        Arsenal     Birmingham  2004      5    1
4317       Man City      Newcastle  2004      5    1
4318      Blackburn     Man United  2004      5    1
4319    Aston Villa      Tottenham  2004      5    2
4320         Bolton          Leeds  2004      5    2
4321      Liverpool  Middlesbrough  2004      5    2
4322     Portsmouth        Arsenal  2004      5    4
4323     Birmingham      Liverpool  2004      5    8
4324        Everton         Bolton  2004      5    8
4325          Leeds       Charlton  2004      5    8
4326      Leicester     Portsmouth  2004      5    8
4327     Man United        Chelsea  2004      5    8
4328  Middlesbrough       Man City  2004      5    8
4329    Southampton    Aston Villa  2004      5    8
4330      Tottenham      Blackburn  2004      5    8
4331      Newcastle         Wolves  2004      5    9
4332         Fulham        Arsenal  2004      5    9
4333    Southampton      Newcastle  2004      5   12
4334        Arsenal      Leicester  2004      5   15
4335    Aston Villa     Man United  2004      5   15
4336      Blackburn     Birmingham  2004      5   15
4337         Bolton         Fulham  2004      5   15
4338       Charlton    Southampton  2004      5   15
4339        Chelsea          Leeds  2004      5   15
4340      Liverpool      Newcastle  2004      5   15
4341       Man City        Everton  2004      5   15
4342     Portsmouth  Middlesbrough  2004      5   15
4343         Wolves      Tottenham  2004      5   15

In [28]:
match_data = {
    # ==================== 11 January 2004 - Matchweek 21 (تکمیل) ====================
    ('Leicester', 'Chelsea'):        {'Round': 21, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},

    # ==================== 8 February 2004 - Matchweek 24 (تکمیل) ====================
    ('Chelsea', 'Charlton'):         {'Round': 24, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},

    # ==================== 3 April 2004 - Matchweek 31 ====================
    ('Middlesbrough', 'Bolton'):     {'Round': 31, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 30104},   # Source: FBref[reference:0][reference:1]
    ('Newcastle', 'Everton'):        {'Round': 31, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 52155},   # Source: FBref[reference:2][reference:3]
    ('Tottenham', 'Chelsea'):        {'Round': 31, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Wolves', 'Southampton'):       {'Round': 31, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Fulham', 'Birmingham'):        {'Round': 31, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 14667},   # Source: FBref[reference:4]
    ('Aston Villa', 'Man City'):     {'Round': 31, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': 37602},   # Source: FBref[reference:5]
    ('Liverpool', 'Blackburn'):      {'Round': 31, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': 41559},   # Source: FBref[reference:6]
    ('Leeds', 'Leicester'):          {'Round': 31, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},

    # ==================== 9-10 April 2004 - Matchweek 32 ====================
    ('Arsenal', 'Liverpool'):        {'Round': 32, 'WeekDay': 'Fri', 'Time': '20:00', 'Attendance': None},
    ('Everton', 'Tottenham'):        {'Round': 32, 'WeekDay': 'Fri', 'Time': '20:00', 'Attendance': None},
    ('Blackburn', 'Leeds'):          {'Round': 32, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Man City', 'Wolves'):          {'Round': 32, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 47248},   # Source: FBref[reference:7]
    ('Leicester', 'Fulham'):         {'Round': 32, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 28392},   # Source: namu.wiki[reference:8]
    ('Birmingham', 'Man United'):    {'Round': 32, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 29548},   # Source: namu.wiki[reference:9]
    ('Charlton', 'Portsmouth'):      {'Round': 32, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Bolton', 'Aston Villa'):       {'Round': 32, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Chelsea', 'Middlesbrough'):    {'Round': 32, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},

    # ==================== 11-12 April 2004 - Matchweek 33 ====================
    ('Newcastle', 'Arsenal'):        {'Round': 33, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},
    ('Aston Villa', 'Chelsea'):      {'Round': 33, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},
    ('Liverpool', 'Charlton'):       {'Round': 33, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},
    ('Middlesbrough', 'Southampton'):{'Round': 33, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},
    ('Portsmouth', 'Birmingham'):    {'Round': 33, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},
    ('Tottenham', 'Man City'):       {'Round': 33, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': 35282},   # Source: FBref[reference:10]
    ('Wolves', 'Bolton'):            {'Round': 33, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': None},
    ('Fulham', 'Blackburn'):         {'Round': 33, 'WeekDay': 'Mon', 'Time': '20:00', 'Attendance': 13981},   # Source: Wikipedia[reference:11][reference:12]
    ('Leeds', 'Everton'):            {'Round': 33, 'WeekDay': 'Tue', 'Time': '19:45', 'Attendance': 39835},   # Source: Wikipedia[reference:13]
    ('Man United', 'Leicester'):     {'Round': 33, 'WeekDay': 'Tue', 'Time': '20:00', 'Attendance': None},

    # ==================== 16 April 2004 - Matchweek 34 ====================
    ('Arsenal', 'Leeds'):            {'Round': 34, 'WeekDay': 'Fri', 'Time': '20:00', 'Attendance': None},

    # ==================== 17-18 April 2004 - Matchweek 34 ====================
    ('Charlton', 'Birmingham'):      {'Round': 34, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Bolton', 'Tottenham'):         {'Round': 34, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Wolves', 'Middlesbrough'):     {'Round': 34, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Portsmouth', 'Man United'):    {'Round': 34, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Blackburn', 'Leicester'):      {'Round': 34, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Liverpool', 'Fulham'):         {'Round': 34, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Chelsea', 'Everton'):          {'Round': 34, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Man City', 'Southampton'):     {'Round': 34, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 47152},   # Source: FBref[reference:14]
    ('Aston Villa', 'Newcastle'):    {'Round': 34, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},

    # ==================== 20 April 2004 - Matchweek 35 ====================
    ('Man United', 'Charlton'):      {'Round': 35, 'WeekDay': 'Tue', 'Time': '20:00', 'Attendance': None},

    # ==================== 24-25 April 2004 - Matchweek 35 ====================
    ('Everton', 'Blackburn'):        {'Round': 35, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Fulham', 'Charlton'):          {'Round': 35, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Leicester', 'Man City'):       {'Round': 35, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 31457},   # Source: FBref[reference:15]
    ('Man United', 'Liverpool'):     {'Round': 35, 'WeekDay': 'Sat', 'Time': '12:30', 'Attendance': None},
    ('Middlesbrough', 'Aston Villa'):{'Round': 35, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Southampton', 'Bolton'):       {'Round': 35, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Birmingham', 'Wolves'):        {'Round': 35, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},
    ('Leeds', 'Portsmouth'):         {'Round': 35, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},
    ('Newcastle', 'Chelsea'):        {'Round': 35, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},
    ('Tottenham', 'Arsenal'):        {'Round': 35, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},

    # ==================== 1-2 May 2004 - Matchweek 36 ====================
    ('Portsmouth', 'Fulham'):        {'Round': 36, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Wolves', 'Everton'):           {'Round': 36, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Chelsea', 'Southampton'):      {'Round': 36, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Charlton', 'Leicester'):       {'Round': 36, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Arsenal', 'Birmingham'):       {'Round': 36, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Man City', 'Newcastle'):       {'Round': 36, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 47266},   # Source: FBref[reference:16]
    ('Blackburn', 'Man United'):     {'Round': 36, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Aston Villa', 'Tottenham'):    {'Round': 36, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': 42573},   # Source: FBref[reference:17]
    ('Bolton', 'Leeds'):             {'Round': 36, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},
    ('Liverpool', 'Middlesbrough'):  {'Round': 36, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},

    # ==================== 4 May 2004 - Matchweek 37 ====================
    ('Portsmouth', 'Arsenal'):       {'Round': 37, 'WeekDay': 'Tue', 'Time': '20:00', 'Attendance': None},

    # ==================== 8-9 May 2004 - Matchweek 37 ====================
    ('Birmingham', 'Liverpool'):     {'Round': 37, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Everton', 'Bolton'):           {'Round': 37, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Leeds', 'Charlton'):           {'Round': 37, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Leicester', 'Portsmouth'):     {'Round': 37, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Man United', 'Chelsea'):       {'Round': 37, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Middlesbrough', 'Man City'):   {'Round': 37, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 34734},   # Source: FBref[reference:18]
    ('Southampton', 'Aston Villa'):  {'Round': 37, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Tottenham', 'Blackburn'):      {'Round': 37, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Newcastle', 'Wolves'):         {'Round': 37, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},
    ('Fulham', 'Arsenal'):           {'Round': 37, 'WeekDay': 'Sun', 'Time': '16:00', 'Attendance': None},

    # ==================== 12 May 2004 - Matchweek 38 ====================
    ('Southampton', 'Newcastle'):    {'Round': 38, 'WeekDay': 'Wed', 'Time': '20:00', 'Attendance': None},

    # ==================== 15 May 2004 - Matchweek 38 ====================
    ('Arsenal', 'Leicester'):        {'Round': 38, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Aston Villa', 'Man United'):   {'Round': 38, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Blackburn', 'Birmingham'):     {'Round': 38, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Bolton', 'Fulham'):            {'Round': 38, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Charlton', 'Southampton'):     {'Round': 38, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Chelsea', 'Leeds'):            {'Round': 38, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Liverpool', 'Newcastle'):      {'Round': 38, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Man City', 'Everton'):         {'Round': 38, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': 47152},   # Source: FBref[reference:19]
    ('Portsmouth', 'Middlesbrough'): {'Round': 38, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
    ('Wolves', 'Tottenham'):         {'Round': 38, 'WeekDay': 'Sat', 'Time': '15:00', 'Attendance': None},
}
fill_from_dict(
    df,
    season="0304",
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [30]:
null_rows(df, "0304", 'Attendance')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
4049        Everton    Southampton  2003     10   19
4050     Birmingham    Aston Villa  2003     10   19
4051      Leicester      Tottenham  2003     10   19
4052      Blackburn       Charlton  2003     10   20
4053         Fulham      Newcastle  2003     10   21
4054    Aston Villa        Everton  2003     10   25
4055         Bolton     Birmingham  2003     10   25
4056      Liverpool          Leeds  2003     10   25
4057     Man United         Fulham  2003     10   25
4058      Newcastle     Portsmouth  2003     10   25
4059    Southampton      Blackburn  2003     10   25
4060         Wolves      Leicester  2003     10   25
4061        Chelsea       Man City  2003     10   25
4062      Tottenham  Middlesbrough  2003     10   26
4063       Charlton        Arsenal  2003     10   26
4065        Everton        Chelsea  2003     11    1
4066      Tottenham         Bolton  2003     11    1
4067          Leeds        Arsenal  2003     11    1
4068    Southampton       Man City  2003     11    1
4069      Newcastle    Aston Villa  2003     11    1
4070  Middlesbrough         Wolves  2003     11    1
4071         Fulham      Liverpool  2003     11    2
4072      Leicester      Blackburn  2003     11    2
4073     Birmingham       Charlton  2003     11    3
4074    Aston Villa  Middlesbrough  2003     11    8
4075         Wolves     Birmingham  2003     11    8
4076        Arsenal      Tottenham  2003     11    8
4077     Portsmouth          Leeds  2003     11    8
4078         Bolton    Southampton  2003     11    8
4079       Charlton         Fulham  2003     11    8
4080        Chelsea      Newcastle  2003     11    9
4081       Man City      Leicester  2003     11    9
4082      Liverpool     Man United  2003     11    9
4083      Blackburn        Everton  2003     11   10
4084     Birmingham        Arsenal  2003     11   22
4085        Everton         Wolves  2003     11   22
4086          Leeds         Bolton  2003     11   22
4087      Leicester       Charlton  2003     11   22
4088  Middlesbrough      Liverpool  2003     11   22
4089      Newcastle       Man City  2003     11   22
4090    Southampton        Chelsea  2003     11   22
4091     Man United      Blackburn  2003     11   22
4092      Tottenham    Aston Villa  2003     11   23
4094         Wolves      Newcastle  2003     11   29
4095       Charlton          Leeds  2003     11   29
4096         Bolton        Everton  2003     11   29
4097      Blackburn      Tottenham  2003     11   29
4098     Portsmouth      Leicester  2003     11   29
4099    Aston Villa    Southampton  2003     11   29
4100        Arsenal         Fulham  2003     11   30
4101        Chelsea     Man United  2003     11   30
4102      Liverpool     Birmingham  2003     11   30
4103       Man City  Middlesbrough  2003     11   30
4104     Birmingham      Blackburn  2003     12    6
4105         Fulham         Bolton  2003     12    6
4106          Leeds        Chelsea  2003     12    6
4107      Leicester        Arsenal  2003     12    6
4108     Man United    Aston Villa  2003     12    6
4109  Middlesbrough     Portsmouth  2003     12    6
4110      Newcastle      Liverpool  2003     12    6
4111      Tottenham         Wolves  2003     12    6
4112        Everton       Man City  2003     12    7
4113    Southampton       Charlton  2003     12    7
4114      Liverpool    Southampton  2003     12   13
4115      Leicester     Birmingham  2003     12   13
4116     Portsmouth        Everton  2003     12   13
4117        Chelsea         Bolton  2003     12   13
4118      Newcastle      Tottenham  2003     12   13
4119  Middlesbrough       Charlton  2003     12   13
4120     Man United       Man City  2003     12   13
4121        Arsenal      Blackburn  2003     12   14
4122          Leeds         Fulham  2003     12   14
4123    Aston Villa         Wolves  2003     12   14
4124         Bolton        Arsenal  2003     12   20
4125       Charlton      Newcastle  2003     12   20
4126        Everton      Leicester  2003     12   20
4127         Fulham        Chelsea  2003     12   20
4128      Blackburn    Aston Villa  2003     12   20
4129      Tottenham     Man United  2003     12   21
4130    Southampton     Portsmouth  2003     12   21
4131       Man City          Leeds  2003     12   22
4132      Liverpool         Bolton  2003     12   26
4133     Portsmouth      Tottenham  2003     12   26
4134     Man United        Everton  2003     12   26
4135          Leeds    Aston Villa  2003     12   26
4136         Fulham    Southampton  2003     12   26
4137       Charlton        Chelsea  2003     12   26
4138     Birmingham       Man City  2003     12   26
4139        Arsenal         Wolves  2003     12   26
4140      Leicester      Newcastle  2003     12   26
4141      Blackburn  Middlesbrough  2003     12   26
4142    Aston Villa         Fulham  2003     12   28
4143         Bolton      Leicester  2003     12   28
4144        Chelsea     Portsmouth  2003     12   28
4145        Everton     Birmingham  2003     12   28
4146       Man City      Liverpool  2003     12   28
4147  Middlesbrough     Man United  2003     12   28
4148      Newcastle      Blackburn  2003     12   28
4149      Tottenham       Charlton  2003     12   28
4150         Wolves          Leeds  2003     12   28

In [32]:
attendance_data = {
    # ==================== 19-21 October 2003 - Matchweek 9 ====================
    ('Everton', 'Southampton'): 35775,      # Source: FBref[reference:0][reference:1]
    ('Birmingham', 'Aston Villa'): 29546,   # Source: FBref[reference:2][reference:3]
    ('Leicester', 'Tottenham'): 31521,      # Source: FBref[reference:4][reference:5]
    ('Blackburn', 'Charlton'): 19939,       # Source: FBref[reference:6][reference:7]
    ('Fulham', 'Newcastle'): 15241,         # Source: FBref[reference:8] (Note: ESPN reported 16,506[reference:9], FBref reports 15,241)

    # ==================== 25-26 October 2003 - Matchweek 10 ====================
    ('Aston Villa', 'Everton'): 36146,      # Source: FBref[reference:10]
    ('Bolton', 'Birmingham'): 25023,        # Source: FBref[reference:11]
    ('Liverpool', 'Leeds'): 43599,          # Source: FBref[reference:12]
    ('Man United', 'Fulham'): 67727,        # Source: FBref[reference:13]
    ('Newcastle', 'Portsmouth'): 52161,     # Source: FBref[reference:14]
    ('Southampton', 'Blackburn'): 31620,    # Source: FBref[reference:15]
    ('Wolves', 'Leicester'): 28578,         # Source: FBref[reference:16]
    ('Chelsea', 'Man City'): 41143,         # Source: FBref[reference:17]
    ('Tottenham', 'Middlesbrough'): 32641,  # Source: FBref[reference:18][reference:19]
    ('Charlton', 'Arsenal'): 26639,         # Source: FBref[reference:20]

    # ==================== 1-3 November 2003 - Matchweek 11 ====================
    ('Everton', 'Chelsea'): 40189,          # Source: FBref[reference:21]
    ('Tottenham', 'Bolton'): 35191,         # Source: FBref[reference:22][reference:23]
    ('Leeds', 'Arsenal'): 36491,            # Source: FBref[reference:24]
    ('Southampton', 'Man City'): 31952,     # Source: FBref[reference:25]
    ('Newcastle', 'Aston Villa'): 51975,    # Source: FBref[reference:26]
    ('Middlesbrough', 'Wolves'): 30303,     # Source: FBref[reference:27]
    ('Man United', 'Portsmouth'): 67639,    # Source: FBref[reference:28]
    ('Fulham', 'Liverpool'): 17682,         # Source: FBref[reference:29]
    ('Leicester', 'Blackburn'): 30975,      # Source: FBref[reference:30]
    ('Birmingham', 'Charlton'): 27225,      # Source: FBref[reference:31]

    # ==================== 8-10 November 2003 - Matchweek 12 ====================
    ('Aston Villa', 'Middlesbrough'): 29898, # Source: FBref[reference:32]
    ('Wolves', 'Birmingham'): 28831,        # Source: FBref[reference:33]
    ('Arsenal', 'Tottenham'): 38101,        # Source: FBref[reference:34][reference:35]
    ('Portsmouth', 'Leeds'): 20122,         # Source: FBref[reference:36]
    ('Bolton', 'Southampton'): 25619,       # Source: FBref[reference:37]
    ('Charlton', 'Fulham'): 26285,          # Source: FBref[reference:38]
    ('Chelsea', 'Newcastle'): 41322,        # Source: FBref[reference:39]
    ('Man City', 'Leicester'): 46966,       # Source: FBref[reference:40]
    ('Liverpool', 'Man United'): 44159,     # Source: FBref[reference:41]
    ('Blackburn', 'Everton'): 22179,        # Source: FBref[reference:42]

    # ==================== 22-24 November 2003 - Matchweek 13 ====================
    ('Birmingham', 'Arsenal'): 29588,       # Source: FBref[reference:43]
    ('Everton', 'Wolves'): 40190,           # Source: FBref[reference:44]
    ('Leeds', 'Bolton'): 36558,             # Source: FBref[reference:45]
    ('Leicester', 'Charlton'): 30242,       # Source: FBref[reference:46]
    ('Middlesbrough', 'Liverpool'): 34268,  # Source: FBref[reference:47]
    ('Newcastle', 'Man City'): 52159,       # Source: FBref[reference:48]
    ('Southampton', 'Chelsea'): 32149,      # Source: FBref[reference:49]
    ('Man United', 'Blackburn'): 67748,     # Source: FBref[reference:50]
    ('Tottenham', 'Aston Villa'): 33140,    # Source: FBref[reference:51]
    ('Fulham', 'Portsmouth'): 15624,        # Source: FBref[reference:52]

    # ==================== 29-30 November 2003 - Matchweek 14 ====================
    ('Wolves', 'Newcastle'): 29344,         # Source: FBref[reference:53]
    ('Charlton', 'Leeds'): 26425,           # Source: FBref[reference:54]
    ('Bolton', 'Everton'): 27350,           # Source: FBref[reference:55]
    ('Blackburn', 'Tottenham'): 22802,      # Source: FBref[reference:56]
    ('Portsmouth', 'Leicester'): 20140,     # Source: FBref[reference:57]
    ('Aston Villa', 'Southampton'): 31285,  # Source: FBref[reference:58]
    ('Arsenal', 'Fulham'): 38063,           # Source: FBref[reference:59]
    ('Chelsea', 'Man United'): 41932,       # Source: FBref[reference:60]
    ('Liverpool', 'Birmingham'): 42683,     # Source: FBref[reference:61]
    ('Man City', 'Middlesbrough'): 46824,   # Source: FBref[reference:62]

    # ==================== 6-7 December 2003 - Matchweek 15 ====================
    ('Birmingham', 'Blackburn'): 29359,     # Source: FBref[reference:63]
    ('Fulham', 'Bolton'): 14393,            # Source: FBref[reference:64]
    ('Leeds', 'Chelsea'): 36305,            # Source: FBref[reference:65]
    ('Leicester', 'Arsenal'): 32108,        # Source: FBref[reference:66]
    ('Man United', 'Aston Villa'): 67621,   # Source: FBref[reference:67]
    ('Middlesbrough', 'Portsmouth'): 28083, # Source: FBref[reference:68]
    ('Newcastle', 'Liverpool'): 52151,      # Source: FBref[reference:69]
    ('Tottenham', 'Wolves'): 34820,         # Source: FBref[reference:70]
    ('Everton', 'Man City'): 37871,         # Source: FBref[reference:71]
    ('Southampton', 'Charlton'): 30513,     # Source: FBref[reference:72]

    # ==================== 13-14 December 2003 - Matchweek 16 ====================
    ('Liverpool', 'Southampton'): 41762,    # Source: FBref[reference:73]
    ('Leicester', 'Birmingham'): 30639,     # Source: FBref[reference:74]
    ('Portsmouth', 'Everton'): 20099,       # Source: FBref[reference:75]
    ('Chelsea', 'Bolton'): 40491,           # Source: FBref[reference:76]
    ('Newcastle', 'Tottenham'): 52138,      # Source: FBref[reference:77]
    ('Middlesbrough', 'Charlton'): 26721,   # Source: FBref[reference:78]
    ('Man United', 'Man City'): 67643,      # Source: FBref[reference:79]
    ('Arsenal', 'Blackburn'): 37677,        # Source: FBref[reference:80]
    ('Leeds', 'Fulham'): 30544,             # Source: FBref[reference:81]
    ('Aston Villa', 'Wolves'): 36964,       # Source: FBref[reference:82]

    # ==================== 20-22 December 2003 - Matchweek 17 ====================
    ('Bolton', 'Arsenal'): 27492,           # Source: FBref[reference:83]
    ('Charlton', 'Newcastle'): 26469,       # Source: FBref[reference:84]
    ('Everton', 'Leicester'): 37007,        # Source: FBref[reference:85]
    ('Fulham', 'Chelsea'): 18431,           # Source: FBref[reference:86]
    ('Blackburn', 'Aston Villa'): 20722,    # Source: FBref[reference:87]
    ('Tottenham', 'Man United'): 35910,     # Source: FBref[reference:88]
    ('Southampton', 'Portsmouth'): 31697,   # Source: FBref[reference:89]
    ('Man City', 'Leeds'): 47126,           # Source: FBref[reference:90]

    # ==================== 26 December 2003 - Matchweek 18 ====================
    ('Liverpool', 'Bolton'): None,          # Source: Not found in FBref schedule
    ('Portsmouth', 'Tottenham'): None,      # Source: Not found in FBref schedule
    ('Man United', 'Everton'): 67642,       # Source: FBref[reference:91]
    ('Leeds', 'Aston Villa'): 38513,        # Source: FBref[reference:92]
    ('Fulham', 'Southampton'): None,        # Source: Not found in FBref schedule
    ('Charlton', 'Chelsea'): None,          # Source: Not found in FBref schedule
    ('Birmingham', 'Man City'): 29520,      # Source: FBref[reference:93]
    ('Arsenal', 'Wolves'): 38003,           # Source: FBref[reference:94]
    ('Leicester', 'Newcastle'): 32148,      # Source: FBref[reference:95]
    ('Blackburn', 'Middlesbrough'): None,   # Source: Not found in FBref schedule

    # ==================== 28-29 December 2003 - Matchweek 19 ====================
    ('Aston Villa', 'Fulham'): None,        # Source: Not found in FBref schedule
    ('Bolton', 'Leicester'): None,          # Source: Not found in FBref schedule
    ('Chelsea', 'Portsmouth'): None,        # Source: Not found in FBref schedule
    ('Everton', 'Birmingham'): None,        # Source: Not found in FBref schedule
    ('Man City', 'Liverpool'): None,        # Source: Not found in FBref schedule
    ('Middlesbrough', 'Man United'): None,  # Source: Not found in FBref schedule
    ('Newcastle', 'Blackburn'): None,       # Source: Not found in FBref schedule
    ('Tottenham', 'Charlton'): None,        # Source: Not found in FBref schedule
    ('Wolves', 'Leeds'): None,              # Source: Not found in FBref schedule
    ('Southampton', 'Arsenal'): None,       # Source: Not found in FBref schedule
}

fill_from_dict(
    df,
    season="0304",
    data=attendance_data,
    value_col=['Attendance'],
    inplace=True
)

In [34]:
null_rows(df, "0304", 'Attendance')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
4132      Liverpool         Bolton  2003     12   26
4133     Portsmouth      Tottenham  2003     12   26
4136         Fulham    Southampton  2003     12   26
4137       Charlton        Chelsea  2003     12   26
4141      Blackburn  Middlesbrough  2003     12   26
4142    Aston Villa         Fulham  2003     12   28
4143         Bolton      Leicester  2003     12   28
4144        Chelsea     Portsmouth  2003     12   28
4145        Everton     Birmingham  2003     12   28
4146       Man City      Liverpool  2003     12   28
4147  Middlesbrough     Man United  2003     12   28
4148      Newcastle      Blackburn  2003     12   28
4149      Tottenham       Charlton  2003     12   28
4150         Wolves          Leeds  2003     12   28
4151    Southampton        Arsenal  2003     12   29
4152    Aston Villa     Portsmouth  2004      1    6
4153        Everton        Arsenal  2004      1    7
4154         Bolton     Man United  2004      1    7
4155         Wolves      Blackburn  2004      1    7
4156      Tottenham     Birmingham  2004      1    7
4157        Chelsea      Liverpool  2004      1    7
4158      Newcastle          Leeds  2004      1    7
4159  Middlesbrough         Fulham  2004      1    7
4160    Southampton      Leicester  2004      1    7
4161       Man City       Charlton  2004      1    7
4162       Charlton         Wolves  2004      1   10
4163         Fulham        Everton  2004      1   10
4165      Liverpool    Aston Villa  2004      1   10
4166     Portsmouth       Man City  2004      1   10
4168     Birmingham    Southampton  2004      1   10
4169      Blackburn         Bolton  2004      1   10
4171      Leicester        Chelsea  2004      1   11
4174    Southampton          Leeds  2004      1   17
4175      Tottenham      Liverpool  2004      1   17
4176         Wolves     Man United  2004      1   17
4177         Bolton     Portsmouth  2004      1   17
4178        Everton       Charlton  2004      1   17
4179    Aston Villa        Arsenal  2004      1   18
4180        Chelsea     Birmingham  2004      1   18
4181      Newcastle         Fulham  2004      1   19
4182         Wolves      Liverpool  2004      1   21
4184       Charlton         Bolton  2004      1   31
4185         Fulham      Tottenham  2004      1   31
4186          Leeds  Middlesbrough  2004      1   31
4187      Leicester    Aston Villa  2004      1   31
4188      Liverpool        Everton  2004      1   31
4189     Man United    Southampton  2004      1   31
4190     Portsmouth         Wolves  2004      1   31
4192      Blackburn        Chelsea  2004      2    1
4194    Southampton         Fulham  2004      2    7
4195      Tottenham     Portsmouth  2004      2    7
4196        Everton     Man United  2004      2    7
4197    Aston Villa          Leeds  2004      2    7
4198      Newcastle      Leicester  2004      2    7
4199  Middlesbrough      Blackburn  2004      2    7
4200         Bolton      Liverpool  2004      2    7
4201       Man City     Birmingham  2004      2    8
4202        Chelsea       Charlton  2004      2    8
4203        Arsenal    Southampton  2004      2   10
4204          Leeds         Wolves  2004      2   10
4205      Leicester         Bolton  2004      2   10
4206     Birmingham        Everton  2004      2   11
4207      Blackburn      Newcastle  2004      2   11
4208       Charlton      Tottenham  2004      2   11
4209         Fulham    Aston Villa  2004      2   11
4210      Liverpool       Man City  2004      2   11
4211     Man United  Middlesbrough  2004      2   11
4212     Portsmouth        Chelsea  2004      2   11
4213         Wolves         Fulham  2004      2   21
4214    Southampton        Everton  2004      2   21
4215     Man United          Leeds  2004      2   21
4217       Charlton      Blackburn  2004      2   21
4218         Bolton       Man City  2004      2   21
4219      Newcastle  Middlesbrough  2004      2   21
4220    Aston Villa     Birmingham  2004      2   22
4221      Tottenham      Leicester  2004      2   22
4222        Everton    Aston Villa  2004      2   28
4223         Fulham     Man United  2004      2   28
4224      Leicester         Wolves  2004      2   28
4226      Blackburn    Southampton  2004      2   28
4227       Man City        Chelsea  2004      2   28
4228          Leeds      Liverpool  2004      2   29
4229     Portsmouth      Newcastle  2004      2   29
4230     Birmingham  Middlesbrough  2004      3    3
4231     Birmingham         Bolton  2004      3    6
4232  Middlesbrough      Tottenham  2004      3    9
4233     Birmingham      Leicester  2004      3   13
4234      Blackburn        Arsenal  2004      3   13
4235         Bolton        Chelsea  2004      3   13
4236         Fulham          Leeds  2004      3   13
4237       Charlton  Middlesbrough  2004      3   13
4238        Everton     Portsmouth  2004      3   13
4239      Tottenham      Newcastle  2004      3   14
4240    Southampton      Liverpool  2004      3   14
4241       Man City     Man United  2004      3   14
4242         Wolves    Aston Villa  2004      3   14
4243      Liverpool     Portsmouth  2004      3   17
4244      Newcastle       Charlton  2004      3   20
4245  Middlesbrough     Birmingham  2004      3   20
4246     Man United      Tottenham  2004      3   20

In [ ]:
attendance_data = {
    # ==================== 26 December 2003 - Matchweek 18 ====================
    ('Liverpool', 'Bolton'): 42987,          # Source: LFChistory[reference:0]
    ('Portsmouth', 'Tottenham'): 20078,      # Source: ESPN[reference:1]
    ('Fulham', 'Southampton'): 16767,        # Source: ESPN[reference:2]
    ('Charlton', 'Chelsea'): 26768,          # Source: ESPN[reference:3]
    ('Blackburn', 'Middlesbrough'): 25452,   # Source: ESPN[reference:4]

    # ==================== 28 December 2003 - Matchweek 19 ====================
    ('Aston Villa', 'Fulham'): 35617,        # Source: ESPN[reference:5]
    ('Bolton', 'Leicester'): 28353,          # Source: ESPN[reference:6]
    ('Chelsea', 'Portsmouth'): 41552,        # Source: ESPN[reference:7]
    ('Everton', 'Birmingham'): 39631,        # Source: Sky Sports[reference:8]
    ('Man City', 'Liverpool'): 47201,        # Source: ESPN[reference:9]
    ('Middlesbrough', 'Man United'): 34738,  # Source: Sky Sports[reference:10]
    ('Newcastle', 'Blackburn'): 51648,       # Source: Sky Sports[reference:11]
    ('Tottenham', 'Charlton'): 34534,        # Source: ESPN[reference:12]
    ('Wolves', 'Leeds'): 29139,              # Source: Sky Sports[reference:13]

    # ==================== 29 December 2003 - Matchweek 19 ====================
    ('Southampton', 'Arsenal'): 32151,       # Source: FBref[reference:14]

    # ==================== 6 January 2004 - Matchweek 20 ====================
    ('Aston Villa', 'Portsmouth'): 28625,    # Source: ESPN[reference:15]

    # ==================== 7 January 2004 - Matchweek 20 ====================
    ('Everton', 'Arsenal'): 38726,           # Source: ESPN[reference:16]
    ('Bolton', 'Man United'): 27668,         # Source: ESPN[reference:17]
    ('Wolves', 'Blackburn'): 27393,          # Source: Sky Sports[reference:18]
    ('Tottenham', 'Birmingham'): 30016,      # Source: ESPN[reference:19]
    ('Chelsea', 'Liverpool'): 41420,         # Source: ESPN[reference:20]
    ('Newcastle', 'Leeds'): 52130,           # Source: ESPN[reference:21]
    ('Middlesbrough', 'Fulham'): 27869,      # Source: ESPN[reference:22]
    ('Southampton', 'Leicester'): 31053,     # Source: ESPN[reference:23]
    ('Man City', 'Charlton'): 44307,         # Source: ESPN[reference:24]

    # ==================== 10 January 2004 - Matchweek 21 ====================
    ('Charlton', 'Wolves'): 26148,           # Source: ESPN[reference:25]
    ('Fulham', 'Everton'): 17103,            # Source: ESPN[reference:26]
    ('Liverpool', 'Aston Villa'): 43771,     # Source: LFChistory[reference:27]
    ('Portsmouth', 'Man City'): 20120,       # Source: ESPN[reference:28]
    ('Birmingham', 'Southampton'): 29071,    # Source: ESPN[reference:29]
    ('Blackburn', 'Bolton'): 23538,          # Source: 11v11.com[reference:30]

    # ==================== 11 January 2004 - Matchweek 21 ====================
    ('Leicester', 'Chelsea'): 31547,         # Source: FBref[reference:31]

    # ==================== 17 January 2004 - Matchweek 22 ====================
    ('Southampton', 'Leeds'): 31976,         # Source: ESPN[reference:32]
    ('Tottenham', 'Liverpool'): 36104,       # Source: ESPN[reference:33]
    ('Wolves', 'Man United'): 29396,         # Source: ESPN[reference:34]
    ('Bolton', 'Portsmouth'): 26558,         # Source: ESPN[reference:35]
    ('Everton', 'Charlton'): 36322,          # Source: ESPN[reference:36]

    # ==================== 18 January 2004 - Matchweek 22 ====================
    ('Aston Villa', 'Arsenal'): 39380,       # Source: ESPN[reference:37]
    ('Chelsea', 'Birmingham'): 41073,        # Source: ESPN[reference:38]

    # ==================== 19 January 2004 - Matchweek 22 ====================
    ('Newcastle', 'Fulham'): 50104,          # Source: 11v11.com[reference:39]

    # ==================== 21 January 2004 - Matchweek 17 (Rescheduled) ====================
    ('Wolves', 'Liverpool'): 29380,          # Source: LFChistory[reference:40]

    # ==================== 31 January 2004 - Matchweek 23 ====================
    ('Charlton', 'Bolton'): 26249,           # Source: ESPN[reference:41]
    ('Fulham', 'Tottenham'): None,           
    ('Leeds', 'Middlesbrough'): None,        
    ('Leicester', 'Aston Villa'): None,      
    ('Liverpool', 'Everton'): None,          
    ('Man United', 'Southampton'): None,     
    ('Portsmouth', 'Wolves'): None,          

    # ==================== 1 February 2004 - Matchweek 23 ====================
    ('Blackburn', 'Chelsea'): None,          

    # ==================== 7 February 2004 - Matchweek 24 ====================
    ('Southampton', 'Fulham'): None,         
    ('Tottenham', 'Portsmouth'): None,       
    ('Everton', 'Man United'): None,         
    ('Aston Villa', 'Leeds'): None,          
    ('Newcastle', 'Leicester'): None,        
    ('Middlesbrough', 'Blackburn'): None,    
    ('Bolton', 'Liverpool'): None,           

    # ==================== 8 February 2004 - Matchweek 24 ====================
    ('Man City', 'Birmingham'): None,        

    # ==================== 10-11 February 2004 - Matchweek 25 ====================
    ('Arsenal', 'Southampton'): None,        
    ('Leeds', 'Wolves'): None,               
    ('Leicester', 'Bolton'): None,           
    ('Birmingham', 'Everton'): None,         
    ('Blackburn', 'Newcastle'): None,        
    ('Charlton', 'Tottenham'): None,         
    ('Fulham', 'Aston Villa'): None,         
    ('Liverpool', 'Man City'): None,         
    ('Man United', 'Middlesbrough'): None,   
    ('Portsmouth', 'Chelsea'): None,         

    # ==================== 21-22 February 2004 - Matchweek 26 ====================
    ('Wolves', 'Fulham'): None,              
    ('Southampton', 'Everton'): None,        
    ('Man United', 'Leeds'): None,           
    ('Charlton', 'Blackburn'): None,         
    ('Bolton', 'Man City'): None,            
    ('Newcastle', 'Middlesbrough'): None,    
    ('Aston Villa', 'Birmingham'): None,     
    ('Tottenham', 'Leicester'): None,        

    # ==================== 28-29 February 2004 - Matchweek 27 ====================
    ('Everton', 'Aston Villa'): None,        
    ('Fulham', 'Man United'): None,          
    ('Leicester', 'Wolves'): None,           
    ('Blackburn', 'Southampton'): None,      
    ('Man City', 'Chelsea'): None,           
    ('Leeds', 'Liverpool'): None,            
    ('Portsmouth', 'Newcastle'): None,       

    # ==================== 3 March 2004 - Matchweek 25 (Rescheduled) ====================
    ('Birmingham', 'Middlesbrough'): None,   

    # ==================== 6 March 2004 - Matchweek 28 ====================
    ('Birmingham', 'Bolton'): None,          

    # ==================== 9 March 2004 - Matchweek 27 (Rescheduled) ====================
    ('Middlesbrough', 'Tottenham'): None,    

    # ==================== 13-14 March 2004 - Matchweek 28 ====================
    ('Birmingham', 'Leicester'): None,       
    ('Blackburn', 'Arsenal'): None,          
    ('Bolton', 'Chelsea'): None,             
    ('Fulham', 'Leeds'): None,               
    ('Charlton', 'Middlesbrough'): None,     
    ('Everton', 'Portsmouth'): None,         
    ('Tottenham', 'Newcastle'): None,        
    ('Southampton', 'Liverpool'): None,      
    ('Man City', 'Man United'): None,        
    ('Wolves', 'Aston Villa'): None,         

    # ==================== 17 March 2004 - Matchweek 29 ====================
    ('Liverpool', 'Portsmouth'): None,       

    # ==================== 20-22 March 2004 - Matchweek 29 ====================
    ('Newcastle', 'Charlton'): None,         
    ('Middlesbrough', 'Birmingham'): None,   
    ('Man United', 'Tottenham'): None,       
    ('Arsenal', 'Bolton'): None,             
    ('Leicester', 'Everton'): None,          
    ('Aston Villa', 'Blackburn'): None,      
    ('Liverpool', 'Wolves'): None,           
    ('Chelsea', 'Fulham'): None,             
    ('Portsmouth', 'Southampton'): None,     
    ('Leeds', 'Man City'): None,             
}

fill_from_dict(
    df,
    season="0304",
    data=attendance_data,
    value_col=['Attendance'],
    inplace=True
)

In [37]:
null_rows(df, "0304", 'Attendance')

           HomeTeam       AwayTeam  Year  Month  Day
4185         Fulham      Tottenham  2004      1   31
4186          Leeds  Middlesbrough  2004      1   31
4187      Leicester    Aston Villa  2004      1   31
4188      Liverpool        Everton  2004      1   31
4189     Man United    Southampton  2004      1   31
4190     Portsmouth         Wolves  2004      1   31
4192      Blackburn        Chelsea  2004      2    1
4194    Southampton         Fulham  2004      2    7
4195      Tottenham     Portsmouth  2004      2    7
4196        Everton     Man United  2004      2    7
4197    Aston Villa          Leeds  2004      2    7
4198      Newcastle      Leicester  2004      2    7
4199  Middlesbrough      Blackburn  2004      2    7
4200         Bolton      Liverpool  2004      2    7
4201       Man City     Birmingham  2004      2    8
4202        Chelsea       Charlton  2004      2    8
4203        Arsenal    Southampton  2004      2   10
4204          Leeds         Wolves  2004      2   10
4205      Leicester         Bolton  2004      2   10
4206     Birmingham        Everton  2004      2   11
4207      Blackburn      Newcastle  2004      2   11
4208       Charlton      Tottenham  2004      2   11
4209         Fulham    Aston Villa  2004      2   11
4210      Liverpool       Man City  2004      2   11
4211     Man United  Middlesbrough  2004      2   11
4212     Portsmouth        Chelsea  2004      2   11
4213         Wolves         Fulham  2004      2   21
4214    Southampton        Everton  2004      2   21
4215     Man United          Leeds  2004      2   21
4217       Charlton      Blackburn  2004      2   21
4218         Bolton       Man City  2004      2   21
4219      Newcastle  Middlesbrough  2004      2   21
4220    Aston Villa     Birmingham  2004      2   22
4221      Tottenham      Leicester  2004      2   22
4222        Everton    Aston Villa  2004      2   28
4223         Fulham     Man United  2004      2   28
4224      Leicester         Wolves  2004      2   28
4226      Blackburn    Southampton  2004      2   28
4227       Man City        Chelsea  2004      2   28
4228          Leeds      Liverpool  2004      2   29
4229     Portsmouth      Newcastle  2004      2   29
4230     Birmingham  Middlesbrough  2004      3    3
4231     Birmingham         Bolton  2004      3    6
4232  Middlesbrough      Tottenham  2004      3    9
4233     Birmingham      Leicester  2004      3   13
4234      Blackburn        Arsenal  2004      3   13
4235         Bolton        Chelsea  2004      3   13
4236         Fulham          Leeds  2004      3   13
4237       Charlton  Middlesbrough  2004      3   13
4238        Everton     Portsmouth  2004      3   13
4239      Tottenham      Newcastle  2004      3   14
4240    Southampton      Liverpool  2004      3   14
4241       Man City     Man United  2004      3   14
4242         Wolves    Aston Villa  2004      3   14
4243      Liverpool     Portsmouth  2004      3   17
4244      Newcastle       Charlton  2004      3   20
4245  Middlesbrough     Birmingham  2004      3   20
4246     Man United      Tottenham  2004      3   20
4247        Arsenal         Bolton  2004      3   20
4248      Leicester        Everton  2004      3   20
4249    Aston Villa      Blackburn  2004      3   20
4250      Liverpool         Wolves  2004      3   20
4251        Chelsea         Fulham  2004      3   20
4252     Portsmouth    Southampton  2004      3   21
4253          Leeds       Man City  2004      3   22
4254       Charlton    Aston Villa  2004      3   27
4255     Birmingham          Leeds  2004      3   27
4256    Southampton      Tottenham  2004      3   27
4257      Blackburn     Portsmouth  2004      3   27
4258        Everton  Middlesbrough  2004      3   27
4259        Chelsea         Wolves  2004      3   27
4260       Man City         Fulham  2004      3   27
4261        Arsenal     Man United  2004      3   28
4262         Bolton      Newcastle  2004      3   28
4263      Leicester      Liverpool  2004      3   28
4266      Tottenham        Chelsea  2004      4    3
4267         Wolves    Southampton  2004      4    3
4271          Leeds      Leicester  2004      4    5
4272        Arsenal      Liverpool  2004      4    9
4273        Everton      Tottenham  2004      4    9
4274      Blackburn          Leeds  2004      4   10
4278       Charlton     Portsmouth  2004      4   10
4279         Bolton    Aston Villa  2004      4   10
4280        Chelsea  Middlesbrough  2004      4   10
4281      Newcastle        Arsenal  2004      4   11
4282    Aston Villa        Chelsea  2004      4   12
4283      Liverpool       Charlton  2004      4   12
4284  Middlesbrough    Southampton  2004      4   12
4285     Portsmouth     Birmingham  2004      4   12
4287         Wolves         Bolton  2004      4   12
4290     Man United      Leicester  2004      4   13
4291        Arsenal          Leeds  2004      4   16
4292       Charlton     Birmingham  2004      4   17
4293         Bolton      Tottenham  2004      4   17
4294         Wolves  Middlesbrough  2004      4   17
4295     Portsmouth     Man United  2004      4   17
4296      Blackburn      Leicester  2004      4   17
4297      Liverpool         Fulham  2004      4   17
4298        Chelsea        Everton  2004      4   17
4300    Aston Villa      Newcastle  2004      4   18
4301     Man United       Charlton  2004      4   20
4302        Everton      Blackburn  2004      4   24
4303         Fulham       Charlton  2004      4   24
4305     Man United      Liverpool  2004      4   24
4306  Middlesbrough    Aston Villa  2004      4   24
4307    Southampton         Bolton  2004      4   24
4308     Birmingham         Wolves  2004      4   25
4309          Leeds     Portsmouth  2004      4   25
4310      Newcastle        Chelsea  2004      4   25
4311      Tottenham        Arsenal  2004      4   25
4312     Portsmouth         Fulham  2004      5    1
4313         Wolves        Everton  2004      5    1
4314        Chelsea    Southampton  2004      5    1
4315       Charlton      Leicester  2004      5    1
4316        Arsenal     Birmingham  2004      5    1
4318      Blackburn     Man United  2004      5    1
4320         Bolton          Leeds  2004      5    2
4321      Liverpool  Middlesbrough  2004      5    2
4322     Portsmouth        Arsenal  2004      5    4
4323     Birmingham      Liverpool  2004      5    8
4324        Everton         Bolton  2004      5    8
4325          Leeds       Charlton  2004      5    8
4326      Leicester     Portsmouth  2004      5    8
4327     Man United        Chelsea  2004      5    8
4329    Southampton    Aston Villa  2004      5    8
4330      Tottenham      Blackburn  2004      5    8
4331      Newcastle         Wolves  2004      5    9
4332         Fulham        Arsenal  2004      5    9
4333    Southampton      Newcastle  2004      5   12
4334        Arsenal      Leicester  2004      5   15
4335    Aston Villa     Man United  2004      5   15
4336      Blackburn     Birmingham  2004      5   15
4337         Bolton         Fulham  2004      5   15
4338       Charlton    Southampton  2004      5   15
4339        Chelsea          Leeds  2004      5   15
4340      Liverpool      Newcastle  2004      5   15
4342     Portsmouth  Middlesbrough  2004      5   15
4343         Wolves      Tottenham  2004      5   15

In [38]:
attendance_data = {
    # ==================== 31 January 2004 - Matchweek 23 ====================
    ('Fulham', 'Tottenham'): 17024,          # Source: ESPN[reference:87]
    ('Leeds', 'Middlesbrough'): 35970,       # Source: ESPN[reference:88]
    ('Leicester', 'Aston Villa'): 31056,     # Source: ESPN[reference:89]
    ('Liverpool', 'Everton'): 44056,         # Source: ESPN[reference:90]
    ('Man United', 'Southampton'): 67758,    # Source: ESPN[reference:91]
    ('Portsmouth', 'Wolves'): 20112,         # Source: Sky Sports[reference:92]

    # ==================== 1 February 2004 - Matchweek 23 ====================
    ('Blackburn', 'Chelsea'): 24867,         # Source: ESPN[reference:93]

    # ==================== 7 February 2004 - Matchweek 24 ====================
    ('Southampton', 'Fulham'): 31820,        # Source: ESPN[reference:94]
    ('Tottenham', 'Portsmouth'): 36107,      # Source: 11v11.com[reference:95]
    ('Everton', 'Man United'): 40190,        # Source: ESPN[reference:96]
    ('Aston Villa', 'Leeds'): 39171,         # Source: ESPN[reference:97]
    ('Newcastle', 'Leicester'): 52125,       # Source: ESPN[reference:98]
    ('Middlesbrough', 'Blackburn'): 28307,   # Source: ESPN[reference:99]
    ('Bolton', 'Liverpool'): 27552,          # Source: ESPN[reference:100]

    # ==================== 8 February 2004 - Matchweek 24 ====================
    ('Man City', 'Birmingham'): 46967,       # Source: ESPN[reference:101]

    # ==================== 8 February 2004 - Matchweek 24 ====================
    ('Chelsea', 'Charlton'): 41255,          # Source: 11v11.com[reference:102]

    # ==================== 10 February 2004 - Matchweek 25 ====================
    ('Arsenal', 'Southampton'): 38007,       # Source: Sky Sports[reference:103]
    ('Leeds', 'Wolves'): 36867,              # Source: FBref[reference:104]
    ('Leicester', 'Bolton'): 26674,          # Source: 11v11.com[reference:105]

    # ==================== 11 February 2004 - Matchweek 25 ====================
    ('Birmingham', 'Everton'): 29004,        # Source: ESPN[reference:106]
    ('Blackburn', 'Newcastle'): 23459,       # Source: ESPN[reference:107]
    ('Charlton', 'Tottenham'): 26660,        # Source: ESPN[reference:108]
    ('Fulham', 'Aston Villa'): 16153,        # Source: ESPN[reference:109]
    ('Liverpool', 'Man City'): 43257,        # Source: 11v11.com[reference:110]
    ('Man United', 'Middlesbrough'): 67346,  # Source: ESPN[reference:111]
    ('Portsmouth', 'Chelsea'): 20140,        # Source: ESPN[reference:112]

    # ==================== 21 February 2004 - Matchweek 26 ====================
    ('Wolves', 'Fulham'): 28424,             # Source: Global Sports Archive[reference:113]
    ('Southampton', 'Everton'): 31875,       # Source: ESPN[reference:114]
    ('Man United', 'Leeds'): 67744,          # Source: ESPN[reference:115]
    ('Charlton', 'Blackburn'): 26322,        # Source: FBref[reference:116]
    ('Bolton', 'Man City'): 27301,           # Source: ESPN[reference:117]
    ('Newcastle', 'Middlesbrough'): 52156,   # Source: Global Sports Archive[reference:118]

    # ==================== 22 February 2004 - Matchweek 26 ====================
    ('Aston Villa', 'Birmingham'): 40061,    # Source: ESPN[reference:119]
    ('Tottenham', 'Leicester'): 35218,       # Source: ESPN[reference:120]

    # ==================== 28 February 2004 - Matchweek 27 ====================
    ('Everton', 'Aston Villa'): 39353,       # Source: ESPN[reference:121]
    ('Fulham', 'Man United'): 18306,         # Source: ESPN[reference:122]
    ('Leicester', 'Wolves'): 31768,          # Source: Sky Sports[reference:123]
    ('Blackburn', 'Southampton'): 21970,     # Source: ESPN[reference:124]
    ('Man City', 'Chelsea'): 47304,          # Source: Stamford-Bridge.com[reference:125]

    # ==================== 29 February 2004 - Matchweek 27 ====================
    ('Leeds', 'Liverpool'): 39932,           # Source: LFChistory[reference:126]
    ('Portsmouth', 'Newcastle'): 20140,      # Source: Sky Sports[reference:127]

    # ==================== 3 March 2004 - Matchweek 17 (Rescheduled) ====================
    ('Birmingham', 'Middlesbrough'): 29369,  # Source: ESPN[reference:128]

    # ==================== 6 March 2004 - Matchweek 27 ====================
    ('Birmingham', 'Bolton'): 28003,         # Source: ESPN[reference:129]

    # ==================== 9 March 2004 - Matchweek 27 ====================
    ('Middlesbrough', 'Tottenham'): 31789,   # Source: ESPN[reference:130]

    # ==================== 13 March 2004 - Matchweek 28 ====================
    ('Birmingham', 'Leicester'): 29491,      # Source: ESPN[reference:131]
    ('Blackburn', 'Arsenal'): 28627,         # Source: FBref[reference:132]
    ('Bolton', 'Chelsea'): 26717,            # Source: ESPN[reference:133]
    ('Fulham', 'Leeds'): 17104,              # Source: Global Sports Archive[reference:134]
    ('Charlton', 'Middlesbrough'): 26229,    # Source: FBref[reference:135]
    ('Everton', 'Portsmouth'): 40105,        # Source: Global Sports Archive[reference:136]

    # ==================== 14 March 2004 - Matchweek 28 ====================
    ('Tottenham', 'Newcastle'): 36083,       # Source: ESPN[reference:137]
    ('Southampton', 'Liverpool'): 32056,     # Source: ESPN[reference:138]
    ('Man City', 'Man United'): 47284,       # Source: ESPN[reference:139]
    ('Wolves', 'Aston Villa'): 29386,        # Source: Sky Sports[reference:140]

    # ==================== 17 March 2004 - Matchweek 26 (Rescheduled) ====================
    ('Liverpool', 'Portsmouth'): 34663,      # Source: LFChistory[reference:141]

    # ==================== 20 March 2004 - Matchweek 29 ====================
    ('Newcastle', 'Charlton'): 51847,        # Source: Sky Sports[reference:142]
    ('Middlesbrough', 'Birmingham'): 30244,  # Source: 11v11.com[reference:143]
    ('Man United', 'Tottenham'): 67634,      # Source: ESPN[reference:144]
    ('Arsenal', 'Bolton'): 38053,            # Source: FBref[reference:145]
    ('Leicester', 'Everton'): 31650,         # Source: DoingThe92[reference:146]
    ('Aston Villa', 'Blackburn'): 37532,     # Source: ESPN[reference:147]
    ('Liverpool', 'Wolves'): 43795,          # Source: ESPN[reference:148]
    ('Chelsea', 'Fulham'): 41169,            # Source: Stamford-Bridge.com[reference:149]

    # ==================== 21 March 2004 - Matchweek 29 ====================
    ('Portsmouth', 'Southampton'): 20140,    # Source: Sky Sports[reference:150]

    # ==================== 22 March 2004 - Matchweek 29 ====================
    ('Leeds', 'Man City'): 36998,            # Source: Transfermarkt[reference:151]

    # ==================== 27 March 2004 - Matchweek 30 ====================
    ('Charlton', 'Aston Villa'): 26238,      # Source: FBref[reference:152]
    ('Birmingham', 'Leeds'): 29069,          # Source: ESPN[reference:153]
    ('Southampton', 'Tottenham'): 31973,     # Source: ESPN[reference:154]
    ('Blackburn', 'Portsmouth'): 22855,      # Source: 11v11.com[reference:155]
    ('Everton', 'Middlesbrough'): 38210,     # Source: ESPN[reference:156]
    ('Chelsea', 'Wolves'): 41215,            # Source: ESPN[reference:157]
    ('Man City', 'Fulham'): 46522,           # Source: ESPN[reference:158]

    # ==================== 28 March 2004 - Matchweek 30 ====================
    ('Arsenal', 'Man United'): 38184,        # Source: Sky Sports[reference:159]
    ('Bolton', 'Newcastle'): 27360,          # Source: ESPN[reference:160]
    ('Leicester', 'Liverpool'): 32013,       # Source: LFChistory[reference:161]

    # ==================== 3 April 2004 - Matchweek 31 ====================
    ('Tottenham', 'Chelsea'): 36101,         # Source: ESPN[reference:162]
    ('Wolves', 'Southampton'): 29106,        # Source: Sky Sports[reference:163]

    # ==================== 5 April 2004 - Matchweek 31 ====================
    ('Leeds', 'Leicester'): 34036,           # Source: FBref[reference:164]

    # ==================== 9 April 2004 - Matchweek 32 ====================
    ('Arsenal', 'Liverpool'): 38119,         # Source: Sky Sports[reference:165]
    ('Everton', 'Tottenham'): 38086,         # Source: ESPN[reference:166]

    # ==================== 10 April 2004 - Matchweek 32 ====================
    ('Blackburn', 'Leeds'): 26611,           # Source: ESPN[reference:167]
    ('Charlton', 'Portsmouth'): 26385,       # Source: ESPN[reference:168]
    ('Bolton', 'Aston Villa'): 26374,        # Source: ESPN[reference:169]
    ('Chelsea', 'Middlesbrough'): 40873,     # Source: ESPN[reference:170]

    # ==================== 11 April 2004 - Matchweek 33 ====================
    ('Newcastle', 'Arsenal'): 52141,         # Source: 11v11.com[reference:171]

    # ==================== 12 April 2004 - Matchweek 33 ====================
    ('Aston Villa', 'Chelsea'): 41112,       # Source: ESPN[reference:172]
    ('Liverpool', 'Charlton'): 40003,        # Source: ESPN[reference:173]
}

fill_from_dict(
    df,
    season="0304",
    data=attendance_data,
    value_col=['Attendance'],
    inplace=True
)

In [40]:
null_rows(df, "0304", 'Attendance')

           HomeTeam       AwayTeam  Year  Month  Day
4284  Middlesbrough    Southampton  2004      4   12
4285     Portsmouth     Birmingham  2004      4   12
4287         Wolves         Bolton  2004      4   12
4290     Man United      Leicester  2004      4   13
4291        Arsenal          Leeds  2004      4   16
4292       Charlton     Birmingham  2004      4   17
4293         Bolton      Tottenham  2004      4   17
4294         Wolves  Middlesbrough  2004      4   17
4295     Portsmouth     Man United  2004      4   17
4296      Blackburn      Leicester  2004      4   17
4297      Liverpool         Fulham  2004      4   17
4298        Chelsea        Everton  2004      4   17
4300    Aston Villa      Newcastle  2004      4   18
4301     Man United       Charlton  2004      4   20
4302        Everton      Blackburn  2004      4   24
4303         Fulham       Charlton  2004      4   24
4305     Man United      Liverpool  2004      4   24
4306  Middlesbrough    Aston Villa  2004      4   24
4307    Southampton         Bolton  2004      4   24
4308     Birmingham         Wolves  2004      4   25
4309          Leeds     Portsmouth  2004      4   25
4310      Newcastle        Chelsea  2004      4   25
4311      Tottenham        Arsenal  2004      4   25
4312     Portsmouth         Fulham  2004      5    1
4313         Wolves        Everton  2004      5    1
4314        Chelsea    Southampton  2004      5    1
4315       Charlton      Leicester  2004      5    1
4316        Arsenal     Birmingham  2004      5    1
4318      Blackburn     Man United  2004      5    1
4320         Bolton          Leeds  2004      5    2
4321      Liverpool  Middlesbrough  2004      5    2
4322     Portsmouth        Arsenal  2004      5    4
4323     Birmingham      Liverpool  2004      5    8
4324        Everton         Bolton  2004      5    8
4325          Leeds       Charlton  2004      5    8
4326      Leicester     Portsmouth  2004      5    8
4327     Man United        Chelsea  2004      5    8
4329    Southampton    Aston Villa  2004      5    8
4330      Tottenham      Blackburn  2004      5    8
4331      Newcastle         Wolves  2004      5    9
4332         Fulham        Arsenal  2004      5    9
4333    Southampton      Newcastle  2004      5   12
4334        Arsenal      Leicester  2004      5   15
4335    Aston Villa     Man United  2004      5   15
4336      Blackburn     Birmingham  2004      5   15
4337         Bolton         Fulham  2004      5   15
4338       Charlton    Southampton  2004      5   15
4339        Chelsea          Leeds  2004      5   15
4340      Liverpool      Newcastle  2004      5   15
4342     Portsmouth  Middlesbrough  2004      5   15
4343         Wolves      Tottenham  2004      5   15

In [41]:
attendance_data = {
    # ==================== 12 April 2004 - Matchweek 33 ====================
    ('Middlesbrough', 'Southampton'): 30768,     # Source: ESPN, FBref[reference:0][reference:1]
    ('Portsmouth', 'Birmingham'): 20079,         # Source: Global Sports Archive, FBref[reference:2][reference:3]
    ('Wolves', 'Bolton'): 28695,                 # Source: Sky Sports, ESPN[reference:4][reference:5]

    # ==================== 13 April 2004 - Matchweek 33 ====================
    ('Man United', 'Leicester'): 67749,          # Source: ESPN, Sky Sports[reference:6][reference:7]

    # ==================== 16 April 2004 - Matchweek 34 ====================
    ('Arsenal', 'Leeds'): 38094,                 # Source: Sky Sports, FBref[reference:8][reference:9]

    # ==================== 17 April 2004 - Matchweek 34 ====================
    ('Charlton', 'Birmingham'): 25206,           # Source: 11v11.com, Sky Sports[reference:10][reference:11]
    ('Bolton', 'Tottenham'): 26440,              # Source: ESPN, worldfootball.net[reference:12][reference:13]
    ('Wolves', 'Middlesbrough'): 27975,          # Source: Sky Sports, ESPN[reference:14][reference:15]
    ('Portsmouth', 'Man United'): 20140,         # Source: ESPN, Sky Sports[reference:16][reference:17]
    ('Blackburn', 'Leicester'): 22749,           # Source: ESPN, Sky Sports[reference:18][reference:19]
    ('Liverpool', 'Fulham'): 42042,              # Source: ESPN, LFChistory[reference:20][reference:21]
    ('Chelsea', 'Everton'): 41169,               # Source: ESPN, worldfootball.net[reference:22][reference:23]

    # ==================== 18 April 2004 - Matchweek 34 ====================
    ('Aston Villa', 'Newcastle'): 40786,         # Source: Sky Sports, FBref[reference:24][reference:25]

    # ==================== 20 April 2004 - Matchweek 31 (Rescheduled) ====================
    ('Man United', 'Charlton'): 67477,           # Source: ESPN, Sky Sports[reference:26][reference:27]

    # ==================== 24 April 2004 - Matchweek 35 ====================
    ('Everton', 'Blackburn'): 38884,             # Source: Sky Sports, ESPN[reference:28][reference:29]
    ('Fulham', 'Charlton'): 16585,               # Source: ESPN, Sky Sports[reference:30][reference:31]
    ('Man United', 'Liverpool'): 67647,          # Source: ESPN, Sky Sports[reference:32][reference:33]
    ('Middlesbrough', 'Aston Villa'): 31243,     # Source: Global Sports Archive, FBref[reference:34][reference:35]
    ('Southampton', 'Bolton'): 31712,            # Source: Sky Sports, Global Sports Archive[reference:36][reference:37]

    # ==================== 25 April 2004 - Matchweek 35 ====================
    ('Birmingham', 'Wolves'): 29494,             # Source: ESPN, Sky Sports[reference:38][reference:39]
    ('Leeds', 'Portsmouth'): 39273,              # Source: ESPN, Sky Sports[reference:40][reference:41]
    ('Newcastle', 'Chelsea'): 52016,             # Source: ESPN, 11v11.com[reference:42][reference:43]
    ('Tottenham', 'Arsenal'): 36097,             # Source: ESPN, THFCDB[reference:44][reference:45]

    # ==================== 1 May 2004 - Matchweek 36 ====================
    ('Portsmouth', 'Fulham'): 20065,             # Source: ESPN, Sky Sports[reference:46][reference:47]
    ('Wolves', 'Everton'): 29395,                # Source: FBref, Sky Sports[reference:48][reference:49]
    ('Chelsea', 'Southampton'): 41321,           # Source: ESPN, 11v11.com[reference:50][reference:51]
    ('Charlton', 'Leicester'): 26034,            # Source: ESPN, 11v11.com[reference:52][reference:53]
    ('Arsenal', 'Birmingham'): 38061,            # Source: ESPN, 11v11.com[reference:54][reference:55]
    ('Blackburn', 'Man United'): 29616,          # Source: ESPN, 11v11.com[reference:56][reference:57]

    # ==================== 2 May 2004 - Matchweek 36 ====================
    ('Bolton', 'Leeds'): 27420,                  # Source: ESPN, FBref[reference:58][reference:59]
    ('Liverpool', 'Middlesbrough'): 42031,       # Source: LFChistory, ESPN[reference:60][reference:61]

    # ==================== 4 May 2004 - Matchweek 31 (Rescheduled) ====================
    ('Portsmouth', 'Arsenal'): 20140,            # Source: ESPN, Wikipedia[reference:62][reference:63]

    # ==================== 8 May 2004 - Matchweek 37 ====================
    ('Birmingham', 'Liverpool'): 29553,          # Source: ESPN, 11v11.com[reference:64][reference:65]
    ('Everton', 'Bolton'): 40190,                # Source: ESPN, Sky Sports[reference:66][reference:67]
    ('Leeds', 'Charlton'): 38986,                # Source: ESPN, FBref[reference:68][reference:69]
    ('Leicester', 'Portsmouth'): 31536,          # Source: Sky Sports, FBref[reference:70][reference:71]
    ('Man United', 'Chelsea'): 67609,            # Source: ESPN, Stamford-Bridge[reference:72][reference:73]
    ('Southampton', 'Aston Villa'): 32054,       # Source: ESPN, 11v11.com[reference:74][reference:75]
    ('Tottenham', 'Blackburn'): 35698,           # Source: ESPN, THFCDB[reference:76][reference:77]

    # ==================== 9 May 2004 - Matchweek 37 ====================
    ('Newcastle', 'Wolves'): 52139,              # Source: ESPN, Sky Sports[reference:78][reference:79]
    ('Fulham', 'Arsenal'): 18102,                # Source: ESPN, FBref[reference:80][reference:81]

    # ==================== 12 May 2004 - Matchweek 38 (Rescheduled) ====================
    ('Southampton', 'Newcastle'): 31815,         # Source: ESPN, 11v11.com[reference:82][reference:83]

    # ==================== 15 May 2004 - Matchweek 38 ====================
    ('Arsenal', 'Leicester'): 38419,             # Source: FBref, Sky Sports[reference:84][reference:85]
    ('Aston Villa', 'Man United'): 42573,        # Source: 11v11.com, FBref[reference:86][reference:87]
    ('Blackburn', 'Birmingham'): 26070,          # Source: ESPN, FBref[reference:88][reference:89]
    ('Bolton', 'Fulham'): 27383,                 # Source: ESPN, 11v11.com[reference:90][reference:91]
    ('Charlton', 'Southampton'): 26614,          # Source: ESPN, 11v11.com[reference:92][reference:93]
    ('Chelsea', 'Leeds'): 41276,                 # Source: Stamford-Bridge, ChelseaFC[reference:94][reference:95]
    ('Liverpool', 'Newcastle'): 44172,           # Source: LFChistory, FBref[reference:96][reference:97]
    ('Portsmouth', 'Middlesbrough'): 20134,      # Source: ESPN, Sky Sports[reference:98][reference:99]
    ('Wolves', 'Tottenham'): 29389,              # Source: Global Sports Archive, Sky Sports[reference:100][reference:101]
}


fill_from_dict(
    df,
    season="0304",
    data=attendance_data,
    value_col=['Attendance'],
    inplace=True
)

In [42]:
missing_report(df,"0304")

XGHome    380
XGAway    380
dtype: int64

In [43]:
df.to_csv("Data/Data8.csv", index=False)

---
$$ 2002-03 $$

In [3]:
missing_report(df,"0203")

WeekDay                          380
Time                             380
Round                            380
Attendance                       380
XGHome                           380
XGAway                           380
SeasonPosAway                     38
SeasonPlayedAway                  38
SeasonWinAway                     38
SeasonDrawAway                    38
SeasonLossAway                    38
SeasonGFAway                      38
SeasonGAAway                      38
SeasonGDAway                      38
SeasonPointsAway                  38
QualificationOrRelegationAway     38
dtype: int64

In [5]:
null_rows(df, '0203', 'SeasonPosAway')['AwayTeam'].unique()

array(['Bolton', 'Birmingham'], dtype=object)

In [6]:
# Season statistics for Bolton Wanderers in 2002-03
bolton_stats = {
    'SeasonPosAway': 17,
    'SeasonPlayedAway': 38,
    'SeasonWinAway': 10,
    'SeasonDrawAway': 14,
    'SeasonLossAway': 14,
    'SeasonGFAway': 41,
    'SeasonGAAway': 51,
    'SeasonGDAway': -10,
    'SeasonPointsAway': 44,
    'QualificationOrRelegationAway': 'Not Applicable'
}

# Season statistics for Birmingham in 2002-03
Birmingham_stats = {
    'SeasonPosAway': 13,
    'SeasonPlayedAway': 38,
    'SeasonWinAway': 13,
    'SeasonDrawAway': 9,
    'SeasonLossAway': 16,
    'SeasonGFAway': 41,
    'SeasonGAAway': 49,
    'SeasonGDAway': -8,
    'SeasonPointsAway': 48,
    'QualificationOrRelegationAway': 'Not Applicable'
}

# List of columns to fill
away_cols = [
    'SeasonPosAway', 'SeasonPlayedAway', 'SeasonWinAway', 'SeasonDrawAway',
    'SeasonLossAway', 'SeasonGFAway', 'SeasonGAAway', 'SeasonGDAway',
    'SeasonPointsAway', 'QualificationOrRelegationAway'
]

# Fill the columns for all rows where AwayTeam is 'Bolton' in the 2002-03 season
for idx, row in df[df['Season'] == '0203'].iterrows():
    if row['AwayTeam'] == 'Bolton':
        for col in away_cols:
            df.loc[(df['Season'] == '0203') & (df.index == idx), col] = bolton_stats[col]

# Fill the columns for all rows where AwayTeam is 'Birmingham' in the 2002-03 season
for idx, row in df[df['Season'] == '0203'].iterrows():
    if row['AwayTeam'] == 'Birmingham':
        for col in away_cols:
            df.loc[(df['Season'] == '0203') & (df.index == idx), col] = Birmingham_stats[col]

In [8]:
null_rows(df, "0203", 'WeekDay')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
3584    Southampton  Middlesbrough  2002      8   17
3585     Man United      West Brom  2002      8   17
3586      Blackburn     Sunderland  2002      8   17
3587         Fulham         Bolton  2002      8   17
3588       Charlton        Chelsea  2002      8   17
3589        Everton      Tottenham  2002      8   17
3590          Leeds       Man City  2002      8   17
3591        Arsenal     Birmingham  2002      8   18
3592    Aston Villa      Liverpool  2002      8   18
3593      Newcastle       West Ham  2002      8   19
3594        Chelsea     Man United  2002      8   23
3595       West Ham        Arsenal  2002      8   24
3596      West Brom          Leeds  2002      8   24
3597      Tottenham    Aston Villa  2002      8   24
3598  Middlesbrough         Fulham  2002      8   24
3599       Man City      Newcastle  2002      8   24
3600      Liverpool    Southampton  2002      8   24
3601         Bolton       Charlton  2002      8   24
3602     Birmingham      Blackburn  2002      8   24
3603     Sunderland        Everton  2002      8   24
3604        Arsenal      West Brom  2002      8   27
3605       Charlton      Tottenham  2002      8   27
3606    Southampton        Chelsea  2002      8   28
3607        Everton     Birmingham  2002      8   28
3608    Aston Villa       Man City  2002      8   28
3609          Leeds     Sunderland  2002      8   28
3610      Blackburn      Liverpool  2002      8   28
3611     Birmingham          Leeds  2002      8   31
3612       Man City        Everton  2002      8   31
3613  Middlesbrough      Blackburn  2002      8   31
3614     Sunderland     Man United  2002      8   31
3615      Tottenham    Southampton  2002      8   31
3616      West Brom         Fulham  2002      8   31
3617       West Ham       Charlton  2002      8   31
3618         Bolton    Aston Villa  2002      9    1
3619        Chelsea        Arsenal  2002      9    1
3620      Liverpool      Newcastle  2002      9    2
3621     Man United  Middlesbrough  2002      9    3
3622        Arsenal       Man City  2002      9   10
3623  Middlesbrough     Sunderland  2002      9   10
3624    Southampton        Everton  2002      9   11
3625      Newcastle          Leeds  2002      9   11
3626       West Ham      West Brom  2002      9   11
3627      Liverpool     Birmingham  2002      9   11
3628         Fulham      Tottenham  2002      9   11
3629    Aston Villa       Charlton  2002      9   11
3630      Blackburn        Chelsea  2002      9   11
3631     Man United         Bolton  2002      9   11
3632      West Brom    Southampton  2002      9   14
3633     Sunderland         Fulham  2002      9   14
3634       Charlton        Arsenal  2002      9   14
3635        Everton  Middlesbrough  2002      9   14
3636         Bolton      Liverpool  2002      9   14
3637        Chelsea      Newcastle  2002      9   14
3638          Leeds     Man United  2002      9   14
3639       Man City      Blackburn  2002      9   15
3640      Tottenham       West Ham  2002      9   15
3641     Birmingham    Aston Villa  2002      9   16
3642        Arsenal         Bolton  2002      9   21
3643      Liverpool      West Brom  2002      9   21
3644     Man United      Tottenham  2002      9   21
3645  Middlesbrough     Birmingham  2002      9   21
3646      Newcastle     Sunderland  2002      9   21
3647    Southampton       Charlton  2002      9   21
3648       West Ham       Man City  2002      9   21
3649    Aston Villa        Everton  2002      9   22
3650      Blackburn          Leeds  2002      9   22
3651         Fulham        Chelsea  2002      9   23
3652      Tottenham  Middlesbrough  2002      9   28
3653       Man City      Liverpool  2002      9   28
3654     Sunderland    Aston Villa  2002      9   28
3655        Everton         Fulham  2002      9   28
3656     Birmingham      Newcastle  2002      9   28
3657         Bolton    Southampton  2002      9   28
3658          Leeds        Arsenal  2002      9   28
3659       Charlton     Man United  2002      9   28
3660        Chelsea       West Ham  2002      9   28
3661      West Brom      Blackburn  2002      9   30
3662  Middlesbrough         Bolton  2002     10    5
3663      Newcastle      West Brom  2002     10    5
3664    Southampton       Man City  2002     10    5
3665       West Ham     Birmingham  2002     10    5
3666        Arsenal     Sunderland  2002     10    6
3667      Blackburn      Tottenham  2002     10    6
3668         Fulham       Charlton  2002     10    6
3669      Liverpool        Chelsea  2002     10    6
3670    Aston Villa          Leeds  2002     10    6
3671     Man United        Everton  2002     10    7
3672     Sunderland       West Ham  2002     10   19
3673      West Brom     Birmingham  2002     10   19
3674       Man City        Chelsea  2002     10   19
3675         Fulham     Man United  2002     10   19
3676        Everton        Arsenal  2002     10   19
3677          Leeds      Liverpool  2002     10   19
3678      Blackburn      Newcastle  2002     10   19
3679       Charlton  Middlesbrough  2002     10   20
3680      Tottenham         Bolton  2002     10   20
3681    Aston Villa    Southampton  2002     10   21
3682         Fulham       West Ham  2002     10   23
3683        Arsenal      Blackburn  2002     10   26

In [ ]:
match_data = {
    # -------------------- 17 August 2002 - Matchweek 1 --------------------
    ('Southampton', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 28341
    },  # Source: FBref [6L16-L17], ESPN [7L3-L4]

    ('Man United', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 67645
    },  # Source: FBref [6L10], ESPN [2L17-L18]

    ('Blackburn', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 27122
    },  # Source: FBref [6L18], Sky Sports [3L23-L24]

    ('Fulham', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 16338
    },  # Source: FBref [6L14], ESPN [4L16-L17]

    ('Charlton', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 25640
    },  # Source: FBref [6L15], ESPN [5L27-L28]

    ('Birmingham', 'Norwich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': None
    },

    ('Man City', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': None
    },

    ('Everton', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 40120
    },  # Source: FBref [6L12-L13]

    ('Leeds', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 40195
    },  # Source: FBref [6L11]

    ('Arsenal', 'Birmingham'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 1,
        'Attendance': 38018
    },  # Source: FBref [6L21]

    ('Aston Villa', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 1,
        'Attendance': 41183
    },  # Source: FBref [6L19-L20]

    ('Newcastle', 'West Ham'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 1,
        'Attendance': 51072
    },  # Source: FBref [6L22]

    # -------------------- 23 August 2002 - Matchweek 2 --------------------
    ('Chelsea', 'Man United'): {
        'WeekDay': 'Fri', 'Time': '15:00', 'Round': 2,
        'Attendance': 41541
    },  # Source: FBref [6L23-L24], ESPN [12L6]

    # -------------------- 24 August 2002 - Matchweek 2 --------------------
    ('West Ham', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 2,
        'Attendance': 35048
    },  # Source: FBref [6L28], ESPN [13L26-L27]

    ('West Brom', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 2,
        'Attendance': 26618
    },  # Source: FBref [6L34-L35]

    ('Tottenham', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 2,
        'Attendance': 35384
    },  # Source: FBref [6L32]

    ('Middlesbrough', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 2,
        'Attendance': 28588
    },  # Source: FBref [6L26]

    ('Man City', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 2,
        'Attendance': 34776
    },  # Source: FBref [6L29]

    ('Liverpool', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 2,
        'Attendance': 43058
    },  # Source: FBref [6L33]

    ('Bolton', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 2,
        'Attendance': None
    },

    ('Birmingham', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 2,
        'Attendance': 27563
    },  # Source: FBref [6L30-L31]

    ('Sunderland', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 2,
        'Attendance': 37698
    },  # Source: FBref [6L25]

    # -------------------- 27 August 2002 - Matchweek 3 --------------------
    ('Arsenal', 'West Brom'): {
        'WeekDay': 'Tue', 'Time': '20:00', 'Round': 3,
        'Attendance': 37920
    },  # Source: FBref [14L7-L8], Transfermarkt [14L26-L27]

    ('Charlton', 'Tottenham'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 3,
        'Attendance': None
    },

    # -------------------- 28 August 2002 - Matchweek 3 --------------------
    ('Southampton', 'Chelsea'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 3,
        'Attendance': 31208
    },  # Source: FBref [15L16-L17], Sky Sports [15L25-L26]

    ('Everton', 'Birmingham'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 3,
        'Attendance': None
    },

    ('Aston Villa', 'Man City'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 3,
        'Attendance': None
    },

    ('Leeds', 'Sunderland'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 3,
        'Attendance': None
    },

    ('Blackburn', 'Liverpool'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 3,
        'Attendance': None
    },

    ('Man United', 'Middlesbrough'): {
        'WeekDay': 'Tue', 'Time': '15:00', 'Round': 3,
        'Attendance': 67464
    },  # Source: FBref [19L7-L8]

    # -------------------- 31 August 2002 - Matchweek 4 --------------------
    ('Birmingham', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 27164
    },  # Source: FBref [16L13-L14], ESPN [16L27-L28]

    ('Man City', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': None
    },

    ('Middlesbrough', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': None
    },

    ('Sunderland', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': None
    },

    ('Tottenham', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': None
    },

    ('West Brom', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': None
    },

    ('West Ham', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': None
    },

    ('Bolton', 'Aston Villa'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 4,
        'Attendance': None
    },

    ('Chelsea', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 4,
        'Attendance': 40037
    },  # Source: ESPN [17L6-L7], Sky Sports [17L15-L16]

    ('Liverpool', 'Newcastle'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 4,
        'Attendance': 43241
    },  # Source: FBref [18L6-L7]

    # -------------------- 10 September 2002 - Matchweek 5 --------------------
    ('Arsenal', 'Man City'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 5,
        'Attendance': 37878
    },  # Source: Sky Sports [20L6-L7], ESPN [20L10]

    ('Middlesbrough', 'Sunderland'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 5,
        'Attendance': None
    },

    # -------------------- 11 September 2002 - Matchweek 5 --------------------
    ('Southampton', 'Everton'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 5,
        'Attendance': 29190
    },  # Source: ESPN [21L9-L10], FBref [21L19-L20]

    ('Newcastle', 'Leeds'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 5,
        'Attendance': None
    },

    ('West Ham', 'West Brom'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 5,
        'Attendance': None
    },

    ('Liverpool', 'Birmingham'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 5,
        'Attendance': None
    },

    ('Fulham', 'Tottenham'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 5,
        'Attendance': None
    },

    ('Aston Villa', 'Charlton'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 5,
        'Attendance': None
    },

    ('Blackburn', 'Chelsea'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 5,
        'Attendance': None
    },

    ('Man United', 'Bolton'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 5,
        'Attendance': None
    },

    # -------------------- 14 September 2002 - Matchweek 6 --------------------
    ('West Brom', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': 26383
    },  # Source: FBref [22L7], Sky Sports [22L15-L16]

    ('Sunderland', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': None
    },

    ('Charlton', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': None
    },

    ('Everton', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': None
    },

    ('Bolton', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': None
    },

    ('Chelsea', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': None
    },

    ('Leeds', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': None
    },

    ('Man City', 'Blackburn'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 6,
        'Attendance': None
    },

    ('Tottenham', 'West Ham'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 6,
        'Attendance': None
    },

    ('Birmingham', 'Aston Villa'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 6,
        'Attendance': None
    },

    # -------------------- 21 September 2002 - Matchweek 7 --------------------
    ('Arsenal', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': 37974
    },  # Source: FBref [23L7], ESPN [23L16-L17]

    ('Liverpool', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': None
    },

    ('Man United', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': None
    },

    ('Middlesbrough', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': None
    },

    ('Newcastle', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': None
    },

    ('Southampton', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': None
    },

    ('West Ham', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': None
    },

    ('Aston Villa', 'Everton'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 7,
        'Attendance': None
    },

    ('Blackburn', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 7,
        'Attendance': None
    },

    ('Fulham', 'Chelsea'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 7,
        'Attendance': None
    },

    # -------------------- 28 September 2002 - Matchweek 8 --------------------
    ('Tottenham', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 36082
    },  # Source: FBref [24L15-L16], Sky Sports [24L24-L25]

    ('Man City', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': None
    },

    ('Sunderland', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': None
    },

    ('Everton', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': None
    },

    ('Birmingham', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': None
    },

    ('Bolton', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': None
    },

    ('Leeds', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': None
    },

    ('Charlton', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': None
    },

    ('Chelsea', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': None
    },

    ('West Brom', 'Blackburn'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 8,
        'Attendance': None
    },

    # -------------------- 5 October 2002 - Matchweek 9 --------------------
    ('Middlesbrough', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': 31005
    },  # Source: FBref [25L10-L11], ESPN [25L19-L20]

    ('Newcastle', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': None
    },

    ('Southampton', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': None
    },

    ('West Ham', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': None
    },

    ('Arsenal', 'Sunderland'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 9,
        'Attendance': None
    },

    ('Blackburn', 'Tottenham'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 9,
        'Attendance': None
    },

    ('Fulham', 'Charlton'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 9,
        'Attendance': None
    },

    ('Liverpool', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 9,
        'Attendance': 43856
    },  # Source: FBref [26L10]

    ('Aston Villa', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 9,
        'Attendance': None
    },

    ('Man United', 'Everton'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 9,
        'Attendance': None
    },

    # -------------------- 19 October 2002 - Matchweek 10 --------------------
    ('Sunderland', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 44352
    },  # Source: FBref [26L11-L12]

    ('West Brom', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': None
    },

    ('Man City', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': None
    },

    ('Fulham', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': None
    },

    ('Everton', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': None
    },

    ('Leeds', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': None
    },

    ('Blackburn', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': None
    },

    ('Charlton', 'Middlesbrough'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    ('Tottenham', 'Bolton'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    ('Aston Villa', 'Southampton'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    # -------------------- 23 October 2002 - Matchweek 10 --------------------
    ('Fulham', 'West Ham'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 10,
        'Attendance': 15858
    },  # Source: FBref [27L6-L7], Sky Sports [27L10-L11]

    # -------------------- 26 October 2002 - Matchweek 11 --------------------
    ('Arsenal', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 38064
    },  # Source: FBref [28L8-L9], Sky Sports [28L25-L26]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0203',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [11]:
null_rows(df, "0203", 'WeekDay')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
3684     Birmingham       Man City  2002     10   26
3685        Chelsea      West Brom  2002     10   26
3686      Liverpool      Tottenham  2002     10   26
3687     Man United    Aston Villa  2002     10   26
3688  Middlesbrough          Leeds  2002     10   26
3689      Newcastle       Charlton  2002     10   26
3690    Southampton         Fulham  2002     10   27
3691       West Ham        Everton  2002     10   27
3692         Bolton     Sunderland  2002     10   28
3693      West Brom       Man City  2002     11    2
3694      Liverpool       West Ham  2002     11    2
3695     Birmingham         Bolton  2002     11    2
3696     Man United    Southampton  2002     11    2
3697      Blackburn    Aston Villa  2002     11    3
3698       Charlton     Sunderland  2002     11    3
3699          Leeds        Everton  2002     11    3
3700         Fulham        Arsenal  2002     11    3
3701      Tottenham        Chelsea  2002     11    3
3702      Newcastle  Middlesbrough  2002     11    4
3703        Arsenal      Newcastle  2002     11    9
3704    Aston Villa         Fulham  2002     11    9
3705         Bolton      West Brom  2002     11    9
3706        Everton       Charlton  2002     11    9
3707       Man City     Man United  2002     11    9
3708  Middlesbrough      Liverpool  2002     11    9
3709    Southampton      Blackburn  2002     11    9
3710        Chelsea     Birmingham  2002     11    9
3711     Sunderland      Tottenham  2002     11   10
3712       West Ham          Leeds  2002     11   10
3713      West Brom    Aston Villa  2002     11   16
3714       Man City       Charlton  2002     11   16
3715        Arsenal      Tottenham  2002     11   16
3716      Newcastle    Southampton  2002     11   16
3717        Chelsea  Middlesbrough  2002     11   16
3718      Liverpool     Sunderland  2002     11   17
3719       West Ham     Man United  2002     11   17
3720          Leeds         Bolton  2002     11   17
3721      Blackburn        Everton  2002     11   17
3722     Birmingham         Fulham  2002     11   17
3723    Aston Villa       West Ham  2002     11   23
3724         Bolton        Chelsea  2002     11   23
3725        Everton      West Brom  2002     11   23
3726         Fulham      Liverpool  2002     11   23
3727     Man United      Newcastle  2002     11   23
3728  Middlesbrough       Man City  2002     11   23
3729    Southampton        Arsenal  2002     11   23
3730     Sunderland     Birmingham  2002     11   23
3731       Charlton      Blackburn  2002     11   24
3732      Tottenham          Leeds  2002     11   24
3733      West Brom  Middlesbrough  2002     11   30
3734     Birmingham      Tottenham  2002     11   30
3735        Chelsea     Sunderland  2002     11   30
3736      Blackburn         Fulham  2002     11   30
3737        Arsenal    Aston Villa  2002     11   30
3738       Man City         Bolton  2002     11   30
3739          Leeds       Charlton  2002     12    1
3740      Liverpool     Man United  2002     12    1
3741      Newcastle        Everton  2002     12    1
3742       West Ham    Southampton  2002     12    2
3743    Southampton     Birmingham  2002     12    7
3744  Middlesbrough       West Ham  2002     12    7
3745         Bolton      Blackburn  2002     12    7
3746         Fulham          Leeds  2002     12    7
3747        Everton        Chelsea  2002     12    7
3748    Aston Villa      Newcastle  2002     12    7
3749       Charlton      Liverpool  2002     12    7
3750     Man United        Arsenal  2002     12    7
3751      Tottenham      West Brom  2002     12    8
3752     Sunderland       Man City  2002     12    9
3753  Middlesbrough        Chelsea  2002     12   14
3754    Southampton      Newcastle  2002     12   14
3755        Everton      Blackburn  2002     12   14
3756       Charlton       Man City  2002     12   14
3757    Aston Villa      West Brom  2002     12   14
3758     Man United       West Ham  2002     12   14
3759         Fulham     Birmingham  2002     12   15
3760     Sunderland      Liverpool  2002     12   15
3761      Tottenham        Arsenal  2002     12   15
3762         Bolton          Leeds  2002     12   16
3763       West Ham         Bolton  2002     12   21
3764      West Brom     Sunderland  2002     12   21
3765        Arsenal  Middlesbrough  2002     12   21
3766          Leeds    Southampton  2002     12   21
3767        Chelsea    Aston Villa  2002     12   21
3768     Birmingham       Charlton  2002     12   21
3769      Newcastle         Fulham  2002     12   21
3770      Liverpool        Everton  2002     12   22
3771      Blackburn     Man United  2002     12   22
3772       Man City      Tottenham  2002     12   23
3773     Birmingham        Everton  2002     12   26
3774         Bolton      Newcastle  2002     12   26
3775        Chelsea    Southampton  2002     12   26
3776      Liverpool      Blackburn  2002     12   26
3778     Sunderland          Leeds  2002     12   26
3779      Tottenham       Charlton  2002     12   26
3780      West Brom        Arsenal  2002     12   26
3781       West Ham         Fulham  2002     12   26
3782  Middlesbrough     Man United  2002     12   26
3783     Man United     Birmingham  2002     12   28
3784    Southampton     Sunderland  2002     12   28

In [ ]:
match_data = {
    # -------------------- 26 October 2002 - Matchweek 11 --------------------
    ('Birmingham', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 29316
    },  # Source: FBref [0L30-L31], Sky Sports [0L11-L12]

    ('Chelsea', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 40893
    },  # Source: FBref [1L31-L32], ESPN [1L7-L8]

    ('Liverpool', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 44084
    },  # Source: FBref [2L23-L24], LFChistory [2L6-L7]

    ('Man United', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 67619
    },  # Source: FBref [3L33-L34], ESPN [3L7-L8]

    ('Middlesbrough', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 34723
    },  # Source: FBref [4L31-L32], ESPN [4L7-L8]

    ('Newcastle', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 51670
    },  # Source: FBref [5L21-L22], Wikiwand [5L9]

    ('Southampton', 'Fulham'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 11,
        'Attendance': 26188
    },  # Source: FBref [6L28-L29], ESPN [6L7]

    ('West Ham', 'Everton'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 11,
        'Attendance': 34117
    },  # Source: FBref [7L34-L35], ESPN [7L7-L8]

    ('Bolton', 'Sunderland'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 11,
        'Attendance': 23036
    },  # Source: FBref [8L15-L17], ESPN [8L7-L8]

    # -------------------- 2 November 2002 - Matchweek 12 --------------------
    ('West Brom', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 27044
    },  # Source: FBref [9L12-L13], citytilidie [9L7-L8]

    ('Liverpool', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 44048
    },  # Source: FBref [10L21-L22], LFChistory [10L7-L8]

    ('Birmingham', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 27224
    },  # Source: FBref [11L8-L9], Sky Sports [11L20-L21]

    ('Man United', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 12,
        'Attendance': 67691
    },  # Source: FBref [12L35-L37], Sky Sports [12L12-L13]

    ('Blackburn', 'Aston Villa'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 12,
        'Attendance': 23004
    },  # Source: ESPN [13L7-L8]

    ('Charlton', 'Sunderland'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 12,
        'Attendance': 26284
    },  # Source: FBref [14L34-L36], Global Sports Archive [14L7-L8]

    ('Leeds', 'Everton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 12,
        'Attendance': 40161
    },  # Source: FBref [15L15-L16], football-lineups [15L7]

    ('Fulham', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 12,
        'Attendance': 18800
    },  # Source: FBref [16L24-L25], ESPN [16L7-L8]

    ('Tottenham', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 12,
        'Attendance': 36049
    },  # Source: FBref [17L30-L31], ESPN [17L7-L8]

    ('Newcastle', 'Middlesbrough'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 12,
        'Attendance': 51558
    },  # Source: FBref [18L36-L37], ESPN [18L7-L8]

    # -------------------- 9 November 2002 - Matchweek 13 --------------------
    ('Arsenal', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 38121
    },  # Source: FBref [19L26-L27], ESPN [19L7-L8]

    ('Aston Villa', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 29563
    },  # Source: FBref [20L23-L24], ESPN [20L7-L8]

    ('Bolton', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 23630
    },  # Source: FBref [21L19], Sky Sports [21L8]

    ('Everton', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 37621
    },  # Source: FBref [22L17], The Football Archives [22L13]

    ('Man City', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '13:15', 'Round': 13,
        'Attendance': 34649
    },  # Source: FBref [23L14-L15], footymags [23L9]

    ('Middlesbrough', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 34747
    },  # Source: FBref [24L27-L28], ESPN [24L7-L8]

    ('Southampton', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 30059
    },  # Source: FBref [25L20-L21], ESPN [25L7-L8]

    ('Chelsea', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 35237
    },  # Source: FBref [26L15], ESPN [26L7-L8]

    ('Sunderland', 'Tottenham'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 13,
        'Attendance': 40024
    },  # Source: FBref [27L15-L16], thfcdb [27L7]

    ('West Ham', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 13,
        'Attendance': 33297
    },  # Source: FBref [28L26-L27], ESPN [28L7-L8]

    # -------------------- 16 November 2002 - Matchweek 14 --------------------
    ('West Brom', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 27091
    },  # Source: FBref [29L25-L26], Albion Till We Die [29L8]

    ('Man City', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 33455
    },  # Source: FBref [30L8-L9], Sky Sports [30L18]

    ('Arsenal', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 38152
    },  # Source: FBref [31L23-L24], ESPN [31L7-L8]

    ('Newcastle', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 51812
    },  # Source: FBref [32L17-L18], ESPN [32L7-L8]

    ('Chelsea', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 39064
    },  # Source: FBref [33L13], ESPN [33L7-L8]

    ('Liverpool', 'Sunderland'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 14,
        'Attendance': 43074
    },  # Source: FBref [34L13], LFChistory [34L7]

    ('West Ham', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '17:05', 'Round': 14,
        'Attendance': 35049
    },  # Source: FBref [35L25-L26], Global Sports Archive [35L12]

    ('Leeds', 'Bolton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 14,
        'Attendance': 36627
    },  # Source: FBref [36L25-L26], ESPN [36L7-L8]

    ('Blackburn', 'Everton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 14,
        'Attendance': 26496
    },  # Source: FBref [37L12-L13]

    ('Birmingham', 'Fulham'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 14,
        'Attendance': 26164
    },  # Source: FBref [38L19-L20], Sky Sports [38L16-L17]

    # -------------------- 23 November 2002 - Matchweek 15 --------------------
    ('Aston Villa', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 33279
    },  # Source: FBref [39L18], ESPN [39L7-L8]

    ('Bolton', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 25476
    },  # Source: FBref [40L24-L25], ESPN [40L7-L8]

    ('Everton', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 40113
    },  # Source: FBref [41L23], Sky Sports [41L7-L8]

    ('Fulham', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 18144
    },  # Source: FBref [42L21-L22], ESPN [42L7-L8]

    ('Man United', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 67619
    },  # Source: FBref [43L17], ESPN [43L7-L8]

    ('Middlesbrough', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 31510
    },  # Source: FBref [44L30-L31], citytilidie [44L7]

    ('Southampton', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 31797
    },  # Source: FBref [45L16-L17], ESPN [45L7-L8]

    ('Sunderland', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 38803
    },  # Source: FBref [46L10-L11], Sky Sports [46L19-L20]

    ('Charlton', 'Blackburn'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 15,
        'Attendance': 26152
    },  # Source: FBref [47L20], ESPN [47L7-L8]

    ('Tottenham', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 15,
        'Attendance': 35718
    },  # Source: FBref [48L39], ESPN [48L7-L8]

    # -------------------- 30 November 2002 - Matchweek 16 --------------------
    ('West Brom', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 27029
    },  # Source: FBref [49L16-L17], Albion Till We Die [49L9]

    ('Birmingham', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': None
    },

    ('Chelsea', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': None
    },

    ('Blackburn', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': None
    },

    ('Arsenal', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': None
    },

    ('Man City', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': None
    },

    ('Leeds', 'Charlton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 16,
        'Attendance': None
    },

    ('Liverpool', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 16,
        'Attendance': None
    },

    ('Newcastle', 'Everton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 16,
        'Attendance': None
    },

    ('West Ham', 'Southampton'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 16,
        'Attendance': None
    },

    # -------------------- 7 December 2002 - Matchweek 17 --------------------
    ('Southampton', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': None
    },

    ('Middlesbrough', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': None
    },

    ('Bolton', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': None
    },

    ('Fulham', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': None
    },

    ('Everton', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': None
    },

    ('Aston Villa', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': None
    },

    ('Charlton', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': None
    },

    ('Man United', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': None
    },

    ('Tottenham', 'West Brom'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 17,
        'Attendance': None
    },

    ('Sunderland', 'Man City'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 17,
        'Attendance': None
    },

    # -------------------- 14 December 2002 - Matchweek 18 --------------------
    ('Middlesbrough', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': None
    },

    ('Southampton', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': None
    },

    ('Everton', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': None
    },

    ('Charlton', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': None
    },

    ('Aston Villa', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': None
    },

    ('Man United', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': None
    },

    ('Fulham', 'Birmingham'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 18,
        'Attendance': None
    },

    ('Sunderland', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 18,
        'Attendance': None
    },

    ('Tottenham', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 18,
        'Attendance': None
    },

    ('Bolton', 'Leeds'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 18,
        'Attendance': None
    },

    # -------------------- 21 December 2002 - Matchweek 19 --------------------
    ('West Ham', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': None
    },

    ('West Brom', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': None
    },

    ('Arsenal', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': None
    },

    ('Leeds', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': None
    },

    ('Chelsea', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': None
    },

    ('Birmingham', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': None
    },

    ('Newcastle', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': None
    },

    ('Liverpool', 'Everton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 19,
        'Attendance': None
    },

    ('Blackburn', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 19,
        'Attendance': None
    },

    ('Man City', 'Tottenham'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 19,
        'Attendance': None
    },

    # -------------------- 26 December 2002 - Matchweek 20 --------------------
    ('Birmingham', 'Everton'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': None
    },

    ('Bolton', 'Newcastle'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': None
    },

    ('Chelsea', 'Southampton'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': None
    },

    ('Liverpool', 'Blackburn'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': None
    },

    ('Sunderland', 'Leeds'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': None
    },

    ('Tottenham', 'Charlton'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': None
    },

    ('West Brom', 'Arsenal'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': None
    },

    ('West Ham', 'Fulham'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': None
    },

    ('Middlesbrough', 'Man United'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': None
    },

    # -------------------- 28 December 2002 - Matchweek 21 --------------------
    ('Man United', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 21,
        'Attendance': None
    },

    ('Southampton', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 21,
        'Attendance': None
    },
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0203',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [14]:
null_rows(df, "0203", 'WeekDay')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
3785         Fulham       Man City  2002     12   28
3786        Everton         Bolton  2002     12   28
3787       Charlton      West Brom  2002     12   28
3788    Aston Villa  Middlesbrough  2002     12   28
3789      Blackburn       West Ham  2002     12   28
3790          Leeds        Chelsea  2002     12   28
3791        Arsenal      Liverpool  2002     12   29
3792      Newcastle      Tottenham  2002     12   29
3793    Southampton      Tottenham  2003      1    1
3794      Newcastle      Liverpool  2003      1    1
3795          Leeds     Birmingham  2003      1    1
3796        Everton       Man City  2003      1    1
3797      Blackburn  Middlesbrough  2003      1    1
3798    Aston Villa         Bolton  2003      1    1
3799        Arsenal        Chelsea  2003      1    1
3800     Man United     Sunderland  2003      1    1
3801       West Ham      Newcastle  2003      1   11
3802      West Brom     Man United  2003      1   11
3803       Man City          Leeds  2003      1   11
3804  Middlesbrough    Southampton  2003      1   11
3805         Bolton         Fulham  2003      1   11
3806     Sunderland      Blackburn  2003      1   11
3807        Chelsea       Charlton  2003      1   11
3808      Liverpool    Aston Villa  2003      1   11
3809     Birmingham        Arsenal  2003      1   12
3810      Tottenham        Everton  2003      1   12
3811    Southampton      Liverpool  2003      1   18
3812      Newcastle       Man City  2003      1   18
3813    Aston Villa      Tottenham  2003      1   18
3814          Leeds      West Brom  2003      1   18
3815        Everton     Sunderland  2003      1   18
3816      Blackburn     Birmingham  2003      1   18
3817       Charlton         Bolton  2003      1   18
3818     Man United        Chelsea  2003      1   18
3819        Arsenal       West Ham  2003      1   19
3820         Fulham  Middlesbrough  2003      1   19
3821       Charlton       West Ham  2003      1   22
3822      Newcastle         Bolton  2003      1   22
3823         Bolton        Everton  2003      1   28
3824        Chelsea          Leeds  2003      1   28
3825  Middlesbrough    Aston Villa  2003      1   28
3826     Sunderland    Southampton  2003      1   28
3827       West Ham      Blackburn  2003      1   29
3828      Tottenham      Newcastle  2003      1   29
3829      Liverpool        Arsenal  2003      1   29
3830      West Brom       Charlton  2003      1   29
3831       Man City         Fulham  2003      1   29
3832        Arsenal         Fulham  2003      2    1
3833         Bolton     Birmingham  2003      2    1
3834        Chelsea      Tottenham  2003      2    1
3835        Everton          Leeds  2003      2    1
3836       Man City      West Brom  2003      2    1
3837    Southampton     Man United  2003      2    1
3838     Sunderland       Charlton  2003      2    1
3839    Aston Villa      Blackburn  2003      2    2
3840       West Ham      Liverpool  2003      2    2
3841     Birmingham     Man United  2003      2    4
3842      Tottenham     Sunderland  2003      2    8
3843      West Brom         Bolton  2003      2    8
3844         Fulham    Aston Villa  2003      2    8
3845     Birmingham        Chelsea  2003      2    8
3846          Leeds       West Ham  2003      2    8
3847      Liverpool  Middlesbrough  2003      2    8
3848       Charlton        Everton  2003      2    8
3849      Blackburn    Southampton  2003      2    8
3850      Newcastle        Arsenal  2003      2    9
3851     Man United       Man City  2003      2    9
3852         Fulham      West Brom  2003      2   19
3853         Bolton     Man United  2003      2   22
3854       Charlton    Aston Villa  2003      2   22
3855        Chelsea      Blackburn  2003      2   22
3856        Everton    Southampton  2003      2   22
3857          Leeds      Newcastle  2003      2   22
3858       Man City        Arsenal  2003      2   22
3859     Sunderland  Middlesbrough  2003      2   22
3860     Birmingham      Liverpool  2003      2   23
3861      West Brom       West Ham  2003      2   23
3862      Tottenham         Fulham  2003      2   24
3863       West Ham      Tottenham  2003      3    1
3864    Southampton      West Brom  2003      3    1
3865  Middlesbrough        Everton  2003      3    1
3866         Fulham     Sunderland  2003      3    1
3867      Blackburn       Man City  2003      3    1
3868      Newcastle        Chelsea  2003      3    1
3869        Arsenal       Charlton  2003      3    2
3870    Aston Villa     Birmingham  2003      3    3
3871     Man United          Leeds  2003      3    5
3872  Middlesbrough      Newcastle  2003      3    5
3873      Liverpool         Bolton  2003      3    8
3874    Aston Villa     Man United  2003      3   15
3875      Blackburn        Arsenal  2003      3   15
3876       Charlton      Newcastle  2003      3   15
3877         Fulham    Southampton  2003      3   15
3878          Leeds  Middlesbrough  2003      3   15
3879     Sunderland         Bolton  2003      3   15
3880        Everton       West Ham  2003      3   15
3881       Man City     Birmingham  2003      3   16
3882      Tottenham      Liverpool  2003      3   16
3883      West Brom        Chelsea  2003      3   16
3884       West Ham     Sunderland  2003      3   22

In [ ]:
match_data = {
    # -------------------- 28 December 2002 - Matchweek 21 --------------------
    ('Fulham', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 21,
        'Attendance': 17937
    },  # Source: FBref [0L30-L31], FootballCritic [1L8]

    ('Everton', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 21,
        'Attendance': 39480
    },  # Source: ESPN [2L6-L7], Sky Sports [2L12]

    ('Charlton', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 21,
        'Attendance': 26196
    },  # Source: Sky Sports [3L8], FBref [3L22-L23]

    ('Aston Villa', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 21,
        'Attendance': 33637
    },  # Source: ESPN [4L7], 11v11 [4L16]

    ('Blackburn', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 21,
        'Attendance': 24998
    },  # Source: ESPN [5L7], Global Sports Archive [5L16]

    ('Leeds', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 21,
        'Attendance': 40122
    },  # Source: FBref [6L16-L17], stamford-bridge.com [6L7]

    ('Man United', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 21,
        'Attendance': 67640
    },  # Source: FBref [0L12-L13]

    # -------------------- 29 December 2002 - Matchweek 21 --------------------
    ('Arsenal', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 21,
        'Attendance': 38074
    },  # Source: ESPN [7L6-L7], LFChistory [7L13]

    ('Newcastle', 'Tottenham'): {
        'WeekDay': 'Sun', 'Time': '19:30', 'Round': 21,
        'Attendance': 52145
    },  # Source: ESPN [16L6-L7], FBref [16L25-L26]

    # -------------------- 1 January 2003 - Matchweek 22 --------------------
    ('Southampton', 'Tottenham'): {
        'WeekDay': 'Wed', 'Time': '15:00', 'Round': 22,
        'Attendance': 31890
    },  # Source: ESPN [17L6-L7], FBref [17L24-L25]

    ('Newcastle', 'Liverpool'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 22,
        'Attendance': 52147
    },  # Source: LFChistory [18L8], Sky Sports [18L12]

    ('Leeds', 'Birmingham'): {
        'WeekDay': 'Wed', 'Time': '15:00', 'Round': 22,
        'Attendance': 40034
    },  # Source: FBref [19L9], Sky Sports [19L13]

    ('Everton', 'Man City'): {
        'WeekDay': 'Wed', 'Time': '15:00', 'Round': 22,
        'Attendance': 40163
    },  # Source: TheFreeLibrary [20L17]

    ('Blackburn', 'Middlesbrough'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 22,
        'Attendance': 23413
    },  # Source: ESPN [21L7-L8], 11v11 [21L12]

    ('Aston Villa', 'Bolton'): {
        'WeekDay': 'Wed', 'Time': '15:00', 'Round': 22,
        'Attendance': 31838
    },  # Source: Sky Sports [22L8], AVFC History [22L11]

    ('Arsenal', 'Chelsea'): {
        'WeekDay': 'Wed', 'Time': '15:00', 'Round': 22,
        'Attendance': 38101
    },  # Source: FBref

    ('Man United', 'Sunderland'): {
        'WeekDay': 'Wed', 'Time': '15:00', 'Round': 22,
        'Attendance': 67650
    },  # Source: FBref

    # -------------------- 11 January 2003 - Matchweek 23 --------------------
    ('West Ham', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 35048
    },  # Source: ESPN [30L6-L7], Global Sports Archive [30L16]

    ('West Brom', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 27129
    },  # Source: Sky Sports [31L38], FBref [31L33]

    ('Man City', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 34884
    },  # Source: leeds-fans.org.uk [32L26]

    ('Middlesbrough', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 27443
    },  # Source: ESPN [33L7-L8], 11v11 [33L12]

    ('Bolton', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 25156
    },  # Source: ESPN [34L6-L7], Global Sports Archive [34L15]

    ('Sunderland', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 36529
    },  # Source: ESPN [35L7-L8], FBref [35L15]

    ('Chelsea', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 37284
    },  # Source: ESPN [36L7], stamford-bridge.com [36L16]

    ('Liverpool', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 43210
    },  # Source: LFChistory [37L7], Sky Sports [37L16]

    # -------------------- 12 January 2003 - Matchweek 23 --------------------
    ('Birmingham', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 23,
        'Attendance': 29505
    },  # Source: ESPN [38L7-L8], FBref [38L19]

    ('Tottenham', 'Everton'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 23,
        'Attendance': 36070
    },  # Source: 11v11 [39L8], THFCDB [39L12]

    # -------------------- 18 January 2003 - Matchweek 24 --------------------
    ('Southampton', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '17:35', 'Round': 24,
        'Attendance': 32104
    },  # Source: ESPN [40L7-L8], 11v11 [40L16]

    ('Newcastle', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 24,
        'Attendance': 52152
    },  # Source: ESPN [41L7], Sky Sports [41L12]

    ('Aston Villa', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 24,
        'Attendance': 38576
    },  # Source: Sky Sports [42L8], 11v11 [42L13]

    ('Leeds', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 24,
        'Attendance': 39708
    },  # Source: Global Sports Archive [43L8], FBref [43L13]

    ('Everton', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 24,
        'Attendance': 37409
    },  # Source: FBref [44L15-L16], Sky Sports [44L12]

    ('Blackburn', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 24,
        'Attendance': 23331
    },  # Source: ESPN [45L7], FBref [45L13]

    ('Charlton', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 24,
        'Attendance': 26057
    },  # Source: ESPN [46L7-L8], Sky Sports [46L19]

    ('Man United', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '12:30', 'Round': 24,
        'Attendance': 67606
    },  # Source: ESPN [47L7-L8]

    # -------------------- 19 January 2003 - Matchweek 24 --------------------
    ('Arsenal', 'West Ham'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 24,
        'Attendance': 38053
    },  # Source: ESPN [48L7], FBref [48L30]

    ('Fulham', 'Middlesbrough'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 24,
        'Attendance': 14253
    },  # Source: ESPN [49L7-L8], 11v11 [49L12]

    # -------------------- 22 January 2003 - Matchweek 22 --------------------
    ('Charlton', 'West Ham'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 22,
        'Attendance': 26340
    },  # Source: ESPN [50L11-L12], 11v11 [50L16]

    ('Newcastle', 'Bolton'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 22,
        'Attendance': 52005
    },  # Source: ESPN [51L11-L12], FBref [51L20-L21]

    # -------------------- 28 January 2003 - Matchweek 25 --------------------
    ('Bolton', 'Everton'): {
        'WeekDay': 'Tue', 'Time': '20:00', 'Round': 25,
        'Attendance': 25119
    },  # Source: ESPN [52L6-L7], FBref [52L16]

    ('Chelsea', 'Leeds'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 25,
        'Attendance': 38659
    },  # Source: FBref

    ('Middlesbrough', 'Aston Villa'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 25,
        'Attendance': 27602
    },  # Source: FBref

    ('Sunderland', 'Southampton'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 25,
        'Attendance': 30162
    },  # Source: FBref

    # -------------------- 29 January 2003 - Matchweek 25 --------------------
    ('West Ham', 'Blackburn'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 25,
        'Attendance': 34887
    },  # Source: FBref

    ('Tottenham', 'Newcastle'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 25,
        'Attendance': 35518
    },  # Source: FBref

    ('Liverpool', 'Arsenal'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 25,
        'Attendance': 44438
    },  # Source: FBref

    ('West Brom', 'Charlton'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 25,
        'Attendance': 26113
    },  # Source: FBref

    ('Man City', 'Fulham'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 25,
        'Attendance': 33473
    },  # Source: FBref

    # -------------------- 1 February 2003 - Matchweek 26 --------------------
    ('Arsenal', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 38022
    },  # Source: FBref

    ('Bolton', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 25178
    },  # Source: FBref

    ('Chelsea', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 40823
    },  # Source: FBref

    ('Everton', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 40164
    },  # Source: FBref

    ('Man City', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 34543
    },  # Source: FBref

    ('Southampton', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 32115
    },  # Source: FBref

    ('Sunderland', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 31682
    },  # Source: FBref

    # -------------------- 2 February 2003 - Matchweek 26 --------------------
    ('Aston Villa', 'Blackburn'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 26,
        'Attendance': 32403
    },  # Source: FBref

    ('West Ham', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 26,
        'Attendance': 35046
    },  # Source: FBref

    # -------------------- 4 February 2003 - Matchweek 26 --------------------
    ('Birmingham', 'Man United'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 26,
        'Attendance': 29125
    },  # Source: FBref

    # -------------------- 8 February 2003 - Matchweek 27 --------------------
    ('Tottenham', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 35350
    },  # Source: FBref

    ('West Brom', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 26491
    },  # Source: FBref

    ('Fulham', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 15555
    },  # Source: FBref

    ('Birmingham', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 29158
    },  # Source: FBref

    ('Leeds', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 36016
    },  # Source: FBref

    ('Liverpool', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 42777
    },  # Source: FBref

    ('Charlton', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 26568
    },  # Source: FBref

    ('Blackburn', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 22652
    },  # Source: FBref

    # -------------------- 9 February 2003 - Matchweek 27 --------------------
    ('Newcastle', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 27,
        'Attendance': 52128
    },  # Source: FBref

    ('Man United', 'Man City'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 27,
        'Attendance': 67641
    },  # Source: FBref

    # -------------------- 19 February 2003 - Matchweek 28 --------------------
    ('Fulham', 'West Brom'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 28,
        'Attendance': 14719
    },  # Source: FBref

    # -------------------- 22 February 2003 - Matchweek 28 --------------------
    ('Bolton', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 27020
    },  # Source: FBref

    ('Charlton', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 26506
    },  # Source: FBref

    ('Chelsea', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 40138
    },  # Source: FBref

    ('Everton', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 37332
    },  # Source: FBref

    ('Leeds', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 39065
    },  # Source: FBref

    ('Man City', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 34756
    },  # Source: FBref

    ('Sunderland', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 31358
    },  # Source: FBref

    # -------------------- 23 February 2003 - Matchweek 28 --------------------
    ('Birmingham', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 28,
        'Attendance': 29106
    },  # Source: FBref

    ('West Brom', 'West Ham'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 28,
        'Attendance': 26742
    },  # Source: FBref

    # -------------------- 24 February 2003 - Matchweek 28 --------------------
    ('Tottenham', 'Fulham'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 28,
        'Attendance': 35070
    },  # Source: FBref

    # -------------------- 1 March 2003 - Matchweek 29 --------------------
    ('West Ham', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 35049
    },  # Source: FBref

    ('Southampton', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 31915
    },  # Source: FBref

    ('Middlesbrough', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 30973
    },  # Source: FBref

    ('Fulham', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 15548
    },  # Source: FBref

    ('Blackburn', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 22772
    },  # Source: FBref

    ('Newcastle', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 52155
    },  # Source: FBref

    # -------------------- 2 March 2003 - Matchweek 29 --------------------
    ('Arsenal', 'Charlton'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 29,
        'Attendance': 38038
    },  # Source: FBref

    # -------------------- 3 March 2003 - Matchweek 29 --------------------
    ('Aston Villa', 'Birmingham'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 29,
        'Attendance': 40638
    },  # Source: FBref

    # -------------------- 5 March 2003 - Matchweek 29 --------------------
    ('Man United', 'Leeds'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 29,
        'Attendance': 67500
    },  # Source: FBref

    ('Middlesbrough', 'Newcastle'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 29,
        'Attendance': 33700
    },  # Source: FBref

    # -------------------- 8 March 2003 - Matchweek 30 --------------------
    ('Liverpool', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 42482
    },  # Source: FBref

    # -------------------- 15 March 2003 - Matchweek 31 --------------------
    ('Aston Villa', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '12:30', 'Round': 31,
        'Attendance': 42445
    },  # Source: FBref

    ('Blackburn', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 28380
    },  # Source: FBref

    ('Charlton', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 26515
    },  # Source: FBref

    ('Fulham', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 16655
    },  # Source: FBref

    ('Leeds', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 36193
    },  # Source: FBref

    ('Sunderland', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 30073
    },  # Source: FBref

    ('Everton', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 39108
    },  # Source: FBref

    # -------------------- 16 March 2003 - Matchweek 31 --------------------
    ('Man City', 'Birmingham'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 31,
        'Attendance': 33292
    },  # Source: FBref

    ('Tottenham', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 31,
        'Attendance': 36190
    },  # Source: FBref

    ('West Brom', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 31,
        'Attendance': 26977
    },  # Source: FBref

    # -------------------- 22 March 2003 - Matchweek 32 --------------------
    ('West Ham', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 35008
    },  # Source: FBref

    ('Birmingham', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 29124
    },  # Source: FBref

    ('Bolton', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 26203
    },  # Source: FBref

    ('Chelsea', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 40552
    },  # Source: FBref

    ('Man United', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 67604
    },  # Source: FBref

    ('Middlesbrough', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 32011
    },  # Source: FBref

    ('Newcastle', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 52189
    },  # Source: FBref

    ('Southampton', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 31567
    },  # Source: FBref

    ('Arsenal', 'Everton'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 32,
        'Attendance': 38036
    },  # Source: FBref

    ('Liverpool', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 32,
        'Attendance': 43827
    },  # Source: FBref
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0203',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [17]:
null_rows(df, "0203", 'WeekDay')

           HomeTeam       AwayTeam  Year  Month  Day
3893         Bolton      Tottenham  2003      3   24
3894     Man United      Liverpool  2003      4    5
3895       Charlton          Leeds  2003      4    5
3896    Aston Villa        Arsenal  2003      4    5
3897      Tottenham     Birmingham  2003      4    5
3899  Middlesbrough      West Brom  2003      4    5
3900    Southampton       West Ham  2003      4    5
3901     Sunderland        Chelsea  2003      4    5
3902        Everton      Newcastle  2003      4    6
3903         Fulham      Blackburn  2003      4    7
3904       West Ham    Aston Villa  2003      4   12
3905      Newcastle     Man United  2003      4   12
3906      West Brom        Everton  2003      4   12
3907      Liverpool         Fulham  2003      4   12
3908          Leeds      Tottenham  2003      4   12
3909        Chelsea         Bolton  2003      4   12
3910      Blackburn       Charlton  2003      4   12
3911     Birmingham     Sunderland  2003      4   12
3912       Man City  Middlesbrough  2003      4   12
3913        Arsenal     Man United  2003      4   16
3914      Tottenham       Man City  2003      4   18
3915    Southampton          Leeds  2003      4   19
3916     Sunderland      West Brom  2003      4   19
3917  Middlesbrough        Arsenal  2003      4   19
3918         Fulham      Newcastle  2003      4   19
3919        Everton      Liverpool  2003      4   19
3920       Charlton     Birmingham  2003      4   19
3921         Bolton       West Ham  2003      4   19
3922    Aston Villa        Chelsea  2003      4   19
3923     Man United      Blackburn  2003      4   19
3924     Birmingham    Southampton  2003      4   21
3925      Blackburn         Bolton  2003      4   21
3926        Chelsea        Everton  2003      4   21
3927      Liverpool       Charlton  2003      4   21
3928       Man City     Sunderland  2003      4   21
3929      Newcastle    Aston Villa  2003      4   21
3930      West Brom      Tottenham  2003      4   21
3931       West Ham  Middlesbrough  2003      4   21
3932          Leeds         Fulham  2003      4   22
3933     Sunderland      Newcastle  2003      4   26
3934          Leeds      Blackburn  2003      4   26
3935      West Brom      Liverpool  2003      4   26
3936        Chelsea         Fulham  2003      4   26
3937     Birmingham  Middlesbrough  2003      4   26
3938         Bolton        Arsenal  2003      4   26
3939        Everton    Aston Villa  2003      4   26
3940       Charlton    Southampton  2003      4   26
3941      Tottenham     Man United  2003      4   27
3942       Man City       West Ham  2003      4   27
3943    Southampton         Bolton  2003      5    3
3944      Newcastle     Birmingham  2003      5    3
3945    Aston Villa     Sunderland  2003      5    3
3946     Man United       Charlton  2003      5    3
3947      Liverpool       Man City  2003      5    3
3948         Fulham        Everton  2003      5    3
3949      Blackburn      West Brom  2003      5    3
3950  Middlesbrough      Tottenham  2003      5    3
3951       West Ham        Chelsea  2003      5    3
3952        Arsenal          Leeds  2003      5    4
3953        Arsenal    Southampton  2003      5    7
3954     Sunderland        Arsenal  2003      5   11
3955      West Brom      Newcastle  2003      5   11
3956      Tottenham      Blackburn  2003      5   11
3957       Man City    Southampton  2003      5   11
3958        Everton     Man United  2003      5   11
3959        Chelsea      Liverpool  2003      5   11
3960       Charlton         Fulham  2003      5   11
3961     Birmingham       West Ham  2003      5   11
3962         Bolton  Middlesbrough  2003      5   11
3963          Leeds    Aston Villa  2003      5   11

In [ ]:
match_data = {
    # -------------------- 24 March 2003 - Matchweek 31 --------------------
    ('Bolton', 'Tottenham'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 31,
        'Attendance': 23084
    },  # Source: ESPN [0L4-L7], Sky Sports [0L12-L15]

    # -------------------- 5 April 2003 - Matchweek 32 --------------------
    ('Charlton', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 26274
    },  # Source: FBref [2L6-L7], Sky Sports [2L9-L11]

    ('Aston Villa', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 42602
    },  # Source: ESPN [3L6-L7], FBref [3L17-L18]

    ('Tottenham', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 36058
    },  # Source: ESPN [4L5-L7], 11v11 [4L14-L16]

    ('Middlesbrough', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '19:30', 'Round': 32,
        'Attendance': 30187
    },  # Source: ESPN [5L12-L13], FBref [5L25-L26]

    ('Southampton', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 31941
    },  # Source: ESPN [6L6-L7], FBref [6L10-L11]

    ('Sunderland', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 40011
    },  # Source: ESPN [13L5-L7], stamford-bridge.com [13L10-L11]

    ('Everton', 'Newcastle'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 32,
        'Attendance': 40031
    },  # Source: FBref [14L5-L6]

    ('Fulham', 'Blackburn'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 32,
        'Attendance': 14017
    },  # Source: Sky Sports [15L5-L7], FBref [15L10-L11]

    # -------------------- 12 April 2003 - Matchweek 33 --------------------
    ('West Ham', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 35029
    },  # Source: FBref [16L7-L8], Global Sports Archive [16L27-L28]

    ('Newcastle', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '17:00', 'Round': 33,
        'Attendance': 52164
    },  # Source: ESPN [17L6-L7], FBref [20L9-L10]

    ('West Brom', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 27039
    },  # Source: evertonresults.com [18L10]

    ('Liverpool', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 42120
    },  # Source: FBref [24L7-L8], LFChistory [24L11]

    ('Leeds', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 39560
    },  # Source: FBref [25L7-L8], SpursOdyssey [25L21]

    ('Chelsea', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '19:30', 'Round': 33,
        'Attendance': 39852
    },  # Source: ESPN [26L6-L7], 11v11 [26L14-L15]

    ('Blackburn', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 27506
    },  # Source: ESPN [27L6-L7], 11v11 [27L10-L11]

    ('Birmingham', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '19:30', 'Round': 33,
        'Attendance': 29132
    },  # Source: ESPN [28L7-L8], FBref [28L15-L16]

    ('Man City', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 34793
    },  # Source: FBref [30L31-L32], citytilidie [34L3]

    # -------------------- 16 April 2003 - Matchweek 35 --------------------
    ('Arsenal', 'Man United'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 35,
        'Attendance': 38164
    },  # Source: FBref [35L15-L16], Arsenal season wiki [38L9]

    # -------------------- 18 April 2003 - Matchweek 34 --------------------
    ('Tottenham', 'Man City'): {
        'WeekDay': 'Fri', 'Time': '15:00', 'Round': 34,
        'Attendance': 36075
    },  # Source: ESPN [36L6-L7], FBref [36L16]

    # -------------------- 19 April 2003 - Matchweek 34 --------------------
    ('Southampton', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '19:30', 'Round': 34,
        'Attendance': 32032
    },  # Source: ESPN [37L6-L7], FBref [37L12]

    ('Sunderland', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 36025
    },  # Source: ESPN [41L6-L7], FBref [41L14-L15]

    ('Middlesbrough', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 34724
    },  # Source: ESPN [42L7-L8], Sky Sports [42L10-L12]

    ('Fulham', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 17900
    },  # Source: Sky Sports [43L5-L7], FBref [43L10-L11]

    ('Everton', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 40162
    },  # Source: LFChistory [44L6-L7], FBref [44L9-L10]

    ('Charlton', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 25732
    },  # Source: ESPN [45L6-L7], 11v11 [45L10-L11]

    ('Bolton', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 27160
    },  # Source: FBref [46L7], ESPN [46L17-L18]

    ('Aston Villa', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 39358
    },  # Source: ESPN [47L6-L7], AVFC History [47L14]

    ('Man United', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 67626
    },  # Source: Sky Sports [48L5-L7]

    # -------------------- 21 April 2003 - Matchweek 35 --------------------
    ('Birmingham', 'Southampton'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 35,
        'Attendance': 29115
    },  # Source: Sky Sports [49L6-L8], FBref [49L12-L13]

    ('Blackburn', 'Bolton'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 35,
        'Attendance': 28862
    },  # Source: Sky Sports [50L6-L7], 11v11 [50L10-L11]

    ('Chelsea', 'Everton'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 35,
        'Attendance': 40875
    },  # Source: ESPN [51L6-L7], FBref [51L12]

    ('Liverpool', 'Charlton'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 35,
        'Attendance': 42010
    },  # Source: Sky Sports [55L5-L7], LFChistory [55L10-L11]

    ('Man City', 'Sunderland'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 35,
        'Attendance': 34357
    },  # Source: ESPN [56L6-L7], Wikipedia [56L14-L16]

    ('Newcastle', 'Aston Villa'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 35,
        'Attendance': 52015
    },  # Source: ESPN [57L10-L11], 11v11 [57L14-L15]

    ('West Brom', 'Tottenham'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 35,
        'Attendance': 26899
    },  # Source: Sky Sports [58L5-L8], FBref [58L11-L12]

    ('West Ham', 'Middlesbrough'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 35,
        'Attendance': 35019
    },  # Source: Sky Sports [59L6-L8]

    # -------------------- 22 April 2003 - Matchweek 35 --------------------
    ('Leeds', 'Fulham'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 35,
        'Attendance': 37220
    },  # Source: Sky Sports [60L5-L7], FBref [60L19-L20]

    # -------------------- 26 April 2003 - Matchweek 36 --------------------
    ('Sunderland', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 45067
    },  # Source: ESPN [61L6-L7], Sky Sports [61L13-L15]

    ('Leeds', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 38062
    },  # Source: Sky Sports [62L5-L7], FBref [62L11]

    ('West Brom', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 27128
    },  # Source: PremierLeague.com [63L6-L7], Sky Sports [63L10-L11]

    ('Chelsea', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 40792
    },  # Source: ESPN [64L6-L7], 11v11 [64L18-L19]

    ('Birmingham', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 28821
    },  # Source: Sky Sports [65L6-L8], 11v11 [65L15-L16]

    ('Bolton', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '12:30', 'Round': 36,
        'Attendance': 27253
    },  # Source: ESPN [66L6-L7], FBref [66L23-L24]

    ('Everton', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 40167
    },  # Source: Sky Sports [67L5-L7]

    ('Charlton', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 25894
    },  # Source: ESPN [68L6-L7], 11v11 [68L14-L15]

    # -------------------- 27 April 2003 - Matchweek 36 --------------------
    ('Tottenham', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 36,
        'Attendance': 36073
    },  # Source: ESPN [69L5-L6], 11v11 [69L10-L11]

    ('Man City', 'West Ham'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 36,
        'Attendance': 34815
    },  # Source: ESPN [75L6-L7], citytilidie [75L18-L19]

    # -------------------- 3 May 2003 - Matchweek 37 --------------------
    ('Southampton', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 37,
        'Attendance': 30951
    },  # Source: ESPN [76L6-L7], FBref [76L27-L28]

    ('Newcastle', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 37,
        'Attendance': 52146
    },  # Source: ESPN [77L6-L7], 11v11 [77L18-L19]

    ('Aston Villa', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 37,
        'Attendance': 36963
    },  # Source: ESPN [78L6-L7], FBref [78L22-L23]

    ('Man United', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '12:30', 'Round': 37,
        'Attendance': 67721
    },  # Source: ESPN [79L6-L7], Wikipedia [79L14]

    ('Liverpool', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 37,
        'Attendance': 44220
    },  # Source: FBref [80L11], Wikipedia [80L7]

    ('Fulham', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 37,
        'Attendance': 18385
    },  # Source: ESPN [81L6-L7]

    ('Blackburn', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 37,
        'Attendance': 27470
    },  # Source: Sky Sports [82L9-L11], FBref [82L21]

    ('Middlesbrough', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 37,
        'Attendance': 30230
    },  # Source: Sky Sports [83L10-L11], FBref [83L15-L16]

    ('West Ham', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 37,
        'Attendance': 35042
    },  # Source: ESPN [84L5-L6], FBref [84L14]

    # -------------------- 4 May 2003 - Matchweek 37 --------------------
    ('Arsenal', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 37,
        'Attendance': 38127
    },  # Source: ESPN [85L6-L7], Sky Sports [85L15-L16]

    # -------------------- 7 May 2003 - Matchweek 33 --------------------
    ('Arsenal', 'Southampton'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 33,
        'Attendance': 38052
    },  # Source: ESPN [86L5-L6], Global Sports Archive [86L15]

    # -------------------- 11 May 2003 - Matchweek 38 --------------------
    ('Sunderland', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': 40188
    },  # Source: ESPN [87L6-L7], 11v11 [87L10-L11]

    ('West Brom', 'Newcastle'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': 27036
    },  # Source: FBref [20L16-L17]

    ('Tottenham', 'Blackburn'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': None
    },

    ('Man City', 'Southampton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': None
    },

    ('Everton', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': None
    },

    ('Chelsea', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': None
    },

    ('Charlton', 'Fulham'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': 26108
    },  # Source: FBref [8L25-L26]

    ('Birmingham', 'West Ham'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': None
    },

    ('Bolton', 'Middlesbrough'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': None
    },

    ('Leeds', 'Aston Villa'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': None
    },
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0203',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [21]:
null_rows(df, "0203", 'Attendance')

           HomeTeam       AwayTeam  Year  Month  Day
3601         Bolton       Charlton  2002      8   24
3605       Charlton      Tottenham  2002      8   27
3607        Everton     Birmingham  2002      8   28
3608    Aston Villa       Man City  2002      8   28
3609          Leeds     Sunderland  2002      8   28
3610      Blackburn      Liverpool  2002      8   28
3612       Man City        Everton  2002      8   31
3613  Middlesbrough      Blackburn  2002      8   31
3614     Sunderland     Man United  2002      8   31
3615      Tottenham    Southampton  2002      8   31
3616      West Brom         Fulham  2002      8   31
3617       West Ham       Charlton  2002      8   31
3618         Bolton    Aston Villa  2002      9    1
3623  Middlesbrough     Sunderland  2002      9   10
3625      Newcastle          Leeds  2002      9   11
3626       West Ham      West Brom  2002      9   11
3627      Liverpool     Birmingham  2002      9   11
3628         Fulham      Tottenham  2002      9   11
3629    Aston Villa       Charlton  2002      9   11
3630      Blackburn        Chelsea  2002      9   11
3631     Man United         Bolton  2002      9   11
3633     Sunderland         Fulham  2002      9   14
3634       Charlton        Arsenal  2002      9   14
3635        Everton  Middlesbrough  2002      9   14
3636         Bolton      Liverpool  2002      9   14
3637        Chelsea      Newcastle  2002      9   14
3638          Leeds     Man United  2002      9   14
3639       Man City      Blackburn  2002      9   15
3640      Tottenham       West Ham  2002      9   15
3641     Birmingham    Aston Villa  2002      9   16
3643      Liverpool      West Brom  2002      9   21
3644     Man United      Tottenham  2002      9   21
3645  Middlesbrough     Birmingham  2002      9   21
3646      Newcastle     Sunderland  2002      9   21
3647    Southampton       Charlton  2002      9   21
3648       West Ham       Man City  2002      9   21
3649    Aston Villa        Everton  2002      9   22
3650      Blackburn          Leeds  2002      9   22
3651         Fulham        Chelsea  2002      9   23
3653       Man City      Liverpool  2002      9   28
3654     Sunderland    Aston Villa  2002      9   28
3655        Everton         Fulham  2002      9   28
3656     Birmingham      Newcastle  2002      9   28
3657         Bolton    Southampton  2002      9   28
3658          Leeds        Arsenal  2002      9   28
3659       Charlton     Man United  2002      9   28
3660        Chelsea       West Ham  2002      9   28
3661      West Brom      Blackburn  2002      9   30
3663      Newcastle      West Brom  2002     10    5
3664    Southampton       Man City  2002     10    5
3665       West Ham     Birmingham  2002     10    5
3666        Arsenal     Sunderland  2002     10    6
3667      Blackburn      Tottenham  2002     10    6
3668         Fulham       Charlton  2002     10    6
3670    Aston Villa          Leeds  2002     10    6
3671     Man United        Everton  2002     10    7
3673      West Brom     Birmingham  2002     10   19
3674       Man City        Chelsea  2002     10   19
3675         Fulham     Man United  2002     10   19
3676        Everton        Arsenal  2002     10   19
3677          Leeds      Liverpool  2002     10   19
3678      Blackburn      Newcastle  2002     10   19
3679       Charlton  Middlesbrough  2002     10   20
3680      Tottenham         Bolton  2002     10   20
3681    Aston Villa    Southampton  2002     10   21
3734     Birmingham      Tottenham  2002     11   30
3735        Chelsea     Sunderland  2002     11   30
3736      Blackburn         Fulham  2002     11   30
3737        Arsenal    Aston Villa  2002     11   30
3738       Man City         Bolton  2002     11   30
3739          Leeds       Charlton  2002     12    1
3740      Liverpool     Man United  2002     12    1
3741      Newcastle        Everton  2002     12    1
3742       West Ham    Southampton  2002     12    2
3743    Southampton     Birmingham  2002     12    7
3744  Middlesbrough       West Ham  2002     12    7
3745         Bolton      Blackburn  2002     12    7
3746         Fulham          Leeds  2002     12    7
3747        Everton        Chelsea  2002     12    7
3748    Aston Villa      Newcastle  2002     12    7
3749       Charlton      Liverpool  2002     12    7
3750     Man United        Arsenal  2002     12    7
3751      Tottenham      West Brom  2002     12    8
3752     Sunderland       Man City  2002     12    9
3753  Middlesbrough        Chelsea  2002     12   14
3754    Southampton      Newcastle  2002     12   14
3755        Everton      Blackburn  2002     12   14
3756       Charlton       Man City  2002     12   14
3757    Aston Villa      West Brom  2002     12   14
3758     Man United       West Ham  2002     12   14
3759         Fulham     Birmingham  2002     12   15
3760     Sunderland      Liverpool  2002     12   15
3761      Tottenham        Arsenal  2002     12   15
3762         Bolton          Leeds  2002     12   16
3763       West Ham         Bolton  2002     12   21
3764      West Brom     Sunderland  2002     12   21
3765        Arsenal  Middlesbrough  2002     12   21
3766          Leeds    Southampton  2002     12   21
3767        Chelsea    Aston Villa  2002     12   21
3768     Birmingham       Charlton  2002     12   21
3769      Newcastle         Fulham  2002     12   21
3770      Liverpool        Everton  2002     12   22
3771      Blackburn     Man United  2002     12   22
3772       Man City      Tottenham  2002     12   23
3773     Birmingham        Everton  2002     12   26
3774         Bolton      Newcastle  2002     12   26
3775        Chelsea    Southampton  2002     12   26
3776      Liverpool      Blackburn  2002     12   26
3777       Man City    Aston Villa  2002     12   26
3778     Sunderland          Leeds  2002     12   26
3779      Tottenham       Charlton  2002     12   26
3780      West Brom        Arsenal  2002     12   26
3781       West Ham         Fulham  2002     12   26
3782  Middlesbrough     Man United  2002     12   26
3784    Southampton     Sunderland  2002     12   28
3894     Man United      Liverpool  2003      4    5
3956      Tottenham      Blackburn  2003      5   11
3957       Man City    Southampton  2003      5   11
3958        Everton     Man United  2003      5   11
3959        Chelsea      Liverpool  2003      5   11
3961     Birmingham       West Ham  2003      5   11
3962         Bolton  Middlesbrough  2003      5   11
3963          Leeds    Aston Villa  2003      5   11

In [ ]:
match_data = {
    # -------------------- 24 August 2002 - Matchweek 2 --------------------
    ('Bolton', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 2,
        'Attendance': 21753
    },  # Source: ESPN [0L6-L7], FBref [0L25-L26]

    # -------------------- 27 August 2002 - Matchweek 3 --------------------
    ('Charlton', 'Tottenham'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 3,
        'Attendance': 26461
    },  # Source: ESPN [1L6-L7], Sky Sports [1L24-L25]

    # -------------------- 28 August 2002 - Matchweek 3 --------------------
    ('Everton', 'Birmingham'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 3,
        'Attendance': 37197
    },  # Source: ESPN [2L6-L7], 11v11 [2L14-L15]

    ('Aston Villa', 'Man City'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 3,
        'Attendance': 33494
    },  # Source: ESPN [3L6-L7], citytilidie [3L31]

    ('Leeds', 'Sunderland'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 3,
        'Attendance': 39929
    },  # Source: Sky Sports [4L7], FBref [4L11-L12]

    ('Blackburn', 'Liverpool'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 3,
        'Attendance': 29207
    },  # Source: Sky Sports [5L7], LFChistory [5L10]

    # -------------------- 31 August 2002 - Matchweek 4 --------------------
    ('Man City', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 34835
    },  # Source: 11v11 [6L7], Sky Sports [6L11]

    ('Middlesbrough', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 28270
    },  # Source: ESPN [14L6-L7], FBref [14L24]

    ('Sunderland', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 47586
    },  # Source: ESPN [15L6], 11v11 [15L10-L11]

    ('Tottenham', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 35573
    },  # Source: ESPN [16L7], Sky Sports [16L15]

    ('West Brom', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 25461
    },  # Source: Sky Sports [17L7], Albion Till We Die [17L17-L18]

    ('West Ham', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 32424
    },  # Source: FBref [18L8], ESPN [18L12-L13]

    ('Bolton', 'Aston Villa'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 4,
        'Attendance': 22500
    },  # Source: ESPN [19L6-L7], Telegraph [19L28]

    # -------------------- 10 September 2002 - Matchweek 5 --------------------
    ('Middlesbrough', 'Sunderland'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 5,
        'Attendance': 32155
    },  # Source: ESPN [20L6-L7], Sky Sports [20L17-L18]

    # -------------------- 11 September 2002 - Matchweek 5 --------------------
    ('Newcastle', 'Leeds'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 5,
        'Attendance': 51730
    },  # Source: Wikipedia [28L7], Sky Sports [28L17-L18]

    ('West Ham', 'West Brom'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 5,
        'Attendance': 34957
    },  # Source: ESPN [29L6-L7], FBref [29L12-L13]

    ('Liverpool', 'Birmingham'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 5,
        'Attendance': 43113
    },  # Source: LFChistory [30L7], FBref [30L10-L11]

    ('Fulham', 'Tottenham'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 5,
        'Attendance': 16757
    },  # Source: Fulham Fandom [31L7], Global Sports Archive [31L11-L12]

    ('Aston Villa', 'Charlton'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 5,
        'Attendance': 26483
    },  # Source: ESPN [32L6-L7], AVFC History [32L14-L15]

    ('Blackburn', 'Chelsea'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 5,
        'Attendance': 22999
    },  # Source: ESPN [33L6-L7], 11v11 [33L14-L15]

    ('Man United', 'Bolton'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 5,
        'Attendance': 67623
    },  # Source: ESPN [34L6-L7], FBref [34L12-L13]

    # -------------------- 14 September 2002 - Matchweek 6 --------------------
    ('Sunderland', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': 35432
    },  # Source: 11v11 [35L6-L7], Sky Sports [35L10-L11]

    ('Charlton', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': 26080
    },  # Source: ESPN [36L6-L7], 11v11 [36L10-L11]

    ('Everton', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': 32240
    },  # Source: ESPN [37L6-L7], FBref [37L28]

    ('Bolton', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': 27328
    },  # Source: ESPN [38L6-L7], LFChistory [38L18-L19]

    ('Chelsea', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': 39746
    },  # Source: ESPN [39L6-L7], 11v11 [39L14-L15]

    ('Leeds', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 6,
        'Attendance': 39622
    },  # Source: ESPN [40L6-L7], Sky Sports [40L22-L23]

    ('Man City', 'Blackburn'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 6,
        'Attendance': 34130
    },  # Source: citytilidie [41L6-L7], FBref [41L25-L26]

    ('Tottenham', 'West Ham'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 6,
        'Attendance': 36005
    },  # Source: ESPN [42L6-L7], 11v11 [42L23-L24]

    ('Birmingham', 'Aston Villa'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 6,
        'Attendance': 29505
    },  # Source: ESPN [43L6-L7], 11v11 [43L14]

    # -------------------- 21 September 2002 - Matchweek 7 --------------------
    ('Liverpool', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': 43830
    },  # Source: Sky Sports [44L7], LFChistory [44L11]

    ('Man United', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': 67611
    },  # Source: ESPN [45L7], 11v11 [45L15]

    ('Middlesbrough', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': 29869
    },  # Source: ESPN [46L6-L7], FBref [46L28]

    ('Newcastle', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '12:15', 'Round': 7,
        'Attendance': 52181
    },  # Source: Wikipedia [47L8], Sky Sports [47L12]

    ('Southampton', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': 25714
    },  # Source: ESPN [48L6-L7], Wikipedia [48L18]

    ('West Ham', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': 35550
    },  # Source: ESPN [49L6-L7], citytilidie [49L18-L19]

    ('Aston Villa', 'Everton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 7,
        'Attendance': 30023
    },  # Source: ESPN [50L6-L7], AVFC History [50L17]

    ('Blackburn', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 7,
        'Attendance': 25415
    },  # Source: ESPN [51L6-L7], 11v11 [51L18-L19]

    ('Fulham', 'Chelsea'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 7,
        'Attendance': 16503
    },  # Source: ESPN [52L6], stamford-bridge [52L10]

    # -------------------- 28 September 2002 - Matchweek 8 --------------------
    ('Man City', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 35131
    },  # Source: Sky Sports [53L7], FBref [53L12]

    ('Sunderland', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 40492
    },  # Source: FBref [54L7-L8], 11v11 [54L12]

    ('Everton', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 34371
    },  # Source: Sky Sports [55L7], Global Sports Archive [55L11]

    ('Birmingham', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 29072
    },  # Source: Global Sports Archive [56L8], Wikipedia [56L15]

    ('Bolton', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 22692
    },  # Source: ESPN [57L7], FBref [57L16]

    ('Leeds', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 40199
    },  # Source: Sky Sports [58L7], FBref [58L11-L12]

    ('Charlton', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 26630
    },  # Source: Sky Sports [59L8], ESPN [59L12]

    ('Chelsea', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 38929
    },  # Source: Sky Sports [60L7], stamford-bridge [60L12]

    ('West Brom', 'Blackburn'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 8,
        'Attendance': 25170
    },  # Source: Sky Sports [61L7], FBref [61L16]

    # -------------------- 5 October 2002 - Matchweek 9 --------------------
    ('Newcastle', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': 52142
    },  # Source: ESPN [62L6-L7], Wikipedia [62L20]

    ('Southampton', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': 31009
    },  # Source: ESPN [63L6-L7], Global Sports Archive [63L16]

    ('West Ham', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': 35010
    },  # Source: 11v11 [64L7], ESPN [64L10]

    ('Arsenal', 'Sunderland'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 9,
        'Attendance': 37902
    },  # Source: Sky Sports [65L7], FBref [65L12]

    ('Blackburn', 'Tottenham'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 9,
        'Attendance': 26203
    },  # Source: ESPN [66L6-L7], 11v11 [66L10-L11]

    ('Fulham', 'Charlton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 9,
        'Attendance': 14775
    },  # Source: ESPN [67L6-L7], Sky Sports [67L17]

    ('Liverpool', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 9,
        'Attendance': 43856
    },  # Source: LFChistory [68L6-L7], FBref [68L18]

    ('Aston Villa', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 9,
        'Attendance': 33505
    },  # Source: ESPN [69L6-L7], AVFC History [69L14]

    ('Man United', 'Everton'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 9,
        'Attendance': 67629
    },  # Source: ESPN [70L6-L7], Sky Sports [70L10-L11]

    # -------------------- 19 October 2002 - Matchweek 10 --------------------
    ('West Brom', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 27021
    },  # Source: Albion Till We Die [71L7], Global Sports Archive [71L11-L12]

    ('Man City', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 34953
    },  # Source: stamford-bridge [72L7], citytilidie [72L14]

    ('Fulham', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 18103
    },  # Source: ESPN [73L7], FBref [73L16]

    ('Everton', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 39038
    },  # Source: 11v11 [74L6-L7], Sky Sports [74L12]

    ('Leeds', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 40187
    },  # Source: ESPN [75L6], Global Sports Archive [75L10]

    ('Blackburn', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 27307
    },  # Source: ESPN [76L6-L7], 11v11 [76L14-L15]

    ('Charlton', 'Middlesbrough'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 10,
        'Attendance': 26271
    },  # Source: FBref [77L8], Sky Sports [77L13]

    ('Tottenham', 'Bolton'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 10,
        'Attendance': 35909
    },  # Source: ESPN [78L6-L7], FBref [78L16]

    ('Aston Villa', 'Southampton'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 10,
        'Attendance': 25817
    },  # Source: ESPN [79L6-L7], Sky Sports [79L11]

    # -------------------- 23 October 2002 - Matchweek 10 --------------------
    ('Fulham', 'West Ham'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 10,
        'Attendance': 15858
    },  # Source: ESPN [80L6-L7], Sky Sports [80L18-L19]

    # -------------------- 26 October 2002 - Matchweek 11 --------------------
    ('Arsenal', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 38064
    },  # Source: Sky Sports [81L7], FBref [81L15-L16]

    ('Birmingham', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 29316
    },  # Source: Sky Sports [82L7], citytilidie [82L17-L18]

    ('Chelsea', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 40893
    },  # Source: ESPN [83L7], stamford-bridge [83L11]

    ('Liverpool', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 44084
    },  # Source: Sky Sports [84L7], LFChistory [84L11]

    ('Man United', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 67619
    },  # Source: ESPN [85L7], Sky Sports [85L15]

    ('Middlesbrough', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 34723
    },  # Source: FBref [86L8], ESPN [86L13]

    ('Newcastle', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 51670
    },  # Source: Sky Sports [87L7], Wikipedia [87L15]

    ('Southampton', 'Fulham'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 11,
        'Attendance': 26188
    },  # Source: ESPN [88L6-L7], FBref [88L12]

    ('West Ham', 'Everton'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 11,
        'Attendance': 34117
    },  # Source: ESPN [89L6-L7], Sky Sports [89L23-L24]

    ('Bolton', 'Sunderland'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 11,
        'Attendance': 23036
    },  # Source: ESPN [90L6-L7], FBref [90L16]

    # -------------------- 11 May 2003 - Matchweek 38 --------------------
    ('Tottenham', 'Blackburn'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': 36036
    },  # Source: ESPN [91L6-L7], THFCDB [91L13-L14]

    ('Man City', 'Southampton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': 34957
    },  # Source: Sky Sports [92L7], BBC [92L26]

    ('Everton', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': 40618
    },  # Source: FBref [93L27], FBref [93L33]

    # -------------------- Missing Data --------------------
    ('Bolton', 'Middlesbrough'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': None
    },

    ('Leeds', 'Aston Villa'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': None
    },
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0203',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [24]:
null_rows(df, "0203", 'Attendance')

           HomeTeam       AwayTeam  Year  Month  Day
3734     Birmingham      Tottenham  2002     11   30
3735        Chelsea     Sunderland  2002     11   30
3736      Blackburn         Fulham  2002     11   30
3737        Arsenal    Aston Villa  2002     11   30
3738       Man City         Bolton  2002     11   30
3739          Leeds       Charlton  2002     12    1
3740      Liverpool     Man United  2002     12    1
3741      Newcastle        Everton  2002     12    1
3742       West Ham    Southampton  2002     12    2
3743    Southampton     Birmingham  2002     12    7
3744  Middlesbrough       West Ham  2002     12    7
3745         Bolton      Blackburn  2002     12    7
3746         Fulham          Leeds  2002     12    7
3747        Everton        Chelsea  2002     12    7
3748    Aston Villa      Newcastle  2002     12    7
3749       Charlton      Liverpool  2002     12    7
3750     Man United        Arsenal  2002     12    7
3751      Tottenham      West Brom  2002     12    8
3752     Sunderland       Man City  2002     12    9
3753  Middlesbrough        Chelsea  2002     12   14
3754    Southampton      Newcastle  2002     12   14
3755        Everton      Blackburn  2002     12   14
3756       Charlton       Man City  2002     12   14
3757    Aston Villa      West Brom  2002     12   14
3758     Man United       West Ham  2002     12   14
3759         Fulham     Birmingham  2002     12   15
3760     Sunderland      Liverpool  2002     12   15
3761      Tottenham        Arsenal  2002     12   15
3762         Bolton          Leeds  2002     12   16
3763       West Ham         Bolton  2002     12   21
3764      West Brom     Sunderland  2002     12   21
3765        Arsenal  Middlesbrough  2002     12   21
3766          Leeds    Southampton  2002     12   21
3767        Chelsea    Aston Villa  2002     12   21
3768     Birmingham       Charlton  2002     12   21
3769      Newcastle         Fulham  2002     12   21
3770      Liverpool        Everton  2002     12   22
3771      Blackburn     Man United  2002     12   22
3772       Man City      Tottenham  2002     12   23
3773     Birmingham        Everton  2002     12   26
3774         Bolton      Newcastle  2002     12   26
3775        Chelsea    Southampton  2002     12   26
3776      Liverpool      Blackburn  2002     12   26
3777       Man City    Aston Villa  2002     12   26
3778     Sunderland          Leeds  2002     12   26
3779      Tottenham       Charlton  2002     12   26
3780      West Brom        Arsenal  2002     12   26
3781       West Ham         Fulham  2002     12   26
3782  Middlesbrough     Man United  2002     12   26
3784    Southampton     Sunderland  2002     12   28
3894     Man United      Liverpool  2003      4    5
3959        Chelsea      Liverpool  2003      5   11
3961     Birmingham       West Ham  2003      5   11
3962         Bolton  Middlesbrough  2003      5   11
3963          Leeds    Aston Villa  2003      5   11

In [ ]:
match_data = {
    # -------------------- 30 November 2002 - Matchweek 16 --------------------
    ('Birmingham', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 29505
    },  # Source: ESPN [0L7-L8], Sky Sports [0L12]

    ('Chelsea', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 38946
    },  # Source: ESPN [1L7], stamford-bridge.com [1L11]

    ('Blackburn', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 21096
    },  # Source: Global Sports Archive [2L7], FBref [2L17]

    ('Arsenal', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 38090
    },  # Source: ESPN [3L6], FBref [3L18]

    ('Man City', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 34860
    },  # Source: ESPN [4L6], FBref [4L11]

    # -------------------- 1 December 2002 - Matchweek 16 --------------------
    ('Leeds', 'Charlton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 16,
        'Attendance': 35537
    },  # Source: ESPN [5L6-L7], FBref [5L15]

    ('Liverpool', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '13:15', 'Round': 16,
        'Attendance': 44250
    },  # Source: footymags.com [6L8], FBref [6L13]

    ('Newcastle', 'Everton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 16,
        'Attendance': 51607
    },  # Source: 11v11.com [7L7], Sky Sports [7L11]

    # -------------------- 2 December 2002 - Matchweek 16 --------------------
    ('West Ham', 'Southampton'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 16,
        'Attendance': 28844
    },  # Source: ESPN [8L7], 11v11.com [8L15]

    # -------------------- 7 December 2002 - Matchweek 17 --------------------
    ('Southampton', 'Birmingham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 31132
    },  # Source: ESPN [9L7], FBref [9L20]

    ('Middlesbrough', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 28283
    },  # Source: ESPN [10L6], FBref [10L14]

    ('Bolton', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 24556
    },  # Source: ESPN [11L7], FBref [11L15]

    ('Fulham', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 17494
    },  # Source: ESPN [12L6], 11v11.com [12L11]

    ('Everton', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 39396
    },  # Source: stamford-bridge.com [13L7], Sky Sports [13L11]

    ('Aston Villa', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 33446
    },  # Source: ESPN [14L6-L7], AVFC History [14L15]

    ('Charlton', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 26694
    },  # Source: FBref [15L8], Sky Sports [15L13]

    ('Man United', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '12:15', 'Round': 17,
        'Attendance': 67650
    },  # Source: ESPN [16L7], FBref [16L12]

    # -------------------- 8 December 2002 - Matchweek 17 --------------------
    ('Tottenham', 'West Brom'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 17,
        'Attendance': 35958
    },  # Source: ESPN [17L7], thfcdb.com [17L20]

    # -------------------- 9 December 2002 - Matchweek 17 --------------------
    ('Sunderland', 'Man City'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 17,
        'Attendance': 36511
    },  # Source: FBref [18L6], Sky Sports [18L15]

    # -------------------- 14 December 2002 - Matchweek 18 --------------------
    ('Middlesbrough', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': 29160
    },  # Source: stamford-bridge.com [19L7], ESPN [19L10]

    ('Southampton', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': 32061
    },  # Source: ESPN [20L7], FBref [20L33]

    ('Everton', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': 36578
    },  # Source: Sky Sports [21L7], FBref [21L11]

    ('Charlton', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': 26434
    },  # Source: Sky Sports [22L8], citytilidie.com [22L18]

    ('Aston Villa', 'West Brom'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': 40391
    },  # Source: Sky Sports [23L7], AVFC History [23L14]

    ('Man United', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '12:15', 'Round': 18,
        'Attendance': 67555
    },  # Source: ESPN [24L8], FBref [24L18]

    # -------------------- 15 December 2002 - Matchweek 18 --------------------
    ('Fulham', 'Birmingham'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 18,
        'Attendance': 14962
    },  # Source: ESPN [25L6-L7], FBref [25L11]

    ('Sunderland', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 18,
        'Attendance': 37118
    },  # Source: LFChistory [26L6], ESPN [26L11]

    ('Tottenham', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 18,
        'Attendance': 36076
    },  # Source: ESPN [27L6], thfcdb.com [27L18]

    # -------------------- 16 December 2002 - Matchweek 18 --------------------
    ('Bolton', 'Leeds'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 18,
        'Attendance': 23378
    },  # Source: ESPN [28L7], FBref [28L23]

    # -------------------- 21 December 2002 - Matchweek 19 --------------------
    ('West Ham', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': 34892
    },  # Source: ESPN [29L5], FBref [29L25]

    ('West Brom', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': 26703
    },  # Source: Sky Sports [30L7], FBref [30L16]

    ('Arsenal', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': 38003
    },  # Source: 11v11.com [31L7], FBref [31L10]

    ('Leeds', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': 36687
    },  # Source: 11v11.com [32L7], FBref [32L21]

    ('Chelsea', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': 38284
    },  # Source: ESPN [33L6], stamford-bridge.com [33L11]

    ('Birmingham', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': 28837
    },  # Source: ESPN [34L8], FBref [34L16]

    ('Newcastle', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': 51576
    },  # Source: Sky Sports [35L7], FBref [35L16]

    # -------------------- 22 December 2002 - Matchweek 19 --------------------
    ('Liverpool', 'Everton'): {
        'WeekDay': 'Sun', 'Time': '16:05', 'Round': 19,
        'Attendance': 44025
    },  # Source: LFChistory [36L7], FBref [36L17]

    ('Blackburn', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 19,
        'Attendance': 30475
    },  # Source: ESPN [37L7], 11v11.com [37L24]

    # -------------------- 23 December 2002 - Matchweek 19 --------------------
    ('Man City', 'Tottenham'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 19,
        'Attendance': 34563
    },  # Source: Sky Sports [38L8], citytilidie.com [38L16]

    # -------------------- 26 December 2002 - Matchweek 20 --------------------
    ('Birmingham', 'Everton'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': 29505
    },  # Source: ESPN [39L7], FBref [39L24]

    ('Bolton', 'Newcastle'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': 27314
    },  # Source: ESPN [40L8], FBref [40L19]

    ('Chelsea', 'Southampton'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': 39428
    },  # Source: ESPN [41L7], stamford-bridge.com [41L11]

    ('Liverpool', 'Blackburn'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': 43075
    },  # Source: ESPN [42L7], LFChistory [42L27]

    ('Man City', 'Aston Villa'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': 33991
    },  # Source: 11v11.com [43L7], FBref [43L20]

    ('Sunderland', 'Leeds'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': 44029
    },  # Source: Sky Sports [44L7], FBref [44L23]

    ('Tottenham', 'Charlton'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': 36043
    },  # Source: ESPN [45L7], thfcdb.com [45L31]

    ('West Brom', 'Arsenal'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': 27025
    },  # Source: FBref [46L19], Transfermarkt [46L16]

    ('West Ham', 'Fulham'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': 35025
    },  # Source: ESPN [47L6], FBref [47L26]

    ('Middlesbrough', 'Man United'): {
        'WeekDay': 'Thu', 'Time': '15:00', 'Round': 20,
        'Attendance': 34673
    },  # Source: ESPN [48L7], FBref [48L17]

    # -------------------- 28 December 2002 - Matchweek 21 --------------------
    ('Southampton', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 21,
        'Attendance': 31423
    },  # Source: ESPN [49L7], FBref [49L14]

    # -------------------- 5 April 2003 - Matchweek 32 --------------------
    ('Man United', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '12:30', 'Round': 32,
        'Attendance': 67639
    },  # Source: ESPN [50L7], mufcinfo.com [50L14]

    # -------------------- 11 May 2003 - Matchweek 38 --------------------
    ('Chelsea', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': 41911
    },  # Source: ESPN [51L7], stamford-bridge.com [51L11]

    ('Birmingham', 'West Ham'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': 29505
    },  # Source: ESPN [52L6], 11v11.com [52L11]

    ('Bolton', 'Middlesbrough'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': 27241
    },  # Source: football-lineups.com [53L8], Sky Sports [53L12]

    ('Leeds', 'Aston Villa'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 38,
        'Attendance': None
    },  # Data not found in available sources
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0203',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [27]:
null_rows(df, "0203", 'Time')

         HomeTeam    AwayTeam  Year  Month  Day
3591      Arsenal  Birmingham  2002      8   18
3592  Aston Villa   Liverpool  2002      8   18
3593    Newcastle    West Ham  2002      8   19
3622      Arsenal    Man City  2002      9   10

In [32]:
match_data = {
    ('Arsenal', 'Birmingham'): {
        'Time': '15:00', 'Attendance': 38018
    },  # EPL
    ('Aston Villa', 'Liverpool'): {
        'Time': '14:00', 'Attendance': 41183
    },  # EPL
    ('Newcastle', 'West Ham'): {
        'Time': '20:00', 'Attendance': 51072
    },  # EPL
    ('Arsenal', 'Man City'): {
        'Time': '20:00', 'Attendance': 37878
    },  # EPL
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0203',
    data=match_data,
    value_col=['Time', 'Attendance'],
    inplace=True
)

In [34]:
null_rows(df, "0203", 'Attendance')

     HomeTeam     AwayTeam  Year  Month  Day
3963    Leeds  Aston Villa  2003      5   11

In [35]:
match_data = {
    ('Leeds', 'Aston Villa'): {
        'Attendance': 40205
    },  # EPL
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0203',
    data=match_data,
    value_col=['Attendance'],
    inplace=True
)

In [36]:
missing_report(df,"0203")

XGHome    380
XGAway    380
dtype: int64

In [37]:
df.to_csv("Data/Data8.csv", index=False)

---
$$ 2001-02 $$

In [39]:
missing_report(df,"0102")

WeekDay                          380
Time                             380
Round                            380
Attendance                       380
XGHome                           380
XGAway                           380
SeasonPosAway                     19
SeasonPlayedAway                  19
SeasonWinAway                     19
SeasonDrawAway                    19
SeasonLossAway                    19
SeasonGFAway                      19
SeasonGAAway                      19
SeasonGDAway                      19
SeasonPointsAway                  19
QualificationOrRelegationAway     19
dtype: int64

In [41]:
null_rows(df, '0102', 'SeasonPosAway')['AwayTeam'].unique()

array(['Bolton'], dtype=object)

In [42]:
# Season statistics for Bolton Wanderers in 2001-02
bolton_stats = {
    'SeasonPosAway': 16,
    'SeasonPlayedAway': 38,
    'SeasonWinAway': 8,
    'SeasonDrawAway': 13,
    'SeasonLossAway': 16,
    'SeasonGFAway': 44,
    'SeasonGAAway': 62,
    'SeasonGDAway': -18,
    'SeasonPointsAway': 40,
    'QualificationOrRelegationAway': 'Not Applicable'
}

# List of columns to fill
away_cols = [
    'SeasonPosAway', 'SeasonPlayedAway', 'SeasonWinAway', 'SeasonDrawAway',
    'SeasonLossAway', 'SeasonGFAway', 'SeasonGAAway', 'SeasonGDAway',
    'SeasonPointsAway', 'QualificationOrRelegationAway'
]

# Fill the columns for all rows where AwayTeam is 'Bolton' in the 2001-02 season
for idx, row in df[df['Season'] == '0102'].iterrows():
    if row['AwayTeam'] == 'Bolton':
        for col in away_cols:
            df.loc[(df['Season'] == '0102') & (df.index == idx), col] = bolton_stats[col]

In [43]:
null_rows(df, "0102", 'WeekDay')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
3204      Tottenham    Aston Villa  2001      8   18
3205  Middlesbrough        Arsenal  2001      8   18
3206     Sunderland        Ipswich  2001      8   18
3207       Charlton        Everton  2001      8   18
3208      Leicester         Bolton  2001      8   18
3209          Leeds    Southampton  2001      8   18
3210          Derby      Blackburn  2001      8   18
3211      Liverpool       West Ham  2001      8   18
3212        Chelsea      Newcastle  2001      8   19
3213     Man United         Fulham  2001      8   19
3214        Everton      Tottenham  2001      8   20
3215        Arsenal          Leeds  2001      8   21
3216         Bolton  Middlesbrough  2001      8   21
3217        Ipswich          Derby  2001      8   21
3218      Blackburn     Man United  2001      8   22
3219         Fulham     Sunderland  2001      8   22
3220       West Ham          Leeds  2001      8   25
3221    Southampton        Chelsea  2001      8   25
3222        Everton  Middlesbrough  2001      8   25
3223         Fulham          Derby  2001      8   25
3224        Arsenal      Leicester  2001      8   25
3225        Ipswich       Charlton  2001      8   25
3226      Blackburn      Tottenham  2001      8   25
3227    Aston Villa     Man United  2001      8   26
3228      Newcastle     Sunderland  2001      8   26
3229         Bolton      Liverpool  2001      8   27
3230     Sunderland      Blackburn  2001      9    8
3231  Middlesbrough      Newcastle  2001      9    8
3232          Leeds         Bolton  2001      9    8
3233      Liverpool    Aston Villa  2001      9    8
3234          Derby       West Ham  2001      9    8
3235        Chelsea        Arsenal  2001      9    8
3236     Man United        Everton  2001      9    8
3237      Leicester        Ipswich  2001      9    8
3238       Charlton         Fulham  2001      9    9
3239      Tottenham    Southampton  2001      9    9
3240         Bolton    Southampton  2001      9   15
3241          Derby      Leicester  2001      9   15
3242        Everton      Liverpool  2001      9   15
3243         Fulham        Arsenal  2001      9   15
3244  Middlesbrough       West Ham  2001      9   15
3245      Newcastle     Man United  2001      9   15
3246        Ipswich      Blackburn  2001      9   16
3247       Charlton          Leeds  2001      9   16
3248      Tottenham        Chelsea  2001      9   16
3249    Aston Villa     Sunderland  2001      9   16
3250      Leicester  Middlesbrough  2001      9   17
3251      Blackburn         Bolton  2001      9   19
3252     Sunderland      Tottenham  2001      9   19
3253     Sunderland       Charlton  2001      9   22
3254     Man United        Ipswich  2001      9   22
3255      Leicester         Fulham  2001      9   22
3256        Arsenal         Bolton  2001      9   22
3257      Blackburn        Everton  2001      9   22
3258      Liverpool      Tottenham  2001      9   22
3259        Chelsea  Middlesbrough  2001      9   23
3260          Leeds          Derby  2001      9   23
3261       West Ham      Newcastle  2001      9   23
3262    Southampton    Aston Villa  2001      9   24
3263      Newcastle      Leicester  2001      9   26
3264      Tottenham     Man United  2001      9   29
3265  Middlesbrough    Southampton  2001      9   29
3266          Derby        Arsenal  2001      9   29
3267       Charlton      Leicester  2001      9   29
3268         Bolton     Sunderland  2001      9   29
3269        Everton       West Ham  2001      9   29
3270    Aston Villa      Blackburn  2001      9   30
3271         Fulham        Chelsea  2001      9   30
3272        Ipswich          Leeds  2001      9   30
3273      Newcastle      Liverpool  2001      9   30
3274     Sunderland     Man United  2001     10   13
3275    Southampton        Arsenal  2001     10   13
3276        Chelsea      Leicester  2001     10   13
3277        Ipswich        Everton  2001     10   13
3278      Liverpool          Leeds  2001     10   13
3279         Bolton      Newcastle  2001     10   13
3280       Charlton  Middlesbrough  2001     10   13
3281    Aston Villa         Fulham  2001     10   14
3282      Blackburn       West Ham  2001     10   14
3283      Tottenham          Derby  2001     10   15
3284        Arsenal      Blackburn  2001     10   20
3285          Derby       Charlton  2001     10   20
3286        Everton    Aston Villa  2001     10   20
3287      Leicester      Liverpool  2001     10   20
3288     Man United         Bolton  2001     10   20
3289       West Ham    Southampton  2001     10   20
3290         Fulham        Ipswich  2001     10   21
3291      Newcastle      Tottenham  2001     10   21
3292          Leeds        Chelsea  2001     10   21
3293  Middlesbrough     Sunderland  2001     10   22
3294    Aston Villa       Charlton  2001     10   24
3295    Southampton        Ipswich  2001     10   24
3296       West Ham        Chelsea  2001     10   24
3297      Tottenham  Middlesbrough  2001     10   27
3298     Sunderland        Arsenal  2001     10   27
3299         Fulham    Southampton  2001     10   27
3300        Everton      Newcastle  2001     10   27
3301    Aston Villa         Bolton  2001     10   27
3302       Charlton      Liverpool  2001     10   27
3303     Man United          Leeds  2001     10   27

In [ ]:
match_data = {
    # -------------------- 18 August 2001 - Matchweek 1 --------------------
    ('Tottenham', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 36059
    },  # Source: FBref [6L19-L20]

    ('Middlesbrough', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 31557
    },  # Source: FBref [6L12-L13]

    ('Sunderland', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 47370
    },  # Source: FBref [6L18-L19]

    ('Charlton', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 20451
    },  # Source: FBref [6L13-L14]

    ('Leicester', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 21455
    },  # Source: FBref [6L15-L16]

    ('Leeds', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 39715
    },  # Source: FBref [6L16-L17]

    ('Derby', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 28236
    },  # Source: FBref [6L9-L10]

    ('Liverpool', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 1,
        'Attendance': 43935
    },  # Source: FBref [6L11-L12]

    ('Chelsea', 'Newcastle'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 1,
        'Attendance': 40124
    },  # Source: FBref [6L21-L22]

    ('Man United', 'Fulham'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 1,
        'Attendance': 67534
    },  # Source: FBref [6L22-L23]

    # -------------------- 20 August 2001 - Matchweek 2 --------------------
    ('Everton', 'Tottenham'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 2,
        'Attendance': 29503
    },  # Source: FBref [6L23-L24]

    # -------------------- 21 August 2001 - Matchweek 2 --------------------
    ('Arsenal', 'Leeds'): {
        'WeekDay': 'Tue', 'Time': '20:00', 'Round': 2,
        'Attendance': 38062
    },  # Source: FBref [6L25-L26]

    ('Ipswich', 'Derby'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 2,
        'Attendance': 21097
    },  # Source: FBref [6L26-L27]

    ('Bolton', 'Middlesbrough'): {
        'WeekDay': 'Tue', 'Time': '20:00', 'Round': 2,
        'Attendance': 20747
    },  # Source: FBref [6L27-L28]

    # -------------------- 22 August 2001 - Matchweek 2 --------------------
    ('Fulham', 'Sunderland'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 2,
        'Attendance': 20197
    },  # Source: FBref [6L29-L30]

    ('Blackburn', 'Man United'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 2,
        'Attendance': 29836
    },  # Source: FBref [6L30-L31]

    # -------------------- 25 August 2001 - Matchweek 3 --------------------
    ('West Ham', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 3,
        'Attendance': 24517
    },  # Source: FBref [12L37-L38]

    ('Southampton', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 3,
        'Attendance': 31107
    },  # Source: FBref [12L34-L35]

    ('Everton', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 3,
        'Attendance': 32829
    },  # Source: FBref [12L36-L37]

    ('Fulham', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 3,
        'Attendance': 15641
    },  # Source: FBref [12L40-L41]

    ('Arsenal', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 3,
        'Attendance': 37909
    },  # Source: FBref [12L33-L34]

    ('Ipswich', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 3,
        'Attendance': 22804
    },  # Source: FBref [12L31-L32]

    ('Blackburn', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 3,
        'Attendance': 24992
    },  # Source: FBref [12L39-L40]

    # -------------------- 26 August 2001 - Matchweek 3 --------------------
    ('Aston Villa', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 3,
        'Attendance': 42632
    },  # Source: FBref [12L41-L42]

    ('Newcastle', 'Sunderland'): {
        'WeekDay': 'Sun', 'Time': '13:00', 'Round': 3,
        'Attendance': 52021
    },  # Source: FBref [12L43-L44]

    # -------------------- 27 August 2001 - Matchweek 3 --------------------
    ('Bolton', 'Liverpool'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 3,
        'Attendance': 27205
    },  # Source: FBref [12L44-L45]

    # -------------------- 8 September 2001 - Matchweek 4 --------------------
    ('Sunderland', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 45103
    },  # Source: FBref [12L45-L46]

    ('Middlesbrough', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 30044
    },  # Source: FBref [12L54-L55]

    ('Leeds', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 40153
    },  # Source: FBref [12L55-L56]

    ('Liverpool', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 44102
    },  # Source: FBref [12L51-L52]

    ('Derby', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 27802
    },  # Source: FBref [12L52-L53]

    ('Chelsea', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 40855
    },  # Source: FBref [12L47-L48]

    ('Man United', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 67534
    },  # Source: FBref [12L50-L51]

    ('Leicester', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 4,
        'Attendance': 18774
    },  # Source: FBref [12L48-L49]

    # -------------------- 9 September 2001 - Matchweek 4 --------------------
    ('Charlton', 'Fulham'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 4,
        'Attendance': 20451
    },  # Source: FBref [12L58-L59]

    ('Tottenham', 'Southampton'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 4,
        'Attendance': 33668
    },  # Source: FBref [12L56-L57]

    # -------------------- 15 September 2001 - Matchweek 5 --------------------
    ('Bolton', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 5,
        'Attendance': 24378
    },  # Source: FBref [13L65-L66]

    ('Derby', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 5,
        'Attendance': 26863
    },  # Source: FBref [13L63-L64]

    ('Everton', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 5,
        'Attendance': 39554
    },  # Source: FBref [13L62-L63]

    ('Fulham', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 5,
        'Attendance': 20805
    },  # Source: FBref [13L66-L67]

    ('Middlesbrough', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 5,
        'Attendance': 25445
    },  # Source: FBref [13L61-L62]

    ('Newcastle', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 5,
        'Attendance': 52056
    },  # Source: FBref [13L59-L60]

    # -------------------- 16 September 2001 - Matchweek 5 --------------------
    ('Ipswich', 'Blackburn'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 5,
        'Attendance': 22126
    },  # Source: FBref [13L72-L73]

    ('Charlton', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 5,
        'Attendance': 20451
    },  # Source: FBref [13L69-L70]

    ('Tottenham', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 5,
        'Attendance': 36037
    },  # Source: FBref [13L68-L69]

    ('Aston Villa', 'Sunderland'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 5,
        'Attendance': 31668
    },  # Source: FBref [13L70-L71]

    # -------------------- 17 September 2001 - Matchweek 6 --------------------
    ('Leicester', 'Middlesbrough'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 6,
        'Attendance': 15415
    },  # Source: FBref [13L73-L74]

    # -------------------- 19 September 2001 - Matchweek 6 --------------------
    ('Blackburn', 'Bolton'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 6,
        'Attendance': 25949
    },  # Source: FBref [13L75-L76]

    ('Sunderland', 'Tottenham'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 6,
        'Attendance': 47310
    },  # Source: FBref [13L76-L77]

    # -------------------- 22 September 2001 - Matchweek 7 --------------------
    ('Sunderland', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': 46825
    },  # Source: FBref [13L77-L78]

    ('Man United', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': 67551
    },  # Source: FBref [13L82-L83]

    ('Leicester', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': 18918
    },  # Source: FBref [13L80-L81]

    ('Arsenal', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': 38014
    },  # Source: FBref [13L83-L84]

    ('Blackburn', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': 27732
    },  # Source: FBref [13L84-L85]

    ('Liverpool', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 7,
        'Attendance': 44116
    },  # Source: FBref [13L79-L80]

    # -------------------- 23 September 2001 - Matchweek 7 --------------------
    ('Chelsea', 'Middlesbrough'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 7,
        'Attendance': 36767
    },  # Source: FBref [13L86-L87]

    ('Leeds', 'Derby'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 7,
        'Attendance': 39155
    },  # Source: FBref [13L87-L88]

    ('West Ham', 'Newcastle'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 7,
        'Attendance': 28840
    },  # Source: FBref [13L88-L89]

    # -------------------- 24 September 2001 - Matchweek 7 --------------------
    ('Southampton', 'Aston Villa'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 7,
        'Attendance': 26794
    },  # Source: FBref [13L90-L91]

    # -------------------- 26 September 2001 - Matchweek 7 --------------------
    ('Newcastle', 'Leicester'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 7,
        'Attendance': 49185
    },  # Source: FBref [13L91-L92]

    # -------------------- 29 September 2001 - Matchweek 8 --------------------
    ('Tottenham', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 36038
    },  # Source: FBref [14L93-L94]

    ('Middlesbrough', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 26142
    },  # Source: FBref [14L97-L98]

    ('Derby', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 29200
    },  # Source: FBref [14L100-L101]

    ('Charlton', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 20451
    },  # Source: FBref [14L94-L95]

    ('Bolton', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 24520
    },  # Source: FBref [14L95-L96]

    ('Everton', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 8,
        'Attendance': 32049
    },  # Source: FBref [14L98-L99]

    ('Aston Villa', 'Blackburn'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 8,
        'Attendance': 28623
    },  # Source: FBref [14L105-L106]

    ('Fulham', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 8,
        'Attendance': 20197
    },  # Source: FBref [14L102-L103]

    ('Ipswich', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 8,
        'Attendance': 22643
    },  # Source: FBref [14L104-L105]

    ('Newcastle', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 8,
        'Attendance': 52095
    },  # Source: FBref [14L101-L102]

    # -------------------- 13 October 2001 - Matchweek 9 --------------------
    ('Sunderland', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': 48305
    },  # Source: FBref [14L106-L107]

    ('Southampton', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': 29759
    },  # Source: FBref [14L112-L113]

    ('Chelsea', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': 40370
    },  # Source: FBref [14L109-L110]

    ('Ipswich', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': 22820
    },  # Source: FBref [14L110-L111]

    ('Liverpool', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': 44352
    },  # Source: FBref [14L113-L114]

    ('Bolton', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': 25631
    },  # Source: FBref [14L108-L109]

    ('Charlton', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 9,
        'Attendance': 20451
    },  # Source: FBref [14L114-L115]

    # -------------------- 14 October 2001 - Matchweek 9 --------------------
    ('Aston Villa', 'Fulham'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 9,
        'Attendance': 28579
    },  # Source: FBref [14L116-L117]

    ('Blackburn', 'West Ham'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 9,
        'Attendance': 22712
    },  # Source: FBref [14L117-L118]

    # -------------------- 15 October 2001 - Matchweek 9 --------------------
    ('Tottenham', 'Derby'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 9,
        'Attendance': 30148
    },  # Source: FBref [14L118-L119]

    # -------------------- 20 October 2001 - Matchweek 10 --------------------
    ('Arsenal', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 38108
    },  # Source: FBref [15L126-L127]

    ('Derby', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 30221
    },  # Source: FBref [15L123-L124]

    ('Everton', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 33352
    },  # Source: FBref [15L121-L122]

    ('Leicester', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 21886
    },  # Source: FBref [15L127-L128]

    ('Man United', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 67559
    },  # Source: FBref [15L120-L121]

    ('West Ham', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 10,
        'Attendance': 25842
    },  # Source: FBref [15L124-L125]

    # -------------------- 21 October 2001 - Matchweek 10 --------------------
    ('Fulham', 'Ipswich'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 10,
        'Attendance': None
    },

    ('Newcastle', 'Tottenham'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 10,
        'Attendance': None
    },

    ('Leeds', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 10,
        'Attendance': None
    },

    # -------------------- 22 October 2001 - Matchweek 10 --------------------
    ('Middlesbrough', 'Sunderland'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 10,
        'Attendance': None
    },

    # -------------------- 24 October 2001 - Matchweek 10 --------------------
    ('Aston Villa', 'Charlton'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 10,
        'Attendance': None
    },

    ('Southampton', 'Ipswich'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 10,
        'Attendance': 29614
    },  # Source: PremierLeague.com [1L6-L8]

    ('West Ham', 'Chelsea'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 10,
        'Attendance': None
    },

    # -------------------- 27 October 2001 - Matchweek 11 --------------------
    ('Tottenham', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': None
    },

    ('Sunderland', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 48029
    },  # Source: FBref [10L15-L16]

    ('Fulham', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': None
    },

    ('Everton', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': None
    },

    ('Aston Villa', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': None
    },

    ('Charlton', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 22887
    },  # Source: FBref [11L13-L14]

    ('Man United', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 67555
    },  # Source: FBref [9L18-L19]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0102',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [47]:
null_rows(df, "0102", 'WeekDay')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
3304          Derby        Chelsea  2001     10   28
3305        Ipswich       West Ham  2001     10   28
3306      Blackburn      Leicester  2001     10   29
3307       West Ham         Fulham  2001     11    3
3308    Southampton      Blackburn  2001     11    3
3309  Middlesbrough          Derby  2001     11    3
3310      Leicester     Sunderland  2001     11    3
3311         Bolton        Everton  2001     11    3
3312      Newcastle    Aston Villa  2001     11    3
3313        Arsenal       Charlton  2001     11    4
3314        Chelsea        Ipswich  2001     11    4
3315          Leeds      Tottenham  2001     11    4
3316      Liverpool     Man United  2001     11    4
3317     Man United      Leicester  2001     11   17
3318      Tottenham        Arsenal  2001     11   17
3319          Derby    Southampton  2001     11   17
3320      Blackburn      Liverpool  2001     11   17
3321    Aston Villa  Middlesbrough  2001     11   17
3322         Fulham      Newcastle  2001     11   17
3323        Everton        Chelsea  2001     11   18
3324        Ipswich         Bolton  2001     11   18
3325     Sunderland          Leeds  2001     11   18
3326       Charlton       West Ham  2001     11   19
3327       West Ham      Tottenham  2001     11   24
3328    Southampton       Charlton  2001     11   24
3329      Leicester        Everton  2001     11   24
3330        Chelsea      Blackburn  2001     11   24
3331         Bolton         Fulham  2001     11   24
3332      Newcastle          Derby  2001     11   24
3333        Arsenal     Man United  2001     11   25
3334          Leeds    Aston Villa  2001     11   25
3335      Liverpool     Sunderland  2001     11   25
3336  Middlesbrough        Ipswich  2001     11   25
3337     Man United        Chelsea  2001     12    1
3338     Sunderland       West Ham  2001     12    1
3339          Derby      Liverpool  2001     12    1
3340       Charlton      Newcastle  2001     12    1
3341    Aston Villa      Leicester  2001     12    1
3342      Blackburn  Middlesbrough  2001     12    1
3343        Ipswich        Arsenal  2001     12    1
3344        Everton    Southampton  2001     12    2
3345         Fulham          Leeds  2001     12    2
3346      Tottenham         Bolton  2001     12    3
3347        Chelsea       Charlton  2001     12    5
3348       West Ham    Aston Villa  2001     12    5
3349     Man United       West Ham  2001     12    8
3350      Liverpool  Middlesbrough  2001     12    8
3351         Fulham        Everton  2001     12    8
3352          Derby         Bolton  2001     12    8
3353       Charlton      Tottenham  2001     12    8
3354      Leicester    Southampton  2001     12    8
3355        Arsenal    Aston Villa  2001     12    9
3356      Blackburn          Leeds  2001     12    9
3357        Ipswich      Newcastle  2001     12    9
3358     Sunderland        Chelsea  2001     12    9
3359      Liverpool         Fulham  2001     12   12
3360     Man United          Derby  2001     12   12
3361       West Ham        Arsenal  2001     12   15
3362      Tottenham         Fulham  2001     12   15
3363         Bolton       Charlton  2001     12   15
3364      Newcastle      Blackburn  2001     12   15
3365    Southampton     Sunderland  2001     12   15
3366  Middlesbrough     Man United  2001     12   15
3367        Everton          Derby  2001     12   15
3368        Chelsea      Liverpool  2001     12   16
3369          Leeds      Leicester  2001     12   16
3370    Aston Villa        Ipswich  2001     12   17
3371        Arsenal      Newcastle  2001     12   18
3372          Leeds        Everton  2001     12   19
3373      Tottenham        Ipswich  2001     12   22
3374     Sunderland        Everton  2001     12   22
3375     Man United    Southampton  2001     12   22
3376          Leeds      Newcastle  2001     12   22
3377          Derby    Aston Villa  2001     12   22
3378       Charlton      Blackburn  2001     12   22
3379      Leicester       West Ham  2001     12   22
3380        Chelsea         Bolton  2001     12   23
3381      Liverpool        Arsenal  2001     12   23
3382       West Ham          Derby  2001     12   26
3383    Southampton      Tottenham  2001     12   26
3384      Newcastle  Middlesbrough  2001     12   26
3385        Everton     Man United  2001     12   26
3386         Fulham       Charlton  2001     12   26
3387         Bolton          Leeds  2001     12   26
3388      Blackburn     Sunderland  2001     12   26
3389        Arsenal        Chelsea  2001     12   26
3390    Aston Villa      Liverpool  2001     12   26
3391        Ipswich      Leicester  2001     12   26
3392       West Ham      Liverpool  2001     12   29
3393    Southampton          Leeds  2001     12   29
3394      Newcastle        Chelsea  2001     12   29
3395        Ipswich     Sunderland  2001     12   29
3396         Bolton      Leicester  2001     12   29
3397      Blackburn          Derby  2001     12   29
3398    Aston Villa      Tottenham  2001     12   29
3399        Arsenal  Middlesbrough  2001     12   29
3400        Everton       Charlton  2001     12   29
3401         Fulham     Man United  2001     12   30
3402      Tottenham      Blackburn  2002      1    1
3403     Sunderland    Aston Villa  2002      1    1

In [ ]:
match_data = {
    # -------------------- 28 October 2001 - Matchweek 11 --------------------
    ('Derby', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 11,
        'Attendance': 28910
    },  # Source: ESPN [0L7-L8], stamford-bridge.com [0L20-L21]

    ('Ipswich', 'West Ham'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 11,
        'Attendance': 22834
    },  # Source: ESPN [1L12-L13], sport.de [1L18]

    # -------------------- 29 October 2001 - Matchweek 11 --------------------
    ('Blackburn', 'Leicester'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 11,
        'Attendance': 21873
    },  # Source: ESPN [2L14-L15], 11v11 [2L11]

    # -------------------- 3 November 2001 - Matchweek 12 --------------------
    ('West Ham', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 26217
    },  # Source: FBref [3L8-L9], ESPN [3L15-L16]

    ('Southampton', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 30523
    },  # Source: Global Sports Archive [4L7], FBref [4L13]

    ('Middlesbrough', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 28117
    },  # Source: Global Sports Archive [5L8], ESPN [5L16-L17]

    ('Leicester', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 20573
    },  # Source: Global Sports Archive [6L7-L8], Foxestalk [6L14]

    ('Bolton', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 27343
    },  # Source: ESPN [7L6-L7], sport.de [7L18-L19]

    ('Newcastle', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 51057
    },  # Source: FBref [8L7-L8], Wikipedia [8L23]

    # -------------------- 4 November 2001 - Matchweek 12 --------------------
    ('Arsenal', 'Charlton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 12,
        'Attendance': 38010
    },  # Source: Sky Sports [9L7], Global Sports Archive [9L11-L12]

    ('Chelsea', 'Ipswich'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 12,
        'Attendance': 40497
    },  # Source: FBref [10L8-L9], stamford-bridge.com [10L16-L17]

    ('Leeds', 'Tottenham'): {
        'WeekDay': 'Sun', 'Time': '12:00', 'Round': 12,
        'Attendance': 40203
    },  # Source: ESPN [11L13-L14], thfcdb.com [11L21]

    ('Liverpool', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '11:30', 'Round': 12,
        'Attendance': 44361
    },  # Source: LFChistory [12L6-L7], sport.de [12L15-L16]

    # -------------------- 17 November 2001 - Matchweek 13 --------------------
    ('Man United', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 67651
    },  # Source: FBref [13L8-L9], ESPN [13L12-L13]

    ('Tottenham', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 36049
    },  # Source: ESPN [14L5-L6], thfcdb.com [14L10]

    ('Derby', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 32063
    },  # Source: ESPN [15L6-L7], 11v11 [15L10-L11]

    ('Blackburn', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 28859
    },  # Source: ESPN [16L6-L7], 11v11 [16L10-L11]

    ('Aston Villa', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 35424
    },  # Source: FBref [17L5-L6], AVFC History [17L22]

    ('Fulham', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 21159
    },  # Source: ESPN [18L6-L7], FBref [18L11-L12]

    # -------------------- 18 November 2001 - Matchweek 13 --------------------
    ('Everton', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 13,
        'Attendance': 30555
    },  # Source: ESPN [19L5-L6], stamford-bridge.com [19L16-L17]

    ('Ipswich', 'Bolton'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 13,
        'Attendance': 22335
    },  # Source: Global Sports Archive [20L7-L8], ESPN [20L13-L14]

    ('Sunderland', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 13,
        'Attendance': 48005
    },  # Source: FBref [21L8], ESPN [21L17-L18]

    # -------------------- 19 November 2001 - Matchweek 13 --------------------
    ('Charlton', 'West Ham'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 13,
        'Attendance': 23198
    },  # Source: Global Sports Archive [22L7-L8], 11v11 [22L14]

    # -------------------- 24 November 2001 - Matchweek 14 --------------------
    ('West Ham', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 32780
    },  # Source: Global Sports Archive [23L7-L8], 11v11 [23L14]

    ('Southampton', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 31198
    },  # Source: FBref [24L7-L8], BBC [24L11]

    ('Leicester', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 21539
    },  # Source: FBref [25L7-L8], sport.de [25L12-L13]

    ('Chelsea', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 37978
    },  # Source: stamford-bridge.com [26L6-L7], ESPN [26L10-L11]

    ('Bolton', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 23848
    },  # Source: Global Sports Archive [27L7-L8], ESPN [27L13-L14]

    ('Newcastle', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 50070
    },  # Source: FBref [28L8-L9], Global Sports Archive [28L13-L14]

    # -------------------- 25 November 2001 - Matchweek 14 --------------------
    ('Arsenal', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 14,
        'Attendance': 38174
    },  # Source: ESPN [29L5-L6], FBref [29L34-L35]

    ('Leeds', 'Aston Villa'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 14,
        'Attendance': 40159
    },  # Source: Global Sports Archive [30L7], Football Web Pages [30L35-L36]

    ('Liverpool', 'Sunderland'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 14,
        'Attendance': 43537
    },  # Source: ESPN [31L6-L7], FBref [31L21-L22]

    ('Middlesbrough', 'Ipswich'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 14,
        'Attendance': 32586
    },  # Source: Pride of Anglia [32L7], FBref [32L11-L12]

    # -------------------- 1 December 2001 - Matchweek 15 --------------------
    ('Man United', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '12:00', 'Round': 15,
        'Attendance': 67544
    },  # Source: ESPN [33L6-L7], stamford-bridge.com [33L14-L15]

    ('Sunderland', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 47437
    },  # Source: ESPN [34L6-L7], The Northern Echo [34L12]

    ('Derby', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 33289
    },  # Source: ESPN [35L6-L7], FBref [35L17-L18]

    ('Charlton', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 24151
    },  # Source: Global Sports Archive [36L7-L8], 11v11 [36L13-L14]

    ('Aston Villa', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 30711
    },  # Source: AVFC History [37L9-L10], sport.de [37L14-L15]

    ('Blackburn', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 23849
    },  # Source: FBref [38L8-L9], FBref [38L13-L14]

    ('Ipswich', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 24666
    },  # Source: ESPN [39L6-L7], FBref [39L16-L17]

    # -------------------- 2 December 2001 - Matchweek 15 --------------------
    ('Everton', 'Southampton'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 15,
        'Attendance': 28138
    },  # Source: sport.de [40L6-L7], ESPN [40L15-L16]

    ('Fulham', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 15,
        'Attendance': 20918
    },  # Source: FBref [41L8], ESPN [41L11-L12]

    # -------------------- 3 December 2001 - Matchweek 15 --------------------
    ('Tottenham', 'Bolton'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 15,
        'Attendance': 32971
    },  # Source: ESPN [42L5-L6], FBref [42L16]

    # -------------------- 5 December 2001 - Matchweek 6 --------------------
    ('Chelsea', 'Charlton'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 6,
        'Attendance': 33504
    },  # Source: Global Sports Archive [43L6-L7], stamford-bridge.com [43L11-L12]

    ('West Ham', 'Aston Villa'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 6,
        'Attendance': 28377
    },  # Source: Global Sports Archive [44L7-L8], 11v11 [44L17]

    # -------------------- 8 December 2001 - Matchweek 16 --------------------
    ('Man United', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 67582
    },  # Source: ESPN [45L6-L7], 11v11 [45L22]

    ('Liverpool', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 43674
    },  # Source: Global Sports Archive [46L7-L8], LFChistory [46L13-L14]

    ('Fulham', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 19338
    },  # Source: Global Sports Archive [47L7-L8], 11v11 [47L17]

    ('Derby', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 25712
    },  # Source: FBref [48L8], 11v11 [48L11-L12]

    ('Charlton', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 25125
    },  # Source: ESPN [49L6-L7], FBref [49L17-L18]

    ('Leicester', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 20321
    },  # Source: FBref [50L11-L12], sport.de [50L16-L17]

    # -------------------- 9 December 2001 - Matchweek 16 --------------------
    ('Arsenal', 'Aston Villa'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 16,
        'Attendance': 38074
    },  # Source: ESPN [51L5-L6], FBref [51L11-L12]

    ('Blackburn', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '13:00', 'Round': 16,
        'Attendance': 28309
    },  # Source: FBref [52L22-L23], leeds-fans.org.uk [52L27]

    ('Ipswich', 'Newcastle'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 16,
        'Attendance': 24748
    },  # Source: FBref [53L7-L8], Global Sports Archive [53L13-L14]

    ('Sunderland', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 16,
        'Attendance': 48017
    },  # Source: stamford-bridge.com [54L6-L7], ESPN [54L10-L11]

    # -------------------- 12 December 2001 - Matchweek 6 --------------------
    ('Liverpool', 'Fulham'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 6,
        'Attendance': 37153
    },  # Source: ESPN [55L6-L7], LFChistory [55L14-L15]

    ('Man United', 'Derby'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 6,
        'Attendance': 67577
    },  # Source: ESPN [56L6-L7], FBref [56L13-L14]

    # -------------------- 15 December 2001 - Matchweek 17 --------------------
    ('West Ham', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 34523
    },  # Source: Global Sports Archive [57L6-L7], ESPN [57L10-L11]

    ('Tottenham', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 36054
    },  # Source: Global Sports Archive [58L7-L8], thfcdb.com [58L20]

    ('Bolton', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 20834
    },  # Source: Global Sports Archive [59L7-L8], sport.de [59L17-L18]

    ('Newcastle', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 50064
    },  # Source: Global Sports Archive [60L7], ESPN [60L12-L13]

    ('Southampton', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 29459
    },  # Source: Global Sports Archive [61L7], FBref [61L14-L15]

    ('Middlesbrough', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 34358
    },  # Source: 11v11 [62L7], FBref [62L12-L13]

    ('Everton', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 30615
    },  # Source: Global Sports Archive [63L6-L7], FBref [63L24-L25]

    # -------------------- 16 December 2001 - Matchweek 17 --------------------
    ('Chelsea', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 17,
        'Attendance': 41174
    },  # Source: ESPN [64L6-L7], LFChistory [64L10-L11]

    ('Leeds', 'Leicester'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 17,
        'Attendance': 38337
    },  # Source: Global Sports Archive [65L7-L8], FBref [65L23-L24]

    # -------------------- 17 December 2001 - Matchweek 17 --------------------
    ('Aston Villa', 'Ipswich'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 17,
        'Attendance': 29320
    },  # Source: ESPN [66L6], AVFC History [66L10]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0102',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [50]:
null_rows(df, "0102", 'WeekDay')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
3371        Arsenal      Newcastle  2001     12   18
3372          Leeds        Everton  2001     12   19
3373      Tottenham        Ipswich  2001     12   22
3374     Sunderland        Everton  2001     12   22
3375     Man United    Southampton  2001     12   22
3376          Leeds      Newcastle  2001     12   22
3377          Derby    Aston Villa  2001     12   22
3378       Charlton      Blackburn  2001     12   22
3379      Leicester       West Ham  2001     12   22
3380        Chelsea         Bolton  2001     12   23
3381      Liverpool        Arsenal  2001     12   23
3382       West Ham          Derby  2001     12   26
3383    Southampton      Tottenham  2001     12   26
3384      Newcastle  Middlesbrough  2001     12   26
3385        Everton     Man United  2001     12   26
3386         Fulham       Charlton  2001     12   26
3387         Bolton          Leeds  2001     12   26
3388      Blackburn     Sunderland  2001     12   26
3389        Arsenal        Chelsea  2001     12   26
3390    Aston Villa      Liverpool  2001     12   26
3391        Ipswich      Leicester  2001     12   26
3392       West Ham      Liverpool  2001     12   29
3393    Southampton          Leeds  2001     12   29
3394      Newcastle        Chelsea  2001     12   29
3395        Ipswich     Sunderland  2001     12   29
3396         Bolton      Leicester  2001     12   29
3397      Blackburn          Derby  2001     12   29
3398    Aston Villa      Tottenham  2001     12   29
3399        Arsenal  Middlesbrough  2001     12   29
3400        Everton       Charlton  2001     12   29
3401         Fulham     Man United  2001     12   30
3402      Tottenham      Blackburn  2002      1    1
3403     Sunderland    Aston Villa  2002      1    1
3404       Charlton        Ipswich  2002      1    1
3405          Leeds       West Ham  2002      1    1
3406  Middlesbrough        Everton  2002      1    1
3407        Chelsea    Southampton  2002      1    1
3408      Liverpool         Bolton  2002      1    1
3409          Derby         Fulham  2002      1    2
3410     Man United      Newcastle  2002      1    2
3411    Southampton      Liverpool  2002      1    9
3412    Aston Villa          Derby  2002      1   12
3413      Blackburn       Charlton  2002      1   12
3414         Bolton        Chelsea  2002      1   12
3415        Everton     Sunderland  2002      1   12
3416        Ipswich      Tottenham  2002      1   12
3417      Newcastle          Leeds  2002      1   12
3418       West Ham      Leicester  2002      1   12
3419         Fulham  Middlesbrough  2002      1   12
3420        Arsenal      Liverpool  2002      1   13
3421    Southampton     Man United  2002      1   13
3422      Tottenham        Everton  2002      1   19
3423     Sunderland         Fulham  2002      1   19
3424      Liverpool    Southampton  2002      1   19
3425          Derby        Ipswich  2002      1   19
3426     Man United      Blackburn  2002      1   19
3427  Middlesbrough         Bolton  2002      1   19
3428      Leicester      Newcastle  2002      1   19
3429        Chelsea       West Ham  2002      1   20
3430          Leeds        Arsenal  2002      1   20
3431       Charlton    Aston Villa  2002      1   21
3432     Man United      Liverpool  2002      1   22
3433      Leicester        Arsenal  2002      1   23
3434         Bolton     Man United  2002      1   29
3435       Charlton          Derby  2002      1   29
3436     Sunderland  Middlesbrough  2002      1   29
3437    Aston Villa        Everton  2002      1   30
3438      Blackburn        Arsenal  2002      1   30
3439        Chelsea          Leeds  2002      1   30
3440        Ipswich         Fulham  2002      1   30
3441      Liverpool      Leicester  2002      1   30
3442    Southampton       West Ham  2002      1   30
3443      Tottenham      Newcastle  2002      1   30
3444      Newcastle         Bolton  2002      2    2
3445     Man United     Sunderland  2002      2    2
3446       West Ham      Blackburn  2002      2    2
3447         Fulham    Aston Villa  2002      2    2
3448      Leicester        Chelsea  2002      2    2
3449        Arsenal    Southampton  2002      2    2
3450          Derby      Tottenham  2002      2    2
3451        Everton        Ipswich  2002      2    2
3452  Middlesbrough       Charlton  2002      2    3
3453          Leeds      Liverpool  2002      2    3
3454      Tottenham      Leicester  2002      2    9
3455      Newcastle    Southampton  2002      2    9
3456    Aston Villa        Chelsea  2002      2    9
3457        Ipswich      Liverpool  2002      2    9
3458         Fulham      Blackburn  2002      2    9
3459          Derby     Sunderland  2002      2    9
3460         Bolton       West Ham  2002      2    9
3461  Middlesbrough          Leeds  2002      2    9
3462       Charlton     Man United  2002      2   10
3463        Everton        Arsenal  2002      2   10
3464  Middlesbrough         Fulham  2002      2   19
3465        Arsenal         Fulham  2002      2   23
3466      Leicester          Derby  2002      2   23
3467      Liverpool        Everton  2002      2   23
3468     Man United    Aston Villa  2002      2   23
3469    Southampton         Bolton  2002      2   23
3470       West Ham  Middlesbrough  2002      2   23

In [ ]:
match_data = {
    # -------------------- 18 December 2001 - Matchweek 6 --------------------
    ('Arsenal', 'Newcastle'): {
        'WeekDay': 'Tue', 'Time': '20:00', 'Round': 6,
        'Attendance': 38012
    },  # Source: ESPN [0L7], 11v11 [0L11]

    # -------------------- 19 December 2001 - Matchweek 6 --------------------
    ('Leeds', 'Everton'): {
        'WeekDay': 'Wed', 'Time': '20:45', 'Round': 6,
        'Attendance': 40201
    },  # Source: Global Sports Archive [1L7], sport.de [1L13]

    # -------------------- 22 December 2001 - Matchweek 18 --------------------
    ('Tottenham', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 18,
        'Attendance': 36040
    },  # Source: Sky Sports [2L7], ESPN [2L11]

    ('Sunderland', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 18,
        'Attendance': 48013
    },  # Source: Sky Sports [3L7], FBref [3L9]

    ('Man United', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': 67638
    },  # Source: ESPN [4L7], Sky Sports [4L11]

    ('Leeds', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': 40287
    },  # Source: Sky Sports [5L7], 11v11 [5L11]

    ('Derby', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '13:00', 'Round': 18,
        'Attendance': 28001
    },  # Source: ESPN [6L7], sport.de [6L25]

    ('Charlton', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': 25857
    },  # Source: ESPN [7L6-L7], Sky Sports [7L11]

    ('Leicester', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 18,
        'Attendance': 20131
    },  # Source: 11v11 [8L7], sport.de [8L12]

    # -------------------- 23 December 2001 - Matchweek 18 --------------------
    ('Chelsea', 'Bolton'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 18,
        'Attendance': 34063
    },  # Source: ESPN [9L6], stamford-bridge.com [9L15]

    ('Liverpool', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 18,
        'Attendance': 44297
    },  # Source: ESPN [10L6-L7], LFChistory [10L10]

    # -------------------- 26 December 2001 - Matchweek 19 --------------------
    ('West Ham', 'Derby'): {
        'WeekDay': 'Wed', 'Time': '13:00', 'Round': 19,
        'Attendance': 31397
    },  # Source: ESPN [11L6], sport.de [11L21]

    ('Southampton', 'Tottenham'): {
        'WeekDay': 'Wed', 'Time': '13:00', 'Round': 19,
        'Attendance': 31719
    },  # Source: Sky Sports [12L7], Global Sports Archive [12L12]

    ('Newcastle', 'Middlesbrough'): {
        'WeekDay': 'Wed', 'Time': '16:00', 'Round': 19,
        'Attendance': 52127
    },  # Source: ESPN [13L6-L7], Sky Sports [13L11]

    ('Everton', 'Man United'): {
        'WeekDay': 'Wed', 'Time': '16:00', 'Round': 19,
        'Attendance': 39948
    },  # Source: Sky Sports [14L7], footymags.com [14L12]

    ('Fulham', 'Charlton'): {
        'WeekDay': 'Wed', 'Time': '13:00', 'Round': 19,
        'Attendance': 17900
    },  # Source: ESPN [15L7], Sky Sports [15L19]

    ('Bolton', 'Leeds'): {
        'WeekDay': 'Wed', 'Time': '13:00', 'Round': 19,
        'Attendance': 27060
    },  # Source: ESPN [16L7], 11v11 [16L19]

    ('Blackburn', 'Sunderland'): {
        'WeekDay': 'Wed', 'Time': '16:00', 'Round': 19,
        'Attendance': 29869
    },  # Source: Sky Sports [17L7], 11v11 [17L11]

    ('Arsenal', 'Chelsea'): {
        'WeekDay': 'Wed', 'Time': '13:00', 'Round': 19,
        'Attendance': 38079
    },  # Source: Sky Sports [18L7], ESPN [18L11]

    ('Aston Villa', 'Liverpool'): {
        'WeekDay': 'Wed', 'Time': '15:00', 'Round': 19,
        'Attendance': 42602
    },  # Source: Sky Sports [19L7], LFChistory [19L16]

    ('Ipswich', 'Leicester'): {
        'WeekDay': 'Wed', 'Time': '16:00', 'Round': 19,
        'Attendance': 24403
    },  # Source: Sky Sports [20L7], sport.de [20L12]

    # -------------------- 29 December 2001 - Matchweek 20 --------------------
    ('West Ham', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 20,
        'Attendance': 35103
    },  # Source: ESPN [21L7], Sky Sports [21L22]

    ('Southampton', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 20,
        'Attendance': 31622
    },  # Source: Sky Sports [22L7], sport.de [22L12]

    ('Newcastle', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 20,
        'Attendance': 52123
    },  # Source: ESPN [23L7], stamford-bridge.com [23L11]

    ('Ipswich', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 20,
        'Attendance': 24517
    },  # Source: ESPN [24L7], Sky Sports [24L11]

    ('Bolton', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 20,
        'Attendance': 23037
    },  # Source: ESPN [25L6-L7], sport.de [25L20]

    ('Blackburn', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 20,
        'Attendance': 23529
    },  # Source: ESPN [26L6-L7], 11v11 [26L11]

    ('Aston Villa', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 20,
        'Attendance': 41134
    },  # Source: ESPN [27L6], AVFC History [27L18]

    ('Arsenal', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 20,
        'Attendance': 37948
    },  # Source: ESPN [28L15-L16], FBref [28L23]

    ('Everton', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 20,
        'Attendance': 31131
    },  # Source: Sky Sports [29L7], sport.de [29L22]

    # -------------------- 30 December 2001 - Matchweek 20 --------------------
    ('Fulham', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 20,
        'Attendance': 21159
    },  # Source: ESPN [30L6], Sky Sports [30L15]

    # -------------------- 1 January 2002 - Matchweek 21 --------------------
    ('Tottenham', 'Blackburn'): {
        'WeekDay': 'Tue', 'Time': '16:00', 'Round': 21,
        'Attendance': 35131
    },  # Source: 11v11 [31L7], thfcdb.com [31L10]

    ('Sunderland', 'Aston Villa'): {
        'WeekDay': 'Tue', 'Time': '16:00', 'Round': 21,
        'Attendance': 45324
    },  # Source: 11v11 [32L7], AVFC History [32L10]

    ('Charlton', 'Ipswich'): {
        'WeekDay': 'Tue', 'Time': '15:00', 'Round': 21,
        'Attendance': 25893
    },  # Source: ESPN [33L6], Global Sports Archive [33L21]

    ('Leeds', 'West Ham'): {
        'WeekDay': 'Tue', 'Time': '21:00', 'Round': 21,
        'Attendance': 39320
    },  # Source: sport.de [34L8], leeds-fans.org.uk [34L27]

    ('Middlesbrough', 'Everton'): {
        'WeekDay': 'Tue', 'Time': '16:00', 'Round': 21,
        'Attendance': 27463
    },  # Source: sport.de [35L8], FBref [35L16]

    ('Chelsea', 'Southampton'): {
        'WeekDay': 'Tue', 'Time': '15:00', 'Round': 21,
        'Attendance': 35156
    },  # Source: stamford-bridge.com [36L7], sport.de [36L12]

    ('Liverpool', 'Bolton'): {
        'WeekDay': 'Tue', 'Time': '15:00', 'Round': 21,
        'Attendance': 43710
    },  # Source: ESPN [37L6], LFChistory [37L19]

    # -------------------- 2 January 2002 - Matchweek 21 --------------------
    ('Derby', 'Fulham'): {
        'WeekDay': 'Wed', 'Time': '20:45', 'Round': 21,
        'Attendance': 28165
    },  # Source: ESPN [38L6], Sky Sports [38L15]

    ('Man United', 'Newcastle'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 21,
        'Attendance': 67646
    },  # Source: ESPN [39L6-L7], Sky Sports [39L11]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0102',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [53]:
null_rows(df, "0102", 'WeekDay')[:100]

           HomeTeam       AwayTeam  Year  Month  Day
3411    Southampton      Liverpool  2002      1    9
3412    Aston Villa          Derby  2002      1   12
3413      Blackburn       Charlton  2002      1   12
3414         Bolton        Chelsea  2002      1   12
3415        Everton     Sunderland  2002      1   12
3416        Ipswich      Tottenham  2002      1   12
3417      Newcastle          Leeds  2002      1   12
3418       West Ham      Leicester  2002      1   12
3419         Fulham  Middlesbrough  2002      1   12
3420        Arsenal      Liverpool  2002      1   13
3421    Southampton     Man United  2002      1   13
3422      Tottenham        Everton  2002      1   19
3423     Sunderland         Fulham  2002      1   19
3424      Liverpool    Southampton  2002      1   19
3425          Derby        Ipswich  2002      1   19
3426     Man United      Blackburn  2002      1   19
3427  Middlesbrough         Bolton  2002      1   19
3428      Leicester      Newcastle  2002      1   19
3429        Chelsea       West Ham  2002      1   20
3430          Leeds        Arsenal  2002      1   20
3431       Charlton    Aston Villa  2002      1   21
3432     Man United      Liverpool  2002      1   22
3433      Leicester        Arsenal  2002      1   23
3434         Bolton     Man United  2002      1   29
3435       Charlton          Derby  2002      1   29
3436     Sunderland  Middlesbrough  2002      1   29
3437    Aston Villa        Everton  2002      1   30
3438      Blackburn        Arsenal  2002      1   30
3439        Chelsea          Leeds  2002      1   30
3440        Ipswich         Fulham  2002      1   30
3441      Liverpool      Leicester  2002      1   30
3442    Southampton       West Ham  2002      1   30
3443      Tottenham      Newcastle  2002      1   30
3444      Newcastle         Bolton  2002      2    2
3445     Man United     Sunderland  2002      2    2
3446       West Ham      Blackburn  2002      2    2
3447         Fulham    Aston Villa  2002      2    2
3448      Leicester        Chelsea  2002      2    2
3449        Arsenal    Southampton  2002      2    2
3450          Derby      Tottenham  2002      2    2
3451        Everton        Ipswich  2002      2    2
3452  Middlesbrough       Charlton  2002      2    3
3453          Leeds      Liverpool  2002      2    3
3454      Tottenham      Leicester  2002      2    9
3455      Newcastle    Southampton  2002      2    9
3456    Aston Villa        Chelsea  2002      2    9
3457        Ipswich      Liverpool  2002      2    9
3458         Fulham      Blackburn  2002      2    9
3459          Derby     Sunderland  2002      2    9
3460         Bolton       West Ham  2002      2    9
3461  Middlesbrough          Leeds  2002      2    9
3462       Charlton     Man United  2002      2   10
3463        Everton        Arsenal  2002      2   10
3464  Middlesbrough         Fulham  2002      2   19
3465        Arsenal         Fulham  2002      2   23
3466      Leicester          Derby  2002      2   23
3467      Liverpool        Everton  2002      2   23
3468     Man United    Aston Villa  2002      2   23
3469    Southampton         Bolton  2002      2   23
3470       West Ham  Middlesbrough  2002      2   23
3471     Sunderland      Newcastle  2002      2   24
3472          Leeds       Charlton  2002      2   24
3473       Charlton        Chelsea  2002      3    2
3474    Aston Villa       West Ham  2002      3    2
3475      Tottenham     Sunderland  2002      3    2
3476         Bolton      Blackburn  2002      3    2
3477  Middlesbrough      Leicester  2002      3    2
3478        Ipswich    Southampton  2002      3    2
3479         Fulham      Liverpool  2002      3    2
3480      Newcastle        Arsenal  2002      3    2
3481          Derby     Man United  2002      3    3
3482        Everton          Leeds  2002      3    3
3483        Arsenal          Derby  2002      3    5
3484      Blackburn    Aston Villa  2002      3    5
3485     Sunderland         Bolton  2002      3    5
3486        Chelsea         Fulham  2002      3    6
3487          Leeds        Ipswich  2002      3    6
3488      Liverpool      Newcastle  2002      3    6
3489     Man United      Tottenham  2002      3    6
3490    Southampton  Middlesbrough  2002      3    6
3491       West Ham        Everton  2002      3    6
3492      Leicester       Charlton  2002      3    9
3493      Blackburn        Ipswich  2002      3   13
3494        Chelsea      Tottenham  2002      3   13
3495        Everton         Fulham  2002      3   16
3496  Middlesbrough      Liverpool  2002      3   16
3497      Newcastle        Ipswich  2002      3   16
3498    Southampton      Leicester  2002      3   16
3499       West Ham     Man United  2002      3   16
3500        Chelsea     Sunderland  2002      3   16
3501         Bolton          Derby  2002      3   16
3502    Aston Villa        Arsenal  2002      3   17
3503          Leeds      Blackburn  2002      3   17
3504      Tottenham       Charlton  2002      3   18
3505     Sunderland    Southampton  2002      3   23
3506      Leicester          Leeds  2002      3   23
3507        Ipswich    Aston Villa  2002      3   23
3508          Derby        Everton  2002      3   23
3509       Charlton         Bolton  2002      3   23
3510     Man United  Middlesbrough  2002      3   23

In [ ]:
match_data = {
    # -------------------- 9 January 2002 - Matchweek 2 --------------------
    ('Southampton', 'Liverpool'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 2,
        'Attendance': 31527
    },  # Source: LFChistory [0L5-L7], sport.de [0L9-L11], Sky Sports [0L19-L21]

    # -------------------- 12 January 2002 - Matchweek 22 --------------------
    ('Aston Villa', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 22,
        'Attendance': 28881
    },  # Source: ESPN [1L4-L7], AVFC History [1L8-L11]

    ('Blackburn', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 22,
        'Attendance': 23365
    },  # Source: ESPN [2L4-L7], FBref [2L33-L35]

    ('Bolton', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 22,
        'Attendance': 23891
    },  # Source: ESPN [3L4-L7], 11v11 [3L22-L24]

    ('Everton', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 22,
        'Attendance': 30736
    },  # Source: Sky Sports [4L4-L7], FBref [4L19-L21]

    ('Ipswich', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 22,
        'Attendance': 25077
    },  # Source: Global Sports Archive [5L8-L12], FBref [5L30-L31]

    ('Newcastle', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 22,
        'Attendance': 52130
    },  # Source: Global Sports Archive [6L4-L8], Sky Sports [6L13-L15]

    ('West Ham', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 22,
        'Attendance': 34698
    },  # Source: ESPN [7L4-L7], FBref [7L26-L28]

    ('Fulham', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 22,
        'Attendance': 18975
    },  # Source: ESPN [8L4-L7], 11v11 [8L8-L11]

    # -------------------- 13 January 2002 - Matchweek 22 --------------------
    ('Arsenal', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 22,
        'Attendance': 38132
    },  # Source: ESPN [9L4-L7], LFChistory [9L17-L20]

    ('Southampton', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 22,
        'Attendance': 31858
    },  # Source: footymags [10L9-L12], FBref [10L15-L17]

    # -------------------- 19 January 2002 - Matchweek 23 --------------------
    ('Tottenham', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 36056
    },  # Source: ESPN [11L8-L11], FBref [11L23-L25]

    ('Sunderland', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 45124
    },  # Source: ESPN (BR) [12L4-L7], FBref [12L17-L18]

    ('Liverpool', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 43710
    },  # Source: ESPN [13L4-L7], LFChistory [13L12-L15]

    ('Derby', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 29658
    },  # Source: ESPN [14L8-L11], Global Sports Archive [14L14-L16]

    ('Man United', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 67552
    },  # Source: ESPN [15L4-L7], 11v11 [15L8-L12]

    ('Middlesbrough', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 26104
    },  # Source: Sky Sports [16L4-L7], FBref [16L15-L16]

    ('Leicester', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 23,
        'Attendance': 21354
    },  # Source: FBref [17L8-L10], NUFC.com [17L16-L19]

    # -------------------- 20 January 2002 - Matchweek 23 --------------------
    ('Chelsea', 'West Ham'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 23,
        'Attendance': 40035
    },  # Source: ESPN [18L4-L6], stamford-bridge [18L7-L10]

    ('Leeds', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 23,
        'Attendance': 40143
    },  # Source: Global Sports Archive [19L4-L7], sport.de [19L10-L14]

    # -------------------- 21 January 2002 - Matchweek 23 --------------------
    ('Charlton', 'Aston Villa'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 23,
        'Attendance': 25681
    },  # Source: ESPN [20L4-L6], Sky Sports [20L8-L10]

    # -------------------- 22 January 2002 - Matchweek 33 --------------------
    ('Man United', 'Liverpool'): {
        'WeekDay': 'Tue', 'Time': '20:00', 'Round': 33,
        'Attendance': 67599
    },  # Source: LFChistory [21L4-L7], sport.de [21L12-L16]

    # -------------------- 23 January 2002 - Matchweek 21 --------------------
    ('Leicester', 'Arsenal'): {
        'WeekDay': 'Wed', 'Time': '20:45', 'Round': 21,
        'Attendance': 21344
    },  # Source: sport.de [22L4-L8], FBref [22L13-L15]

    # -------------------- 29 January 2002 - Matchweek 24 --------------------
    ('Bolton', 'Man United'): {
        'WeekDay': 'Tue', 'Time': '20:00', 'Round': 24,
        'Attendance': 27350
    },  # Source: 11v11 [23L4-L8], footymags [23L9-L13]

    ('Charlton', 'Derby'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 24,
        'Attendance': 25387
    },  # Source: ESPN [24L4-L6], 11v11 [24L7-L10]

    ('Sunderland', 'Middlesbrough'): {
        'WeekDay': 'Tue', 'Time': '20:00', 'Round': 24,
        'Attendance': 44579
    },  # Source: ESPN [25L4-L7], 11v11 [25L8-L11]

    # -------------------- 30 January 2002 - Matchweek 24 --------------------
    ('Aston Villa', 'Everton'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 24,
        'Attendance': 32460
    },  # Source: ESPN [26L4-L7], AVFC History [26L8-L11]

    ('Blackburn', 'Arsenal'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 24,
        'Attendance': 25893
    },  # Source: ESPN [27L4-L7], sport.de [27L8-L12]

    ('Chelsea', 'Leeds'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 24,
        'Attendance': 40614
    },  # Source: ESPN [28L4-L7], stamford-bridge [28L8-L11]

    ('Ipswich', 'Fulham'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 24,
        'Attendance': 25156
    },  # Source: ESPN [29L4-L7], Pride of Anglia [29L12-L15]

    ('Liverpool', 'Leicester'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 24,
        'Attendance': 42305
    },  # Source: ESPN [30L4-L7], FBref [30L20-L21]

    ('Southampton', 'West Ham'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 24,
        'Attendance': 31879
    },  # Source: ESPN [31L4-L7], FBref [31L14-L15]

    ('Tottenham', 'Newcastle'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 24,
        'Attendance': 35798
    },  # Source: 11v11 [32L4-L7], thfcdb [32L8-L11]

    # -------------------- 2 February 2002 - Matchweek 25 --------------------
    ('Newcastle', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 25,
        'Attendance': 52094
    },  # Source: FBref [33L8-L9], Global Sports Archive [33L10-L14]

    ('Man United', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 25,
        'Attendance': 67587
    },  # Source: sport.de [34L4-L8], FBref [34L14-L16]

    ('West Ham', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 25,
        'Attendance': 35307
    },  # Source: ESPN [35L4-L7], 11v11 [35L8-L11]

    ('Fulham', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 25,
        'Attendance': 20041
    },  # Source: ESPN [36L4-L7], sport.de [36L8-L12]

    ('Leicester', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 25,
        'Attendance': 19950
    },  # Source: stamford-bridge [37L4-L7], FBref [37L12-L13]

    ('Arsenal', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 25,
        'Attendance': 38024
    },  # Source: ESPN [38L4-L7], sport.de [38L13-L17]

    ('Derby', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 25,
        'Attendance': 27721
    },  # Source: ESPN [39L4-L7], 11v11 [39L8-L11]

    ('Everton', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 25,
        'Attendance': 33069
    },  # Source: Sky Sports [40L4-L7], Pride of Anglia [40L8-L11]

    # -------------------- 3 February 2002 - Matchweek 25 --------------------
    ('Middlesbrough', 'Charlton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 25,
        'Attendance': 24189
    },  # Source: 11v11 [41L4-L7], FBref [41L38-L40]

    ('Leeds', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '12:00', 'Round': 25,
        'Attendance': 40216
    },  # Source: LFChistory [42L4-L7], sport.de [42L8-L12]

    # -------------------- 9 February 2002 - Matchweek 26 --------------------
    ('Tottenham', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 35973
    },  # Source: ESPN [43L4-L7], thfcdb [43L19-L21]

    ('Newcastle', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 51857
    },  # Source: Global Sports Archive [44L4-L8], FBref [44L13-L14]

    ('Aston Villa', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 41137
    },  # Source: stamford-bridge [45L4-L7], AVFC History [45L8-L11]

    ('Ipswich', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 25608
    },  # Source: ESPN [46L4-L7], LFChistory [46L8-L11]

    ('Fulham', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 19580
    },  # Source: ESPN [47L4-L7], FBref [47L22-L23]

    ('Derby', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 31771
    },  # Source: ESPN [48L4-L7], sport.de [48L8-L12]

    ('Bolton', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 24342
    },  # Source: ESPN [49L4-L7], sport.de [49L12-L16]

    ('Middlesbrough', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 30221
    },  # Source: sport.de [50L4-L8], FBref [50L27-L28]

    # -------------------- 10 February 2002 - Matchweek 26 --------------------
    ('Charlton', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 26,
        'Attendance': 26475
    },  # Source: ESPN [51L4-L7], Global Sports Archive [51L8-L12]

    ('Everton', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 26,
        'Attendance': 30859
    },  # Source: Global Sports Archive [52L4-L7], sport.de [52L10-L14]

    # -------------------- 19 February 2002 - Matchweek 18 --------------------
    ('Middlesbrough', 'Fulham'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 18,
        'Attendance': 26235
    },  # Source: ESPN [53L4-L7], 11v11 [53L8-L11]

    # -------------------- 23 February 2002 - Matchweek 27 --------------------
    ('Arsenal', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 38029
    },  # Source: ESPN [54L4-L7], sport.de [54L12-L16]

    ('Leicester', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 21620
    },  # Source: Sky Sports [55L4-L7], FBref [55L14-L15]

    ('Liverpool', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 44371
    },  # Source: ESPN [56L4-L7], LFChistory [56L8-L11]

    ('Man United', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '12:00', 'Round': 27,
        'Attendance': 67592
    },  # Source: ESPN [57L4-L7], sport.de [57L8-L12]

    ('Southampton', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 31380
    },  # Source: Sky Sports [58L4-L7], Global Sports Archive [58L8-L12]

    ('West Ham', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 35420
    },  # Source: sport.de [59L4-L8], FBref [59L15-L16]

    # -------------------- 24 February 2002 - Matchweek 27 --------------------
    ('Sunderland', 'Newcastle'): {
        'WeekDay': 'Sun', 'Time': '13:00', 'Round': 27,
        'Attendance': 48290
    },  # Source: ESPN [60L4-L7], Global Sports Archive [60L16-L20]

    ('Leeds', 'Charlton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 27,
        'Attendance': 39374
    },  # Source: ESPN [61L4-L7], FBref [61L28-L29]

    # -------------------- 2 March 2002 - Matchweek 28 --------------------
    ('Charlton', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 26354
    },  # Source: ESPN [62L4-L7], stamford-bridge [62L19-L22]

    ('Aston Villa', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 37341
    },  # Source: ESPN [63L4-L7], AVFC History [63L14-L17]

    ('Tottenham', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 36062
    },  # Source: ESPN [64L4-L7], thfcdb [64L12-L15]

    ('Bolton', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 27203
    },  # Source: ESPN [65L4-L7], sport.de [65L17-L21]

    ('Middlesbrough', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 25734
    },  # Source: ESPN [66L4-L7], FBref [66L12-L13]

    ('Ipswich', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 25440
    },  # Source: ESPN [67L4-L7], Global Sports Archive [67L8-L11]

    ('Fulham', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 21103
    },  # Source: LFChistory [68L4-L7], sport.de [68L12-L16]

    ('Newcastle', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '17:30', 'Round': 28,
        'Attendance': 52067
    },  # Source: sport.de [69L4-L8], FBref [69L10-L12]

    # -------------------- 3 March 2002 - Matchweek 28 --------------------
    ('Derby', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 28,
        'Attendance': 33041
    },  # Source: ESPN [70L4-L7], footymags [70L8-L12]

    ('Everton', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 28,
        'Attendance': 33226
    },  # Source: ESPN [71L4-L7], Global Sports Archive [71L8-L11]

    # -------------------- 5 March 2002 - Matchweek 29 --------------------
    ('Arsenal', 'Derby'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 29,
        'Attendance': 37878
    },  # Source: ESPN [72L4-L7], sport.de [72L8-L12]

    ('Blackburn', 'Aston Villa'): {
        'WeekDay': 'Tue', 'Time': '20:00', 'Round': 29,
        'Attendance': 21988
    },  # Source: 11v11 [73L4-L7], ESPN [73L8-L11]

    ('Sunderland', 'Bolton'): {
        'WeekDay': 'Tue', 'Time': '20:00', 'Round': 29,
        'Attendance': 43011
    },  # Source: ESPN [74L4-L7], FBref [74L16-L17]

    # -------------------- 6 March 2002 - Matchweek 29 --------------------
    ('Chelsea', 'Fulham'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 29,
        'Attendance': 39744
    },  # Source: ESPN [75L4-L7], FBref [75L9-L11]

    ('Leeds', 'Ipswich'): {
        'WeekDay': 'Wed', 'Time': '20:45', 'Round': 29,
        'Attendance': 39414
    },  # Source: sport.de [76L4-L8], FBref [76L16-L17]

    ('Liverpool', 'Newcastle'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 29,
        'Attendance': 44204
    },  # Source: Global Sports Archive [77L4-L7], LFChistory [77L10-L12]

    ('Man United', 'Tottenham'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 29,
        'Attendance': 67059
    },  # Source: thfcdb [78L4-L7], sport.de [78L8-L12]

    # -------------------- 9 March 2002 - Matchweek 29 --------------------
    ('Leicester', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 18562
    },  # Source: Global Sports Archive [79L4-L8], sport.de [79L9-L13]

    # -------------------- 13 March 2002 - Matchweek 27 --------------------
    ('Blackburn', 'Ipswich'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 27,
        'Attendance': 23305
    },  # Source: ESPN [80L4-L7], 11v11 [80L8-L11]

    ('Chelsea', 'Tottenham'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 27,
        'Attendance': 39652
    },  # Source: ESPN [81L4-L7], stamford-bridge [81L8-L11]

    # -------------------- 16 March 2002 - Matchweek 30 --------------------
    ('Everton', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 34639
    },  # Source: ESPN [82L4-L7], sport.de [82L8-L11]

    ('Middlesbrough', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '12:00', 'Round': 30,
        'Attendance': 31253
    },  # Source: ESPN [83L4-L7], LFChistory [83L13-L16]

    ('Newcastle', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 51115
    },  # Source: NUFC.com [84L4-L5], Sky Sports [84L8-L11]

    ('Southampton', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 30012
    },  # Source: Sky Sports [85L4-L7], sport.de [85L8-L12]

    ('West Ham', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 35281
    },  # Source: ESPN [86L4-L7], FBref [86L14-L15]

    ('Chelsea', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 40218
    },  # Source: ESPN [87L4-L7], stamford-bridge [87L8-L11]

    ('Bolton', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 25893
    },  # Source: ESPN [88L4-L7], sport.de [88L12-L16]

    # -------------------- 17 March 2002 - Matchweek 30 --------------------
    ('Aston Villa', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 30,
        'Attendance': 41520
    },  # Source: ESPN [89L4-L7], AVFC History [89L8-L10]

    ('Leeds', 'Blackburn'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 30,
        'Attendance': 39857
    },  # Source: Global Sports Archive [90L4-L8], sport.de [90L11-L14]

    # -------------------- 18 March 2002 - Matchweek 30 --------------------
    ('Tottenham', 'Charlton'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 30,
        'Attendance': 29602
    },  # Source: 11v11 [91L4-L8], Wikipedia [91L12-L13]

    # -------------------- 23 March 2002 - Matchweek 31 --------------------
    ('Sunderland', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 46120
    },  # Source: Sky Sports [92L4-L7], sport.de [92L8-L12]

    ('Leicester', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 18976
    },  # Source: Global Sports Archive [93L4-L8], Sky Sports [93L11-L14]

    ('Ipswich', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 25247
    },  # Source: Global Sports Archive [94L4-L8], Pride of Anglia [94L12-L14]

    ('Derby', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 33297
    },  # Source: ESPN [95L4-L7], FBref [95L16]

    ('Charlton', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 26358
    },  # Source: Sky Sports [96L4-L8], 11v11 [96L9-L12]

    ('Man United', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 67683
    },  # Source: Global Sports Archive [97L4-L8], sport.de [97L11-L15]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0102',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [56]:
null_rows(df, "0102", 'WeekDay')

           HomeTeam       AwayTeam  Year  Month  Day
3490    Southampton  Middlesbrough  2002      3    6
3491       West Ham        Everton  2002      3    6
3511         Fulham      Tottenham  2002      3   24
3512      Liverpool        Chelsea  2002      3   24
3513      Newcastle        Everton  2002      3   29
3514    Southampton         Fulham  2002      3   30
3515       West Ham        Ipswich  2002      3   30
3516  Middlesbrough      Tottenham  2002      3   30
3517        Chelsea          Derby  2002      3   30
3518      Leicester      Blackburn  2002      3   30
3519          Leeds     Man United  2002      3   30
3520         Bolton    Aston Villa  2002      3   30
3521        Arsenal     Sunderland  2002      3   30
3522      Liverpool       Charlton  2002      3   30
3523      Blackburn    Southampton  2002      4    1
3524       Charlton        Arsenal  2002      4    1
3525          Derby  Middlesbrough  2002      4    1
3526        Everton         Bolton  2002      4    1
3527         Fulham       West Ham  2002      4    1
3528        Ipswich        Chelsea  2002      4    1
3529     Sunderland      Leicester  2002      4    1
3530      Tottenham          Leeds  2002      4    1
3531    Aston Villa      Newcastle  2002      4    2
3532       West Ham       Charlton  2002      4    6
3533    Southampton          Derby  2002      4    6
3534      Leicester     Man United  2002      4    6
3535        Chelsea        Everton  2002      4    6
3536         Bolton        Ipswich  2002      4    6
3537  Middlesbrough    Aston Villa  2002      4    6
3538        Arsenal      Tottenham  2002      4    6
3539          Leeds     Sunderland  2002      4    7
3540      Newcastle         Fulham  2002      4    8
3541      Blackburn        Chelsea  2002      4   10
3542      Tottenham       West Ham  2002      4   13
3543    Aston Villa          Leeds  2002      4   13
3544        Everton      Leicester  2002      4   13
3545       Charlton    Southampton  2002      4   13
3546          Derby      Newcastle  2002      4   13
3547     Sunderland      Liverpool  2002      4   13
3548      Leicester    Aston Villa  2002      4   20
3549      Liverpool          Derby  2002      4   20
3550  Middlesbrough      Blackburn  2002      4   20
3551      Newcastle       Charlton  2002      4   20
3552    Southampton        Everton  2002      4   20
3553       West Ham     Sunderland  2002      4   20
3554          Leeds         Fulham  2002      4   20
3555        Chelsea     Man United  2002      4   20
3556         Bolton      Tottenham  2002      4   20
3557        Arsenal        Ipswich  2002      4   21
3558      Blackburn      Newcastle  2002      4   23
3559         Fulham         Bolton  2002      4   23
3560        Arsenal       West Ham  2002      4   24
3561        Ipswich  Middlesbrough  2002      4   24
3562      Newcastle       West Ham  2002      4   27
3563  Middlesbrough        Chelsea  2002      4   27
3564      Tottenham      Liverpool  2002      4   27
3565         Fulham      Leicester  2002      4   27
3566          Derby          Leeds  2002      4   27
3567    Aston Villa    Southampton  2002      4   27
3568       Charlton     Sunderland  2002      4   27
3569        Ipswich     Man United  2002      4   27
3570        Everton      Blackburn  2002      4   28
3571         Bolton        Arsenal  2002      4   29
3572      Liverpool      Blackburn  2002      5    8
3573     Man United        Arsenal  2002      5    8
3574       West Ham         Bolton  2002      5   11
3575     Sunderland          Derby  2002      5   11
3576    Southampton      Newcastle  2002      5   11
3577          Leeds  Middlesbrough  2002      5   11
3578      Liverpool        Ipswich  2002      5   11
3579      Leicester      Tottenham  2002      5   11
3580        Chelsea    Aston Villa  2002      5   11
3581      Blackburn         Fulham  2002      5   11
3582        Arsenal        Everton  2002      5   11
3583     Man United       Charlton  2002      5   11

In [ ]:
match_data = {
    # -------------------- 6 March 2002 - Matchweek 29 --------------------
    ('Southampton', 'Middlesbrough'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 29,
        'Attendance': 28931
    },  # Source: Sky Sports [3L6-L7], sport.de [3L10-L12]

    ('West Ham', 'Everton'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 29,
        'Attendance': 29883
    },  # Source: ESPN [4L6-L7], Sky Sports [4L14-L15]

    # -------------------- 24 March 2002 - Matchweek 31 --------------------
    ('Fulham', 'Tottenham'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 31,
        'Attendance': 15885
    },  # Source: ESPN [5L6-L7], thfcdb.com [5L14-L15]

    ('Liverpool', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 31,
        'Attendance': 44203
    },  # Source: ESPN [33L38-L40]

    # -------------------- 29 March 2002 - Matchweek 32 --------------------
    ('Newcastle', 'Everton'): {
        'WeekDay': 'Fri', 'Time': '15:00', 'Round': 32,
        'Attendance': 51921
    },  # Source: Sky Sports [34L30-L31], FBref [34L33-L36]

    # -------------------- 30 March 2002 - Matchweek 32 --------------------
    ('Southampton', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 31616
    },  # Source: Sky Sports [35L20-L21], FBref [35L29-L30]

    ('West Ham', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 33871
    },  # Source: ESPN [36L6-L7], Pride of Anglia [36L10-L11]

    ('Middlesbrough', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 31258
    },  # Source: ESPN [37L16-L17], 11v11 [37L20-L21]

    ('Chelsea', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 37849
    },  # Source: ESPN [38L6-L7], stamford-bridge.com [38L35-L36]

    ('Leicester', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 16236
    },  # Source: Sky Sports [44L16-L17], FBref [44L21-L22]

    ('Leeds', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 40058
    },  # Source: ESPN [45L6-L7], Sky Sports [45L24-L25]

    ('Bolton', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 24600
    },  # Source: ESPN [46L23-L24], sport.de [46L32-L33]

    ('Arsenal', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 38047
    },  # Source: Global Sports Archive [47L6-L8], ESPN [47L34-L35]

    ('Liverpool', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 44094
    },  # Source: ESPN [48L6-L7], Global Sports Archive [48L10-L11]

    # -------------------- 1 April 2002 - Matchweek 33 --------------------
    ('Blackburn', 'Southampton'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 33,
        'Attendance': None
    },

    ('Charlton', 'Arsenal'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 33,
        'Attendance': None
    },

    ('Derby', 'Middlesbrough'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 33,
        'Attendance': None
    },

    ('Everton', 'Bolton'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 33,
        'Attendance': None
    },

    ('Fulham', 'West Ham'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 33,
        'Attendance': None
    },

    ('Ipswich', 'Chelsea'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 33,
        'Attendance': None
    },

    ('Sunderland', 'Leicester'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 33,
        'Attendance': None
    },

    ('Tottenham', 'Leeds'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 33,
        'Attendance': None
    },

    ('Aston Villa', 'Newcastle'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 33,
        'Attendance': None
    },

    # -------------------- 6 April 2002 - Matchweek 34 --------------------
    ('West Ham', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    ('Southampton', 'Derby'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    ('Leicester', 'Man United'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    ('Chelsea', 'Everton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    ('Bolton', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    ('Middlesbrough', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    ('Arsenal', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    # -------------------- 7 April 2002 - Matchweek 34 --------------------
    ('Leeds', 'Sunderland'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    # -------------------- 8 April 2002 - Matchweek 34 --------------------
    ('Newcastle', 'Fulham'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    # -------------------- 10 April 2002 - Matchweek 35 --------------------
    ('Blackburn', 'Chelsea'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    # -------------------- 13 April 2002 - Matchweek 35 --------------------
    ('Tottenham', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    ('Aston Villa', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    ('Everton', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    ('Charlton', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    ('Derby', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    ('Sunderland', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    # -------------------- 20 April 2002 - Matchweek 36 --------------------
    ('Leicester', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Liverpool', 'Derby'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Middlesbrough', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Newcastle', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Southampton', 'Everton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('West Ham', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Leeds', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Chelsea', 'Man United'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Bolton', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    # -------------------- 21 April 2002 - Matchweek 36 --------------------
    ('Arsenal', 'Ipswich'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    # -------------------- 23 April 2002 - Matchweek 31 --------------------
    ('Blackburn', 'Newcastle'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 31,
        'Attendance': None
    },

    ('Fulham', 'Bolton'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 31,
        'Attendance': None
    },

    # -------------------- 24 April 2002 - Matchweek 31 --------------------
    ('Arsenal', 'West Ham'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 31,
        'Attendance': None
    },

    ('Ipswich', 'Middlesbrough'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 31,
        'Attendance': None
    },

    # -------------------- 27 April 2002 - Matchweek 37 --------------------
    ('Newcastle', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Middlesbrough', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Tottenham', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Fulham', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Derby', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Aston Villa', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Charlton', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Ipswich', 'Man United'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    # -------------------- 28 April 2002 - Matchweek 37 --------------------
    ('Everton', 'Blackburn'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    # -------------------- 29 April 2002 - Matchweek 37 --------------------
    ('Bolton', 'Arsenal'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    # -------------------- 8 May 2002 - Matchweek 35 --------------------
    ('Liverpool', 'Blackburn'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    ('Man United', 'Arsenal'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    # -------------------- 11 May 2002 - Matchweek 38 --------------------
    ('West Ham', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Sunderland', 'Derby'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Southampton', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Leeds', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Liverpool', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Leicester', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Chelsea', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Blackburn', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Arsenal', 'Everton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Man United', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0102',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [59]:
null_rows(df, "0102", 'Attendance')

           HomeTeam       AwayTeam  Year  Month  Day
3290         Fulham        Ipswich  2001     10   21
3291      Newcastle      Tottenham  2001     10   21
3292          Leeds        Chelsea  2001     10   21
3293  Middlesbrough     Sunderland  2001     10   22
3294    Aston Villa       Charlton  2001     10   24
3296       West Ham        Chelsea  2001     10   24
3297      Tottenham  Middlesbrough  2001     10   27
3299         Fulham    Southampton  2001     10   27
3300        Everton      Newcastle  2001     10   27
3301    Aston Villa         Bolton  2001     10   27
3523      Blackburn    Southampton  2002      4    1
3524       Charlton        Arsenal  2002      4    1
3525          Derby  Middlesbrough  2002      4    1
3526        Everton         Bolton  2002      4    1
3527         Fulham       West Ham  2002      4    1
3528        Ipswich        Chelsea  2002      4    1
3529     Sunderland      Leicester  2002      4    1
3530      Tottenham          Leeds  2002      4    1
3531    Aston Villa      Newcastle  2002      4    2
3532       West Ham       Charlton  2002      4    6
3533    Southampton          Derby  2002      4    6
3534      Leicester     Man United  2002      4    6
3535        Chelsea        Everton  2002      4    6
3536         Bolton        Ipswich  2002      4    6
3537  Middlesbrough    Aston Villa  2002      4    6
3538        Arsenal      Tottenham  2002      4    6
3539          Leeds     Sunderland  2002      4    7
3540      Newcastle         Fulham  2002      4    8
3541      Blackburn        Chelsea  2002      4   10
3542      Tottenham       West Ham  2002      4   13
3543    Aston Villa          Leeds  2002      4   13
3544        Everton      Leicester  2002      4   13
3545       Charlton    Southampton  2002      4   13
3546          Derby      Newcastle  2002      4   13
3547     Sunderland      Liverpool  2002      4   13
3548      Leicester    Aston Villa  2002      4   20
3549      Liverpool          Derby  2002      4   20
3550  Middlesbrough      Blackburn  2002      4   20
3551      Newcastle       Charlton  2002      4   20
3552    Southampton        Everton  2002      4   20
3553       West Ham     Sunderland  2002      4   20
3554          Leeds         Fulham  2002      4   20
3555        Chelsea     Man United  2002      4   20
3556         Bolton      Tottenham  2002      4   20
3557        Arsenal        Ipswich  2002      4   21
3558      Blackburn      Newcastle  2002      4   23
3559         Fulham         Bolton  2002      4   23
3560        Arsenal       West Ham  2002      4   24
3561        Ipswich  Middlesbrough  2002      4   24
3562      Newcastle       West Ham  2002      4   27
3563  Middlesbrough        Chelsea  2002      4   27
3564      Tottenham      Liverpool  2002      4   27
3565         Fulham      Leicester  2002      4   27
3566          Derby          Leeds  2002      4   27
3567    Aston Villa    Southampton  2002      4   27
3568       Charlton     Sunderland  2002      4   27
3569        Ipswich     Man United  2002      4   27
3570        Everton      Blackburn  2002      4   28
3571         Bolton        Arsenal  2002      4   29
3572      Liverpool      Blackburn  2002      5    8
3573     Man United        Arsenal  2002      5    8
3574       West Ham         Bolton  2002      5   11
3575     Sunderland          Derby  2002      5   11
3576    Southampton      Newcastle  2002      5   11
3577          Leeds  Middlesbrough  2002      5   11
3578      Liverpool        Ipswich  2002      5   11
3579      Leicester      Tottenham  2002      5   11
3580        Chelsea    Aston Villa  2002      5   11
3581      Blackburn         Fulham  2002      5   11
3582        Arsenal        Everton  2002      5   11
3583     Man United       Charlton  2002      5   11

In [ ]:
match_data = {
    # -------------------- 21 October 2001 - Matchweek 10 --------------------
    ('Fulham', 'Ipswich'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 10,
        'Attendance': 17221
    },  # Source: FBref [20L4-L8], sport.de [20L29-L32]

    ('Newcastle', 'Tottenham'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 10,
        'Attendance': 50593
    },  # Source: FBref [21L4-L9], worldfootball.net [21L17-L20]

    ('Leeds', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 10,
        'Attendance': 40171
    },  # Source: 11v11 [29L4-L7], ESPN [29L18-L21]

    # -------------------- 22 October 2001 - Matchweek 10 --------------------
    ('Middlesbrough', 'Sunderland'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 10,
        'Attendance': 28432
    },  # Source: FBref [22L4-L8], ESPN [22L32-L35]

    # -------------------- 24 October 2001 - Matchweek 10 --------------------
    ('Aston Villa', 'Charlton'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 10,
        'Attendance': 27701
    },  # Source: FBref [23L17-L22], Global Sports Archive [23L4-L6]

    ('West Ham', 'Chelsea'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 10,
        'Attendance': 26520
    },  # Source: 11v11 [25L3-L5], sport.de [24L23-L26]

    # -------------------- 27 October 2001 - Matchweek 11 --------------------
    ('Tottenham', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 36062
    },  # Source: ESPN [30L4-L7], thfcdb.com [30L8-L11]

    ('Fulham', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 18771
    },  # Source: ESPN [31L4-L7], Wikipedia [31L17-L20]

    ('Everton', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 37524
    },  # Source: ESPN [32L4-L7], sport.de [32L32-L36]

    ('Aston Villa', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 33599
    },  # Source: ESPN [33L4-L7], 11v11 [33L12-L15]

    # -------------------- 28 October 2001 - Matchweek 11 --------------------
    ('Derby', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 11,
        'Attendance': 28910
    },  # Source: ESPN [34L4-L7], sport.de [34L29-L33]

    ('Ipswich', 'West Ham'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 11,
        'Attendance': 22834
    },  # Source: ESPN [35L4-L7], Wikipedia [35L22-L25]

    # -------------------- 29 October 2001 - Matchweek 11 --------------------
    ('Blackburn', 'Leicester'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 11,
        'Attendance': 21873
    },  # Source: ESPN [36L4-L7], 11v11 [36L8-L11]

    # -------------------- 1 April 2002 - Matchweek 33 --------------------
    ('Blackburn', 'Southampton'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 33,
        'Attendance': 28851
    },  # Source: BBC Sport [37L19-L23], ESPN [37L24-L27]

    # -------------------- 6 April 2002 - Matchweek 34 --------------------
    ('West Ham', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    ('Southampton', 'Derby'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    ('Leicester', 'Man United'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    ('Chelsea', 'Everton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    ('Bolton', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    ('Middlesbrough', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    ('Arsenal', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    # -------------------- 7 April 2002 - Matchweek 34 --------------------
    ('Leeds', 'Sunderland'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    # -------------------- 8 April 2002 - Matchweek 34 --------------------
    ('Newcastle', 'Fulham'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 34,
        'Attendance': None
    },

    # -------------------- 10 April 2002 - Matchweek 35 --------------------
    ('Blackburn', 'Chelsea'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    # -------------------- 13 April 2002 - Matchweek 35 --------------------
    ('Tottenham', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    ('Aston Villa', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    ('Everton', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    ('Charlton', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    ('Derby', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    ('Sunderland', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    # -------------------- 20 April 2002 - Matchweek 36 --------------------
    ('Leicester', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Liverpool', 'Derby'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Middlesbrough', 'Blackburn'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Newcastle', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Southampton', 'Everton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('West Ham', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Leeds', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Chelsea', 'Man United'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    ('Bolton', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    # -------------------- 21 April 2002 - Matchweek 36 --------------------
    ('Arsenal', 'Ipswich'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 36,
        'Attendance': None
    },

    # -------------------- 23 April 2002 - Matchweek 31 --------------------
    ('Blackburn', 'Newcastle'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 31,
        'Attendance': None
    },

    ('Fulham', 'Bolton'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 31,
        'Attendance': None
    },

    # -------------------- 24 April 2002 - Matchweek 31 --------------------
    ('Arsenal', 'West Ham'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 31,
        'Attendance': None
    },

    ('Ipswich', 'Middlesbrough'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 31,
        'Attendance': None
    },

    # -------------------- 27 April 2002 - Matchweek 37 --------------------
    ('Newcastle', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Middlesbrough', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Tottenham', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Fulham', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Derby', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Aston Villa', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Charlton', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    ('Ipswich', 'Man United'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    # -------------------- 28 April 2002 - Matchweek 37 --------------------
    ('Everton', 'Blackburn'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    # -------------------- 29 April 2002 - Matchweek 37 --------------------
    ('Bolton', 'Arsenal'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 37,
        'Attendance': None
    },

    # -------------------- 8 May 2002 - Matchweek 35 --------------------
    ('Liverpool', 'Blackburn'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    ('Man United', 'Arsenal'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 35,
        'Attendance': None
    },

    # -------------------- 11 May 2002 - Matchweek 38 --------------------
    ('West Ham', 'Bolton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Sunderland', 'Derby'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Southampton', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Leeds', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Liverpool', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Leicester', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Chelsea', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Blackburn', 'Fulham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Arsenal', 'Everton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },

    ('Man United', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 38,
        'Attendance': None
    },
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0102',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [62]:
null_rows(df, "0102", 'Attendance')

           HomeTeam       AwayTeam  Year  Month  Day
3524       Charlton        Arsenal  2002      4    1
3525          Derby  Middlesbrough  2002      4    1
3526        Everton         Bolton  2002      4    1
3527         Fulham       West Ham  2002      4    1
3528        Ipswich        Chelsea  2002      4    1
3529     Sunderland      Leicester  2002      4    1
3530      Tottenham          Leeds  2002      4    1
3531    Aston Villa      Newcastle  2002      4    2
3532       West Ham       Charlton  2002      4    6
3533    Southampton          Derby  2002      4    6
3534      Leicester     Man United  2002      4    6
3535        Chelsea        Everton  2002      4    6
3536         Bolton        Ipswich  2002      4    6
3537  Middlesbrough    Aston Villa  2002      4    6
3538        Arsenal      Tottenham  2002      4    6
3539          Leeds     Sunderland  2002      4    7
3540      Newcastle         Fulham  2002      4    8
3541      Blackburn        Chelsea  2002      4   10
3542      Tottenham       West Ham  2002      4   13
3543    Aston Villa          Leeds  2002      4   13
3544        Everton      Leicester  2002      4   13
3545       Charlton    Southampton  2002      4   13
3546          Derby      Newcastle  2002      4   13
3547     Sunderland      Liverpool  2002      4   13
3548      Leicester    Aston Villa  2002      4   20
3549      Liverpool          Derby  2002      4   20
3550  Middlesbrough      Blackburn  2002      4   20
3551      Newcastle       Charlton  2002      4   20
3552    Southampton        Everton  2002      4   20
3553       West Ham     Sunderland  2002      4   20
3554          Leeds         Fulham  2002      4   20
3555        Chelsea     Man United  2002      4   20
3556         Bolton      Tottenham  2002      4   20
3557        Arsenal        Ipswich  2002      4   21
3558      Blackburn      Newcastle  2002      4   23
3559         Fulham         Bolton  2002      4   23
3560        Arsenal       West Ham  2002      4   24
3561        Ipswich  Middlesbrough  2002      4   24
3562      Newcastle       West Ham  2002      4   27
3563  Middlesbrough        Chelsea  2002      4   27
3564      Tottenham      Liverpool  2002      4   27
3565         Fulham      Leicester  2002      4   27
3566          Derby          Leeds  2002      4   27
3567    Aston Villa    Southampton  2002      4   27
3568       Charlton     Sunderland  2002      4   27
3569        Ipswich     Man United  2002      4   27
3570        Everton      Blackburn  2002      4   28
3571         Bolton        Arsenal  2002      4   29
3572      Liverpool      Blackburn  2002      5    8
3573     Man United        Arsenal  2002      5    8
3574       West Ham         Bolton  2002      5   11
3575     Sunderland          Derby  2002      5   11
3576    Southampton      Newcastle  2002      5   11
3577          Leeds  Middlesbrough  2002      5   11
3578      Liverpool        Ipswich  2002      5   11
3579      Leicester      Tottenham  2002      5   11
3580        Chelsea    Aston Villa  2002      5   11
3581      Blackburn         Fulham  2002      5   11
3582        Arsenal        Everton  2002      5   11
3583     Man United       Charlton  2002      5   11

In [ ]:
match_data = {
    # -------------------- 21 October 2001 - Matchweek 10 --------------------
    ('Fulham', 'Ipswich'): {
        'Time': '14:00', 'Attendance': 17221
    },  # Source: FBref [20L4-L8], sport.de [20L29-L32]

    ('Newcastle', 'Tottenham'): {
        'Time': '15:00', 'Attendance': 50593
    },  # Source: FBref [21L4-L9], worldfootball.net [21L17-L20]

    ('Leeds', 'Chelsea'): {
        'Time': '16:00', 'Attendance': 40171
    },  # Source: 11v11 [29L4-L7], ESPN [29L18-L21]

    # -------------------- 22 October 2001 - Matchweek 10 --------------------
    ('Middlesbrough', 'Sunderland'): {
        'Time': '20:00', 'Attendance': 28432
    },  # Source: FBref [22L4-L8], ESPN [22L32-L35]

    # -------------------- 24 October 2001 - Matchweek 10 --------------------
    ('Aston Villa', 'Charlton'): {
        'Time': '19:45', 'Attendance': 27701
    },  # Source: FBref [23L17-L22], Global Sports Archive [23L4-L6]

    ('West Ham', 'Chelsea'): {
        'Time': '19:45', 'Attendance': 26520
    },  # Source: 11v11 [25L3-L5], sport.de [24L23-L26]

    # -------------------- 27 October 2001 - Matchweek 11 --------------------
    ('Tottenham', 'Middlesbrough'): {
        'Time': '15:00', 'Attendance': 36062
    },  # Source: ESPN [30L4-L7], thfcdb.com [30L8-L11]

    ('Fulham', 'Southampton'): {
        'Time': '15:00', 'Attendance': 18771
    },  # Source: ESPN [31L4-L7], Wikipedia [31L17-L20]

    ('Everton', 'Newcastle'): {
        'Time': '15:00', 'Attendance': 37524
    },  # Source: ESPN [32L4-L7], sport.de [32L32-L36]

    ('Aston Villa', 'Bolton'): {
        'Time': '15:00', 'Attendance': 33599
    },  # Source: ESPN [33L4-L7], 11v11 [33L12-L15]

    # -------------------- 28 October 2001 - Matchweek 11 --------------------
    ('Derby', 'Chelsea'): {
        'Time': '16:00', 'Attendance': 28910
    },  # Source: ESPN [34L4-L7], sport.de [34L29-L33]

    ('Ipswich', 'West Ham'): {
        'Time': '15:00', 'Attendance': 22834
    },  # Source: ESPN [35L4-L7], Wikipedia [35L22-L25]

    # -------------------- 29 October 2001 - Matchweek 11 --------------------
    ('Blackburn', 'Leicester'): {
        'Time': '20:00', 'Attendance': 21873
    },  # Source: ESPN [36L4-L7], 11v11 [36L8-L11]

    # -------------------- 1 April 2002 - Matchweek 33 --------------------
    ('Charlton', 'Arsenal'): {
        'Time': '16:00', 'Attendance': 26339
    },  # Source: sport.de [0L22], ESPN [0L35], FBref [0L16]

    ('Derby', 'Middlesbrough'): {
        'Time': '16:00', 'Attendance': 30822
    },  # Source: sport.de [1L10], ESPN [1L15], FBref [1L35]

    ('Everton', 'Bolton'): {
        'Time': '16:00', 'Attendance': 39784
    },  # Source: ESPN [2L6], FBref [2L16], sport.de [2L21]

    ('Fulham', 'West Ham'): {
        'Time': '16:00', 'Attendance': 19416
    },  # Source: 11v11 [3L10], sport.de [3L15], FBref [3L18]

    ('Ipswich', 'Chelsea'): {
        'Time': '15:00', 'Attendance': 28053
    },  # Source: stamford-bridge.com [4L7], FBref [4L17]

    ('Sunderland', 'Leicester'): {
        'Time': '16:00', 'Attendance': 44950
    },  # Source: ESPN [5L7], sport.de [5L12], FBref [5L24]

    ('Tottenham', 'Leeds'): {
        'Time': '15:00', 'Attendance': 35167
    },  # Source: ESPN [6L7], thfcdb.com [6L19], FBref [6L16]

    # -------------------- 2 April 2002 - Matchweek 33 --------------------
    ('Aston Villa', 'Newcastle'): {
        'Time': '20:45', 'Attendance': 36597
    },  # Source: ESPN [7L7], sport.de [7L14], AVFC History [7L34]

    # -------------------- 6 April 2002 - Matchweek 34 --------------------
    ('West Ham', 'Charlton'): {
        'Time': '15:00', 'Attendance': 32389
    },  # Source: ESPN [8L6], FBref [8L11]

    ('Southampton', 'Derby'): {
        'Time': '16:00', 'Attendance': 29263
    },  # Source: FBref [9L8], sport.de [9L14]

    ('Leicester', 'Man United'): {
        'Time': '13:00', 'Attendance': 21447
    },  # Source: sport.de [10L11], Global Sports Archive [10L7]

    ('Chelsea', 'Everton'): {
        'Time': '15:00', 'Attendance': 40545
    },  # Source: ESPN [11L7], stamford-bridge.com [11L15]

    ('Bolton', 'Ipswich'): {
        'Time': '16:00', 'Attendance': 25817
    },  # Source: FBref [12L8], sport.de [12L14]

    ('Middlesbrough', 'Aston Villa'): {
        'Time': '16:00', 'Attendance': 26003
    },  # Source: sport.de [13L12], ESPN [13L7]

    ('Arsenal', 'Tottenham'): {
        'Time': '15:00', 'Attendance': 38186
    },  # Source: thfcdb.com [14L6], FBref [14L13]

    # -------------------- 7 April 2002 - Matchweek 34 --------------------
    ('Leeds', 'Sunderland'): {
        'Time': '16:00', 'Attendance': 39195
    },  # Source: FBref [15L8], Transfermarkt [15L20]

    # -------------------- 8 April 2002 - Matchweek 34 --------------------
    ('Newcastle', 'Fulham'): {
        'Time': '21:00', 'Attendance': 50017
    },  # Source: ESPN [16L7], sport.de [16L12]

    # -------------------- 10 April 2002 - Matchweek 35 --------------------
    ('Blackburn', 'Chelsea'): {
        'Time': '20:00', 'Attendance': 25441
    },  # Source: ESPN [17L7], stamford-bridge.com [17L11]

    # -------------------- 13 April 2002 - Matchweek 35 --------------------
    ('Tottenham', 'West Ham'): {
        'Time': '15:00', 'Attendance': 36083
    },  # Source: ESPN [18L7], Wikipedia [18L19]

    ('Aston Villa', 'Leeds'): {
        'Time': '15:00', 'Attendance': 40039
    },  # Source: ESPN [19L7], AVFC History [19L22]

    ('Everton', 'Leicester'): {
        'Time': '16:00', 'Attendance': 35580
    },  # Source: ESPN [20L7], sport.de [20L15]

    ('Charlton', 'Southampton'): {
        'Time': '15:00', 'Attendance': 26557
    },  # Source: ESPN [21L7], FBref [21L16]

    ('Derby', 'Newcastle'): {
        'Time': '15:00', 'Attendance': 31031
    },  # Source: ESPN [22L7], FBref [22L31]

    ('Sunderland', 'Liverpool'): {
        'Time': '18:35', 'Attendance': 48355
    },  # Source: ESPN [23L7], sport.de [23L21]

    # -------------------- 20 April 2002 - Matchweek 36 --------------------
    ('Leicester', 'Aston Villa'): {
        'Time': '15:00', 'Attendance': 18125
    },  # Source: AVFC History [24L6], FBref [24L10]

    ('Liverpool', 'Derby'): {
        'Time': '16:00', 'Attendance': 43510
    },  # Source: sport.de [25L8], Transfermarkt [25L21]

    ('Middlesbrough', 'Blackburn'): {
        'Time': '16:00', 'Attendance': 26932
    },  # Source: 11v11 [26L7], sport.de [26L12]

    ('Newcastle', 'Charlton'): {
        'Time': '16:00', 'Attendance': 51360
    },  # Source: sport.de [27L12], FBref [27L15]

    ('Southampton', 'Everton'): {
        'Time': '18:15', 'Attendance': 31785
    },  # Source: ESPN [28L7], sport.de [28L16]

    ('West Ham', 'Sunderland'): {
        'Time': '16:00', 'Attendance': 33319
    },  # Source: ESPN [29L7], 11v11 [29L11]

    ('Leeds', 'Fulham'): {
        'Time': '16:00', 'Attendance': 39111
    },  # Source: sport.de [30L8], leeds-fans.org.uk [30L31]

    ('Chelsea', 'Man United'): {
        'Time': '12:00', 'Attendance': 41725
    },  # Source: stamford-bridge.com [31L7], Transfermarkt [31L20]

    ('Bolton', 'Tottenham'): {
        'Time': '16:00', 'Attendance': 25817
    },  # Source: ESPN [32L7], sport.de [32L16]

    # -------------------- 21 April 2002 - Matchweek 36 --------------------
    ('Arsenal', 'Ipswich'): {
        'Time': '17:00', 'Attendance': 38058
    },  # Source: ESPN [33L7], sport.de [33L12]

    # -------------------- 23 April 2002 - Matchweek 31 --------------------
    ('Blackburn', 'Newcastle'): {
        'Time': '21:00', 'Attendance': 26712
    },  # Source: ESPN [34L7], sport.de [34L16]

    ('Fulham', 'Bolton'): {
        'Time': '19:45', 'Attendance': 18107
    },  # Source: ESPN [35L7], 11v11 [35L15]

    # -------------------- 24 April 2002 - Matchweek 31 --------------------
    ('Arsenal', 'West Ham'): {
        'Time': '21:00', 'Attendance': 38038
    },  # Source: ESPN [36L7], FBref [36L16]

    ('Ipswich', 'Middlesbrough'): {
        'Time': '20:45', 'Attendance': 25979
    },  # Source: Sky Sports [37L7], Global Sports Archive [37L12]

    # -------------------- 27 April 2002 - Matchweek 37 --------------------
    ('Newcastle', 'West Ham'): {
        'Time': '15:00', 'Attendance': 52127
    },  # Source: ESPN [38L7], FBref [38L16]

    ('Middlesbrough', 'Chelsea'): {
        'Time': '16:00', 'Attendance': 28686
    },  # Source: PremierLeague.com [39L7], stamford-bridge.com [39L11]

    ('Tottenham', 'Liverpool'): {
        'Time': '12:00', 'Attendance': 36017
    },  # Source: ESPN [40L7], LFChistory [40L14]

    ('Fulham', 'Leicester'): {
        'Time': '16:00', 'Attendance': 21106
    },  # Source: ESPN [41L7], 11v11 [41L10]

    ('Derby', 'Leeds'): {
        'Time': '16:00', 'Attendance': 30705
    },  # Source: sport.de [42L12], leeds-fans.org.uk [42L28]

    ('Aston Villa', 'Southampton'): {
        'Time': '16:00', 'Attendance': 35255
    },  # Source: ESPN [43L7], AVFC History [43L18]

    ('Charlton', 'Sunderland'): {
        'Time': '15:00', 'Attendance': 26614
    },  # Source: ESPN [44L7], Wikipedia [44L14]

    ('Ipswich', 'Man United'): {
        'Time': '18:35', 'Attendance': 28433
    },  # Source: sport.de [45L12], Wikipedia [45L6]

    # -------------------- 28 April 2002 - Matchweek 37 --------------------
    ('Everton', 'Blackburn'): {
        'Time': '16:00', 'Attendance': 34976
    },  # Source: Sky Sports [46L7], ESPN [46L11]

    # -------------------- 29 April 2002 - Matchweek 37 --------------------
    ('Bolton', 'Arsenal'): {
        'Time': '21:00', 'Attendance': 27351
    },  # Source: ESPN [47L7], FBref [47L12]

    # -------------------- 8 May 2002 - Matchweek 35 --------------------
    ('Liverpool', 'Blackburn'): {
        'Time': '20:00', 'Attendance': 40663
    },  # Source: ESPN [48L7], LFChistory [48L18]

    ('Man United', 'Arsenal'): {
        'Time': '21:00', 'Attendance': 67580
    },  # Source: ESPN [49L7], 11v11 [49L11]

    # -------------------- 11 May 2002 - Matchweek 38 --------------------
    ('West Ham', 'Bolton'): {
        'Time': '15:00', 'Attendance': 35546
    },  # Source: ESPN [50L7], FBref [50L31]

    ('Sunderland', 'Derby'): {
        'Time': '15:00', 'Attendance': 47989
    },  # Source: ESPN [51L7], FBref [51L32]

    ('Southampton', 'Newcastle'): {
        'Time': '15:00', 'Attendance': 31973
    },  # Source: Sky Sports [52L7], Wikipedia [52L10]

    ('Leeds', 'Middlesbrough'): {
        'Time': '15:00', 'Attendance': 40218
    },  # Source: football-lineups.com [53L6], FBref [53L25]

    ('Liverpool', 'Ipswich'): {
        'Time': '15:00', 'Attendance': 44088
    },  # Source: ESPN [54L7], LFChistory [54L14]

    ('Leicester', 'Tottenham'): {
        'Time': '15:00', 'Attendance': 21716
    },  # Source: thfcdb.com [55L6], Sky Sports [55L10]

    ('Chelsea', 'Aston Villa'): {
        'Time': '15:00', 'Attendance': 40709
    },  # Source: stamford-bridge.com [56L7], sport.de [56L16]

    ('Blackburn', 'Fulham'): {
        'Time': '16:00', 'Attendance': 30487
    },  # Source: 11v11 [57L7], sport.de [57L12]

    ('Arsenal', 'Everton'): {
        'Time': '15:00', 'Attendance': 38254
    },  # Source: ESPN [58L11], Wikipedia [58L26]

    ('Man United', 'Charlton'): {
        'Time': '15:00', 'Attendance': 67571
    },  # Source: ESPN [59L7], mufcinfo.com [59L18]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0102',
    data=match_data,
    value_col=['Time', 'Attendance'],
    inplace=True
)

In [64]:
missing_report(df,"0102")

XGHome    380
XGAway    380
dtype: int64

In [65]:
df.to_csv("Data/Data8.csv", index=False)

---

$$ 2000-01 $$

In [4]:
missing_report(df,"0001")

WeekDay       380
Time          380
Round         380
Attendance    380
XGHome        380
XGAway        380
dtype: int64

In [7]:
null_rows(df, "0001","WeekDay")[:100]

           HomeTeam       AwayTeam  Year  Month  Day
2824       Charlton       Man City  2000      8   19
2825          Leeds        Everton  2000      8   19
2826          Derby    Southampton  2000      8   19
2827        Chelsea       West Ham  2000      8   19
2828      Tottenham        Ipswich  2000      8   19
2829      Leicester    Aston Villa  2000      8   19
2830     Sunderland        Arsenal  2000      8   19
2831       Coventry  Middlesbrough  2000      8   19
2832      Liverpool       Bradford  2000      8   19
2833     Man United      Newcastle  2000      8   20
2834        Arsenal      Liverpool  2000      8   21
2835  Middlesbrough      Tottenham  2000      8   22
2836       Bradford        Chelsea  2000      8   22
2837        Ipswich     Man United  2000      8   22
2838    Southampton       Coventry  2000      8   23
2839       Man City     Sunderland  2000      8   23
2840        Everton       Charlton  2000      8   23
2841      Newcastle          Derby  2000      8   23
2842       West Ham      Leicester  2000      8   23
2843        Everton          Derby  2000      8   26
2844        Ipswich     Sunderland  2000      8   26
2845       Man City       Coventry  2000      8   26
2846  Middlesbrough          Leeds  2000      8   26
2847      Newcastle      Tottenham  2000      8   26
2848    Southampton      Liverpool  2000      8   26
2849       West Ham     Man United  2000      8   26
2850       Bradford      Leicester  2000      8   26
2851        Arsenal       Charlton  2000      8   26
2852    Aston Villa        Chelsea  2000      8   27
2853          Leeds       Man City  2000      9    5
2854     Man United       Bradford  2000      9    5
2855     Sunderland       West Ham  2000      9    5
2856      Tottenham        Everton  2000      9    5
2857      Liverpool    Aston Villa  2000      9    6
2858      Leicester        Ipswich  2000      9    6
2859       Coventry      Newcastle  2000      9    6
2860        Chelsea        Arsenal  2000      9    6
2861       Charlton    Southampton  2000      9    6
2862          Derby  Middlesbrough  2000      9    6
2863      Newcastle        Chelsea  2000      9    9
2864  Middlesbrough        Everton  2000      9    9
2865       Bradford        Arsenal  2000      9    9
2866      Liverpool       Man City  2000      9    9
2867      Leicester    Southampton  2000      9    9
2868        Ipswich    Aston Villa  2000      9    9
2869       Coventry          Leeds  2000      9    9
2870     Man United     Sunderland  2000      9    9
2871          Derby       Charlton  2000      9   10
2872      Tottenham       West Ham  2000      9   11
2873        Arsenal       Coventry  2000      9   16
2874    Aston Villa       Bradford  2000      9   16
2875       Charlton      Tottenham  2000      9   16
2876        Everton     Man United  2000      9   16
2877          Leeds        Ipswich  2000      9   16
2878    Southampton      Newcastle  2000      9   16
2879     Sunderland          Derby  2000      9   16
2880       West Ham      Liverpool  2000      9   17
2881        Chelsea      Leicester  2000      9   17
2882       Man City  Middlesbrough  2000      9   17
2883       Bradford    Southampton  2000      9   23
2884      Tottenham       Man City  2000      9   23
2885      Newcastle       Charlton  2000      9   23
2886       Coventry       West Ham  2000      9   23
2887     Man United        Chelsea  2000      9   23
2888      Liverpool     Sunderland  2000      9   23
2889          Derby          Leeds  2000      9   23
2890        Ipswich        Arsenal  2000      9   23
2891  Middlesbrough    Aston Villa  2000      9   23
2892      Leicester        Everton  2000      9   24
2893       West Ham       Bradford  2000      9   30
2894    Southampton  Middlesbrough  2000      9   30
2895          Leeds      Tottenham  2000      9   30
2896        Everton        Ipswich  2000      9   30
2897       Charlton       Coventry  2000      9   30
2898    Aston Villa          Derby  2000      9   30
2899       Man City      Newcastle  2000      9   30
2900        Arsenal     Man United  2000     10    1
2901        Chelsea      Liverpool  2000     10    1
2902     Sunderland      Leicester  2000     10    1
2903     Sunderland        Chelsea  2000     10   14
2904       Man City       Bradford  2000     10   14
2905        Ipswich       West Ham  2000     10   14
2906          Leeds       Charlton  2000     10   14
2907        Everton    Southampton  2000     10   14
2908       Coventry      Tottenham  2000     10   14
2909      Leicester     Man United  2000     10   14
2910        Arsenal    Aston Villa  2000     10   14
2911          Derby      Liverpool  2000     10   15
2912  Middlesbrough      Newcastle  2000     10   16
2913       Bradford        Ipswich  2000     10   21
2914       Charlton  Middlesbrough  2000     10   21
2915        Chelsea       Coventry  2000     10   21
2916      Liverpool      Leicester  2000     10   21
2917     Man United          Leeds  2000     10   21
2918      Newcastle        Everton  2000     10   21
2919      Tottenham          Derby  2000     10   21
2920       West Ham        Arsenal  2000     10   21
2921    Aston Villa     Sunderland  2000     10   22
2922    Southampton       Man City  2000     10   23
2923        Chelsea      Tottenham  2000     10   28

In [ ]:
match_data = {
    # -------------------- 19 August 2000 - Matchweek 1 --------------------
    ('Charlton', 'Man City'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 1,
        'Attendance': 20043
    },  # Source: FBref [5L20-L21]

    ('Leeds', 'Everton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 1,
        'Attendance': 40010
    },  # Source: FBref [5L10-L11]

    ('Derby', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 1,
        'Attendance': 27223
    },  # Source: FBref [5L17-L18]

    ('Chelsea', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 1,
        'Attendance': 34914
    },  # Source: FBref [5L13-L14]

    ('Tottenham', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 1,
        'Attendance': 36148
    },  # Source: FBref [5L15-L16]

    ('Leicester', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 1,
        'Attendance': 21455
    },  # Source: FBref [5L22-L23]

    ('Sunderland', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 1,
        'Attendance': 47121
    },  # Source: FBref [5L19-L20]

    ('Coventry', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 1,
        'Attendance': 20624
    },  # Source: FBref [5L16-L17]

    ('Liverpool', 'Bradford'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 1,
        'Attendance': 44183
    },  # Source: FBref [5L12-L13]

    ('Man United', 'Newcastle'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 1,
        'Attendance': 67477
    },  # Source: FBref [5L23-L24]

    # -------------------- 21 August 2000 - Matchweek 2 --------------------
    ('Arsenal', 'Liverpool'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 2,
        'Attendance': 38014
    },  # Source: FBref [5L24-L25]

    # -------------------- 22 August 2000 - Matchweek 2 --------------------
    ('Middlesbrough', 'Tottenham'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 2,
        'Attendance': 31254
    },  # Source: FBref [5L29-L30]

    ('Bradford', 'Chelsea'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 2,
        'Attendance': 17872
    },  # Source: FBref [5L27-L28]

    ('Ipswich', 'Man United'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 2,
        'Attendance': 22007
    },  # Source: FBref [5L26-L27]

    # -------------------- 23 August 2000 - Matchweek 2 --------------------
    ('Southampton', 'Coventry'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 2,
        'Attendance': 14801
    },  # Source: FBref [5L30-L31]

    ('Man City', 'Sunderland'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 2,
        'Attendance': 34410
    },  # Source: FBref [5L33-L34]

    ('Everton', 'Charlton'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 2,
        'Attendance': 36300
    },  # Source: FBref [5L36-L37]

    ('Newcastle', 'Derby'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 2,
        'Attendance': 51327
    },  # Source: FBref [5L31-L32]

    ('West Ham', 'Leicester'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 2,
        'Attendance': 25195
    },  # Source: FBref [5L34-L35]

    # -------------------- 26 August 2000 - Matchweek 3 --------------------
    ('Everton', 'Derby'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 3,
        'Attendance': 34840
    },  # Source: FBref [6L49-L50]

    ('Ipswich', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 3,
        'Attendance': 21830
    },  # Source: FBref [6L37-L38]

    ('Man City', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 3,
        'Attendance': 34140
    },  # Source: FBref [6L46-L47]

    ('Middlesbrough', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 3,
        'Attendance': 31626
    },  # Source: FBref [6L44-L45]

    ('Newcastle', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 3,
        'Attendance': 51573
    },  # Source: FBref [6L40-L41]

    ('Southampton', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 3,
        'Attendance': 15202
    },  # Source: FBref [6L41-L42]

    ('West Ham', 'Man United'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 3,
        'Attendance': 25988
    },  # Source: FBref [6L47-L48]

    ('Bradford', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 3,
        'Attendance': 16766
    },  # Source: FBref [6L38-L39]

    ('Arsenal', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 3,
        'Attendance': 38025
    },  # Source: FBref [6L43-L44]

    ('Aston Villa', 'Chelsea'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 3,
        'Attendance': 27057
    },  # Source: FBref [6L50-L51]

    # -------------------- 5 September 2000 - Matchweek 4 --------------------
    ('Leeds', 'Man City'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 4,
        'Attendance': 40055
    },  # Source: FBref [6L51-L52]

    ('Man United', 'Bradford'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 4,
        'Attendance': 66447
    },  # Source: FBref [6L55-L56]

    ('Sunderland', 'West Ham'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 4,
        'Attendance': 46605
    },  # Source: FBref [6L53-L54]

    ('Tottenham', 'Everton'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 4,
        'Attendance': 35316
    },  # Source: FBref [6L54-L55]

    # -------------------- 6 September 2000 - Matchweek 4 --------------------
    ('Liverpool', 'Aston Villa'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 4,
        'Attendance': 43360
    },  # Source: FBref [6L60-L61]

    ('Leicester', 'Ipswich'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 4,
        'Attendance': 19598
    },  # Source: FBref [6L58-L59]

    ('Coventry', 'Newcastle'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 4,
        'Attendance': 22109
    },  # Source: FBref [6L62-L63]

    ('Chelsea', 'Arsenal'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 4,
        'Attendance': 34923
    },  # Source: FBref [6L61-L62]

    ('Charlton', 'Southampton'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 4,
        'Attendance': 20043
    },  # Source: FBref [6L57-L58]

    ('Derby', 'Middlesbrough'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 4,
        'Attendance': 24290
    },  # Source: FBref [6L63-L64]

    # -------------------- 9 September 2000 - Matchweek 5 --------------------
    ('Newcastle', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 5,
        'Attendance': 51687
    },  # Source: FBref [7L73-L74]

    ('Middlesbrough', 'Everton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 5,
        'Attendance': 30885
    },  # Source: FBref [7L72-L73]

    ('Bradford', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 5,
        'Attendance': 17160
    },  # Source: FBref [7L75-L76]

    ('Liverpool', 'Man City'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 5,
        'Attendance': 44692
    },  # Source: FBref [7L76-L77]

    ('Leicester', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 5,
        'Attendance': 18366
    },  # Source: FBref [7L65-L66]

    ('Ipswich', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 5,
        'Attendance': 20665
    },  # Source: FBref [7L66-L67]

    ('Coventry', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 5,
        'Attendance': 20377
    },  # Source: FBref [7L69-L70]

    ('Man United', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 5,
        'Attendance': 67503
    },  # Source: FBref [7L70-L71]

    ('Derby', 'Charlton'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 5,
        'Attendance': 22310
    },  # Source: FBref [7L77-L78]

    ('Tottenham', 'West Ham'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 5,
        'Attendance': 33282
    },  # Source: FBref [7L79-L80]

    # -------------------- 16 September 2000 - Matchweek 6 --------------------
    ('Arsenal', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 6,
        'Attendance': 37794
    },  # Source: FBref [7L86-L87]

    ('Aston Villa', 'Bradford'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 6,
        'Attendance': 27849
    },  # Source: FBref [7L81-L82]

    ('Charlton', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 6,
        'Attendance': 20043
    },  # Source: FBref [7L84-L85]

    ('Everton', 'Man United'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 6,
        'Attendance': 38541
    },  # Source: FBref [7L88-L89]

    ('Leeds', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 6,
        'Attendance': 35552
    },  # Source: FBref [7L87-L88]

    ('Southampton', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 6,
        'Attendance': 15221
    },  # Source: FBref [7L80-L81]

    ('Sunderland', 'Derby'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 6,
        'Attendance': 45343
    },  # Source: FBref [7L83-L84]

    ('West Ham', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 6,
        'Attendance': 25998
    },  # Source: FBref [7L91-L92]

    ('Chelsea', 'Leicester'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 6,
        'Attendance': 33697
    },  # Source: FBref [7L93-L94]

    ('Man City', 'Middlesbrough'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 6,
        'Attendance': 32053
    },  # Source: FBref [7L90-L91]

    # -------------------- 23 September 2000 - Matchweek 7 --------------------
    ('Bradford', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 7,
        'Attendance': 16163
    },  # Source: FBref [7L94-L95]

    ('Tottenham', 'Man City'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 7,
        'Attendance': 36069
    },  # Source: FBref [8L105-L106]

    ('Newcastle', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 7,
        'Attendance': 50866
    },  # Source: FBref [7L95-L96]

    ('Coventry', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 7,
        'Attendance': 21020
    },  # Source: FBref [7L100-L101]

    ('Man United', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 7,
        'Attendance': 67568
    },  # Source: FBref [8L103-L104]

    ('Liverpool', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 7,
        'Attendance': 44713
    },  # Source: FBref [8L104-L105]

    ('Derby', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 7,
        'Attendance': 26248
    },  # Source: FBref [7L98-L99]

    ('Ipswich', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 7,
        'Attendance': 22030
    },  # Source: FBref [7L97-L98]

    ('Middlesbrough', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 7,
        'Attendance': 27556
    },  # Source: FBref [8L101-L102]

    ('Leicester', 'Everton'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 7,
        'Attendance': 18084
    },  # Source: FBref [8L106-L107]

    # -------------------- 30 September 2000 - Matchweek 8 --------------------
    ('West Ham', 'Bradford'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 8,
        'Attendance': 25407
    },  # Source: FBref [8L109-L110]

    ('Southampton', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 8,
        'Attendance': 14903
    },  # Source: FBref [8L113-L114]

    ('Leeds', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 8,
        'Attendance': 37562
    },  # Source: FBref [8L112-L113]

    ('Everton', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 8,
        'Attendance': 32597
    },  # Source: FBref [8L111-L112]

    ('Charlton', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 8,
        'Attendance': 20043
    },  # Source: FBref [8L108-L109]

    ('Aston Villa', 'Derby'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 8,
        'Attendance': 26534
    },  # Source: FBref [8L116-L117]

    ('Man City', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 8,
        'Attendance': 34497
    },  # Source: FBref [8L115-L116]

    ('Arsenal', 'Man United'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 8,
        'Attendance': 38146
    },  # Source: FBref [8L118-L119]

    ('Chelsea', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 8,
        'Attendance': 34966
    },  # Source: FBref [8L119-L120]

    ('Sunderland', 'Leicester'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 8,
        'Attendance': 45338
    },  # Source: FBref [8L120-L121]

    # -------------------- 14 October 2000 - Matchweek 9 --------------------
    ('Sunderland', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 9,
        'Attendance': 45078
    },  # Source: FBref [8L129-L130]

    ('Man City', 'Bradford'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 9,
        'Attendance': 34229
    },  # Source: FBref [8L122-L123]

    ('Ipswich', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 9,
        'Attendance': None
    },

    ('Leeds', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 9,
        'Attendance': 38837
    },  # Source: FBref [8L130-L131]

    ('Everton', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 9,
        'Attendance': 29491
    },  # Source: FBref [8L125-L126]

    ('Coventry', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 9,
        'Attendance': None
    },

    ('Leicester', 'Man United'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 9,
        'Attendance': 22132
    },  # Source: FBref [8L123-L124]

    ('Arsenal', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 9,
        'Attendance': 38042
    },  # Source: FBref [8L127-L128]

    ('Derby', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 9,
        'Attendance': None
    },

    ('Middlesbrough', 'Newcastle'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 9,
        'Attendance': None
    },

    # -------------------- 21 October 2000 - Matchweek 10 --------------------
    ('Bradford', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    ('Charlton', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    ('Chelsea', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    ('Liverpool', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    ('Man United', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    ('Newcastle', 'Everton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    ('Tottenham', 'Derby'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    ('West Ham', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    ('Aston Villa', 'Sunderland'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    ('Southampton', 'Man City'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 10,
        'Attendance': None
    },

    # -------------------- 28 October 2000 - Matchweek 11 --------------------
    ('Chelsea', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 11,
        'Attendance': None
    },
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0001',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [10]:
null_rows(df, "0001","WeekDay")[:100]

           HomeTeam       AwayTeam  Year  Month  Day
2924    Aston Villa       Charlton  2000     10   28
2925       West Ham      Newcastle  2000     10   28
2926        Arsenal       Man City  2000     10   28
2927     Man United    Southampton  2000     10   28
2928     Sunderland       Coventry  2000     10   28
2929        Ipswich  Middlesbrough  2000     10   28
2930      Leicester          Derby  2000     10   28
2931       Bradford          Leeds  2000     10   29
2932      Liverpool        Everton  2000     10   29
2933       Coventry     Man United  2000     11    4
2934          Leeds      Liverpool  2000     11    4
2935       Man City      Leicester  2000     11    4
2936  Middlesbrough        Arsenal  2000     11    4
2937      Newcastle        Ipswich  2000     11    4
2938    Southampton        Chelsea  2000     11    4
2939      Tottenham     Sunderland  2000     11    4
2940       Charlton       Bradford  2000     11    4
2941        Everton    Aston Villa  2000     11    5
2942          Derby       West Ham  2000     11    6
2943     Sunderland    Southampton  2000     11   11
2944       West Ham       Man City  2000     11   11
2945     Man United  Middlesbrough  2000     11   11
2946        Ipswich       Charlton  2000     11   11
2947       Bradford        Everton  2000     11   11
2948        Arsenal          Derby  2000     11   11
2949    Aston Villa      Tottenham  2000     11   11
2950      Leicester      Newcastle  2000     11   11
2951        Chelsea          Leeds  2000     11   12
2952      Liverpool       Coventry  2000     11   12
2953    Southampton    Aston Villa  2000     11   18
2954      Newcastle     Sunderland  2000     11   18
2955       Man City     Man United  2000     11   18
2956          Leeds       West Ham  2000     11   18
2957        Everton        Arsenal  2000     11   18
2958          Derby       Bradford  2000     11   18
2959       Charlton        Chelsea  2000     11   18
2960  Middlesbrough      Leicester  2000     11   18
2961      Tottenham      Liverpool  2000     11   19
2962       Coventry        Ipswich  2000     11   20
2963      Tottenham      Leicester  2000     11   25
2964  Middlesbrough       Bradford  2000     11   25
2965    Southampton       West Ham  2000     11   25
2966          Derby     Man United  2000     11   25
2967       Charlton     Sunderland  2000     11   25
2968        Everton        Chelsea  2000     11   25
2969       Man City        Ipswich  2000     11   25
2970       Coventry    Aston Villa  2000     11   25
2971      Newcastle      Liverpool  2000     11   26
2972          Leeds        Arsenal  2000     11   26
2973        Arsenal    Southampton  2000     12    2
2974    Aston Villa      Newcastle  2000     12    2
2975       Bradford       Coventry  2000     12    2
2976        Ipswich          Derby  2000     12    2
2977      Leicester          Leeds  2000     12    2
2978      Liverpool       Charlton  2000     12    2
2979     Man United      Tottenham  2000     12    2
2980       West Ham  Middlesbrough  2000     12    2
2981        Chelsea       Man City  2000     12    3
2982     Sunderland        Everton  2000     12    4
2983       West Ham    Aston Villa  2000     12    9
2984    Southampton          Leeds  2000     12    9
2985     Sunderland  Middlesbrough  2000     12    9
2986        Chelsea          Derby  2000     12    9
2987       Charlton     Man United  2000     12    9
2988       Bradford      Tottenham  2000     12    9
2989        Arsenal      Newcastle  2000     12    9
2990       Man City        Everton  2000     12    9
2991       Coventry      Leicester  2000     12   10
2992      Liverpool        Ipswich  2000     12   10
2993        Everton       West Ham  2000     12   16
2994        Ipswich    Southampton  2000     12   16
2995          Leeds     Sunderland  2000     12   16
2996      Leicester       Charlton  2000     12   16
2997    Aston Villa       Man City  2000     12   16
2998      Newcastle       Bradford  2000     12   16
2999          Derby       Coventry  2000     12   16
3000  Middlesbrough        Chelsea  2000     12   16
3001     Man United      Liverpool  2000     12   17
3002      Tottenham        Arsenal  2000     12   18
3003       Coventry    Southampton  2000     12   22
3004     Man United        Ipswich  2000     12   23
3005      Tottenham  Middlesbrough  2000     12   23
3006     Sunderland       Man City  2000     12   23
3007      Liverpool        Arsenal  2000     12   23
3008          Leeds    Aston Villa  2000     12   23
3009          Derby      Newcastle  2000     12   23
3010        Chelsea       Bradford  2000     12   23
3011       Charlton        Everton  2000     12   23
3012      Leicester       West Ham  2000     12   23
3013        Arsenal      Leicester  2000     12   26
3014    Aston Villa     Man United  2000     12   26
3015       Bradford     Sunderland  2000     12   26
3016        Everton       Coventry  2000     12   26
3017        Ipswich        Chelsea  2000     12   26
3018       Man City          Derby  2000     12   26
3019  Middlesbrough      Liverpool  2000     12   26
3020      Newcastle          Leeds  2000     12   26
3021       West Ham       Charlton  2000     12   26
3022    Southampton      Tottenham  2000     12   27
3023  Middlesbrough       Coventry  2000     12   30

In [ ]:
match_data = {
    # -------------------- 28 October 2000 - Matchweek 11 --------------------
    ('Aston Villa', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 27461
    },  # Source: sport.de [0L12-L15], FBref [0L22-L24]

    ('West Ham', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 26044
    },  # Source: 11v11 [1L5-L7], sport.de [1L15-L17]

    ('Arsenal', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 38049
    },  # Source: bluemoon-mcfc [2L6], transfermarkt [2L18-L19]

    ('Man United', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 67581
    },  # Source: sport.de [3L7-L8], mufcinfo [3L15]

    ('Sunderland', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 44526
    },  # Source: thenorthernecho [4L7], transfermarkt [4L10-L11]

    ('Ipswich', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 21771
    },  # Source: globalsportsarchive [5L8], sport.de [5L19-L20]

    ('Leicester', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 11,
        'Attendance': 20525
    },  # Source: foxestalk [6L7], FBref [6L12-L13]

    # -------------------- 29 October 2000 - Matchweek 11 --------------------
    ('Bradford', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 11,
        'Attendance': 17364
    },  # Source: globalsportsarchive [7L8], leeds-fans [7L17]

    ('Liverpool', 'Everton'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 11,
        'Attendance': 44718
    },  # Source: LFChistory [8L6-L7], sport.de [8L11-L12]

    # -------------------- 4 November 2000 - Matchweek 12 --------------------
    ('Coventry', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 21079
    },  # Source: sport.de [9L7-L8], FBref [9L15-L16]

    ('Leeds', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '11:30', 'Round': 12,
        'Attendance': 40055
    },  # Source: footballcritic [10L7], 11v11 [10L15-L16]

    ('Man City', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 34279
    },  # Source: 11v11 [11L12], globalsportsarchive [11L7]

    ('Middlesbrough', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 29541
    },  # Source: globalsportsarchive [12L7], 11v11 [12L11-L12]

    ('Newcastle', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 50922
    },  # Source: nufc [13L6], 11v11 [13L11-L12]

    ('Southampton', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 15236
    },  # Source: stamford-bridge [14L6-L7], sport.de [14L21-L22]

    ('Tottenham', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 36016
    },  # Source: globalsportsarchive [15L7], thfcdb [15L11]

    ('Charlton', 'Bradford'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 12,
        'Attendance': 19655
    },  # Source: sport.de [16L14-L15], transfermarkt [16L17-L18]

    ('Everton', 'Aston Villa'): {
        'WeekDay': 'Sun', 'Time': '14:00', 'Round': 12,
        'Attendance': 27670
    },  # Source: sport.de [17L7], transfermarkt [17L10-L11]

    ('Derby', 'West Ham'): {
        'WeekDay': 'Mon', 'Time': '21:00', 'Round': 12,
        'Attendance': 24621
    },  # Source: sport.de [18L7-L8], FBref [18L19-L20]

    # -------------------- 11 November 2000 - Matchweek 13 --------------------
    ('Sunderland', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 45064
    },  # Source: 11v11 [19L5-L7], sport.de [19L11-L12]

    ('West Ham', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 26022
    },  # Source: globalsportsarchive [20L7], 11v11 [20L11-L12]

    ('Man United', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 67576
    },  # Source: globalsportsarchive [21L7], sport.de [21L17-L18]

    ('Ipswich', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 22263
    },  # Source: 11v11 [22L6-L7], sport.de [22L18-L19]

    ('Bradford', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 17276
    },  # Source: globalsportsarchive [23L7], sport.de [23L12]

    ('Arsenal', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 37679
    },  # Source: globalsportsarchive [24L7], FBref [24L28-L29]

    ('Aston Villa', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 33608
    },  # Source: globalsportsarchive [25L8], sport.de [25L19-L20]

    ('Leicester', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 13,
        'Attendance': 21406
    },  # Source: 11v11 [26L6-L7], sport.de [26L23-L24]

    ('Chelsea', 'Leeds'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 13,
        'Attendance': 35121
    },  # Source: stamford-bridge [27L6-L7], sport.de [27L17-L18]

    ('Liverpool', 'Coventry'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 13,
        'Attendance': 43701
    },  # Source: globalsportsarchive [28L7], LFChistory [28L11-L12]

    # -------------------- 18 November 2000 - Matchweek 14 --------------------
    ('Southampton', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 14979
    },  # Source: globalsportsarchive [29L7-L8], sport.de [29L13-L14]

    ('Newcastle', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 52030
    },  # Source: 11v11 [30L6-L7], sport.de [30L11-L12]

    ('Man City', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '12:30', 'Round': 14,
        'Attendance': 34429
    },  # Source: FBref [31L9], sport.de [31L13-L14]

    ('Leeds', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 40005
    },  # Source: 11v11 [32L6-L7], sport.de [32L20-L21]

    ('Everton', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 33106
    },  # Source: globalsportsarchive [33L7], sport.de [33L13-L14]

    ('Derby', 'Bradford'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 31614
    },  # Source: worldfootball [34L6-L7], sport.de [34L11-L12]

    ('Charlton', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 20043
    },  # Source: stamford-bridge [35L6-L7], sport.de [35L11-L12]

    ('Middlesbrough', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 14,
        'Attendance': 27965
    },  # Source: football-lineups [36L7-L8], sport.de [36L19-L20]

    ('Tottenham', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 14,
        'Attendance': 36036
    },  # Source: 11v11 [37L6-L7], LFChistory [37L10]

    ('Coventry', 'Ipswich'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 14,
        'Attendance': 19324
    },  # Source: transfermarkt [38L6-L7], sport.de [38L11-L12]

    # -------------------- 25 November 2000 - Matchweek 15 --------------------
    ('Tottenham', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 35636
    },  # Source: globalsportsarchive [39L7], sport.de [39L12-L13]

    ('Middlesbrough', 'Bradford'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 28526
    },  # Source: football-lineups [40L5-L6], sport.de [40L19-L20]

    ('Southampton', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 15232
    },  # Source: globalsportsarchive [41L8], sport.de [41L14-L15]

    ('Derby', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 32910
    },  # Source: sport.de [42L7-L8], mufcinfo [42L15]

    ('Charlton', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 20043
    },  # Source: 11v11 [43L6-L7], sport.de [43L11-L12]

    ('Everton', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 33515
    },  # Source: stamford-bridge [44L6-L7], FBref [44L24-L25]

    ('Man City', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 33741
    },  # Source: globalsportsarchive [45L8], prideofanglia [45L14]

    ('Coventry', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 15,
        'Attendance': 21464
    },  # Source: globalsportsarchive [46L8], sport.de [46L13-L14]

    ('Newcastle', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 15,
        'Attendance': 51949
    },  # Source: 11v11 [47L6-L7], LFChistory [47L10-L11]

    ('Leeds', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 15,
        'Attendance': 38084
    },  # Source: leesun [48L6], FBref [48L10-L11]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0001',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [13]:
null_rows(df, "0001","WeekDay")[:100]

           HomeTeam       AwayTeam  Year  Month  Day
2973        Arsenal    Southampton  2000     12    2
2974    Aston Villa      Newcastle  2000     12    2
2975       Bradford       Coventry  2000     12    2
2976        Ipswich          Derby  2000     12    2
2977      Leicester          Leeds  2000     12    2
2978      Liverpool       Charlton  2000     12    2
2979     Man United      Tottenham  2000     12    2
2980       West Ham  Middlesbrough  2000     12    2
2981        Chelsea       Man City  2000     12    3
2982     Sunderland        Everton  2000     12    4
2983       West Ham    Aston Villa  2000     12    9
2984    Southampton          Leeds  2000     12    9
2985     Sunderland  Middlesbrough  2000     12    9
2986        Chelsea          Derby  2000     12    9
2987       Charlton     Man United  2000     12    9
2988       Bradford      Tottenham  2000     12    9
2989        Arsenal      Newcastle  2000     12    9
2990       Man City        Everton  2000     12    9
2991       Coventry      Leicester  2000     12   10
2992      Liverpool        Ipswich  2000     12   10
2993        Everton       West Ham  2000     12   16
2994        Ipswich    Southampton  2000     12   16
2995          Leeds     Sunderland  2000     12   16
2996      Leicester       Charlton  2000     12   16
2997    Aston Villa       Man City  2000     12   16
2998      Newcastle       Bradford  2000     12   16
2999          Derby       Coventry  2000     12   16
3000  Middlesbrough        Chelsea  2000     12   16
3001     Man United      Liverpool  2000     12   17
3002      Tottenham        Arsenal  2000     12   18
3003       Coventry    Southampton  2000     12   22
3004     Man United        Ipswich  2000     12   23
3005      Tottenham  Middlesbrough  2000     12   23
3006     Sunderland       Man City  2000     12   23
3007      Liverpool        Arsenal  2000     12   23
3008          Leeds    Aston Villa  2000     12   23
3009          Derby      Newcastle  2000     12   23
3010        Chelsea       Bradford  2000     12   23
3011       Charlton        Everton  2000     12   23
3012      Leicester       West Ham  2000     12   23
3013        Arsenal      Leicester  2000     12   26
3014    Aston Villa     Man United  2000     12   26
3015       Bradford     Sunderland  2000     12   26
3016        Everton       Coventry  2000     12   26
3017        Ipswich        Chelsea  2000     12   26
3018       Man City          Derby  2000     12   26
3019  Middlesbrough      Liverpool  2000     12   26
3020      Newcastle          Leeds  2000     12   26
3021       West Ham       Charlton  2000     12   26
3022    Southampton      Tottenham  2000     12   27
3023  Middlesbrough       Coventry  2000     12   30
3024      Newcastle     Man United  2000     12   30
3025    Southampton          Derby  2000     12   30
3026        Ipswich      Tottenham  2000     12   30
3027        Arsenal     Sunderland  2000     12   30
3028       Man City       Charlton  2000     12   30
3029     Man United       West Ham  2001      1    1
3030     Sunderland        Ipswich  2001      1    1
3031      Liverpool    Southampton  2001      1    1
3032          Derby        Everton  2001      1    1
3033          Leeds  Middlesbrough  2001      1    1
3034       Charlton        Arsenal  2001      1    1
3035        Chelsea    Aston Villa  2001      1    1
3036       Coventry       Man City  2001      1    1
3037      Leicester       Bradford  2001      1    1
3038      Tottenham      Newcastle  2001      1    2
3039       West Ham     Sunderland  2001      1   13
3040    Southampton       Charlton  2001      1   13
3041      Newcastle       Coventry  2001      1   13
3042  Middlesbrough          Derby  2001      1   13
3043        Everton      Tottenham  2001      1   13
3044       Bradford     Man United  2001      1   13
3045    Aston Villa      Liverpool  2001      1   13
3046        Arsenal        Chelsea  2001      1   13
3047       Man City          Leeds  2001      1   13
3048        Ipswich      Leicester  2001      1   14
3049     Man United    Aston Villa  2001      1   20
3050      Liverpool  Middlesbrough  2001      1   20
3051      Tottenham    Southampton  2001      1   20
3052          Leeds      Newcastle  2001      1   20
3053      Leicester        Arsenal  2001      1   20
3054       Coventry        Everton  2001      1   20
3055          Derby       Man City  2001      1   20
3056        Chelsea        Ipswich  2001      1   20
3057     Sunderland       Bradford  2001      1   21
3058       Charlton       West Ham  2001      1   22
3059    Aston Villa          Leeds  2001      1   24
3060        Arsenal       Bradford  2001      1   30
3061       Charlton          Derby  2001      1   30
3062       West Ham      Tottenham  2001      1   31
3063     Sunderland     Man United  2001      1   31
3064       Man City      Liverpool  2001      1   31
3065          Leeds       Coventry  2001      1   31
3066        Everton  Middlesbrough  2001      1   31
3067        Chelsea      Newcastle  2001      1   31
3068    Southampton      Leicester  2001      1   31
3069       Coventry        Arsenal  2001      2    3
3070          Derby     Sunderland  2001      2    3
3071        Ipswich          Leeds  2001      2    3
3072      Leicester        Chelsea  2001      2    3

In [ ]:
match_data = {
    # -------------------- 2 December 2000 - Matchweek 16 --------------------
    ('Arsenal', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 16,
        'Attendance': 38036
    },  # Source: FBref [8L2-L3], sport.de [0L8]

    ('Aston Villa', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 34255
    },  # Source: Wikipedia [1L21-L22], AVDB [1L14]

    ('Bradford', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 16,
        'Attendance': 15523
    },  # Source: Wikipedia [2L12]

    ('Ipswich', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': None
    },  # Source: BBC Sport [3L5-L7]

    ('Leicester', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 16,
        'Attendance': 21486
    },  # Source: leeds-fans.org.uk [4L31]

    ('Liverpool', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': 43515
    },  # Source: 11v11 [12L5]

    ('Man United', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 16,
        'Attendance': None
    },  # Source: FBref [13L5-L7]

    ('West Ham', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 16,
        'Attendance': 25459
    },  # Source: Wikiwand [7L28]

    # -------------------- 3 December 2000 - Matchweek 16 --------------------
    ('Chelsea', 'Man City'): {
        'WeekDay': 'Sun', 'Time': '17:00', 'Round': 16,
        'Attendance': None
    },  # Source: sport.de [15L33]

    # -------------------- 4 December 2000 - Matchweek 16 --------------------
    ('Sunderland', 'Everton'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 16,
        'Attendance': 46372
    },  # Source: FBref [16L37-L38]

    # -------------------- 9 December 2000 - Matchweek 17 --------------------
    ('West Ham', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 17,
        'Attendance': 25888
    },  # Source: resultdb.com [17L12-L13]

    ('Southampton', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 15225
    },  # Source: FBref [18L33], resultdb.com [18L12]

    ('Sunderland', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 17,
        'Attendance': 47742
    },  # Source: 11v11 [19L36]

    ('Chelsea', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 17,
        'Attendance': 34317
    },  # Source: livefutbol.com [20L32-L34]

    ('Charlton', 'Man United'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 17,
        'Attendance': 20043
    },  # Source: resultdb.com [21L41]

    ('Bradford', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': None
    },  # Source: FBref [22L14-L16]

    ('Arsenal', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 17,
        'Attendance': 38052
    },  # Source: resultdb.com [30L16], sport.de [30L38]

    ('Man City', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 17,
        'Attendance': 34516
    },  # Source: football-lineups.com [31L11]

    # -------------------- 10 December 2000 - Matchweek 17 --------------------
    ('Coventry', 'Leicester'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 17,
        'Attendance': None
    },  # Source: FBref [32L18-L20]

    ('Liverpool', 'Ipswich'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 17,
        'Attendance': None
    },  # Source: weltfussball.de [33L32]

    # -------------------- 16 December 2000 - Matchweek 18 --------------------
    ('Everton', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': 31260
    },  # Source: FBref [34L39]

    ('Ipswich', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 18,
        'Attendance': 22228
    },  # Source: Global Sports Archive [35L20], resultdb.com [35L32]

    ('Leeds', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': 40053
    },  # Source: FBref [36L14-L17]

    ('Leicester', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 18,
        'Attendance': None
    },  # Source: sport.de [37L31]

    ('Aston Villa', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': 29281
    },  # Source: football-lineups.com [38L6]

    ('Newcastle', 'Bradford'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 18,
        'Attendance': 50470
    },  # Source: resultdb.com [39L16]

    ('Derby', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 18,
        'Attendance': None
    },  # Source: sport.de [40L35]

    ('Middlesbrough', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 18,
        'Attendance': 29422
    },  # Source: 11v11 [41L36], football-lineups.com [41L31-L32]

    # -------------------- 17 December 2000 - Matchweek 18 --------------------
    ('Man United', 'Liverpool'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 18,
        'Attendance': 67533
    },  # Source: Global Sports Archive [42L7]

    # -------------------- 18 December 2000 - Matchweek 18 --------------------
    ('Tottenham', 'Arsenal'): {
        'WeekDay': 'Mon', 'Time': '21:00', 'Round': 18,
        'Attendance': None
    },  # Source: sport.de [43L31]

    # -------------------- 22 December 2000 - Matchweek 19 --------------------
    ('Coventry', 'Southampton'): {
        'WeekDay': 'Fri', 'Time': None, 'Round': 19,
        'Attendance': 18090
    },  # Source: 11v11 [44L43]

    # -------------------- 23 December 2000 - Matchweek 19 --------------------
    ('Man United', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 19,
        'Attendance': 67597
    },  # Source: Global Sports Archive [45L7]

    ('Tottenham', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 19,
        'Attendance': 35638
    },  # Source: footballdatabase.eu [46L29]

    ('Sunderland', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '16:00', 'Round': 19,
        'Attendance': None
    },  # Source: sport.de [47L13]

    ('Liverpool', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 19,
        'Attendance': None
    },  # Source: FBref [48L10-L13]

    ('Leeds', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 19,
        'Attendance': 39714
    },  # Source: resultdb.com [49L39]

    ('Derby', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': 29978
    },  # Source: resultdb.com [50L11], football-lineups.com [50L29]

    ('Chelsea', 'Bradford'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 19,
        'Attendance': 33377
    },  # Source: footballdatabase.eu [51L14]

    ('Charlton', 'Everton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 19,
        'Attendance': 20043
    },  # Source: 11v11 [52L41-L42]

    ('Leicester', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 19,
        'Attendance': 21524
    },  # Source: 11v11 [53L31], footballdatabase.eu [53L22]

    # -------------------- 26 December 2000 - Matchweek 20 --------------------
    ('Arsenal', 'Leicester'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 20,
        'Attendance': 38007
    },  # Source: FBref [8L10-L11]

    ('Aston Villa', 'Man United'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 20,
        'Attendance': None
    },

    ('Bradford', 'Sunderland'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 20,
        'Attendance': None
    },

    ('Everton', 'Coventry'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 20,
        'Attendance': None
    },

    ('Ipswich', 'Chelsea'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 20,
        'Attendance': None
    },

    ('Man City', 'Derby'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 20,
        'Attendance': None
    },

    ('Middlesbrough', 'Liverpool'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 20,
        'Attendance': None
    },

    ('Newcastle', 'Leeds'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 20,
        'Attendance': None
    },

    ('West Ham', 'Charlton'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 20,
        'Attendance': None
    },

    # -------------------- 27 December 2000 - Matchweek 20 --------------------
    ('Southampton', 'Tottenham'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 20,
        'Attendance': None
    },

    # -------------------- 30 December 2000 - Matchweek 21 --------------------
    ('Middlesbrough', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 21,
        'Attendance': None
    },

    ('Newcastle', 'Man United'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 21,
        'Attendance': None
    },

    ('Southampton', 'Derby'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 21,
        'Attendance': None
    },

    ('Ipswich', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 21,
        'Attendance': None
    },

    ('Arsenal', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 21,
        'Attendance': 38026
    },  # Source: FBref [8L12]

    ('Man City', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 21,
        'Attendance': None
    },

    # -------------------- 1 January 2001 - Matchweek 22 --------------------
    ('Man United', 'West Ham'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 22,
        'Attendance': None
    },

    ('Sunderland', 'Ipswich'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 22,
        'Attendance': None
    },

    ('Liverpool', 'Southampton'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 22,
        'Attendance': None
    },

    ('Derby', 'Everton'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 22,
        'Attendance': None
    },

    ('Leeds', 'Middlesbrough'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 22,
        'Attendance': None
    },

    ('Charlton', 'Arsenal'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 22,
        'Attendance': 20043
    },  # Source: FBref [8L13-L14]

    ('Chelsea', 'Aston Villa'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 22,
        'Attendance': None
    },

    ('Coventry', 'Man City'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 22,
        'Attendance': None
    },

    ('Leicester', 'Bradford'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 22,
        'Attendance': None
    },

    # -------------------- 2 January 2001 - Matchweek 22 --------------------
    ('Tottenham', 'Newcastle'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 22,
        'Attendance': None
    },

    # -------------------- 13 January 2001 - Matchweek 23 --------------------
    ('West Ham', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 23,
        'Attendance': None
    },

    ('Southampton', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 23,
        'Attendance': None
    },

    ('Newcastle', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 23,
        'Attendance': None
    },

    ('Middlesbrough', 'Derby'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 23,
        'Attendance': None
    },

    ('Everton', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 23,
        'Attendance': None
    },

    ('Bradford', 'Man United'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 23,
        'Attendance': None
    },

    ('Aston Villa', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 23,
        'Attendance': None
    },

    ('Arsenal', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 23,
        'Attendance': 38071
    },  # Source: FBref [8L15]

    ('Man City', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 23,
        'Attendance': None
    },

    # -------------------- 14 January 2001 - Matchweek 23 --------------------
    ('Ipswich', 'Leicester'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 23,
        'Attendance': None
    },

    # -------------------- 20 January 2001 - Matchweek 24 --------------------
    ('Man United', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 24,
        'Attendance': None
    },

    ('Liverpool', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 24,
        'Attendance': None
    },

    ('Tottenham', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 24,
        'Attendance': None
    },

    ('Leeds', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 24,
        'Attendance': None
    },

    ('Leicester', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 24,
        'Attendance': 21872
    },  # Source: FBref [8L17]

    ('Coventry', 'Everton'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 24,
        'Attendance': None
    },

    ('Derby', 'Man City'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 24,
        'Attendance': None
    },

    ('Chelsea', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 24,
        'Attendance': None
    },

    # -------------------- 21 January 2001 - Matchweek 24 --------------------
    ('Sunderland', 'Bradford'): {
        'WeekDay': 'Sun', 'Time': None, 'Round': 24,
        'Attendance': None
    },

    # -------------------- 22 January 2001 - Matchweek 24 --------------------
    ('Charlton', 'West Ham'): {
        'WeekDay': 'Mon', 'Time': None, 'Round': 24,
        'Attendance': None
    },

    # -------------------- 24 January 2001 - Matchweek 22 --------------------
    ('Aston Villa', 'Leeds'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 22,
        'Attendance': 29335
    },  # Source: resultdb.com [49L38]

    # -------------------- 30 January 2001 - Matchweek 25 --------------------
    ('Arsenal', 'Bradford'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 25,
        'Attendance': 37318
    },  # Source: FBref [8L18-L19]

    ('Charlton', 'Derby'): {
        'WeekDay': 'Tue', 'Time': None, 'Round': 25,
        'Attendance': None
    },

    # -------------------- 31 January 2001 - Matchweek 25 --------------------
    ('West Ham', 'Tottenham'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 25,
        'Attendance': None
    },

    ('Sunderland', 'Man United'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 25,
        'Attendance': None
    },

    ('Man City', 'Liverpool'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 25,
        'Attendance': None
    },

    ('Leeds', 'Coventry'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 25,
        'Attendance': None
    },

    ('Everton', 'Middlesbrough'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 25,
        'Attendance': None
    },

    ('Chelsea', 'Newcastle'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 25,
        'Attendance': None
    },

    ('Southampton', 'Leicester'): {
        'WeekDay': 'Wed', 'Time': None, 'Round': 25,
        'Attendance': None
    },

    # -------------------- 3 February 2001 - Matchweek 26 --------------------
    ('Coventry', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 26,
        'Attendance': 22035
    },  # Source: FBref [8L19-L20]

    ('Derby', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 26,
        'Attendance': None
    },

    ('Ipswich', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 26,
        'Attendance': None
    },

    ('Leicester', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': None, 'Round': 26,
        'Attendance': None
    },
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0001',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [16]:
null_rows(df, "0001","WeekDay")

           HomeTeam       AwayTeam  Year  Month  Day
3073      Liverpool       West Ham  2001      2    3
3074     Man United        Everton  2001      2    3
3075  Middlesbrough       Man City  2001      2    3
3076      Tottenham       Charlton  2001      2    3
3077       Bradford    Aston Villa  2001      2    3
3078        Everton          Leeds  2001      2    7
3079        Everton      Leicester  2001      2   10
3080          Leeds          Derby  2001      2   10
3081       Man City      Tottenham  2001      2   10
3082    Southampton       Bradford  2001      2   10
3083     Sunderland      Liverpool  2001      2   10
3084        Arsenal        Ipswich  2001      2   10
3085    Aston Villa  Middlesbrough  2001      2   10
3086        Chelsea     Man United  2001      2   10
3087       Charlton      Newcastle  2001      2   11
3088       West Ham       Coventry  2001      2   12
3089      Tottenham          Leeds  2001      2   24
3090      Newcastle       Man City  2001      2   24
3091        Ipswich        Everton  2001      2   24
3092      Leicester     Sunderland  2001      2   24
3093          Derby    Aston Villa  2001      2   24
3094       Coventry       Charlton  2001      2   24
3095       Bradford       West Ham  2001      2   24
3096  Middlesbrough    Southampton  2001      2   24
3097     Man United        Arsenal  2001      2   25
3098  Middlesbrough       Charlton  2001      3    3
3099       Man City    Southampton  2001      3    3
3100        Arsenal       West Ham  2001      3    3
3101          Leeds     Man United  2001      3    3
3102        Everton      Newcastle  2001      3    3
3103       Coventry        Chelsea  2001      3    3
3104      Leicester      Liverpool  2001      3    3
3105          Derby      Tottenham  2001      3    3
3106        Ipswich       Bradford  2001      3    4
3107     Sunderland    Aston Villa  2001      3    5
3108       West Ham        Chelsea  2001      3    7
3109    Aston Villa        Ipswich  2001      3   10
3110       West Ham        Ipswich  2001      3   17
3111      Tottenham       Coventry  2001      3   17
3112      Newcastle  Middlesbrough  2001      3   17
3113     Man United      Leicester  2001      3   17
3114        Chelsea     Sunderland  2001      3   17
3115       Charlton          Leeds  2001      3   17
3116       Bradford       Man City  2001      3   17
3117    Southampton        Everton  2001      3   17
3118    Aston Villa        Arsenal  2001      3   18
3119      Liverpool          Derby  2001      3   18
3120       West Ham        Everton  2001      3   31
3121     Sunderland          Leeds  2001      3   31
3122       Man City    Aston Villa  2001      3   31
3123      Liverpool     Man United  2001      3   31
3124       Coventry          Derby  2001      3   31
3125        Arsenal      Tottenham  2001      3   31
3126       Bradford      Newcastle  2001      3   31
3127        Chelsea  Middlesbrough  2001      3   31
3128       Charlton      Leicester  2001      4    1
3129    Southampton        Ipswich  2001      4    2
3130    Aston Villa      Leicester  2001      4    4
3131    Aston Villa       West Ham  2001      4    7
3132          Derby        Chelsea  2001      4    7
3133          Leeds    Southampton  2001      4    7
3134      Leicester       Coventry  2001      4    7
3135        Everton       Man City  2001      4    8
3136  Middlesbrough     Sunderland  2001      4    9
3137     Man United       Charlton  2001      4   10
3138        Ipswich      Liverpool  2001      4   10
3139      Tottenham       Bradford  2001      4   10
3140       Man City        Arsenal  2001      4   11
3141       Bradford       Charlton  2001      4   13
3142      Liverpool          Leeds  2001      4   13
3143       West Ham          Derby  2001      4   14
3144     Sunderland      Tottenham  2001      4   14
3145    Aston Villa        Everton  2001      4   14
3146      Leicester       Man City  2001      4   14
3147     Man United       Coventry  2001      4   14
3148        Arsenal  Middlesbrough  2001      4   14
3149        Chelsea    Southampton  2001      4   14
3150        Ipswich      Newcastle  2001      4   14
3151        Everton      Liverpool  2001      4   16
3152  Middlesbrough        Ipswich  2001      4   16
3153      Newcastle       West Ham  2001      4   16
3154       Coventry     Sunderland  2001      4   16
3155          Derby      Leicester  2001      4   16
3156       Charlton    Aston Villa  2001      4   17
3157      Tottenham        Chelsea  2001      4   17
3158       West Ham          Leeds  2001      4   21
3159     Sunderland      Newcastle  2001      4   21
3160     Man United       Man City  2001      4   21
3161        Chelsea       Charlton  2001      4   21
3162        Ipswich       Coventry  2001      4   21
3163       Bradford          Derby  2001      4   21
3164        Arsenal        Everton  2001      4   21
3165      Leicester  Middlesbrough  2001      4   21
3166    Aston Villa    Southampton  2001      4   21
3167      Liverpool      Tottenham  2001      4   22
3168          Leeds        Chelsea  2001      4   28
3169       Man City       West Ham  2001      4   28
3170  Middlesbrough     Man United  2001      4   28
3171      Newcastle      Leicester  2001      4   28
3172    Southampton     Sunderland  2001      4   28
3173      Tottenham    Aston Villa  2001      4   28
3174          Derby        Arsenal  2001      4   28
3175       Coventry      Liverpool  2001      4   28
3176        Everton       Bradford  2001      4   28
3177       Charlton        Ipswich  2001      4   30
3178       Bradford      Liverpool  2001      5    1
3179      Newcastle    Southampton  2001      5    1
3180       West Ham    Southampton  2001      5    5
3181     Sunderland       Charlton  2001      5    5
3182     Man United          Derby  2001      5    5
3183      Leicester      Tottenham  2001      5    5
3184        Chelsea        Everton  2001      5    5
3185       Bradford  Middlesbrough  2001      5    5
3186      Liverpool      Newcastle  2001      5    5
3187        Arsenal          Leeds  2001      5    5
3188    Aston Villa       Coventry  2001      5    5
3189        Ipswich       Man City  2001      5    7
3190      Liverpool        Chelsea  2001      5    8
3191          Leeds       Bradford  2001      5   13
3192    Southampton     Man United  2001      5   13
3193      Newcastle        Arsenal  2001      5   15
3194      Tottenham     Man United  2001      5   19
3195    Southampton        Arsenal  2001      5   19
3196      Newcastle    Aston Villa  2001      5   19
3197        Everton     Sunderland  2001      5   19
3198       Man City        Chelsea  2001      5   19
3199          Leeds      Leicester  2001      5   19
3200          Derby        Ipswich  2001      5   19
3201       Coventry       Bradford  2001      5   19
3202       Charlton      Liverpool  2001      5   19
3203  Middlesbrough       West Ham  2001      5   19

In [ ]:
match_data = {
    # -------------------- 3 February 2001 - Matchweek 26 --------------------
    ('Liverpool', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 44045
    },  # Source: 11v11 [0L4-L7], sport.de [0L22-L25], FBref [0L20-L21]

    ('Man United', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 67528
    },  # Source: Global Sports Archive [1L4-L8], footballdatabase [1L11-L13]

    ('Middlesbrough', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 31794
    },  # Source: bluemoon-mcfc [2L10-L12], football-lineups [2L19-L22], sport.de [2L17]

    ('Tottenham', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 35368
    },  # Source: thfcdb [3L5-L7], Wikipedia [3L18]

    ('Bradford', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 26,
        'Attendance': 19591
    },  # Source: AVFC History [4L5-L7], Wikipedia [4L19-L20], sport.de [4L33-L35]

    # -------------------- 7 February 2001 - Matchweek 21 --------------------
    ('Everton', 'Leeds'): {
        'WeekDay': 'Wed', 'Time': '20:00', 'Round': 21,
        'Attendance': 34224
    },  # Source: evertonresults [5L5-L6], Guardian [5L19], FBref [5L33]

    # -------------------- 10 February 2001 - Matchweek 27 --------------------
    ('Everton', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 30409
    },  # Source: 11v11 [6L5-L7], sport.de [6L23-L25]

    ('Leeds', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 38789
    },  # Source: sport.de [7L9-L12], football-lineups [7L15-L16], FBref [7L28-L29]

    ('Man City', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 34399
    },  # Source: 11v11 [8L10-L13], globalnet [8L17]

    ('Southampton', 'Bradford'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 14651
    },  # Source: Wikipedia [9L26], sport.de [9L34-L36]

    ('Sunderland', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 47553
    },  # Source: LFChistory [10L5-L7], 11v11 [10L9-L11]

    ('Arsenal', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 38011
    },  # Source: 11v11 [11L5-L7], sport.de [11L20-L21]

    ('Aston Villa', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 28912
    },  # Source: Wikipedia [12L12], sport.de [12L24-L27]

    ('Chelsea', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 27,
        'Attendance': 34960
    },  # Source: Global Sports Archive [13L6-L8], 11v11 [13L10-L12]

    # -------------------- 11 February 2001 - Matchweek 27 --------------------
    ('Charlton', 'Newcastle'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 27,
        'Attendance': 20043
    },  # Source: Wikipedia [14L11-L12], Global Sports Archive [14L21-L22], FBref [14L26-L27]

    # -------------------- 12 February 2001 - Matchweek 27 --------------------
    ('West Ham', 'Coventry'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 27,
        'Attendance': 22586
    },  # Source: Wikipedia [15L7], Global Sports Archive [15L24-L25]

    # -------------------- 24 February 2001 - Matchweek 28 --------------------
    ('Tottenham', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 36070
    },  # Source: leeds-fans [16L10-L11], Sky Sports [16L15]

    ('Newcastle', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 51981
    },  # Source: sport.de [17L11-L13], bluemoon-mcfc [17L16]

    ('Ipswich', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 22220
    },  # Source: Wikipedia [18L13], Global Sports Archive [18L21-L22]

    ('Leicester', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 21086
    },  # Source: thestatcat [19L6], Wikipedia [19L21]

    ('Derby', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 27289
    },  # Source: AVDB [20L5], Wikipedia [20L16], sport.de [20L36]

    ('Coventry', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 19480
    },  # Source: doingthe92 [21L6], Wikipedia [21L17]

    ('Bradford', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 20469
    },  # Source: sport.de [22L13], Global Sports Archive [22L17]

    ('Middlesbrough', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 28,
        'Attendance': 28725
    },  # Source: Wikipedia [23L17], Wikipedia [23L26]

    # -------------------- 25 February 2001 - Matchweek 28 --------------------
    ('Man United', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '13:00', 'Round': 28,
        'Attendance': 67535
    },  # Source: 11v11 [24L11-L12]

    # -------------------- 3 March 2001 - Matchweek 29 --------------------
    ('Middlesbrough', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 28177
    },  # Source: Wikipedia [25L11], Wikipedia [25L34]

    ('Man City', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 33990
    },  # Source: 11v11 [26L12]

    ('Arsenal', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 38071
    },  # Source: leesun [27L14], FBref [27L18]

    ('Leeds', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '12:00', 'Round': 29,
        'Attendance': None
    },  

    ('Everton', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 35779
    },  # Source: 11v11 [29L5-L7], sport.de [29L27-L28]

    ('Coventry', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 21609
    },  # Source: stamford-bridge [30L30]

    ('Leicester', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 21924
    },  # Source: Global Sports Archive [31L18]

    ('Derby', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 29,
        'Attendance': 29410
    },  # Source: thfcdb [32L6-L7], sport.de [32L16-L17]

    # -------------------- 4 March 2001 - Matchweek 29 --------------------
    ('Ipswich', 'Bradford'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 29,
        'Attendance': 21820
    },  # Source: Wikipedia [33L20], FBref [33L30], sport.de [33L39-L40]

    # -------------------- 5 March 2001 - Matchweek 29 --------------------
    ('Sunderland', 'Aston Villa'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 29,
        'Attendance': 47196
    },  # Source: AVFC History [34L6-L7], thestatcat [34L10], sport.de [34L29-L30]

    # -------------------- 7 March 2001 - Matchweek 21 --------------------
    ('West Ham', 'Chelsea'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 21,
        'Attendance': 26016
    },  # Source: stamford-bridge [35L15], FBref [35L20]

    # -------------------- 10 March 2001 - Matchweek 25 --------------------
    ('Aston Villa', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 25,
        'Attendance': 28216
    },  # Source: 11v11 [36L5-L7], AVDB [36L9-L10]

    # -------------------- 17 March 2001 - Matchweek 30 --------------------
    ('West Ham', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 26046
    },  # Source: 11v11 [37L5-L7], Global Sports Archive [37L15]

    ('Tottenham', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 35606
    },  # Source: thfcdb [38L6], football-lineups [38L25]

    ('Newcastle', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 51751
    },  # Source: 11v11 [39L5-L7], sport.de [39L33-L34]

    ('Man United', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 67516
    },  # Source: Global Sports Archive [40L8]

    ('Chelsea', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 34981
    },  # Source: thestatcat [41L6], Wikipedia [41L16]

    ('Charlton', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 20043
    },  # Source: Wikipedia [42L17], Global Sports Archive [42L37]

    ('Bradford', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 19117
    },  # Source: football-lineups [43L11], sport.de [43L20]

    ('Southampton', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 30,
        'Attendance': 15251
    },  # Source: Wikipedia [44L8], Wikipedia [44L23]

    # -------------------- 18 March 2001 - Matchweek 30 --------------------
    ('Aston Villa', 'Arsenal'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 30,
        'Attendance': 36111
    },  # Source: Wikipedia [45L12], sport.de [45L23-L24]

    ('Liverpool', 'Derby'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 30,
        'Attendance': 43362
    },  # Source: LFChistory [46L6-L7], sport.de [46L20-L21]

    # -------------------- 31 March 2001 - Matchweek 31 --------------------
    ('West Ham', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 26044
    },  # Source: 11v11 [47L5-L7], evertonresults [47L14]

    ('Sunderland', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 48285
    },  # Source: Wikipedia [48L7], sport.de [48L23-L24]

    ('Man City', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 34247
    },  # Source: football-lineups [49L11], sport.de [49L16-L17]

    ('Liverpool', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '12:00', 'Round': 31,
        'Attendance': 44806
    },  # Source: Global Sports Archive [50L12], 11v11 [50L16-L17]

    ('Coventry', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 19622
    },  # Source: ccfpa [51L28], ccfpa [51L33]

    ('Arsenal', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 38120
    },  # Source: Sky Sports [52L33]

    ('Bradford', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 20160
    },  # Source: Wikipedia [53L23], sport.de [53L33]

    ('Chelsea', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 31,
        'Attendance': 34933
    },  # Source: 11v11 [54L5-L7], Wikipedia [54L20]

    # -------------------- 1 April 2001 - Matchweek 31 --------------------
    ('Charlton', 'Leicester'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 31,
        'Attendance': 20043
    },  # Source: Wikipedia [55L23-L24], Sky Sports [55L43]

    # -------------------- 2 April 2001 - Matchweek 31 --------------------
    ('Southampton', 'Ipswich'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 31,
        'Attendance': 15244
    },  # Source: FBref [37L36-L37]

    # -------------------- 4 April 2001 - Matchweek 23 --------------------
    ('Aston Villa', 'Leicester'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 23,
        'Attendance': 26137
    },  # Source: AVFC History

    # -------------------- 7 April 2001 - Matchweek 32 --------------------
    ('Aston Villa', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 28349
    },  # Source: AVFC History

    ('Derby', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 29751
    },  # Source: stamford-bridge

    ('Leeds', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 38208
    },  # Source: leeds-fans

    ('Leicester', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 32,
        'Attendance': 21163
    },  # Source: foxestalk

    ('Everton', 'Man City'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 32,
        'Attendance': 34062
    },  # Source: evertonresults

    ('Middlesbrough', 'Sunderland'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 32,
        'Attendance': 30285
    },  # Source: thestatcat

    ('Man United', 'Charlton'): {
        'WeekDay': 'Tue', 'Time': '20:00', 'Round': 32,
        'Attendance': 67539
    },  # Source: mufcinfo

    ('Ipswich', 'Liverpool'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 32,
        'Attendance': 24258
    },  # Source: Pride of Anglia

    ('Tottenham', 'Bradford'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 32,
        'Attendance': 34568
    },  # Source: thfcdb

    # -------------------- 11 April 2001 - Matchweek 32 --------------------
    ('Man City', 'Arsenal'): {
        'WeekDay': 'Wed', 'Time': '19:45', 'Round': 32,
        'Attendance': 32492
    },  # Source: bluemoon-mcfc

    # -------------------- 13 April 2001 - Matchweek 33 --------------------
    ('Bradford', 'Charlton'): {
        'WeekDay': 'Fri', 'Time': '19:45', 'Round': 33,
        'Attendance': 16221
    },  # Source: Wikipedia

    ('Liverpool', 'Leeds'): {
        'WeekDay': 'Fri', 'Time': '20:00', 'Round': 33,
        'Attendance': 44008
    },  # Source: LFChistory

    # -------------------- 14 April 2001 - Matchweek 33 --------------------
    ('West Ham', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 25859
    },  # Source: 11v11

    ('Sunderland', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 46180
    },  # Source: thestatcat

    ('Aston Villa', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 28874
    },  # Source: AVFC History

    ('Leicester', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 20549
    },  # Source: foxestalk

    ('Man United', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 67637
    },  # Source: mufcinfo

    ('Arsenal', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 38031
    },  # Source: FBref

    ('Chelsea', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 34238
    },  # Source: stamford-bridge

    ('Ipswich', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 33,
        'Attendance': 24952
    },  # Source: Pride of Anglia

    # -------------------- 16 April 2001 - Matchweek 33 --------------------
    ('Everton', 'Liverpool'): {
        'WeekDay': 'Mon', 'Time': '12:00', 'Round': 33,
        'Attendance': 40260
    },  # Source: evertonresults

    ('Middlesbrough', 'Ipswich'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 33,
        'Attendance': 26671
    },  # Source: 11v11

    ('Newcastle', 'West Ham'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 33,
        'Attendance': 51213
    },  # Source: nufc

    ('Coventry', 'Sunderland'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 33,
        'Attendance': 19060
    },  # Source: skybluearchive

    ('Derby', 'Leicester'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 33,
        'Attendance': 25302
    },  # Source: Wikipedia

    # -------------------- 17 April 2001 - Matchweek 33 --------------------
    ('Charlton', 'Aston Villa'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 33,
        'Attendance': 20043
    },  # Source: Wikipedia

    ('Tottenham', 'Chelsea'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 33,
        'Attendance': 36038
    },  # Source: thfcdb

    # -------------------- 21 April 2001 - Matchweek 34 --------------------
    ('West Ham', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 26037
    },  # Source: 11v11

    ('Sunderland', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '12:00', 'Round': 34,
        'Attendance': 48285
    },  # Source: thestatcat

    ('Man United', 'Man City'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 67542
    },  # Source: mufcinfo

    ('Chelsea', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 34922
    },  # Source: stamford-bridge

    ('Ipswich', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 23445
    },  # Source: Pride of Anglia

    ('Bradford', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 16795
    },  # Source: Wikipedia

    ('Arsenal', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 38016
    },  # Source: FBref

    ('Leicester', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 20337
    },  # Source: foxestalk

    ('Aston Villa', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 34,
        'Attendance': 27515
    },  # Source: AVFC History

    # -------------------- 22 April 2001 - Matchweek 34 --------------------
    ('Liverpool', 'Tottenham'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 34,
        'Attendance': 43711
    },  # Source: LFChistory

    # -------------------- 28 April 2001 - Matchweek 35 --------------------
    ('Leeds', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 35,
        'Attendance': 39953
    },  # Source: leeds-fans

    ('Man City', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 35,
        'Attendance': 33033
    },  # Source: bluemoon-mcfc

    ('Middlesbrough', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 35,
        'Attendance': 34696
    },  # Source: 11v11

    ('Newcastle', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 35,
        'Attendance': 50576
    },  # Source: nufc

    ('Southampton', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 35,
        'Attendance': 15242
    },  # Source: Wikipedia

    ('Tottenham', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 35,
        'Attendance': 36088
    },  # Source: thfcdb

    ('Derby', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 35,
        'Attendance': 33221
    },  # Source: Wikipedia

    ('Coventry', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 35,
        'Attendance': 22293
    },  # Source: skybluearchive

    ('Everton', 'Bradford'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 35,
        'Attendance': 35034
    },  # Source: evertonresults

    # -------------------- 30 April 2001 - Matchweek 35 --------------------
    ('Charlton', 'Ipswich'): {
        'WeekDay': 'Mon', 'Time': '20:00', 'Round': 35,
        'Attendance': 20043
    },  # Source: Wikipedia

    # -------------------- 1 May 2001 - Matchweek 33 --------------------
    ('Bradford', 'Liverpool'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 33,
        'Attendance': 22057
    },  # Source: LFChistory

    ('Newcastle', 'Southampton'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 33,
        'Attendance': 50102
    },  # Source: nufc

    # -------------------- 5 May 2001 - Matchweek 36 --------------------
    ('West Ham', 'Southampton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 26001
    },  # Source: 11v11

    ('Sunderland', 'Charlton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 44779
    },  # Source: thestatcat

    ('Man United', 'Derby'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 67587
    },  # Source: mufcinfo

    ('Leicester', 'Tottenham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 21712
    },  # Source: foxestalk

    ('Chelsea', 'Everton'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 34925
    },  # Source: stamford-bridge

    ('Bradford', 'Middlesbrough'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 17031
    },  # Source: Wikipedia

    ('Liverpool', 'Newcastle'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 44394
    },  # Source: LFChistory

    ('Arsenal', 'Leeds'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 38121
    },  # Source: FBref

    ('Aston Villa', 'Coventry'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 36,
        'Attendance': 28739
    },  # Source: AVFC History

    # -------------------- 7 May 2001 - Matchweek 36 --------------------
    ('Ipswich', 'Man City'): {
        'WeekDay': 'Mon', 'Time': '15:00', 'Round': 36,
        'Attendance': 27536
    },  # Source: Pride of Anglia

    # -------------------- 8 May 2001 - Matchweek 33 --------------------
    ('Liverpool', 'Chelsea'): {
        'WeekDay': 'Tue', 'Time': '20:00', 'Round': 33,
        'Attendance': 40736
    },  # Source: LFChistory

    # -------------------- 13 May 2001 - Matchweek 37 --------------------
    ('Leeds', 'Bradford'): {
        'WeekDay': 'Sun', 'Time': '15:00', 'Round': 37,
        'Attendance': 39759
    },  # Source: leeds-fans

    ('Southampton', 'Man United'): {
        'WeekDay': 'Sun', 'Time': '16:00', 'Round': 37,
        'Attendance': 15252
    },  # Source: Wikipedia

    # -------------------- 15 May 2001 - Matchweek 35 --------------------
    ('Newcastle', 'Arsenal'): {
        'WeekDay': 'Tue', 'Time': '19:45', 'Round': 35,
        'Attendance': 52000
    },  # Source: nufc

    # -------------------- 19 May 2001 - Matchweek 38 --------------------
    ('Tottenham', 'Man United'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 38,
        'Attendance': 36031
    },  # Source: thfcdb

    ('Southampton', 'Arsenal'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 38,
        'Attendance': 15250
    },  # Source: Wikipedia

    ('Newcastle', 'Aston Villa'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 38,
        'Attendance': 51546
    },  # Source: nufc

    ('Everton', 'Sunderland'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 38,
        'Attendance': 37195
    },  # Source: evertonresults

    ('Man City', 'Chelsea'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 38,
        'Attendance': 34457
    },  # Source: bluemoon-mcfc

    ('Leeds', 'Leicester'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 38,
        'Attendance': 39165
    },  # Source: leeds-fans

    ('Derby', 'Ipswich'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 38,
        'Attendance': 31051
    },  # Source: Wikipedia

    ('Coventry', 'Bradford'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 38,
        'Attendance': 19542
    },  # Source: skybluearchive

    ('Charlton', 'Liverpool'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 38,
        'Attendance': 20043
    },  # Source: Wikipedia

    ('Middlesbrough', 'West Ham'): {
        'WeekDay': 'Sat', 'Time': '15:00', 'Round': 38,
        'Attendance': 30950
    },  # Source: 11v11
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0001',
    data=match_data,
    value_col=['WeekDay', 'Time', 'Round', 'Attendance'],
    inplace=True
)

In [19]:
null_rows(df, "0001","Time")

           HomeTeam       AwayTeam  Year  Month  Day
2824       Charlton       Man City  2000      8   19
2825          Leeds        Everton  2000      8   19
2826          Derby    Southampton  2000      8   19
2827        Chelsea       West Ham  2000      8   19
2828      Tottenham        Ipswich  2000      8   19
2829      Leicester    Aston Villa  2000      8   19
2830     Sunderland        Arsenal  2000      8   19
2831       Coventry  Middlesbrough  2000      8   19
2832      Liverpool       Bradford  2000      8   19
2833     Man United      Newcastle  2000      8   20
2834        Arsenal      Liverpool  2000      8   21
2835  Middlesbrough      Tottenham  2000      8   22
2836       Bradford        Chelsea  2000      8   22
2837        Ipswich     Man United  2000      8   22
2838    Southampton       Coventry  2000      8   23
2839       Man City     Sunderland  2000      8   23
2840        Everton       Charlton  2000      8   23
2841      Newcastle          Derby  2000      8   23
2842       West Ham      Leicester  2000      8   23
2843        Everton          Derby  2000      8   26
2844        Ipswich     Sunderland  2000      8   26
2845       Man City       Coventry  2000      8   26
2846  Middlesbrough          Leeds  2000      8   26
2847      Newcastle      Tottenham  2000      8   26
2848    Southampton      Liverpool  2000      8   26
2849       West Ham     Man United  2000      8   26
2850       Bradford      Leicester  2000      8   26
2851        Arsenal       Charlton  2000      8   26
2852    Aston Villa        Chelsea  2000      8   27
2853          Leeds       Man City  2000      9    5
2854     Man United       Bradford  2000      9    5
2855     Sunderland       West Ham  2000      9    5
2856      Tottenham        Everton  2000      9    5
2857      Liverpool    Aston Villa  2000      9    6
2858      Leicester        Ipswich  2000      9    6
2859       Coventry      Newcastle  2000      9    6
2860        Chelsea        Arsenal  2000      9    6
2861       Charlton    Southampton  2000      9    6
2862          Derby  Middlesbrough  2000      9    6
2863      Newcastle        Chelsea  2000      9    9
2864  Middlesbrough        Everton  2000      9    9
2865       Bradford        Arsenal  2000      9    9
2866      Liverpool       Man City  2000      9    9
2867      Leicester    Southampton  2000      9    9
2868        Ipswich    Aston Villa  2000      9    9
2869       Coventry          Leeds  2000      9    9
2870     Man United     Sunderland  2000      9    9
2871          Derby       Charlton  2000      9   10
2872      Tottenham       West Ham  2000      9   11
2873        Arsenal       Coventry  2000      9   16
2874    Aston Villa       Bradford  2000      9   16
2875       Charlton      Tottenham  2000      9   16
2876        Everton     Man United  2000      9   16
2877          Leeds        Ipswich  2000      9   16
2878    Southampton      Newcastle  2000      9   16
2879     Sunderland          Derby  2000      9   16
2880       West Ham      Liverpool  2000      9   17
2881        Chelsea      Leicester  2000      9   17
2882       Man City  Middlesbrough  2000      9   17
2883       Bradford    Southampton  2000      9   23
2884      Tottenham       Man City  2000      9   23
2885      Newcastle       Charlton  2000      9   23
2886       Coventry       West Ham  2000      9   23
2887     Man United        Chelsea  2000      9   23
2888      Liverpool     Sunderland  2000      9   23
2889          Derby          Leeds  2000      9   23
2890        Ipswich        Arsenal  2000      9   23
2891  Middlesbrough    Aston Villa  2000      9   23
2892      Leicester        Everton  2000      9   24
2893       West Ham       Bradford  2000      9   30
2894    Southampton  Middlesbrough  2000      9   30
2895          Leeds      Tottenham  2000      9   30
2896        Everton        Ipswich  2000      9   30
2897       Charlton       Coventry  2000      9   30
2898    Aston Villa          Derby  2000      9   30
2899       Man City      Newcastle  2000      9   30
2900        Arsenal     Man United  2000     10    1
2901        Chelsea      Liverpool  2000     10    1
2902     Sunderland      Leicester  2000     10    1
2903     Sunderland        Chelsea  2000     10   14
2904       Man City       Bradford  2000     10   14
2905        Ipswich       West Ham  2000     10   14
2906          Leeds       Charlton  2000     10   14
2907        Everton    Southampton  2000     10   14
2908       Coventry      Tottenham  2000     10   14
2909      Leicester     Man United  2000     10   14
2910        Arsenal    Aston Villa  2000     10   14
2911          Derby      Liverpool  2000     10   15
2912  Middlesbrough      Newcastle  2000     10   16
2913       Bradford        Ipswich  2000     10   21
2914       Charlton  Middlesbrough  2000     10   21
2915        Chelsea       Coventry  2000     10   21
2916      Liverpool      Leicester  2000     10   21
2917     Man United          Leeds  2000     10   21
2918      Newcastle        Everton  2000     10   21
2919      Tottenham          Derby  2000     10   21
2920       West Ham        Arsenal  2000     10   21
2921    Aston Villa     Sunderland  2000     10   22
2922    Southampton       Man City  2000     10   23
2923        Chelsea      Tottenham  2000     10   28
2931       Bradford          Leeds  2000     10   29
2975       Bradford       Coventry  2000     12    2
2977      Leicester          Leeds  2000     12    2
2980       West Ham  Middlesbrough  2000     12    2
2982     Sunderland        Everton  2000     12    4
2987       Charlton     Man United  2000     12    9
2991       Coventry      Leicester  2000     12   10
2994        Ipswich    Southampton  2000     12   16
2998      Newcastle       Bradford  2000     12   16
3001     Man United      Liverpool  2000     12   17
3003       Coventry    Southampton  2000     12   22
3004     Man United        Ipswich  2000     12   23
3007      Liverpool        Arsenal  2000     12   23
3008          Leeds    Aston Villa  2000     12   23
3011       Charlton        Everton  2000     12   23
3012      Leicester       West Ham  2000     12   23
3013        Arsenal      Leicester  2000     12   26
3014    Aston Villa     Man United  2000     12   26
3015       Bradford     Sunderland  2000     12   26
3016        Everton       Coventry  2000     12   26
3017        Ipswich        Chelsea  2000     12   26
3018       Man City          Derby  2000     12   26
3019  Middlesbrough      Liverpool  2000     12   26
3020      Newcastle          Leeds  2000     12   26
3021       West Ham       Charlton  2000     12   26
3022    Southampton      Tottenham  2000     12   27
3023  Middlesbrough       Coventry  2000     12   30
3024      Newcastle     Man United  2000     12   30
3025    Southampton          Derby  2000     12   30
3026        Ipswich      Tottenham  2000     12   30
3027        Arsenal     Sunderland  2000     12   30
3028       Man City       Charlton  2000     12   30
3029     Man United       West Ham  2001      1    1
3030     Sunderland        Ipswich  2001      1    1
3031      Liverpool    Southampton  2001      1    1
3032          Derby        Everton  2001      1    1
3033          Leeds  Middlesbrough  2001      1    1
3034       Charlton        Arsenal  2001      1    1
3035        Chelsea    Aston Villa  2001      1    1
3036       Coventry       Man City  2001      1    1
3037      Leicester       Bradford  2001      1    1
3038      Tottenham      Newcastle  2001      1    2
3039       West Ham     Sunderland  2001      1   13
3040    Southampton       Charlton  2001      1   13
3041      Newcastle       Coventry  2001      1   13
3042  Middlesbrough          Derby  2001      1   13
3043        Everton      Tottenham  2001      1   13
3044       Bradford     Man United  2001      1   13
3045    Aston Villa      Liverpool  2001      1   13
3046        Arsenal        Chelsea  2001      1   13
3047       Man City          Leeds  2001      1   13
3048        Ipswich      Leicester  2001      1   14
3049     Man United    Aston Villa  2001      1   20
3050      Liverpool  Middlesbrough  2001      1   20
3051      Tottenham    Southampton  2001      1   20
3052          Leeds      Newcastle  2001      1   20
3053      Leicester        Arsenal  2001      1   20
3054       Coventry        Everton  2001      1   20
3055          Derby       Man City  2001      1   20
3056        Chelsea        Ipswich  2001      1   20
3057     Sunderland       Bradford  2001      1   21
3058       Charlton       West Ham  2001      1   22
3059    Aston Villa          Leeds  2001      1   24
3060        Arsenal       Bradford  2001      1   30
3061       Charlton          Derby  2001      1   30
3062       West Ham      Tottenham  2001      1   31
3063     Sunderland     Man United  2001      1   31
3064       Man City      Liverpool  2001      1   31
3065          Leeds       Coventry  2001      1   31
3066        Everton  Middlesbrough  2001      1   31
3067        Chelsea      Newcastle  2001      1   31
3068    Southampton      Leicester  2001      1   31
3069       Coventry        Arsenal  2001      2    3
3070          Derby     Sunderland  2001      2    3
3071        Ipswich          Leeds  2001      2    3
3072      Leicester        Chelsea  2001      2    3

In [ ]:
match_data = {
    # -------------------- 19 August 2000 - Matchweek 1 --------------------
    ('Charlton', 'Man City'): {
        'Time': None, 'Attendance': 20043
    },  # Source: FBref [5L20-L21]
    ('Leeds', 'Everton'): {
        'Time': None, 'Attendance': 40010
    },  # Source: FBref [5L10-L11]
    ('Derby', 'Southampton'): {
        'Time': None, 'Attendance': 27223
    },  # Source: FBref [5L17-L18]
    ('Chelsea', 'West Ham'): {
        'Time': None, 'Attendance': 34914
    },  # Source: FBref [5L13-L14]
    ('Tottenham', 'Ipswich'): {
        'Time': None, 'Attendance': 36148
    },  # Source: FBref [5L15-L16]
    ('Leicester', 'Aston Villa'): {
        'Time': None, 'Attendance': 21455
    },  # Source: FBref [5L22-L23]
    ('Sunderland', 'Arsenal'): {
        'Time': None, 'Attendance': 47121
    },  # Source: FBref [5L19-L20]
    ('Coventry', 'Middlesbrough'): {
        'Time': None, 'Attendance': 20624
    },  # Source: FBref [5L16-L17]
    ('Liverpool', 'Bradford'): {
        'Time': None, 'Attendance': 44183
    },  # Source: FBref [5L12-L13]
    ('Man United', 'Newcastle'): {
        'Time': None, 'Attendance': 67477
    },  # Source: FBref [5L23-L24]

    # -------------------- 21 August 2000 - Matchweek 2 --------------------
    ('Arsenal', 'Liverpool'): {
        'Time': None, 'Attendance': 38014
    },  # Source: FBref [5L24-L25]

    # -------------------- 22 August 2000 - Matchweek 2 --------------------
    ('Middlesbrough', 'Tottenham'): {
        'Time': None, 'Attendance': 31254
    },  # Source: FBref [5L29-L30]
    ('Bradford', 'Chelsea'): {
        'Time': None, 'Attendance': 17872
    },  # Source: FBref [5L27-L28]
    ('Ipswich', 'Man United'): {
        'Time': None, 'Attendance': 22007
    },  # Source: FBref [5L26-L27]

    # -------------------- 23 August 2000 - Matchweek 2 --------------------
    ('Southampton', 'Coventry'): {
        'Time': None, 'Attendance': 14801
    },  # Source: FBref [5L30-L31]
    ('Man City', 'Sunderland'): {
        'Time': None, 'Attendance': 34410
    },  # Source: FBref [5L33-L34]
    ('Everton', 'Charlton'): {
        'Time': None, 'Attendance': 36300
    },  # Source: FBref [5L36-L37]
    ('Newcastle', 'Derby'): {
        'Time': None, 'Attendance': 51327
    },  # Source: FBref [5L31-L32]
    ('West Ham', 'Leicester'): {
        'Time': None, 'Attendance': 25195
    },  # Source: FBref [5L34-L35]

    # -------------------- 26 August 2000 - Matchweek 3 --------------------
    ('Everton', 'Derby'): {
        'Time': None, 'Attendance': 34840
    },  # Source: FBref [6L49-L50]
    ('Ipswich', 'Sunderland'): {
        'Time': None, 'Attendance': 21830
    },  # Source: FBref [6L37-L38]
    ('Man City', 'Coventry'): {
        'Time': None, 'Attendance': 34140
    },  # Source: FBref [6L46-L47]
    ('Middlesbrough', 'Leeds'): {
        'Time': None, 'Attendance': 31626
    },  # Source: FBref [6L44-L45]
    ('Newcastle', 'Tottenham'): {
        'Time': None, 'Attendance': 51573
    },  # Source: FBref [6L40-L41]
    ('Southampton', 'Liverpool'): {
        'Time': None, 'Attendance': 15202
    },  # Source: FBref [6L41-L42]
    ('West Ham', 'Man United'): {
        'Time': None, 'Attendance': 25988
    },  # Source: FBref [6L47-L48]
    ('Bradford', 'Leicester'): {
        'Time': None, 'Attendance': 16766
    },  # Source: FBref [6L38-L39]
    ('Arsenal', 'Charlton'): {
        'Time': None, 'Attendance': 38025
    },  # Source: FBref [6L43-L44]
    ('Aston Villa', 'Chelsea'): {
        'Time': None, 'Attendance': 27057
    },  # Source: FBref [6L50-L51]

    # -------------------- 5 September 2000 - Matchweek 4 --------------------
    ('Leeds', 'Man City'): {
        'Time': None, 'Attendance': 40055
    },  # Source: FBref [6L51-L52]
    ('Man United', 'Bradford'): {
        'Time': None, 'Attendance': 66447
    },  # Source: FBref [6L55-L56]
    ('Sunderland', 'West Ham'): {
        'Time': None, 'Attendance': 46605
    },  # Source: FBref [6L53-L54]
    ('Tottenham', 'Everton'): {
        'Time': None, 'Attendance': 35316
    },  # Source: FBref [6L54-L55]

    # -------------------- 6 September 2000 - Matchweek 4 --------------------
    ('Liverpool', 'Aston Villa'): {
        'Time': None, 'Attendance': 43360
    },  # Source: FBref [6L60-L61]
    ('Leicester', 'Ipswich'): {
        'Time': None, 'Attendance': 19598
    },  # Source: FBref [6L58-L59]
    ('Coventry', 'Newcastle'): {
        'Time': None, 'Attendance': 22109
    },  # Source: FBref [6L62-L63]
    ('Chelsea', 'Arsenal'): {
        'Time': None, 'Attendance': 34923
    },  # Source: FBref [6L61-L62]
    ('Charlton', 'Southampton'): {
        'Time': None, 'Attendance': 20043
    },  # Source: FBref [6L57-L58]
    ('Derby', 'Middlesbrough'): {
        'Time': None, 'Attendance': 24290
    },  # Source: FBref [6L63-L64]

    # -------------------- 9 September 2000 - Matchweek 5 --------------------
    ('Newcastle', 'Chelsea'): {
        'Time': None, 'Attendance': 51687
    },  # Source: FBref [7L73-L74]
    ('Middlesbrough', 'Everton'): {
        'Time': None, 'Attendance': 30885
    },  # Source: FBref [7L72-L73]
    ('Bradford', 'Arsenal'): {
        'Time': None, 'Attendance': 17160
    },  # Source: FBref [7L75-L76]
    ('Liverpool', 'Man City'): {
        'Time': None, 'Attendance': 44692
    },  # Source: FBref [7L76-L77]
    ('Leicester', 'Southampton'): {
        'Time': None, 'Attendance': 18366
    },  # Source: FBref [7L65-L66]
    ('Ipswich', 'Aston Villa'): {
        'Time': None, 'Attendance': 20665
    },  # Source: FBref [7L66-L67]
    ('Coventry', 'Leeds'): {
        'Time': None, 'Attendance': 20377
    },  # Source: FBref [7L69-L70]
    ('Man United', 'Sunderland'): {
        'Time': None, 'Attendance': 67503
    },  # Source: FBref [7L70-L71]
    ('Derby', 'Charlton'): {
        'Time': None, 'Attendance': 22310
    },  # Source: FBref [7L77-L78]
    ('Tottenham', 'West Ham'): {
        'Time': None, 'Attendance': 33282
    },  # Source: FBref [7L79-L80]

    # -------------------- 16 September 2000 - Matchweek 6 --------------------
    ('Arsenal', 'Coventry'): {
        'Time': None, 'Attendance': 37794
    },  # Source: FBref [7L86-L87]
    ('Aston Villa', 'Bradford'): {
        'Time': None, 'Attendance': 27849
    },  # Source: FBref [7L81-L82]
    ('Charlton', 'Tottenham'): {
        'Time': None, 'Attendance': 20043
    },  # Source: FBref [7L84-L85]
    ('Everton', 'Man United'): {
        'Time': None, 'Attendance': 38541
    },  # Source: FBref [7L88-L89]
    ('Leeds', 'Ipswich'): {
        'Time': None, 'Attendance': 35552
    },  # Source: FBref [7L87-L88]
    ('Southampton', 'Newcastle'): {
        'Time': None, 'Attendance': 15221
    },  # Source: FBref [7L80-L81]
    ('Sunderland', 'Derby'): {
        'Time': None, 'Attendance': 45343
    },  # Source: FBref [7L83-L84]
    ('West Ham', 'Liverpool'): {
        'Time': None, 'Attendance': 25998
    },  # Source: FBref [7L91-L92]
    ('Chelsea', 'Leicester'): {
        'Time': None, 'Attendance': 33697
    },  # Source: FBref [7L93-L94]
    ('Man City', 'Middlesbrough'): {
        'Time': None, 'Attendance': 32053
    },  # Source: FBref [7L90-L91]

    # -------------------- 23 September 2000 - Matchweek 7 --------------------
    ('Bradford', 'Southampton'): {
        'Time': None, 'Attendance': 16163
    },  # Source: FBref [7L94-L95]
    ('Tottenham', 'Man City'): {
        'Time': None, 'Attendance': 36069
    },  # Source: FBref [8L105-L106]
    ('Newcastle', 'Charlton'): {
        'Time': None, 'Attendance': 50866
    },  # Source: FBref [7L95-L96]
    ('Coventry', 'West Ham'): {
        'Time': None, 'Attendance': 21020
    },  # Source: FBref [7L100-L101]
    ('Man United', 'Chelsea'): {
        'Time': None, 'Attendance': 67568
    },  # Source: FBref [8L103-L104]
    ('Liverpool', 'Sunderland'): {
        'Time': None, 'Attendance': 44713
    },  # Source: FBref [8L104-L105]
    ('Derby', 'Leeds'): {
        'Time': None, 'Attendance': 26248
    },  # Source: FBref [7L98-L99]
    ('Ipswich', 'Arsenal'): {
        'Time': None, 'Attendance': 22030
    },  # Source: FBref [7L97-L98]
    ('Middlesbrough', 'Aston Villa'): {
        'Time': None, 'Attendance': 27556
    },  # Source: FBref [8L101-L102]
    ('Leicester', 'Everton'): {
        'Time': None, 'Attendance': 18084
    },  # Source: FBref [8L106-L107]

    # -------------------- 30 September 2000 - Matchweek 8 --------------------
    ('West Ham', 'Bradford'): {
        'Time': None, 'Attendance': 25407
    },  # Source: FBref [8L109-L110]
    ('Southampton', 'Middlesbrough'): {
        'Time': None, 'Attendance': 14903
    },  # Source: FBref [8L113-L114]
    ('Leeds', 'Tottenham'): {
        'Time': None, 'Attendance': 37562
    },  # Source: FBref [8L112-L113]
    ('Everton', 'Ipswich'): {
        'Time': None, 'Attendance': 32597
    },  # Source: FBref [8L111-L112]
    ('Charlton', 'Coventry'): {
        'Time': None, 'Attendance': 20043
    },  # Source: FBref [8L108-L109]
    ('Aston Villa', 'Derby'): {
        'Time': None, 'Attendance': 26534
    },  # Source: FBref [8L116-L117]
    ('Man City', 'Newcastle'): {
        'Time': None, 'Attendance': 34497
    },  # Source: FBref [8L115-L116]
    ('Arsenal', 'Man United'): {
        'Time': None, 'Attendance': 38146
    },  # Source: FBref [8L118-L119]
    ('Chelsea', 'Liverpool'): {
        'Time': None, 'Attendance': 34966
    },  # Source: FBref [8L119-L120]
    ('Sunderland', 'Leicester'): {
        'Time': None, 'Attendance': 45338
    },  # Source: FBref [8L120-L121]

    # -------------------- 14 October 2000 - Matchweek 9 --------------------
    ('Sunderland', 'Chelsea'): {
        'Time': None, 'Attendance': 45078
    },  # Source: FBref [8L129-L130]
    ('Man City', 'Bradford'): {
        'Time': None, 'Attendance': 34229
    },  # Source: FBref [8L122-L123]
    ('Leeds', 'Charlton'): {
        'Time': None, 'Attendance': 38837
    },  # Source: FBref [8L130-L131]
    ('Everton', 'Southampton'): {
        'Time': None, 'Attendance': 29491
    },  # Source: FBref [8L125-L126]
    ('Leicester', 'Man United'): {
        'Time': None, 'Attendance': 22132
    },  # Source: FBref [8L123-L124]
    ('Arsenal', 'Aston Villa'): {
        'Time': None, 'Attendance': 38042
    },  # Source: FBref [8L127-L128]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0001',
    data=match_data,
    value_col=['Time', 'Attendance'],
    inplace=True
)

In [22]:
null_rows(df, "0001","Time")[:100]

           HomeTeam       AwayTeam  Year  Month  Day
2824       Charlton       Man City  2000      8   19
2825          Leeds        Everton  2000      8   19
2826          Derby    Southampton  2000      8   19
2827        Chelsea       West Ham  2000      8   19
2828      Tottenham        Ipswich  2000      8   19
2829      Leicester    Aston Villa  2000      8   19
2830     Sunderland        Arsenal  2000      8   19
2831       Coventry  Middlesbrough  2000      8   19
2832      Liverpool       Bradford  2000      8   19
2833     Man United      Newcastle  2000      8   20
2834        Arsenal      Liverpool  2000      8   21
2835  Middlesbrough      Tottenham  2000      8   22
2836       Bradford        Chelsea  2000      8   22
2837        Ipswich     Man United  2000      8   22
2838    Southampton       Coventry  2000      8   23
2839       Man City     Sunderland  2000      8   23
2840        Everton       Charlton  2000      8   23
2841      Newcastle          Derby  2000      8   23
2842       West Ham      Leicester  2000      8   23
2843        Everton          Derby  2000      8   26
2844        Ipswich     Sunderland  2000      8   26
2845       Man City       Coventry  2000      8   26
2846  Middlesbrough          Leeds  2000      8   26
2847      Newcastle      Tottenham  2000      8   26
2848    Southampton      Liverpool  2000      8   26
2849       West Ham     Man United  2000      8   26
2850       Bradford      Leicester  2000      8   26
2851        Arsenal       Charlton  2000      8   26
2852    Aston Villa        Chelsea  2000      8   27
2853          Leeds       Man City  2000      9    5
2854     Man United       Bradford  2000      9    5
2855     Sunderland       West Ham  2000      9    5
2856      Tottenham        Everton  2000      9    5
2857      Liverpool    Aston Villa  2000      9    6
2858      Leicester        Ipswich  2000      9    6
2859       Coventry      Newcastle  2000      9    6
2860        Chelsea        Arsenal  2000      9    6
2861       Charlton    Southampton  2000      9    6
2862          Derby  Middlesbrough  2000      9    6
2863      Newcastle        Chelsea  2000      9    9
2864  Middlesbrough        Everton  2000      9    9
2865       Bradford        Arsenal  2000      9    9
2866      Liverpool       Man City  2000      9    9
2867      Leicester    Southampton  2000      9    9
2868        Ipswich    Aston Villa  2000      9    9
2869       Coventry          Leeds  2000      9    9
2870     Man United     Sunderland  2000      9    9
2871          Derby       Charlton  2000      9   10
2872      Tottenham       West Ham  2000      9   11
2873        Arsenal       Coventry  2000      9   16
2874    Aston Villa       Bradford  2000      9   16
2875       Charlton      Tottenham  2000      9   16
2876        Everton     Man United  2000      9   16
2877          Leeds        Ipswich  2000      9   16
2878    Southampton      Newcastle  2000      9   16
2879     Sunderland          Derby  2000      9   16
2880       West Ham      Liverpool  2000      9   17
2881        Chelsea      Leicester  2000      9   17
2882       Man City  Middlesbrough  2000      9   17
2883       Bradford    Southampton  2000      9   23
2884      Tottenham       Man City  2000      9   23
2885      Newcastle       Charlton  2000      9   23
2886       Coventry       West Ham  2000      9   23
2887     Man United        Chelsea  2000      9   23
2888      Liverpool     Sunderland  2000      9   23
2889          Derby          Leeds  2000      9   23
2890        Ipswich        Arsenal  2000      9   23
2891  Middlesbrough    Aston Villa  2000      9   23
2892      Leicester        Everton  2000      9   24
2893       West Ham       Bradford  2000      9   30
2894    Southampton  Middlesbrough  2000      9   30
2895          Leeds      Tottenham  2000      9   30
2896        Everton        Ipswich  2000      9   30
2897       Charlton       Coventry  2000      9   30
2898    Aston Villa          Derby  2000      9   30
2899       Man City      Newcastle  2000      9   30
2900        Arsenal     Man United  2000     10    1
2901        Chelsea      Liverpool  2000     10    1
2902     Sunderland      Leicester  2000     10    1
2903     Sunderland        Chelsea  2000     10   14
2904       Man City       Bradford  2000     10   14
2905        Ipswich       West Ham  2000     10   14
2906          Leeds       Charlton  2000     10   14
2907        Everton    Southampton  2000     10   14
2908       Coventry      Tottenham  2000     10   14
2909      Leicester     Man United  2000     10   14
2910        Arsenal    Aston Villa  2000     10   14
2911          Derby      Liverpool  2000     10   15
2912  Middlesbrough      Newcastle  2000     10   16
2913       Bradford        Ipswich  2000     10   21
2914       Charlton  Middlesbrough  2000     10   21
2915        Chelsea       Coventry  2000     10   21
2916      Liverpool      Leicester  2000     10   21
2917     Man United          Leeds  2000     10   21
2918      Newcastle        Everton  2000     10   21
2919      Tottenham          Derby  2000     10   21
2920       West Ham        Arsenal  2000     10   21
2921    Aston Villa     Sunderland  2000     10   22
2922    Southampton       Man City  2000     10   23
2923        Chelsea      Tottenham  2000     10   28

In [ ]:
match_data = {
    # -------------------- 19 August 2000 - Matchweek 1 --------------------
    ('Charlton', 'Man City'): {
        'Time': '15:00', 'Attendance': 20043
    },  # Source: FBref [6L20-L21]

    ('Leeds', 'Everton'): {
        'Time': '15:00', 'Attendance': 40010
    },  # Source: FBref [6L10-L11]

    ('Derby', 'Southampton'): {
        'Time': '15:00', 'Attendance': 27223
    },  # Source: FBref [6L17-L18]

    ('Chelsea', 'West Ham'): {
        'Time': '15:00', 'Attendance': 34914
    },  # Source: FBref [6L13-L14]

    ('Tottenham', 'Ipswich'): {
        'Time': '15:00', 'Attendance': 36148
    },  # Source: FBref [6L14-L15]

    ('Leicester', 'Aston Villa'): {
        'Time': '15:00', 'Attendance': 21455
    },  # Source: FBref [6L21-L22]

    ('Sunderland', 'Arsenal'): {
        'Time': '15:00', 'Attendance': 47121
    },  # Source: FBref [6L19-L20]

    ('Coventry', 'Middlesbrough'): {
        'Time': '15:00', 'Attendance': 20624
    },  # Source: FBref [6L16-L17]

    ('Liverpool', 'Bradford'): {
        'Time': '15:00', 'Attendance': 44183
    },  # Source: FBref [6L12-L13]

    # -------------------- 20 August 2000 - Matchweek 1 --------------------
    ('Man United', 'Newcastle'): {
        'Time': '16:00', 'Attendance': 67477
    },  # Source: FBref [6L23-L24]

    # -------------------- 21 August 2000 - Matchweek 2 --------------------
    ('Arsenal', 'Liverpool'): {
        'Time': '20:00', 'Attendance': 38014
    },  # Source: FBref [6L24-L25]

    # -------------------- 22 August 2000 - Matchweek 2 --------------------
    ('Middlesbrough', 'Tottenham'): {
        'Time': '20:00', 'Attendance': 31254
    },  # Source: FBref [6L28-L29]

    ('Bradford', 'Chelsea'): {
        'Time': '19:45', 'Attendance': 17872
    },  # Source: FBref [6L27-L28]

    ('Ipswich', 'Man United'): {
        'Time': '20:00', 'Attendance': 22007
    },  # Source: FBref [6L26-L27]

    # -------------------- 23 August 2000 - Matchweek 2 --------------------
    ('Southampton', 'Coventry'): {
        'Time': '19:45', 'Attendance': 14801
    },  # Source: FBref [6L30-L31]

    ('Man City', 'Sunderland'): {
        'Time': '20:00', 'Attendance': 34410
    },  # Source: FBref [6L32-L33]

    ('Everton', 'Charlton'): {
        'Time': '20:00', 'Attendance': 36300
    },  # Source: FBref [6L35-L36]

    ('Newcastle', 'Derby'): {
        'Time': '20:00', 'Attendance': 51327
    },  # Source: FBref [6L31-L32]

    ('West Ham', 'Leicester'): {
        'Time': '20:00', 'Attendance': 25195
    },  # Source: FBref [6L34-L35]

    # -------------------- 26 August 2000 - Matchweek 3 --------------------
    ('Everton', 'Derby'): {
        'Time': '15:00', 'Attendance': 34840
    },  # Source: FBref [7L48-L49]

    ('Ipswich', 'Sunderland'): {
        'Time': '15:00', 'Attendance': 21830
    },  # Source: FBref [7L37-L38]

    ('Man City', 'Coventry'): {
        'Time': '15:00', 'Attendance': 34140
    },  # Source: FBref [7L46-L47]

    ('Middlesbrough', 'Leeds'): {
        'Time': '15:00', 'Attendance': 31626
    },  # Source: FBref [7L44-L45]

    ('Newcastle', 'Tottenham'): {
        'Time': '15:00', 'Attendance': 51573
    },  # Source: FBref [7L40-L41]

    ('Southampton', 'Liverpool'): {
        'Time': '15:00', 'Attendance': 15202
    },  # Source: FBref [7L41-L42]

    ('West Ham', 'Man United'): {
        'Time': '15:00', 'Attendance': 25988
    },  # Source: FBref [7L47-L48]

    ('Bradford', 'Leicester'): {
        'Time': '15:00', 'Attendance': 16766
    },  # Source: FBref [7L38-L39]

    ('Arsenal', 'Charlton'): {
        'Time': '15:00', 'Attendance': 38025
    },  # Source: FBref [7L43-L44]

    # -------------------- 27 August 2000 - Matchweek 3 --------------------
    ('Aston Villa', 'Chelsea'): {
        'Time': '16:00', 'Attendance': 27057
    },  # Source: FBref [7L50-L51]

    # -------------------- 5 September 2000 - Matchweek 4 --------------------
    ('Leeds', 'Man City'): {
        'Time': '20:00', 'Attendance': 40055
    },  # Source: FBref [7L51-L52]

    ('Man United', 'Bradford'): {
        'Time': '20:00', 'Attendance': 66447
    },  # Source: FBref [7L55-L56]

    ('Sunderland', 'West Ham'): {
        'Time': '20:00', 'Attendance': 46605
    },  # Source: FBref [7L53-L54]

    ('Tottenham', 'Everton'): {
        'Time': '20:00', 'Attendance': 35316
    },  # Source: FBref [7L54-L55]

    # -------------------- 6 September 2000 - Matchweek 4 --------------------
    ('Liverpool', 'Aston Villa'): {
        'Time': '20:00', 'Attendance': 43360
    },  # Source: FBref [7L60-L61]

    ('Leicester', 'Ipswich'): {
        'Time': '19:45', 'Attendance': 19598
    },  # Source: FBref [7L58-L59]

    ('Coventry', 'Newcastle'): {
        'Time': '19:45', 'Attendance': 22109
    },  # Source: FBref [7L62-L63]

    ('Chelsea', 'Arsenal'): {
        'Time': '20:00', 'Attendance': 34923
    },  # Source: FBref [7L61-L62]

    ('Charlton', 'Southampton'): {
        'Time': '19:45', 'Attendance': 20043
    },  # Source: FBref [7L57-L58]

    ('Derby', 'Middlesbrough'): {
        'Time': '20:00', 'Attendance': 24290
    },  # Source: FBref [7L63-L64]

    # -------------------- 9 September 2000 - Matchweek 5 --------------------
    ('Newcastle', 'Chelsea'): {
        'Time': '15:00', 'Attendance': 51687
    },  # Source: FBref [8L73-L74]

    ('Middlesbrough', 'Everton'): {
        'Time': '15:00', 'Attendance': 30885
    },  # Source: FBref [8L72-L73]

    ('Bradford', 'Arsenal'): {
        'Time': '15:00', 'Attendance': 17160
    },  # Source: FBref [8L75-L76]

    ('Liverpool', 'Man City'): {
        'Time': '15:00', 'Attendance': 44692
    },  # Source: FBref [8L76-L77]

    ('Leicester', 'Southampton'): {
        'Time': '15:00', 'Attendance': 18366
    },  # Source: FBref [8L65-L66]

    ('Ipswich', 'Aston Villa'): {
        'Time': '15:00', 'Attendance': 20665
    },  # Source: FBref [8L66-L67]

    ('Coventry', 'Leeds'): {
        'Time': '15:00', 'Attendance': 20377
    },  # Source: FBref [8L69-L70]

    ('Man United', 'Sunderland'): {
        'Time': '15:00', 'Attendance': 67503
    },  # Source: FBref [8L70-L71]

    # -------------------- 10 September 2000 - Matchweek 5 --------------------
    ('Derby', 'Charlton'): {
        'Time': '16:00', 'Attendance': 22310
    },  # Source: FBref [8L77-L78]

    # -------------------- 11 September 2000 - Matchweek 5 --------------------
    ('Tottenham', 'West Ham'): {
        'Time': '20:00', 'Attendance': 33282
    },  # Source: FBref [8L78-L79]

    # -------------------- 16 September 2000 - Matchweek 6 --------------------
    ('Arsenal', 'Coventry'): {
        'Time': '15:00', 'Attendance': 37794
    },  # Source: FBref [8L86-L87]

    ('Aston Villa', 'Bradford'): {
        'Time': '15:00', 'Attendance': 27849
    },  # Source: FBref [8L81-L82]

    ('Charlton', 'Tottenham'): {
        'Time': '15:00', 'Attendance': 20043
    },  # Source: FBref [8L84-L85]

    ('Everton', 'Man United'): {
        'Time': '15:00', 'Attendance': 38541
    },  # Source: FBref [8L88-L89]

    ('Leeds', 'Ipswich'): {
        'Time': '15:00', 'Attendance': 35552
    },  # Source: FBref [8L87-L88]

    ('Southampton', 'Newcastle'): {
        'Time': '15:00', 'Attendance': 15221
    },  # Source: FBref [8L80-L81]

    ('Sunderland', 'Derby'): {
        'Time': '15:00', 'Attendance': 45343
    },  # Source: FBref [8L83-L84]

    # -------------------- 17 September 2000 - Matchweek 6 --------------------
    ('West Ham', 'Liverpool'): {
        'Time': '16:00', 'Attendance': 25998
    },  # Source: FBref [8L91-L92]

    ('Chelsea', 'Leicester'): {
        'Time': '14:00', 'Attendance': 33697
    },  # Source: FBref [8L93-L94]

    ('Man City', 'Middlesbrough'): {
        'Time': '16:00', 'Attendance': 32053
    },  # Source: FBref [8L90-L91]

    # -------------------- 23 September 2000 - Matchweek 7 --------------------
    ('Bradford', 'Southampton'): {
        'Time': '15:00', 'Attendance': 16163
    },  # Source: FBref [8L94-L95]

    ('Tottenham', 'Man City'): {
        'Time': '15:00', 'Attendance': 36069
    },  # Source: FBref [9L105-L106]

    ('Newcastle', 'Charlton'): {
        'Time': '15:00', 'Attendance': 50866
    },  # Source: FBref [8L95-L96]

    ('Coventry', 'West Ham'): {
        'Time': '15:00', 'Attendance': 21020
    },  # Source: FBref [8L100-L101]

    ('Man United', 'Chelsea'): {
        'Time': '15:00', 'Attendance': 67568
    },  # Source: FBref [9L103-L104]

    ('Liverpool', 'Sunderland'): {
        'Time': '15:00', 'Attendance': 44713
    },  # Source: FBref [9L104-L105]

    ('Derby', 'Leeds'): {
        'Time': '15:00', 'Attendance': 26248
    },  # Source: FBref [8L98-L99]

    ('Ipswich', 'Arsenal'): {
        'Time': '15:00', 'Attendance': 22030
    },  # Source: FBref [8L97-L98]

    ('Middlesbrough', 'Aston Villa'): {
        'Time': '15:00', 'Attendance': 27556
    },  # Source: FBref [9L101-L102]

    # -------------------- 24 September 2000 - Matchweek 7 --------------------
    ('Leicester', 'Everton'): {
        'Time': '16:00', 'Attendance': 18084
    },  # Source: FBref [9L107-L108]

    # -------------------- 30 September 2000 - Matchweek 8 --------------------
    ('West Ham', 'Bradford'): {
        'Time': '15:00', 'Attendance': 25407
    },  # Source: FBref [9L109-L110]

    ('Southampton', 'Middlesbrough'): {
        'Time': '15:00', 'Attendance': 14903
    },  # Source: FBref [9L114-L115]

    ('Leeds', 'Tottenham'): {
        'Time': '15:00', 'Attendance': 37562
    },  # Source: FBref [9L112-L113]

    ('Everton', 'Ipswich'): {
        'Time': '15:00', 'Attendance': 32597
    },  # Source: FBref [9L111-L112]

    ('Charlton', 'Coventry'): {
        'Time': '15:00', 'Attendance': 20043
    },  # Source: FBref [9L108-L109]

    ('Aston Villa', 'Derby'): {
        'Time': '15:00', 'Attendance': 26534
    },  # Source: FBref [9L116-L117]

    ('Man City', 'Newcastle'): {
        'Time': '15:00', 'Attendance': 34497
    },  # Source: FBref [9L115-L116]

    # -------------------- 1 October 2000 - Matchweek 8 --------------------
    ('Arsenal', 'Man United'): {
        'Time': '16:00', 'Attendance': 38146
    },  # Source: FBref [9L118-L119]

    ('Chelsea', 'Liverpool'): {
        'Time': '14:00', 'Attendance': 34966
    },  # Source: FBref [9L119-L120]

    ('Sunderland', 'Leicester'): {
        'Time': '16:00', 'Attendance': 45338
    },  # Source: FBref [9L120-L121]

    # -------------------- 14 October 2000 - Matchweek 9 --------------------
    ('Sunderland', 'Chelsea'): {
        'Time': '15:00', 'Attendance': 45078
    },  # Source: FBref [9L129-L130]

    ('Man City', 'Bradford'): {
        'Time': '15:00', 'Attendance': 34229
    },  # Source: FBref [9L122-L123]

    ('Ipswich', 'West Ham'): {
        'Time': '15:00', 'Attendance': None
    },  # Data not found in available sources

    ('Leeds', 'Charlton'): {
        'Time': '15:00', 'Attendance': 38837
    },  # Source: FBref [9L130-L131]

    ('Everton', 'Southampton'): {
        'Time': '15:00', 'Attendance': 29491
    },  # Source: FBref [9L125-L126]

    ('Coventry', 'Tottenham'): {
        'Time': '15:00', 'Attendance': 21435
    },  # Source: FBref [12L42-L43]

    ('Leicester', 'Man United'): {
        'Time': '15:00', 'Attendance': 22132
    },  # Source: FBref [9L123-L124]

    ('Arsenal', 'Aston Villa'): {
        'Time': '15:00', 'Attendance': 38042
    },  # Source: FBref [9L127-L128]

    # -------------------- 15 October 2000 - Matchweek 9 --------------------
    ('Derby', 'Liverpool'): {
        'Time': '16:00', 'Attendance': None
    },  # Data not found in available sources

    # -------------------- 16 October 2000 - Matchweek 9 --------------------
    ('Middlesbrough', 'Newcastle'): {
        'Time': '20:00', 'Attendance': None
    },  # Data not found in available sources

    # -------------------- 21 October 2000 - Matchweek 10 --------------------
    ('Bradford', 'Ipswich'): {
        'Time': '15:00', 'Attendance': None
    },  # Data not found in available sources

    ('Charlton', 'Middlesbrough'): {
        'Time': '15:00', 'Attendance': 20043
    },  # Source: 11v11 [12L8]

    ('Chelsea', 'Coventry'): {
        'Time': '15:00', 'Attendance': 34646
    },  # Source: stamford-bridge.com [13L7]

    ('Liverpool', 'Leicester'): {
        'Time': '15:00', 'Attendance': 44395
    },  # Source: LFChistory.net [14L7]

    ('Man United', 'Leeds'): {
        'Time': '12:30', 'Attendance': 67525
    },  # Source: 11v11 [15L7]

    ('Newcastle', 'Everton'): {
        'Time': '15:00', 'Attendance': 51625
    },  # Source: football-lineups.com [16L6]

    ('Tottenham', 'Derby'): {
        'Time': '15:00', 'Attendance': 34483
    },  # Source: sport.de [17L8]

    ('West Ham', 'Arsenal'): {
        'Time': '15:00', 'Attendance': 26034
    },  # Source: 11v11 [18L7]

    # -------------------- 22 October 2000 - Matchweek 10 --------------------
    ('Aston Villa', 'Sunderland'): {
        'Time': '17:00', 'Attendance': 27215
    },  # Source: sport.de [19L15-L16]

    # -------------------- 23 October 2000 - Matchweek 10 --------------------
    ('Southampton', 'Man City'): {
        'Time': '21:00', 'Attendance': 15056
    },  # Source: sport.de [20L7-L8]

    # -------------------- 28 October 2000 - Matchweek 11 --------------------
    ('Chelsea', 'Tottenham'): {
        'Time': '15:00', 'Attendance': 34966
    },  # Source: stamford-bridge.com [21L7]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0001',
    data=match_data,
    value_col=['Time', 'Attendance'],
    inplace=True
)

In [25]:
null_rows(df, "0001","Time")

           HomeTeam       AwayTeam  Year  Month  Day
2931       Bradford          Leeds  2000     10   29
2975       Bradford       Coventry  2000     12    2
2977      Leicester          Leeds  2000     12    2
2980       West Ham  Middlesbrough  2000     12    2
2982     Sunderland        Everton  2000     12    4
2987       Charlton     Man United  2000     12    9
2991       Coventry      Leicester  2000     12   10
2994        Ipswich    Southampton  2000     12   16
2998      Newcastle       Bradford  2000     12   16
3001     Man United      Liverpool  2000     12   17
3003       Coventry    Southampton  2000     12   22
3004     Man United        Ipswich  2000     12   23
3007      Liverpool        Arsenal  2000     12   23
3008          Leeds    Aston Villa  2000     12   23
3011       Charlton        Everton  2000     12   23
3012      Leicester       West Ham  2000     12   23
3013        Arsenal      Leicester  2000     12   26
3014    Aston Villa     Man United  2000     12   26
3015       Bradford     Sunderland  2000     12   26
3016        Everton       Coventry  2000     12   26
3017        Ipswich        Chelsea  2000     12   26
3018       Man City          Derby  2000     12   26
3019  Middlesbrough      Liverpool  2000     12   26
3020      Newcastle          Leeds  2000     12   26
3021       West Ham       Charlton  2000     12   26
3022    Southampton      Tottenham  2000     12   27
3023  Middlesbrough       Coventry  2000     12   30
3024      Newcastle     Man United  2000     12   30
3025    Southampton          Derby  2000     12   30
3026        Ipswich      Tottenham  2000     12   30
3027        Arsenal     Sunderland  2000     12   30
3028       Man City       Charlton  2000     12   30
3029     Man United       West Ham  2001      1    1
3030     Sunderland        Ipswich  2001      1    1
3031      Liverpool    Southampton  2001      1    1
3032          Derby        Everton  2001      1    1
3033          Leeds  Middlesbrough  2001      1    1
3034       Charlton        Arsenal  2001      1    1
3035        Chelsea    Aston Villa  2001      1    1
3036       Coventry       Man City  2001      1    1
3037      Leicester       Bradford  2001      1    1
3038      Tottenham      Newcastle  2001      1    2
3039       West Ham     Sunderland  2001      1   13
3040    Southampton       Charlton  2001      1   13
3041      Newcastle       Coventry  2001      1   13
3042  Middlesbrough          Derby  2001      1   13
3043        Everton      Tottenham  2001      1   13
3044       Bradford     Man United  2001      1   13
3045    Aston Villa      Liverpool  2001      1   13
3046        Arsenal        Chelsea  2001      1   13
3047       Man City          Leeds  2001      1   13
3048        Ipswich      Leicester  2001      1   14
3049     Man United    Aston Villa  2001      1   20
3050      Liverpool  Middlesbrough  2001      1   20
3051      Tottenham    Southampton  2001      1   20
3052          Leeds      Newcastle  2001      1   20
3053      Leicester        Arsenal  2001      1   20
3054       Coventry        Everton  2001      1   20
3055          Derby       Man City  2001      1   20
3056        Chelsea        Ipswich  2001      1   20
3057     Sunderland       Bradford  2001      1   21
3058       Charlton       West Ham  2001      1   22
3059    Aston Villa          Leeds  2001      1   24
3060        Arsenal       Bradford  2001      1   30
3061       Charlton          Derby  2001      1   30
3062       West Ham      Tottenham  2001      1   31
3063     Sunderland     Man United  2001      1   31
3064       Man City      Liverpool  2001      1   31
3065          Leeds       Coventry  2001      1   31
3066        Everton  Middlesbrough  2001      1   31
3067        Chelsea      Newcastle  2001      1   31
3068    Southampton      Leicester  2001      1   31
3069       Coventry        Arsenal  2001      2    3
3070          Derby     Sunderland  2001      2    3
3071        Ipswich          Leeds  2001      2    3
3072      Leicester        Chelsea  2001      2    3

In [ ]:
match_data = {
    # -------------------- 29 October 2000 - Matchweek 11 --------------------
    ('Bradford', 'Leeds'): {
        'Time': '17:00', 'Attendance': 17364
    },  # Source: Transfermarkt [0L24-L25], leeds-fans.org.uk [0L21]

    # -------------------- 2 December 2000 - Matchweek 16 --------------------
    ('Bradford', 'Coventry'): {
        'Time': '16:00', 'Attendance': 15523
    },  # Source: sport.de [1L13-L15], FBref [1L19]

    ('Leicester', 'Leeds'): {
        'Time': '15:00', 'Attendance': 21486
    },  # Source: football-lineups.com [2L7-L8], FBref [2L10-L11]

    ('West Ham', 'Middlesbrough'): {
        'Time': '16:00', 'Attendance': 25459
    },  # Source: globalsportsarchive.com [3L7], sport.de [3L13-L14]

    # -------------------- 4 December 2000 - Matchweek 16 --------------------
    ('Sunderland', 'Everton'): {
        'Time': None, 'Attendance': 46372
    },  # Source: thestatcat.co.uk [4L10], FBref [4L6]

    # -------------------- 9 December 2000 - Matchweek 17 --------------------
    ('Charlton', 'Man United'): {
        'Time': '16:00', 'Attendance': 20043
    },  # Source: sport.de [5L7-L9], weltfussball.de [5L22]

    # -------------------- 10 December 2000 - Matchweek 17 --------------------
    ('Coventry', 'Leicester'): {
        'Time': '17:00', 'Attendance': 17283
    },  # Source: sport.de [6L11-L13], globalsportsarchive.com [6L7-L8]

    # -------------------- 16 December 2000 - Matchweek 18 --------------------
    ('Ipswich', 'Southampton'): {
        'Time': None, 'Attendance': 22228
    },  # Source: Pride of Anglia [7L11], globalsportsarchive.com [7L7]

    ('Newcastle', 'Bradford'): {
        'Time': '16:00', 'Attendance': 50470
    },  # Source: sport.de [8L11-L13], nufc.com [8L20]

    # -------------------- 17 December 2000 - Matchweek 18 --------------------
    ('Man United', 'Liverpool'): {
        'Time': '12:00', 'Attendance': 67533
    },  # Source: LFChistory.net [9L10-L11], globalsportsarchive.com [9L7]

    # -------------------- 22 December 2000 - Matchweek 19 --------------------
    ('Coventry', 'Southampton'): {
        'Time': '20:45', 'Attendance': 18090
    },  # Source: sport.de [10L10-L12], 11v11.com [10L7]

    # -------------------- 23 December 2000 - Matchweek 19 --------------------
    ('Man United', 'Ipswich'): {
        'Time': '16:00', 'Attendance': 67597
    },  # Source: sport.de [11L25-L27], globalsportsarchive.com [11L7-L8]

    ('Liverpool', 'Arsenal'): {
        'Time': '12:30', 'Attendance': 44144
    },  # Source: sport.de [12L16-L18], LFChistory.net [12L12-L13]

    ('Leeds', 'Aston Villa'): {
        'Time': '16:00', 'Attendance': 39714
    },  # Source: sport.de [13L25-L27], football-lineups.com [13L6]

    ('Charlton', 'Everton'): {
        'Time': None, 'Attendance': 20043
    },  # Source: 11v11.com [14L7], FBref [14L11-L12]

    ('Leicester', 'West Ham'): {
        'Time': '15:00', 'Attendance': 21524
    },  # Source: 11v11.com [15L8], globalsportsarchive.com [15L12-L13]

    # -------------------- 26 December 2000 - Matchweek 20 --------------------
    ('Arsenal', 'Leicester'): {
        'Time': '13:00', 'Attendance': 38007
    },  # Source: sport.de [16L10-L12], football-lineups.com [16L6]

    ('Aston Villa', 'Man United'): {
        'Time': '14:00', 'Attendance': 40889
    },  # Source: sport.de [17L6-L8], AVDB [17L15]

    ('Bradford', 'Sunderland'): {
        'Time': '16:00', 'Attendance': 20370
    },  # Source: sport.de [18L12-L14], Telegraph [18L8-L9]

    ('Everton', 'Coventry'): {
        'Time': '16:00', 'Attendance': 35704
    },  # Source: sport.de [19L16-L18], Transfermarkt [19L7]

    ('Ipswich', 'Chelsea'): {
        'Time': '16:00', 'Attendance': 22237
    },  # Source: sport.de [20L14-L16], 11v11.com [20L7]

    ('Man City', 'Derby'): {
        'Time': '16:00', 'Attendance': 34321
    },  # Source: sport.de [21L10-L12], 11v11.com [21L7]

    ('Middlesbrough', 'Liverpool'): {
        'Time': '15:00', 'Attendance': 34696
    },  # Source: LFChistory.net [22L9-L11], Wikipedia [22L6-L7]

    ('Newcastle', 'Leeds'): {
        'Time': '16:00', 'Attendance': 52118
    },  # Source: sport.de [23L6-L8], globalsportsarchive.com [23L13]

    ('West Ham', 'Charlton'): {
        'Time': '13:00', 'Attendance': 26046
    },  # Source: sport.de [24L11-L13], 11v11.com [24L8]

    # -------------------- 27 December 2000 - Matchweek 20 --------------------
    ('Southampton', 'Tottenham'): {
        'Time': '21:00', 'Attendance': 15237
    },  # Source: sport.de [25L13-L15], globalsportsarchive.com [25L8]

    # -------------------- 30 December 2000 - Matchweek 21 --------------------
    ('Middlesbrough', 'Coventry'): {
        'Time': '16:00', 'Attendance': 30499
    },  # Source: sport.de [26L13-L15], globalsportsarchive.com [26L8]

    ('Newcastle', 'Man United'): {
        'Time': '16:00', 'Attendance': 52134
    },  # Source: sport.de [27L7-L9], FBref [27L13]

    ('Southampton', 'Derby'): {
        'Time': '16:00', 'Attendance': 15075
    },  # Source: sport.de [28L6-L7], globalsportsarchive.com [28L11]

    ('Ipswich', 'Tottenham'): {
        'Time': '13:00', 'Attendance': 22234
    },  # Source: sport.de [29L7-L9], thfcdb.com [29L24]

    ('Arsenal', 'Sunderland'): {
        'Time': '16:00', 'Attendance': 38026
    },  # Source: sport.de [30L16-L18], 11v11.com [30L7]

    ('Man City', 'Charlton'): {
        'Time': None, 'Attendance': 33280
    },  # Source: citytilidie.com [31L12], FBref [31L7-L8]

    # -------------------- 1 January 2001 - Matchweek 22 --------------------
    ('Man United', 'West Ham'): {
        'Time': '21:00', 'Attendance': 67603
    },  # Source: sport.de [32L24-L26], 11v11.com [32L8]

    ('Sunderland', 'Ipswich'): {
        'Time': '15:00', 'Attendance': 46053
    },  # Source: football-lineups.com [33L6-L7], 11v11.com [33L11]

    ('Liverpool', 'Southampton'): {
        'Time': '16:00', 'Attendance': 38474
    },  # Source: sport.de [34L19-L21], LFChistory.net [34L10]

    ('Derby', 'Everton'): {
        'Time': '16:00', 'Attendance': 27358
    },  # Source: sport.de [35L10-L12], 11v11.com [35L7]

    ('Leeds', 'Middlesbrough'): {
        'Time': '15:00', 'Attendance': 39251
    },  # Source: football-lineups.com [36L7-L8], leeds-fans.org.uk [36L37]

    ('Charlton', 'Arsenal'): {
        'Time': '16:00', 'Attendance': 20043
    },  # Source: sport.de [37L10-L12], 11v11.com [37L7]

    ('Chelsea', 'Aston Villa'): {
        'Time': '15:00', 'Attendance': 33159
    },  # Source: stamford-bridge.com [38L6-L7], 11v11.com [38L10-L11]

    ('Coventry', 'Man City'): {
        'Time': '16:00', 'Attendance': 21999
    },  # Source: sport.de [39L6-L8], citytilidie.com [39L11]

    ('Leicester', 'Bradford'): {
        'Time': '16:00', 'Attendance': 19278
    },  # Source: sport.de [40L6-L8], FBref [40L11-L12]

    # -------------------- 2 January 2001 - Matchweek 22 --------------------
    ('Tottenham', 'Newcastle'): {
        'Time': '20:45', 'Attendance': 34324
    },  # Source: sport.de [41L17-L19], 11v11.com [41L13]

    # -------------------- 13 January 2001 - Matchweek 23 --------------------
    ('West Ham', 'Sunderland'): {
        'Time': None, 'Attendance': 26014
    },  # Source: globalsportsarchive.com [42L8], FBref [42L19]

    ('Southampton', 'Charlton'): {
        'Time': '16:00', 'Attendance': 15220
    },  # Source: sport.de [43L6-L8], Transfermarkt [43L22]

    ('Newcastle', 'Coventry'): {
        'Time': '16:00', 'Attendance': 50159
    },  # Source: sport.de [44L6-L8], 11v11.com [44L12]

    ('Middlesbrough', 'Derby'): {
        'Time': '16:00', 'Attendance': 29041
    },  # Source: sport.de [45L14-L16], football-lineups.com [45L6-L7]

    ('Everton', 'Tottenham'): {
        'Time': '16:00', 'Attendance': 32290
    },  # Source: sport.de [46L10-L11], 11v11.com [46L7]

    ('Bradford', 'Man United'): {
        'Time': '16:00', 'Attendance': 20551
    },  # Source: sport.de [47L12-L14], footymags.com [47L9]

    ('Aston Villa', 'Liverpool'): {
        'Time': '16:00', 'Attendance': 41366
    },  # Source: sport.de [48L18-L20], Wikipedia [48L6]

    ('Arsenal', 'Chelsea'): {
        'Time': '16:00', 'Attendance': 38071
    },  # Source: sport.de [49L13-L15], stamford-bridge.com [49L6]

    ('Man City', 'Leeds'): {
        'Time': '15:00', 'Attendance': 34288
    },  # Source: football-lineups.com [50L6], Transfermarkt [50L11]

    # -------------------- 14 January 2001 - Matchweek 23 --------------------
    ('Ipswich', 'Leicester'): {
        'Time': '17:00', 'Attendance': 22002
    },  # Source: sport.de [51L11-L13], globalsportsarchive.com [51L7]

    # -------------------- 20 January 2001 - Matchweek 24 --------------------
    ('Man United', 'Aston Villa'): {
        'Time': '16:00', 'Attendance': 67533
    },  # Source: sport.de [52L10-L12], 11v11.com [52L7]

    ('Liverpool', 'Middlesbrough'): {
        'Time': None, 'Attendance': 43042
    },  # Source: 11v11.com [53L7], globalsportsarchive.com [53L12]

    ('Tottenham', 'Southampton'): {
        'Time': '16:00', 'Attendance': 36095
    },  # Source: sport.de [54L10-L12], thfcdb.com [54L6]

    ('Leeds', 'Newcastle'): {
        'Time': '15:00', 'Attendance': 40005
    },  # Source: football-lineups.com [55L6], globalsportsarchive.com [55L12]

    ('Leicester', 'Arsenal'): {
        'Time': None, 'Attendance': None
    },

    ('Coventry', 'Everton'): {
        'Time': None, 'Attendance': None
    },

    ('Derby', 'Man City'): {
        'Time': None, 'Attendance': None
    },

    ('Chelsea', 'Ipswich'): {
        'Time': None, 'Attendance': None
    },

    # -------------------- 21 January 2001 - Matchweek 24 --------------------
    ('Sunderland', 'Bradford'): {
        'Time': None, 'Attendance': None
    },

    # -------------------- 22 January 2001 - Matchweek 24 --------------------
    ('Charlton', 'West Ham'): {
        'Time': None, 'Attendance': None
    },

    # -------------------- 24 January 2001 - Matchweek 22 --------------------
    ('Aston Villa', 'Leeds'): {
        'Time': None, 'Attendance': None
    },

    # -------------------- 30 January 2001 - Matchweek 25 --------------------
    ('Arsenal', 'Bradford'): {
        'Time': None, 'Attendance': None
    },

    ('Charlton', 'Derby'): {
        'Time': None, 'Attendance': None
    },

    # -------------------- 31 January 2001 - Matchweek 25 --------------------
    ('West Ham', 'Tottenham'): {
        'Time': None, 'Attendance': None
    },

    ('Sunderland', 'Man United'): {
        'Time': None, 'Attendance': None
    },

    ('Man City', 'Liverpool'): {
        'Time': None, 'Attendance': None
    },

    ('Leeds', 'Coventry'): {
        'Time': None, 'Attendance': None
    },

    ('Everton', 'Middlesbrough'): {
        'Time': None, 'Attendance': None
    },

    ('Chelsea', 'Newcastle'): {
        'Time': None, 'Attendance': None
    },

    ('Southampton', 'Leicester'): {
        'Time': None, 'Attendance': None
    },

    # -------------------- 3 February 2001 - Matchweek 26 --------------------
    ('Coventry', 'Arsenal'): {
        'Time': None, 'Attendance': None
    },

    ('Derby', 'Sunderland'): {
        'Time': None, 'Attendance': None
    },

    ('Ipswich', 'Leeds'): {
        'Time': None, 'Attendance': None
    },

    ('Leicester', 'Chelsea'): {
        'Time': None, 'Attendance': None
    },
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0001',
    data=match_data,
    value_col=['Time', 'Attendance'],
    inplace=True
)

In [29]:
null_rows(df, "0001","Time")

         HomeTeam       AwayTeam  Year  Month  Day
2982   Sunderland        Everton  2000     12    4
2994      Ipswich    Southampton  2000     12   16
3011     Charlton        Everton  2000     12   23
3028     Man City       Charlton  2000     12   30
3039     West Ham     Sunderland  2001      1   13
3050    Liverpool  Middlesbrough  2001      1   20
3053    Leicester        Arsenal  2001      1   20
3054     Coventry        Everton  2001      1   20
3055        Derby       Man City  2001      1   20
3056      Chelsea        Ipswich  2001      1   20
3057   Sunderland       Bradford  2001      1   21
3058     Charlton       West Ham  2001      1   22
3059  Aston Villa          Leeds  2001      1   24
3060      Arsenal       Bradford  2001      1   30
3061     Charlton          Derby  2001      1   30
3062     West Ham      Tottenham  2001      1   31
3063   Sunderland     Man United  2001      1   31
3064     Man City      Liverpool  2001      1   31
3065        Leeds       Coventry  2001      1   31
3066      Everton  Middlesbrough  2001      1   31
3067      Chelsea      Newcastle  2001      1   31
3068  Southampton      Leicester  2001      1   31
3069     Coventry        Arsenal  2001      2    3
3070        Derby     Sunderland  2001      2    3
3071      Ipswich          Leeds  2001      2    3
3072    Leicester        Chelsea  2001      2    3

In [ ]:
match_data = {
    # -------------------- 4 December 2000 - Matchweek 16 --------------------
    ('Sunderland', 'Everton'): {
        'Time': None, 'Attendance': 46372
    },  # Source: FBref [0L6], thestatcat [0L10]

    # -------------------- 16 December 2000 - Matchweek 18 --------------------
    ('Ipswich', 'Southampton'): {
        'Time': None, 'Attendance': 22228
    },  # Source: Global Sports Archive [1L7], Pride of Anglia [1L11]

    # -------------------- 23 December 2000 - Matchweek 19 --------------------
    ('Charlton', 'Everton'): {
        'Time': None, 'Attendance': 20043
    },  # Source: 11v11 [2L7], FBref [2L11-L12]

    # -------------------- 30 December 2000 - Matchweek 21 --------------------
    ('Man City', 'Charlton'): {
        'Time': None, 'Attendance': 33280
    },  # Source: FBref [3L6], citytilidie [3L11]

    # -------------------- 13 January 2001 - Matchweek 23 --------------------
    ('West Ham', 'Sunderland'): {
        'Time': None, 'Attendance': 26014
    },  # Source: Global Sports Archive [4L7], FBref [4L12]

    # -------------------- 20 January 2001 - Matchweek 24 --------------------
    ('Liverpool', 'Middlesbrough'): {
        'Time': '15:00', 'Attendance': 43042
    },  # Source: 11v11 [5L7], Global Sports Archive [5L12]

    ('Leicester', 'Arsenal'): {
        'Time': '16:00', 'Attendance': 21872
    },  # Source: FBref [6L7], Transfermarkt [6L13-L14]

    ('Coventry', 'Everton'): {
        'Time': '16:00', 'Attendance': 19174
    },  # Source: sport.de [7L11-L12], Transfermarkt [7L7]

    ('Derby', 'Man City'): {
        'Time': '16:00', 'Attendance': 31174
    },  # Source: sport.de [8L7-L8], Transfermarkt [8L12]

    ('Chelsea', 'Ipswich'): {
        'Time': '15:00', 'Attendance': 34948
    },  # Source: stamford-bridge [9L7], sport.de [9L12]

    # -------------------- 21 January 2001 - Matchweek 24 --------------------
    ('Sunderland', 'Bradford'): {
        'Time': '17:00', 'Attendance': 47812
    },  # Source: 11v11 [10L7], sport.de [10L12]

    # -------------------- 22 January 2001 - Matchweek 24 --------------------
    ('Charlton', 'West Ham'): {
        'Time': '21:00', 'Attendance': 20043
    },  # Source: 11v11 [11L7], sport.de [11L12]

    # -------------------- 24 January 2001 - Matchweek 2 --------------------
    ('Aston Villa', 'Leeds'): {
        'Time': '19:45', 'Attendance': 29335
    },  # Source: football-lineups [12L6], Transfermarkt [12L14-L15]

    # -------------------- 30 January 2001 - Matchweek 25 --------------------
    ('Arsenal', 'Bradford'): {
        'Time': '20:45', 'Attendance': 37318
    },  # Source: sport.de [13L7-L8], Global Sports Archive [13L12]

    ('Charlton', 'Derby'): {
        'Time': '21:00', 'Attendance': 20043
    },  # Source: 11v11 [14L7], sport.de [14L15-L16]

    # -------------------- 31 January 2001 - Matchweek 25 --------------------
    ('West Ham', 'Tottenham'): {
        'Time': None, 'Attendance': 26048
    },  # Source: Global Sports Archive [15L7], Wikipedia [15L12-L13]

    ('Sunderland', 'Man United'): {
        'Time': '20:45', 'Attendance': 48260
    },  # Source: 11v11 [16L7], sport.de [16L13]

    ('Man City', 'Liverpool'): {
        'Time': '20:45', 'Attendance': 34629
    },  # Source: sport.de [17L7-L8], Transfermarkt [17L12]

    ('Leeds', 'Coventry'): {
        'Time': '20:45', 'Attendance': 36555
    },  # Source: sport.de [18L6-L7], Global Sports Archive [18L11]

    ('Everton', 'Middlesbrough'): {
        'Time': '20:00', 'Attendance': 34244
    },  # Source: Global Sports Archive [19L7-L8], evertonresults [19L38]

    ('Chelsea', 'Newcastle'): {
        'Time': '19:45', 'Attendance': 35108
    },  # Source: stamford-bridge [20L7], sport.de [20L12]

    ('Southampton', 'Leicester'): {
        'Time': '20:45', 'Attendance': 14909
    },  # Source: sport.de [21L11-L12], foxestalk [21L7]

    # -------------------- 3 February 2001 - Matchweek 26 --------------------
    ('Coventry', 'Arsenal'): {
        'Time': '15:00', 'Attendance': 22035
    },  # Source: FBref [22L6], Global Sports Archive [22L10]

    ('Derby', 'Sunderland'): {
        'Time': '16:00', 'Attendance': 29129
    },  # Source: sport.de [23L7-L8], Transfermarkt [23L17-L18]

    ('Ipswich', 'Leeds'): {
        'Time': '15:00', 'Attendance': 22015
    },  # Source: Guardian [24L6], 11v11 [24L11]

    ('Leicester', 'Chelsea'): {
        'Time': '15:00', 'Attendance': 21502
    },  # Source: stamford-bridge [25L7], 11v11 [25L11]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0001',
    data=match_data,
    value_col=['Time', 'Attendance'],
    inplace=True
)

In [32]:
null_rows(df, "0001","Attendance")

           HomeTeam    AwayTeam  Year  Month  Day
2905        Ipswich    West Ham  2000     10   14
2911          Derby   Liverpool  2000     10   15
2912  Middlesbrough   Newcastle  2000     10   16
2913       Bradford     Ipswich  2000     10   21
2976        Ipswich       Derby  2000     12    2
2979     Man United   Tottenham  2000     12    2
2981        Chelsea    Man City  2000     12    3
2988       Bradford   Tottenham  2000     12    9
2992      Liverpool     Ipswich  2000     12   10
2996      Leicester    Charlton  2000     12   16
2999          Derby    Coventry  2000     12   16
3002      Tottenham     Arsenal  2000     12   18
3006     Sunderland    Man City  2000     12   23
3101          Leeds  Man United  2001      3    3

In [ ]:
match_data = {
    # -------------------- 14 October 2000 - Matchweek 9 --------------------
    ('Ipswich', 'West Ham'): {
        'Time': '15:00', 'Attendance': 22243
    },  # Source: 11v11 [0L7], Global Sports Archive [0L12], Pride of Anglia [0L16]

    # -------------------- 15 October 2000 - Matchweek 9 --------------------
    ('Derby', 'Liverpool'): {
        'Time': '16:00', 'Attendance': 30532
    },  # Source: 11v11 [1L4-L7], LFChistory [1L9-L11]

    # -------------------- 16 October 2000 - Matchweek 9 --------------------
    ('Middlesbrough', 'Newcastle'): {
        'Time': '21:00', 'Attendance': 31436
    },  # Source: Global Sports Archive [2L7-L8], sport.de [2L14-L16]

    # -------------------- 21 October 2000 - Matchweek 10 --------------------
    ('Bradford', 'Ipswich'): {
        'Time': '15:00', 'Attendance': 17045
    },  # Source: Global Sports Archive [3L7-L8], Pride of Anglia [3L11-L12]

    # -------------------- 2 December 2000 - Matchweek 16 --------------------
    ('Ipswich', 'Derby'): {
        'Time': '15:00', 'Attendance': 22003
    },  # Source: football-lineups.com [4L6-L8], Pride of Anglia [4L11-L12]

    ('Man United', 'Tottenham'): {
        'Time': '16:00', 'Attendance': 67583
    },  # Source: sport.de [5L6-L8], Transfermarkt [5L11-L12]

    # -------------------- 3 December 2000 - Matchweek 16 --------------------
    ('Chelsea', 'Man City'): {
        'Time': '16:00', 'Attendance': 34971
    },  # Source: stamford-bridge.com [12L6-L7], 11v11 [12L11]

    # -------------------- 9 December 2000 - Matchweek 17 --------------------
    ('Bradford', 'Tottenham'): {
        'Time': '16:00', 'Attendance': 17225
    },  # Source: sport.de [13L6-L8], FBref [13L11-L12]

    # -------------------- 10 December 2000 - Matchweek 17 --------------------
    ('Liverpool', 'Ipswich'): {
        'Time': '16:00', 'Attendance': 43509
    },  # Source: sport.de [14L6-L8], LFChistory [14L10-L11]

    # -------------------- 16 December 2000 - Matchweek 18 --------------------
    ('Leicester', 'Charlton'): {
        'Time': '16:00', 'Attendance': 19371
    },  # Source: sport.de [15L11-L13], Foxestalk [15L8]

    ('Derby', 'Coventry'): {
        'Time': '16:00', 'Attendance': 27869
    },  # Source: sport.de [16L6-L8], FBref [16L11-L12]

    # -------------------- 18 December 2000 - Matchweek 18 --------------------
    ('Tottenham', 'Arsenal'): {
        'Time': '21:00', 'Attendance': 36062
    },  # Source: sport.de [17L6-L8], FBref [17L11-L12]

    # -------------------- 23 December 2000 - Matchweek 19 --------------------
    ('Sunderland', 'Man City'): {
        'Time': '16:00', 'Attendance': 47475
    },  # Source: sport.de [18L6-L8], StatCity [18L11-L12]

    # -------------------- 3 March 2001 - Matchweek 29 --------------------
    ('Leeds', 'Man United'): {
        'Time': '16:00', 'Attendance': 40055
    },  # Source: The Guardian [19L6], footymags [19L11]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0001',
    data=match_data,
    value_col=['Time', 'Attendance'],
    inplace=True
)

In [35]:
null_rows(df, "0001","Time")

        HomeTeam     AwayTeam  Year  Month  Day
2982  Sunderland      Everton  2000     12    4
2994     Ipswich  Southampton  2000     12   16
3011    Charlton      Everton  2000     12   23
3028    Man City     Charlton  2000     12   30
3039    West Ham   Sunderland  2001      1   13
3062    West Ham    Tottenham  2001      1   31

In [ ]:
match_data = {
    # -------------------- 4 December 2000 - Matchweek 16 --------------------
    ('Sunderland', 'Everton'): {
        'Time': '20:00', 'Attendance': 46372
    },  # Source: thestatcat [7L2-L3], FBref [0L15-L16], TheFreeLibrary [19L23]

    # -------------------- 16 December 2000 - Matchweek 18 --------------------
    ('Ipswich', 'Southampton'): {
        'Time': None, 'Attendance': 22228
    },  # Source: Global Sports Archive [8L3], Pride of Anglia [1L11]

    # -------------------- 23 December 2000 - Matchweek 19 --------------------
    ('Charlton', 'Everton'): {
        'Time': None, 'Attendance': 20043
    },  # Source: 11v11 [9L5], FBref [2L8]

    # -------------------- 30 December 2000 - Matchweek 21 --------------------
    ('Man City', 'Charlton'): {
        'Time': '15:00', 'Attendance': 33280
    },  # Source: Sports Mole [21L3], citytilidie [10L3]

    # -------------------- 13 January 2001 - Matchweek 23 --------------------
    ('West Ham', 'Sunderland'): {
        'Time': None, 'Attendance': 26014
    },  # Source: Global Sports Archive [11L12], thestatcat [4L31-L32]

    # -------------------- 31 January 2001 - Matchweek 25 --------------------
    ('West Ham', 'Tottenham'): {
        'Time': '19:45', 'Attendance': 26048
    },  # Source: THFCDB [20L5-L6], Global Sports Archive [12L7]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0001',
    data=match_data,
    value_col=['Time', 'Attendance'],
    inplace=True
)

In [38]:
null_rows(df, "0001","Time")

      HomeTeam     AwayTeam  Year  Month  Day
2994   Ipswich  Southampton  2000     12   16
3011  Charlton      Everton  2000     12   23
3039  West Ham   Sunderland  2001      1   13

In [ ]:
match_data = {
    # -------------------- 16 December 2000 - Matchweek 18 --------------------
    ('Ipswich', 'Southampton'): {
        'Time': '15:00', 'Attendance': 22228
    },  # Source: Global Sports Archive [0L6-L8], FBref [0L24-L26], Pride of Anglia [1L10-L12]

    # -------------------- 23 December 2000 - Matchweek 19 --------------------
    ('Charlton', 'Everton'): {
        'Time': '15:00', 'Attendance': 20043
    },  # Source: 11v11 [2L4-L7], FBref [2L10-L16], Transfermarkt [2L27-L28]

    # -------------------- 13 January 2001 - Matchweek 23 --------------------
    ('West Ham', 'Sunderland'): {
        'Time': '15:00', 'Attendance': 26014
    },  # Source: Global Sports Archive [4L5-L10], FBref [4L11-L20]
}

# Fill the DataFrame
fill_from_dict(
    df=df,
    season='0001',
    data=match_data,
    value_col=['Time', 'Attendance'],
    inplace=True
)

In [40]:
missing_report(df,"0001")

XGHome    380
XGAway    380
dtype: int64

In [42]:
df.to_csv("Data/Data8.csv", index=False)

---