In [1]:
import pandas as pd
import glob
import os
from pathlib import Path

pd.set_option('display.max_columns', None)

In [2]:
pd.read_csv("RawData/season-2021.csv").head(10)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,2020-09-12,Fulham,Arsenal,0,3,A,0,1,A,C Kavanagh,5,13,2,6,12,12,2,3,2,2,0,0
1,2020-09-12,Crystal Palace,Southampton,1,0,H,1,0,H,J Moss,5,9,3,5,14,11,7,3,2,1,0,0
2,2020-09-12,Liverpool,Leeds,4,3,H,3,2,H,M Oliver,22,6,6,3,9,6,9,0,1,0,0,0
3,2020-09-12,West Ham,Newcastle,0,2,A,0,0,D,S Attwell,15,15,3,2,13,7,8,7,2,2,0,0
4,2020-09-13,West Brom,Leicester,0,3,A,0,0,D,A Taylor,7,13,1,7,12,9,2,5,1,1,0,0
5,2020-09-13,Tottenham,Everton,0,1,A,0,0,D,M Atkinson,9,15,5,4,15,7,5,3,1,0,0,0
6,2020-09-14,Brighton,Chelsea,1,3,A,0,1,A,C Pawson,13,10,3,5,8,13,4,3,1,0,0,0
7,2020-09-14,Sheffield United,Wolves,0,2,A,0,2,A,M Dean,9,11,2,4,13,7,12,5,2,1,0,0
8,2020-09-19,Everton,West Brom,5,2,H,2,1,H,M Dean,17,6,7,4,9,11,11,1,1,0,0,1
9,2020-09-19,Leeds,Fulham,4,3,H,2,1,H,A Taylor,10,14,7,6,13,18,5,3,1,2,0,0

In [3]:
folder_path = "RawData/"

In [4]:
all_files = glob.glob(os.path.join(folder_path, "*.csv"))
all_files.sort()
len(all_files)

33

In [11]:
df_list = []

for file in all_files:
    df = pd.read_csv(file)
    file_name = os.path.basename(file).replace('.csv', '')
    df['Season'] = file_name  
    df_list.append(df)
    print(f"Read: {file_name}  |  Records: {len(df)}")

df = pd.concat(df_list, ignore_index=True)

Read: season-0001  |  Records: 380
Read: season-0102  |  Records: 380
Read: season-0203  |  Records: 380
Read: season-0304  |  Records: 380
Read: season-0405  |  Records: 380
Read: season-0506  |  Records: 380
Read: season-0607  |  Records: 380
Read: season-0708  |  Records: 380
Read: season-0809  |  Records: 380
Read: season-0910  |  Records: 380
Read: season-1011  |  Records: 380
Read: season-1112  |  Records: 380
Read: season-1213  |  Records: 380
Read: season-1314  |  Records: 380
Read: season-1415  |  Records: 380
Read: season-1516  |  Records: 380
Read: season-1617  |  Records: 380
Read: season-1718  |  Records: 380
Read: season-1819  |  Records: 380
Read: season-1920  |  Records: 380
Read: season-2021  |  Records: 380
Read: season-2122  |  Records: 380
Read: season-2223  |  Records: 380
Read: season-2324  |  Records: 380
Read: season-2425  |  Records: 380
Read: season-2526  |  Records: 380
Read: season-9394  |  Records: 462
Read: season-9495  |  Records: 462
Read: season-9596  |  Records: 380
Read: season-9697  |  Records: 380
Read: season-9798  |  Records: 380
Read: season-9899  |  Records: 380
Read: season-9900  |  Records: 380

In [12]:
pd.read_csv("RawData/season-9394.csv")['HomeTeam'].nunique(), pd.read_csv("RawData/season-9495.csv")['HomeTeam'].nunique()

(22, 22)

In [13]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')
df = df.sort_values(by='Date').reset_index(drop=True)

C:\Users\Reza\AppData\Local\Temp\ipykernel_10388\2894939067.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

In [14]:
len(df) == (((len(all_files) - 2) * 380) + (2 * 462))

True

In [15]:
len(df.columns)

23

In [16]:
df['Date'].min(), df['Date'].max()

(Timestamp('1993-08-14 00:00:00'), Timestamp('2026-05-24 00:00:00'))

In [18]:
df.columns

Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG',
       'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC',
       'HY', 'AY', 'HR', 'AR', 'Season'],
      dtype='object')

In [17]:
df.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Season
0,1993-08-14,West Ham,Wimbledon,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,season-9394
1,1993-08-14,Southampton,Everton,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,season-9394
2,1993-08-14,Sheffield United,Swindon,3,1,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,season-9394
3,1993-08-14,Oldham,Ipswich,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,season-9394
4,1993-08-14,Newcastle,Tottenham,0,1,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,season-9394

In [19]:
df.tail()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Season
12699,2026-05-24,Crystal Palace,Arsenal,1,2,A,0.0,1.0,A,F Hallam,8.0,17.0,3.0,7.0,9.0,12.0,3.0,4.0,0.0,1.0,0.0,0.0,season-2526
12700,2026-05-24,Burnley,Wolves,1,1,D,0.0,1.0,A,A Kitchen,16.0,16.0,8.0,4.0,10.0,11.0,7.0,7.0,2.0,2.0,0.0,0.0,season-2526
12701,2026-05-24,Brighton,Man United,0,3,A,0.0,2.0,A,S Barrott,13.0,11.0,2.0,7.0,11.0,8.0,0.0,3.0,0.0,1.0,0.0,0.0,season-2526
12702,2026-05-24,Fulham,Newcastle,2,0,H,1.0,0.0,H,R Jones,21.0,7.0,6.0,2.0,13.0,6.0,6.0,6.0,2.0,2.0,0.0,0.0,season-2526
12703,2026-05-24,Tottenham,Everton,1,0,H,1.0,0.0,H,M Oliver,21.0,8.0,6.0,3.0,15.0,12.0,6.0,2.0,5.0,3.0,0.0,1.0,season-2526

In [20]:
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df.tail()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Season,Year,Month,Day
12699,2026-05-24,Crystal Palace,Arsenal,1,2,A,0.0,1.0,A,F Hallam,8.0,17.0,3.0,7.0,9.0,12.0,3.0,4.0,0.0,1.0,0.0,0.0,season-2526,2026,5,24
12700,2026-05-24,Burnley,Wolves,1,1,D,0.0,1.0,A,A Kitchen,16.0,16.0,8.0,4.0,10.0,11.0,7.0,7.0,2.0,2.0,0.0,0.0,season-2526,2026,5,24
12701,2026-05-24,Brighton,Man United,0,3,A,0.0,2.0,A,S Barrott,13.0,11.0,2.0,7.0,11.0,8.0,0.0,3.0,0.0,1.0,0.0,0.0,season-2526,2026,5,24
12702,2026-05-24,Fulham,Newcastle,2,0,H,1.0,0.0,H,R Jones,21.0,7.0,6.0,2.0,13.0,6.0,6.0,6.0,2.0,2.0,0.0,0.0,season-2526,2026,5,24
12703,2026-05-24,Tottenham,Everton,1,0,H,1.0,0.0,H,M Oliver,21.0,8.0,6.0,3.0,15.0,12.0,6.0,2.0,5.0,3.0,0.0,1.0,season-2526,2026,5,24

In [21]:
new_order = ['Year', 'Month', 'Day'] + [col for col in df.columns if col not in ['Year', 'Month', 'Day', 'Date']]

df = df[new_order]

df.tail()

,Year,Month,Day,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Season
12699,2026,5,24,Crystal Palace,Arsenal,1,2,A,0.0,1.0,A,F Hallam,8.0,17.0,3.0,7.0,9.0,12.0,3.0,4.0,0.0,1.0,0.0,0.0,season-2526
12700,2026,5,24,Burnley,Wolves,1,1,D,0.0,1.0,A,A Kitchen,16.0,16.0,8.0,4.0,10.0,11.0,7.0,7.0,2.0,2.0,0.0,0.0,season-2526
12701,2026,5,24,Brighton,Man United,0,3,A,0.0,2.0,A,S Barrott,13.0,11.0,2.0,7.0,11.0,8.0,0.0,3.0,0.0,1.0,0.0,0.0,season-2526
12702,2026,5,24,Fulham,Newcastle,2,0,H,1.0,0.0,H,R Jones,21.0,7.0,6.0,2.0,13.0,6.0,6.0,6.0,2.0,2.0,0.0,0.0,season-2526
12703,2026,5,24,Tottenham,Everton,1,0,H,1.0,0.0,H,M Oliver,21.0,8.0,6.0,3.0,15.0,12.0,6.0,2.0,5.0,3.0,0.0,1.0,season-2526

In [28]:
clubs = df['HomeTeam'].unique()
clubs

array(['West Ham', 'Southampton', 'Sheffield United', 'Oldham',
       'Newcastle', 'Arsenal', 'Liverpool', 'Chelsea', 'Aston Villa',
       'Man City', 'Norwich', 'Tottenham', 'Ipswich', 'Leeds',
       'Wimbledon', 'Everton', 'Blackburn', 'Coventry', 'Man United',
       'QPR', 'Sheffield Weds', 'Swindon', 'Crystal Palace', 'Leicester',
       "Nott'm Forest", 'Bolton', 'Middlesbrough', 'Sunderland', 'Derby',
       'Barnsley', 'Charlton', 'Watford', 'Bradford', 'Fulham',
       'West Brom', 'Birmingham', 'Portsmouth', 'Wolves', 'Wigan',
       'Reading', 'Hull', 'Stoke', 'Burnley', 'Blackpool', 'Swansea',
       'Cardiff', 'Bournemouth', 'Brighton', 'Huddersfield', 'Brentford',
       'Luton'], dtype=object)

In [23]:
df[ 
    [
        'HTHG',
        'HTAG',
        'HS',
        'AS',
        'HST',
        'AST',
        'HF',
        'AF',
        'HC',
        'AC',
        'HY',
        'AY',
        'HR',
        'AR'
    ]
].describe()

,HTHG,HTAG,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
count,11780.000000,11780.00000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000,9880.000000
mean,0.691341,0.51129,13.620648,10.817409,5.923583,4.663563,11.261032,11.743421,6.012551,4.763968,1.473279,1.800202,0.062146,0.084312
std,0.838506,0.73177,5.333120,4.695642,3.245798,2.732529,3.734316,3.904293,3.097538,2.751870,1.217718,1.291253,0.252899,0.288591
min,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.00000,10.000000,7.000000,4.000000,3.000000,9.000000,9.000000,4.000000,3.000000,1.000000,1.000000,0.000000,0.000000
50%,0.000000,0.00000,13.000000,10.000000,5.000000,4.000000,11.000000,11.000000,6.000000,4.000000,1.000000,2.000000,0.000000,0.000000
75%,1.000000,1.00000,17.000000,14.000000,8.000000,6.000000,14.000000,14.000000,8.000000,6.000000,2.000000,3.000000,0.000000,0.000000
max,5.000000,5.00000,43.000000,37.000000,24.000000,20.000000,33.000000,29.000000,20.000000,19.000000,7.000000,9.000000,3.000000,2.000000

In [38]:
df[['HTHG', 'HTAG', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']] = df[['HTHG', 'HTAG', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']].astype('Int64')

In [32]:
pd.DataFrame(clubs).to_csv("clubs.csv", index=False)

In [33]:
df['Season'] = df['Season'].str.extract(r'(\d+)')

In [39]:
df.tail()

,Year,Month,Day,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Season
12699,2026,5,24,Crystal Palace,Arsenal,1,2,A,0,1,A,F Hallam,8,17,3,7,9,12,3,4,0,1,0,0,2526
12700,2026,5,24,Burnley,Wolves,1,1,D,0,1,A,A Kitchen,16,16,8,4,10,11,7,7,2,2,0,0,2526
12701,2026,5,24,Brighton,Man United,0,3,A,0,2,A,S Barrott,13,11,2,7,11,8,0,3,0,1,0,0,2526
12702,2026,5,24,Fulham,Newcastle,2,0,H,1,0,H,R Jones,21,7,6,2,13,6,6,6,2,2,0,0,2526
12703,2026,5,24,Tottenham,Everton,1,0,H,1,0,H,M Oliver,21,8,6,3,15,12,6,2,5,3,0,1,2526

In [43]:
df.head()

,Year,Month,Day,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Season
0,1993,8,14,West Ham,Wimbledon,0,2,A,<NA>,<NA>,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9394
1,1993,8,14,Southampton,Everton,0,2,A,<NA>,<NA>,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9394
2,1993,8,14,Sheffield United,Swindon,3,1,H,<NA>,<NA>,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9394
3,1993,8,14,Oldham,Ipswich,0,3,A,<NA>,<NA>,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9394
4,1993,8,14,Newcastle,Tottenham,0,1,A,<NA>,<NA>,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9394

In [46]:
df.to_csv("Data/Data1.csv", index=False)

---